from _typeshed import Incomplete
from pyscf import __config__ as __config__
from pyscf.lib import logger as logger, misc as misc, numpy_helper as numpy_helper

INCORE_SIZE: Incomplete
BLOCK_SIZE: Incomplete

class DIIS:
    verbose: Incomplete
    stdout: Incomplete
    space: int
    min_space: int
    incore: Incomplete
    filename: Incomplete
    def __init__(self, dev=None, filename=None, incore=...) -> None: ...
    def push_err_vec(self, xerr) -> None: ...
    def push_vec(self, x) -> None: ...
    def get_err_vec(self, idx): ...
    def get_vec(self, idx): ...
    def get_num_vec(self): ...
    def update(self, x, xerr=None): ...
    def extrapolate(self, nd=None): ...
    def restore(self, filename, inplace: bool = True): ...
    to_gpu = misc.to_gpu

def restore(filename): ...
