class BasisNotFoundError(RuntimeError): ...
class PointGroupSymmetryError(RuntimeError): ...
class WfnSymmetryError(RuntimeError): ...
class LinearDependencyError(RuntimeError): ...
class DeprecationWarning(UserWarning): ...
