from _typeshed import Incomplete
from pyscf import __config__ as __config__
from pyscf.lib import logger as logger, misc as misc, numpy_helper as numpy_helper
from pyscf.lib.exceptions import LinearDependencyError as LinearDependencyError

SAFE_EIGH_LINDEP: Incomplete
DAVIDSON_LINDEP: Incomplete
DSOLVE_LINDEP: Incomplete
MAX_MEMORY: Incomplete
SORT_EIG_BY_SIMILARITY: Incomplete
PROJECT_OUT_CONV_EIGS: Incomplete
FOLLOW_STATE: Incomplete

def safe_eigh(h, s, lindep=...): ...
def eigh_by_blocks(h, s=None, labels=None): ...
def davidson(aop, x0, precond, tol: float = 1e-12, max_cycle: int = 50, max_space: int = 12, lindep=..., max_memory=..., dot=..., callback=None, nroots: int = 1, lessio: bool = False, pick=None, verbose=..., follow_state=...): ...
def davidson1(aop, x0, precond, tol: float = 1e-12, max_cycle: int = 50, max_space: int = 12, lindep=..., max_memory=..., dot=..., callback=None, nroots: int = 1, lessio: bool = False, pick=None, verbose=..., follow_state=..., tol_residual=None, fill_heff=...): ...
def make_diag_precond(diag, level_shift: float = 0.001): ...
def eigh(a, *args, **kwargs): ...
dsyev = eigh

def pick_real_eigs(w, v, nroots, envs): ...
def eig(aop, x0, precond, tol: float = 1e-12, max_cycle: int = 50, max_space: int = 20, lindep=..., max_memory=..., dot=..., callback=None, nroots: int = 1, lessio: bool = False, left: bool = False, pick=..., verbose=..., follow_state=...): ...
davidson_nosym = eig

def davidson_nosym1(aop, x0, precond, tol: float = 1e-12, max_cycle: int = 50, max_space: int = 20, lindep=..., max_memory=..., dot=..., callback=None, nroots: int = 1, lessio: bool = False, left: bool = False, pick=..., verbose=..., follow_state=..., tol_residual=None, fill_heff=...): ...
def dgeev(abop, x0, precond, type: int = 1, tol: float = 1e-12, max_cycle: int = 50, max_space: int = 12, lindep=..., max_memory=..., dot=..., callback=None, nroots: int = 1, lessio: bool = False, verbose=...): ...
def dgeev1(abop, x0, precond, type: int = 1, tol: float = 1e-12, max_cycle: int = 50, max_space: int = 12, lindep=..., max_memory=..., dot=..., callback=None, nroots: int = 1, lessio: bool = False, verbose=..., tol_residual=None): ...
def krylov(aop, b, x0=None, tol: float = 1e-10, max_cycle: int = 30, dot=..., lindep=..., callback=None, hermi: bool = False, max_memory=..., verbose=...): ...
def solve(aop, b, precond=None, tol: float = 1e-12, max_cycle: int = 60, dot=..., lindep=..., verbose: int = 0, tol_residual=None): ...
dsolve = solve

def cho_solve(a, b, strict_sym_pos: bool = True): ...
LinearDependenceError = LinearDependencyError

class _Xlist(list):
    scr_h5: Incomplete
    index: Incomplete
    def __init__(self) -> None: ...
    def __getitem__(self, n): ...
    def __iter__(self): ...
    def append(self, x) -> None: ...
    def extend(self, x) -> None: ...
    def __setitem__(self, n, x) -> None: ...
    def __len__(self) -> int: ...
    def pop(self, index) -> None: ...
