import time
from _typeshed import Incomplete

process_clock = time.process_time
perf_counter = time.perf_counter
DEBUG4: Incomplete
DEBUG3: Incomplete
DEBUG2: Incomplete
DEBUG1: Incomplete
DEBUG: Incomplete
INFO: Incomplete
NOTE: Incomplete
NOTICE = NOTE
WARN: Incomplete
WARNING = WARN
ERR: Incomplete
ERROR = ERR
QUIET: Incomplete
CRIT: Incomplete
ALERT: Incomplete
PANIC: Incomplete
TIMER_LEVEL: Incomplete

def flush(rec, msg, *args) -> None: ...
def log(rec, msg, *args) -> None: ...
def error(rec, msg, *args) -> None: ...
def warn(rec, msg, *args) -> None: ...
def info(rec, msg, *args) -> None: ...
def note(rec, msg, *args) -> None: ...
def debug(rec, msg, *args) -> None: ...
def debug1(rec, msg, *args) -> None: ...
def debug2(rec, msg, *args) -> None: ...
def debug3(rec, msg, *args) -> None: ...
def debug4(rec, msg, *args) -> None: ...
def stdout(rec, msg, *args) -> None: ...
def timer(rec, msg, cpu0=None, wall0=None): ...
def timer_debug1(rec, msg, cpu0=None, wall0=None): ...
def init_timer(): ...

class Logger:
    stdout: Incomplete
    verbose: Incomplete
    def __init__(self, stdout=..., verbose=...) -> None: ...
    def init_timer(self): ...
    log = log
    error = error
    warn = warn
    note = note
    info = info
    debug = debug
    debug1 = debug1
    debug2 = debug2
    debug3 = debug3
    debug4 = debug4
    timer = timer
    timer_debug1 = timer_debug1

def new_logger(rec=None, verbose=None): ...
