import h5py
import types
from _typeshed import Incomplete
from collections.abc import Generator
from math import comb as comb
from multiprocessing import Process
from pyscf import __config__ as __config__
from threading import Thread

so_file: Incomplete
c_double_p: Incomplete
c_int_p: Incomplete
c_null_ptr: Incomplete

def load_library(libname): ...

CLOCK_TICKS: Incomplete
PAGESIZE: Incomplete

def current_memory(): ...
def num_threads(n=None): ...

class with_omp_threads:
    nthreads: Incomplete
    sys_threads: Incomplete
    def __init__(self, nthreads=None) -> None: ...
    def __enter__(self): ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...

class with_multiproc_nproc:
    nproc: Incomplete
    sys_threads: Incomplete
    def __init__(self, nproc: int = 1) -> None: ...
    def __enter__(self): ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...

def c_int_arr(m): ...
def f_int_arr(m): ...
def c_double_arr(m): ...
def f_double_arr(m): ...
def member(test, x, lst): ...
def remove_dup(test, lst, from_end: bool = False): ...
def remove_if(test, lst): ...
def find_if(test, lst): ...
def arg_first_match(test, lst): ...
def flatten(lst): ...
def prange(start, end, step) -> Generator[Incomplete]: ...
def prange_tril(start, stop, blocksize): ...
def prange_split(n_total, n_sections): ...
izip = zip

def map_with_prefetch(func, *iterables) -> Generator[Incomplete]: ...
def index_tril_to_pair(ij): ...
def tril_product(*iterables, **kwds) -> Generator[Incomplete]: ...
def square_mat_in_trilu_indices(n): ...

class capture_stdout:
    old_stdout_fileno: Incomplete
    bak_stdout_fd: Incomplete
    ftmp: Incomplete
    def __enter__(self): ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
    def read(self): ...
ctypes_stdout = capture_stdout

class quite_run:
    old_stdout_fileno: Incomplete
    bak_stdout_fd: Incomplete
    fnull: Incomplete
    def __enter__(self) -> None: ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...

class omnimethod:
    func: Incomplete
    def __init__(self, func) -> None: ...
    def __get__(self, instance, owner): ...

def view(obj, cls): ...
def generate_pickle_methods(excludes=(), reset_state: bool = False): ...

SANITY_CHECK: Incomplete

class StreamObject:
    verbose: int
    stdout: Incomplete
    def kernel(self, *args, **kwargs) -> None: ...
    def pre_kernel(self, envs) -> None: ...
    def post_kernel(self, envs) -> None: ...
    def run(self, *args, **kwargs): ...
    def set(self, *args, **kwargs): ...
    __call__ = set
    def apply(self, fn, *args, **kwargs): ...
    def check_sanity(self): ...
    view = view
    def copy(self): ...
    def reset(self) -> None: ...

def check_sanity(obj, keysref, stdout=...): ...
def with_doc(doc): ...
def alias(fn, alias_name=None): ...
def module_method(fn, absences=None): ...
def class_as_method(cls): ...
def invalid_method(name): ...
def make_class(bases, name=None, attrs=None): ...
def set_class(obj, bases, name=None, attrs=None): ...
def drop_class(cls, base_cls, name_mixin=None): ...
def replace_class(cls, old_cls, new_cls): ...
def overwrite_mro(obj, mro) -> None: ...

class ProcessWithReturnValue(Process):
    def __init__(self, group=None, target=None, name=None, args=(), kwargs=None) -> None: ...
    def join(self): ...
    get = join

class ProcessRuntimeError(RuntimeError): ...

class ThreadWithReturnValue(Thread):
    def __init__(self, group=None, target=None, name=None, args=(), kwargs=None) -> None: ...
    def join(self): ...
    get = join

class ThreadWithTraceBack(Thread):
    def __init__(self, group=None, target=None, name=None, args=(), kwargs=None) -> None: ...
    def join(self) -> None: ...

class ThreadRuntimeError(RuntimeError): ...

def background_thread(func, *args, **kwargs): ...
def background_process(func, *args, **kwargs): ...
bg = background_thread
background = background_thread
bg_thread = background_thread
bp = background_process
bg_process = background_process
ASYNC_IO: Incomplete

class call_in_background:
    fns: Incomplete
    executor: Incomplete
    handlers: Incomplete
    sync: Incomplete
    def __init__(self, *fns, **kwargs) -> None: ...
    def __enter__(self): ...
    def __enter__(self): ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...

class H5FileWrap(h5py.File):
    def __init__(self, filename, mode, *args, **kwargs) -> None: ...
    def __del__(self) -> None: ...

class H5TmpFile(H5FileWrap):
    delete_on_close: bool
    def __init__(self, filename=None, mode: str = 'a', prefix: str = '', suffix: str = '', dir=None, *args, **kwargs) -> None: ...
    def close(self) -> None: ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...

def fingerprint(a): ...
finger = fingerprint
fp = fingerprint

def ndpointer(*args, **kwargs): ...

class SinglePointScanner:
    __name_mixin__: str
    def undo_scanner(self): ...

class GradScanner:
    __name_mixin__: str
    def undo_scanner(self): ...
    base: Incomplete
    def __init__(self, g) -> None: ...
    @property
    def e_tot(self): ...
    @e_tot.setter
    def e_tot(self, x) -> None: ...
    @property
    def converged(self): ...

class temporary_env:
    obj: Incomplete
    env_bak: Incomplete
    env_new: Incomplete
    def __init__(self, obj, **kwargs) -> None: ...
    def __enter__(self): ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...

class light_speed(temporary_env):
    c: Incomplete
    def __init__(self, c) -> None: ...
    def __enter__(self): ...

class h5filewrite_options(temporary_env):
    def __init__(self, **kwargs) -> None: ...

def repo_info(repo_path): ...
def git_info(repo_path): ...
def format_sys_info(): ...
def isinteger(obj): ...
def issequence(obj): ...
def isintsequence(obj): ...

class _OmniObject:
    verbose: int
    max_memory: Incomplete
    stdout: Incomplete
    def __init__(self, default_factory=None) -> None: ...
    def __getattr__(self, key): ...

omniobj: Incomplete

def to_gpu(method, out=None): ...
