import numpy
from _typeshed import Incomplete
from numpy import asarray as asarray
from pyscf import tblis_einsum as tblis_einsum
from pyscf.lib import misc as misc

EINSUM_MAX_SIZE: Incomplete
EINSUM_BACKEND: Incomplete
BLOCK_DIM: int
PLAIN: int
HERMITIAN: int
ANTIHERMI: int
SYMMETRIC: int
LeviCivita: Incomplete
PauliMatrices: Incomplete

def contract(subscripts, A, B, alpha: int = 1, beta: int = 0, out=None, **kwargs): ...
def einsum(scripts, *tensors, **kwargs): ...
def pack_tril(mat, axis: int = -1, out=None): ...
def unpack_tril(tril, filltriu=..., axis: int = -1, out=None): ...
def unpack_row(tril, row_id): ...
def hermi_triu(mat, hermi=..., inplace: bool = True): ...

LINEAR_DEP_THRESHOLD: float

def solve_lineq_by_SVD(a, b): ...
def take_2d(a, idx, idy, out=None): ...
def takebak_2d(out, a, idx, idy, thread_safe: bool = True): ...
def inplace_transpose_scale(a, alpha: float = 1.0): ...
def transpose(a, axes=None, inplace: bool = False, out=None): ...
def transpose_sum(a, inplace: bool = False, out=None): ...
def hermi_sum(a, axes=None, hermi=..., inplace: bool = False, out=None): ...
def ddot(a, b, alpha: int = 1, c=None, beta: int = 0): ...
def zdot(a, b, alpha: int = 1, c=None, beta: int = 0): ...
def zdotNN(aR, aI, bR, bI, alpha: int = 1, cR=None, cI=None, beta: int = 0): ...
def zdotCN(aR, aI, bR, bI, alpha: int = 1, cR=None, cI=None, beta: int = 0): ...
def zdotNC(aR, aI, bR, bI, alpha: int = 1, cR=None, cI=None, beta: int = 0): ...
def dot(a, b, alpha: int = 1, c=None, beta: int = 0): ...

Ylm: Incomplete

def frompointer(pointer, count, dtype=...): ...
def leading_dimension_order(a): ...

norm: Incomplete

def cond(x, p=None): ...
def cartesian_prod(arrays, out=None): ...
def direct_sum(subscripts, *operands): ...
def condense(opname, a, loc_x, loc_y=None): ...
def expm(a): ...
def omatcopy(a, out=None): ...
def zeros(shape, dtype=..., order: str = 'C'): ...
def entrywise_mul(a, b, out=None): ...
def broadcast_mul(a, b, out=None): ...
def ndarray_pointer_2d(array): ...

class NPArrayWithTag(numpy.ndarray):
    def __reduce__(self): ...
    def __array_wrap__(self, out, context=None, return_scalar: bool = False): ...

def tag_array(a, **kwargs): ...
def split_reshape(a, shapes): ...
def locs_to_indices(locs, segement_list): ...
def cleanse(a, axis: int = 0, tol: int = 0): ...
def base_repr_int(number, base, ndigits=None): ...
def inv_base_repr_int(x, base): ...
def isin_1d(v, vs, return_index: bool = False): ...
def groupby(labels, a, op: str = 'argmin'): ...
def stack_with_padding(arrays): ...
