from pyscf.pbc import scf as scf
from pyscf.pbc.tdscf import krhf as krhf, krks as krks, kuhf as kuhf, kuks as kuks, rhf as rhf, rks as rks, uhf as uhf, uks as uks
from _typeshed import Incomplete
from pyscf.pbc.scf.khf import KRHF
from pyscf.pbc.scf.kuhf import KUHF
from typing import Union

def TDHF(mf): ...
def TDA(mf): ...
def TDDFT(mf): ...
def KTDHF(mf: Union[KRHF, KUHF]) -> Union[Incomplete, Incomplete]: ...
def KTDA(mf: Union[KRHF, KUHF]) -> Union[Incomplete, Incomplete]: ...
def KTDDFT(mf): ...
KTD = KTDDFT
