from pyscf.pbc import scf as scf
from pyscf.pbc.tdscf import krhf as krhf, krks as krks, kuhf as kuhf, kuks as kuks, rhf as rhf, rks as rks, uhf as uhf, uks as uks

def TDHF(mf): ...
def TDA(mf): ...
def TDDFT(mf): ...
def KTDHF(mf): ...
def KTDA(mf): ...
def KTDDFT(mf): ...
KTD = KTDDFT
