from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.lib.exceptions import PointGroupSymmetryError as PointGroupSymmetryError
from pyscf.symm import basis as basis, param as param
from numpy import ndarray
from pyscf.gto.mole import Mole
from pyscf.lib.numpy_helper import NPArrayWithTag
from typing import List, Optional, Union

MULTI_IRREPS: int

def label_orb_symm(mol: Mole, irrep_name: List[Union[str, int]], symm_orb: List[ndarray], mo: Union[ndarray, NPArrayWithTag], s: Optional[ndarray]=None, check: bool=..., tol: float=...) -> ndarray: ...
def symmetrize_orb(mol: Mole, mo: Union[ndarray, NPArrayWithTag], orbsym: None=None, s: None=None, check: bool=...) -> Union[ndarray, NPArrayWithTag]: ...
def find_symmetric_mo(moso: ndarray, ovlpso: ndarray, thr: float = 1e-08) -> ndarray: ...
def symmetrize_space(mol: Mole, mo: ndarray, s: None=None, check: bool=..., tol: float=..., clean: bool=...) -> ndarray: ...
def symmetrize_multidim(mol, mo, s=None, check=..., tol=..., keep_phase=...): ...
def std_symb(gpname: str) -> str: ...
def irrep_name2id(gpname, symb): ...
def irrep_id2name(gpname: str, irrep_id: int) -> str: ...
def irrep_name(pgname, irrep_id) -> None: ...
def route(target: int, nelec: int, orbsym: List[int]) -> List[int]: ...
def eigh(h, orbsym): ...
def direct_prod(orbsym1, orbsym2, groupname: str = 'D2h'): ...
