from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.lib.exceptions import PointGroupSymmetryError as PointGroupSymmetryError
from pyscf.symm import basis as basis, param as param

MULTI_IRREPS: int

def label_orb_symm(mol, irrep_name, symm_orb, mo, s=None, check=..., tol=...): ...
def symmetrize_orb(mol, mo, orbsym=None, s=None, check=...): ...
def find_symmetric_mo(moso, ovlpso, thr: float = 1e-08): ...
def symmetrize_space(mol, mo, s=None, check=..., tol=..., clean=...): ...
def symmetrize_multidim(mol, mo, s=None, check=..., tol=..., keep_phase=...): ...
def std_symb(gpname): ...
def irrep_name2id(gpname, symb): ...
def irrep_id2name(gpname, irrep_id): ...
def irrep_name(pgname, irrep_id) -> None: ...
def route(target, nelec, orbsym): ...
def eigh(h, orbsym): ...
def direct_prod(orbsym1, orbsym2, groupname: str = 'D2h'): ...
