from pyscf.symm import sph as sph
from numpy import float64, ndarray
from typing import Tuple, Union

def Dmatrix(l: int, alpha: Union[float, float64], beta: Union[float, float64], gamma: Union[float, float64], reorder_p: bool = False) -> ndarray: ...
def dmatrix(l: int, beta: Union[float, float64], reorder_p: bool = False) -> ndarray: ...
def get_euler_angles(c1: ndarray, c2: ndarray) -> Tuple[float64, float64, float64]: ...
