from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__
from pyscf.gto import mole as mole
from pyscf.lib import logger as logger, norm as norm
from pyscf.lib.exceptions import PointGroupSymmetryError as PointGroupSymmetryError
from pyscf.symm.param import OPERATOR_TABLE as OPERATOR_TABLE
from numpy import bool, float64, int64, ndarray
from typing import Any, Dict, Iterator, List, Optional, Tuple, Union

TOLERANCE: Incomplete

def parallel_vectors(v1: ndarray, v2: ndarray, tol: float=...) -> bool: ...
def argsort_coords(coords: ndarray, decimals: None=None, tol: float = 0.05) -> ndarray: ...
def sort_coords(coords: ndarray, decimals: None=None, tol: float = 0.05) -> ndarray: ...
def rotation_mat(vec: Union[ndarray, Tuple[int, int, int]], theta: Union[float, float64]) -> ndarray: ...
def householder(vec: ndarray) -> ndarray: ...
def closest_axes(axes: ndarray, ref: ndarray) -> Tuple[int64, int64, int64]: ...
def alias_axes(axes: ndarray, ref: ndarray) -> ndarray: ...
def detect_symm(atoms: List[Any], basis: Optional[Union[Dict[str, str], Dict[str, List[List[Union[int, List[float]]]]]]]=None, verbose: int=...) -> Tuple[str, ndarray, ndarray]: ...
def get_subgroup(gpname: str, axes: ndarray) -> Tuple[str, ndarray]: ...
subgroup = get_subgroup

def as_subgroup(topgroup: str, axes: ndarray, subgroup: Optional[str]=None) -> Tuple[str, ndarray]: ...
def symm_ops(gpname: str, axes: None=None) -> Dict[str, Union[ndarray, int]]: ...
def symm_identical_atoms(gpname: str, atoms: List[Union[Tuple[str, List[float]], List[Union[str, ndarray]], List[Union[str, Tuple[int, int, int]]]]]) -> List[List[Union[int64, int]]]: ...
def check_symm(gpname: str, atoms: List[Union[Tuple[str, List[float]], List[Union[str, ndarray]], List[Union[str, Tuple[int, int, int]]]]], basis: Optional[Union[Dict[str, str], Dict[str, List[List[Union[int, List[float]]]]]]]=None) -> bool: ...
check_given_symm = check_symm

def shift_atom(atoms: List[List[Any]], orig: ndarray, axis: ndarray) -> List[List[Union[str, ndarray]]]: ...
def is_identical_geometry(coords1: ndarray, coords2: ndarray, weights: ndarray): ...
def casimir_tensors(r: ndarray, q: ndarray, order: int = 1) -> ndarray: ...

class RotationAxisNotFound(PointGroupSymmetryError): ...

class SymmSys:
    atomtypes: Incomplete
    charge_center: Incomplete
    atoms: Incomplete
    group_atoms_by_distance: Incomplete
    def __init__(self, atoms: List[Any], basis: Optional[Union[Dict[str, str], Dict[str, List[List[Union[int, List[float]]]]]]]=None) -> None: ...
    @property
    def atom_coords(self) -> ndarray: ...
    def cartesian_tensor(self, n: int) -> Tuple[ndarray, ndarray]: ...
    def symmetric_for(self, op: Union[ndarray, int]) -> Iterator[bool]: ...
    def has_icenter(self) -> bool: ...
    def has_rotation(self, axis: ndarray, n: Union[int64, int]) -> bool: ...
    def has_mirror(self, perp_vec: ndarray) -> bool: ...
    def has_improper_rotation(self, axis: ndarray, n: int64) -> bool: ...
    def search_possible_rotations(self, zaxis: Optional[ndarray]=None) -> List[Tuple[ndarray, int64]]: ...
    def search_c2x(self, zaxis: ndarray, n: int64) -> ndarray: ...
    def search_mirrorx(self, zaxis: Optional[ndarray], n: Union[int64, int]) -> ndarray: ...
    def search_c_highest(self, zaxis: Optional[ndarray]=None) -> Union[Tuple[ndarray, int64], Tuple[ndarray, int]]: ...
