from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__
from pyscf.gto import mole as mole
from pyscf.lib import logger as logger, norm as norm
from pyscf.lib.exceptions import PointGroupSymmetryError as PointGroupSymmetryError
from pyscf.symm.param import OPERATOR_TABLE as OPERATOR_TABLE

TOLERANCE: Incomplete

def parallel_vectors(v1, v2, tol=...): ...
def argsort_coords(coords, decimals=None, tol: float = 0.05): ...
def sort_coords(coords, decimals=None, tol: float = 0.05): ...
def rotation_mat(vec, theta): ...
def householder(vec): ...
def closest_axes(axes, ref): ...
def alias_axes(axes, ref): ...
def detect_symm(atoms, basis=None, verbose=...): ...
def get_subgroup(gpname, axes): ...
subgroup = get_subgroup

def as_subgroup(topgroup, axes, subgroup=None): ...
def symm_ops(gpname, axes=None): ...
def symm_identical_atoms(gpname, atoms): ...
def check_symm(gpname, atoms, basis=None): ...
check_given_symm = check_symm

def shift_atom(atoms, orig, axis): ...
def is_identical_geometry(coords1, coords2, weights): ...
def casimir_tensors(r, q, order: int = 1): ...

class RotationAxisNotFound(PointGroupSymmetryError): ...

class SymmSys:
    atomtypes: Incomplete
    charge_center: Incomplete
    atoms: Incomplete
    group_atoms_by_distance: Incomplete
    def __init__(self, atoms, basis=None) -> None: ...
    @property
    def atom_coords(self): ...
    def cartesian_tensor(self, n): ...
    def symmetric_for(self, op) -> Generator[Incomplete]: ...
    def has_icenter(self): ...
    def has_rotation(self, axis, n): ...
    def has_mirror(self, perp_vec): ...
    def has_improper_rotation(self, axis, n): ...
    def search_possible_rotations(self, zaxis=None): ...
    def search_c2x(self, zaxis, n): ...
    def search_mirrorx(self, zaxis, n): ...
    def search_c_highest(self, zaxis=None): ...
