from pyscf import symm as symm
from pyscf.data import elements as elements
from pyscf.lib import logger as logger, param as param
from pyscf.lo.orth import vec_lowdin as vec_lowdin

def sph_mval(label): ...
def basis_info(ao_labels): ...
def msym_basis(ao_labels, msym_atoms): ...
def msym_atoms(_atom): ...
def log_symmetry_info(mol) -> None: ...
def d2h_compat_irrep_id(mol, msym_symm_orb): ...
def gen_mol_msym(mol, tol: float = 1e-14, verbose: bool = True): ...
def symmetrize_space_pyscf(mol, mo, s=None, orthonormalize: bool = False): ...
def symmetrize_space_libmsym(mol, mo, tol: float = 1e-14, check: bool = True, orthonormalize: bool = False): ...
symmetrize_space = symmetrize_space_pyscf
