from pyscf.symm.cg import cg_spin as cg_spin
from numpy import ndarray
from pyscf.gto.mole import Mole
from typing import List, Tuple

def real_sph_vec(r: ndarray, lmax: int, reorder_p: bool = False) -> List[ndarray]: ...
def multipoles(r: ndarray, lmax: int, reorder_dipole: bool = True) -> List[ndarray]: ...
def sph_pure2real(l: int, reorder_p: bool = True) -> ndarray: ...
def sph_real2pure(l: int, reorder_p: bool = True) -> ndarray: ...
def sph2spinor(l: int, reorder_p: bool = True) -> Tuple[ndarray, ndarray]: ...
real2spinor = sph2spinor

def sph2spinor_coeff(mol: Mole) -> ndarray: ...
real2spinor_whole = sph2spinor_coeff

def cart2spinor(l): ...
