from pyscf.symm.cg import cg_spin as cg_spin

def real_sph_vec(r, lmax, reorder_p: bool = False): ...
def multipoles(r, lmax, reorder_dipole: bool = True): ...
def sph_pure2real(l, reorder_p: bool = True): ...
def sph_real2pure(l, reorder_p: bool = True): ...
def sph2spinor(l, reorder_p: bool = True): ...
real2spinor = sph2spinor

def sph2spinor_coeff(mol): ...
real2spinor_whole = sph2spinor_coeff

def cart2spinor(l): ...
