from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, gto as gto
from pyscf.data import elements as elements
from pyscf.df.autoaux import autoabs as autoabs, autoaux as autoaux
from pyscf.lib import logger as logger
from pyscf.lib.exceptions import BasisNotFoundError as BasisNotFoundError

DFBASIS: Incomplete
ETB_BETA: Incomplete
FIRST_ETB_ELEMENT: Incomplete
USE_VERSION_26_AUXBASIS: bool
DEFAULT_AUXBASIS: Incomplete

class load(ao2mo.load):
    def __init__(self, eri, dataname: str = 'j3c') -> None: ...

def aug_etb_for_dfbasis(mol, dfbasis=..., beta=..., start_at=...): ...
def aug_etb(mol, beta=...): ...
def make_auxbasis(mol, *, xc: str = 'HF', mp2fit: bool = False): ...
def make_auxmol(mol, auxbasis=None): ...
def bse_predefined_auxbasis(mol, basis, xc: str = 'HF', mp2fit: bool = False): ...
def predefined_auxbasis(mol, basis, xc: str = 'HF', mp2fit: bool = False): ...
