import contextlib
from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, ao2mo as ao2mo, lib as lib
from pyscf.ao2mo.incore import iden_coeffs as iden_coeffs
from pyscf.df import addons as addons, df_jk as df_jk, incore as incore, outcore as outcore, r_incore as r_incore
from pyscf.lib import logger as logger

class DF(lib.StreamObject):
    blockdim: Incomplete
    mol: Incomplete
    stdout: Incomplete
    verbose: Incomplete
    max_memory: Incomplete
    auxmol: Incomplete
    def __init__(self, mol, auxbasis=None) -> None: ...
    @property
    def auxbasis(self): ...
    @auxbasis.setter
    def auxbasis(self, x) -> None: ...
    def dump_flags(self, verbose=None): ...
    def build(self): ...
    def kernel(self, *args, **kwargs): ...
    def reset(self, mol=None): ...
    def loop(self, blksize=None) -> Generator[Incomplete, None, Incomplete]: ...
    def prange(self, start, end, step) -> Generator[Incomplete]: ...
    def get_naoaux(self): ...
    def get_jk(self, dm, hermi: int = 1, with_j: bool = True, with_k: bool = True, direct_scf_tol=..., omega=None): ...
    def get_eri(self): ...
    get_ao_eri = get_eri
    def ao2mo(self, mo_coeffs, compact=...): ...
    get_mo_eri = ao2mo
    @contextlib.contextmanager
    def range_coulomb(self, omega) -> Generator[Incomplete]: ...
    to_gpu = lib.to_gpu
GDF = DF

class DF4C(DF):
    def build(self): ...
    def loop(self, blksize=None) -> Generator[Incomplete]: ...
    def get_jk(self, dm, hermi: int = 1, with_j: bool = True, with_k: bool = True, direct_scf_tol=..., omega=None): ...
    def get_eri(self) -> None: ...
    get_ao_eri = get_eri
    def ao2mo(self, mo_coeffs) -> None: ...
    get_mo_eri = ao2mo
GDF4C = DF4C
