import contextlib
from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, ao2mo as ao2mo, lib as lib
from pyscf.ao2mo.incore import iden_coeffs as iden_coeffs
from pyscf.df import addons as addons, df_jk as df_jk, incore as incore, outcore as outcore, r_incore as r_incore
from pyscf.lib import logger as logger
from numpy import ndarray
from pyscf.gto.mole import Mole
from pyscf.lib.numpy_helper import NPArrayWithTag
from typing import Iterator, Optional, Tuple, Union

class DF(lib.StreamObject):
    blockdim: Incomplete
    mol: Incomplete
    stdout: Incomplete
    verbose: Incomplete
    max_memory: Incomplete
    auxmol: Incomplete
    def __init__(self, mol: Mole, auxbasis: Optional[str]=None) -> None: ...
    @property
    def auxbasis(self): ...
    @auxbasis.setter
    def auxbasis(self, x) -> None: ...
    def dump_flags(self, verbose: None=None) -> "DF": ...
    def build(self) -> "DF": ...
    def kernel(self, *args, **kwargs) -> "DF": ...
    def reset(self, mol: Optional[Mole]=None) -> Union[DF4C, DF]: ...
    def loop(self, blksize: Optional[int]=None) -> Iterator[ndarray]: ...
    def prange(self, start: int, end: int, step: int) -> Iterator[Tuple[int, int]]: ...
    def get_naoaux(self) -> int: ...
    def get_jk(self, dm: Union[ndarray, NPArrayWithTag, Tuple[ndarray, ndarray]], hermi: int = 1, with_j: bool = True, with_k: bool = True, direct_scf_tol: float=..., omega: Optional[float]=None) -> Union[Tuple[ndarray, None], Tuple[int, ndarray], Tuple[ndarray, ndarray]]: ...
    def get_eri(self) -> ndarray: ...
    get_ao_eri = get_eri
    def ao2mo(self, mo_coeffs: Union[ndarray, Tuple[ndarray, ndarray, ndarray, ndarray]], compact: bool=...) -> ndarray: ...
    get_mo_eri = ao2mo
    @contextlib.contextmanager
    def range_coulomb(self, omega: float) -> Iterator[Union[DF4C, DF]]: ...
    to_gpu = lib.to_gpu
GDF = DF

class DF4C(DF):
    def build(self) -> "DF4C": ...
    def loop(self, blksize: None=None) -> Iterator[Tuple[ndarray, ndarray]]: ...
    def get_jk(self, dm: Union[ndarray, NPArrayWithTag], hermi: int = 1, with_j: bool = True, with_k: bool = True, direct_scf_tol: float=..., omega: Optional[float]=None) -> Tuple[ndarray, ndarray]: ...
    def get_eri(self) -> None: ...
    get_ao_eri = get_eri
    def ao2mo(self, mo_coeffs) -> None: ...
    get_mo_eri = ao2mo
GDF4C = DF4C
