from _typeshed import Incomplete
from pyscf import lib as lib, scf as scf
from pyscf.lib import logger as logger
from numpy import ndarray
from pyscf.df.df import DF4C
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.scf.hf import SCF
from typing import Optional, Tuple, Union

DEBUG: bool
libri: Incomplete

def density_fit(mf, auxbasis=None, with_df=None, only_dfj: bool = False): ...

class _DFHF:
    __name_mixin__: str
    only_dfj: Incomplete
    with_df: Incomplete
    direct_scf: Incomplete
    def __init__(self, mf: SCF, df: Optional[Union[Incomplete, DF4C]]=None, only_dfj: Optional[bool]=None) -> None: ...
    def undo_df(self): ...
    def reset(self, mol=None): ...
    def get_jk(self, mol=None, dm=None, hermi: int = 1, with_j: bool = True, with_k: bool = True, omega=None): ...
    @property
    def auxbasis(self): ...
    def nuc_grad_method(self): ...
    Gradients = nuc_grad_method
    def Hessian(self): ...
    def method_not_implemented(self, *args, **kwargs) -> None: ...
    NMR = method_not_implemented
    NSR = method_not_implemented
    Polarizability = method_not_implemented
    RotationalGTensor = method_not_implemented
    def MP2(self, frozen=None, auxbasis=None): ...
    CISD = method_not_implemented
    def CCSD(self, frozen=None, auxbasis=None): ...
    def CASCI(self, ncas, nelecas, auxbasis=None, ncore=None): ...
    def CASSCF(self, ncas, nelecas, auxbasis=None, ncore=None, frozen=None): ...
    def to_gpu(self): ...

def get_jk(dfobj: Union[Incomplete, Incomplete], dm: Union[ndarray, Tuple[ndarray, ndarray], NPArrayWithTag], hermi: int = 0, with_j: bool = True, with_k: bool = True, direct_scf_tol: float = 1e-13) -> Union[Tuple[int, ndarray], Tuple[ndarray, ndarray], Tuple[ndarray, None]]: ...
def get_j(dfobj: Incomplete, dm: Union[ndarray, NPArrayWithTag], hermi: int = 0, direct_scf_tol: float = 1e-13) -> ndarray: ...
def r_get_jk(dfobj: DF4C, dms: Union[ndarray, NPArrayWithTag], hermi: int = 0, with_j: bool = True, with_k: bool = True) -> Tuple[ndarray, ndarray]: ...
