from _typeshed import Incomplete
from pyscf import lib as lib, scf as scf
from pyscf.lib import logger as logger

DEBUG: bool
libri: Incomplete

def density_fit(mf, auxbasis=None, with_df=None, only_dfj: bool = False): ...

class _DFHF:
    __name_mixin__: str
    only_dfj: Incomplete
    with_df: Incomplete
    direct_scf: Incomplete
    def __init__(self, mf, df=None, only_dfj=None) -> None: ...
    def undo_df(self): ...
    def reset(self, mol=None): ...
    def get_jk(self, mol=None, dm=None, hermi: int = 1, with_j: bool = True, with_k: bool = True, omega=None): ...
    @property
    def auxbasis(self): ...
    def nuc_grad_method(self): ...
    Gradients = nuc_grad_method
    def Hessian(self): ...
    def method_not_implemented(self, *args, **kwargs) -> None: ...
    NMR = method_not_implemented
    NSR = method_not_implemented
    Polarizability = method_not_implemented
    RotationalGTensor = method_not_implemented
    def MP2(self, frozen=None, auxbasis=None): ...
    CISD = method_not_implemented
    def CCSD(self, frozen=None, auxbasis=None): ...
    def CASCI(self, ncas, nelecas, auxbasis=None, ncore=None): ...
    def CASSCF(self, ncas, nelecas, auxbasis=None, ncore=None, frozen=None): ...
    def to_gpu(self): ...

def get_jk(dfobj, dm, hermi: int = 0, with_j: bool = True, with_k: bool = True, direct_scf_tol: float = 1e-13): ...
def get_j(dfobj, dm, hermi: int = 0, direct_scf_tol: float = 1e-13): ...
def r_get_jk(dfobj, dms, hermi: int = 0, with_j: bool = True, with_k: bool = True): ...
