from _typeshed import Incomplete
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.df import addons as addons
from pyscf.gto.moleintor import getints as getints
from pyscf.lib import logger as logger

MAX_MEMORY: Incomplete
LINEAR_DEP_THR: Incomplete
format_aux_basis = addons.make_auxmol

def aux_e2(mol, auxmol_or_auxbasis, intor: str = 'int3c2e', aosym: str = 's1', comp=None, out=None, cintopt=None, shls_slice=None): ...
def aux_e1(mol, auxmol_or_auxbasis, intor: str = 'int3c2e', aosym: str = 's1', comp=None, out=None): ...
def fill_2c2e(mol, auxmol_or_auxbasis, intor: str = 'int2c2e', comp=None, hermi: int = 1, out=None): ...
def cholesky_eri(mol, auxbasis: str = 'weigend+etb', auxmol=None, int3c: str = 'int3c2e', aosym: str = 's2ij', int2c: str = 'int2c2e', comp: int = 1, max_memory=..., decompose_j2c: str = 'cd', lindep=..., verbose: int = 0, fauxe2=...): ...
def cholesky_eri_debug(mol, auxbasis: str = 'weigend+etb', auxmol=None, int3c: str = 'int3c2e', aosym: str = 's2ij', int2c: str = 'int2c2e', comp: int = 1, verbose: int = 0, fauxe2=...): ...
