from pyscf import gto as gto
from pyscf.df import incore as incore

def aux_e2(mol, auxmol, intor: str = 'int3c2e_spinor', aosym: str = 's1', comp=None, hermi: int = 0): ...
def aux_e1(mol, auxmol, intor: str = 'int3c2e_spinor', aosym: str = 's1', comp: int = 1, hermi: int = 0) -> None: ...
def cholesky_eri(mol, auxbasis: str = 'weigend+etb', auxmol=None, int3c: str = 'int3c2e_spinor', aosym: str = 's1', int2c: str = 'int2c2e_sph', comp: int = 1, verbose: int = 0): ...
