from pyscf.pbc import scf as scf
from pyscf.pbc.mp import kmp2 as kmp2, kmp2_ksymm as kmp2_ksymm, mp2 as mp2

def RMP2(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
MP2 = RMP2

def UMP2(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def GMP2(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def KRMP2(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
KMP2 = KRMP2
