from pyscf import lib as lib
from pyscf.lib import logger as logger
from pyscf.lib.parameters import LARGE_DENOM as LARGE_DENOM
from pyscf.pbc import scf as scf
from pyscf.pbc.lib import kpts_helper as kpts_helper
from pyscf.pbc.mp import kmp2 as kmp2

def kernel(mp, mo_energy, mo_coeff, verbose=...) -> None: ...
def padding_k_idx(mp, kind: str = 'split'): ...
def padded_mo_energy(mp, mo_energy): ...
def padded_mo_coeff(mp, mo_coeff): ...
def get_nocc(mp, per_kpoint: bool = False): ...
def get_nmo(mp, per_kpoint: bool = False): ...
def get_frozen_mask(mp): ...

class KUMP2(kmp2.KMP2):
    get_nocc = get_nocc
    get_nmo = get_nmo
    get_frozen_mask = get_frozen_mask
    def kernel(self, mo_energy=None, mo_coeff=None): ...
