from pyscf import lib as lib
from pyscf.lib import logger as logger
from pyscf.lib.parameters import LARGE_DENOM as LARGE_DENOM
from pyscf.pbc import scf as scf
from pyscf.pbc.lib import kpts_helper as kpts_helper
from pyscf.pbc.mp import kmp2 as kmp2
from numpy import int64, ndarray
from pyscf.pbc.cc.kccsd_uhf import KUCCSD
from pyscf.pbc.gw.kugw_ac import KUGWAC
from typing import List, Tuple, Union

def kernel(mp, mo_energy, mo_coeff, verbose=...) -> None: ...
def padding_k_idx(mp: KUCCSD, kind: str = 'split') -> Union[Tuple[List[ndarray], List[ndarray]], Tuple[List[List[ndarray]], List[List[ndarray]]]]: ...
def padded_mo_energy(mp, mo_energy): ...
def padded_mo_coeff(mp: KUCCSD, mo_coeff: ndarray) -> Tuple[ndarray, ndarray]: ...
def get_nocc(mp: Union[KUCCSD, KUGWAC], per_kpoint: bool = False) -> Union[Tuple[int64, int64], Tuple[List[int], List[int]], Tuple[List[int64], List[int64]]]: ...
def get_nmo(mp: Union[KUCCSD, KUGWAC], per_kpoint: bool = False) -> Union[Tuple[int64, int64], Tuple[List[int], List[int]]]: ...
def get_frozen_mask(mp: KUCCSD) -> List[List[ndarray]]: ...

class KUMP2(kmp2.KMP2):
    get_nocc = get_nocc
    get_nmo = get_nmo
    get_frozen_mask = get_frozen_mask
    def kernel(self, mo_energy=None, mo_coeff=None): ...
