from pyscf import lib as lib
from pyscf.mp import gmp2 as gmp2, mp2 as mp2, ump2 as ump2
from pyscf.pbc import scf as scf

class RMP2(mp2.RMP2):
    def __init__(self, mf, frozen=None, mo_coeff=None, mo_occ=None) -> None: ...
    def ao2mo(self, mo_coeff=None): ...

class UMP2(ump2.UMP2):
    def __init__(self, mf, frozen=None, mo_coeff=None, mo_occ=None) -> None: ...
    def ao2mo(self, mo_coeff=None): ...

class GMP2(gmp2.GMP2):
    def __init__(self, mf, frozen=None, mo_coeff=None, mo_occ=None) -> None: ...
    def ao2mo(self, mo_coeff=None): ...
