from _typeshed import Incomplete
from pyscf import gto as gto
from pyscf.df import density_fit as density_fit
from pyscf.dft import dks as dks, gen_grid as gen_grid, gks as gks, gks_symm as gks_symm, libxc as libxc, numint as numint, radi as radi, rks as rks, rks_symm as rks_symm, roks as roks, uks as uks, uks_symm as uks_symm, xcfun as xcfun
from pyscf.dft.gen_grid import Grids as Grids, nwchem_prune as nwchem_prune, original_becke as original_becke, sg1_prune as sg1_prune, stratmann as stratmann, treutler_prune as treutler_prune
from pyscf.dft.radi import BRAGG_RADII as BRAGG_RADII, COVALENT_RADII as COVALENT_RADII, becke_atomic_radii_adjust as becke_atomic_radii_adjust, delley as delley, gauss_chebyshev as gauss_chebyshev, mura_knowles as mura_knowles, treutler as treutler, treutler_ahlrichs as treutler_ahlrichs, treutler_atomic_radii_adjust as treutler_atomic_radii_adjust
from pyscf.dft.rks import KohnShamDFT as KohnShamDFT

XC: Incomplete
grid = gen_grid

def KS(mol, xc: str = 'LDA,VWN'): ...
DFT = KS

def RKS(mol, xc: str = 'LDA,VWN'): ...
def ROKS(mol, xc: str = 'LDA,VWN'): ...
def UKS(mol, xc: str = 'LDA,VWN'): ...
def GKS(mol, xc: str = 'LDA,VWN'): ...
def DKS(mol, xc: str = 'LDA,VWN'): ...

UDKS: Incomplete
RDKS = dks.RDKS

def X2C(mol, *args): ...
X2C_KS = X2C

def RKSpU(mol, xc: str = 'LDA,VWN', **kwargs): ...
def UKSpU(mol, xc: str = 'LDA,VWN', **kwargs): ...
