from _typeshed import Incomplete
from pyscf import lib as lib
from pyscf.dft import gks as gks, r_numint as r_numint, rks as rks
from pyscf.lib import logger as logger
from pyscf.scf import dhf as dhf
from pyscf.gto.mole import Mole
from pyscf.scf.dhf import DHF
from pyscf.x2c.dft import UKS
from typing import Optional, Union

def get_veff(ks, mol=None, dm=None, dm_last: int = 0, vhf_last: int = 0, hermi: int = 1): ...
def energy_elec(ks, dm=None, h1e=None, vhf=None): ...

class KohnShamDFT(rks.KohnShamDFT):
    def __init__(self, xc: str = 'LDA,VWN') -> None: ...
    def dump_flags(self, verbose: None=None) -> Union[DKS, UKS]: ...
    get_veff = gks.get_veff
    energy_elec: Incomplete
    @property
    def collinear(self): ...
    @collinear.setter
    def collinear(self, val) -> None: ...
    @property
    def spin_samples(self): ...
    @spin_samples.setter
    def spin_samples(self, val) -> None: ...
    def to_rhf(self) -> None: ...
    def to_uhf(self) -> None: ...
    def to_ghf(self) -> None: ...
    def to_rks(self, xc: None=None) -> None: ...
    def to_uks(self, xc: None=None) -> None: ...
    def to_gks(self, xc: None=None) -> None: ...
    def to_dhf(self) -> DHF: ...
    to_hf = to_dhf
    def to_dks(self, xc: Optional[str]=None) -> "DKS": ...
    to_ks = to_dks

class DKS(KohnShamDFT, dhf.DHF):
    def __init__(self, mol: Mole, xc: str = 'LDA,VWN') -> None: ...
    def dump_flags(self, verbose: None=None) -> "DKS": ...
    def x2c1e(self) -> "UKS": ...
    x2c = x2c1e
    to_gpu = lib.to_gpu
UKS = DKS
UDKS = DKS

class RDKS(DKS, dhf.RDHF):
    def __init__(self, mol, xc: str = 'LDA,VWN') -> None: ...
    def x2c1e(self): ...
    x2c = x2c1e
    def to_dhf(self): ...
RKS = RDKS
