from pyscf import lib as lib
from pyscf.dft import rks as rks
from pyscf.dft.numint2c import NumInt2C as NumInt2C
from pyscf.lib import logger as logger
from pyscf.scf import ghf as ghf

def get_veff(ks, mol=None, dm=None, dm_last: int = 0, vhf_last: int = 0, hermi: int = 1): ...
energy_elec = rks.energy_elec

class GKS(rks.KohnShamDFT, ghf.GHF):
    get_veff = get_veff
    energy_elec = energy_elec
    def __init__(self, mol, xc: str = 'LDA,VWN') -> None: ...
    def dump_flags(self, verbose=None): ...
    @property
    def collinear(self): ...
    @collinear.setter
    def collinear(self, val) -> None: ...
    @property
    def spin_samples(self): ...
    @spin_samples.setter
    def spin_samples(self, val) -> None: ...
    def nuc_grad_method(self) -> None: ...
    def to_hf(self): ...
    to_gpu = lib.to_gpu
