from _typeshed import Incomplete
from numpy import int64, ndarray
from typing import Union

def SphGenOh(code: int, a: Union[float, int], b: Union[float, int], v: float) -> ndarray: ...
def MakeAngularGrid_6() -> ndarray: ...
def MakeAngularGrid_14() -> ndarray: ...
def MakeAngularGrid_26(): ...
def MakeAngularGrid_38() -> ndarray: ...
def MakeAngularGrid_50() -> ndarray: ...
def MakeAngularGrid_74() -> ndarray: ...
def MakeAngularGrid_86() -> ndarray: ...
def MakeAngularGrid_110() -> ndarray: ...
def MakeAngularGrid_146(): ...
def MakeAngularGrid_170() -> ndarray: ...
def MakeAngularGrid_194() -> ndarray: ...
def MakeAngularGrid_230(): ...
def MakeAngularGrid_266() -> ndarray: ...
def MakeAngularGrid_302() -> ndarray: ...
def MakeAngularGrid_350() -> ndarray: ...
def MakeAngularGrid_434() -> ndarray: ...
def MakeAngularGrid_590() -> ndarray: ...
def MakeAngularGrid_770() -> ndarray: ...
def MakeAngularGrid_974(): ...
def MakeAngularGrid_1202(): ...
def MakeAngularGrid_1454(): ...
def MakeAngularGrid_1730(): ...
def MakeAngularGrid_2030(): ...
def MakeAngularGrid_2354(): ...
def MakeAngularGrid_2702(): ...
def MakeAngularGrid_3074(): ...
def MakeAngularGrid_3470(): ...
def MakeAngularGrid_3890(): ...
def MakeAngularGrid_4334(): ...
def MakeAngularGrid_4802(): ...
def MakeAngularGrid_5294(): ...
def MakeAngularGrid_5810(): ...

LEBEDEV_ORDER: Incomplete
LEBEDEV_NGRID: Incomplete

def MakeAngularGrid(points: int64) -> ndarray: ...
