from _typeshed import Incomplete

def SphGenOh(code, a, b, v): ...
def MakeAngularGrid_6(): ...
def MakeAngularGrid_14(): ...
def MakeAngularGrid_26(): ...
def MakeAngularGrid_38(): ...
def MakeAngularGrid_50(): ...
def MakeAngularGrid_74(): ...
def MakeAngularGrid_86(): ...
def MakeAngularGrid_110(): ...
def MakeAngularGrid_146(): ...
def MakeAngularGrid_170(): ...
def MakeAngularGrid_194(): ...
def MakeAngularGrid_230(): ...
def MakeAngularGrid_266(): ...
def MakeAngularGrid_302(): ...
def MakeAngularGrid_350(): ...
def MakeAngularGrid_434(): ...
def MakeAngularGrid_590(): ...
def MakeAngularGrid_770(): ...
def MakeAngularGrid_974(): ...
def MakeAngularGrid_1202(): ...
def MakeAngularGrid_1454(): ...
def MakeAngularGrid_1730(): ...
def MakeAngularGrid_2030(): ...
def MakeAngularGrid_2354(): ...
def MakeAngularGrid_2702(): ...
def MakeAngularGrid_3074(): ...
def MakeAngularGrid_3470(): ...
def MakeAngularGrid_3890(): ...
def MakeAngularGrid_4334(): ...
def MakeAngularGrid_4802(): ...
def MakeAngularGrid_5294(): ...
def MakeAngularGrid_5810(): ...

LEBEDEV_ORDER: Incomplete
LEBEDEV_NGRID: Incomplete

def MakeAngularGrid(points): ...
