from _typeshed import Incomplete
from functools import cached_property as cached_property
from pyscf import __config__ as __config__, lib as lib
from pyscf.dft import xc_deriv as xc_deriv
from pyscf.dft.xc.utils import format_xc_code as format_xc_code, remove_dup as remove_dup

def libxc_version(): ...
def libxc_reference(): ...
def libxc_reference_doi(): ...

__version__: Incomplete
__reference__: Incomplete
__reference_doi__: Incomplete

def available_libxc_functionals(): ...

XC: Incomplete

XC_CODES: Incomplete
PROBLEMATIC_XC: Incomplete

def print_XC_CODES() -> None: ...

XC_KEYS: Incomplete
XC_ALIAS: Incomplete

def xc_reference(xc_code): ...
def xc_type(xc_code): ...
def is_lda(xc_code): ...
def is_hybrid_xc(xc_code): ...
def is_meta_gga(xc_code): ...
def is_gga(xc_code): ...
def is_nlc(xc_code): ...
def needs_laplacian(xc_code): ...
def max_deriv_order(xc_code): ...
def test_deriv_order(xc_code, deriv, raise_error: bool = False): ...
def hybrid_coeff(xc_code, spin: int = 0): ...
def nlc_coeff(xc_code): ...
def rsh_coeff(xc_code): ...
def parse_xc_name(xc_name: str = 'LDA,VWN'): ...
def parse_xc(description): ...
def eval_xc(xc_code, rho, spin: int = 0, relativity: int = 0, deriv: int = 1, omega=None, verbose=None): ...
def eval_xc1(xc_code, rho, spin: int = 0, deriv: int = 1, omega=None): ...
def eval_xc_eff(xc_code, rho, deriv: int = 1, omega=None, spin=None): ...
def define_xc_(ni, description, xctype: str = 'LDA', hyb: int = 0, rsh=(0, 0, 0)): ...
def define_xc(ni, description, xctype: str = 'LDA', hyb: int = 0, rsh=(0, 0, 0)): ...

class XCFunctionalCache:
    xc_code: Incomplete
    spin: Incomplete
    fn_ids: Incomplete
    facs: Incomplete
    nfunc: Incomplete
    hyb: Incomplete
    xc_arr: Incomplete
    xc_objs: Incomplete
    def __init__(self, xc_code, spin: int = 0, omega=None, density_threshold=None) -> None: ...
    @cached_property
    def xc_type(self): ...
    @cached_property
    def is_nlc(self): ...
    @cached_property
    def needs_laplacian(self): ...
    @cached_property
    def max_deriv_order(self): ...
    @cached_property
    def hybrid_coeff(self): ...
    @cached_property
    def nlc_coeff(self): ...
    @cached_property
    def rsh_coeff(self): ...
    def customize_(self, ext_params=None, omega=None, hyb=None, facs=None, density_threshold=None, callback=None, clear: bool = True) -> None: ...
    def __del__(self) -> None: ...
    def obj_by_id(self): ...

def register_custom_functional_(new_xc_code, based_on_xc_code, ext_params=None, omega=None, hyb=None, facs=None, density_threshold=None, callback=None, restricted: bool = True, unrestricted: bool = True): ...
def update_custom_functional_(xc_code, ext_params=None, omega=None, hyb=None, facs=None, density_threshold=None, callback=None, restricted: bool = True, unrestricted: bool = True, clear: bool = True) -> None: ...
def unregister_custom_functional_(xc_code) -> None: ...
