from _typeshed import Incomplete
from functools import cached_property as cached_property
from pyscf import __config__ as __config__, lib as lib
from pyscf.dft import xc_deriv as xc_deriv
from pyscf.dft.xc.utils import format_xc_code as format_xc_code, remove_dup as remove_dup
from ctypes import c_void_p
from numpy import int32, ndarray
from pyscf.dft.numint import NumInt
from typing import Any, Callable, Dict, List, Optional, Tuple, Union

def libxc_version() -> str: ...
def libxc_reference() -> str: ...
def libxc_reference_doi() -> str: ...

__version__: Incomplete
__reference__: Incomplete
__reference_doi__: Incomplete

def available_libxc_functionals() -> Dict[str, int32]: ...

XC: Incomplete

XC_CODES: Incomplete
PROBLEMATIC_XC: Incomplete

def print_XC_CODES() -> None: ...

XC_KEYS: Incomplete
XC_ALIAS: Incomplete

def xc_reference(xc_code: str) -> List[str]: ...
def xc_type(xc_code: Union[int, str]) -> str: ...
def is_lda(xc_code: str) -> bool: ...
def is_hybrid_xc(xc_code: Union[int, Tuple[int, str], str, Tuple[str, str]]) -> bool: ...
def is_meta_gga(xc_code: str) -> bool: ...
def is_gga(xc_code: str) -> bool: ...
def is_nlc(xc_code: Union[Tuple[str, str], Tuple[int, str], str, int]) -> Union[bool, int]: ...
def needs_laplacian(xc_code): ...
def max_deriv_order(xc_code: str) -> int: ...
def test_deriv_order(xc_code: str, deriv: int, raise_error: bool = False) -> bool: ...
def hybrid_coeff(xc_code: str, spin: int = 0) -> Union[float, int]: ...
def nlc_coeff(xc_code: str) -> Union[Tuple[Tuple[Tuple[float, float], float]], Tuple[Tuple[Tuple[float, float], int]]]: ...
def rsh_coeff(xc_code: Union[int, str]) -> Union[Tuple[int, int, float], Tuple[float, float, float]]: ...
def parse_xc_name(xc_name: str = 'LDA,VWN') -> Tuple[int, int32]: ...
def parse_xc(description: Union[int, Tuple[int, int], str, Tuple[str, str]]) -> Any: ...
def eval_xc(xc_code: str, rho: Union[ndarray, Tuple[ndarray, ndarray], List[ndarray]], spin: int = 0, relativity: int = 0, deriv: int = 1, omega: Optional[float]=None, verbose: None=None) -> Any: ...
def eval_xc1(xc_code: str, rho: ndarray, spin: int = 0, deriv: int = 1, omega: Optional[float]=None) -> ndarray: ...
def eval_xc_eff(xc_code: str, rho: ndarray, deriv: int = 1, omega: None=None, spin: None=None) -> ndarray: ...
def define_xc_(ni: NumInt, description: Union[float, str, Callable], xctype: str = 'LDA', hyb: Union[float, int] = 0, rsh: Tuple[int, int, int]=(0, 0, 0)) -> NumInt: ...
def define_xc(ni: NumInt, description: Union[float, str, Callable], xctype: str = 'LDA', hyb: Union[float, int] = 0, rsh: Tuple[int, int, int]=(0, 0, 0)) -> NumInt: ...

class XCFunctionalCache:
    xc_code: Incomplete
    spin: Incomplete
    fn_ids: Incomplete
    facs: Incomplete
    nfunc: Incomplete
    hyb: Incomplete
    xc_arr: Incomplete
    xc_objs: Incomplete
    def __init__(self, xc_code: Union[int, str], spin: int = 0, omega: Optional[float]=None, density_threshold: None=None) -> None: ...
    @cached_property
    def xc_type(self): ...
    @cached_property
    def is_nlc(self): ...
    @cached_property
    def needs_laplacian(self): ...
    @cached_property
    def max_deriv_order(self): ...
    @cached_property
    def hybrid_coeff(self): ...
    @cached_property
    def nlc_coeff(self): ...
    @cached_property
    def rsh_coeff(self): ...
    def customize_(self, ext_params: Optional[Dict[int, ndarray]]=None, omega: None=None, hyb: None=None, facs: None=None, density_threshold: None=None, callback: None=None, clear: bool = True) -> None: ...
    def __del__(self) -> None: ...
    def obj_by_id(self) -> Dict[int32, c_void_p]: ...

def register_custom_functional_(new_xc_code: str, based_on_xc_code: str, ext_params: Optional[Dict[int, ndarray]]=None, omega: None=None, hyb: None=None, facs: None=None, density_threshold: None=None, callback: None=None, restricted: bool = True, unrestricted: bool = True): ...
def update_custom_functional_(xc_code: str, ext_params: Optional[Dict[int, ndarray]]=None, omega: None=None, hyb: None=None, facs: None=None, density_threshold: None=None, callback: None=None, restricted: bool = True, unrestricted: bool = True, clear: bool = True) -> None: ...
def unregister_custom_functional_(xc_code: str) -> None: ...
