from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, lib as lib
from pyscf.dft import libxc as libxc, xc_deriv as xc_deriv, xcfun as xcfun
from pyscf.dft.gen_grid import Grids, ALIGNMENT_UNIT as ALIGNMENT_UNIT, BLKSIZE as BLKSIZE, CUTOFF as CUTOFF, NBINS as NBINS, make_mask as make_mask
from numpy import float64, ndarray
from pyscf.gto.mole import Mole
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.gto.cell import Cell
from typing import Callable, Iterator, List, Optional, Tuple, Union

libxc = xcfun
libdft: Incomplete
OCCDROP: Incomplete
SWITCH_SIZE: Incomplete
MGGA_DENSITY_LAPL: bool

def eval_ao(mol: Union[Cell, Mole], coords: ndarray, deriv: int = 0, shls_slice: None=None, non0tab: Optional[ndarray]=None, cutoff: Optional[float]=None, out: Optional[ndarray]=None, verbose: None=None) -> ndarray: ...
def eval_rho(mol: Union[Cell, Mole], ao: ndarray, dm: Union[ndarray, NPArrayWithTag], non0tab: Optional[ndarray]=None, xctype: str = 'LDA', hermi: int = 0, with_lapl: bool = True, verbose: None=None) -> ndarray: ...
def eval_rho1(mol: Mole, ao: ndarray, dm: Union[NPArrayWithTag, ndarray], screen_index: Optional[ndarray]=None, xctype: str = 'LDA', hermi: int = 0, with_lapl: bool = True, cutoff: Optional[float]=None, ao_cutoff: float=..., pair_mask: Optional[ndarray]=None, verbose: None=None) -> ndarray: ...
def eval_rho2(mol: Union[Cell, Mole], ao: ndarray, mo_coeff: Union[ndarray, NPArrayWithTag], mo_occ: ndarray, non0tab: Optional[ndarray]=None, xctype: str = 'LDA', with_lapl: bool = True, verbose: None=None) -> ndarray: ...
def eval_mat(mol: Union[Cell, Mole], ao: ndarray, weight: ndarray, rho: Union[ndarray, List[ndarray]], vxc: Union[List[Optional[ndarray]], List[ndarray], Tuple[ndarray, ndarray, None, ndarray], ndarray], non0tab: None=None, xctype: str = 'LDA', spin: int = 0, verbose: None=None) -> ndarray: ...
def nr_vxc(mol, grids, xc_code, dms, spin: int = 0, relativity: int = 0, hermi: int = 0, max_memory: int = 2000, verbose=None): ...
def nr_sap_vxc(ni: "NumInt", mol: Mole, grids: Grids, max_memory: float = 2000, verbose: None=None) -> ndarray: ...
def nr_rks(ni: "NumInt", mol: Mole, grids: Grids, xc_code: str, dms: Union[ndarray, NPArrayWithTag], relativity: int = 0, hermi: int = 1, max_memory: Union[float, int] = 2000, verbose: None=None) -> Union[Tuple[ndarray, ndarray, ndarray], Tuple[float64, float64, ndarray]]: ...
def nr_uks(ni: "NumInt", mol: Mole, grids: Grids, xc_code: str, dms: Union[NPArrayWithTag, Tuple[NPArrayWithTag, NPArrayWithTag], Tuple[ndarray, ndarray], ndarray], relativity: int = 0, hermi: int = 1, max_memory: Union[float, int] = 2000, verbose: None=None) -> Tuple[ndarray, float64, ndarray]: ...
nr_rks_vxc = nr_rks
nr_uks_vxc = nr_uks

def nr_nlc_vxc(ni: "NumInt", mol: Mole, grids: Grids, xc_code: str, dm: Union[NPArrayWithTag, ndarray], relativity: int = 0, hermi: int = 1, max_memory: Union[float, int] = 2000, verbose: None=None) -> Tuple[float64, float64, ndarray]: ...
def nr_rks_fxc(ni: "NumInt", mol: Mole, grids: Grids, xc_code: str, dm0: ndarray, dms: ndarray, relativity: int = 0, hermi: int = 0, rho0: Optional[ndarray]=None, vxc: Optional[ndarray]=None, fxc: Optional[ndarray]=None, max_memory: int = 2000, verbose: None=None) -> ndarray: ...
def nr_rks_fxc_st(ni: "NumInt", mol: Mole, grids: Grids, xc_code: str, dm0: ndarray, dms_alpha: ndarray, hermi: int = 0, singlet: bool = True, rho0: Optional[Tuple[ndarray, ndarray]]=None, vxc: Optional[ndarray]=None, fxc: Optional[ndarray]=None, max_memory: int = 2000, verbose: None=None) -> ndarray: ...
def nr_uks_fxc(ni: "NumInt", mol: Mole, grids: Grids, xc_code: str, dm0: Union[ndarray, Tuple[ndarray, ndarray]], dms: Union[ndarray, Tuple[ndarray, ndarray]], relativity: int = 0, hermi: int = 0, rho0: Optional[Tuple[ndarray, ndarray]]=None, vxc: Optional[ndarray]=None, fxc: Optional[ndarray]=None, max_memory: int = 2000, verbose: None=None) -> ndarray: ...
def nr_fxc(mol: Mole, grids: Grids, xc_code: str, dm0: ndarray, dms: ndarray, spin: int = 0, relativity: int = 0, hermi: int = 0, rho0: Optional[Union[Tuple[ndarray, ndarray], ndarray]]=None, vxc: Optional[ndarray]=None, fxc: Optional[ndarray]=None, max_memory: int = 2000, verbose: None=None) -> ndarray: ...
def cache_xc_kernel(ni: "NumInt", mol: Mole, grids: Grids, xc_code: str, mo_coeff: Union[ndarray, List[ndarray]], mo_occ: Union[ndarray, List[ndarray]], spin: int = 0, max_memory: int = 2000) -> Union[Tuple[Tuple[ndarray, ndarray], ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]]: ...
def cache_xc_kernel1(ni: "NumInt", mol: Mole, grids: Grids, xc_code: str, dm: Union[ndarray, Tuple[ndarray, ndarray]], spin: int = 0, max_memory: int = 2000) -> Union[Tuple[Tuple[ndarray, ndarray], ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]]: ...
def get_rho(ni: "NumInt", mol: Mole, dm: Union[NPArrayWithTag, ndarray], grids: Grids, max_memory: int = 2000) -> ndarray: ...
def get_rho_naive(mol: Mole, dm: NPArrayWithTag, grids: Grids) -> ndarray: ...
def get_rho_with_derivatives(ni: "NumInt", mol: Mole, dm: NPArrayWithTag, grids: Grids, xc: str = 'r2scan', max_memory: int = 2000, verbose: None=None) -> ndarray: ...
def get_rho_with_derivatives_naive(mol: Mole, dm: NPArrayWithTag, grids: Grids, xc: str = 'r2scan') -> ndarray: ...

class LibXCMixin:
    libxc = libxc
    omega: Incomplete
    def hybrid_coeff(self, xc_code: str, spin: int = 0) -> Union[float, int]: ...
    def nlc_coeff(self, xc_code: str) -> Tuple[Tuple[Tuple[float, float], int]]: ...
    def rsh_coeff(self, xc_code: str) -> Union[Tuple[int, int, float], Tuple[float, float, float]]: ...
    def eval_xc(self, xc_code: str, rho: ndarray, spin: int = 0, relativity: int = 0, deriv: int = 1, omega: Optional[float]=None, verbose: None=None) -> Tuple[ndarray, List[ndarray], None, None]: ...
    def eval_xc1(self, xc_code: str, rho: ndarray, spin: int = 0, deriv: int = 1, omega: Optional[float]=None) -> ndarray: ...
    def eval_xc_eff(self, xc_code: Optional[str], rho: Union[ndarray, Tuple[ndarray, ndarray]], deriv: int = 1, omega: None=None, xctype: Optional[str]=None, verbose: None=None, spin: Optional[int]=None) -> List[Optional[ndarray]]: ...
    def rsh_and_hybrid_coeff(self, xc_code: str, spin: int = 0) -> Union[Tuple[int, int, int], Tuple[float, float, float]]: ...

class NumInt(lib.StreamObject, LibXCMixin):
    cutoff: Incomplete
    def nr_vxc(self, mol: Mole, grids: Grids, xc_code: str, dms: ndarray, spin: int = 0, relativity: int = 0, hermi: int = 0, max_memory: int = 2000, verbose: None=None) -> Union[Tuple[ndarray, float64, ndarray], Tuple[ndarray, ndarray, ndarray]]: ...
    get_vxc = nr_vxc
    def nr_fxc(self, mol: Mole, grids: Grids, xc_code: str, dm0: ndarray, dms: ndarray, spin: int = 0, relativity: int = 0, hermi: int = 0, rho0: Optional[Union[Tuple[ndarray, ndarray], ndarray]]=None, vxc: Optional[ndarray]=None, fxc: Optional[ndarray]=None, max_memory: int = 2000, verbose: None=None) -> ndarray: ...
    get_fxc = nr_fxc
    nr_rks = nr_rks
    nr_uks = nr_uks
    nr_nlc_vxc = nr_nlc_vxc
    nr_sap = nr_sap_vxc
    nr_sap_vxc = nr_sap_vxc
    nr_rks_fxc = nr_rks_fxc
    nr_uks_fxc = nr_uks_fxc
    nr_rks_fxc_st = nr_rks_fxc_st
    cache_xc_kernel = cache_xc_kernel
    cache_xc_kernel1 = cache_xc_kernel1
    make_mask: Incomplete
    eval_ao: Incomplete
    eval_rho: Incomplete
    eval_rho1: Incomplete
    eval_rho2: Incomplete
    get_rho = get_rho
    get_rho_with_derivatives = get_rho_with_derivatives
    def block_loop(self, mol: Union[Cell, Mole], grids: Grids, nao: Optional[int]=None, deriv: int = 0, max_memory: Union[float, int] = 2000, non0tab: None=None, blksize: None=None, buf: None=None) -> Iterator[Union[Tuple[ndarray, ndarray, ndarray, ndarray], Tuple[ndarray, None, ndarray, ndarray]]]: ...
    def to_gpu(self): ...
