from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.dft import numint as numint, xc_deriv as xc_deriv
from pyscf.dft.numint import BLKSIZE as BLKSIZE

def eval_rho(mol, ao, dm, non0tab=None, xctype: str = 'LDA', hermi: int = 0, with_lapl: bool = True, verbose=None): ...
def mcfun_eval_xc_adapter(ni, xc_code): ...

class NumInt2C(lib.StreamObject, numint.LibXCMixin):
    collinear: Incomplete
    spin_samples: Incomplete
    collinear_thrd: Incomplete
    collinear_samples: Incomplete
    make_mask: Incomplete
    eval_ao: Incomplete
    eval_rho: Incomplete
    def eval_rho1(self, mol, ao, dm, screen_index=None, xctype: str = 'LDA', hermi: int = 0, with_lapl: bool = True, cutoff=None, ao_cutoff=None, pair_mask=None, verbose=None): ...
    def eval_rho2(self, mol, ao, mo_coeff, mo_occ, non0tab=None, xctype: str = 'LDA', with_lapl: bool = True, verbose=None): ...
    def cache_xc_kernel(self, mol, grids, xc_code, mo_coeff, mo_occ, spin: int = 0, max_memory: int = 2000): ...
    def cache_xc_kernel1(self, mol, grids, xc_code, dm, spin: int = 0, max_memory: int = 2000): ...
    def get_rho(self, mol, dm, grids, max_memory: int = 2000): ...
    def nr_vxc(self, mol, grids, xc_code, dms, spin: int = 0, relativity: int = 0, hermi: int = 1, max_memory: int = 2000, verbose=None): ...
    get_vxc = nr_vxc
    nr_gks_vxc = nr_vxc
    def nr_nlc_vxc(self, mol, grids, xc_code, dm, spin: int = 0, relativity: int = 0, hermi: int = 1, max_memory: int = 2000, verbose=None): ...
    def nr_fxc(self, mol, grids, xc_code, dm0, dms, spin: int = 0, relativity: int = 0, hermi: int = 0, rho0=None, vxc=None, fxc=None, max_memory: int = 2000, verbose=None): ...
    get_fxc = nr_fxc
    nr_gks_fxc = nr_fxc
    eval_xc_eff: Incomplete
    mcfun_eval_xc_adapter = mcfun_eval_xc_adapter
    block_loop: Incomplete
    def to_gpu(self): ...
