from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, lib as lib
from pyscf.dft import libxc as libxc, xc_deriv as xc_deriv, xcfun as xcfun
from pyscf.dft.gen_grid import ALIGNMENT_UNIT as ALIGNMENT_UNIT, BLKSIZE as BLKSIZE, CUTOFF as CUTOFF, NBINS as NBINS, make_mask as make_mask

libxc = xcfun
libdft: Incomplete
OCCDROP: Incomplete
SWITCH_SIZE: Incomplete
MGGA_DENSITY_LAPL: bool

def eval_ao(mol, coords, deriv: int = 0, shls_slice=None, non0tab=None, cutoff=None, out=None, verbose=None): ...
def eval_rho(mol, ao, dm, non0tab=None, xctype: str = 'LDA', hermi: int = 0, with_lapl: bool = True, verbose=None): ...
def eval_rho1(mol, ao, dm, screen_index=None, xctype: str = 'LDA', hermi: int = 0, with_lapl: bool = True, cutoff=None, ao_cutoff=..., pair_mask=None, verbose=None): ...
def eval_rho2(mol, ao, mo_coeff, mo_occ, non0tab=None, xctype: str = 'LDA', with_lapl: bool = True, verbose=None): ...
def eval_mat(mol, ao, weight, rho, vxc, non0tab=None, xctype: str = 'LDA', spin: int = 0, verbose=None): ...
def nr_vxc(mol, grids, xc_code, dms, spin: int = 0, relativity: int = 0, hermi: int = 0, max_memory: int = 2000, verbose=None): ...
def nr_sap_vxc(ni, mol, grids, max_memory: int = 2000, verbose=None): ...
def nr_rks(ni, mol, grids, xc_code, dms, relativity: int = 0, hermi: int = 1, max_memory: int = 2000, verbose=None): ...
def nr_uks(ni, mol, grids, xc_code, dms, relativity: int = 0, hermi: int = 1, max_memory: int = 2000, verbose=None): ...
nr_rks_vxc = nr_rks
nr_uks_vxc = nr_uks

def nr_nlc_vxc(ni, mol, grids, xc_code, dm, relativity: int = 0, hermi: int = 1, max_memory: int = 2000, verbose=None): ...
def nr_rks_fxc(ni, mol, grids, xc_code, dm0, dms, relativity: int = 0, hermi: int = 0, rho0=None, vxc=None, fxc=None, max_memory: int = 2000, verbose=None): ...
def nr_rks_fxc_st(ni, mol, grids, xc_code, dm0, dms_alpha, hermi: int = 0, singlet: bool = True, rho0=None, vxc=None, fxc=None, max_memory: int = 2000, verbose=None): ...
def nr_uks_fxc(ni, mol, grids, xc_code, dm0, dms, relativity: int = 0, hermi: int = 0, rho0=None, vxc=None, fxc=None, max_memory: int = 2000, verbose=None): ...
def nr_fxc(mol, grids, xc_code, dm0, dms, spin: int = 0, relativity: int = 0, hermi: int = 0, rho0=None, vxc=None, fxc=None, max_memory: int = 2000, verbose=None): ...
def cache_xc_kernel(ni, mol, grids, xc_code, mo_coeff, mo_occ, spin: int = 0, max_memory: int = 2000): ...
def cache_xc_kernel1(ni, mol, grids, xc_code, dm, spin: int = 0, max_memory: int = 2000): ...
def get_rho(ni, mol, dm, grids, max_memory: int = 2000): ...
def get_rho_naive(mol, dm, grids): ...
def get_rho_with_derivatives(ni, mol, dm, grids, xc: str = 'r2scan', max_memory: int = 2000, verbose=None): ...
def get_rho_with_derivatives_naive(mol, dm, grids, xc: str = 'r2scan'): ...

class LibXCMixin:
    libxc = libxc
    omega: Incomplete
    def hybrid_coeff(self, xc_code, spin: int = 0): ...
    def nlc_coeff(self, xc_code): ...
    def rsh_coeff(self, xc_code): ...
    def eval_xc(self, xc_code, rho, spin: int = 0, relativity: int = 0, deriv: int = 1, omega=None, verbose=None): ...
    def eval_xc1(self, xc_code, rho, spin: int = 0, deriv: int = 1, omega=None): ...
    def eval_xc_eff(self, xc_code, rho, deriv: int = 1, omega=None, xctype=None, verbose=None, spin=None): ...
    def rsh_and_hybrid_coeff(self, xc_code, spin: int = 0): ...

class NumInt(lib.StreamObject, LibXCMixin):
    cutoff: Incomplete
    def nr_vxc(self, mol, grids, xc_code, dms, spin: int = 0, relativity: int = 0, hermi: int = 0, max_memory: int = 2000, verbose=None): ...
    get_vxc = nr_vxc
    def nr_fxc(self, mol, grids, xc_code, dm0, dms, spin: int = 0, relativity: int = 0, hermi: int = 0, rho0=None, vxc=None, fxc=None, max_memory: int = 2000, verbose=None): ...
    get_fxc = nr_fxc
    nr_rks = nr_rks
    nr_uks = nr_uks
    nr_nlc_vxc = nr_nlc_vxc
    nr_sap = nr_sap_vxc
    nr_sap_vxc = nr_sap_vxc
    nr_rks_fxc = nr_rks_fxc
    nr_uks_fxc = nr_uks_fxc
    nr_rks_fxc_st = nr_rks_fxc_st
    cache_xc_kernel = cache_xc_kernel
    cache_xc_kernel1 = cache_xc_kernel1
    make_mask: Incomplete
    eval_ao: Incomplete
    eval_rho: Incomplete
    eval_rho1: Incomplete
    eval_rho2: Incomplete
    get_rho = get_rho
    get_rho_with_derivatives = get_rho_with_derivatives
    def block_loop(self, mol, grids, nao=None, deriv: int = 0, max_memory: int = 2000, non0tab=None, blksize=None, buf=None) -> Generator[Incomplete]: ...
    def to_gpu(self): ...
