from _typeshed import Incomplete
from pyscf import __config__ as __config__
from pyscf.data import radii as radii

BRAGG_RADII: Incomplete
COVALENT_RADII: Incomplete
ATOM_SPECIFIC_TREUTLER_GRIDS: Incomplete
SG1RADII: Incomplete

def murray(n, *args, **kwargs) -> None: ...
def becke(n, charge, *args, **kwargs): ...
def delley(n, *args, **kwargs): ...
gauss_legendre = delley

def mura_knowles(n, charge=None, *args, **kwargs): ...
def gauss_chebyshev(n, *args, **kwargs): ...
def treutler_ahlrichs(n, chg, *args, **kwargs): ...
treutler = treutler_ahlrichs

def becke_atomic_radii_adjust(mol, atomic_radii): ...
def treutler_atomic_radii_adjust(mol, atomic_radii): ...
