from _typeshed import Incomplete
from pyscf import __config__ as __config__
from pyscf.data import radii as radii
from numpy import int64, ndarray
from pyscf.gto.mole import Mole
from pyscf.pbc.gto.cell import Cell
from typing import Callable, Optional, Tuple, Union

BRAGG_RADII: Incomplete
COVALENT_RADII: Incomplete
ATOM_SPECIFIC_TREUTLER_GRIDS: Incomplete
SG1RADII: Incomplete

def murray(n, *args, **kwargs) -> None: ...
def becke(n: int, charge: int, *args, **kwargs) -> Tuple[ndarray, ndarray]: ...
def delley(n: int, *args, **kwargs) -> Tuple[ndarray, ndarray]: ...
gauss_legendre = delley

def mura_knowles(n: int, charge: Optional[int]=None, *args, **kwargs) -> Tuple[ndarray, ndarray]: ...
def gauss_chebyshev(n: Union[int64, int], *args, **kwargs) -> Tuple[ndarray, ndarray]: ...
def treutler_ahlrichs(n: Union[int64, int], chg: int, *args, **kwargs) -> Tuple[ndarray, ndarray]: ...
treutler = treutler_ahlrichs

def becke_atomic_radii_adjust(mol: Mole, atomic_radii: ndarray) -> Callable: ...
def treutler_atomic_radii_adjust(mol: Union[Mole, Cell], atomic_radii: ndarray) -> Callable: ...
