from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib, scf as scf
from pyscf.dft import gen_grid as gen_grid, numint as numint
from pyscf.lib import logger as logger
from pyscf.scf import hf as hf, jk as jk
from pyscf.scf.dispersion import parse_dft as parse_dft
from numpy import float64, ndarray
from pyscf.dft.gen_grid import Grids
from pyscf.dft.gks import GKS
from pyscf.dft.rks_symm import SymAdaptedRKS, SymAdaptedROKS
from pyscf.dft.rkspu import RKSpU
from pyscf.dft.uks import UKS
from pyscf.dft.uks_symm import SymAdaptedUKS
from pyscf.grad.rks import Gradients
from pyscf.gto.mole import Mole
from pyscf.lib.logger import Logger
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.scf.kuhf import KUHF
from pyscf.scf.ghf import GHF
from pyscf.scf.hf import RHF
from pyscf.scf.uhf import UHF
from typing import Optional, Tuple, Union

def get_veff(ks: Union[RKSpU, SymAdaptedRKS, RKS], mol: Optional[Mole]=None, dm: Optional[Union[ndarray, NPArrayWithTag]]=None, dm_last: Union[NPArrayWithTag, int] = 0, vhf_last: Union[NPArrayWithTag, int] = 0, hermi: int = 1) -> NPArrayWithTag: ...
def get_vsap(ks: Union[SymAdaptedUKS, SymAdaptedROKS, RKS], mol: None=None) -> ndarray: ...
def energy_elec(ks: "KohnShamDFT", dm: Optional[Union[ndarray, NPArrayWithTag]]=None, h1e: Optional[ndarray]=None, vhf: Optional[NPArrayWithTag]=None) -> Tuple[float64, float64]: ...
def prune_small_rho_grids_(ks: "RKS", mol: Mole, dm: NPArrayWithTag, grids: Grids) -> Grids: ...
def define_xc_(ks: "RKS", description: str, xctype: str = 'LDA', hyb: int = 0, rsh: Tuple[int, int, int]=(0, 0, 0)) -> "RKS": ...

class KohnShamDFT:
    small_rho_cutoff: Incomplete
    xc: Incomplete
    nlc: str
    disp: Incomplete
    grids: Incomplete
    nlcgrids: Incomplete
    def __init__(self, xc: str = 'LDA,VWN') -> None: ...
    @property
    def omega(self): ...
    @omega.setter
    def omega(self, v) -> None: ...
    def dump_flags(self, verbose: Optional[Logger]=None) -> "KohnShamDFT": ...
    define_xc_ = define_xc_
    def do_nlc(self) -> Union[bool, int]: ...
    def to_rhf(self) -> RHF: ...
    def to_uhf(self) -> Union[UHF, KUHF]: ...
    def to_ghf(self) -> GHF: ...
    def to_hf(self) -> None: ...
    def to_rks(self, xc: Optional[str]=None) -> "RKS": ...
    def to_uks(self, xc: Optional[str]=None) -> UKS: ...
    def to_gks(self, xc: Optional[str]=None) -> GKS: ...
    def reset(self, mol: Optional[Mole]=None) -> "RKS": ...
    def check_sanity(self) -> "KohnShamDFT": ...
    def initialize_grids(self, mol: Optional[Mole]=None, dm: Optional[Union[ndarray, NPArrayWithTag]]=None) -> "KohnShamDFT": ...
    def to_gpu(self) -> None: ...

def init_guess_by_vsap(mf: Union[SymAdaptedUKS, SymAdaptedROKS, RKS], mol: Optional[Mole]=None) -> NPArrayWithTag: ...

class RKS(KohnShamDFT, hf.RHF):
    __doc__: Incomplete
    def __init__(self, mol: Mole, xc: str = 'LDA,VWN') -> None: ...
    def dump_flags(self, verbose: Optional[Logger]=None) -> Union[RKSpU, RKS]: ...
    get_veff = get_veff
    get_vsap = get_vsap
    energy_elec = energy_elec
    init_guess_by_vsap = init_guess_by_vsap
    def nuc_grad_method(self) -> Gradients: ...
    def to_hf(self) -> RHF: ...
    to_gpu = lib.to_gpu
