from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib, scf as scf
from pyscf.dft import gen_grid as gen_grid, numint as numint
from pyscf.lib import logger as logger
from pyscf.scf import hf as hf, jk as jk
from pyscf.scf.dispersion import parse_dft as parse_dft

def get_veff(ks, mol=None, dm=None, dm_last: int = 0, vhf_last: int = 0, hermi: int = 1): ...
def get_vsap(ks, mol=None): ...
def energy_elec(ks, dm=None, h1e=None, vhf=None): ...
def prune_small_rho_grids_(ks, mol, dm, grids): ...
def define_xc_(ks, description, xctype: str = 'LDA', hyb: int = 0, rsh=(0, 0, 0)): ...

class KohnShamDFT:
    small_rho_cutoff: Incomplete
    xc: Incomplete
    nlc: str
    disp: Incomplete
    grids: Incomplete
    nlcgrids: Incomplete
    def __init__(self, xc: str = 'LDA,VWN') -> None: ...
    @property
    def omega(self): ...
    @omega.setter
    def omega(self, v) -> None: ...
    def dump_flags(self, verbose=None): ...
    define_xc_ = define_xc_
    def do_nlc(self): ...
    def to_rhf(self): ...
    def to_uhf(self): ...
    def to_ghf(self): ...
    def to_hf(self) -> None: ...
    def to_rks(self, xc=None): ...
    def to_uks(self, xc=None): ...
    def to_gks(self, xc=None): ...
    def reset(self, mol=None): ...
    def check_sanity(self): ...
    def initialize_grids(self, mol=None, dm=None): ...
    def to_gpu(self) -> None: ...

def init_guess_by_vsap(mf, mol=None): ...

class RKS(KohnShamDFT, hf.RHF):
    __doc__: Incomplete
    def __init__(self, mol, xc: str = 'LDA,VWN') -> None: ...
    def dump_flags(self, verbose=None): ...
    get_veff = get_veff
    get_vsap = get_vsap
    energy_elec = energy_elec
    init_guess_by_vsap = init_guess_by_vsap
    def nuc_grad_method(self): ...
    def to_hf(self): ...
    to_gpu = lib.to_gpu
