from pyscf import lib as lib
from pyscf.dft import rks as rks
from pyscf.lib import logger as logger
from pyscf.scf import hf as hf, uhf as uhf

def get_veff(ks, mol=None, dm=None, dm_last: int = 0, vhf_last: int = 0, hermi: int = 1): ...
def get_vsap(ks, mol=None): ...
def energy_elec(ks, dm=None, h1e=None, vhf=None): ...

class UKS(rks.KohnShamDFT, uhf.UHF):
    def __init__(self, mol, xc: str = 'LDA,VWN') -> None: ...
    def dump_flags(self, verbose=None): ...
    def initialize_grids(self, mol=None, dm=None): ...
    get_veff = get_veff
    get_vsap = get_vsap
    energy_elec = energy_elec
    init_guess_by_vsap = rks.init_guess_by_vsap
    def nuc_grad_method(self): ...
    def to_hf(self): ...
    to_gpu = lib.to_gpu
