from _typeshed import Incomplete
from pyscf import lib as lib
from numpy import ndarray
from typing import List, Optional, Tuple, Union

libdft: Incomplete

def transform_vxc(rho: ndarray, vxc: Union[List[ndarray], List[Optional[ndarray]], Tuple[ndarray, ndarray, None, ndarray], ndarray], xctype: str, spin: int = 0) -> ndarray: ...
def transform_fxc(rho: ndarray, vxc: Union[Tuple[ndarray, ndarray, None, ndarray], List[Optional[ndarray]], List[ndarray]], fxc: List[Optional[ndarray]], xctype: str, spin: int = 0) -> ndarray: ...
def transform_kxc(rho: ndarray, fxc: List[Optional[ndarray]], kxc: List[Optional[ndarray]], xctype: str, spin: int = 0) -> ndarray: ...
def transform_lxc(rho, fxc, kxc, lxc, xctype, spin: int = 0) -> None: ...
def transform_xc(rho: ndarray, xc_val: ndarray, xctype: str, spin: int, order: int) -> ndarray: ...
def count_combinations(nvar: int, order: int) -> int: ...
def ud2ts(v_ud: ndarray) -> ndarray: ...
def ts2ud(v_ts): ...
