from _typeshed import Incomplete
from pyscf import lib as lib

libdft: Incomplete

def transform_vxc(rho, vxc, xctype, spin: int = 0): ...
def transform_fxc(rho, vxc, fxc, xctype, spin: int = 0): ...
def transform_kxc(rho, fxc, kxc, xctype, spin: int = 0): ...
def transform_lxc(rho, fxc, kxc, lxc, xctype, spin: int = 0) -> None: ...
def transform_xc(rho, xc_val, xctype, spin, order): ...
def count_combinations(nvar, order): ...
def ud2ts(v_ud): ...
def ts2ud(v_ts): ...
