from pyscf.pbc.cc import ccsd as ccsd, eom_kccsd_ghf as eom_kccsd_ghf, eom_kccsd_rhf as eom_kccsd_rhf, eom_kccsd_uhf as eom_kccsd_uhf
from pyscf.pbc.cc.kccsd_rhf_ksymm import KsymAdaptedRCCSD as KsymAdaptedRCCSD

def RCCSD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
CCSD = RCCSD

def UCCSD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def GCCSD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def KGCCSD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def KRCCSD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
KCCSD = KRCCSD

def KUCCSD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
