from _typeshed import Incomplete
from pyscf import lib as lib
from pyscf.lib import logger as logger
from pyscf.lib.parameters import LARGE_DENOM as LARGE_DENOM, LOOSE_ZERO_TOL as LOOSE_ZERO_TOL
from pyscf.pbc.cc import eom_kccsd_ghf as eom_kgccsd, kintermediates_rhf as imdk
from pyscf.pbc.cc.kccsd_rhf import nested_to_vector as nested_to_vector, vector_to_nested as vector_to_nested
from pyscf.pbc.lib import kpts_helper as kpts_helper
from pyscf.pbc.mp.kmp2 import get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc, padded_mo_coeff as padded_mo_coeff, padding_k_idx as padding_k_idx

einsum = lib.einsum

def ipccsd_matvec(eom, vector, kshift, imds=None, diag=None): ...
def lipccsd_matvec(eom, vector, kshift, imds=None, diag=None): ...
def ipccsd_diag(eom, kshift, imds=None, diag=None): ...
def ipccsd_star_contract(eom, ipccsd_evals, ipccsd_evecs, lipccsd_evecs, kshift, imds=None): ...

class EOMIP(eom_kgccsd.EOMIP):
    matvec = ipccsd_matvec
    l_matvec = lipccsd_matvec
    get_diag = ipccsd_diag
    ccsd_star_contract = ipccsd_star_contract
    mask_frozen = eom_kgccsd.mask_frozen_ip
    @property
    def nkpts(self): ...
    @property
    def ip_vector_desc(self): ...
    def ip_amplitudes_to_vector(self, t1, t2): ...
    def ip_vector_to_amplitudes(self, vec): ...
    def vector_to_amplitudes(self, vector, kshift=None): ...
    def amplitudes_to_vector(self, r1, r2, kshift=None, kconserv=None): ...
    def vector_size(self): ...
    def make_imds(self, eris=None): ...

class EOMIP_Ta(EOMIP):
    def make_imds(self, eris=None): ...

def eaccsd_matvec(eom, vector, kshift, imds=None, diag=None): ...
def leaccsd_matvec(eom, vector, kshift, imds=None, diag=None): ...
def eaccsd_diag(eom, kshift, imds=None, diag=None): ...
def eaccsd_star_contract(eom, eaccsd_evals, eaccsd_evecs, leaccsd_evecs, kshift, imds=None): ...

class EOMEA(eom_kgccsd.EOMEA):
    matvec = eaccsd_matvec
    l_matvec = leaccsd_matvec
    get_diag = eaccsd_diag
    ccsd_star_contract = eaccsd_star_contract
    mask_frozen = eom_kgccsd.mask_frozen_ea
    @property
    def nkpts(self): ...
    @property
    def ea_vector_desc(self): ...
    def ea_amplitudes_to_vector(self, t1, t2, kshift=None, kconserv=None): ...
    def ea_vector_to_amplitudes(self, vec): ...
    def vector_to_amplitudes(self, vector, kshift=None): ...
    def amplitudes_to_vector(self, r1, r2, kshift=None, kconserv=None): ...
    def vector_size(self): ...
    def make_imds(self, eris=None): ...

class EOMEA_Ta(EOMEA):
    def make_imds(self, eris=None): ...

def eeccsd(eom, nroots: int = 1, koopmans: bool = False, guess=None, left: bool = False, eris=None, imds=None, partition=None, kptlist=None, dtype=None) -> None: ...
def eomee_ccsd_singlet(eom, nroots: int = 1, koopmans: bool = False, guess=None, left: bool = False, eris=None, imds=None, diag=None, partition=None, kptlist=None, dtype=None): ...
def vector_to_amplitudes_singlet(vector, nkpts, nmo, nocc, kconserv): ...
def amplitudes_to_vector_singlet(r1, r2, kconserv): ...
def join_indices(indices, struct): ...
def eeccsd_matvec(eom, vector, kshift, imds=None, diag=None) -> None: ...
def eeccsd_matvec_singlet(eom, vector, kshift, imds=None, diag=None): ...
def eeccsd_diag(eom, kshift: int = 0, imds=None): ...
def eeccsd_matvec_singlet_Hr1(eom, vector, kshift, imds=None): ...
def eeccsd_cis_approx_slow(eom, kshift, nroots: int = 1, imds=None, **kwargs): ...
def get_init_guess_cis(eom, kshift, nroots: int = 1, imds=None, **kwargs): ...
def cis_easy(eom, nroots: int = 1, kptlist=None, imds=None, **kwargs): ...

class EOMEE(eom_kgccsd.EOMEE):
    kernel = eeccsd
    eeccsd = eeccsd
    matvec = eeccsd_matvec
    get_diag = eeccsd_diag
    @property
    def nkpts(self): ...
    def vector_size(self, kshift: int = 0) -> None: ...
    def make_imds(self, eris=None): ...

class EOMEESinglet(EOMEE):
    kernel = eomee_ccsd_singlet
    eomee_ccsd_singlet = eomee_ccsd_singlet
    matvec = eeccsd_matvec_singlet
    get_init_guess = get_init_guess_cis
    cis = cis_easy
    def vector_size(self, kshift: int = 0): ...
    def gen_matvec(self, kshift, imds=None, left: bool = False, **kwargs): ...
    def vector_to_amplitudes(self, vector, kshift=None, nkpts=None, nmo=None, nocc=None, kconserv=None): ...
    def amplitudes_to_vector(self, r1, r2, kshift=None, kconserv=None): ...

class EOMEETriplet(EOMEE):
    def vector_size(self, kshift: int = 0) -> None: ...

class EOMEESpinFlip(EOMEE):
    def vector_size(self, kshift: int = 0) -> None: ...
imd = imdk

class _IMDS:
    verbose: Incomplete
    stdout: Incomplete
    t1: Incomplete
    t2: Incomplete
    eris: Incomplete
    kconserv: Incomplete
    made_ip_imds: bool
    made_ea_imds: bool
    def __init__(self, cc, eris=None) -> None: ...
    Woooo: Incomplete
    Wooov: Incomplete
    Wovoo: Incomplete
    def make_ip(self, ip_partition=None) -> None: ...
    def make_t3p2_ip(self, cc): ...
    Wvovv: Incomplete
    Wvvvo: Incomplete
    Wvvvv: Incomplete
    def make_ea(self, ea_partition=None) -> None: ...
    def make_t3p2_ea(self, cc): ...
    def make_t3p2_ip_ea(self, cc): ...
    Foo: Incomplete
    Fvv: Incomplete
    woOvV: Incomplete
    woVvO: Incomplete
    woVoV: Incomplete
    woOoO: Incomplete
    woOoV: Incomplete
    woVoO: Incomplete
    wvOvV: Incomplete
    wvVvV: Incomplete
    wvVvO: Incomplete
    made_ee_imds: bool
    def make_ee(self, ee_partition=None) -> None: ...
    def get_Wvvvv(self, ka, kb, kc): ...
