from _typeshed import Incomplete
from collections.abc import Generator
from pyscf.pbc.cc import kccsd_rhf as kccsd_rhf
from pyscf.pbc.lib.kpts_helper import VectorComposer as VectorComposer, VectorSplitter as VectorSplitter
from pyscf.pbc.mp.kmp2 import padding_k_idx as padding_k_idx

def iter_12(cc_or_eom, k) -> Generator[Incomplete]: ...
def amplitudes_to_vector(cc_or_eom, t1, t2, kshift: int = 0, kconserv=None): ...
def vector_to_amplitudes(cc_or_eom, vec, kshift: int = 0): ...
def vector_size(cc_or_eom, kshift: int = 0): ...
