from _typeshed import Incomplete
from pyscf import lib as lib
from pyscf.lib import logger as logger
from pyscf.lib.parameters import LARGE_DENOM as LARGE_DENOM, LOOSE_ZERO_TOL as LOOSE_ZERO_TOL
from pyscf.pbc.cc import eom_kccsd_ghf as eom_kgccsd, kintermediates_rhf as imdk
from pyscf.pbc.cc.kccsd_rhf import RCCSD, _ERIS, nested_to_vector as nested_to_vector, vector_to_nested as vector_to_nested
from pyscf.pbc.lib import kpts_helper as kpts_helper
from pyscf.pbc.mp.kmp2 import get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc, padded_mo_coeff as padded_mo_coeff, padding_k_idx as padding_k_idx
from numpy import float64, int64, ndarray
from typing import Callable, List, Optional, Tuple, Union

einsum = lib.einsum

def ipccsd_matvec(eom: Union[EOMIP, EOMIP_Ta], vector: ndarray, kshift: int, imds: Optional[_IMDS]=None, diag: Optional[ndarray]=None) -> ndarray: ...
def lipccsd_matvec(eom: Union[EOMIP_Ta, EOMIP], vector: ndarray, kshift: int, imds: Optional[_IMDS]=None, diag: Optional[ndarray]=None) -> ndarray: ...
def ipccsd_diag(eom: Union[EOMIP, EOMIP_Ta], kshift: int, imds: Optional[_IMDS]=None, diag: None=None) -> ndarray: ...
def ipccsd_star_contract(eom: "EOMIP_Ta", ipccsd_evals: ndarray, ipccsd_evecs: ndarray, lipccsd_evecs: ndarray, kshift: int, imds: Optional[_IMDS]=None) -> List[float64]: ...

class EOMIP(eom_kgccsd.EOMIP):
    matvec = ipccsd_matvec
    l_matvec = lipccsd_matvec
    get_diag = ipccsd_diag
    ccsd_star_contract = ipccsd_star_contract
    mask_frozen = eom_kgccsd.mask_frozen_ip
    @property
    def nkpts(self) -> int: ...
    @property
    def ip_vector_desc(self) -> List[Union[Tuple[int64], Tuple[int, int, int64, int64, int64]]]: ...
    def ip_amplitudes_to_vector(self, t1: ndarray, t2: ndarray) -> ndarray: ...
    def ip_vector_to_amplitudes(self, vec: ndarray) -> List[ndarray]: ...
    def vector_to_amplitudes(self, vector: ndarray, kshift: Optional[int]=None) -> List[ndarray]: ...
    def amplitudes_to_vector(self, r1: ndarray, r2: ndarray, kshift: Optional[int]=None, kconserv: Optional[ndarray]=None) -> ndarray: ...
    def vector_size(self) -> int64: ...
    def make_imds(self, eris: None=None) -> "_IMDS": ...

class EOMIP_Ta(EOMIP):
    def make_imds(self, eris: Optional[_ERIS]=None) -> "_IMDS": ...

def eaccsd_matvec(eom: Union[EOMEA_Ta, EOMEA], vector: ndarray, kshift: int, imds: Optional[_IMDS]=None, diag: Optional[ndarray]=None) -> ndarray: ...
def leaccsd_matvec(eom: Union[EOMEA_Ta, EOMEA], vector: ndarray, kshift: int, imds: Optional[_IMDS]=None, diag: Optional[ndarray]=None) -> ndarray: ...
def eaccsd_diag(eom: Union[EOMEA_Ta, EOMEA], kshift: int, imds: Optional[_IMDS]=None, diag: None=None) -> ndarray: ...
def eaccsd_star_contract(eom: "EOMEA_Ta", eaccsd_evals: ndarray, eaccsd_evecs: ndarray, leaccsd_evecs: ndarray, kshift: int, imds: Optional[_IMDS]=None) -> List[float64]: ...

class EOMEA(eom_kgccsd.EOMEA):
    matvec = eaccsd_matvec
    l_matvec = leaccsd_matvec
    get_diag = eaccsd_diag
    ccsd_star_contract = eaccsd_star_contract
    mask_frozen = eom_kgccsd.mask_frozen_ea
    @property
    def nkpts(self) -> int: ...
    @property
    def ea_vector_desc(self) -> List[Union[Tuple[int64], Tuple[int, int, int64, int64, int64]]]: ...
    def ea_amplitudes_to_vector(self, t1: ndarray, t2: ndarray, kshift: None=None, kconserv: None=None) -> ndarray: ...
    def ea_vector_to_amplitudes(self, vec: ndarray) -> List[ndarray]: ...
    def vector_to_amplitudes(self, vector: ndarray, kshift: Optional[int]=None) -> List[ndarray]: ...
    def amplitudes_to_vector(self, r1: ndarray, r2: ndarray, kshift: Optional[int]=None, kconserv: Optional[ndarray]=None) -> ndarray: ...
    def vector_size(self) -> int64: ...
    def make_imds(self, eris: Optional[_ERIS]=None) -> "_IMDS": ...

class EOMEA_Ta(EOMEA):
    def make_imds(self, eris: Optional[_ERIS]=None) -> "_IMDS": ...

def eeccsd(eom, nroots: int = 1, koopmans: bool = False, guess=None, left: bool = False, eris=None, imds=None, partition=None, kptlist=None, dtype=None) -> None: ...
def eomee_ccsd_singlet(eom: "EOMEESinglet", nroots: int = 1, koopmans: bool = False, guess: None=None, left: bool = False, eris: None=None, imds: None=None, diag: None=None, partition: None=None, kptlist: Optional[List[int]]=None, dtype: None=None) -> Tuple[List[ndarray], List[List[ndarray]]]: ...
def vector_to_amplitudes_singlet(vector: ndarray, nkpts: int, nmo: int64, nocc: int64, kconserv: ndarray) -> List[ndarray]: ...
def amplitudes_to_vector_singlet(r1: ndarray, r2: ndarray, kconserv: ndarray) -> ndarray: ...
def join_indices(indices, struct): ...
def eeccsd_matvec(eom, vector, kshift, imds=None, diag=None) -> None: ...
def eeccsd_matvec_singlet(eom: "EOMEESinglet", vector: ndarray, kshift: int, imds: Optional[_IMDS]=None, diag: Optional[ndarray]=None) -> ndarray: ...
def eeccsd_diag(eom: "EOMEESinglet", kshift: int = 0, imds: Optional[_IMDS]=None) -> ndarray: ...
def eeccsd_matvec_singlet_Hr1(eom: "EOMEESinglet", vector: ndarray, kshift: Union[int64, int], imds: Optional[_IMDS]=None) -> ndarray: ...
def eeccsd_cis_approx_slow(eom: "EOMEESinglet", kshift: Union[int64, int], nroots: int = 1, imds: Optional[_IMDS]=None, **kwargs) -> Tuple[ndarray, ndarray]: ...
def get_init_guess_cis(eom: "EOMEESinglet", kshift: int, nroots: int = 1, imds: Optional[_IMDS]=None, **kwargs) -> List[ndarray]: ...
def cis_easy(eom: "EOMEESinglet", nroots: int = 1, kptlist: Optional[ndarray]=None, imds: None=None, **kwargs) -> Tuple[List[ndarray], List[ndarray]]: ...

class EOMEE(eom_kgccsd.EOMEE):
    kernel = eeccsd
    eeccsd = eeccsd
    matvec = eeccsd_matvec
    get_diag = eeccsd_diag
    @property
    def nkpts(self) -> int: ...
    def vector_size(self, kshift: int = 0) -> None: ...
    def make_imds(self, eris: None=None) -> "_IMDS": ...

class EOMEESinglet(EOMEE):
    kernel = eomee_ccsd_singlet
    eomee_ccsd_singlet = eomee_ccsd_singlet
    matvec = eeccsd_matvec_singlet
    get_init_guess = get_init_guess_cis
    cis = cis_easy
    def vector_size(self, kshift: int = 0) -> int64: ...
    def gen_matvec(self, kshift: int, imds: Optional[_IMDS]=None, left: bool = False, **kwargs) -> Tuple[Callable, ndarray]: ...
    def vector_to_amplitudes(self, vector: ndarray, kshift: Optional[int]=None, nkpts: None=None, nmo: None=None, nocc: None=None, kconserv: None=None) -> List[ndarray]: ...
    def amplitudes_to_vector(self, r1, r2, kshift=None, kconserv=None): ...

class EOMEETriplet(EOMEE):
    def vector_size(self, kshift: int = 0) -> None: ...

class EOMEESpinFlip(EOMEE):
    def vector_size(self, kshift: int = 0) -> None: ...
imd = imdk

class _IMDS:
    verbose: Incomplete
    stdout: Incomplete
    t1: Incomplete
    t2: Incomplete
    eris: Incomplete
    kconserv: Incomplete
    made_ip_imds: bool
    made_ea_imds: bool
    def __init__(self, cc: RCCSD, eris: Optional[_ERIS]=None) -> None: ...
    Woooo: Incomplete
    Wooov: Incomplete
    Wovoo: Incomplete
    def make_ip(self, ip_partition: None=None) -> None: ...
    def make_t3p2_ip(self, cc: RCCSD) -> "_IMDS": ...
    Wvovv: Incomplete
    Wvvvo: Incomplete
    Wvvvv: Incomplete
    def make_ea(self, ea_partition: None=None) -> None: ...
    def make_t3p2_ea(self, cc: RCCSD) -> "_IMDS": ...
    def make_t3p2_ip_ea(self, cc): ...
    Foo: Incomplete
    Fvv: Incomplete
    woOvV: Incomplete
    woVvO: Incomplete
    woVoV: Incomplete
    woOoO: Incomplete
    woOoV: Incomplete
    woVoO: Incomplete
    wvOvV: Incomplete
    wvVvV: Incomplete
    wvVvO: Incomplete
    made_ee_imds: bool
    def make_ee(self, ee_partition: None=None) -> None: ...
    def get_Wvvvv(self, ka: Union[int64, int], kb: Union[int64, int], kc: Union[int64, int]) -> ndarray: ...
