from _typeshed import Incomplete
from pyscf import lib as lib
from pyscf.lib import logger as logger
from pyscf.lib.parameters import LARGE_DENOM as LARGE_DENOM, LOOSE_ZERO_TOL as LOOSE_ZERO_TOL
from pyscf.pbc.cc import eom_kccsd_ghf as eom_kgccsd, kccsd as kccsd, kintermediates_uhf as kintermediates_uhf
from pyscf.pbc.lib import kpts_helper as kpts_helper
from pyscf.pbc.mp.kump2 import get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc, padded_mo_coeff as padded_mo_coeff, padding_k_idx as padding_k_idx
from numpy import int64, ndarray
from pyscf.cc.uccsd import _ChemistsERIs
from pyscf.pbc.cc.kccsd_uhf import KUCCSD
from typing import Callable, List, Optional, Tuple, Union

einsum = lib.einsum

def amplitudes_to_vector_ip(r1: Union[List[ndarray], Tuple[ndarray, ndarray]], r2: Union[Tuple[ndarray, ndarray, ndarray, ndarray], List[ndarray]], kshift: int, kconserv: ndarray) -> ndarray: ...
def vector_to_amplitudes_ip(vector: ndarray, kshift: int, nkpts: int, nmo: Union[Tuple[int, int], Tuple[int64, int64]], nocc: Union[Tuple[int, int], Tuple[int64, int64]], kconserv: ndarray) -> Tuple[Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray, ndarray]]: ...
def ipccsd_matvec(eom: "EOMIP", vector: ndarray, kshift: int, imds: Optional[_IMDS]=None, diag: Optional[ndarray]=None) -> ndarray: ...
def ipccsd_diag(eom: "EOMIP", kshift: int, imds: Optional[_IMDS]=None) -> ndarray: ...
def mask_frozen_ip(eom: "EOMIP", vector: ndarray, kshift: int, const: Union[float, int]=...) -> ndarray: ...
def get_padding_k_idx(eom: Union[EOMEA, EOMIP], cc: KUCCSD) -> Tuple[Tuple[List[ndarray], List[ndarray]], Tuple[List[ndarray], List[ndarray]]]: ...

class EOMIP(eom_kgccsd.EOMIP):
    kpts: Incomplete
    def __init__(self, cc: KUCCSD) -> None: ...
    get_diag = ipccsd_diag
    matvec = ipccsd_matvec
    get_padding_k_idx = get_padding_k_idx
    mask_frozen = mask_frozen_ip
    def get_init_guess(self, kshift: int, nroots: int = 1, koopmans: bool = False, diag: Optional[ndarray]=None) -> List[ndarray]: ...
    def gen_matvec(self, kshift: int, imds: Optional[_IMDS]=None, left: bool = False, **kwargs) -> Tuple[Callable, ndarray]: ...
    def vector_to_amplitudes(self, vector: ndarray, kshift: int, nkpts: Optional[int]=None, nmo: Optional[Union[Tuple[int, int], Tuple[int64, int64]]]=None, nocc: Optional[Union[Tuple[int, int], Tuple[int64, int64]]]=None, kconserv: Optional[ndarray]=None) -> Tuple[Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray, ndarray]]: ...
    def amplitudes_to_vector(self, r1: Tuple[ndarray, ndarray], r2: Tuple[ndarray, ndarray, ndarray, ndarray], kshift: int, kconserv: Optional[ndarray]=None) -> ndarray: ...
    def vector_size(self) -> int64: ...
    def make_imds(self, eris: None=None, t1: None=None, t2: None=None) -> "_IMDS": ...

def amplitudes_to_vector_ea(r1: Union[List[ndarray], Tuple[ndarray, ndarray]], r2: Union[Tuple[ndarray, ndarray, ndarray, ndarray], List[ndarray]], kshift: int, kconserv: ndarray) -> ndarray: ...
def vector_to_amplitudes_ea(vector: ndarray, kshift: int, nkpts: int, nmo: Union[Tuple[int, int], Tuple[int64, int64]], nocc: Union[Tuple[int, int], Tuple[int64, int64]], kconserv: ndarray) -> Tuple[Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray, ndarray]]: ...
def eaccsd_matvec(eom: "EOMEA", vector: ndarray, kshift: int, imds: Optional[_IMDS]=None, diag: Optional[ndarray]=None) -> ndarray: ...
def eaccsd_diag(eom: "EOMEA", kshift: int, imds: Optional[_IMDS]=None) -> ndarray: ...
def mask_frozen_ea(eom: "EOMEA", vector: ndarray, kshift: int, const: Union[float, int]=...) -> ndarray: ...

class EOMEA(eom_kgccsd.EOMEA):
    kpts: Incomplete
    def __init__(self, cc: KUCCSD) -> None: ...
    get_diag = eaccsd_diag
    matvec = eaccsd_matvec
    get_padding_k_idx = get_padding_k_idx
    mask_frozen = mask_frozen_ea
    def get_init_guess(self, kshift: int, nroots: int = 1, koopmans: bool = False, diag: Optional[ndarray]=None) -> List[ndarray]: ...
    def vector_to_amplitudes(self, vector: ndarray, kshift: int, nkpts: Optional[int]=None, nmo: Optional[Union[Tuple[int, int], Tuple[int64, int64]]]=None, nocc: Optional[Union[Tuple[int, int], Tuple[int64, int64]]]=None, kconserv: Optional[ndarray]=None) -> Tuple[Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray, ndarray]]: ...
    def amplitudes_to_vector(self, r1: Tuple[ndarray, ndarray], r2: Tuple[ndarray, ndarray, ndarray, ndarray], kshift: int, kconserv: None=None) -> ndarray: ...
    def vector_size(self) -> int64: ...
    def make_imds(self, eris: Optional[_ChemistsERIs]=None, t1: None=None, t2: None=None) -> "_IMDS": ...

class _IMDS:
    verbose: Incomplete
    kconserv: Incomplete
    stdout: Incomplete
    t1: Incomplete
    t2: Incomplete
    eris: Incomplete
    made_ip_imds: bool
    made_ea_imds: bool
    made_ee_imds: bool
    def __init__(self, cc: KUCCSD, eris: Optional[_ChemistsERIs]=None, t1: None=None, t2: None=None) -> None: ...
    def make_ip(self) -> "_IMDS": ...
    Wvvvv: Incomplete
    def make_ea(self) -> "_IMDS": ...
    def make_ee(self) -> None: ...
    def get_Wvvvv(self, ka: int, kb: int64, kc: int) -> Tuple[ndarray, ndarray, ndarray]: ...
