from _typeshed import Incomplete
from pyscf import lib as lib
from pyscf.lib import logger as logger
from pyscf.lib.parameters import LARGE_DENOM as LARGE_DENOM, LOOSE_ZERO_TOL as LOOSE_ZERO_TOL
from pyscf.pbc.cc import eom_kccsd_ghf as eom_kgccsd, kccsd as kccsd, kintermediates_uhf as kintermediates_uhf
from pyscf.pbc.lib import kpts_helper as kpts_helper
from pyscf.pbc.mp.kump2 import get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc, padded_mo_coeff as padded_mo_coeff, padding_k_idx as padding_k_idx

einsum = lib.einsum

def amplitudes_to_vector_ip(r1, r2, kshift, kconserv): ...
def vector_to_amplitudes_ip(vector, kshift, nkpts, nmo, nocc, kconserv): ...
def ipccsd_matvec(eom, vector, kshift, imds=None, diag=None): ...
def ipccsd_diag(eom, kshift, imds=None): ...
def mask_frozen_ip(eom, vector, kshift, const=...): ...
def get_padding_k_idx(eom, cc): ...

class EOMIP(eom_kgccsd.EOMIP):
    kpts: Incomplete
    def __init__(self, cc) -> None: ...
    get_diag = ipccsd_diag
    matvec = ipccsd_matvec
    get_padding_k_idx = get_padding_k_idx
    mask_frozen = mask_frozen_ip
    def get_init_guess(self, kshift, nroots: int = 1, koopmans: bool = False, diag=None): ...
    def gen_matvec(self, kshift, imds=None, left: bool = False, **kwargs): ...
    def vector_to_amplitudes(self, vector, kshift, nkpts=None, nmo=None, nocc=None, kconserv=None): ...
    def amplitudes_to_vector(self, r1, r2, kshift, kconserv=None): ...
    def vector_size(self): ...
    def make_imds(self, eris=None, t1=None, t2=None): ...

def amplitudes_to_vector_ea(r1, r2, kshift, kconserv): ...
def vector_to_amplitudes_ea(vector, kshift, nkpts, nmo, nocc, kconserv): ...
def eaccsd_matvec(eom, vector, kshift, imds=None, diag=None): ...
def eaccsd_diag(eom, kshift, imds=None): ...
def mask_frozen_ea(eom, vector, kshift, const=...): ...

class EOMEA(eom_kgccsd.EOMEA):
    kpts: Incomplete
    def __init__(self, cc) -> None: ...
    get_diag = eaccsd_diag
    matvec = eaccsd_matvec
    get_padding_k_idx = get_padding_k_idx
    mask_frozen = mask_frozen_ea
    def get_init_guess(self, kshift, nroots: int = 1, koopmans: bool = False, diag=None): ...
    def vector_to_amplitudes(self, vector, kshift, nkpts=None, nmo=None, nocc=None, kconserv=None): ...
    def amplitudes_to_vector(self, r1, r2, kshift, kconserv=None): ...
    def vector_size(self): ...
    def make_imds(self, eris=None, t1=None, t2=None): ...

class _IMDS:
    verbose: Incomplete
    kconserv: Incomplete
    stdout: Incomplete
    t1: Incomplete
    t2: Incomplete
    eris: Incomplete
    made_ip_imds: bool
    made_ea_imds: bool
    made_ee_imds: bool
    def __init__(self, cc, eris=None, t1=None, t2=None) -> None: ...
    def make_ip(self): ...
    Wvvvv: Incomplete
    def make_ea(self): ...
    def make_ee(self) -> None: ...
    def get_Wvvvv(self, ka, kb, kc): ...
