from _typeshed import Incomplete
from pyscf import lib as lib
from pyscf.cc import eom_rccsd as eom_rccsd
from pyscf.lib import logger as logger
from pyscf.lib.parameters import LARGE_DENOM as LARGE_DENOM, LOOSE_ZERO_TOL as LOOSE_ZERO_TOL
from pyscf.pbc.lib import kpts_helper as kpts_helper
from pyscf.pbc.mp.kmp2 import get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc, padded_mo_coeff as padded_mo_coeff, padding_k_idx as padding_k_idx

einsum = lib.einsum

def kernel(eom, nroots: int = 1, koopmans: bool = False, guess=None, left: bool = False, eris=None, imds=None, partition=None, kptlist=None, dtype=None, **kwargs): ...
def enforce_2p_spin_doublet(r2, kconserv, kshift, orbspin, excitation): ...
def get_padding_k_idx(eom, cc): ...
def enforce_2p_spin_ip_doublet(r2, kconserv, kshift, orbspin): ...
def spin2spatial_ip_doublet(r1, r2, kconserv, kshift, orbspin): ...
def spatial2spin_ip_doublet(r1, r2, kconserv, kshift, orbspin=None): ...
def vector_to_amplitudes_ip(vector, kshift, nkpts, nmo, nocc, kconserv): ...
def amplitudes_to_vector_ip(r1, r2, kshift, kconserv): ...
def ipccsd_matvec(eom, vector, kshift, imds=None, diag=None): ...
def lipccsd_matvec(eom, vector, kshift, imds=None, diag=None): ...
def ipccsd_diag(eom, kshift, imds=None): ...
def ipccsd_star_contract(eom, ipccsd_evals, ipccsd_evecs, lipccsd_evecs, kshift, imds=None): ...
def ipccsd(eom, nroots: int = 1, koopmans: bool = False, guess=None, left: bool = False, eris=None, imds=None, partition=None, kptlist=None, dtype=None, **kwargs): ...
def perturbed_ccsd_kernel(eom, nroots: int = 1, koopmans: bool = False, right_guess=None, left_guess=None, eris=None, imds=None, partition=None, kptlist=None, dtype=None): ...
def ipccsd_star(eom, nroots: int = 1, koopmans: bool = False, right_guess=None, left_guess=None, eris=None, imds=None, partition=None, kptlist=None, dtype=None, **kwargs): ...
def mask_frozen_ip(eom, vector, kshift, const=...): ...

class EOMIP(eom_rccsd.EOMIP):
    kpts: Incomplete
    kconserv: Incomplete
    def __init__(self, cc) -> None: ...
    kernel = ipccsd
    ipccsd = ipccsd
    ipccsd_star = ipccsd_star
    ccsd_star_contract = ipccsd_star_contract
    get_diag = ipccsd_diag
    matvec = ipccsd_matvec
    l_matvec = lipccsd_matvec
    mask_frozen = mask_frozen_ip
    get_padding_k_idx = get_padding_k_idx
    def ipccsd_star_contract(self, ipccsd_evals, ipccsd_evecs, lipccsd_evecs, kshift, imds=None): ...
    def get_init_guess(self, kshift, nroots: int = 1, koopmans: bool = False, diag=None): ...
    @property
    def nkpts(self): ...
    def gen_matvec(self, kshift, imds=None, left: bool = False, **kwargs): ...
    def vector_to_amplitudes(self, vector, kshift=None, nkpts=None, nmo=None, nocc=None, kconserv=None): ...
    def amplitudes_to_vector(self, r1, r2, kshift, kconserv=None): ...
    def vector_size(self): ...
    def make_imds(self, eris=None): ...

class EOMIP_Ta(EOMIP):
    def make_imds(self, eris=None): ...

def enforce_2p_spin_ea_doublet(r2, kconserv, kshift, orbspin): ...
def spin2spatial_ea_doublet(r1, r2, kconserv, kshift, orbspin): ...
def spatial2spin_ea_doublet(r1, r2, kconserv, kshift, orbspin=None): ...
def amplitudes_to_vector_ea(r1, r2, kshift, kconserv): ...
def vector_to_amplitudes_ea(vector, kshift, nkpts, nmo, nocc, kconserv): ...
def eaccsd(eom, nroots: int = 1, koopmans: bool = False, guess=None, left: bool = False, eris=None, imds=None, partition=None, kptlist=None, dtype=None): ...
def eaccsd_matvec(eom, vector, kshift, imds=None, diag=None): ...
def leaccsd_matvec(eom, vector, kshift, imds=None, diag=None): ...
def eaccsd_diag(eom, kshift, imds=None): ...
def eaccsd_star_contract(eom, eaccsd_evals, eaccsd_evecs, leaccsd_evecs, kshift, imds=None): ...
def eaccsd_star(eom, nroots: int = 1, koopmans: bool = False, right_guess=None, left_guess=None, eris=None, imds=None, partition=None, kptlist=None, dtype=None, **kwargs): ...
def mask_frozen_ea(eom, vector, kshift, const=...): ...

class EOMEA(eom_rccsd.EOMEA):
    kpts: Incomplete
    kconserv: Incomplete
    def __init__(self, cc) -> None: ...
    kernel = eaccsd
    eaccsd = eaccsd
    eaccsd_star = eaccsd_star
    ccsd_star_contract = eaccsd_star_contract
    get_diag = eaccsd_diag
    matvec = eaccsd_matvec
    l_matvec = leaccsd_matvec
    mask_frozen = mask_frozen_ea
    get_padding_k_idx = get_padding_k_idx
    def eaccsd_star_contract(self, eaccsd_evals, eaccsd_evecs, leaccsd_evecs, kshift, imds=None): ...
    def get_init_guess(self, kshift, nroots: int = 1, koopmans: bool = False, diag=None): ...
    @property
    def nkpts(self): ...
    def gen_matvec(self, kshift, imds=None, left: bool = False, **kwargs): ...
    def vector_to_amplitudes(self, vector, kshift=None, nkpts=None, nmo=None, nocc=None, kconserv=None): ...
    def amplitudes_to_vector(self, r1, r2, kshift, kconserv=None): ...
    def vector_size(self): ...
    def make_imds(self, eris=None): ...

class EOMEA_Ta(EOMEA):
    def make_imds(self, eris=None): ...

def kernel_ee(eom, nroots: int = 1, koopmans: bool = False, guess=None, left: bool = False, eris=None, imds=None, partition=None, kptlist=None, dtype=None, **kwargs): ...
def eeccsd(eom, nroots: int = 1, koopmans: bool = False, guess=None, left: bool = False, eris=None, imds=None, partition=None, kptlist=None, dtype=None): ...
def eeccsd_matvec(eom, vector, kshift, imds=None, diag=None): ...
def eeccsd_diag(eom, kshift, imds=None): ...
def vector_to_amplitudes_ee(vector, kshift, nkpts, nmo, nocc, kconserv): ...
def amplitudes_to_vector_ee(r1, r2, kshift, kconserv): ...

class EOMEE(eom_rccsd.EOM):
    kpts: Incomplete
    kconserv: Incomplete
    debug_vals: Incomplete
    def __init__(self, cc) -> None: ...
    kernel = eeccsd
    eeccsd = eeccsd
    matvec = eeccsd_matvec
    get_diag = eeccsd_diag
    @property
    def nkpts(self): ...
    def vector_size(self, kshift: int = 0): ...
    def get_init_guess(self, kshift, nroots: int = 1, koopmans: bool = False, diag=None, **kwargs): ...
    def gen_matvec(self, kshift, imds=None, left: bool = False, **kwargs): ...
    def vector_to_amplitudes(self, vector, kshift=None, nkpts=None, nmo=None, nocc=None, kconserv=None): ...
    def amplitudes_to_vector(self, r1, r2, kshift, kconserv=None): ...
    def get_kconserv_ee_r1(self, kshift: int = 0): ...
    def get_kconserv_ee_r2(self, kshift: int = 0): ...
    def make_imds(self, eris=None): ...

class _IMDS:
    verbose: Incomplete
    kconserv: Incomplete
    stdout: Incomplete
    eris: Incomplete
    made_ip_imds: bool
    made_ea_imds: bool
    made_ee_imds: bool
    def __init__(self, cc, eris=None) -> None: ...
    Woooo: Incomplete
    Wooov: Incomplete
    Wovoo: Incomplete
    def make_ip(self): ...
    t1: Incomplete
    t2: Incomplete
    def make_t3p2_ip(self, cc): ...
    Wvovv: Incomplete
    Wvvvv: Incomplete
    Wvvvo: Incomplete
    def make_ea(self): ...
    def make_t3p2_ea(self, cc): ...
    def make_ee(self): ...
