from _typeshed import Incomplete
from pyscf import lib as lib
from pyscf.cc import eom_rccsd as eom_rccsd
from pyscf.lib import logger as logger
from pyscf.lib.parameters import LARGE_DENOM as LARGE_DENOM, LOOSE_ZERO_TOL as LOOSE_ZERO_TOL
from pyscf.pbc.lib import kpts_helper as kpts_helper
from pyscf.pbc.mp.kmp2 import get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc, padded_mo_coeff as padded_mo_coeff, padding_k_idx as padding_k_idx
from numpy import float64, int64, ndarray
from pyscf.cc.eom_rccsd import EOM
from pyscf.cc.gccsd import _PhysicistsERIs
from pyscf.pbc.cc.eom_kccsd_rhf import EOMEA_Ta, EOMEESinglet, EOMIP, EOMIP_Ta
from pyscf.pbc.cc.kccsd import GCCSD
from pyscf.pbc.cc.kccsd_rhf import RCCSD, _ERIS
from pyscf.pbc.cc.kccsd_uhf import KUCCSD
from typing import Callable, List, Optional, Tuple, Union

einsum = lib.einsum

def kernel(eom: EOM, nroots: int = 1, koopmans: bool = False, guess: None=None, left: bool = False, eris: Optional[Union[_PhysicistsERIs, _ERIS]]=None, imds: Optional[Union[Incomplete, Incomplete]]=None, partition: None=None, kptlist: Optional[Union[Tuple[int], List[int]]]=None, dtype: None=None, **kwargs) -> Tuple[ndarray, ndarray, ndarray]: ...
def enforce_2p_spin_doublet(r2: ndarray, kconserv: ndarray, kshift: int, orbspin: ndarray, excitation: str) -> ndarray: ...
def get_padding_k_idx(eom: EOM, cc: Union[GCCSD, RCCSD]) -> Tuple[List[ndarray], List[ndarray]]: ...
def enforce_2p_spin_ip_doublet(r2: ndarray, kconserv: ndarray, kshift: int, orbspin: ndarray) -> ndarray: ...
def spin2spatial_ip_doublet(r1: ndarray, r2: ndarray, kconserv: ndarray, kshift: int, orbspin: ndarray) -> Tuple[List[ndarray], List[ndarray]]: ...
def spatial2spin_ip_doublet(r1: List[ndarray], r2: List[ndarray], kconserv: ndarray, kshift: int, orbspin: Optional[ndarray]=None) -> Tuple[ndarray, ndarray]: ...
def vector_to_amplitudes_ip(vector: ndarray, kshift: int, nkpts: int, nmo: Union[int64, int], nocc: Union[int64, int], kconserv: ndarray) -> List[ndarray]: ...
def amplitudes_to_vector_ip(r1: ndarray, r2: ndarray, kshift: int, kconserv: ndarray) -> ndarray: ...
def ipccsd_matvec(eom: Union[EOMIP, EOMIP_Ta], vector: ndarray, kshift: int, imds: Optional[Incomplete]=None, diag: Optional[ndarray]=None) -> ndarray: ...
def lipccsd_matvec(eom: Union[EOMIP, EOMIP_Ta], vector: ndarray, kshift: int, imds: Optional[Incomplete]=None, diag: Optional[ndarray]=None) -> ndarray: ...
def ipccsd_diag(eom: Union[EOMIP, EOMIP_Ta], kshift: int, imds: Optional[Incomplete]=None) -> ndarray: ...
def ipccsd_star_contract(eom: Union[EOMIP, EOMIP_Ta], ipccsd_evals: ndarray, ipccsd_evecs: ndarray, lipccsd_evecs: ndarray, kshift: int, imds: Optional[Incomplete]=None) -> List[float64]: ...
def ipccsd(eom: EOM, nroots: int = 1, koopmans: bool = False, guess: None=None, left: bool = False, eris: Optional[_ERIS]=None, imds: Optional[Union[Incomplete, Incomplete]]=None, partition: None=None, kptlist: Optional[Union[Tuple[int], List[int]]]=None, dtype: None=None, **kwargs) -> Tuple[ndarray, ndarray]: ...
def perturbed_ccsd_kernel(eom: EOM, nroots: int = 1, koopmans: bool = False, right_guess: None=None, left_guess: None=None, eris: Optional[Union[_PhysicistsERIs, _ERIS]]=None, imds: Optional[Incomplete]=None, partition: None=None, kptlist: Optional[Union[Tuple[int], List[int]]]=None, dtype: None=None) -> List[List[float64]]: ...
def ipccsd_star(eom: Union[EOMIP_Ta, EOMIP, EOMIP_Ta], nroots: int = 1, koopmans: bool = False, right_guess: None=None, left_guess: None=None, eris: Optional[Union[_PhysicistsERIs, _ERIS]]=None, imds: Optional[Incomplete]=None, partition: None=None, kptlist: Optional[Union[Tuple[int], List[int]]]=None, dtype: None=None, **kwargs) -> List[List[float64]]: ...
def mask_frozen_ip(eom: Union[EOMIP_Ta, EOMIP, EOMIP_Ta, EOMIP], vector: ndarray, kshift: int, const: Union[float, int]=...) -> ndarray: ...

class EOMIP(eom_rccsd.EOMIP):
    kpts: Incomplete
    kconserv: Incomplete
    def __init__(self, cc: Union[RCCSD, GCCSD, KUCCSD]) -> None: ...
    kernel = ipccsd
    ipccsd = ipccsd
    ipccsd_star = ipccsd_star
    ccsd_star_contract = ipccsd_star_contract
    get_diag = ipccsd_diag
    matvec = ipccsd_matvec
    l_matvec = lipccsd_matvec
    mask_frozen = mask_frozen_ip
    get_padding_k_idx = get_padding_k_idx
    def ipccsd_star_contract(self, ipccsd_evals, ipccsd_evecs, lipccsd_evecs, kshift, imds=None): ...
    def get_init_guess(self, kshift: int, nroots: int = 1, koopmans: bool = False, diag: Optional[ndarray]=None) -> List[ndarray]: ...
    @property
    def nkpts(self) -> int: ...
    def gen_matvec(self, kshift: int, imds: Optional[Union[Incomplete, Incomplete]]=None, left: bool = False, **kwargs) -> Tuple[Callable, ndarray]: ...
    def vector_to_amplitudes(self, vector: ndarray, kshift: Optional[int]=None, nkpts: None=None, nmo: None=None, nocc: None=None, kconserv: None=None) -> List[ndarray]: ...
    def amplitudes_to_vector(self, r1: ndarray, r2: ndarray, kshift: int, kconserv: Optional[ndarray]=None) -> ndarray: ...
    def vector_size(self) -> int64: ...
    def make_imds(self, eris: Optional[_PhysicistsERIs]=None) -> Incomplete: ...

class EOMIP_Ta(EOMIP):
    def make_imds(self, eris: Optional[_PhysicistsERIs]=None) -> Incomplete: ...

def enforce_2p_spin_ea_doublet(r2: ndarray, kconserv: ndarray, kshift: int, orbspin: ndarray) -> ndarray: ...
def spin2spatial_ea_doublet(r1: ndarray, r2: ndarray, kconserv: ndarray, kshift: int, orbspin: ndarray) -> Tuple[List[ndarray], List[ndarray]]: ...
def spatial2spin_ea_doublet(r1: List[ndarray], r2: List[ndarray], kconserv: ndarray, kshift: int, orbspin: Optional[ndarray]=None) -> Tuple[ndarray, ndarray]: ...
def amplitudes_to_vector_ea(r1: ndarray, r2: ndarray, kshift: int, kconserv: ndarray) -> ndarray: ...
def vector_to_amplitudes_ea(vector: ndarray, kshift: int, nkpts: int, nmo: Union[int64, int], nocc: Union[int64, int], kconserv: ndarray) -> List[ndarray]: ...
def eaccsd(eom: Union[Incomplete, Incomplete, EOMEA_Ta, EOMEA_Ta, Incomplete], nroots: int = 1, koopmans: bool = False, guess: None=None, left: bool = False, eris: Optional[_ERIS]=None, imds: Optional[Incomplete]=None, partition: None=None, kptlist: Optional[Union[Tuple[int], List[int]]]=None, dtype: None=None) -> Tuple[ndarray, ndarray]: ...
def eaccsd_matvec(eom: Union[Incomplete, EOMEA_Ta], vector: ndarray, kshift: int, imds: Optional[Incomplete]=None, diag: Optional[ndarray]=None) -> ndarray: ...
def leaccsd_matvec(eom: Union[Incomplete, EOMEA_Ta], vector: ndarray, kshift: int, imds: Optional[Incomplete]=None, diag: Optional[ndarray]=None) -> ndarray: ...
def eaccsd_diag(eom: Union[Incomplete, EOMEA_Ta], kshift: int, imds: Optional[Incomplete]=None) -> ndarray: ...
def eaccsd_star_contract(eom: Union[Incomplete, EOMEA_Ta], eaccsd_evals: ndarray, eaccsd_evecs: ndarray, leaccsd_evecs: ndarray, kshift: int, imds: Optional[Incomplete]=None) -> List[float64]: ...
def eaccsd_star(eom: Union[EOMEA_Ta, Incomplete, EOMEA_Ta], nroots: int = 1, koopmans: bool = False, right_guess: None=None, left_guess: None=None, eris: Optional[Union[_PhysicistsERIs, _ERIS]]=None, imds: Optional[Incomplete]=None, partition: None=None, kptlist: Optional[Union[Tuple[int], List[int]]]=None, dtype: None=None, **kwargs) -> List[List[float64]]: ...
def mask_frozen_ea(eom: Union[EOMEA_Ta, Incomplete, Incomplete, EOMEA_Ta], vector: ndarray, kshift: int, const: Union[float, int]=...) -> ndarray: ...

class EOMEA(eom_rccsd.EOMEA):
    kpts: Incomplete
    kconserv: Incomplete
    def __init__(self, cc: Union[RCCSD, GCCSD, KUCCSD]) -> None: ...
    kernel = eaccsd
    eaccsd = eaccsd
    eaccsd_star = eaccsd_star
    ccsd_star_contract = eaccsd_star_contract
    get_diag = eaccsd_diag
    matvec = eaccsd_matvec
    l_matvec = leaccsd_matvec
    mask_frozen = mask_frozen_ea
    get_padding_k_idx = get_padding_k_idx
    def eaccsd_star_contract(self, eaccsd_evals, eaccsd_evecs, leaccsd_evecs, kshift, imds=None): ...
    def get_init_guess(self, kshift: int, nroots: int = 1, koopmans: bool = False, diag: Optional[ndarray]=None) -> List[ndarray]: ...
    @property
    def nkpts(self) -> int: ...
    def gen_matvec(self, kshift: int, imds: Optional[Union[Incomplete, Incomplete, Incomplete]]=None, left: bool = False, **kwargs) -> Tuple[Callable, ndarray]: ...
    def vector_to_amplitudes(self, vector: ndarray, kshift: Optional[int]=None, nkpts: None=None, nmo: None=None, nocc: None=None, kconserv: None=None) -> List[ndarray]: ...
    def amplitudes_to_vector(self, r1: ndarray, r2: ndarray, kshift: int, kconserv: Optional[ndarray]=None) -> ndarray: ...
    def vector_size(self) -> int64: ...
    def make_imds(self, eris: Optional[_PhysicistsERIs]=None) -> Incomplete: ...

class EOMEA_Ta(EOMEA):
    def make_imds(self, eris: Optional[_PhysicistsERIs]=None) -> Incomplete: ...

def kernel_ee(eom: Union[EOMEE, EOMEESinglet], nroots: int = 1, koopmans: bool = False, guess: None=None, left: bool = False, eris: None=None, imds: Optional[Incomplete]=None, partition: None=None, kptlist: Optional[List[int]]=None, dtype: None=None, **kwargs) -> Tuple[List[ndarray], List[ndarray], List[List[ndarray]]]: ...
def eeccsd(eom: "EOMEE", nroots: int = 1, koopmans: bool = False, guess: None=None, left: bool = False, eris: None=None, imds: Optional[Incomplete]=None, partition: None=None, kptlist: Optional[List[int]]=None, dtype: None=None) -> Tuple[List[ndarray], List[List[ndarray]]]: ...
def eeccsd_matvec(eom: "EOMEE", vector: ndarray, kshift: int, imds: Optional[Incomplete]=None, diag: Optional[ndarray]=None) -> ndarray: ...
def eeccsd_diag(eom: "EOMEE", kshift: int, imds: Optional[Incomplete]=None) -> ndarray: ...
def vector_to_amplitudes_ee(vector: ndarray, kshift: int, nkpts: int, nmo: int64, nocc: int64, kconserv: ndarray) -> List[ndarray]: ...
def amplitudes_to_vector_ee(r1: ndarray, r2: ndarray, kshift: int, kconserv: ndarray) -> ndarray: ...

class EOMEE(eom_rccsd.EOM):
    kpts: Incomplete
    kconserv: Incomplete
    debug_vals: Incomplete
    def __init__(self, cc: Union[GCCSD, RCCSD]) -> None: ...
    kernel = eeccsd
    eeccsd = eeccsd
    matvec = eeccsd_matvec
    get_diag = eeccsd_diag
    @property
    def nkpts(self) -> int: ...
    def vector_size(self, kshift: int = 0) -> int64: ...
    def get_init_guess(self, kshift: int, nroots: int = 1, koopmans: bool = False, diag: Optional[ndarray]=None, **kwargs) -> List[ndarray]: ...
    def gen_matvec(self, kshift: int, imds: Optional[Incomplete]=None, left: bool = False, **kwargs) -> Tuple[Callable, ndarray]: ...
    def vector_to_amplitudes(self, vector: ndarray, kshift: Optional[int]=None, nkpts: None=None, nmo: None=None, nocc: None=None, kconserv: None=None) -> List[ndarray]: ...
    def amplitudes_to_vector(self, r1, r2, kshift, kconserv=None): ...
    def get_kconserv_ee_r1(self, kshift: Union[int64, int] = 0) -> ndarray: ...
    def get_kconserv_ee_r2(self, kshift: int = 0) -> ndarray: ...
    def make_imds(self, eris: Optional[_PhysicistsERIs]=None) -> Incomplete: ...

class _IMDS:
    verbose: Incomplete
    kconserv: Incomplete
    stdout: Incomplete
    eris: Incomplete
    made_ip_imds: bool
    made_ea_imds: bool
    made_ee_imds: bool
    def __init__(self, cc: GCCSD, eris: Optional[_PhysicistsERIs]=None) -> None: ...
    Woooo: Incomplete
    Wooov: Incomplete
    Wovoo: Incomplete
    def make_ip(self) -> Incomplete: ...
    t1: Incomplete
    t2: Incomplete
    def make_t3p2_ip(self, cc: GCCSD) -> Incomplete: ...
    Wvovv: Incomplete
    Wvvvv: Incomplete
    Wvvvo: Incomplete
    def make_ea(self) -> Incomplete: ...
    def make_t3p2_ea(self, cc: GCCSD) -> Incomplete: ...
    def make_ee(self) -> Incomplete: ...
