from pyscf import lib as lib
from pyscf.lib import logger as logger
from pyscf.lib.parameters import LARGE_DENOM as LARGE_DENOM
from pyscf.pbc.lib import kpts_helper as kpts_helper
from pyscf.pbc.mp.kmp2 import get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc, padded_mo_coeff as padded_mo_coeff, padding_k_idx as padding_k_idx

einsum = lib.einsum

def kernel(mycc, eris, t1=None, t2=None, max_memory: int = 2000, verbose=...): ...
def check_read_success(filename, **kwargs): ...
def transpose_t2(t2, nkpts, nocc, nvir, kconserv, out=None): ...
def create_eris_vvop(vovv, oovv, nkpts, nocc, nvir, kconserv, out=None): ...
def create_eris_vooo(ooov, nkpts, nocc, nvir, kconserv, out=None): ...
def create_t3_eris(mycc, kconserv, eris, tmpfile: str = 'tmp_t3_eris.h5'): ...
def zip_kpoints(kpt_indices): ...
def get_data_slices(kpt_indices, orb_indices, kconserv): ...
