from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.cc import uccsd as uccsd
from pyscf.lib import logger as logger
from pyscf.lib.parameters import LARGE_DENOM as LARGE_DENOM, LOOSE_ZERO_TOL as LOOSE_ZERO_TOL
from pyscf.pbc import scf as scf
from pyscf.pbc.cc import kintermediates_uhf as kintermediates_uhf
from pyscf.pbc.lib import kpts_helper as kpts_helper
from pyscf.pbc.lib.kpts_helper import gamma_point as gamma_point
from pyscf.pbc.mp.kump2 import get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc, padded_mo_coeff as padded_mo_coeff, padding_k_idx as padding_k_idx

einsum = lib.einsum

def mo_c_list_to_array(mo_coeff): ...
def convert_mo_coeff(mo_coeff): ...
def update_amps(cc, t1, t2, eris): ...
def get_normt_diff(cc, t1, t2, t1new, t2new): ...
def energy(cc, t1, t2, eris): ...
def amplitudes_to_vector(t1, t2): ...
def vector_to_amplitudes(vec, nmo, nocc, nkpts: int = 1): ...
def add_vvvv_(cc, Ht2, t1, t2, eris): ...

class KUCCSD(uccsd.UCCSD):
    max_space: Incomplete
    kpts: Incomplete
    mo_energy: Incomplete
    khelper: Incomplete
    direct: bool
    def __init__(self, mf, frozen=None, mo_coeff=None, mo_occ=None) -> None: ...
    @property
    def nkpts(self): ...
    get_normt_diff = get_normt_diff
    get_nocc = get_nocc
    get_nmo = get_nmo
    get_frozen_mask = get_frozen_mask
    update_amps = update_amps
    energy = energy
    def dump_flags(self, verbose=None): ...
    def ao2mo(self, mo_coeff=None): ...
    emp2: Incomplete
    def init_amps(self, eris): ...
    def amplitudes_to_vector(self, t1, t2): ...
    def vector_to_amplitudes(self, vec, nmo=None, nocc=None, nkpts=None): ...
    to_gpu = lib.to_gpu
UCCSD = KUCCSD
