from pyscf import lib as lib
from pyscf.lib import logger as logger
from pyscf.lib.parameters import LARGE_DENOM as LARGE_DENOM
from pyscf.pbc.lib import kpts_helper as kpts_helper
from pyscf.pbc.mp.kmp2 import get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc, padded_mo_coeff as padded_mo_coeff, padding_k_idx as padding_k_idx
from h5py._hl.dataset import Dataset
from numpy import float64, int64, ndarray
from pyscf.lib.misc import H5TmpFile
from pyscf.pbc.cc.kccsd_rhf import RCCSD, _ERIS
from typing import List, Optional, Tuple, Union

einsum = lib.einsum

def kernel(mycc: RCCSD, eris: _ERIS, t1: Optional[ndarray]=None, t2: Optional[ndarray]=None, max_memory: int = 2000, verbose: int=...) -> float64: ...
def check_read_success(filename: str, **kwargs) -> bool: ...
def transpose_t2(t2: ndarray, nkpts: int, nocc: int64, nvir: int64, kconserv: ndarray, out: Optional[Dataset]=None) -> Dataset: ...
def create_eris_vvop(vovv: ndarray, oovv: ndarray, nkpts: int, nocc: int64, nvir: int64, kconserv: ndarray, out: Optional[Dataset]=None) -> Dataset: ...
def create_eris_vooo(ooov: ndarray, nkpts: int, nocc: int64, nvir: int64, kconserv: ndarray, out: Optional[Dataset]=None) -> Dataset: ...
def create_t3_eris(mycc: RCCSD, kconserv: ndarray, eris: List[ndarray], tmpfile: str = 'tmp_t3_eris.h5') -> Tuple[H5TmpFile, Dataset, Dataset, Dataset]: ...
def zip_kpoints(kpt_indices: List[Union[int, ndarray]]) -> List[int]: ...
def get_data_slices(kpt_indices: List[Union[int, ndarray]], orb_indices: Tuple[int, int, int, int, int, int], kconserv: ndarray) -> Tuple[List[List[Union[int, slice]]], List[List[Union[int, slice]]], List[List[Union[int, int64, slice]]], List[List[Union[int, int64, slice]]]]: ...
