from pyscf import lib as lib
from pyscf.lib import logger as logger
from pyscf.lib.parameters import LARGE_DENOM as LARGE_DENOM, LOOSE_ZERO_TOL as LOOSE_ZERO_TOL
from pyscf.pbc.lib import kpts_helper as kpts_helper
from pyscf.pbc.mp.kmp2 import get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc, padded_mo_coeff as padded_mo_coeff, padding_k_idx as padding_k_idx

einsum = lib.einsum

def cc_Foo(t1, t2, eris, kconserv): ...
def cc_Fvv(t1, t2, eris, kconserv): ...
def cc_Fov(t1, t2, eris, kconserv): ...
def Loo(t1, t2, eris, kconserv): ...
def Lvv(t1, t2, eris, kconserv): ...
def cc_Woooo(t1, t2, eris, kconserv, out=None): ...
def cc_Wvvvv(t1, t2, eris, kconserv, out=None): ...
def cc_Wvoov(t1, t2, eris, kconserv, out=None): ...
def cc_Wvovo(t1, t2, eris, kconserv, out=None): ...
def Wooov(t1, t2, eris, kconserv, out=None): ...
def Wvovv(t1, t2, eris, kconserv, out=None): ...
def W1ovvo(t1, t2, eris, kconserv, out=None): ...
def W2ovvo(t1, t2, eris, kconserv, out=None): ...
def Wovvo(t1, t2, eris, kconserv, out=None): ...
def W1ovov(t1, t2, eris, kconserv, out=None): ...
def W2ovov(t1, t2, eris, kconserv, out=None): ...
def Wovov(t1, t2, eris, kconserv, out=None): ...
def Woooo(t1, t2, eris, kconserv, out=None): ...
def Wvvvv(t1, t2, eris, kconserv, out=None): ...
def get_Wvvvv(t1, t2, eris, kconserv, ka, kb, kc): ...
def Wvvvo(t1, t2, eris, kconserv, _Wvvvv=None, out=None): ...
def Wovoo(t1, t2, eris, kconserv, out=None): ...
def get_t3p2_imds_slow(cc, t1, t2, eris=None, t3p2_ip_out=None, t3p2_ea_out=None): ...
def get_t3p2_imds(mycc, t1, t2, eris=None, t3p2_ip_out=None, t3p2_ea_out=None): ...
