from pyscf import lib as lib
from pyscf.pbc.lib import kpts_helper as kpts_helper
from numpy import int64, ndarray
from pyscf.cc.uccsd import _ChemistsERIs
from pyscf.pbc.cc.kccsd_uhf import KUCCSD
from typing import Tuple, Union

einsum = lib.einsum

def make_tau(cc: KUCCSD, t2: Tuple[ndarray, ndarray, ndarray], t1: Tuple[ndarray, ndarray], t1p: Tuple[ndarray, ndarray], fac: float = 1.0) -> Tuple[ndarray, ndarray, ndarray]: ...
def make_tau2(cc: KUCCSD, t2: Tuple[ndarray, ndarray, ndarray], t1: Tuple[ndarray, ndarray], t1p: Tuple[ndarray, ndarray], fac: float = 1.0) -> Tuple[ndarray, ndarray, ndarray]: ...
def cc_Fvv(cc: KUCCSD, t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: _ChemistsERIs) -> Tuple[ndarray, ndarray]: ...
def cc_Foo(cc: KUCCSD, t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: _ChemistsERIs) -> Tuple[ndarray, ndarray]: ...
def cc_Fov(cc: KUCCSD, t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: _ChemistsERIs) -> Tuple[ndarray, ndarray]: ...
def cc_Woooo(cc: KUCCSD, t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: _ChemistsERIs) -> Tuple[ndarray, ndarray, ndarray]: ...
def cc_Wvvvv(cc: KUCCSD, t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: _ChemistsERIs) -> Tuple[ndarray, ndarray, ndarray]: ...
def cc_Wvvvv_half(cc: KUCCSD, t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: _ChemistsERIs) -> Tuple[ndarray, ndarray, ndarray]: ...
def Wvvvv(cc: KUCCSD, t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: _ChemistsERIs) -> Tuple[ndarray, ndarray, ndarray]: ...
def get_Wvvvv(cc: KUCCSD, t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: _ChemistsERIs, ka: int, kb: Union[int64, int], kc: int) -> Tuple[ndarray, ndarray, ndarray]: ...
def cc_Wovvo(cc: KUCCSD, t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: _ChemistsERIs) -> Tuple[ndarray, ndarray, ndarray, ndarray, ndarray, ndarray]: ...
def kconserv_mat(nkpts: int, kconserv: ndarray) -> ndarray: ...
def Foo(cc: KUCCSD, t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: _ChemistsERIs) -> Tuple[ndarray, ndarray]: ...
def Fvv(cc: KUCCSD, t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: _ChemistsERIs) -> Tuple[ndarray, ndarray]: ...
def Fov(cc: KUCCSD, t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: _ChemistsERIs) -> Tuple[ndarray, ndarray]: ...
def Wvvov(cc: KUCCSD, t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: _ChemistsERIs) -> Tuple[ndarray, ndarray, ndarray, ndarray]: ...
def Wvvvo(cc: KUCCSD, t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: _ChemistsERIs) -> Tuple[ndarray, ndarray, ndarray, ndarray]: ...
def Woooo(cc: KUCCSD, t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: _ChemistsERIs) -> Tuple[ndarray, ndarray, None, ndarray]: ...
def Woovo(cc: KUCCSD, t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: _ChemistsERIs) -> Tuple[ndarray, ndarray, ndarray, ndarray]: ...
def Wooov(cc: KUCCSD, t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: _ChemistsERIs, kconserv: ndarray) -> Tuple[ndarray, ndarray, ndarray, ndarray]: ...
def Wovvo(cc: KUCCSD, t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: _ChemistsERIs) -> Tuple[ndarray, ndarray, ndarray, ndarray]: ...
def W1oovv(cc: KUCCSD, t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: _ChemistsERIs) -> Tuple[ndarray, ndarray, ndarray, ndarray]: ...
def W2oovv(cc: KUCCSD, t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: _ChemistsERIs) -> Tuple[ndarray, ndarray, ndarray, ndarray]: ...
def Woovv(cc: KUCCSD, t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: _ChemistsERIs) -> Tuple[ndarray, ndarray, ndarray, ndarray]: ...
