from pyscf import lib as lib
from pyscf.pbc.lib import ktensor as ktensor
from numpy import ndarray
from pyscf.pbc.cc.kccsd_rhf_ksymm import _PhysicistsERIs
from pyscf.pbc.lib.kpts import KPoints, KQuartets, MORotationMatrix
from pyscf.pbc.lib.ktensor import KsymmArray

einsum = lib.einsum

def cc_Foo(kpts: KPoints, kqrts: KQuartets, t1: KsymmArray, t2: KsymmArray, eris: _PhysicistsERIs, rmat: MORotationMatrix) -> KsymmArray: ...
def cc_Fov(kpts: KPoints, kqrts: KQuartets, t1: KsymmArray, t2: KsymmArray, eris: _PhysicistsERIs, rmat: MORotationMatrix) -> KsymmArray: ...
def cc_Fvv(kpts: KPoints, kqrts: KQuartets, t1: KsymmArray, t2: KsymmArray, eris: _PhysicistsERIs, rmat: MORotationMatrix) -> KsymmArray: ...
def Loo(kpts: KPoints, kqrts: KQuartets, t1: KsymmArray, t2: KsymmArray, eris: _PhysicistsERIs, rmat: MORotationMatrix) -> KsymmArray: ...
def Lvv(kpts: KPoints, kqrts: KQuartets, t1: KsymmArray, t2: KsymmArray, eris: _PhysicistsERIs, rmat: MORotationMatrix) -> KsymmArray: ...
def cc_Woooo(kpts: KPoints, kqrts: KQuartets, t1: ndarray, t2: ndarray, eris: _PhysicistsERIs, rmat: MORotationMatrix, out: None=None) -> KsymmArray: ...
def cc_Wvvvv(kpts: KPoints, kqrts: KQuartets, t1: ndarray, t2: ndarray, eris: _PhysicistsERIs, rmat: MORotationMatrix, out: None=None) -> KsymmArray: ...
def cc_Wvoov(kpts: KPoints, kqrts: KQuartets, t1: ndarray, t2: ndarray, eris: _PhysicistsERIs, rmat: MORotationMatrix, out: None=None) -> KsymmArray: ...
def cc_Wvovo(kpts: KPoints, kqrts: KQuartets, t1: ndarray, t2: ndarray, eris: _PhysicistsERIs, rmat: MORotationMatrix, out: None=None) -> KsymmArray: ...
