from pyscf import lib as lib
from pyscf.pbc.lib import ktensor as ktensor

einsum = lib.einsum

def cc_Foo(kpts, kqrts, t1, t2, eris, rmat): ...
def cc_Fov(kpts, kqrts, t1, t2, eris, rmat): ...
def cc_Fvv(kpts, kqrts, t1, t2, eris, rmat): ...
def Loo(kpts, kqrts, t1, t2, eris, rmat): ...
def Lvv(kpts, kqrts, t1, t2, eris, rmat): ...
def cc_Woooo(kpts, kqrts, t1, t2, eris, rmat, out=None): ...
def cc_Wvvvv(kpts, kqrts, t1, t2, eris, rmat, out=None): ...
def cc_Wvoov(kpts, kqrts, t1, t2, eris, rmat, out=None): ...
def cc_Wvovo(kpts, kqrts, t1, t2, eris, rmat, out=None): ...
