from pyscf import lib as lib
from pyscf.lib import logger as logger
from pyscf.lib.parameters import LARGE_DENOM as LARGE_DENOM
from pyscf.pbc.lib import kpts_helper as kpts_helper
from pyscf.pbc.mp.kmp2 import get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc, padded_mo_coeff as padded_mo_coeff, padding_k_idx as padding_k_idx
from numpy import float64, ndarray
from pyscf.cc.gccsd import _PhysicistsERIs
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.cc.kccsd import GCCSD
from typing import Optional, Tuple, Union

einsum = lib.einsum

def make_tau(cc: GCCSD, t2: Union[ndarray, NPArrayWithTag], t1: Union[ndarray, NPArrayWithTag], t1p: Union[ndarray, NPArrayWithTag], kconserv: ndarray, fac: float = 1.0, out: None=None) -> ndarray: ...
def cc_Fvv(cc: GCCSD, t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs, kconserv: ndarray) -> ndarray: ...
def cc_Foo(cc: GCCSD, t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs, kconserv: ndarray) -> ndarray: ...
def cc_Fov(cc: GCCSD, t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs, kconserv: ndarray) -> ndarray: ...
def cc_Woooo(cc: GCCSD, t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs, kconserv: ndarray) -> ndarray: ...
def cc_Wvvvv(cc: GCCSD, t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs, kconserv: ndarray) -> ndarray: ...
def cc_Wovvo(cc: GCCSD, t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs, kconserv: ndarray) -> ndarray: ...
def cc_Wovvo_jk(cc, t1, t2, eris, kconserv): ...
def Fvv(cc: GCCSD, t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs, kconserv: ndarray) -> ndarray: ...
def Foo(cc: GCCSD, t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs, kconserv: ndarray) -> ndarray: ...
def Fov(cc: GCCSD, t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs, kconserv: ndarray) -> ndarray: ...
def Woooo(cc: GCCSD, t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs, kconserv: ndarray) -> ndarray: ...
def Wvvvv(cc: GCCSD, t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs, kconserv: ndarray) -> ndarray: ...
def Wovvo(cc: GCCSD, t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs, kconserv: ndarray) -> ndarray: ...
def Wooov(cc: GCCSD, t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs, kconserv: ndarray) -> ndarray: ...
def Wvovv(cc: GCCSD, t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs, kconserv: ndarray) -> ndarray: ...
def Wovoo(cc: GCCSD, t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs, kconserv: ndarray) -> ndarray: ...
def Wvvvo(cc: GCCSD, t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs, kconserv: ndarray, WWvvvv: Optional[ndarray]=None) -> ndarray: ...
def get_full_t3p2(mycc: GCCSD, t1: NPArrayWithTag, t2: NPArrayWithTag, eris: _PhysicistsERIs) -> ndarray: ...
def get_t3p2_imds_slow(cc: GCCSD, t1: NPArrayWithTag, t2: NPArrayWithTag, eris: Optional[_PhysicistsERIs]=None, t3p2_ip_out: None=None, t3p2_ea_out: None=None) -> Tuple[float64, ndarray, ndarray, ndarray, ndarray]: ...
