from pyscf import lib as lib
from pyscf.pbc.lib import kpts_helper as kpts_helper

einsum = lib.einsum

def make_tau(cc, t2, t1, t1p, fac: float = 1.0): ...
def make_tau2(cc, t2, t1, t1p, fac: float = 1.0): ...
def cc_Fvv(cc, t1, t2, eris): ...
def cc_Foo(cc, t1, t2, eris): ...
def cc_Fov(cc, t1, t2, eris): ...
def cc_Woooo(cc, t1, t2, eris): ...
def cc_Wvvvv(cc, t1, t2, eris): ...
def cc_Wvvvv_half(cc, t1, t2, eris): ...
def Wvvvv(cc, t1, t2, eris): ...
def get_Wvvvv(cc, t1, t2, eris, ka, kb, kc): ...
def cc_Wovvo(cc, t1, t2, eris): ...
def kconserv_mat(nkpts, kconserv): ...
def Foo(cc, t1, t2, eris): ...
def Fvv(cc, t1, t2, eris): ...
def Fov(cc, t1, t2, eris): ...
def Wvvov(cc, t1, t2, eris): ...
def Wvvvo(cc, t1, t2, eris): ...
def Woooo(cc, t1, t2, eris): ...
def Woovo(cc, t1, t2, eris): ...
def Wooov(cc, t1, t2, eris, kconserv): ...
def Wovvo(cc, t1, t2, eris): ...
def W1oovv(cc, t1, t2, eris): ...
def W2oovv(cc, t1, t2, eris): ...
def Woovv(cc, t1, t2, eris): ...
