from pyscf import lib as lib
from pyscf.lib import logger as logger
from pyscf.lib.parameters import LARGE_DENOM as LARGE_DENOM, LOOSE_ZERO_TOL as LOOSE_ZERO_TOL
from pyscf.pbc.lib import kpts_helper as kpts_helper
from pyscf.pbc.mp.kmp2 import get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc, padded_mo_coeff as padded_mo_coeff, padding_k_idx as padding_k_idx
from h5py._hl.dataset import Dataset
from numpy import float64, int64, ndarray
from numpy.dtypes import Complex128DType, Float64DType
from pyscf.pbc.cc.kccsd_rhf import RCCSD, _ERIS
from typing import List, Optional, Tuple, Union

einsum = lib.einsum

def cc_Foo(t1: ndarray, t2: ndarray, eris: _ERIS, kconserv: ndarray) -> ndarray: ...
def cc_Fvv(t1: ndarray, t2: ndarray, eris: _ERIS, kconserv: ndarray) -> ndarray: ...
def cc_Fov(t1: ndarray, t2: ndarray, eris: _ERIS, kconserv: ndarray) -> ndarray: ...
def Loo(t1: ndarray, t2: ndarray, eris: _ERIS, kconserv: ndarray) -> ndarray: ...
def Lvv(t1: ndarray, t2: ndarray, eris: _ERIS, kconserv: ndarray) -> ndarray: ...
def cc_Woooo(t1: ndarray, t2: ndarray, eris: _ERIS, kconserv: ndarray, out: None=None) -> ndarray: ...
def cc_Wvvvv(t1: ndarray, t2: ndarray, eris: _ERIS, kconserv: ndarray, out: None=None) -> ndarray: ...
def cc_Wvoov(t1: ndarray, t2: ndarray, eris: _ERIS, kconserv: ndarray, out: None=None) -> ndarray: ...
def cc_Wvovo(t1: ndarray, t2: ndarray, eris: _ERIS, kconserv: ndarray, out: None=None) -> ndarray: ...
def Wooov(t1: ndarray, t2: ndarray, eris: _ERIS, kconserv: ndarray, out: None=None) -> ndarray: ...
def Wvovv(t1: ndarray, t2: ndarray, eris: _ERIS, kconserv: ndarray, out: Optional[Dataset]=None) -> Union[ndarray, Dataset]: ...
def W1ovvo(t1: ndarray, t2: ndarray, eris: _ERIS, kconserv: ndarray, out: Optional[Dataset]=None) -> Union[ndarray, Dataset]: ...
def W2ovvo(t1: ndarray, t2: ndarray, eris: _ERIS, kconserv: ndarray, out: None=None) -> ndarray: ...
def Wovvo(t1: ndarray, t2: ndarray, eris: _ERIS, kconserv: ndarray, out: Optional[Dataset]=None) -> Union[ndarray, Dataset]: ...
def W1ovov(t1: ndarray, t2: ndarray, eris: _ERIS, kconserv: ndarray, out: Optional[Dataset]=None) -> Union[ndarray, Dataset]: ...
def W2ovov(t1: ndarray, t2: ndarray, eris: _ERIS, kconserv: ndarray, out: None=None) -> ndarray: ...
def Wovov(t1: ndarray, t2: ndarray, eris: _ERIS, kconserv: ndarray, out: Optional[Dataset]=None) -> Union[ndarray, Dataset]: ...
def Woooo(t1: ndarray, t2: ndarray, eris: _ERIS, kconserv: ndarray, out: None=None) -> ndarray: ...
def Wvvvv(t1: ndarray, t2: ndarray, eris: _ERIS, kconserv: ndarray, out: None=None) -> ndarray: ...
def get_Wvvvv(t1: ndarray, t2: ndarray, eris: _ERIS, kconserv: ndarray, ka: Union[int64, int], kb: Union[int64, int], kc: Union[int64, int]) -> ndarray: ...
def Wvvvo(t1: ndarray, t2: ndarray, eris: _ERIS, kconserv: ndarray, _Wvvvv: Optional[ndarray]=None, out: Optional[Dataset]=None) -> Union[ndarray, Dataset]: ...
def Wovoo(t1: ndarray, t2: ndarray, eris: _ERIS, kconserv: ndarray, out: None=None) -> ndarray: ...
def get_t3p2_imds_slow(cc, t1, t2, eris=None, t3p2_ip_out=None, t3p2_ea_out=None): ...
def get_t3p2_imds(mycc: RCCSD, t1: ndarray, t2: ndarray, eris: Optional[_ERIS]=None, t3p2_ip_out: None=None, t3p2_ea_out: None=None) -> Tuple[float64, ndarray, ndarray, ndarray, ndarray]: ...
