from pyscf import lib as lib
from pyscf.lib import logger as logger
from pyscf.lib.parameters import LARGE_DENOM as LARGE_DENOM
from pyscf.pbc.lib import kpts_helper as kpts_helper
from pyscf.pbc.mp.kmp2 import get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc, padded_mo_coeff as padded_mo_coeff, padding_k_idx as padding_k_idx

einsum = lib.einsum

def make_tau(cc, t2, t1, t1p, kconserv, fac: float = 1.0, out=None): ...
def cc_Fvv(cc, t1, t2, eris, kconserv): ...
def cc_Foo(cc, t1, t2, eris, kconserv): ...
def cc_Fov(cc, t1, t2, eris, kconserv): ...
def cc_Woooo(cc, t1, t2, eris, kconserv): ...
def cc_Wvvvv(cc, t1, t2, eris, kconserv): ...
def cc_Wovvo(cc, t1, t2, eris, kconserv): ...
def cc_Wovvo_jk(cc, t1, t2, eris, kconserv): ...
def Fvv(cc, t1, t2, eris, kconserv): ...
def Foo(cc, t1, t2, eris, kconserv): ...
def Fov(cc, t1, t2, eris, kconserv): ...
def Woooo(cc, t1, t2, eris, kconserv): ...
def Wvvvv(cc, t1, t2, eris, kconserv): ...
def Wovvo(cc, t1, t2, eris, kconserv): ...
def Wooov(cc, t1, t2, eris, kconserv): ...
def Wvovv(cc, t1, t2, eris, kconserv): ...
def Wovoo(cc, t1, t2, eris, kconserv): ...
def Wvvvo(cc, t1, t2, eris, kconserv, WWvvvv=None): ...
def get_full_t3p2(mycc, t1, t2, eris): ...
def get_t3p2_imds_slow(cc, t1, t2, eris=None, t3p2_ip_out=None, t3p2_ea_out=None): ...
