import ctypes
from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from numpy import float64, int64, ndarray
from pyscf.pbc.gto.cell import Cell
from typing import List, Tuple, Union

libdft: Incomplete

def gradient_gs(f_gs: ndarray, Gv: ndarray) -> ndarray: ...
def get_gga_vrho_gs(v: ndarray, v1: ndarray, Gv: ndarray, weight: float64, ngrid: int64, fac: float = 2.0) -> ndarray: ...
def pp_loc_part1_gs(coulG, Gv, G2, G0idx, Z, coords, rloc): ...
def build_core_density(atm: ndarray, bas: ndarray, env: ndarray, mesh: ndarray, dimension: int, a: ndarray, b: ndarray, max_radius: float64) -> ndarray: ...
def int_gauss_charge_v_rs(v_rs: ndarray, comp: int, atm: ndarray, bas: ndarray, env: ndarray, mesh: ndarray, dimension: int, a: ndarray, b: ndarray, max_radius: Union[int, float64]) -> ndarray: ...
def grid_collocate(xctype: str, dm: ndarray, task_list: "TaskList", hermi: int, shls_slice: Tuple[int, int, int, int], ao_loc0: ndarray, ao_loc1: ndarray, dimension: int, a: ndarray, b: ndarray, ish_atm: ndarray, ish_bas: ndarray, ish_env: ndarray, jsh_atm: ndarray, jsh_bas: ndarray, jsh_env: ndarray, cart: bool) -> "RS_Grid": ...
def grid_integrate(xctype: str, wv: ndarray, task_list: "TaskList", comp: int, hermi: int, grid_level: int, shls_slice: Tuple[int, int, int, int], ao_loc0: ndarray, ao_loc1: ndarray, dimension: int, a: ndarray, b: ndarray, ish_atm: ndarray, ish_bas: ndarray, ish_env: ndarray, jsh_atm: ndarray, jsh_bas: ndarray, jsh_env: ndarray, cart: bool) -> ndarray: ...

class _CGridLevel_Info(ctypes.Structure): ...

class GridLevel_Info:
    cutoff: Incomplete
    mesh: Incomplete
    rel_cutoff: Incomplete
    nlevels: Incomplete
    def __init__(self, cutoff: List[Union[float64, int, float]], rel_cutoff: float, mesh: List[ndarray]) -> None: ...
    def __del__(self) -> None: ...

class _CRS_Grid(ctypes.Structure): ...

class RS_Grid:
    gridlevel_info: Incomplete
    nlevels: Incomplete
    def __init__(self, gridlevel_info: GridLevel_Info, comp: int) -> None: ...
    def __del__(self) -> None: ...
    def __getitem__(self, i: int) -> ndarray: ...

class _CPGFPair(ctypes.Structure): ...
class _CTask(ctypes.Structure): ...
class _CTaskList(ctypes.Structure): ...

class TaskList:
    grid_level_method: Incomplete
    gridlevel_info: Incomplete
    nlevels: Incomplete
    hermi: Incomplete
    Ls: Incomplete
    def __init__(self, cell: Cell, gridlevel_info: GridLevel_Info, cell1: None=None, Ls: None=None, hermi: int = 0, precision: None=None) -> None: ...
    @property
    def ntasks(self) -> List[int]: ...
    def __del__(self) -> None: ...
