import ctypes
from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger

libdft: Incomplete

def gradient_gs(f_gs, Gv): ...
def get_gga_vrho_gs(v, v1, Gv, weight, ngrid, fac: float = 2.0): ...
def pp_loc_part1_gs(coulG, Gv, G2, G0idx, Z, coords, rloc): ...
def build_core_density(atm, bas, env, mesh, dimension, a, b, max_radius): ...
def int_gauss_charge_v_rs(v_rs, comp, atm, bas, env, mesh, dimension, a, b, max_radius): ...
def grid_collocate(xctype, dm, task_list, hermi, shls_slice, ao_loc0, ao_loc1, dimension, a, b, ish_atm, ish_bas, ish_env, jsh_atm, jsh_bas, jsh_env, cart): ...
def grid_integrate(xctype, wv, task_list, comp, hermi, grid_level, shls_slice, ao_loc0, ao_loc1, dimension, a, b, ish_atm, ish_bas, ish_env, jsh_atm, jsh_bas, jsh_env, cart): ...

class _CGridLevel_Info(ctypes.Structure): ...

class GridLevel_Info:
    cutoff: Incomplete
    mesh: Incomplete
    rel_cutoff: Incomplete
    nlevels: Incomplete
    def __init__(self, cutoff, rel_cutoff, mesh) -> None: ...
    def __del__(self) -> None: ...

class _CRS_Grid(ctypes.Structure): ...

class RS_Grid:
    gridlevel_info: Incomplete
    nlevels: Incomplete
    def __init__(self, gridlevel_info, comp) -> None: ...
    def __del__(self) -> None: ...
    def __getitem__(self, i): ...

class _CPGFPair(ctypes.Structure): ...
class _CTask(ctypes.Structure): ...
class _CTaskList(ctypes.Structure): ...

class TaskList:
    grid_level_method: Incomplete
    gridlevel_info: Incomplete
    nlevels: Incomplete
    hermi: Incomplete
    Ls: Incomplete
    def __init__(self, cell, gridlevel_info, cell1=None, Ls=None, hermi: int = 0, precision=None) -> None: ...
    @property
    def ntasks(self): ...
    def __del__(self) -> None: ...
