from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.dft.numint import BLKSIZE as BLKSIZE, LibXCMixin as LibXCMixin, MGGA_DENSITY_LAPL as MGGA_DENSITY_LAPL, libdft as libdft
from pyscf.gto import ANG_OF as ANG_OF, ATOM_OF as ATOM_OF, NPRIM_OF as NPRIM_OF, PTR_COEFF as PTR_COEFF, PTR_EXP as PTR_EXP
from pyscf.lib import logger as logger
from pyscf.pbc import gto as gto, tools as tools
from pyscf.pbc.df import aft as aft, fft as fft, ft_ao as ft_ao
from pyscf.pbc.dft import gen_grid as gen_grid, numint as numint
from pyscf.pbc.gto import pseudo as pseudo
from pyscf.pbc.gto.pseudo import pp_int as pp_int
from pyscf.pbc.lib.kpts import KPoints as KPoints
from pyscf.pbc.lib.kpts_helper import gamma_point as gamma_point

EXTRA_PREC: Incomplete
TO_EVEN_GRIDS: Incomplete
RMAX_FACTOR_ORTH: Incomplete
RMAX_FACTOR_NONORTH: Incomplete
RMAX_RATIO: Incomplete
R_RATIO_SUBLOOP: Incomplete
INIT_MESH_ORTH: Incomplete
INIT_MESH_NONORTH: Incomplete
KE_RATIO: Incomplete
TASKS_TYPE: Incomplete
RHOG_HIGH_ORDER: Incomplete
PTR_EXPDROP: int
EXPDROP: Incomplete
IMAG_TOL: float

def eval_mat(cell, weights, shls_slice=None, comp: int = 1, hermi: int = 0, xctype: str = 'LDA', kpts=None, mesh=None, offset=None, submesh=None): ...
def eval_rho(cell, dm, shls_slice=None, hermi: int = 0, xctype: str = 'LDA', kpts=None, mesh=None, offset=None, submesh=None, ignore_imag: bool = False, out=None): ...
def get_nuc(mydf, kpts=None): ...
def get_pp(mydf, kpts=None, max_memory: int = 4000): ...
def get_j_kpts(mydf, dm_kpts, hermi: int = 1, kpts=..., kpts_band=None): ...
def nr_rks(mydf, xc_code, dm_kpts, hermi: int = 1, kpts=None, kpts_band=None, with_j: bool = False, return_j: bool = False, verbose=None): ...
def nr_uks(mydf, xc_code, dm_kpts, hermi: int = 1, kpts=None, kpts_band=None, with_j: bool = False, return_j: bool = False, verbose=None): ...
def nr_rks_fxc(mydf, xc_code, dm0, dms, hermi: int = 0, with_j: bool = False, rho0=None, vxc=None, fxc=None, kpts=None, verbose=None): ...
def nr_rks_fxc_st(mydf, xc_code, dm0, dms_alpha, hermi: int = 1, singlet: bool = True, rho0=None, vxc=None, fxc=None, kpts=None, with_j: bool = False, verbose=None): ...
def nr_uks_fxc(mydf, xc_code, dm0, dms, hermi: int = 0, with_j: bool = False, rho0=None, vxc=None, fxc=None, kpts=None, verbose=None): ...
def cache_xc_kernel(mydf, xc_code, mo_coeff, mo_occ, spin: int = 0, kpts=None): ...
def cache_xc_kernel1(mydf, xc_code, dm, spin: int = 0, kpts=None): ...
def get_rho(mydf, dm, kpts=None): ...
def multi_grids_tasks(cell, fft_mesh=None, verbose=None): ...
def multi_grids_tasks_for_rcut(cell, fft_mesh=None, verbose=None): ...
def multi_grids_tasks_for_ke_cut(cell, fft_mesh=None, verbose=None): ...

class MultiGridNumInt(lib.StreamObject, LibXCMixin):
    cell: Incomplete
    mesh: Incomplete
    stdout: Incomplete
    verbose: Incomplete
    max_memory: Incomplete
    xc_with_j: bool
    tasks: Incomplete
    def __init__(self, cell) -> None: ...
    def build(self): ...
    def reset(self, cell=None): ...
    get_pp = get_pp
    get_nuc = get_nuc
    def get_jk(self, dm, hermi: int = 1, kpts=None, kpts_band=None, with_j: bool = True, with_k: bool = True, omega=None, exxdiv: str = 'ewald'): ...
    def get_j(self, dm, hermi: int = 1, kpts=None, kpts_band=None, omega=None): ...
    def nr_vxc(self, cell, grids, xc_code, dms, spin: int = 0, relativity: int = 0, hermi: int = 1, kpts=None, kpts_band=None, max_memory: int = 2000, with_j: bool = False, return_j: bool = False, verbose=None): ...
    get_vxc = nr_vxc
    def nr_rks(self, cell, grids, xc_code, dm_kpts, relativity: int = 0, hermi: int = 1, kpts=None, kpts_band=None, max_memory: int = 2000, verbose=None): ...
    def nr_uks(self, cell, grids, xc_code, dm_kpts, relativity: int = 0, hermi: int = 1, kpts=None, kpts_band=None, max_memory: int = 2000, verbose=None): ...
    def nr_rks_fxc(self, cell, grids, xc_code, dm0, dms, relativity: int = 0, hermi: int = 0, rho0=None, vxc=None, fxc=None, kpts=None, max_memory: int = 2000, verbose=None): ...
    def nr_uks_fxc(self, cell, grids, xc_code, dm0, dms, relativity: int = 0, hermi: int = 0, rho0=None, vxc=None, fxc=None, kpts=None, max_memory: int = 2000, verbose=None): ...
    def nr_rks_fxc_st(self, cell, grids, xc_code, dm0, dms_alpha, hermi: int = 1, singlet: bool = True, rho0=None, vxc=None, fxc=None, kpts=None, max_memory: int = 2000, verbose=None): ...
    def cache_xc_kernel(self, cell, grids, xc_code, mo_coeff, mo_occ, spin: int = 0, kpts=None, max_memory: int = 2000): ...
    def cache_xc_kernel1(self, cell, grids, xc_code, dm, spin: int = 0, kpts=None, max_memory: int = 2000): ...
    def nr_nlc_vxc(self, cell, grids, xc_code, dms, relativity: int = 0, hermi: int = 1, kpts=None, kpts_band=None, max_memory: int = 2000, verbose=None) -> None: ...
    def get_rho(self, cell, dm, grids, kpts=..., max_memory: int = 2000): ...
    range_coulomb: Incomplete
    to_gpu = lib.to_gpu
NumInt = MultiGridNumInt

def multigrid_fftdf(mf): ...
multigrid = multigrid_fftdf
