from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.dft.numint import BLKSIZE as BLKSIZE, LibXCMixin as LibXCMixin, MGGA_DENSITY_LAPL as MGGA_DENSITY_LAPL, libdft as libdft
from pyscf.gto import ANG_OF as ANG_OF, ATOM_OF as ATOM_OF, NPRIM_OF as NPRIM_OF, PTR_COEFF as PTR_COEFF, PTR_EXP as PTR_EXP
from pyscf.lib import logger as logger
from pyscf.pbc import gto as gto, tools as tools
from pyscf.pbc.df import aft as aft, fft as fft, ft_ao as ft_ao
from pyscf.pbc.dft import gen_grid as gen_grid, numint as numint
from pyscf.pbc.gto import pseudo as pseudo
from pyscf.pbc.gto.pseudo import pp_int as pp_int
from pyscf.pbc.lib.kpts import KPoints, KPoints as KPoints
from pyscf.pbc.lib.kpts_helper import gamma_point as gamma_point
from numpy import float64, int64, ndarray
from pyscf.lib.logger import Logger
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.dft.gen_grid import UniformGrids
from pyscf.pbc.gto.cell import Cell
from typing import List, Optional, Tuple, Union

EXTRA_PREC: Incomplete
TO_EVEN_GRIDS: Incomplete
RMAX_FACTOR_ORTH: Incomplete
RMAX_FACTOR_NONORTH: Incomplete
RMAX_RATIO: Incomplete
R_RATIO_SUBLOOP: Incomplete
INIT_MESH_ORTH: Incomplete
INIT_MESH_NONORTH: Incomplete
KE_RATIO: Incomplete
TASKS_TYPE: Incomplete
RHOG_HIGH_ORDER: Incomplete
PTR_EXPDROP: int
EXPDROP: Incomplete
IMAG_TOL: float

def eval_mat(cell: Cell, weights: ndarray, shls_slice: Optional[Union[Tuple[int, int64, int, int64], Tuple[int64, int64, int, int64]]]=None, comp: int = 1, hermi: int = 0, xctype: str = 'LDA', kpts: Optional[ndarray]=None, mesh: None=None, offset: None=None, submesh: None=None) -> List[ndarray]: ...
def eval_rho(cell: Cell, dm: ndarray, shls_slice: Optional[Union[Tuple[int, int64, int64, int64], Tuple[int64, int64, int, int64], Tuple[int, int64, int, int64], Tuple[int, int, int, int64]]]=None, hermi: int = 0, xctype: str = 'LDA', kpts: Optional[ndarray]=None, mesh: Optional[ndarray]=None, offset: Optional[ndarray]=None, submesh: Optional[ndarray]=None, ignore_imag: bool = False, out: Optional[ndarray]=None) -> Union[ndarray, List[ndarray]]: ...
def get_nuc(mydf: "MultiGridNumInt", kpts: Optional[ndarray]=None) -> ndarray: ...
def get_pp(mydf: "MultiGridNumInt", kpts: Optional[ndarray]=None, max_memory: int = 4000) -> ndarray: ...
def get_j_kpts(mydf: "MultiGridNumInt", dm_kpts: ndarray, hermi: int = 1, kpts: ndarray=..., kpts_band: None=None) -> ndarray: ...
def nr_rks(mydf: "MultiGridNumInt", xc_code: str, dm_kpts: Union[NPArrayWithTag, ndarray], hermi: int = 1, kpts: Optional[Union[ndarray, KPoints]]=None, kpts_band: Optional[ndarray]=None, with_j: bool = False, return_j: bool = False, verbose: None=None) -> Tuple[float64, float64, NPArrayWithTag]: ...
def nr_uks(mydf: "MultiGridNumInt", xc_code: str, dm_kpts: Union[NPArrayWithTag, ndarray, Tuple[ndarray, ndarray]], hermi: int = 1, kpts: Optional[Union[ndarray, KPoints]]=None, kpts_band: Optional[ndarray]=None, with_j: bool = False, return_j: bool = False, verbose: None=None) -> Tuple[ndarray, float64, NPArrayWithTag]: ...
def nr_rks_fxc(mydf: "MultiGridNumInt", xc_code: str, dm0: Optional[ndarray], dms: ndarray, hermi: int = 0, with_j: bool = False, rho0: Optional[ndarray]=None, vxc: Optional[ndarray]=None, fxc: Optional[ndarray]=None, kpts: Optional[Union[ndarray, KPoints]]=None, verbose: None=None) -> ndarray: ...
def nr_rks_fxc_st(mydf: "MultiGridNumInt", xc_code: str, dm0: Optional[ndarray], dms_alpha: ndarray, hermi: int = 1, singlet: bool = True, rho0: Optional[ndarray]=None, vxc: Optional[ndarray]=None, fxc: Optional[ndarray]=None, kpts: Optional[ndarray]=None, with_j: bool = False, verbose: None=None) -> ndarray: ...
def nr_uks_fxc(mydf: "MultiGridNumInt", xc_code: str, dm0: Optional[Tuple[ndarray, ndarray]], dms: Union[ndarray, Tuple[ndarray, ndarray]], hermi: int = 0, with_j: bool = False, rho0: Optional[ndarray]=None, vxc: Optional[ndarray]=None, fxc: Optional[ndarray]=None, kpts: Optional[Union[ndarray, KPoints]]=None, verbose: None=None) -> ndarray: ...
def cache_xc_kernel(mydf: "MultiGridNumInt", xc_code: str, mo_coeff: Union[ndarray, Tuple[ndarray, ndarray]], mo_occ: ndarray, spin: int = 0, kpts: Optional[Union[ndarray, KPoints]]=None) -> Tuple[ndarray, ndarray, ndarray]: ...
def cache_xc_kernel1(mydf: "MultiGridNumInt", xc_code: str, dm: Union[ndarray, List[List[ndarray]], List[ndarray], Tuple[ndarray, ndarray]], spin: int = 0, kpts: Optional[Union[ndarray, KPoints]]=None) -> Tuple[ndarray, ndarray, ndarray]: ...
def get_rho(mydf: "MultiGridNumInt", dm: Union[ndarray, NPArrayWithTag], kpts: Optional[Union[ndarray, KPoints]]=None) -> ndarray: ...
def multi_grids_tasks(cell: Cell, fft_mesh: Optional[Union[ndarray, List[int]]]=None, verbose: Optional[Logger]=None) -> List[List[Optional[UniformGrids]]]: ...
def multi_grids_tasks_for_rcut(cell: Cell, fft_mesh: Optional[List[int]]=None, verbose: Optional[Logger]=None) -> List[List[Optional[UniformGrids]]]: ...
def multi_grids_tasks_for_ke_cut(cell: Cell, fft_mesh: Optional[Union[ndarray, List[int]]]=None, verbose: Optional[Logger]=None) -> List[List[Optional[UniformGrids]]]: ...

class MultiGridNumInt(lib.StreamObject, LibXCMixin):
    cell: Incomplete
    mesh: Incomplete
    stdout: Incomplete
    verbose: Incomplete
    max_memory: Incomplete
    xc_with_j: bool
    tasks: Incomplete
    def __init__(self, cell: Cell) -> None: ...
    def build(self): ...
    def reset(self, cell=None): ...
    get_pp = get_pp
    get_nuc = get_nuc
    def get_jk(self, dm, hermi: int = 1, kpts=None, kpts_band=None, with_j: bool = True, with_k: bool = True, omega=None, exxdiv: str = 'ewald'): ...
    def get_j(self, dm: ndarray, hermi: int = 1, kpts: Optional[ndarray]=None, kpts_band: None=None, omega: None=None) -> ndarray: ...
    def nr_vxc(self, cell, grids, xc_code, dms, spin: int = 0, relativity: int = 0, hermi: int = 1, kpts=None, kpts_band=None, max_memory: int = 2000, with_j: bool = False, return_j: bool = False, verbose=None): ...
    get_vxc = nr_vxc
    def nr_rks(self, cell: Cell, grids: UniformGrids, xc_code: str, dm_kpts: Union[ndarray, NPArrayWithTag], relativity: int = 0, hermi: int = 1, kpts: Optional[Union[ndarray, KPoints]]=None, kpts_band: Optional[ndarray]=None, max_memory: float = 2000, verbose: None=None) -> Tuple[float64, float64, NPArrayWithTag]: ...
    def nr_uks(self, cell: Cell, grids: Optional[UniformGrids], xc_code: str, dm_kpts: Union[NPArrayWithTag, ndarray, Tuple[ndarray, ndarray]], relativity: int = 0, hermi: int = 1, kpts: Optional[Union[ndarray, KPoints]]=None, kpts_band: Optional[ndarray]=None, max_memory: Union[float, int] = 2000, verbose: None=None) -> Tuple[ndarray, float64, NPArrayWithTag]: ...
    def nr_rks_fxc(self, cell: Cell, grids: Optional[UniformGrids], xc_code: str, dm0: Optional[ndarray], dms: ndarray, relativity: int = 0, hermi: int = 0, rho0: Optional[ndarray]=None, vxc: Optional[ndarray]=None, fxc: Optional[ndarray]=None, kpts: Optional[Union[ndarray, KPoints]]=None, max_memory: Union[float, int] = 2000, verbose: None=None) -> ndarray: ...
    def nr_uks_fxc(self, cell: Cell, grids: Optional[UniformGrids], xc_code: str, dm0: Optional[Tuple[ndarray, ndarray]], dms: Union[ndarray, Tuple[ndarray, ndarray]], relativity: int = 0, hermi: int = 0, rho0: Optional[ndarray]=None, vxc: Optional[ndarray]=None, fxc: Optional[ndarray]=None, kpts: Optional[Union[ndarray, KPoints]]=None, max_memory: Union[float, int] = 2000, verbose: None=None) -> ndarray: ...
    def nr_rks_fxc_st(self, cell: Cell, grids: Optional[UniformGrids], xc_code: str, dm0: Optional[ndarray], dms_alpha: ndarray, hermi: int = 1, singlet: bool = True, rho0: Optional[ndarray]=None, vxc: Optional[ndarray]=None, fxc: Optional[ndarray]=None, kpts: Optional[ndarray]=None, max_memory: Union[float, int] = 2000, verbose: None=None) -> ndarray: ...
    def cache_xc_kernel(self, cell: Cell, grids: UniformGrids, xc_code: str, mo_coeff: Union[ndarray, Tuple[ndarray, ndarray]], mo_occ: ndarray, spin: int = 0, kpts: Optional[Union[ndarray, KPoints]]=None, max_memory: int = 2000) -> Tuple[ndarray, ndarray, ndarray]: ...
    def cache_xc_kernel1(self, cell, grids, xc_code, dm, spin: int = 0, kpts=None, max_memory: int = 2000): ...
    def nr_nlc_vxc(self, cell, grids, xc_code, dms, relativity: int = 0, hermi: int = 1, kpts=None, kpts_band=None, max_memory: int = 2000, verbose=None) -> None: ...
    def get_rho(self, cell: Cell, dm: Union[NPArrayWithTag, ndarray], grids: UniformGrids, kpts: Union[ndarray, KPoints]=..., max_memory: int = 2000) -> ndarray: ...
    range_coulomb: Incomplete
    to_gpu = lib.to_gpu
NumInt = MultiGridNumInt

def multigrid_fftdf(mf): ...
multigrid = multigrid_fftdf
