from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.gto import moleintor as moleintor
from pyscf.lib import logger as logger
from pyscf.pbc import tools as tools
from pyscf.pbc.df import fft as fft
from pyscf.pbc.dft.multigrid.multigrid import MGGA_DENSITY_LAPL as MGGA_DENSITY_LAPL, MultiGridNumInt as MultiGridNumInt_v1
from pyscf.pbc.dft.multigrid.pp import get_vpploc_part1_ip1 as get_vpploc_part1_ip1, vpploc_part1_nuc_grad as vpploc_part1_nuc_grad
from pyscf.pbc.lib.kpts import KPoints as KPoints
from pyscf.pbc.lib.kpts_helper import is_gamma_point as is_gamma_point
from numpy import float64, ndarray
from pyscf.lib.logger import Logger
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.dft.gen_grid import UniformGrids
from pyscf.pbc.dft.multigrid._backend_c import RS_Grid, TaskList
from pyscf.pbc.gto.cell import Cell
from typing import List, Optional, Tuple, Union

NTASKS: Incomplete
KE_RATIO: Incomplete
REL_CUTOFF: Incomplete
GGA_METHOD: Incomplete
EXTRA_PREC: Incomplete
RHOG_HIGH_ORDER: Incomplete
PTR_EXPDROP: int

def multi_grids_tasks(cell: Cell, ke_cutoff: None=None, hermi: int = 0, ntasks: int=..., ke_ratio: float=..., rel_cutoff: float=...) -> TaskList: ...
def eval_rho(cell: Cell, dm: ndarray, task_list: TaskList, shls_slice: None=None, hermi: int = 0, xctype: str = 'LDA', kpts: Optional[ndarray]=None, dimension: None=None, cell1: None=None, shls_slice1: None=None, a: None=None, ignore_imag: bool = False) -> Union[List[RS_Grid], RS_Grid]: ...
def eval_mat(cell: Cell, weights: ndarray, task_list: TaskList, shls_slice: None=None, comp: int = 1, hermi: int = 0, deriv: int = 0, xctype: str = 'LDA', kpts: Optional[ndarray]=None, grid_level: Optional[int]=None, dimension: None=None, mesh: Optional[ndarray]=None, cell1: None=None, shls_slice1: None=None, a: None=None) -> List[ndarray]: ...
def nr_rks(mydf: "MultiGridNumInt", xc_code: str, dm_kpts: Union[ndarray, NPArrayWithTag], hermi: int = 1, kpts: Optional[ndarray]=None, kpts_band: None=None, with_j: bool = False, return_j: bool = False, verbose: None=None) -> Tuple[float64, float64, NPArrayWithTag]: ...
def nr_uks(mydf: "MultiGridNumInt", xc_code: str, dm_kpts: Union[ndarray, NPArrayWithTag], hermi: int = 1, kpts: Optional[ndarray]=None, kpts_band: None=None, with_j: bool = False, return_j: bool = False, verbose: None=None) -> Tuple[ndarray, float64, NPArrayWithTag]: ...
def get_veff_ip1(mydf: "MultiGridNumInt", dm_kpts: NPArrayWithTag, xc_code: Optional[str]=None, kpts: ndarray=..., kpts_band: None=None, spin: int = 0) -> ndarray: ...
def get_nuc(mydf: "MultiGridNumInt", kpts: Optional[ndarray]=None, deriv: int = 0) -> ndarray: ...
def get_nuc_ip1(mydf: "MultiGridNumInt", kpts: Optional[ndarray]=None) -> ndarray: ...
def get_nuc_nuc_grad(mydf: "MultiGridNumInt", dm: Union[NPArrayWithTag, ndarray], kpts: Optional[ndarray]=None) -> ndarray: ...

class MultiGridNumInt(MultiGridNumInt_v1):
    ntasks = NTASKS
    ke_ratio = KE_RATIO
    rel_cutoff = REL_CUTOFF
    task_list: Incomplete
    vpplocG_part1: Incomplete
    rhoG: Incomplete
    def __init__(self, cell: Cell) -> None: ...
    def reset(self, cell=None): ...
    @property
    def ngrids(self): ...
    @ngrids.setter
    def ngrids(self, x) -> None: ...
    def get_veff_ip1(self, dm: NPArrayWithTag, xc_code: Optional[str]=None, kpts: Optional[ndarray]=None, kpts_band: None=None, spin: int = 0) -> ndarray: ...
    def get_pp(self, kpts: Optional[ndarray]=None, return_full: bool = False) -> ndarray: ...
    get_nuc = get_nuc
    get_nuc_ip1 = get_nuc_ip1
    get_nuc_nuc_grad = get_nuc_nuc_grad
    vpploc_part1_nuc_grad = vpploc_part1_nuc_grad
    get_vpploc_part1_ip1 = get_vpploc_part1_ip1
    def nr_rks(self, cell: Cell, grids: UniformGrids, xc_code: str, dm_kpts: Union[ndarray, NPArrayWithTag], relativity: int = 0, hermi: int = 1, kpts: Optional[ndarray]=None, kpts_band: None=None, max_memory: float = 2000, verbose: None=None) -> Tuple[float64, float64, NPArrayWithTag]: ...
    def nr_uks(self, cell: Cell, grids: UniformGrids, xc_code: str, dm_kpts: Union[ndarray, NPArrayWithTag], relativity: int = 0, hermi: int = 1, kpts: Optional[ndarray]=None, kpts_band: None=None, max_memory: float = 2000, verbose: None=None) -> Tuple[ndarray, float64, NPArrayWithTag]: ...
    def nr_rks_fxc(self, cell, grids, xc_code, dm0, dms, relativity: int = 0, hermi: int = 0, rho0=None, vxc=None, fxc=None, kpts=None, max_memory: int = 2000, verbose=None): ...
    def nr_uks_fxc(self, cell, grids, xc_code, dm0, dms, relativity: int = 0, hermi: int = 0, rho0=None, vxc=None, fxc=None, kpts=None, max_memory: int = 2000, verbose=None): ...
    def nr_rks_fxc_st(self, cell, grids, xc_code, dm0, dms_alpha, hermi: int = 1, singlet: bool = True, rho0=None, vxc=None, fxc=None, kpts=None, max_memory: int = 2000, verbose=None): ...
    def cache_xc_kernel(self, cell, grids, xc_code, mo_coeff, mo_occ, spin: int = 0, kpts=None, max_memory: int = 2000): ...
    def cache_xc_kernel1(self, cell, grids, xc_code, dm, spin: int = 0, kpts=None, max_memory: int = 2000): ...
    def get_rho(self, cell, dm, grids, kpts=None, max_memory: int = 2000): ...
