from _typeshed import Incomplete
from pyscf import df as df, gto as gto, lib as lib, scf as scf
from pyscf.lib import logger as logger
from pyscf.solvent.grad.pcm import get_dD_dS as get_dD_dS, get_dF_dA as get_dF_dA, grad_nuc as grad_nuc, grad_qv as grad_qv, grad_switch_h as grad_switch_h
from pyscf.solvent.pcm import PCM, PI as PI, switch_h as switch_h
from numpy import int64, ndarray
from pyscf.lib.logger import Logger
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.solvent.smd import SMD
from typing import Dict, List, Optional, Tuple, Union

def gradgrad_switch_h(x: ndarray) -> ndarray: ...
def get_d2F_d2A(surface: Dict[str, Union[int, List[List[Union[int, int64]]], ndarray]], surface_discretization_method: str = 'SWIG') -> Tuple[ndarray, ndarray]: ...
def get_d2Sii(surface: Dict[str, Union[int, List[List[Union[int, int64]]], ndarray]], dF: ndarray, d2F: ndarray, stream: None=None) -> ndarray: ...
def get_d2D_d2S(surface: Dict[str, Union[int, List[List[Union[int, int64]]], ndarray]], with_S: bool = True, with_D: bool = False, stream: None=None) -> Union[Tuple[None, ndarray], Tuple[ndarray, ndarray]]: ...
def analytical_hess_nuc(pcmobj: Union[SMD, PCM], dm: Union[ndarray, NPArrayWithTag], verbose: Optional[int]=None) -> ndarray: ...
def analytical_hess_qv(pcmobj: Union[SMD, PCM], dm: Union[ndarray, NPArrayWithTag], verbose: Optional[int]=None) -> ndarray: ...
def einsum_ij_Adj_Adi_inverseK(K: ndarray, Adj_term: ndarray) -> ndarray: ...
def einsum_Adi_ij_Adj_inverseK(Adi_term: ndarray, K: ndarray) -> ndarray: ...
def get_dS_dot_q(dS: ndarray, dSii: ndarray, q: ndarray, atmlst: range, gridslice: List[List[Union[int, int64]]]) -> ndarray: ...
def get_dST_dot_q(dS: ndarray, dSii: ndarray, q: ndarray, atmlst: range, gridslice: List[List[Union[int, int64]]]) -> ndarray: ...
def get_dA_dot_q(dA: ndarray, q: ndarray, atmlst: range) -> ndarray: ...
def get_dD_dot_q(dD: ndarray, q: ndarray, atmlst: range, gridslice: List[List[Union[int, int64]]], ngrids: int) -> ndarray: ...
def get_dDT_dot_q(dD: ndarray, q: ndarray, atmlst: range, gridslice: List[List[Union[int, int64]]], ngrids: int) -> ndarray: ...
def get_v_dot_d2S_dot_q(d2S: ndarray, d2Sii: ndarray, v_left: ndarray, q_right: ndarray, natom: int, gridslice: List[List[Union[int, int64]]]) -> ndarray: ...
def get_v_dot_d2ST_dot_q(d2S: ndarray, d2Sii: ndarray, v_left: ndarray, q_right: ndarray, natom: int, gridslice: List[List[Union[int, int64]]]) -> ndarray: ...
def get_v_dot_d2A_dot_q(d2A: ndarray, v_left: ndarray, q_right: ndarray) -> ndarray: ...
def get_v_dot_d2D_dot_q(d2D: ndarray, v_left: ndarray, q_right: ndarray, natom: int, gridslice: List[List[Union[int, int64]]]) -> ndarray: ...
def get_v_dot_d2DT_dot_q(d2D: ndarray, v_left: ndarray, q_right: ndarray, natom: int, gridslice: List[List[Union[int, int64]]]) -> ndarray: ...
def analytical_hess_solver(pcmobj: Union[SMD, PCM], dm: Union[ndarray, NPArrayWithTag], verbose: Optional[int]=None) -> ndarray: ...
def get_dqsym_dx_fix_vgrids(pcmobj: Union[SMD, PCM], atmlst: range) -> ndarray: ...
def get_dvgrids(pcmobj: Union[SMD, PCM], dm: Union[ndarray, NPArrayWithTag], atmlst: range) -> ndarray: ...
def get_dqsym_dx_fix_K_R(pcmobj: Union[SMD, PCM], dm: Union[ndarray, NPArrayWithTag], atmlst: range) -> ndarray: ...
def get_dqsym_dx(pcmobj: Union[SMD, PCM], dm: Union[ndarray, NPArrayWithTag], atmlst: range) -> ndarray: ...
def analytical_grad_vmat(pcmobj: Union[SMD, PCM], dm: Union[ndarray, NPArrayWithTag], atmlst: Optional[range]=None, verbose: Optional[Logger]=None) -> ndarray: ...
def make_hess_object(base_method): ...

class WithSolventHess:
    de_solvent: Incomplete
    de_solute: Incomplete
    def __init__(self, hess_method: Union[Incomplete, Incomplete, Incomplete]) -> None: ...
    def undo_solvent(self): ...
    def to_gpu(self): ...
    de: Incomplete
    def kernel(self, *args, dm=None, atmlst=None, **kwargs): ...
    def make_h1(self, mo_coeff, mo_occ, chkfile=None, atmlst=None, verbose=None): ...
