from _typeshed import Incomplete
from pyscf import df as df, gto as gto, lib as lib, scf as scf
from pyscf.lib import logger as logger
from pyscf.solvent.grad.pcm import get_dD_dS as get_dD_dS, get_dF_dA as get_dF_dA, grad_nuc as grad_nuc, grad_qv as grad_qv, grad_switch_h as grad_switch_h
from pyscf.solvent.pcm import PI as PI, switch_h as switch_h

def gradgrad_switch_h(x): ...
def get_d2F_d2A(surface, surface_discretization_method: str = 'SWIG'): ...
def get_d2Sii(surface, dF, d2F, stream=None): ...
def get_d2D_d2S(surface, with_S: bool = True, with_D: bool = False, stream=None): ...
def analytical_hess_nuc(pcmobj, dm, verbose=None): ...
def analytical_hess_qv(pcmobj, dm, verbose=None): ...
def einsum_ij_Adj_Adi_inverseK(K, Adj_term): ...
def einsum_Adi_ij_Adj_inverseK(Adi_term, K): ...
def get_dS_dot_q(dS, dSii, q, atmlst, gridslice): ...
def get_dST_dot_q(dS, dSii, q, atmlst, gridslice): ...
def get_dA_dot_q(dA, q, atmlst): ...
def get_dD_dot_q(dD, q, atmlst, gridslice, ngrids): ...
def get_dDT_dot_q(dD, q, atmlst, gridslice, ngrids): ...
def get_v_dot_d2S_dot_q(d2S, d2Sii, v_left, q_right, natom, gridslice): ...
def get_v_dot_d2ST_dot_q(d2S, d2Sii, v_left, q_right, natom, gridslice): ...
def get_v_dot_d2A_dot_q(d2A, v_left, q_right): ...
def get_v_dot_d2D_dot_q(d2D, v_left, q_right, natom, gridslice): ...
def get_v_dot_d2DT_dot_q(d2D, v_left, q_right, natom, gridslice): ...
def analytical_hess_solver(pcmobj, dm, verbose=None): ...
def get_dqsym_dx_fix_vgrids(pcmobj, atmlst): ...
def get_dvgrids(pcmobj, dm, atmlst): ...
def get_dqsym_dx_fix_K_R(pcmobj, dm, atmlst): ...
def get_dqsym_dx(pcmobj, dm, atmlst): ...
def analytical_grad_vmat(pcmobj, dm, atmlst=None, verbose=None): ...
def make_hess_object(base_method): ...

class WithSolventHess:
    de_solvent: Incomplete
    de_solute: Incomplete
    def __init__(self, hess_method) -> None: ...
    def undo_solvent(self): ...
    def to_gpu(self): ...
    de: Incomplete
    def kernel(self, *args, dm=None, atmlst=None, **kwargs): ...
    def make_h1(self, mo_coeff, mo_occ, chkfile=None, atmlst=None, verbose=None): ...
