import ctypes
from _typeshed import Incomplete
from pyscf import lib as lib

libpbc: Incomplete

class PBCOpt:
    def __init__(self, cell) -> None: ...
    def init_rcut_cond(self, cell, precision=None): ...
    def del_rcut_cond(self): ...
    def __del__(self) -> None: ...

class _CPBCOpt(ctypes.Structure): ...
