import ctypes
from _typeshed import Incomplete
from pyscf import lib as lib
from pyscf.pbc.gto.cell import Cell

libpbc: Incomplete

class PBCOpt:
    def __init__(self, cell: Cell) -> None: ...
    def init_rcut_cond(self, cell: Cell, precision: None=None) -> "PBCOpt": ...
    def del_rcut_cond(self): ...
    def __del__(self) -> None: ...

class _CPBCOpt(ctypes.Structure): ...
