from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.dft import radi as radi
from pyscf.gto import mole as mole, moleintor as moleintor
from pyscf.gto.mole import Mole, _MoleLazyCallAdapter, conc_env as conc_env, is_au as is_au
from pyscf.lib import logger as logger
from pyscf.pbc.gto.eval_gto import eval_gto as pbc_eval_gto
from pyscf.pbc.tools import pbc as pbctools
from numpy import float64, int32, int64, ndarray
from pyscf.pbc.df.ft_ao import ExtendedMole, _RangeSeparatedCell
from pyscf.pbc.df.rsdf_builder import _ExtendedMoleFT
from pyscf.pbc.lib.kpts import KPoints
from typing import Any, List, Optional, Tuple, Union

INTEGRAL_PRECISION: Incomplete
WRAP_AROUND: Incomplete
WITH_GAMMA: Incomplete
EXP_DELIMITER: Incomplete
RCUT_EPS: float
RCUT_MAX_CYCLE: int
libpbc: Incomplete

def M(*args, **kwargs) -> "Cell": ...
C = M

def pack(cell): ...
def unpack(celldic): ...
def dumps(cell: "Cell") -> str: ...
def loads(cellstr: Union[bytes, str]) -> "Cell": ...
def conc_cell(cell1: "Cell", cell2: "Cell") -> "Cell": ...
def intor_cross(intor: str, cell1: Union[Cell, _RangeSeparatedCell], cell2: Union[Cell, _RangeSeparatedCell], comp: Optional[int]=None, hermi: int = 0, kpts: Optional[Union[ndarray, List[ndarray]]]=None, kpt: Optional[ndarray]=None, shls_slice: None=None, **kwargs) -> Union[ndarray, List[ndarray]]: ...
def get_nimgs(cell: "Cell", precision: Optional[float]=None) -> ndarray: ...
def bas_rcut(cell: "Cell", bas_id: int, precision: Optional[float]=None) -> float64: ...
def estimate_rcut(cell: Union[Cell, _RangeSeparatedCell], precision: Optional[float]=None) -> float64: ...
def estimate_ke_cutoff(cell: "Cell", precision: Optional[float]=None) -> float64: ...
def error_for_ke_cutoff(cell: "Cell", ke_cutoff: float64, omega: None=None) -> float64: ...
def get_bounding_sphere(cell: "Cell", rcut: Union[float, float64, int]) -> ndarray: ...
def get_Gv(cell: "Cell", mesh: Optional[Union[ndarray, List[int]]]=None, **kwargs) -> ndarray: ...
def get_Gv_weights(cell: Union[Cell, _RangeSeparatedCell], mesh: Optional[Union[ndarray, List[int]]]=None, **kwargs) -> Union[Tuple[ndarray, Tuple[ndarray, ndarray, ndarray], float64], Tuple[ndarray, Tuple[ndarray, ndarray, ndarray], ndarray]]: ...
def get_SI(cell: "Cell", Gv: Optional[ndarray]=None, mesh: Optional[Union[ndarray, List[int]]]=None, atmlst: Optional[List[int]]=None) -> ndarray: ...
def get_ewald_params(cell: "Cell", precision: None=None, mesh: None=None) -> Union[Tuple[float64, float], Tuple[float64, float64]]: ...
def ewald(cell: "Cell", ew_eta: Optional[Union[float, int]]=None, ew_cut: Optional[int]=None) -> Union[int, float64]: ...
energy_nuc = ewald

def make_kpts(cell: "Cell", nks: Union[ndarray, Tuple[int, int, int], List[int]], wrap_around: bool=..., with_gamma_point: bool=..., scaled_center: Optional[Union[ndarray, Tuple[float, float, float], List[float], List[int]]]=None, space_group_symmetry: bool = False, time_reversal_symmetry: bool = False, **kwargs) -> Union[ndarray, KPoints]: ...
def get_uniform_grids(cell: "Cell", mesh: Optional[Union[ndarray, Tuple[int64, int64, int64], List[int]]]=None, wrap_around: bool = True) -> ndarray: ...
gen_uniform_grids = get_uniform_grids

def tot_electrons(cell: "Cell", nkpts: int = 1) -> int: ...
def pgf_rcut(l: int, alpha: float, coeff: float64, precision: float=..., rcut: int = 0, max_cycle: int=..., eps: float=...) -> float64: ...
def rcut_by_shells(cell: "Cell", precision: Optional[float]=None, rcut: int = 0, return_pgf_radius: bool = False) -> Union[ndarray, Tuple[ndarray, ndarray]]: ...
def tostring(cell: "Cell", format: str = 'poscar') -> str: ...
def tofile(cell: "Cell", filename: str, format: Optional[str]=None) -> str: ...
def fromfile(filename: str, format: Optional[str]=None) -> Tuple[str, str]: ...
def fromstring(string: str, format: str = 'poscar') -> Union[Tuple[ndarray, List[Tuple[str, ndarray]]], Tuple[str, str]]: ...

class Cell(mole.MoleBase):
    precision: Incomplete
    exp_to_discard: Incomplete
    fractional: bool
    dimension: int
    low_dim_ft_type: Incomplete
    use_loose_rcut: bool
    use_particle_mesh_ewald: bool
    space_group_symmetry: bool
    symmorphic: bool
    lattice_symmetry: Incomplete
    tostring = tostring
    tofile = tofile
    a: Incomplete
    ke_cutoff: Incomplete
    def __init__(self, **kwargs) -> None: ...
    def fromstring(self, string: str, format: str = 'poscar') -> "Cell": ...
    def fromfile(self, filename: str, format: Optional[str]=None) -> "Cell": ...
    @property
    def mesh(self): ...
    @mesh.setter
    def mesh(self, x) -> None: ...
    @property
    def rcut(self): ...
    @rcut.setter
    def rcut(self, x) -> None: ...
    @property
    def ew_eta(self): ...
    @property
    def ew_cut(self): ...
    @ew_eta.setter
    def ew_eta(self, val) -> None: ...
    @ew_cut.setter
    def ew_cut(self, val) -> None: ...
    @property
    def nelec(self) -> Tuple[int, int]: ...
    def __getattr__(self, key: str) -> _MoleLazyCallAdapter: ...
    tot_electrons = tot_electrons
    def symmetrize_mesh(self, mesh: Optional[Union[ndarray, List[int]]]=None) -> Union[ndarray, List[int]]: ...
    def build_lattice_symmetry(self, check_mesh_symmetry: bool = True) -> Union[Cell, _RangeSeparatedCell]: ...
    def format_atom(self, atoms: Any, origin: int = 0, axes: None=None, unit: Union[float, str]=...) -> List[Tuple[str, List[float]]]: ...
    def build(self, dump_input: Union[bool, int] = True, parse_arg: Union[bool, int]=..., a: Optional[Any]=None, mesh: Optional[List[int]]=None, ke_cutoff: Optional[int]=None, precision: Optional[float]=None, nimgs: None=None, h: None=None, dimension: Optional[int]=None, rcut: Optional[float]=None, low_dim_ft_type: Optional[str]=None, space_group_symmetry: Optional[bool]=None, symmorphic: Optional[bool]=None, use_loose_rcut: None=None, use_particle_mesh_ewald: None=None, fractional: Optional[bool]=None, *args, **kwargs) -> "Cell": ...
    kernel = build
    @property
    def h(self): ...
    @h.setter
    def h(self, x) -> None: ...
    @property
    def vol(self) -> float64: ...
    @property
    def Gv(self) -> ndarray: ...
    @property
    def gs(self): ...
    @gs.setter
    def gs(self, x) -> None: ...
    @property
    def drop_exponent(self): ...
    @drop_exponent.setter
    def drop_exponent(self, x) -> None: ...
    @property
    def nimgs(self): ...
    @nimgs.setter
    def nimgs(self, x) -> None: ...
    def lattice_vectors(self, unit: str = 'Bohr') -> ndarray: ...
    def get_scaled_atom_coords(self, a: Optional[ndarray]=None) -> ndarray: ...
    def reciprocal_vectors(self, norm_to: Union[float, int]=...) -> ndarray: ...
    def get_abs_kpts(self, scaled_kpts: Union[ndarray, List[List[float]], List[float], List[float64]]) -> ndarray: ...
    def get_scaled_kpts(self, abs_kpts: Union[ndarray, List[List[float]], List[ndarray], KPoints], kpts_in_ibz: bool = True) -> ndarray: ...
    def cutoff_to_mesh(self, ke_cutoff: Union[float, float64]) -> ndarray: ...
    make_kpts = make_kpts
    get_kpts = make_kpts
    pack = pack
    @classmethod
    def unpack(cls, moldic): ...
    def unpack_(self, moldic): ...
    dumps = dumps
    @classmethod
    def loads(cls, molstr: str) -> "Cell": ...
    def loads_(self, molstr): ...
    bas_rcut = bas_rcut
    rcut_by_shells = rcut_by_shells
    get_lattice_Ls = pbctools.get_lattice_Ls
    get_nimgs = get_nimgs
    get_ewald_params = get_ewald_params
    get_bounding_sphere = get_bounding_sphere
    get_Gv = get_Gv
    get_Gv_weights = get_Gv_weights
    get_SI = get_SI
    ewald = ewald
    energy_nuc = ewald
    get_enuc = ewald
    gen_uniform_grids = get_uniform_grids
    get_uniform_grids = get_uniform_grids
    __add__ = conc_cell
    def pbc_intor(self, intor: str, comp: Optional[int]=None, hermi: int = 0, kpts: Optional[Union[ndarray, List[ndarray]]]=None, kpt: Optional[ndarray]=None, shls_slice: None=None, **kwargs) -> Union[ndarray, List[ndarray]]: ...
    pbc_eval_ao = pbc_eval_gto
    pbc_eval_gto = pbc_eval_gto
    def eval_gto(self, eval_name: str, coords: ndarray, comp: Optional[int]=None, kpts: None=None, kpt: Optional[ndarray]=None, shls_slice: None=None, non0tab: None=None, ao_loc: None=None, cutoff: Optional[float]=None, out: Optional[ndarray]=None) -> ndarray: ...
    eval_ao = eval_gto
    atom: Incomplete
    def from_ase(self, ase_atom): ...
    def to_mol(self) -> Mole: ...
    def to_gpu(self): ...
    def set_geom_(self, atoms_or_coords: Optional[Union[ndarray, List[Tuple[str, ndarray]], str, List[List[Union[str, List[float]]]]]]=None, unit: Optional[str]=None, symmetry: None=None, a: Optional[Union[str, ndarray]]=None, inplace: bool = True) -> "Cell": ...
