from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.dft import radi as radi
from pyscf.gto import mole as mole, moleintor as moleintor
from pyscf.gto.mole import conc_env as conc_env, is_au as is_au
from pyscf.lib import logger as logger
from pyscf.pbc.gto.eval_gto import eval_gto as pbc_eval_gto
from pyscf.pbc.tools import pbc as pbctools

INTEGRAL_PRECISION: Incomplete
WRAP_AROUND: Incomplete
WITH_GAMMA: Incomplete
EXP_DELIMITER: Incomplete
RCUT_EPS: float
RCUT_MAX_CYCLE: int
libpbc: Incomplete

def M(*args, **kwargs): ...
C = M

def pack(cell): ...
def unpack(celldic): ...
def dumps(cell): ...
def loads(cellstr): ...
def conc_cell(cell1, cell2): ...
def intor_cross(intor, cell1, cell2, comp=None, hermi: int = 0, kpts=None, kpt=None, shls_slice=None, **kwargs): ...
def get_nimgs(cell, precision=None): ...
def bas_rcut(cell, bas_id, precision=None): ...
def estimate_rcut(cell, precision=None): ...
def estimate_ke_cutoff(cell, precision=None): ...
def error_for_ke_cutoff(cell, ke_cutoff, omega=None): ...
def get_bounding_sphere(cell, rcut): ...
def get_Gv(cell, mesh=None, **kwargs): ...
def get_Gv_weights(cell, mesh=None, **kwargs): ...
def get_SI(cell, Gv=None, mesh=None, atmlst=None): ...
def get_ewald_params(cell, precision=None, mesh=None): ...
def ewald(cell, ew_eta=None, ew_cut=None): ...
energy_nuc = ewald

def make_kpts(cell, nks, wrap_around=..., with_gamma_point=..., scaled_center=None, space_group_symmetry: bool = False, time_reversal_symmetry: bool = False, **kwargs): ...
def get_uniform_grids(cell, mesh=None, wrap_around: bool = True): ...
gen_uniform_grids = get_uniform_grids

def tot_electrons(cell, nkpts: int = 1): ...
def pgf_rcut(l, alpha, coeff, precision=..., rcut: int = 0, max_cycle=..., eps=...): ...
def rcut_by_shells(cell, precision=None, rcut: int = 0, return_pgf_radius: bool = False): ...
def tostring(cell, format: str = 'poscar'): ...
def tofile(cell, filename, format=None): ...
def fromfile(filename, format=None): ...
def fromstring(string, format: str = 'poscar'): ...

class Cell(mole.MoleBase):
    precision: Incomplete
    exp_to_discard: Incomplete
    fractional: bool
    dimension: int
    low_dim_ft_type: Incomplete
    use_loose_rcut: bool
    use_particle_mesh_ewald: bool
    space_group_symmetry: bool
    symmorphic: bool
    lattice_symmetry: Incomplete
    tostring = tostring
    tofile = tofile
    a: Incomplete
    ke_cutoff: Incomplete
    def __init__(self, **kwargs) -> None: ...
    def fromstring(self, string, format: str = 'poscar'): ...
    def fromfile(self, filename, format=None): ...
    @property
    def mesh(self): ...
    @mesh.setter
    def mesh(self, x) -> None: ...
    @property
    def rcut(self): ...
    @rcut.setter
    def rcut(self, x) -> None: ...
    @property
    def ew_eta(self): ...
    @property
    def ew_cut(self): ...
    @ew_eta.setter
    def ew_eta(self, val) -> None: ...
    @ew_cut.setter
    def ew_cut(self, val) -> None: ...
    @property
    def nelec(self): ...
    def __getattr__(self, key): ...
    tot_electrons = tot_electrons
    def symmetrize_mesh(self, mesh=None): ...
    def build_lattice_symmetry(self, check_mesh_symmetry: bool = True): ...
    def format_atom(self, atoms, origin: int = 0, axes=None, unit=...): ...
    def build(self, dump_input: bool = True, parse_arg=..., a=None, mesh=None, ke_cutoff=None, precision=None, nimgs=None, h=None, dimension=None, rcut=None, low_dim_ft_type=None, space_group_symmetry=None, symmorphic=None, use_loose_rcut=None, use_particle_mesh_ewald=None, fractional=None, *args, **kwargs): ...
    kernel = build
    @property
    def h(self): ...
    @h.setter
    def h(self, x) -> None: ...
    @property
    def vol(self): ...
    @property
    def Gv(self): ...
    @property
    def gs(self): ...
    @gs.setter
    def gs(self, x) -> None: ...
    @property
    def drop_exponent(self): ...
    @drop_exponent.setter
    def drop_exponent(self, x) -> None: ...
    @property
    def nimgs(self): ...
    @nimgs.setter
    def nimgs(self, x) -> None: ...
    def lattice_vectors(self, unit: str = 'Bohr'): ...
    def get_scaled_atom_coords(self, a=None): ...
    def reciprocal_vectors(self, norm_to=...): ...
    def get_abs_kpts(self, scaled_kpts): ...
    def get_scaled_kpts(self, abs_kpts, kpts_in_ibz: bool = True): ...
    def cutoff_to_mesh(self, ke_cutoff): ...
    make_kpts = make_kpts
    get_kpts = make_kpts
    pack = pack
    @classmethod
    def unpack(cls, moldic): ...
    def unpack_(self, moldic): ...
    dumps = dumps
    @classmethod
    def loads(cls, molstr): ...
    def loads_(self, molstr): ...
    bas_rcut = bas_rcut
    rcut_by_shells = rcut_by_shells
    get_lattice_Ls = pbctools.get_lattice_Ls
    get_nimgs = get_nimgs
    get_ewald_params = get_ewald_params
    get_bounding_sphere = get_bounding_sphere
    get_Gv = get_Gv
    get_Gv_weights = get_Gv_weights
    get_SI = get_SI
    ewald = ewald
    energy_nuc = ewald
    get_enuc = ewald
    gen_uniform_grids = get_uniform_grids
    get_uniform_grids = get_uniform_grids
    __add__ = conc_cell
    def pbc_intor(self, intor, comp=None, hermi: int = 0, kpts=None, kpt=None, shls_slice=None, **kwargs): ...
    pbc_eval_ao = pbc_eval_gto
    pbc_eval_gto = pbc_eval_gto
    def eval_gto(self, eval_name, coords, comp=None, kpts=None, kpt=None, shls_slice=None, non0tab=None, ao_loc=None, cutoff=None, out=None): ...
    eval_ao = eval_gto
    atom: Incomplete
    def from_ase(self, ase_atom): ...
    def to_mol(self): ...
    def to_gpu(self): ...
    def set_geom_(self, atoms_or_coords=None, unit=None, symmetry=None, a=None, inplace: bool = True): ...
