import ctypes
from _typeshed import Incomplete
from pyscf import lib as lib
from pyscf.lib import logger as logger

libpbc: Incomplete

class _CNeighborPair(ctypes.Structure): ...
class _CNeighborList(ctypes.Structure): ...
class _CNeighborListOpt(ctypes.Structure): ...

def build_neighbor_list_for_shlpairs(cell, cell1=None, Ls=None, ish_rcut=None, jsh_rcut=None, hermi: int = 0, precision=None): ...
def free_neighbor_list(nl) -> None: ...
def neighbor_list_to_ndarray(cell, cell1, nl): ...

class NeighborListOpt:
    cell: Incomplete
    nl: Incomplete
    def __init__(self, cell) -> None: ...
    def build(self, cell=None, cell1=None, Ls=None, ish_rcut=None, jsh_rcut=None, hermi: int = 0, precision=None, set_nl: bool = True, set_optimizer: bool = True) -> None: ...
    def reset(self, free_nl: bool = True) -> None: ...
    def __del__(self) -> None: ...
