from numpy import int32
from typing import Any, List, Tuple, Union

def remove_dup(fn_facs: List[Union[Tuple[int, int], Tuple[int, float], Any, Tuple[int32, int], Tuple[int32, float]]]) -> List[Union[Tuple[int, int], Tuple[int, float], Any, Tuple[int32, int], Tuple[int32, float]]]: ...
def format_xc_code(description: str) -> str: ...
