from pyscf.solvent import ddcosmo as ddcosmo, pcm as pcm, smd as smd

def ddCOSMO(method_or_mol, solvent_obj=None, dm=None): ...
DDCOSMO = ddCOSMO

def ddPCM(method_or_mol, solvent_obj=None, dm=None): ...
DDPCM = ddPCM

def PE(method_or_mol, solvent_obj=None, dm=None): ...
def PCM(method_or_mol, solvent_obj=None, dm=None): ...
PCM = PCM

def SMD(method_or_mol, solvent_obj=None, dm=None): ...
SMD = SMD
