from _typeshed import Incomplete
from pyscf import lib as lib, scf as scf
from pyscf.lib import logger as logger
from pyscf.dft.rks import RKS
from pyscf.dft.uks import UKS
from pyscf.mcscf.casci import CASCI
from pyscf.mcscf.mc1step import CASSCF
from pyscf.scf.hf import RHF
from pyscf.scf.rohf import ROHF
from pyscf.scf.uhf import UHF
from pyscf.solvent.ddcosmo import ddCOSMO
from pyscf.solvent.ddpcm import ddPCM
from pyscf.solvent.pcm import PCM
from pyscf.solvent.smd import SMD
from pyscf.tdscf.rhf import TDBase
from typing import Union

class _Solvation: ...

class SCFWithSolvent(_Solvation):
    with_solvent: Incomplete
    def __init__(self, mf: Union[RKS, UHF, RHF, UKS, ROHF], solvent: Union[ddCOSMO, SMD, PCM, ddPCM]) -> None: ...
    def undo_solvent(self): ...
    def dump_flags(self, verbose=None): ...
    def reset(self, mol=None): ...
    def get_veff(self, mol=None, dm=None, *args, **kwargs): ...
    def get_fock(self, h1e=None, s1e=None, vhf=None, dm=None, cycle: int = -1, diis=None, diis_start_cycle=None, level_shift_factor=None, damp_factor=None, fock_last=None): ...
    def energy_elec(self, dm=None, h1e=None, vhf=None): ...
    def nuc_grad_method(self): ...
    Gradients = nuc_grad_method
    def Hessian(self): ...
    def gen_response(self, *args, **kwargs): ...
    def stability(self, *args, **kwargs): ...
    def to_gpu(self): ...
    def TDA(self, equilibrium_solvation: bool = False): ...
    def TDHF(self, equilibrium_solvation: bool = False): ...
    CasidaTDDFT = NotImplemented
    def TDDFT(self, equilibrium_solvation: bool = False): ...
    def MP2(self): ...
    def CISD(self): ...
    def CCSD(self): ...
    def CASCI(self, ncas, nelecas, **kwargs): ...
    def CASSCF(self, ncas, nelecas, **kwargs): ...

class CASSCFWithSolvent(_Solvation):
    with_solvent: Incomplete
    def __init__(self, mc: CASSCF, solvent: Union[ddCOSMO, PCM]) -> None: ...
    def undo_solvent(self): ...
    def dump_flags(self, verbose=None): ...
    def reset(self, mol=None): ...
    def update_casdm(self, mo, u, fcivec, e_ci, eris, envs={}): ...
    def get_hcore(self, mol=None): ...
    def casci(self, mo_coeff, ci0=None, eris=None, verbose=None, envs=None): ...
    def nuc_grad_method(self): ...
    Gradients = nuc_grad_method
    def to_gpu(self): ...

class CASCIWithSolvent(_Solvation):
    with_solvent: Incomplete
    def __init__(self, mc: CASCI, solvent: Union[PCM, ddCOSMO]) -> None: ...
    def undo_solvent(self): ...
    def dump_flags(self, verbose=None): ...
    def reset(self, mol=None): ...
    def get_hcore(self, mol=None): ...
    converged: bool
    def kernel(self, mo_coeff=None, ci0=None, verbose=None): ...
    def nuc_grad_method(self): ...
    Gradients = nuc_grad_method
    def to_gpu(self): ...

class PostSCFWithSolvent(_Solvation):
    def __init__(self, method, scf_with_solvent) -> None: ...
    def undo_solvent(self): ...
    @property
    def with_solvent(self): ...
    def dump_flags(self, verbose=None): ...
    def reset(self, mol=None): ...
    def kernel(self, *args, **kwargs): ...
    def nuc_grad_method(self): ...
    Gradients = nuc_grad_method
    def to_gpu(self): ...

class TDSCFWithSolvent(_Solvation):
    with_solvent: Incomplete
    def __init__(self, method: TDBase, solvent_obj: Union[ddPCM, PCM, ddCOSMO]) -> None: ...
    def undo_solvent(self): ...
    @property
    def equilibrium_solvation(self): ...
    @equilibrium_solvation.setter
    def equilibrium_solvation(self, val) -> None: ...
    def dump_flags(self, verbose=None): ...
    def reset(self, mol=None): ...
    def gen_response(self, *args, **kwargs): ...
    def get_ab(self, mf=None) -> None: ...
    def nuc_grad_method(self): ...
    Gradients = nuc_grad_method
    def to_gpu(self): ...
