from pyscf import __version__ as __version__
from numpy import float64, int64, ndarray
from typing import Any, Dict, List, Union

def get_sas_volume(surface: Dict[str, Union[int, List[List[Union[int, int64]]], ndarray]], step: float = 0.2) -> float64: ...
def get_pcm_parameters(mf, step: float = 0.2): ...
def write_cosmo_file(fout, mf, step: float = 0.2, volume=None) -> None: ...
