from pyscf import __version__ as __version__

def get_sas_volume(surface, step: float = 0.2): ...
def get_pcm_parameters(mf, step: float = 0.2): ...
def write_cosmo_file(fout, mf, step: float = 0.2, volume=None) -> None: ...
