from _typeshed import Incomplete
from pyscf import cc as cc, ci as ci, df as df, gto as gto, lib as lib, mcscf as mcscf, mp as mp, scf as scf, tdscf as tdscf
from pyscf.data import radii as radii
from pyscf.dft import gen_grid as gen_grid, numint as numint
from pyscf.lib import logger as logger
from pyscf.symm import sph as sph
from numpy import float64, ndarray
from pyscf.gto.mole import Mole
from pyscf.lib.logger import Logger
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.solvent.ddpcm import ddPCM
from typing import Any, Callable, Dict, List, Optional, Tuple, Union

def ddcosmo_for_scf(mf, solvent_obj=None, dm=None): ...
def ddcosmo_for_casscf(mc, solvent_obj=None, dm=None): ...
def ddcosmo_for_casci(mc, solvent_obj=None, dm=None): ...
def ddcosmo_for_post_scf(method, solvent_obj=None, dm=None): ...

ddcosmo_for_tdscf: Incomplete

def gen_ddcosmo_solver(pcmobj: "ddCOSMO", verbose: None=None) -> Callable: ...
def energy(pcmobj: "ddCOSMO", dm: Union[ndarray, NPArrayWithTag]) -> float64: ...
def get_atomic_radii(pcmobj: Union[ddPCM, ddCOSMO]) -> ndarray: ...
def regularize_xt(t: ndarray, eta: float) -> ndarray: ...
def make_grids_one_sphere(lebedev_order: int) -> Tuple[ndarray, ndarray]: ...
def make_L(pcmobj: Union[ddPCM, ddCOSMO], r_vdw: ndarray, ylm_1sph: ndarray, fi: ndarray) -> ndarray: ...
def make_fi(pcmobj: Union[ddPCM, ddCOSMO], r_vdw: ndarray) -> ndarray: ...
def make_phi(pcmobj: Union[ddPCM, ddCOSMO], dm: Union[ndarray, Tuple[ndarray, ndarray], NPArrayWithTag], r_vdw: ndarray, ui: ndarray, ylm_1sph: ndarray, with_nuc: bool = True) -> ndarray: ...
def make_psi_vmat(pcmobj: Union[ddPCM, ddCOSMO], dm: Union[ndarray, Tuple[ndarray, ndarray], NPArrayWithTag], r_vdw: ndarray, ui: ndarray, ylm_1sph: ndarray, cached_pol: Dict[str, Tuple[List[ndarray], ndarray]], Xvec: ndarray, L: ndarray, with_nuc: bool = True) -> Tuple[ndarray, ndarray, ndarray]: ...
def cache_fake_multipoles(grids: "Grids", r_vdw: ndarray, lmax: int) -> Dict[str, Tuple[List[ndarray], ndarray]]: ...
def atoms_with_vdw_overlap(atm_id: int, atom_coords: ndarray, r_vdw: ndarray) -> ndarray: ...

class ddCOSMO(lib.StreamObject):
    mol: Incomplete
    stdout: Incomplete
    verbose: Incomplete
    max_memory: Incomplete
    radii_table: Incomplete
    atom_radii: Incomplete
    lebedev_order: int
    lmax: int
    eta: float
    eps: float
    grids: Incomplete
    max_cycle: int
    conv_tol: float
    state_id: int
    frozen: bool
    equilibrium_solvation: bool
    e: Incomplete
    v: Incomplete
    def __init__(self, mol: Mole) -> None: ...
    @property
    def dm(self): ...
    @dm.setter
    def dm(self, dm) -> None: ...
    @property
    def epcm(self): ...
    e_solvent: Incomplete
    @epcm.setter
    def epcm(self, val) -> None: ...
    @property
    def vpcm(self): ...
    v_solvent: Incomplete
    @vpcm.setter
    def vpcm(self, val) -> None: ...
    def __setattr__(self, key: str, val: Any) -> None: ...
    def dump_flags(self, verbose: Optional[Logger]=None) -> "ddCOSMO": ...
    def build(self) -> None: ...
    def kernel(self, dm: Union[ndarray, NPArrayWithTag]) -> Tuple[float64, ndarray]: ...
    def reset(self, mol: Optional[Mole]=None) -> Union[ddPCM, ddCOSMO]: ...
    energy = energy
    gen_solver = gen_ddcosmo_solver
    as_solver = gen_ddcosmo_solver
    get_atomic_radii = get_atomic_radii
    def regularize_xt(self, t: ndarray, eta: float, scale: int = 1) -> ndarray: ...
    def nuc_grad_method(self, grad_method) -> None: ...
    def grad(self, dm: Union[ndarray, NPArrayWithTag]) -> ndarray: ...
    def hess(self, dm) -> None: ...
    to_gpu = lib.to_gpu
DDCOSMO = ddCOSMO

class Grids(gen_grid.Grids):
    alignment: int
    def build(self, mol: None=None, *args, **kwargs) -> "Grids": ...
