from _typeshed import Incomplete
from pyscf import cc as cc, ci as ci, gto as gto, lib as lib, mcscf as mcscf, mp as mp, scf as scf, tdscf as tdscf
from pyscf.data import radii as radii
from pyscf.dft import gen_grid as gen_grid
from pyscf.lib import logger as logger
from pyscf.solvent import ddcosmo as ddcosmo
from pyscf.symm import sph as sph
from numpy import float64, ndarray
from pyscf.gto.mole import Mole
from pyscf.lib.numpy_helper import NPArrayWithTag
from typing import Tuple, Union

def ddpcm_for_scf(mf, solvent_obj=None, dm=None): ...
def ddpcm_for_casscf(mc, solvent_obj=None, dm=None): ...
def ddpcm_for_casci(mc, solvent_obj=None, dm=None): ...
def ddpcm_for_post_scf(method, solvent_obj=None, dm=None): ...

ddpcm_for_tdscf: Incomplete

def gen_ddpcm_solver(pcmobj, verbose=None): ...
def energy(pcmobj, dm): ...
def regularize_xt(t: ndarray, eta: float) -> ndarray: ...
def make_A(pcmobj: "ddPCM", r_vdw: ndarray, ylm_1sph: ndarray, ui: ndarray) -> ndarray: ...

class ddPCM(ddcosmo.DDCOSMO):
    method: str
    def __init__(self, mol: Mole) -> None: ...
    def dump_flags(self, verbose: None=None) -> "ddPCM": ...
    def build(self) -> None: ...
    gen_solver = gen_ddpcm_solver
    as_solver = gen_ddpcm_solver
    def regularize_xt(self, t: ndarray, eta: float, scale: int = 1) -> ndarray: ...
    def nuc_grad_method(self, grad_method) -> None: ...
DDPCM = ddPCM
