from _typeshed import Incomplete
from pyscf import cc as cc, ci as ci, df as df, gto as gto, lib as lib, mcscf as mcscf, mp as mp, scf as scf, tdscf as tdscf
from pyscf.data import radii as radii
from pyscf.dft import gen_grid as gen_grid
from pyscf.lib import logger as logger
from pyscf.solvent import ddcosmo as ddcosmo

def pcm_for_scf(mf, solvent_obj=None, dm=None): ...
def pcm_for_casscf(mc, solvent_obj=None, dm=None): ...
def pcm_for_casci(mc, solvent_obj=None, dm=None): ...
def pcm_for_post_scf(method, solvent_obj=None, dm=None): ...

pcm_for_tdscf: Incomplete
XI: Incomplete
modified_Bondi: Incomplete
PI: Incomplete

def switch_h(x): ...
def gen_surface(mol, ng: int = 302, rad=..., surface_discretization_method: str = 'SWIG'): ...
def get_F_A(surface): ...
def get_D_S(surface, with_S: bool = True, with_D: bool = False): ...

class PCM(lib.StreamObject):
    kernel: Incomplete
    mol: Incomplete
    stdout: Incomplete
    verbose: Incomplete
    max_memory: Incomplete
    method: str
    vdw_scale: float
    r_probe: float
    radii_table: Incomplete
    lebedev_order: int
    eps: float
    surface_discretization_method: str
    max_cycle: int
    conv_tol: float
    state_id: int
    frozen: bool
    equilibrium_solvation: bool
    surface: Incomplete
    v_grids_n: Incomplete
    e: Incomplete
    v: Incomplete
    def __init__(self, mol) -> None: ...
    def dump_flags(self, verbose=None): ...
    def to_gpu(self): ...
    def reset(self, mol=None): ...
    def build(self, ng=None) -> None: ...
    def nuc_grad_method(self, grad_method) -> None: ...
    def grad(self, dm): ...
    def Hessian(self, hess_method) -> None: ...
    def hess(self, dm): ...
