from . import mpi_pool as mpi_pool
from .mpi_pool import MPIPool as MPIPool
from _typeshed import Incomplete
from collections.abc import Generator

pool: Incomplete
comm: Incomplete
rank: Incomplete

def static_partition(tasks): ...
def work_balanced_partition(tasks, costs=None): ...

INQUIRY: int
TASK: int

def work_share_partition(tasks, interval: float = 0.02, loadmin: int = 1) -> Generator[Incomplete]: ...
def work_stealing_partition(tasks, interval: float = 0.0001) -> Generator[Incomplete, None, Incomplete]: ...
def bcast(buf, root: int = 0): ...
def reduce(sendbuf, op=..., root: int = 0): ...
def allreduce(sendbuf, op=...): ...
def gather(sendbuf, root: int = 0): ...
def allgather(sendbuf): ...
def alltoall(sendbuf, split_recvbuf: bool = False): ...
def sendrecv(sendbuf, source: int = 0, dest: int = 0): ...
def register_for(obj): ...
def del_registry(reg_keys): ...
