from _typeshed import Incomplete
from time import sleep as sleep

def enum(**enums): ...

tags: Incomplete

class load_balancer:
    rank: Incomplete
    size: Incomplete
    COMM: Incomplete
    BLKSIZE: Incomplete
    curr_block: Incomplete
    def __init__(self, BLKSIZE) -> None: ...
    nindices: Incomplete
    outblocks: Incomplete
    def set_ranges(self, inindices, BLKSIZE=None) -> None: ...
    def master(self) -> None: ...
    working: bool
    def slave_set(self): ...
    def get_blocks_from_data(self, data): ...
    def slave_finished(self) -> None: ...
