import types
from _typeshed import Incomplete

__all__ = ['MPIPool', 'MPIPoolException']

class MPIPool:
    comm: Incomplete
    rank: Incomplete
    size: Incomplete
    debug: Incomplete
    function: Incomplete
    def __init__(self, comm=None, debug: bool = False) -> None: ...
    def is_master(self): ...
    def wait(self) -> None: ...
    def apply(self, function, master_args, worker_args): ...
    def close(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self) -> None: ...

class _close_pool_message: ...

class _function_wrapper:
    func_code: Incomplete
    def __init__(self, function) -> None: ...

class MPIPoolException(Exception):
    traceback: Incomplete
    def __init__(self, tb) -> None: ...
