from .mpi_blksize import get_max_blocksize_from_mem as get_max_blocksize_from_mem
from pyscf.lib.numpy_helper import cartesian_prod as cartesian_prod

MEM_SIZE: float

def generate_task_list(chunk_size, array_size): ...
def generate_max_task_list(array_size, blk_mem_size: float = 16.0, memory=..., priority_list=None): ...
def safeNormDiff(in_array1, in_array2): ...
def safeAllreduceInPlace(comm, in_array) -> None: ...
def safeBcastInPlace(comm, in_array, root: int = 0) -> None: ...
