from _typeshed import Incomplete
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.lib import logger as logger
from pyscf.scf import addons as addons, chkfile as chkfile, dhf as dhf, ghf_symm as ghf_symm, hf as hf, hf_symm as hf_symm, rohf as rohf, uhf as uhf, uhf_symm as uhf_symm
from pyscf.soscf import ciah as ciah

WITH_EX_EY_DEGENERACY: Incomplete

def expmat(a): ...
def gen_g_hop_rhf(mf, mo_coeff, mo_occ, fock_ao=None, h1e=None, with_symmetry: bool = True): ...
def gen_g_hop_rohf(mf, mo_coeff, mo_occ, fock_ao=None, h1e=None, with_symmetry: bool = True): ...
def gen_g_hop_uhf(mf, mo_coeff, mo_occ, fock_ao=None, h1e=None, with_symmetry: bool = True): ...
def gen_g_hop_ghf(mf, mo_coeff, mo_occ, fock_ao=None, h1e=None, with_symmetry: bool = True): ...
def gen_g_hop_dhf(mf, mo_coeff, mo_occ, fock_ao=None, h1e=None, with_symmetry: bool = False): ...
def project_mol(mol, dual_basis={}): ...
def kernel(mf, mo_coeff=None, mo_occ=None, dm=None, conv_tol: float = 1e-10, conv_tol_grad=None, max_cycle: int = 50, dump_chk: bool = True, callback=None, verbose=...): ...

class _CIAH_SOSCF:
    __name_mixin__: str
    max_cycle_inner: Incomplete
    max_stepsize: Incomplete
    canonicalization: Incomplete
    ah_start_tol: Incomplete
    ah_start_cycle: Incomplete
    ah_level_shift: Incomplete
    ah_conv_tol: Incomplete
    ah_lindep: Incomplete
    ah_max_cycle: Incomplete
    ah_grad_trust_region: Incomplete
    kf_interval: Incomplete
    kf_trust_region: Incomplete
    def __init__(self, mf) -> None: ...
    def undo_soscf(self): ...
    undo_newton = undo_soscf
    def dump_flags(self, verbose=None): ...
    def build(self, mol=None): ...
    mol: Incomplete
    def reset(self, mol=None): ...
    def kernel(self, mo_coeff=None, mo_occ=None, dm0=None): ...
    def from_dm(self, dm): ...
    gen_g_hop = gen_g_hop_rhf
    def update_rotate_matrix(self, dx, mo_occ, u0: int = 1, mo_coeff=None): ...
    def rotate_mo(self, mo_coeff, u, log=None): ...
    def density_fit(self, auxbasis=None, with_df=None, only_dfj: bool = False): ...
    def approx_hessian(self, auxbasis=None, with_df=None, only_dfj: bool = False): ...
    def to_gpu(self): ...

class _SecondOrderROHF(_CIAH_SOSCF):
    gen_g_hop = gen_g_hop_rohf

class _SecondOrderUHF(_CIAH_SOSCF):
    gen_g_hop = gen_g_hop_uhf
    def update_rotate_matrix(self, dx, mo_occ, u0: int = 1, mo_coeff=None): ...
    def rotate_mo(self, mo_coeff, u, log=None): ...
    def spin_square(self, mo_coeff=None, s=None): ...
    def kernel(self, mo_coeff=None, mo_occ=None, dm0=None): ...

class _SecondOrderGHF(_CIAH_SOSCF):
    gen_g_hop = gen_g_hop_ghf
    def update_rotate_matrix(self, dx, mo_occ, u0: int = 1, mo_coeff=None): ...
    def rotate_mo(self, mo_coeff, u, log=None): ...

class _SecondOrderRDHF(_CIAH_SOSCF):
    gen_g_hop = gen_g_hop_dhf
    def update_rotate_matrix(self, dx, mo_occ, u0: int = 1, mo_coeff=None): ...
    def rotate_mo(self, mo_coeff, u, log=None): ...

class _SecondOrderDHF(_CIAH_SOSCF):
    gen_g_hop = gen_g_hop_dhf
    def update_rotate_matrix(self, dx, mo_occ, u0: int = 1, mo_coeff=None): ...
    def rotate_mo(self, mo_coeff, u, log=None): ...

class _SecondOrderRHF(_CIAH_SOSCF):
    gen_g_hop = gen_g_hop_rhf

def newton(mf): ...
def remove_soscf(mf): ...

SVD_TOL: Incomplete
