import contextlib
from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc import tools as tools
from pyscf.pbc.df import aft_ao2mo as aft_ao2mo, aft_jk as aft_jk, ft_ao as ft_ao
from pyscf.pbc.df.incore import Int3cBuilder as Int3cBuilder
from pyscf.pbc.gto import error_for_ke_cutoff as error_for_ke_cutoff, pseudo as pseudo
from pyscf.pbc.gto.pseudo import pp_int as pp_int
from pyscf.pbc.lib.kpts import KPoints as KPoints
from pyscf.pbc.lib.kpts_helper import gamma_point as gamma_point, is_zero as is_zero
from pyscf.pbc.tools import k2gamma as k2gamma

KE_SCALING: Incomplete
RCUT_THRESHOLD: Incomplete

def estimate_eta_min(cell, cutoff=None): ...
estimate_eta = estimate_eta_min

def estimate_eta_for_ke_cutoff(cell, ke_cutoff, precision=None): ...
def estimate_ke_cutoff_for_eta(cell, eta, precision=None): ...
def estimate_omega_min(cell, cutoff=None): ...
estimate_omega = estimate_omega_min

def estimate_ke_cutoff_for_omega(cell, omega, precision=None): ...
def estimate_omega_for_ke_cutoff(cell, ke_cutoff, precision=None): ...
def get_pp(mydf, kpts=None): ...
def get_nuc(mydf, kpts=None): ...
def weighted_coulG(mydf, kpt=..., exx: bool = False, mesh=None, omega=None): ...
def estimate_ke_cutoff(cell, precision=None): ...

class _IntPPBuilder(Int3cBuilder):
    def __init__(self, cell, kpts=...) -> None: ...
    def get_ovlp_mask(self, cutoff, supmol=None, cintopt=None): ...
    def build(self) -> None: ...
    bvk_kmesh: Incomplete
    rs_cell: Incomplete
    supmol: Incomplete
    def get_pp_loc_part2(self): ...

class AFTDFMixin:
    weighted_coulG = weighted_coulG
    def pw_loop(self, mesh=None, kpti_kptj=None, q=None, shls_slice=None, max_memory: int = 2000, aosym: str = 's1', blksize=None, intor: str = 'GTO_ft_ovlp', comp: int = 1, bvk_kmesh=None) -> Generator[Incomplete]: ...
    def ft_loop(self, mesh=None, q=..., kpts=None, shls_slice=None, max_memory: int = 4000, aosym: str = 's1', intor: str = 'GTO_ft_ovlp', comp: int = 1, bvk_kmesh=None, return_complex: bool = True) -> Generator[Incomplete]: ...
    @contextlib.contextmanager
    def range_coulomb(self, omega) -> Generator[Incomplete]: ...

class AFTDF(lib.StreamObject, AFTDFMixin):
    blockdim: Incomplete
    cell: Incomplete
    stdout: Incomplete
    verbose: Incomplete
    max_memory: Incomplete
    mesh: Incomplete
    time_reversal_symmetry: bool
    def __init__(self, cell, kpts=None) -> None: ...
    @property
    def kpts(self): ...
    @kpts.setter
    def kpts(self, val) -> None: ...
    def dump_flags(self, verbose=None): ...
    def reset(self, cell=None): ...
    def check_sanity(self): ...
    def build(self): ...
    get_nuc = get_nuc
    get_pp = get_pp
    def get_jk(self, dm, hermi: int = 1, kpts=None, kpts_band=None, with_j: bool = True, with_k: bool = True, omega=None, exxdiv=None): ...
    get_eri = aft_ao2mo.get_eri
    get_ao_eri = aft_ao2mo.get_eri
    ao2mo = aft_ao2mo.general
    get_mo_eri = aft_ao2mo.general
    ao2mo_7d = aft_ao2mo.ao2mo_7d
    get_ao_pairs_G = aft_ao2mo.get_ao_pairs_G
    get_ao_pairs = aft_ao2mo.get_ao_pairs_G
    get_mo_pairs_G = aft_ao2mo.get_mo_pairs_G
    get_mo_pairs = aft_ao2mo.get_mo_pairs_G
    def update_mf(self, mf): ...
    def prange(self, start, stop, step): ...
    def loop(self, blksize=None) -> Generator[Incomplete]: ...
    def get_naoaux(self): ...
