import contextlib
from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc import tools as tools
from pyscf.pbc.df import aft_ao2mo as aft_ao2mo, aft_jk as aft_jk, ft_ao as ft_ao
from pyscf.pbc.df.incore import Int3cBuilder as Int3cBuilder
from pyscf.pbc.gto import error_for_ke_cutoff as error_for_ke_cutoff, pseudo as pseudo
from pyscf.pbc.gto.pseudo import pp_int as pp_int
from pyscf.pbc.lib.kpts import KPoints as KPoints
from pyscf.pbc.lib.kpts_helper import gamma_point as gamma_point, is_zero as is_zero
from pyscf.pbc.tools import k2gamma as k2gamma
from numpy import float64, int32, ndarray
from pyscf.lib.misc import StreamObject
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.df.fft import FFTDF
from pyscf.pbc.df.ft_ao import _RangeSeparatedCell
from pyscf.pbc.gto.cell import Cell
from typing import Any, Dict, Iterator, List, Optional, Tuple, Union

KE_SCALING: Incomplete
RCUT_THRESHOLD: Incomplete

def estimate_eta_min(cell, cutoff=None): ...
estimate_eta = estimate_eta_min

def estimate_eta_for_ke_cutoff(cell, ke_cutoff, precision=None): ...
def estimate_ke_cutoff_for_eta(cell, eta, precision=None): ...
def estimate_omega_min(cell, cutoff=None): ...
estimate_omega = estimate_omega_min

def estimate_ke_cutoff_for_omega(cell: Cell, omega: float, precision: None=None) -> float64: ...
def estimate_omega_for_ke_cutoff(cell, ke_cutoff, precision=None): ...
def get_pp(mydf: "AFTDF", kpts: Optional[ndarray]=None) -> ndarray: ...
def get_nuc(mydf: "AFTDF", kpts: Optional[ndarray]=None) -> ndarray: ...
def weighted_coulG(mydf: StreamObject, kpt: ndarray=..., exx: Optional[Union[bool, str]] = False, mesh: Optional[Union[ndarray, List[int]]]=None, omega: Optional[Union[float, float64]]=None) -> ndarray: ...
def estimate_ke_cutoff(cell: Cell, precision: Optional[float]=None) -> float64: ...

class _IntPPBuilder(Int3cBuilder):
    def __init__(self, cell: Cell, kpts: ndarray=...) -> None: ...
    def get_ovlp_mask(self, cutoff, supmol=None, cintopt=None): ...
    def build(self) -> None: ...
    bvk_kmesh: Incomplete
    rs_cell: Incomplete
    supmol: Incomplete
    def get_pp_loc_part2(self) -> Union[ndarray, List[ndarray]]: ...

class AFTDFMixin:
    weighted_coulG = weighted_coulG
    def pw_loop(self, mesh: Optional[Union[ndarray, List[int]]]=None, kpti_kptj: Optional[ndarray]=None, q: Optional[ndarray]=None, shls_slice: None=None, max_memory: Union[float, int] = 2000, aosym: str = 's1', blksize: None=None, intor: str = 'GTO_ft_ovlp', comp: int = 1, bvk_kmesh: None=None) -> Iterator[Tuple[ndarray, ndarray, int, int]]: ...
    def ft_loop(self, mesh: Optional[Union[ndarray, List[int]]]=None, q: ndarray=..., kpts: Optional[ndarray]=None, shls_slice: None=None, max_memory: float = 4000, aosym: str = 's1', intor: str = 'GTO_ft_ovlp', comp: int = 1, bvk_kmesh: None=None, return_complex: bool = True) -> Iterator[Tuple[ndarray, int, int]]: ...
    @contextlib.contextmanager
    def range_coulomb(self, omega: float) -> Iterator[Union[AFTDF, FFTDF]]: ...

class AFTDF(lib.StreamObject, AFTDFMixin):
    blockdim: Incomplete
    cell: Incomplete
    stdout: Incomplete
    verbose: Incomplete
    max_memory: Incomplete
    mesh: Incomplete
    time_reversal_symmetry: bool
    def __init__(self, cell: Cell, kpts: Optional[Union[List[List[float]], List[ndarray], ndarray]]=None) -> None: ...
    @property
    def kpts(self): ...
    @kpts.setter
    def kpts(self, val) -> None: ...
    def dump_flags(self, verbose=None): ...
    def reset(self, cell: None=None) -> "AFTDF": ...
    def check_sanity(self) -> "AFTDF": ...
    def build(self): ...
    get_nuc = get_nuc
    get_pp = get_pp
    def get_jk(self, dm: Union[ndarray, List[NPArrayWithTag], NPArrayWithTag], hermi: int = 1, kpts: Optional[Union[ndarray, List[List[float]], List[ndarray]]]=None, kpts_band: Optional[ndarray]=None, with_j: bool = True, with_k: bool = True, omega: Optional[float]=None, exxdiv: Optional[str]=None) -> Union[Tuple[ndarray, ndarray], Tuple[None, ndarray]]: ...
    get_eri = aft_ao2mo.get_eri
    get_ao_eri = aft_ao2mo.get_eri
    ao2mo = aft_ao2mo.general
    get_mo_eri = aft_ao2mo.general
    ao2mo_7d = aft_ao2mo.ao2mo_7d
    get_ao_pairs_G = aft_ao2mo.get_ao_pairs_G
    get_ao_pairs = aft_ao2mo.get_ao_pairs_G
    get_mo_pairs_G = aft_ao2mo.get_mo_pairs_G
    get_mo_pairs = aft_ao2mo.get_mo_pairs_G
    def update_mf(self, mf): ...
    def prange(self, start: int, stop: int, step: int) -> Iterator[Any]: ...
    def loop(self, blksize=None) -> Generator[Incomplete]: ...
    def get_naoaux(self): ...
