from pyscf import __config__ as __config__, ao2mo as ao2mo, lib as lib
from pyscf.ao2mo.incore import iden_coeffs as iden_coeffs
from pyscf.pbc.df.df_ao2mo import warn_pbc2d_eri as warn_pbc2d_eri
from pyscf.pbc.df.df_jk import zdotNC as zdotNC
from pyscf.pbc.lib import kpts_helper as kpts_helper
from pyscf.pbc.lib.kpts_helper import gamma_point as gamma_point, is_zero as is_zero, unique as unique
from numpy import ndarray
from pyscf.pbc.df.aft import AFTDF
from pyscf.pbc.df.mdf import MDF
from typing import Optional, Tuple, Union

def get_eri(mydf: Union[MDF, AFTDF], kpts: Optional[Union[ndarray, Tuple[ndarray, ndarray, ndarray, ndarray]]]=None, compact: bool=...) -> ndarray: ...
def general(mydf: Union[MDF, AFTDF], mo_coeffs: Union[ndarray, Tuple[ndarray, ndarray, ndarray, ndarray]], kpts: Optional[Union[ndarray, Tuple[ndarray, ndarray, ndarray, ndarray]]]=None, compact: bool=...) -> ndarray: ...
def get_ao_pairs_G(mydf, kpts=..., q=None, shls_slice=None, compact=...): ...
def get_mo_pairs_G(mydf, mo_coeffs, kpts=..., q=None, compact=...): ...
def ao2mo_7d(mydf: AFTDF, mo_coeff_kpts: ndarray, kpts: Optional[ndarray]=None, factor: int = 1, out: None=None) -> ndarray: ...
