import contextlib
import types
from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.df import addons as addons
from pyscf.lib import logger as logger
from pyscf.pbc import tools as tools
from pyscf.pbc.df import aft as aft, df_ao2mo as df_ao2mo, df_jk as df_jk, ft_ao as ft_ao, incore as incore, outcore as outcore
from pyscf.pbc.df.aft import estimate_eta as estimate_eta
from pyscf.pbc.df.df_jk import zdotCN as zdotCN
from pyscf.pbc.df.gdf_builder import libpbc as libpbc
from pyscf.pbc.df.rsdf_builder import LINEAR_DEP_THR as LINEAR_DEP_THR
from pyscf.pbc.lib.kpts import KPoints, KPoints as KPoints
from pyscf.pbc.lib.kpts_helper import KPT_DIFF_TOL as KPT_DIFF_TOL, gamma_point as gamma_point, is_zero as is_zero, member as member, unique as unique
from h5py._hl.dataset import Dataset
from h5py._hl.files import File
from h5py._hl.group import Group
from numpy import int64, ndarray
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.df.mdf import MDF
from pyscf.pbc.gto.cell import Cell
from typing import Any, Callable, Iterator, List, Optional, Tuple, Union

def make_modrho_basis(cell: Cell, auxbasis: Optional[Any]=None, drop_eta: Optional[float]=None) -> Cell: ...
make_auxcell = make_modrho_basis

class GDF(lib.StreamObject, aft.AFTDFMixin):
    blockdim: Incomplete
    force_dm_kbuild: bool
    cell: Incomplete
    stdout: Incomplete
    verbose: Incomplete
    max_memory: Incomplete
    kpts_band: Incomplete
    eta: Incomplete
    mesh: Incomplete
    exp_to_discard: Incomplete
    exxdiv: Incomplete
    auxcell: Incomplete
    linear_dep_threshold: Incomplete
    def __init__(self, cell: Cell, kpts: Optional[Union[ndarray, List[ndarray], KPoints, List[List[float]]]]=None) -> None: ...
    @property
    def auxbasis(self): ...
    @auxbasis.setter
    def auxbasis(self, x) -> None: ...
    def reset(self, cell: None=None) -> "GDF": ...
    @property
    def gs(self): ...
    @gs.setter
    def gs(self, x) -> None: ...
    @property
    def kpts(self): ...
    @kpts.setter
    def kpts(self, val) -> None: ...
    def dump_flags(self, verbose: None=None) -> Union[GDF, MDF]: ...
    def build(self, j_only: Optional[bool]=None, with_j3c: bool = True, kpts_band: Optional[ndarray]=None) -> Union[GDF, MDF]: ...
    def cderi_array(self, label=None): ...
    def has_kpts(self, kpts: Optional[ndarray]) -> bool: ...
    def sr_loop(self, kpti_kptj: Union[ndarray, Tuple[ndarray, ndarray], List[ndarray]]=..., max_memory: Union[float, int] = 2000, compact: bool = True, blksize: Optional[int]=None, aux_slice: Optional[Tuple[int, int]]=None) -> Iterator[Tuple[ndarray, ndarray, int]]: ...
    def get_pp(self, kpts: Optional[Union[ndarray, List[float]]]=None) -> ndarray: ...
    def get_nuc(self, kpts: Optional[ndarray]=None) -> ndarray: ...
    def get_jk(self, dm: Union[ndarray, NPArrayWithTag], hermi: int = 1, kpts: Optional[Union[ndarray, List[List[float]]]]=None, kpts_band: Optional[ndarray]=None, with_j: bool = True, with_k: bool = True, omega: Optional[float]=None, exxdiv: Optional[str]=None) -> Union[Tuple[ndarray, ndarray], Tuple[None, ndarray], Tuple[ndarray, None]]: ...
    get_eri = df_ao2mo.get_eri
    get_ao_eri = df_ao2mo.get_eri
    ao2mo = df_ao2mo.general
    get_mo_eri = df_ao2mo.general
    ao2mo_7d = df_ao2mo.ao2mo_7d
    def update_mp(self): ...
    def update_cc(self) -> None: ...
    def update(self) -> None: ...
    def prange(self, start: int, stop: int, step: int) -> Iterator[Any]: ...
    @contextlib.contextmanager
    def range_coulomb(self, omega: float) -> Iterator[GDF]: ...
    def loop(self, blksize: None=None) -> Iterator[ndarray]: ...
    def get_naoaux(self) -> int: ...
    to_gpu = lib.to_gpu
DF = GDF

class CDERIArray:
    data_group: Incomplete
    nkpts: Incomplete
    aosym: Incomplete
    j3c: Incomplete
    kpts: Incomplete
    naux: int
    nao: Incomplete
    def __init__(self, data_group: str, label: str = 'j3c') -> None: ...
    def __del__(self) -> None: ...
    def __enter__(self) -> "CDERIArray": ...
    def __exit__(self, type: None, value: None, traceback: None) -> None: ...
    def __getitem__(self, slices: Union[slice, Tuple[int, int], Tuple[int64, int64]]) -> ndarray: ...
    def load(self, kpti, kptj): ...
    def __array__(self): ...

class _load3c:
    cderi: Incomplete
    label: Incomplete
    kptij_label: Incomplete
    kpti_kptj: Incomplete
    ignore_key_error: Incomplete
    feri: Incomplete
    def __init__(self, cderi: str, label: str, kpti_kptj: Optional[Union[ndarray, Tuple[ndarray, ndarray], List[ndarray]]]=None, kptij_label: str = 'j3c-kptij', ignore_key_error: bool = False) -> None: ...
    def __enter__(self) -> Union[_load_and_unpack, _KPair3CLoader, Callable]: ...
    def __exit__(self, type: None, value: None, traceback: None) -> None: ...
    @property
    def kptij_lst(self) -> ndarray: ...
    @property
    def aosym(self) -> str: ...
    @property
    def data_version(self): ...
    def getitem(self, kpti: ndarray, kptj: ndarray) -> Union[_load_and_unpack, _KPair3CLoader]: ...

class _load_and_unpack:
    dat: Incomplete
    hermi: Incomplete
    def __init__(self, dat: Group, hermi: bool) -> None: ...
    def __getitem__(self, s: slice) -> ndarray: ...
    def __array__(self): ...
    @property
    def shape(self) -> Tuple[int, int]: ...

class _KPair3CLoader:
    dat: Incomplete
    kikj: Incomplete
    kjki: Incomplete
    nkpts: Incomplete
    nsegs: Incomplete
    aosym: Incomplete
    def __init__(self, dat: Group, ki: int64, kj: int64, nkpts: int, aosym: str) -> None: ...
    def __getitem__(self, s: Union[Tuple[()], slice]) -> ndarray: ...
    def __array__(self) -> ndarray: ...
    @property
    def shape(self) -> Tuple[int, int]: ...
