from pyscf import __config__ as __config__, ao2mo as ao2mo, lib as lib
from pyscf.ao2mo.incore import iden_coeffs as iden_coeffs
from pyscf.pbc.df.df_jk import zdotNC as zdotNC, zdotNN as zdotNN
from pyscf.pbc.lib import kpts_helper as kpts_helper
from pyscf.pbc.lib.kpts_helper import gamma_point as gamma_point, is_zero as is_zero, unique as unique

def get_eri(mydf, kpts=None, compact=...): ...
def general(mydf, mo_coeffs, kpts=None, compact=...): ...
def ao2mo_7d(mydf, mo_coeff_kpts, kpts=None, factor: int = 1, out=None): ...

class PBC2DIntegralsWarning(RuntimeWarning): ...

def warn_pbc2d_eri(mydf) -> None: ...
