from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger, zdotCN as zdotCN, zdotNC as zdotNC, zdotNN as zdotNN
from pyscf.pbc import tools as tools
from pyscf.pbc.lib.kpts_helper import gamma_point as gamma_point, get_kconserv_ria as get_kconserv_ria, is_zero as is_zero, member as member

DM2MO_PREC: Incomplete

def density_fit(mf, auxbasis=None, mesh=None, with_df=None): ...
def get_j_kpts(mydf, dm_kpts, hermi: int = 1, kpts=..., kpts_band=None): ...
def get_j_kpts_kshift(mydf, dm_kpts, kshift, hermi: int = 0, kpts=..., kpts_band=None): ...
def get_k_kpts(mydf, dm_kpts, hermi: int = 1, kpts=..., kpts_band=None, exxdiv=None): ...
def get_k_kpts_kshift(mydf, dm_kpts, kshift, hermi: int = 0, kpts=..., kpts_band=None, exxdiv=None): ...
def get_jk(mydf, dm, hermi: int = 1, kpt=..., kpts_band=None, with_j: bool = True, with_k: bool = True, exxdiv=None): ...
