from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc import tools as tools
from pyscf.pbc.df import aft as aft, fft_ao2mo as fft_ao2mo, fft_jk as fft_jk, ft_ao as ft_ao
from pyscf.pbc.gto import error_for_ke_cutoff as error_for_ke_cutoff, estimate_ke_cutoff as estimate_ke_cutoff, pseudo as pseudo
from pyscf.pbc.lib.kpts import KPoints, KPoints as KPoints
from pyscf.pbc.lib.kpts_helper import is_zero as is_zero
from numpy import ndarray
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.dft.gen_grid import UniformGrids
from pyscf.pbc.gto.cell import Cell
from typing import Iterator, List, Optional, Tuple, Union

KE_SCALING: Incomplete

def get_nuc(mydf: "FFTDF", kpts: Optional[Union[List[ndarray], ndarray]]=None) -> ndarray: ...
def get_pp(mydf: "FFTDF", kpts: Optional[ndarray]=None) -> ndarray: ...

class FFTDF(lib.StreamObject):
    blockdim: Incomplete
    cell: Incomplete
    stdout: Incomplete
    verbose: Incomplete
    max_memory: Incomplete
    mesh: Incomplete
    exxdiv: Incomplete
    def __init__(self, cell: Cell, kpts: Optional[Union[KPoints, List[List[float]], ndarray]]=None) -> None: ...
    @property
    def grids(self): ...
    @grids.setter
    def grids(self, val) -> None: ...
    @property
    def kpts(self): ...
    @kpts.setter
    def kpts(self, val) -> None: ...
    def reset(self, cell: Optional[Cell]=None) -> "FFTDF": ...
    def dump_flags(self, verbose=None): ...
    def check_sanity(self): ...
    def build(self): ...
    def aoR_loop(self, grids: Optional[UniformGrids]=None, kpts: Optional[ndarray]=None, deriv: int = 0) -> Iterator[Tuple[Tuple[List[ndarray], List[ndarray], ndarray, ndarray, ndarray], int, int]]: ...
    get_pp = get_pp
    get_nuc = get_nuc
    def get_jk_e1(self, dm: NPArrayWithTag, kpts: Optional[ndarray]=None, kpts_band: None=None, exxdiv: Optional[str]=None) -> Tuple[ndarray, ndarray]: ...
    def get_j_e1(self, dm: NPArrayWithTag, kpts: Optional[ndarray]=None, kpts_band: None=None) -> ndarray: ...
    def get_k_e1(self, dm: ndarray, kpts: Optional[ndarray]=None, kpts_band: None=None, exxdiv: Optional[str]=None) -> ndarray: ...
    def get_jk(self, dm: Union[ndarray, List[ndarray], NPArrayWithTag], hermi: int = 1, kpts: Optional[Union[ndarray, List[List[float]]]]=None, kpts_band: Optional[ndarray]=None, with_j: bool = True, with_k: bool = True, omega: Optional[float]=None, exxdiv: Optional[str]=None) -> Union[Tuple[ndarray, ndarray], Tuple[ndarray, None], Tuple[None, ndarray]]: ...
    get_eri = fft_ao2mo.get_eri
    get_ao_eri = fft_ao2mo.get_eri
    ao2mo = fft_ao2mo.general
    get_mo_eri = fft_ao2mo.general
    ao2mo_7d = fft_ao2mo.ao2mo_7d
    get_ao_pairs_G = fft_ao2mo.get_ao_pairs_G
    get_ao_pairs = fft_ao2mo.get_ao_pairs_G
    get_mo_pairs_G = fft_ao2mo.get_mo_pairs_G
    get_mo_pairs = fft_ao2mo.get_mo_pairs_G
    def update_mf(self, mf): ...
    def loop(self, blksize=None) -> Generator[Incomplete]: ...
    def get_naoaux(self): ...
    range_coulomb: Incomplete
    to_gpu = lib.to_gpu
