from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc import tools as tools
from pyscf.pbc.df import aft as aft, fft_ao2mo as fft_ao2mo, fft_jk as fft_jk, ft_ao as ft_ao
from pyscf.pbc.gto import error_for_ke_cutoff as error_for_ke_cutoff, estimate_ke_cutoff as estimate_ke_cutoff, pseudo as pseudo
from pyscf.pbc.lib.kpts import KPoints as KPoints
from pyscf.pbc.lib.kpts_helper import is_zero as is_zero

KE_SCALING: Incomplete

def get_nuc(mydf, kpts=None): ...
def get_pp(mydf, kpts=None): ...

class FFTDF(lib.StreamObject):
    blockdim: Incomplete
    cell: Incomplete
    stdout: Incomplete
    verbose: Incomplete
    max_memory: Incomplete
    mesh: Incomplete
    exxdiv: Incomplete
    def __init__(self, cell, kpts=None) -> None: ...
    @property
    def grids(self): ...
    @grids.setter
    def grids(self, val) -> None: ...
    @property
    def kpts(self): ...
    @kpts.setter
    def kpts(self, val) -> None: ...
    def reset(self, cell=None): ...
    def dump_flags(self, verbose=None): ...
    def check_sanity(self): ...
    def build(self): ...
    def aoR_loop(self, grids=None, kpts=None, deriv: int = 0) -> Generator[Incomplete]: ...
    get_pp = get_pp
    get_nuc = get_nuc
    def get_jk_e1(self, dm, kpts=None, kpts_band=None, exxdiv=None): ...
    def get_j_e1(self, dm, kpts=None, kpts_band=None): ...
    def get_k_e1(self, dm, kpts=None, kpts_band=None, exxdiv=None): ...
    def get_jk(self, dm, hermi: int = 1, kpts=None, kpts_band=None, with_j: bool = True, with_k: bool = True, omega=None, exxdiv=None): ...
    get_eri = fft_ao2mo.get_eri
    get_ao_eri = fft_ao2mo.get_eri
    ao2mo = fft_ao2mo.general
    get_mo_eri = fft_ao2mo.general
    ao2mo_7d = fft_ao2mo.ao2mo_7d
    get_ao_pairs_G = fft_ao2mo.get_ao_pairs_G
    get_ao_pairs = fft_ao2mo.get_ao_pairs_G
    get_mo_pairs_G = fft_ao2mo.get_mo_pairs_G
    get_mo_pairs = fft_ao2mo.get_mo_pairs_G
    def update_mf(self, mf): ...
    def loop(self, blksize=None) -> Generator[Incomplete]: ...
    def get_naoaux(self): ...
    range_coulomb: Incomplete
    to_gpu = lib.to_gpu
