from pyscf import __config__ as __config__, ao2mo as ao2mo, lib as lib
from pyscf.ao2mo.incore import iden_coeffs as iden_coeffs
from pyscf.pbc import tools as tools
from pyscf.pbc.lib import kpts_helper as kpts_helper
from pyscf.pbc.lib.kpts_helper import gamma_point as gamma_point, is_zero as is_zero, unique as unique
from numpy import bool, ndarray
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.df.fft import FFTDF
from pyscf.pbc.gto.cell import Cell
from typing import List, Optional, Tuple, Union

def get_eri(mydf: FFTDF, kpts: Optional[Union[ndarray, Tuple[ndarray, ndarray, ndarray, ndarray], List[ndarray]]]=None, compact: bool=...) -> ndarray: ...
def general(mydf: FFTDF, mo_coeffs: Union[ndarray, Tuple[ndarray, ndarray, ndarray, ndarray], Tuple[NPArrayWithTag, NPArrayWithTag, NPArrayWithTag, NPArrayWithTag], List[ndarray]], kpts: Optional[Union[ndarray, Tuple[ndarray, ndarray, ndarray, ndarray]]]=None, compact: bool=...) -> ndarray: ...
def get_ao_pairs_G(mydf: FFTDF, kpts: ndarray=..., q: None=None, shls_slice: None=None, compact: bool=...) -> ndarray: ...
def get_mo_pairs_G(mydf, mo_coeffs, kpts=..., q=None, compact=...): ...
def ao2mo_7d(mydf: FFTDF, mo_coeff_kpts: Union[ndarray, List[ndarray]], kpts: Optional[ndarray]=None, factor: Union[float, int] = 1, out: None=None) -> ndarray: ...
