from pyscf import lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc import tools as tools
from pyscf.pbc.lib.kpts_helper import is_zero as is_zero
from pyscf.pbc.tools.k2gamma import kpts_to_kmesh as kpts_to_kmesh
from numpy import ndarray
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.df.fft import FFTDF
from typing import List, Optional, Tuple, Union

def get_j_kpts(mydf: FFTDF, dm_kpts: Union[ndarray, List[ndarray], NPArrayWithTag], hermi: int = 1, kpts: ndarray=..., kpts_band: Optional[ndarray]=None) -> ndarray: ...
def get_j_e1_kpts(mydf: FFTDF, dm_kpts: NPArrayWithTag, kpts: ndarray=..., kpts_band: None=None) -> ndarray: ...
def get_k_kpts(mydf: FFTDF, dm_kpts: Union[ndarray, List[ndarray], NPArrayWithTag], hermi: int = 1, kpts: ndarray=..., kpts_band: Optional[ndarray]=None, exxdiv: Optional[str]=None) -> ndarray: ...
def get_k_e1_kpts(mydf: FFTDF, dm_kpts: Union[ndarray, NPArrayWithTag], kpts: ndarray=..., kpts_band: None=None, exxdiv: Optional[str]=None) -> ndarray: ...
def get_jk(mydf: FFTDF, dm: Union[ndarray, NPArrayWithTag], hermi: int = 1, kpt: ndarray=..., kpts_band: Optional[ndarray]=None, with_j: bool = True, with_k: bool = True, exxdiv: Optional[str]=None) -> Union[Tuple[ndarray, ndarray], Tuple[None, ndarray], Tuple[ndarray, None]]: ...
def get_j(mydf: FFTDF, dm: Union[ndarray, NPArrayWithTag], hermi: int = 1, kpt: ndarray=..., kpts_band: Optional[ndarray]=None) -> ndarray: ...
def get_k(mydf: FFTDF, dm: Union[ndarray, NPArrayWithTag], hermi: int = 1, kpt: ndarray=..., kpts_band: Optional[ndarray]=None, exxdiv: Optional[str]=None) -> ndarray: ...
