from _typeshed import Incomplete
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc import gto as pbcgto
from pyscf.pbc.lib.kpts_helper import gamma_point as gamma_point, is_zero as is_zero
from pyscf.pbc.tools import k2gamma as k2gamma
from numpy import float64, ndarray
from pyscf.lib.logger import Logger
from pyscf.pbc.df.rsdf_builder import _ExtendedMoleFT
from pyscf.pbc.gto.cell import Cell
from typing import Callable, Optional, Tuple, Union

RCUT_THRESHOLD: Incomplete
KECUT_THRESHOLD: Incomplete
STEEP_BASIS: int
LOCAL_BASIS: int
SMOOTH_BASIS: int
libpbc: Incomplete

def ft_aopair(cell: Cell, Gv: ndarray, shls_slice: None=None, aosym: str = 's1', b: Optional[ndarray]=None, gxyz: Optional[ndarray]=None, Gvbase: Optional[Tuple[ndarray, ndarray, ndarray]]=None, kpti_kptj: Union[ndarray, Tuple[ndarray, ndarray]]=..., q: Optional[ndarray]=None, intor: str = 'GTO_ft_ovlp', comp: int = 1, verbose: None=None) -> ndarray: ...
def ft_aopair_kpts(cell: Cell, Gv: ndarray, shls_slice: None=None, aosym: str = 's1', b: Optional[ndarray]=None, gxyz: Optional[ndarray]=None, Gvbase: Optional[Tuple[ndarray, ndarray, ndarray]]=None, q: ndarray=..., kptjs: ndarray=..., intor: str = 'GTO_ft_ovlp', comp: int = 1, bvk_kmesh: Optional[ndarray]=None, out: None=None) -> ndarray: ...
def ft_ao(mol: Union[Cell, _RangeSeparatedCell], Gv: ndarray, shls_slice: Optional[Tuple[int, int]]=None, b: Optional[ndarray]=None, gxyz: Optional[ndarray]=None, Gvbase: Optional[Tuple[ndarray, ndarray, ndarray]]=None, kpt: ndarray=..., verbose: None=None) -> ndarray: ...
def gen_ft_kernel(supmol: Union[_ExtendedMoleFT, ExtendedMole], aosym: str = 's1', intor: str = 'GTO_ft_ovlp', comp: int = 1, return_complex: bool = False, kpts: Optional[ndarray]=None, verbose: Optional[Logger]=None) -> Callable: ...

class _RangeSeparatedCell(pbcgto.Cell):
    ref_cell: Incomplete
    bas_map: Incomplete
    bas_type: Incomplete
    sh_loc: Incomplete
    def __init__(self) -> None: ...
    @classmethod
    def from_cell(cls, cell: Cell, ke_cut_threshold: Optional[Union[float, float64]]=None, rcut_threshold: Optional[float]=None, in_rsjk: Union[bool, Logger] = False, verbose: Optional[Logger]=None) -> "_RangeSeparatedCell": ...
    def smooth_basis_cell(self) -> Cell: ...
    def compact_basis_cell(self) -> "_RangeSeparatedCell": ...
    def merge_diffused_block(self, aosym: str = 's1') -> Callable: ...
    def recontract(self, dim: int = 1) -> Callable: ...
    def recontract_1d(self, vec: ndarray) -> ndarray: ...
    def get_ao_type(self) -> ndarray: ...
    def decontract_basis(self, to_cart: bool = True, aggregate: bool = False): ...

class ExtendedMole(gto.Mole):
    rs_cell: _RangeSeparatedCell
    bvk_kmesh: Incomplete
    Ls: Incomplete
    bvkmesh_Ls: Incomplete
    seg_loc: Incomplete
    seg2sh: Incomplete
    bas_mask: Incomplete
    precision: Incomplete
    def __init__(self) -> None: ...
    @property
    def sh_loc(self) -> ndarray: ...
    @property
    def bas_map(self): ...
    @classmethod
    def from_cell(cls, cell: Union[Cell, _RangeSeparatedCell], kmesh: ndarray, rcut: Optional[float64]=None, verbose: Optional[Logger]=None) -> Union[_ExtendedMoleFT, ExtendedMole]: ...
    def strip_basis(self, rcut: ndarray) -> Union[_ExtendedMoleFT, ExtendedMole]: ...
    def get_ovlp_mask(self, cutoff: None=None) -> ndarray: ...
    @staticmethod
    def bas_mask_to_segment(rs_cell: _RangeSeparatedCell, bas_mask: ndarray, verbose: Optional[Logger]=None) -> Tuple[ndarray, ndarray]: ...
    def bas_type_to_indices(self, type_code: int=...) -> ndarray: ...
    gen_ft_kernel = gen_ft_kernel

def estimate_rcut(cell: Union[Cell, _RangeSeparatedCell], precision: None=None) -> ndarray: ...
