from _typeshed import Incomplete
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc import gto as pbcgto
from pyscf.pbc.lib.kpts_helper import gamma_point as gamma_point, is_zero as is_zero
from pyscf.pbc.tools import k2gamma as k2gamma

RCUT_THRESHOLD: Incomplete
KECUT_THRESHOLD: Incomplete
STEEP_BASIS: int
LOCAL_BASIS: int
SMOOTH_BASIS: int
libpbc: Incomplete

def ft_aopair(cell, Gv, shls_slice=None, aosym: str = 's1', b=None, gxyz=None, Gvbase=None, kpti_kptj=..., q=None, intor: str = 'GTO_ft_ovlp', comp: int = 1, verbose=None): ...
def ft_aopair_kpts(cell, Gv, shls_slice=None, aosym: str = 's1', b=None, gxyz=None, Gvbase=None, q=..., kptjs=..., intor: str = 'GTO_ft_ovlp', comp: int = 1, bvk_kmesh=None, out=None): ...
def ft_ao(mol, Gv, shls_slice=None, b=None, gxyz=None, Gvbase=None, kpt=..., verbose=None): ...
def gen_ft_kernel(supmol, aosym: str = 's1', intor: str = 'GTO_ft_ovlp', comp: int = 1, return_complex: bool = False, kpts=None, verbose=None): ...

class _RangeSeparatedCell(pbcgto.Cell):
    ref_cell: Incomplete
    bas_map: Incomplete
    bas_type: Incomplete
    sh_loc: Incomplete
    def __init__(self) -> None: ...
    @classmethod
    def from_cell(cls, cell, ke_cut_threshold=None, rcut_threshold=None, in_rsjk: bool = False, verbose=None): ...
    def smooth_basis_cell(self): ...
    def compact_basis_cell(self): ...
    def merge_diffused_block(self, aosym: str = 's1'): ...
    def recontract(self, dim: int = 1): ...
    def recontract_1d(self, vec): ...
    def get_ao_type(self): ...
    def decontract_basis(self, to_cart: bool = True, aggregate: bool = False): ...

class ExtendedMole(gto.Mole):
    rs_cell: _RangeSeparatedCell
    bvk_kmesh: Incomplete
    Ls: Incomplete
    bvkmesh_Ls: Incomplete
    seg_loc: Incomplete
    seg2sh: Incomplete
    bas_mask: Incomplete
    precision: Incomplete
    def __init__(self) -> None: ...
    @property
    def sh_loc(self): ...
    @property
    def bas_map(self): ...
    @classmethod
    def from_cell(cls, cell, kmesh, rcut=None, verbose=None): ...
    def strip_basis(self, rcut): ...
    def get_ovlp_mask(self, cutoff=None): ...
    @staticmethod
    def bas_mask_to_segment(rs_cell, bas_mask, verbose=None): ...
    def bas_type_to_indices(self, type_code=...): ...
    gen_ft_kernel = gen_ft_kernel

def estimate_rcut(cell, precision=None): ...
