from _typeshed import Incomplete
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.lib import logger as logger, zdotCN as zdotCN, zdotNC as zdotNC, zdotNN as zdotNN
from pyscf.pbc.df import aft as aft, ft_ao as ft_ao, rsdf_builder as rsdf_builder
from pyscf.pbc.df.incore import Int3cBuilder as Int3cBuilder, libpbc as libpbc
from pyscf.pbc.lib.kpts_helper import KPT_DIFF_TOL as KPT_DIFF_TOL, is_zero as is_zero, kk_adapted_iter as kk_adapted_iter
from pyscf.pbc.tools import k2gamma as k2gamma
from numpy import float64, ndarray
from pyscf.lib.misc import H5TmpFile
from pyscf.pbc.df.ft_ao import _RangeSeparatedCell
from pyscf.pbc.df.mdf import _CCMDFBuilder
from pyscf.pbc.gto.cell import Cell
from typing import Callable, List, Optional, Tuple, Union

ETA_MIN: Incomplete

class _CCGDFBuilder(rsdf_builder._RSGDFBuilder):
    eta: Incomplete
    mesh: Incomplete
    fused_cell: Incomplete
    fuse: callable
    rs_fused_cell: Incomplete
    supmol_ft: Incomplete
    def __init__(self, cell: Cell, auxcell: Cell, kpts: ndarray=...) -> None: ...
    def has_long_range(self) -> bool: ...
    def reset(self, cell: None=None) -> None: ...
    def dump_flags(self, verbose: None=None) -> Union[_CCMDFBuilder, _CCGDFBuilder]: ...
    bvk_kmesh: Incomplete
    ke_cutoff: Incomplete
    direct_scf_tol: Incomplete
    rs_cell: Incomplete
    supmol: Incomplete
    def build(self) -> Union[_CCMDFBuilder, _CCGDFBuilder]: ...
    weighted_coulG = aft.weighted_coulG
    def get_2c2e(self, uniq_kpts: ndarray) -> List[ndarray]: ...
    def outcore_auxe2(self, cderi_file: str, intor: str = 'int3c2e', aosym: str = 's2', comp: None=None, j_only: bool = False, dataname: str = 'j3c', shls_slice: None=None, fft_dd_block: Optional[bool]=None, kk_idx: None=None) -> H5TmpFile: ...
    def weighted_ft_ao(self, kpt: ndarray) -> Tuple[ndarray, ndarray]: ...
    def gen_j3c_loader(self, h5group: H5TmpFile, kpt: ndarray, kpt_ij_idx: ndarray, aosym: str) -> Callable: ...
    def add_ft_j3c(self, j3c: Union[Tuple[List[ndarray], List[Optional[ndarray]]], Tuple[List[ndarray], List[ndarray]], Tuple[List[ndarray], List[None]]], Gpq: ndarray, Gaux: Tuple[ndarray, ndarray], p0: int, p1: int) -> None: ...
    def solve_cderi(self, cd_j2c: Union[Tuple[ndarray, None, str], Tuple[ndarray, ndarray, str]], j3cR: ndarray, j3cI: Optional[ndarray]) -> Union[Tuple[ndarray, ndarray], Tuple[ndarray, None]]: ...

class _CCNucBuilder(_CCGDFBuilder):
    exclude_dd_block: bool
    mesh: Incomplete
    fused_cell: Incomplete
    modchg_cell: Incomplete
    auxcell: Incomplete
    def __init__(self, cell: Cell, kpts: ndarray=...) -> None: ...
    def dump_flags(self, verbose: None=None) -> "_CCNucBuilder": ...
    bvk_kmesh: Incomplete
    ke_cutoff: Incomplete
    eta: Incomplete
    rs_cell: Incomplete
    supmol: Incomplete
    direct_scf_tol: Incomplete
    supmol_ft: Incomplete
    def build(self, eta: None=None) -> "_CCNucBuilder": ...
    def get_pp_loc_part1(self, mesh: None=None, with_pseudo: bool = True) -> ndarray: ...
    get_nuc = rsdf_builder.get_nuc
    get_pp = rsdf_builder.get_pp

def auxbar(fused_cell: Cell) -> ndarray: ...
def make_modchg_basis(auxcell: Cell, smooth_eta: float64) -> Cell: ...
def fuse_auxcell(auxcell: Cell, eta: Union[float, float64]) -> Tuple[Cell, Callable]: ...
def estimate_rcut(rs_cell: _RangeSeparatedCell, auxcell: Cell, precision: None=None, exclude_dd_block: bool = False) -> ndarray: ...
def estimate_eta_min(cell, precision=None): ...
def estimate_eta_for_ke_cutoff(cell: Cell, ke_cutoff: float64, precision: Optional[float]=None) -> Union[float, float64]: ...
def estimate_ke_cutoff_for_eta(cell: Cell, eta: Union[float, float64], precision: Optional[float]=None) -> float64: ...
