from _typeshed import Incomplete
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.lib import logger as logger, zdotCN as zdotCN, zdotNC as zdotNC, zdotNN as zdotNN
from pyscf.pbc.df import aft as aft, ft_ao as ft_ao, rsdf_builder as rsdf_builder
from pyscf.pbc.df.incore import Int3cBuilder as Int3cBuilder, libpbc as libpbc
from pyscf.pbc.lib.kpts_helper import KPT_DIFF_TOL as KPT_DIFF_TOL, is_zero as is_zero, kk_adapted_iter as kk_adapted_iter
from pyscf.pbc.tools import k2gamma as k2gamma

ETA_MIN: Incomplete

class _CCGDFBuilder(rsdf_builder._RSGDFBuilder):
    eta: Incomplete
    mesh: Incomplete
    fused_cell: Incomplete
    fuse: callable
    rs_fused_cell: Incomplete
    supmol_ft: Incomplete
    def __init__(self, cell, auxcell, kpts=...) -> None: ...
    def has_long_range(self): ...
    def reset(self, cell=None) -> None: ...
    def dump_flags(self, verbose=None): ...
    bvk_kmesh: Incomplete
    ke_cutoff: Incomplete
    direct_scf_tol: Incomplete
    rs_cell: Incomplete
    supmol: Incomplete
    def build(self): ...
    weighted_coulG = aft.weighted_coulG
    def get_2c2e(self, uniq_kpts): ...
    def outcore_auxe2(self, cderi_file, intor: str = 'int3c2e', aosym: str = 's2', comp=None, j_only: bool = False, dataname: str = 'j3c', shls_slice=None, fft_dd_block=None, kk_idx=None): ...
    def weighted_ft_ao(self, kpt): ...
    def gen_j3c_loader(self, h5group, kpt, kpt_ij_idx, aosym): ...
    def add_ft_j3c(self, j3c, Gpq, Gaux, p0, p1) -> None: ...
    def solve_cderi(self, cd_j2c, j3cR, j3cI): ...

class _CCNucBuilder(_CCGDFBuilder):
    exclude_dd_block: bool
    mesh: Incomplete
    fused_cell: Incomplete
    modchg_cell: Incomplete
    auxcell: Incomplete
    def __init__(self, cell, kpts=...) -> None: ...
    def dump_flags(self, verbose=None): ...
    bvk_kmesh: Incomplete
    ke_cutoff: Incomplete
    eta: Incomplete
    rs_cell: Incomplete
    supmol: Incomplete
    direct_scf_tol: Incomplete
    supmol_ft: Incomplete
    def build(self, eta=None): ...
    def get_pp_loc_part1(self, mesh=None, with_pseudo: bool = True): ...
    get_nuc = rsdf_builder.get_nuc
    get_pp = rsdf_builder.get_pp

def auxbar(fused_cell): ...
def make_modchg_basis(auxcell, smooth_eta): ...
def fuse_auxcell(auxcell, eta): ...
def estimate_rcut(rs_cell, auxcell, precision=None, exclude_dd_block: bool = False): ...
def estimate_eta_min(cell, precision=None): ...
def estimate_eta_for_ke_cutoff(cell, ke_cutoff, precision=None): ...
def estimate_ke_cutoff_for_eta(cell, eta, precision=None): ...
