from _typeshed import Incomplete
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc.df import ft_ao as ft_ao
from pyscf.pbc.gto.pseudo import pp_int as pp_int
from pyscf.pbc.lib.kpts_helper import is_zero as is_zero, unique as unique
from pyscf.pbc.tools import k2gamma as k2gamma
from numpy import bool, ndarray
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.df.ft_ao import ExtendedMole, _RangeSeparatedCell
from pyscf.pbc.df.gdf_builder import _CCGDFBuilder
from pyscf.pbc.df.mdf import _CCMDFBuilder, _RSMDFBuilder
from pyscf.pbc.df.rsdf_builder import _RSGDFBuilder
from pyscf.pbc.gto.cell import Cell
from typing import Any, Callable, Optional, Union

RCUT_THRESHOLD: Incomplete
KECUT_THRESHOLD: Incomplete
LOG_ADJUST: int
libpbc: Incomplete

def verify_cint_backend() -> None: ...
def make_auxcell(cell: Cell, auxbasis: Optional[Any]=None) -> Cell: ...
make_auxmol = make_auxcell

def format_aux_basis(cell: Cell, auxbasis: str = 'weigend+etb') -> Cell: ...
def aux_e2(cell: Cell, auxcell_or_auxbasis: Cell, intor: str = 'int3c2e', aosym: str = 's1', comp: None=None, kptij_lst: ndarray=..., shls_slice: None=None, **kwargs) -> ndarray: ...
def wrap_int3c(cell: Cell, auxcell: Cell, intor: str = 'int3c2e', aosym: str = 's1', comp: Optional[int] = 1, kptij_lst: ndarray=..., cintopt: None=None, pbcopt: None=None) -> Callable: ...
def fill_2c2e(cell: Cell, auxcell_or_auxbasis: Cell, intor: str = 'int2c2e', hermi: int = 0, kpt: ndarray=...) -> ndarray: ...

class Int3cBuilder(lib.StreamObject):
    cell: Incomplete
    auxcell: Incomplete
    stdout: Incomplete
    verbose: Incomplete
    max_memory: Incomplete
    kpts: Incomplete
    rs_cell: Incomplete
    bvk_kmesh: Incomplete
    supmol: Incomplete
    ke_cutoff: Incomplete
    direct_scf_tol: Incomplete
    def __init__(self, cell: Cell, auxcell: Optional[Cell], kpts: Optional[ndarray]=None) -> None: ...
    def reset(self, cell: None=None) -> Union[_RSMDFBuilder, _CCGDFBuilder, _RSGDFBuilder, _CCMDFBuilder]: ...
    def build(self) -> "Int3cBuilder": ...
    def gen_int3c_kernel(self, intor: str = 'int3c2e', aosym: str = 's2', comp: Optional[int]=None, j_only: Union[bool, bool] = False, reindex_k: Optional[ndarray]=None, rs_auxcell: Optional[_RangeSeparatedCell]=None, auxcell: Optional[Cell]=None, supmol: None=None, return_complex: bool = False) -> Callable: ...
    def get_q_cond(self, supmol: Optional[ExtendedMole]=None) -> ndarray: ...

def estimate_rcut(cell: Cell, auxcell: Cell, precision: None=None) -> ndarray: ...
def aux_e2_sum_auxbas(cell: Cell, auxcell_or_auxbasis: Cell, intor: str = 'int3c2e', aosym: str = 's1', comp: Optional[int]=None, kptij_lst: ndarray=..., shls_slice: None=None, **kwargs) -> ndarray: ...
def wrap_int3c_sum_auxbas(cell, auxcell, intor: str = 'int3c2e', aosym: str = 's1', comp=None, kptij_lst=..., cintopt=None, pbcopt=None, neighbor_list=None): ...
def int3c1e_nuc_grad(cell: Cell, auxcell: Cell, dm: Union[ndarray, NPArrayWithTag], intor: str = 'int3c1e', aosym: str = 's1', comp: int = 3, kptij_lst: ndarray=..., shls_slice: None=None, **kwargs) -> ndarray: ...
def wrap_int3c1e_nuc_grad(cell, auxcell, dm, intor: str = 'int3c1e', aosym: str = 's1', comp: int = 3, kptij_lst=..., cintopt=None, pbcopt=None, neighbor_list=None): ...
