from _typeshed import Incomplete
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc.df import ft_ao as ft_ao
from pyscf.pbc.gto.pseudo import pp_int as pp_int
from pyscf.pbc.lib.kpts_helper import is_zero as is_zero, unique as unique
from pyscf.pbc.tools import k2gamma as k2gamma

RCUT_THRESHOLD: Incomplete
KECUT_THRESHOLD: Incomplete
LOG_ADJUST: int
libpbc: Incomplete

def verify_cint_backend() -> None: ...
def make_auxcell(cell, auxbasis=None): ...
make_auxmol = make_auxcell

def format_aux_basis(cell, auxbasis: str = 'weigend+etb'): ...
def aux_e2(cell, auxcell_or_auxbasis, intor: str = 'int3c2e', aosym: str = 's1', comp=None, kptij_lst=..., shls_slice=None, **kwargs): ...
def wrap_int3c(cell, auxcell, intor: str = 'int3c2e', aosym: str = 's1', comp: int = 1, kptij_lst=..., cintopt=None, pbcopt=None): ...
def fill_2c2e(cell, auxcell_or_auxbasis, intor: str = 'int2c2e', hermi: int = 0, kpt=...): ...

class Int3cBuilder(lib.StreamObject):
    cell: Incomplete
    auxcell: Incomplete
    stdout: Incomplete
    verbose: Incomplete
    max_memory: Incomplete
    kpts: Incomplete
    rs_cell: Incomplete
    bvk_kmesh: Incomplete
    supmol: Incomplete
    ke_cutoff: Incomplete
    direct_scf_tol: Incomplete
    def __init__(self, cell, auxcell, kpts=None) -> None: ...
    def reset(self, cell=None): ...
    def build(self): ...
    def gen_int3c_kernel(self, intor: str = 'int3c2e', aosym: str = 's2', comp=None, j_only: bool = False, reindex_k=None, rs_auxcell=None, auxcell=None, supmol=None, return_complex: bool = False): ...
    def get_q_cond(self, supmol=None): ...

def estimate_rcut(cell, auxcell, precision=None): ...
def aux_e2_sum_auxbas(cell, auxcell_or_auxbasis, intor: str = 'int3c2e', aosym: str = 's1', comp=None, kptij_lst=..., shls_slice=None, **kwargs): ...
def wrap_int3c_sum_auxbas(cell, auxcell, intor: str = 'int3c2e', aosym: str = 's1', comp=None, kptij_lst=..., cintopt=None, pbcopt=None, neighbor_list=None): ...
def int3c1e_nuc_grad(cell, auxcell, dm, intor: str = 'int3c1e', aosym: str = 's1', comp: int = 3, kptij_lst=..., shls_slice=None, **kwargs): ...
def wrap_int3c1e_nuc_grad(cell, auxcell, dm, intor: str = 'int3c1e', aosym: str = 's1', comp: int = 3, kptij_lst=..., cintopt=None, pbcopt=None, neighbor_list=None): ...
