from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger, zdotCN as zdotCN
from pyscf.pbc import gto as gto
from pyscf.pbc.df import aft as aft, df as df, ft_ao as ft_ao, mdf_ao2mo as mdf_ao2mo, mdf_jk as mdf_jk, outcore as outcore
from pyscf.pbc.df.gdf_builder import _CCGDFBuilder
from pyscf.pbc.df.incore import libpbc as libpbc, make_auxcell as make_auxcell
from pyscf.pbc.df.rsdf_builder import _RSGDFBuilder, estimate_rs_2c2e_rcut as estimate_rs_2c2e_rcut
from pyscf.pbc.lib.kpts import KPoints as KPoints
from pyscf.pbc.lib.kpts_helper import is_zero as is_zero, member as member, unique as unique

class MDF(df.GDF):
    cell: Incomplete
    stdout: Incomplete
    verbose: Incomplete
    max_memory: Incomplete
    kpts: Incomplete
    kpts_band: Incomplete
    eta: Incomplete
    mesh: Incomplete
    exp_to_discard: Incomplete
    time_reversal_symmetry: bool
    exxdiv: Incomplete
    auxcell: Incomplete
    blockdim: Incomplete
    linear_dep_threshold: Incomplete
    def __init__(self, cell, kpts=...) -> None: ...
    def build(self, j_only=None, with_j3c: bool = True, kpts_band=None): ...
    def weighted_coulG(self, kpt=..., exx: bool = False, mesh=None, omega=None): ...
    get_pp: Incomplete
    get_nuc: Incomplete
    def get_jk(self, dm, hermi: int = 1, kpts=None, kpts_band=None, with_j: bool = True, with_k: bool = True, omega=None, exxdiv=None): ...
    get_eri = mdf_ao2mo.get_eri
    get_ao_eri = mdf_ao2mo.get_eri
    ao2mo = mdf_ao2mo.general
    get_mo_eri = mdf_ao2mo.general
    ao2mo_7d = mdf_ao2mo.ao2mo_7d
    def update_mp(self) -> None: ...
    def update_cc(self) -> None: ...
    def update(self) -> None: ...
    def loop(self, blksize=None) -> Generator[Incomplete]: ...
    def get_naoaux(self): ...

class _RSMDFBuilder(_RSGDFBuilder):
    j2c_eig_always: bool
    def __init__(self, cell, auxcell, kpts=...) -> None: ...
    def has_long_range(self): ...
    def get_2c2e(self, uniq_kpts): ...
    def outcore_auxe2(self, cderi_file, intor: str = 'int3c2e', aosym: str = 's2', comp=None, j_only: bool = False, dataname: str = 'j3c', shls_slice=None, fft_dd_block: bool = False, kk_idx=None): ...
    def weighted_ft_ao(self, kpt): ...
    weighted_coulG: Incomplete

class _CCMDFBuilder(_CCGDFBuilder):
    j2c_eig_always: bool
    def __init__(self, cell, auxcell, kpts=...) -> None: ...
    def has_long_range(self): ...
    def get_2c2e(self, uniq_kpts): ...
    def outcore_auxe2(self, cderi_file, intor: str = 'int3c2e', aosym: str = 's2', comp=None, j_only: bool = False, dataname: str = 'j3c', shls_slice=None, fft_dd_block: bool = False, kk_idx=None): ...
    def weighted_ft_ao(self, kpt): ...
    def gen_j3c_loader(self, h5group, kpt, kpt_ij_idx, aosym): ...
    def add_ft_j3c(self, j3c, Gpq, Gaux, p0, p1) -> None: ...
    def solve_cderi(self, cd_j2c, j3cR, j3cI): ...
    weighted_coulG: Incomplete
