from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger, zdotCN as zdotCN
from pyscf.pbc import gto as gto
from pyscf.pbc.df import aft as aft, df as df, ft_ao as ft_ao, mdf_ao2mo as mdf_ao2mo, mdf_jk as mdf_jk, outcore as outcore
from pyscf.pbc.df.gdf_builder import _CCGDFBuilder
from pyscf.pbc.df.incore import libpbc as libpbc, make_auxcell as make_auxcell
from pyscf.pbc.df.rsdf_builder import _RSGDFBuilder, estimate_rs_2c2e_rcut as estimate_rs_2c2e_rcut
from pyscf.pbc.lib.kpts import KPoints, KPoints as KPoints
from pyscf.pbc.lib.kpts_helper import is_zero as is_zero, member as member, unique as unique
from numpy import float64, ndarray
from pyscf.lib.misc import H5TmpFile
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.gto.cell import Cell
from typing import Callable, List, Optional, Tuple, Union

class MDF(df.GDF):
    cell: Incomplete
    stdout: Incomplete
    verbose: Incomplete
    max_memory: Incomplete
    kpts: Incomplete
    kpts_band: Incomplete
    eta: Incomplete
    mesh: Incomplete
    exp_to_discard: Incomplete
    time_reversal_symmetry: bool
    exxdiv: Incomplete
    auxcell: Incomplete
    blockdim: Incomplete
    linear_dep_threshold: Incomplete
    def __init__(self, cell: Cell, kpts: Union[ndarray, List[ndarray], List[List[float]], KPoints]=...) -> None: ...
    def build(self, j_only: Optional[bool]=None, with_j3c: bool = True, kpts_band: Optional[ndarray]=None) -> "MDF": ...
    def weighted_coulG(self, kpt: ndarray=..., exx: Optional[Union[bool, str]] = False, mesh: Optional[Union[ndarray, List[int]]]=None, omega: Optional[float64]=None) -> ndarray: ...
    get_pp: Incomplete
    get_nuc: Incomplete
    def get_jk(self, dm: Union[ndarray, NPArrayWithTag], hermi: int = 1, kpts: Optional[Union[ndarray, List[List[float]]]]=None, kpts_band: Optional[ndarray]=None, with_j: bool = True, with_k: bool = True, omega: Optional[float]=None, exxdiv: Optional[str]=None) -> Union[Tuple[ndarray, ndarray], Tuple[None, ndarray]]: ...
    get_eri = mdf_ao2mo.get_eri
    get_ao_eri = mdf_ao2mo.get_eri
    ao2mo = mdf_ao2mo.general
    get_mo_eri = mdf_ao2mo.general
    ao2mo_7d = mdf_ao2mo.ao2mo_7d
    def update_mp(self) -> None: ...
    def update_cc(self) -> None: ...
    def update(self) -> None: ...
    def loop(self, blksize=None) -> Generator[Incomplete]: ...
    def get_naoaux(self): ...

class _RSMDFBuilder(_RSGDFBuilder):
    j2c_eig_always: bool
    def __init__(self, cell: Cell, auxcell: Cell, kpts: ndarray=...) -> None: ...
    def has_long_range(self): ...
    def get_2c2e(self, uniq_kpts: ndarray) -> List[ndarray]: ...
    def outcore_auxe2(self, cderi_file: str, intor: str = 'int3c2e', aosym: str = 's2', comp: None=None, j_only: bool = False, dataname: str = 'j3c', shls_slice: None=None, fft_dd_block: bool = False, kk_idx: None=None) -> H5TmpFile: ...
    def weighted_ft_ao(self, kpt: ndarray) -> Tuple[ndarray, ndarray]: ...
    weighted_coulG: Incomplete

class _CCMDFBuilder(_CCGDFBuilder):
    j2c_eig_always: bool
    def __init__(self, cell: Cell, auxcell: Cell, kpts: ndarray=...) -> None: ...
    def has_long_range(self): ...
    def get_2c2e(self, uniq_kpts: ndarray) -> List[ndarray]: ...
    def outcore_auxe2(self, cderi_file: str, intor: str = 'int3c2e', aosym: str = 's2', comp: None=None, j_only: bool = False, dataname: str = 'j3c', shls_slice: None=None, fft_dd_block: bool = False, kk_idx: None=None) -> H5TmpFile: ...
    def weighted_ft_ao(self, kpt: ndarray) -> Tuple[ndarray, ndarray]: ...
    def gen_j3c_loader(self, h5group: H5TmpFile, kpt: ndarray, kpt_ij_idx: ndarray, aosym: str) -> Callable: ...
    def add_ft_j3c(self, j3c: Union[Tuple[List[ndarray], List[ndarray]], Tuple[List[ndarray], List[Optional[ndarray]]], Tuple[List[ndarray], List[None]]], Gpq: ndarray, Gaux: Tuple[ndarray, ndarray], p0: int, p1: int) -> None: ...
    def solve_cderi(self, cd_j2c: Tuple[ndarray, None, str], j3cR: ndarray, j3cI: Optional[ndarray]) -> Tuple[ndarray, None]: ...
    weighted_coulG: Incomplete
