from pyscf.lib import logger as logger
from pyscf.pbc.df import aft_jk as aft_jk, df_jk as df_jk
from numpy import ndarray
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.df.mdf import MDF
from pyscf.pbc.scf.hf import SCF
from typing import Optional, Tuple, Union

def density_fit(mf: SCF, auxbasis: Optional[str]=None, mesh: Optional[Tuple[int, int, int]]=None, with_df: None=None) -> SCF: ...
def get_j_kpts(mydf: MDF, dm_kpts: Union[ndarray, NPArrayWithTag], hermi: int = 1, kpts: ndarray=..., kpts_band: Optional[ndarray]=None) -> ndarray: ...
def get_k_kpts(mydf: MDF, dm_kpts: Union[ndarray, NPArrayWithTag], hermi: int = 1, kpts: ndarray=..., kpts_band: Optional[ndarray]=None, exxdiv: Optional[str]=None) -> ndarray: ...
def get_jk(mydf: MDF, dm: Union[ndarray, NPArrayWithTag], hermi: int = 1, kpt: ndarray=..., kpts_band: Optional[ndarray]=None, with_j: bool = True, with_k: bool = True, exxdiv: Optional[str]=None) -> Tuple[ndarray, ndarray]: ...
