from pyscf import __config__ as __config__, lib as lib
from pyscf.pbc.df import aft_ao2mo as aft_ao2mo, df_ao2mo as df_ao2mo
from pyscf.pbc.lib import kpts_helper as kpts_helper
from pyscf.pbc.lib.kpts_helper import gamma_point as gamma_point, unique as unique

def get_eri(mydf, kpts=None, compact=...): ...
def general(mydf, mo_coeffs, kpts=None, compact=...): ...
def ao2mo_7d(mydf, mo_coeff_kpts, kpts=None, factor: int = 1, out=None): ...
