from _typeshed import Incomplete
from pyscf import gto as mol_gto, lib as lib
from pyscf.lib import logger as logger
from pyscf.lib.parameters import BOHR as BOHR
from pyscf.pbc.df.incore import libpbc as libpbc, make_auxcell as make_auxcell
from pyscf.pbc.lib.kpts_helper import KPT_DIFF_TOL as KPT_DIFF_TOL, gamma_point as gamma_point, is_zero as is_zero, unique as unique
from pyscf.pbc.tools import k2gamma as k2gamma

class MoleNoBasSort(mol_gto.mole.Mole):
    atom: Incomplete
    basis: Incomplete
    def build(self, **kwargs): ...

def remove_exp_basis(basis, amin=None, amax=None): ...
def estimate_omega_for_npw(cell, npw_max, precision=None, kmax: int = 0, round2odd: bool = True): ...
def estimate_mesh_for_omega(cell, omega, precision=None, kmax: int = 0, round2odd: bool = True): ...
def intor_j2c(cell, omega, precision=None, kpts=None, hermi: int = 1, shls_slice=None, no_screening: bool = False): ...
def wrap_int3c_nospltbas(cell, auxcell, omega, shlpr_mask, prescreening_data, intor: str = 'int3c2e', aosym: str = 's1', comp: int = 1, kptij_lst=..., cintopt=None, bvk_kmesh=None): ...
