from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.lib import logger as logger, zdotCN as zdotCN
from pyscf.pbc.df import aft as aft, ft_ao as ft_ao
from pyscf.pbc.df.incore import Int3cBuilder as Int3cBuilder, libpbc as libpbc
from pyscf.pbc.gto import pseudo as pseudo
from pyscf.pbc.lib.kpts_helper import KPT_DIFF_TOL as KPT_DIFF_TOL, is_zero as is_zero, kk_adapted_iter as kk_adapted_iter, member as member, members_with_wrap_around as members_with_wrap_around
from pyscf.pbc.tools import k2gamma as k2gamma
from h5py._hl.dataset import Dataset
from numpy import bool, float64, int64, ndarray
from pyscf.lib.misc import H5TmpFile
from pyscf.pbc.df.ft_ao import ExtendedMole, _RangeSeparatedCell
from pyscf.pbc.df.gdf_builder import _CCGDFBuilder, _CCNucBuilder
from pyscf.pbc.df.mdf import _CCMDFBuilder, _RSMDFBuilder
from pyscf.pbc.gto.cell import Cell
from typing import Callable, Iterator, List, Optional, Tuple, Union

OMEGA_MIN: float
INDEX_MIN: int
LINEAR_DEP_THR: Incomplete
RCUT_THRESHOLD: Incomplete

class _RSGDFBuilder(Int3cBuilder):
    fft_dd_block: bool
    exclude_d_aux: bool
    j2c_eig_always: bool
    linear_dep_threshold = LINEAR_DEP_THR
    mesh: Incomplete
    omega: Incomplete
    rs_auxcell: Incomplete
    supmol_ft: Incomplete
    def __init__(self, cell: Cell, auxcell: Cell, kpts: ndarray=...) -> None: ...
    @property
    def exclude_dd_block(self): ...
    @exclude_dd_block.setter
    def exclude_dd_block(self, x) -> None: ...
    def has_long_range(self) -> Union[bool, bool]: ...
    def dump_flags(self, verbose: None=None) -> Union[_RSGDFBuilder, _RSNucBuilder, _RSMDFBuilder]: ...
    bvk_kmesh: Incomplete
    ke_cutoff: Incomplete
    direct_scf_tol: Incomplete
    rs_cell: Incomplete
    supmol: Incomplete
    def build(self, omega: None=None) -> Union[_RSGDFBuilder, _RSMDFBuilder]: ...
    weighted_coulG = aft.weighted_coulG
    def weighted_coulG_LR(self, kpt=..., exx: bool = False, mesh=None): ...
    def weighted_coulG_SR(self, kpt: ndarray=..., exx: bool = False, mesh: Optional[Union[ndarray, List[int]]]=None) -> ndarray: ...
    def get_q_cond(self, supmol: Optional[ExtendedMole]=None) -> ndarray: ...
    def decompose_j2c(self, j2c: Union[ndarray, Dataset]) -> Union[Tuple[ndarray, ndarray, str], Tuple[ndarray, None, str]]: ...
    def cholesky_decomposed_metric(self, j2c: ndarray) -> Union[Tuple[ndarray, ndarray, str], Tuple[ndarray, None, str]]: ...
    def eigenvalue_decomposed_metric(self, j2c: ndarray) -> Union[Tuple[ndarray, ndarray, str], Tuple[ndarray, None, str]]: ...
    def get_2c2e(self, uniq_kpts: ndarray) -> List[ndarray]: ...
    def outcore_auxe2(self, cderi_file: str, intor: str = 'int3c2e', aosym: str = 's2', comp: None=None, j_only: bool = False, dataname: str = 'j3c', shls_slice: None=None, fft_dd_block: Optional[bool]=None, kk_idx: Optional[ndarray]=None) -> H5TmpFile: ...
    def weighted_ft_ao(self, kpt: ndarray) -> Tuple[ndarray, ndarray]: ...
    def gen_j3c_loader(self, h5group: H5TmpFile, kpt: ndarray, kpt_ij_idx: ndarray, aosym: str) -> Callable: ...
    def add_ft_j3c(self, j3c: Union[Tuple[List[ndarray], List[None]], Tuple[List[ndarray], List[ndarray]], Tuple[List[ndarray], List[Optional[ndarray]]]], Gpq: ndarray, Gaux: Tuple[ndarray, ndarray], p0: int, p1: int) -> None: ...
    def solve_cderi(self, cd_j2c: Union[Tuple[ndarray, ndarray, str], Tuple[ndarray, None, str]], j3cR: ndarray, j3cI: Optional[ndarray]) -> Union[Tuple[ndarray, ndarray], Tuple[ndarray, None]]: ...
    def gen_uniq_kpts_groups(self, j_only: bool, h5swap: H5TmpFile, kk_idx: Optional[ndarray]=None) -> Iterator[Union[Tuple[ndarray, ndarray, Tuple[ndarray, ndarray, str]], Tuple[ndarray, ndarray, Tuple[ndarray, None, str]]]]: ...
    def make_j3c(self, cderi_file: str, intor: str = 'int3c2e', aosym: str = 's2', comp: None=None, j_only: bool = False, dataname: str = 'j3c', shls_slice: None=None, kptij_lst: Optional[ndarray]=None) -> Union[_CCMDFBuilder, _RSGDFBuilder, _CCGDFBuilder, _RSMDFBuilder]: ...

def get_nuc(nuc_builder: Union[_CCNucBuilder, _RSNucBuilder]) -> ndarray: ...
def get_pp(nuc_builder: Union[_CCNucBuilder, _RSNucBuilder]) -> ndarray: ...

class _RSNucBuilder(_RSGDFBuilder):
    exclude_d_aux: bool
    mesh: Incomplete
    omega: Incomplete
    auxcell: Incomplete
    def __init__(self, cell: Cell, kpts: ndarray=...) -> None: ...
    bvk_kmesh: Incomplete
    ke_cutoff: Incomplete
    direct_scf_tol: Incomplete
    rs_cell: Incomplete
    supmol: Incomplete
    supmol_ft: Incomplete
    def build(self, omega: None=None) -> "_RSNucBuilder": ...
    def get_pp_loc_part1(self, mesh: None=None, with_pseudo: bool = True) -> ndarray: ...
    get_pp = get_pp
    get_nuc = get_nuc

class _ExtendedMoleFT(ft_ao.ExtendedMole):
    exclude_dd_block: bool
    def get_ovlp_mask(self, cutoff: None=None) -> ndarray: ...

def estimate_rcut(rs_cell: _RangeSeparatedCell, rs_auxcell: Union[Cell, _RangeSeparatedCell], omega: Union[float, int, float64], precision: None=None, exclude_dd_block: bool = False, exclude_d_aux: bool = False) -> ndarray: ...
def estimate_ft_rcut(rs_cell: _RangeSeparatedCell, precision: Optional[float]=None, exclude_dd_block: bool = False) -> ndarray: ...
def estimate_omega_min(cell, precision=None): ...
def estimate_ke_cutoff_for_omega(cell: Cell, omega: Union[float, float64], precision: Optional[float]=None) -> float64: ...
def estimate_omega_for_ke_cutoff(cell: Cell, ke_cutoff: float64, precision: Optional[float]=None) -> float64: ...
def estimate_rs_2c2e_rcut(auxcell: Union[Cell, _RangeSeparatedCell], omega: Union[float, float64], precision: Optional[float]=None) -> float64: ...
