from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.lib import logger as logger, zdotCN as zdotCN
from pyscf.pbc.df import aft as aft, ft_ao as ft_ao
from pyscf.pbc.df.incore import Int3cBuilder as Int3cBuilder, libpbc as libpbc
from pyscf.pbc.gto import pseudo as pseudo
from pyscf.pbc.lib.kpts_helper import KPT_DIFF_TOL as KPT_DIFF_TOL, is_zero as is_zero, kk_adapted_iter as kk_adapted_iter, member as member, members_with_wrap_around as members_with_wrap_around
from pyscf.pbc.tools import k2gamma as k2gamma

OMEGA_MIN: float
INDEX_MIN: int
LINEAR_DEP_THR: Incomplete
RCUT_THRESHOLD: Incomplete

class _RSGDFBuilder(Int3cBuilder):
    fft_dd_block: bool
    exclude_d_aux: bool
    j2c_eig_always: bool
    linear_dep_threshold = LINEAR_DEP_THR
    mesh: Incomplete
    omega: Incomplete
    rs_auxcell: Incomplete
    supmol_ft: Incomplete
    def __init__(self, cell, auxcell, kpts=...) -> None: ...
    @property
    def exclude_dd_block(self): ...
    @exclude_dd_block.setter
    def exclude_dd_block(self, x) -> None: ...
    def has_long_range(self): ...
    def dump_flags(self, verbose=None): ...
    bvk_kmesh: Incomplete
    ke_cutoff: Incomplete
    direct_scf_tol: Incomplete
    rs_cell: Incomplete
    supmol: Incomplete
    def build(self, omega=None): ...
    weighted_coulG = aft.weighted_coulG
    def weighted_coulG_LR(self, kpt=..., exx: bool = False, mesh=None): ...
    def weighted_coulG_SR(self, kpt=..., exx: bool = False, mesh=None): ...
    def get_q_cond(self, supmol=None): ...
    def decompose_j2c(self, j2c): ...
    def cholesky_decomposed_metric(self, j2c): ...
    def eigenvalue_decomposed_metric(self, j2c): ...
    def get_2c2e(self, uniq_kpts): ...
    def outcore_auxe2(self, cderi_file, intor: str = 'int3c2e', aosym: str = 's2', comp=None, j_only: bool = False, dataname: str = 'j3c', shls_slice=None, fft_dd_block=None, kk_idx=None): ...
    def weighted_ft_ao(self, kpt): ...
    def gen_j3c_loader(self, h5group, kpt, kpt_ij_idx, aosym): ...
    def add_ft_j3c(self, j3c, Gpq, Gaux, p0, p1) -> None: ...
    def solve_cderi(self, cd_j2c, j3cR, j3cI): ...
    def gen_uniq_kpts_groups(self, j_only, h5swap, kk_idx=None) -> Generator[Incomplete]: ...
    def make_j3c(self, cderi_file, intor: str = 'int3c2e', aosym: str = 's2', comp=None, j_only: bool = False, dataname: str = 'j3c', shls_slice=None, kptij_lst=None): ...

def get_nuc(nuc_builder): ...
def get_pp(nuc_builder): ...

class _RSNucBuilder(_RSGDFBuilder):
    exclude_d_aux: bool
    mesh: Incomplete
    omega: Incomplete
    auxcell: Incomplete
    def __init__(self, cell, kpts=...) -> None: ...
    bvk_kmesh: Incomplete
    ke_cutoff: Incomplete
    direct_scf_tol: Incomplete
    rs_cell: Incomplete
    supmol: Incomplete
    supmol_ft: Incomplete
    def build(self, omega=None): ...
    def get_pp_loc_part1(self, mesh=None, with_pseudo: bool = True): ...
    get_pp = get_pp
    get_nuc = get_nuc

class _ExtendedMoleFT(ft_ao.ExtendedMole):
    exclude_dd_block: bool
    def get_ovlp_mask(self, cutoff=None): ...

def estimate_rcut(rs_cell, rs_auxcell, omega, precision=None, exclude_dd_block: bool = False, exclude_d_aux: bool = False): ...
def estimate_ft_rcut(rs_cell, precision=None, exclude_dd_block: bool = False): ...
def estimate_omega_min(cell, precision=None): ...
def estimate_ke_cutoff_for_omega(cell, omega, precision=None): ...
def estimate_omega_for_ke_cutoff(cell, ke_cutoff, precision=None): ...
def estimate_rs_2c2e_rcut(auxcell, omega, precision=None): ...
