import ctypes
from _typeshed import Incomplete
from pyscf import gto as gto, lib as lib
from pyscf.data.elements import NUC as NUC
from pyscf.data.radii import BRAGG as BRAGG
from pyscf.df.incore import aux_e2 as aux_e2
from pyscf.dft import gen_grid as gen_grid
from pyscf.dft.gen_grid import LEBEDEV_ORDER as LEBEDEV_ORDER, SGX_ANG_MAPPING as SGX_ANG_MAPPING, becke_lko as becke_lko, sgx_prune as sgx_prune
from pyscf.dft.numint import BLKSIZE as BLKSIZE, NBINS as NBINS, SWITCH_SIZE as SWITCH_SIZE, libdft as libdft
from pyscf.dft.radi import treutler_ahlrichs as treutler_ahlrichs
from pyscf.gto import moleintor as moleintor
from pyscf.lib import logger as logger

SGX_BLKSIZE: Incomplete
DFT_PER_SGX: Incomplete
SGX_DELTA: float

class _CSGXOpt(ctypes.Structure): ...

class SGXData:
    fit_ovlp: Incomplete
    sym_ovlp: Incomplete
    max_memory: Incomplete
    hermi: Incomplete
    bound_algo: Incomplete
    def __init__(self, mol, grids, fit_ovlp: bool = True, sym_ovlp: bool = False, max_memory: int = 2000, hermi: int = 0, bound_algo: str = 'sample_pos', sgxopt=None, etol=None, vtol=None, direct_scf_tol: float = 0.0) -> None: ...
    @property
    def use_dm_screening(self): ...
    def reset(self) -> None: ...
    @property
    def mol(self): ...
    @mol.setter
    def mol(self, mol) -> None: ...
    @property
    def grids(self): ...
    @grids.setter
    def grids(self, grids) -> None: ...
    def set_block(self, b0, weights, full_f_bi=None) -> None: ...
    def unset_block(self) -> None: ...
    def get_loop_data(self, nset: int = 1, with_pair_mask: bool = True, grad: bool = False): ...
    def reduce_mask_ni2sgx(self, xni_bi): ...
    def reduce_ao_to_shl_mat(self, ao, ao_loc, wt): ...
    def build(self) -> None: ...
    def get_dm_threshold_matrix(self, dm, full_dm_ij=None): ...
    def get_g_threshold(self, f_ug, g_ug, i0, wt, full_f_bi=None): ...

def get_jk_favork(sgx, dm, hermi: int = 1, with_j: bool = True, with_k: bool = True, direct_scf_tol: float = 1e-13): ...
def get_k_only(sgx, dm, hermi: int = 1, direct_scf_tol: float = 1e-13): ...
def get_jk_favorj(sgx, dm, hermi: int = 1, with_j: bool = True, with_k: bool = True, direct_scf_tol: float = 1e-13): ...

SGX_RAD_GRIDS: Incomplete
nums: Incomplete

def get_gridss(mol, level: int = 1, gthrd: float = 1e-10, use_opt_grids: bool = False): ...
get_jk = get_jk_favorj
