from _typeshed import Incomplete
from pyscf import df as df, grad as grad, gto as gto, lib as lib, scf as scf
from pyscf.lib import logger as logger
from pyscf.qmmm.pbc import mm_mole as mm_mole

def add_mm_charges(scf_method, atoms_or_coords, a, charges, radii=None, rcut_ewald=None, rcut_hcore=None, unit=None): ...
def qmmm_for_scf(method, mm_mol): ...

class QMMM:
    __name_mixin__: str

class QMMMSCF(QMMM):
    to_gpu = NotImplemented
    as_scanner = NotImplemented
    mm_mol: Incomplete
    s1r: Incomplete
    s1rr: Incomplete
    mm_ewald_pot: Incomplete
    qm_ewald_hess: Incomplete
    e_nuc: Incomplete
    def __init__(self, method, mm_mol) -> None: ...
    def dump_flags(self, verbose=None): ...
    def get_mm_ewald_pot(self, mol, mm_mol): ...
    def get_qm_ewald_pot(self, mol, dm, qm_ewald_hess=None): ...
    def get_hcore(self, mol=None): ...
    def get_qm_charges(self, dm): ...
    def get_s1r(self): ...
    def get_qm_dipoles(self, dm, s1r=None): ...
    def get_s1rr(self): ...
    def get_qm_quadrupoles(self, dm, s1rr=None): ...
    def get_vdiff(self, mol, ewald_pot): ...
    def get_veff(self, mol=None, dm=None, dm_last: int = 0, vhf_last: int = 0, hermi: int = 1, mm_ewald_pot=None, qm_ewald_pot=None): ...
    def energy_elec(self, dm=None, h1e=None, vhf=None): ...
    def energy_ewald(self, dm=None, mm_ewald_pot=None, qm_ewald_pot=None): ...
    def energy_nuc(self): ...
    def energy_tot(self, dm=None, h1e=None, vhf=None, mm_ewald_pot=None, qm_ewald_pot=None): ...
    def nuc_grad_method(self): ...
    Gradients = nuc_grad_method

def add_mm_charges_grad(scf_grad, atoms_or_coords, a, charges, radii=None, rcut_ewald=None, rcut_hcore=None, unit=None): ...
mm_charge_grad = add_mm_charges_grad

def qmmm_grad_for_scf(scf_grad): ...

class QMMMGrad:
    __name_mixin__: str
    to_gpu = NotImplemented
    def __init__(self, scf_grad) -> None: ...
    def dump_flags(self, verbose=None): ...
    def grad_ewald(self, dm=None, with_mm: bool = False, mm_ewald_pot=None, qm_ewald_pot=None): ...
    def get_hcore(self, mol=None): ...
    def grad_hcore_mm(self, dm, mol=None): ...
    contract_hcore_mm = grad_hcore_mm
    de_nuc_mm: Incomplete
    def grad_nuc(self, mol=None, atmlst=None): ...
    def grad_nuc_mm(self, mol=None): ...
