from pyscf import gto as gto
from pyscf.ao2mo import incore as incore, outcore as outcore, r_outcore as r_outcore
from pyscf.ao2mo.addons import load as load, restore as restore

def full(eri_or_mol, mo_coeff, erifile=None, dataname: str = 'eri_mo', intor: str = 'int2e', *args, **kwargs): ...
def general(eri_or_mol, mo_coeffs, erifile=None, dataname: str = 'eri_mo', intor: str = 'int2e', *args, **kwargs): ...
def kernel(eri_or_mol, mo_coeffs, erifile=None, dataname: str = 'eri_mo', intor: str = 'int2e', *args, **kwargs): ...
def get_ao_eri(mol): ...
get_mo_eri = kernel
