from _typeshed import Incomplete
from pyscf import lib as lib
from pyscf.gto.moleintor import ascint3 as ascint3, make_cintopt as make_cintopt, make_loc as make_loc

libao2mo: Incomplete

class AO2MOpt:
    def __init__(self, mol, intor, prescreen: str = 'CVHFnoscreen', qcondname=None) -> None: ...
    def __del__(self) -> None: ...

def nr_e1fill(intor, sh_range, atm, bas, env, aosym: str = 's1', comp: int = 1, ao2mopt=None, out=None): ...
def nr_e1(eri, mo_coeff, orbs_slice, aosym: str = 's1', mosym: str = 's1', out=None): ...
def nr_e2(eri, mo_coeff, orbs_slice, aosym: str = 's1', mosym: str = 's1', out=None, ao_loc=None): ...
def r_e1(intor, mo_coeff, orbs_slice, sh_range, atm, bas, env, tao, aosym: str = 's1', comp: int = 1, ao2mopt=None, out=None): ...
def r_e2(eri, mo_coeff, orbs_slice, tao, ao_loc, aosym: str = 's1', out=None): ...
