from _typeshed import Incomplete
from pyscf import lib as lib
from pyscf.gto.moleintor import ascint3 as ascint3, make_cintopt as make_cintopt, make_loc as make_loc
from ctypes import c_void_p
from numpy import ndarray
from pyscf.gto.mole import Mole
from typing import Optional, Tuple

libao2mo: Incomplete

class AO2MOpt:
    def __init__(self, mol: Mole, intor: str, prescreen: str = 'CVHFnoscreen', qcondname: Optional[str]=None) -> None: ...
    def __del__(self) -> None: ...

def nr_e1fill(intor: str, sh_range: Tuple[int, int, int], atm: ndarray, bas: ndarray, env: ndarray, aosym: str = 's1', comp: int = 1, ao2mopt: Optional[AO2MOpt]=None, out: Optional[ndarray]=None) -> ndarray: ...
def nr_e1(eri: ndarray, mo_coeff: ndarray, orbs_slice: Tuple[int, int, int, int], aosym: str = 's1', mosym: str = 's1', out: None=None) -> ndarray: ...
def nr_e2(eri: ndarray, mo_coeff: ndarray, orbs_slice: Tuple[int, int, int, int], aosym: str = 's1', mosym: str = 's1', out: Optional[ndarray]=None, ao_loc: Optional[ndarray]=None) -> ndarray: ...
def r_e1(intor: str, mo_coeff: ndarray, orbs_slice: Tuple[int, int, int, int], sh_range: Tuple[int, int, int], atm: ndarray, bas: ndarray, env: ndarray, tao: ndarray, aosym: str = 's1', comp: int = 1, ao2mopt: Optional[AO2MOpt]=None, out: None=None) -> ndarray: ...
def r_e2(eri: ndarray, mo_coeff: ndarray, orbs_slice: Tuple[int, int, int, int], tao: ndarray, ao_loc: Optional[ndarray], aosym: str = 's1', out: None=None) -> ndarray: ...
