from pyscf import lib as lib
from pyscf.lib import logger as logger

BLOCK: int

def full(eri_ao, mo_coeff, verbose: int = 0, compact: bool = True, **kwargs): ...
def general(eri_ao, mo_coeffs, verbose: int = 0, compact: bool = True, **kwargs): ...
def half_e1(eri_ao, mo_coeffs, compact: bool = True): ...
def iden_coeffs(mo1, mo2): ...
