from pyscf import lib as lib
from pyscf.lib import logger as logger
from numpy import bool, ndarray
from pyscf.lib.logger import Logger
from pyscf.lib.numpy_helper import NPArrayWithTag
from typing import List, Tuple, Union

BLOCK: int

def full(eri_ao: ndarray, mo_coeff: ndarray, verbose: Union[int, Logger] = 0, compact: bool = True, **kwargs) -> ndarray: ...
def general(eri_ao: ndarray, mo_coeffs: Union[ndarray, Tuple[NPArrayWithTag, NPArrayWithTag, NPArrayWithTag, NPArrayWithTag], Tuple[ndarray, ndarray, ndarray, ndarray], List[ndarray]], verbose: Union[int, Logger] = 0, compact: bool = True, **kwargs) -> ndarray: ...
def half_e1(eri_ao: ndarray, mo_coeffs: Union[ndarray, Tuple[NPArrayWithTag, NPArrayWithTag, NPArrayWithTag, NPArrayWithTag], Tuple[ndarray, ndarray, ndarray, ndarray], List[ndarray]], compact: bool = True) -> ndarray: ...
def iden_coeffs(mo1: Union[ndarray, NPArrayWithTag], mo2: Union[ndarray, NPArrayWithTag]) -> Union[bool, bool]: ...
