from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.ao2mo import outcore as outcore
from pyscf.gto.moleintor import ascint3 as ascint3, make_cintopt as make_cintopt, make_loc as make_loc
from pyscf.lib import logger as logger
from ctypes import c_void_p
from numpy import ndarray
from pyscf.gto.mole import Mole
from pyscf.lib.logger import Logger
from typing import Callable, Iterator, List, Optional, Tuple

libao2mo: Incomplete
IOBLK_SIZE: Incomplete
IOBUF_WORDS: Incomplete
IOBUF_ROW_MIN: Incomplete
MAX_MEMORY: Incomplete

def full(mol, mo_coeff, erifile, dataname: str = 'eri_mo', intor: str = 'int2e_sph', motype: str = 'ghf', aosym: str = 's1', comp=None, max_memory=..., ioblk_size=..., verbose=...): ...
def general(mol: Mole, mo_coeffs: Tuple[ndarray, ndarray, ndarray, ndarray], erifile: str, dataname: str = 'eri_mo', intor: str = 'int2e_sph', motype: str = 'ghf', aosym: str = 's1', comp: None=None, max_memory: int=..., ioblk_size: int=..., verbose: Callable=...) -> str: ...
def full_iofree(mol: Mole, mo_coeff: ndarray, dataname: str = 'eri_mo', intor: str = 'int2e_sph', motype: str = 'ghf', aosym: str = 's1', comp: None=None, verbose: Callable=..., **kwargs) -> ndarray: ...
def general_iofree(mol, mo_coeffs, dataname: str = 'eri_mo', intor: str = 'int2e_sph', motype: str = 'ghf', aosym: str = 's1', comp=None, verbose=..., **kwargs): ...
def half_e1(mol: Mole, mo_coeffs: Tuple[List[ndarray], List[ndarray]], swapfile: str, intor: str = 'int2e_sph', aosym: str = 's1', comp: Optional[int]=None, max_memory: int=..., ioblk_size: int=..., verbose: Logger=..., ao2mopt: None=None) -> str: ...
def r_e1(intor: str, mo_a: ndarray, mo_b: ndarray, orbs_slice: Tuple[int, int, int, int], sh_range: Tuple[int, int, int], atm: ndarray, bas: ndarray, env: ndarray, tao: ndarray, aosym: str = 's1', comp: int = 1, ao2mopt: None=None, out: None=None) -> ndarray: ...
def iden_coeffs(mo1: ndarray, mo2: ndarray) -> bool: ...
def prange(start: int, end: int, step: int) -> Iterator[Tuple[int, int]]: ...
def guess_e1bufsize(max_memory: int, ioblk_size: int, nij_pair: int, nao_pair: int, comp: int) -> Tuple[int, float, int, int]: ...
def guess_e2bufsize(ioblk_size: int, nrows: int, ncols: int) -> Tuple[int, Tuple[int, int]]: ...
