from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.ao2mo import outcore as outcore
from pyscf.gto.moleintor import ascint3 as ascint3, make_cintopt as make_cintopt, make_loc as make_loc
from pyscf.lib import logger as logger

libao2mo: Incomplete
IOBLK_SIZE: Incomplete
IOBUF_WORDS: Incomplete
IOBUF_ROW_MIN: Incomplete
MAX_MEMORY: Incomplete

def full(mol, mo_coeff, erifile, dataname: str = 'eri_mo', intor: str = 'int2e_sph', motype: str = 'ghf', aosym: str = 's1', comp=None, max_memory=..., ioblk_size=..., verbose=...): ...
def general(mol, mo_coeffs, erifile, dataname: str = 'eri_mo', intor: str = 'int2e_sph', motype: str = 'ghf', aosym: str = 's1', comp=None, max_memory=..., ioblk_size=..., verbose=...): ...
def full_iofree(mol, mo_coeff, dataname: str = 'eri_mo', intor: str = 'int2e_sph', motype: str = 'ghf', aosym: str = 's1', comp=None, verbose=..., **kwargs): ...
def general_iofree(mol, mo_coeffs, dataname: str = 'eri_mo', intor: str = 'int2e_sph', motype: str = 'ghf', aosym: str = 's1', comp=None, verbose=..., **kwargs): ...
def half_e1(mol, mo_coeffs, swapfile, intor: str = 'int2e_sph', aosym: str = 's1', comp=None, max_memory=..., ioblk_size=..., verbose=..., ao2mopt=None): ...
def r_e1(intor, mo_a, mo_b, orbs_slice, sh_range, atm, bas, env, tao, aosym: str = 's1', comp: int = 1, ao2mopt=None, out=None): ...
def iden_coeffs(mo1, mo2): ...
def prange(start, end, step) -> Generator[Incomplete]: ...
def guess_e1bufsize(max_memory, ioblk_size, nij_pair, nao_pair, comp): ...
def guess_e2bufsize(ioblk_size, nrows, ncols): ...
