from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.ao2mo import incore as incore
from pyscf.lib import logger as logger

IOBLK_SIZE: Incomplete
IOBUF_WORDS: Incomplete
IOBUF_ROW_MIN: Incomplete
MAX_MEMORY: Incomplete

def full(mol, mo_coeff, erifile, dataname: str = 'eri_mo', intor: str = 'int2e', aosym: str = 's4', comp=None, max_memory=..., ioblk_size=..., verbose=..., compact: bool = True): ...
def general(mol, mo_coeffs, erifile, dataname: str = 'eri_mo', intor: str = 'int2e', aosym: str = 's4', comp=None, max_memory=..., ioblk_size=..., verbose=..., compact: bool = True): ...
def half_e1(mol, mo_coeffs, swapfile, intor: str = 'int2e', aosym: str = 's4', comp: int = 1, max_memory=..., ioblk_size=..., verbose=..., compact: bool = True, ao2mopt=None): ...
def full_iofree(mol, mo_coeff, intor: str = 'int2e', aosym: str = 's4', comp=None, max_memory=..., ioblk_size=..., verbose=..., compact: bool = True): ...
def general_iofree(mol, mo_coeffs, intor: str = 'int2e', aosym: str = 's4', comp=None, max_memory=..., ioblk_size=..., verbose=..., compact: bool = True): ...
def iden_coeffs(mo1, mo2): ...
def prange(start, end, step) -> Generator[Incomplete]: ...
def guess_e1bufsize(max_memory, ioblk_size, nij_pair, nao_pair, comp): ...
def guess_e2bufsize(ioblk_size, nrows, ncols): ...
def guess_shell_ranges(mol, aosym, max_iobuf, max_aobuf=None, ao_loc=None, compress_diag: bool = True): ...
def balance_segs(segs_lst, blksize, start_id: int = 0, stop_id=None): ...
def balance_partition(ao_loc, blksize, start_id: int = 0, stop_id=None): ...
