from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.ao2mo import incore as incore
from pyscf.lib import logger as logger
from h5py._hl.group import Group
from numpy import ndarray
from pyscf.gto.mole import Mole
from pyscf.lib.logger import Logger
from pyscf.lib.misc import H5TmpFile
from pyscf.lib.numpy_helper import NPArrayWithTag
from typing import Iterator, List, Optional, Tuple, Union

IOBLK_SIZE: Incomplete
IOBUF_WORDS: Incomplete
IOBUF_ROW_MIN: Incomplete
MAX_MEMORY: Incomplete

def full(mol: Mole, mo_coeff: ndarray, erifile: Union[H5TmpFile, str], dataname: str = 'eri_mo', intor: str = 'int2e', aosym: str = 's4', comp: Optional[int]=None, max_memory: int=..., ioblk_size: int=..., verbose: Union[int, Logger]=..., compact: bool = True) -> Union[H5TmpFile, str]: ...
def general(mol: Mole, mo_coeffs: Union[Tuple[ndarray, ndarray, ndarray, ndarray], Tuple[NPArrayWithTag, NPArrayWithTag, NPArrayWithTag, NPArrayWithTag], List[ndarray]], erifile: Union[H5TmpFile, str], dataname: str = 'eri_mo', intor: str = 'int2e', aosym: Union[int, str] = 's4', comp: Optional[int]=None, max_memory: Union[float, int]=..., ioblk_size: int=..., verbose: Union[int, Logger]=..., compact: bool = True) -> Union[H5TmpFile, str]: ...
def half_e1(mol: Mole, mo_coeffs: Union[Tuple[ndarray, ndarray], Tuple[NPArrayWithTag, NPArrayWithTag, NPArrayWithTag, NPArrayWithTag], Tuple[ndarray, ndarray, ndarray, ndarray], List[ndarray]], swapfile: H5TmpFile, intor: str = 'int2e', aosym: str = 's4', comp: int = 1, max_memory: Union[float, int]=..., ioblk_size: int=..., verbose: Logger=..., compact: bool = True, ao2mopt: None=None) -> H5TmpFile: ...
def full_iofree(mol: Mole, mo_coeff: ndarray, intor: str = 'int2e', aosym: str = 's4', comp: None=None, max_memory: int=..., ioblk_size: int=..., verbose: int=..., compact: bool = True) -> ndarray: ...
def general_iofree(mol: Mole, mo_coeffs: List[ndarray], intor: str = 'int2e', aosym: str = 's4', comp: None=None, max_memory: int=..., ioblk_size: int=..., verbose: int=..., compact: bool = True) -> ndarray: ...
def iden_coeffs(mo1: Union[ndarray, NPArrayWithTag], mo2: Union[ndarray, NPArrayWithTag]) -> bool: ...
def prange(start: int, end: int, step: int) -> Iterator[Tuple[int, int]]: ...
def guess_e1bufsize(max_memory: Union[float, int], ioblk_size: int, nij_pair: int, nao_pair: int, comp: int) -> Union[Tuple[int, float, float, int], Tuple[int, int, float, int]]: ...
def guess_e2bufsize(ioblk_size: Union[float, int], nrows: int, ncols: int) -> Tuple[int, Tuple[int, int]]: ...
def guess_shell_ranges(mol: Mole, aosym: bool, max_iobuf: int, max_aobuf: Optional[int]=None, ao_loc: Optional[ndarray]=None, compress_diag: bool = True) -> List[Tuple[int, int, int, List[Tuple[int, int, int]]]]: ...
def balance_segs(segs_lst: ndarray, blksize: int, start_id: int = 0, stop_id: None=None) -> List[Tuple[int, int, int]]: ...
def balance_partition(ao_loc: ndarray, blksize: int, start_id: int = 0, stop_id: Optional[int]=None) -> List[Tuple[int, int, int]]: ...
