from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.ao2mo import outcore as outcore
from pyscf.lib import logger as logger
from numpy import ndarray
from pyscf.gto.mole import Mole
from pyscf.lib.logger import Logger
from pyscf.lib.misc import H5TmpFile
from typing import Iterator, List, Optional, Tuple, Union

IOBLK_SIZE: Incomplete
IOBUF_WORDS: Incomplete
IOBUF_ROW_MIN: Incomplete
MAX_MEMORY: Incomplete

def full(mol: Mole, mo_coeff: ndarray, erifile: str, dataname: str = 'eri_mo', intor: str = 'int2e_spinor', aosym: str = 's4', comp: None=None, max_memory: int=..., ioblk_size: int=..., verbose: int=...) -> str: ...
def general(mol: Mole, mo_coeffs: Union[List[ndarray], Tuple[ndarray, ndarray, ndarray, ndarray]], erifile: Union[H5TmpFile, str], dataname: str = 'eri_mo', intor: str = 'int2e_spinor', aosym: str = 's4', comp: None=None, max_memory: int=..., ioblk_size: int=..., verbose: int=...) -> Union[H5TmpFile, str]: ...
def half_e1(mol: Mole, mo_coeffs: Union[List[ndarray], Tuple[ndarray, ndarray, ndarray, ndarray]], swapfile: str, intor: str = 'int2e_spinor', aosym: str = 's4', comp: Optional[int]=None, max_memory: int=..., ioblk_size: int=..., verbose: Logger=..., ao2mopt: None=None) -> str: ...
def full_iofree(mol: Mole, mo_coeff: ndarray, intor: str = 'int2e_spinor', aosym: str = 's4', comp: None=None, verbose: int=..., **kwargs) -> ndarray: ...
def general_iofree(mol: Mole, mo_coeffs: Union[List[ndarray], Tuple[ndarray, ndarray, ndarray, ndarray]], intor: str = 'int2e_spinor', aosym: str = 's4', comp: None=None, verbose: int=..., **kwargs) -> ndarray: ...
def iden_coeffs(mo1: ndarray, mo2: ndarray) -> bool: ...
def prange(start: int, end: int, step: int) -> Iterator[Tuple[int, int]]: ...
def guess_e1bufsize(max_memory: int, ioblk_size: int, nij_pair: int, nao_pair: int, comp: int) -> Tuple[int, float, int, int]: ...
def guess_e2bufsize(ioblk_size: int, nrows: int, ncols: int) -> Tuple[int, Tuple[int, int]]: ...
