from pyscf import scf as scf
from pyscf.dft import KohnShamDFT as KohnShamDFT
from pyscf.tdscf import dhf as dhf, dks as dks, ghf as ghf, gks as gks, rhf as rhf, rks as rks, uhf as uhf, uks as uks
from pyscf.tdscf.ghf import TDGHF as TDGHF
from pyscf.tdscf.gks import TDGKS as TDGKS
from pyscf.tdscf.rhf import TDRHF as TDRHF
from pyscf.tdscf.rks import TDRKS as TDRKS
from pyscf.tdscf.uhf import TDUHF as TDUHF
from pyscf.tdscf.uks import TDUKS as TDUKS

def TDHF(mf, frozen=None): ...
def TDA(mf, frozen=None): ...
def TDDFT(mf, frozen=None): ...
TD = TDDFT

def RPA(mf, frozen=None): ...
def dRPA(mf, frozen=None): ...
def dTDA(mf, frozen=None): ...
