from pyscf.lib import logger as logger
from pyscf.lib.exceptions import LinearDependencyError as LinearDependencyError
from pyscf.lib.parameters import MAX_MEMORY as MAX_MEMORY

MAX_SPACE_INC: int

def eigh(aop, x0, precond, tol_residual: float = 1e-05, lindep: float = 1e-12, nroots: int = 1, x0sym=None, pick=None, max_cycle: int = 50, max_memory=..., verbose=...): ...
def eig(aop, x0, precond, tol_residual: float = 1e-05, nroots: int = 1, x0sym=None, pick=None, max_cycle: int = 50, max_memory=..., lindep: float = 1e-12, verbose=...): ...
def real_eig(aop, x0, precond, tol_residual: float = 1e-05, nroots: int = 1, x0sym=None, pick=None, max_cycle: int = 50, max_memory=..., lindep: float = 1e-12, verbose=...): ...
def TDDFT_subspace_eigen_solver(a, b, sigma, pi, nroots): ...
def VW_Gram_Schmidt_fill_holder(V_holder, W_holder, X_new, Y_new, lindep: float = 1e-12): ...
