from pyscf.lib import logger as logger
from pyscf.lib.exceptions import LinearDependencyError as LinearDependencyError
from pyscf.lib.parameters import MAX_MEMORY as MAX_MEMORY
from numpy import ndarray
from pyscf.lib.logger import Logger
from typing import Callable, List, Optional, Tuple, Union

MAX_SPACE_INC: int

def eigh(aop: Callable, x0: ndarray, precond: Callable, tol_residual: float = 1e-05, lindep: float = 1e-12, nroots: int = 1, x0sym: Optional[ndarray]=None, pick: Optional[Callable]=None, max_cycle: int = 50, max_memory: Union[float, int]=..., verbose: Logger=...) -> Tuple[ndarray, ndarray, ndarray]: ...
def eig(aop: Callable, x0: ndarray, precond: Callable, tol_residual: float = 1e-05, nroots: int = 1, x0sym: Optional[ndarray]=None, pick: Optional[Callable]=None, max_cycle: int = 50, max_memory: int=..., lindep: float = 1e-12, verbose: Logger=...) -> Tuple[ndarray, ndarray, ndarray]: ...
def real_eig(aop: Callable, x0: ndarray, precond: Callable, tol_residual: float = 1e-05, nroots: int = 1, x0sym: Optional[ndarray]=None, pick: None=None, max_cycle: int = 50, max_memory: int=..., lindep: float = 1e-12, verbose: Logger=...) -> Tuple[ndarray, ndarray, ndarray]: ...
def TDDFT_subspace_eigen_solver(a: ndarray, b: ndarray, sigma: ndarray, pi: ndarray, nroots: int) -> Tuple[ndarray, ndarray, ndarray]: ...
def VW_Gram_Schmidt_fill_holder(V_holder: ndarray, W_holder: ndarray, X_new: ndarray, Y_new: ndarray, lindep: float = 1e-12) -> Tuple[ndarray, ndarray]: ...
