from _typeshed import Incomplete
from functools import reduce as reduce
from pyscf import __config__ as __config__, ao2mo as ao2mo, gto as gto, lib as lib, scf as scf, symm as symm
from pyscf.data import nist as nist
from pyscf.gto.ppnl_velgauge import get_gth_pp_nl_velgauge_commutator as get_gth_pp_nl_velgauge_commutator
from pyscf.lib import logger as logger
from pyscf.scf import hf_symm as hf_symm
from pyscf.tdscf._lr_eig import real_eig as real_eig
from numpy import int64, ndarray
from pyscf.dft.rks import RKS
from pyscf.dft.rks_symm import SymAdaptedRKS
from pyscf.gto.mole import Mole
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.scf.hf import RHF, SCF
from pyscf.scf.hf_symm import SymAdaptedRHF
from pyscf.tdscf.rks import CasidaTDDFT, TDDFT, dTDA
from typing import Callable, List, Optional, Tuple, Union

OUTPUT_THRESHOLD: Incomplete
REAL_EIG_THRESHOLD: Incomplete
MO_BASE: Incomplete

def gen_tda_operation(mf: Union[RHF, RKS], fock_ao: None=None, singlet: Optional[bool] = True, wfnsym: None=None, with_nlc: bool = True) -> Tuple[Callable, ndarray]: ...
gen_tda_hop = gen_tda_operation

def get_frozen_mask(td: "TDBase") -> ndarray: ...
def get_ab(mf: Union[RHF, RKS], frozen: None=None, mo_energy: None=None, mo_coeff: None=None, mo_occ: None=None) -> Tuple[ndarray, ndarray]: ...
def get_nto(tdobj: Incomplete, state: int = 1, threshold: float=..., verbose: None=None) -> Union[Tuple[ndarray, NPArrayWithTag], Tuple[ndarray, ndarray]]: ...
def analyze(tdobj: Union[Incomplete, CasidaTDDFT, Incomplete], verbose: None=None) -> Union[Incomplete, CasidaTDDFT, Incomplete]: ...
def transition_dipole(tdobj: "TDBase", xy: None=None) -> ndarray: ...
def transition_velocity_dipole(tdobj: "TDBase", xy: None=None) -> ndarray: ...
def transition_magnetic_dipole(tdobj: "TDBase", xy: None=None) -> ndarray: ...
def transition_quadrupole(tdobj: Incomplete, xy: None=None) -> ndarray: ...
def transition_velocity_quadrupole(tdobj: Union[Incomplete, Incomplete], xy: None=None) -> ndarray: ...
def transition_magnetic_quadrupole(tdobj: Union[Incomplete, Incomplete], xy: None=None) -> ndarray: ...
def transition_octupole(tdobj: Incomplete, xy: None=None) -> ndarray: ...
def transition_velocity_octupole(tdobj: Union[Incomplete, Incomplete], xy: None=None) -> ndarray: ...
def oscillator_strength(tdobj: "TDBase", e: None=None, xy: None=None, gauge: str = 'length', order: int = 0) -> ndarray: ...
def dipole_spectral_function(tdobj, e=None, xy=None, gauge: str = 'length', freqs=None, eta: float = 0.001): ...
def photoabsorption_cross_section(tdobj, e=None, xy=None, gauge: str = 'length', freqs=None, eta: float = 0.001): ...
def as_scanner(td): ...

class TD_Scanner(lib.SinglePointScanner):
    def __init__(self, td: Incomplete) -> None: ...
    def __call__(self, mol_or_geom, **kwargs): ...

class TDBase(lib.StreamObject):
    conv_tol: Incomplete
    nstates: Incomplete
    singlet: Incomplete
    lindep: Incomplete
    level_shift: Incomplete
    max_cycle: Incomplete
    positive_eig_threshold: Incomplete
    deg_eia_thresh: Incomplete
    exclude_nlc: bool
    verbose: Incomplete
    stdout: Incomplete
    mol: Incomplete
    max_memory: Incomplete
    chkfile: Incomplete
    frozen: Incomplete
    wfnsym: Incomplete
    converged: Incomplete
    e: Incomplete
    xy: Incomplete
    def __init__(self, mf: SCF, frozen: None=None) -> None: ...
    @property
    def nroots(self): ...
    @nroots.setter
    def nroots(self, x) -> None: ...
    def set_frozen(self, method: str = 'auto', window: Tuple[float, float]=(-1000.0, 1000.0)) -> Union[Incomplete, Incomplete, Incomplete]: ...
    @property
    def e_tot(self) -> ndarray: ...
    def dump_flags(self, verbose: None=None) -> None: ...
    def reset(self, mol: Optional[Mole]=None) -> Incomplete: ...
    get_frozen_mask = get_frozen_mask
    def gen_vind(self, mf=None) -> None: ...
    def gen_response(self, *args, **kwargs) -> Callable: ...
    def get_ab(self, mf: None=None, frozen: None=None) -> Tuple[ndarray, ndarray]: ...
    def get_precond(self, hdiag: ndarray) -> Callable: ...
    analyze = analyze
    get_nto = get_nto
    oscillator_strength = oscillator_strength
    transition_dipole = transition_dipole
    transition_quadrupole = transition_quadrupole
    transition_octupole = transition_octupole
    transition_velocity_dipole = transition_velocity_dipole
    transition_velocity_quadrupole = transition_velocity_quadrupole
    transition_velocity_octupole = transition_velocity_octupole
    transition_magnetic_dipole = transition_magnetic_dipole
    transition_magnetic_quadrupole = transition_magnetic_quadrupole
    dipole_spectral_function = dipole_spectral_function
    photoabsorption_cross_section = photoabsorption_cross_section
    as_scanner = as_scanner
    def Gradients(self) -> None: ...
    def nuc_grad_method(self): ...
    def to_gpu(self) -> None: ...

class TDA(TDBase):
    def gen_vind(self, mf: Optional[Union[SymAdaptedRKS, RHF, SymAdaptedRHF, RKS]]=None) -> Tuple[Callable, ndarray]: ...
    def get_init_guess(self, mf: Union[SymAdaptedRKS, RHF, SymAdaptedRHF, RKS], nstates: Optional[int]=None, wfnsym: None=None, return_symmetry: bool = False) -> Union[Tuple[ndarray, None], Tuple[ndarray, ndarray]]: ...
    def init_guess(self, mf, nstates=None, wfnsym=None, return_symmetry: bool = False): ...
    nstates: Incomplete
    xy: Incomplete
    def kernel(self, x0: None=None, nstates: Optional[int]=None) -> Tuple[ndarray, List[Tuple[ndarray, int]]]: ...
    def Gradients(self): ...
    def to_gpu(self): ...
CIS = TDA

def gen_tdhf_operation(mf: Union[RHF, RKS], fock_ao: None=None, singlet: bool = True, wfnsym: None=None, with_nlc: bool = True) -> Tuple[Callable, ndarray]: ...

class TDHF(TDBase):
    def gen_vind(self, mf: Optional[Union[RHF, SymAdaptedRHF, RKS]]=None) -> Tuple[Callable, ndarray]: ...
    def get_init_guess(self, mf: Union[RHF, SymAdaptedRHF, RKS], nstates: Optional[int]=None, wfnsym: None=None, return_symmetry: bool = False) -> Union[Tuple[ndarray, None], Tuple[ndarray, ndarray]]: ...
    nstates: Incomplete
    xy: Incomplete
    def kernel(self, x0: None=None, nstates: Optional[int]=None) -> Tuple[ndarray, List[Tuple[ndarray, ndarray]]]: ...
    Gradients: Incomplete
    def to_gpu(self): ...
RPA = TDHF
TDRHF = TDHF
