from _typeshed import Incomplete
from functools import reduce as reduce
from pyscf import __config__ as __config__, ao2mo as ao2mo, gto as gto, lib as lib, scf as scf, symm as symm
from pyscf.data import nist as nist
from pyscf.gto.ppnl_velgauge import get_gth_pp_nl_velgauge_commutator as get_gth_pp_nl_velgauge_commutator
from pyscf.lib import logger as logger
from pyscf.scf import hf_symm as hf_symm
from pyscf.tdscf._lr_eig import real_eig as real_eig

OUTPUT_THRESHOLD: Incomplete
REAL_EIG_THRESHOLD: Incomplete
MO_BASE: Incomplete

def gen_tda_operation(mf, fock_ao=None, singlet: bool = True, wfnsym=None, with_nlc: bool = True): ...
gen_tda_hop = gen_tda_operation

def get_frozen_mask(td): ...
def get_ab(mf, frozen=None, mo_energy=None, mo_coeff=None, mo_occ=None): ...
def get_nto(tdobj, state: int = 1, threshold=..., verbose=None): ...
def analyze(tdobj, verbose=None): ...
def transition_dipole(tdobj, xy=None): ...
def transition_velocity_dipole(tdobj, xy=None): ...
def transition_magnetic_dipole(tdobj, xy=None): ...
def transition_quadrupole(tdobj, xy=None): ...
def transition_velocity_quadrupole(tdobj, xy=None): ...
def transition_magnetic_quadrupole(tdobj, xy=None): ...
def transition_octupole(tdobj, xy=None): ...
def transition_velocity_octupole(tdobj, xy=None): ...
def oscillator_strength(tdobj, e=None, xy=None, gauge: str = 'length', order: int = 0): ...
def dipole_spectral_function(tdobj, e=None, xy=None, gauge: str = 'length', freqs=None, eta: float = 0.001): ...
def photoabsorption_cross_section(tdobj, e=None, xy=None, gauge: str = 'length', freqs=None, eta: float = 0.001): ...
def as_scanner(td): ...

class TD_Scanner(lib.SinglePointScanner):
    def __init__(self, td) -> None: ...
    def __call__(self, mol_or_geom, **kwargs): ...

class TDBase(lib.StreamObject):
    conv_tol: Incomplete
    nstates: Incomplete
    singlet: Incomplete
    lindep: Incomplete
    level_shift: Incomplete
    max_cycle: Incomplete
    positive_eig_threshold: Incomplete
    deg_eia_thresh: Incomplete
    exclude_nlc: bool
    verbose: Incomplete
    stdout: Incomplete
    mol: Incomplete
    max_memory: Incomplete
    chkfile: Incomplete
    frozen: Incomplete
    wfnsym: Incomplete
    converged: Incomplete
    e: Incomplete
    xy: Incomplete
    def __init__(self, mf, frozen=None) -> None: ...
    @property
    def nroots(self): ...
    @nroots.setter
    def nroots(self, x) -> None: ...
    def set_frozen(self, method: str = 'auto', window=(-1000.0, 1000.0)): ...
    @property
    def e_tot(self): ...
    def dump_flags(self, verbose=None) -> None: ...
    def reset(self, mol=None): ...
    get_frozen_mask = get_frozen_mask
    def gen_vind(self, mf=None) -> None: ...
    def gen_response(self, *args, **kwargs): ...
    def get_ab(self, mf=None, frozen=None): ...
    def get_precond(self, hdiag): ...
    analyze = analyze
    get_nto = get_nto
    oscillator_strength = oscillator_strength
    transition_dipole = transition_dipole
    transition_quadrupole = transition_quadrupole
    transition_octupole = transition_octupole
    transition_velocity_dipole = transition_velocity_dipole
    transition_velocity_quadrupole = transition_velocity_quadrupole
    transition_velocity_octupole = transition_velocity_octupole
    transition_magnetic_dipole = transition_magnetic_dipole
    transition_magnetic_quadrupole = transition_magnetic_quadrupole
    dipole_spectral_function = dipole_spectral_function
    photoabsorption_cross_section = photoabsorption_cross_section
    as_scanner = as_scanner
    def Gradients(self) -> None: ...
    def nuc_grad_method(self): ...
    def to_gpu(self) -> None: ...

class TDA(TDBase):
    def gen_vind(self, mf=None): ...
    def get_init_guess(self, mf, nstates=None, wfnsym=None, return_symmetry: bool = False): ...
    def init_guess(self, mf, nstates=None, wfnsym=None, return_symmetry: bool = False): ...
    nstates: Incomplete
    xy: Incomplete
    def kernel(self, x0=None, nstates=None): ...
    def Gradients(self): ...
    def to_gpu(self): ...
CIS = TDA

def gen_tdhf_operation(mf, fock_ao=None, singlet: bool = True, wfnsym=None, with_nlc: bool = True): ...

class TDHF(TDBase):
    def gen_vind(self, mf=None): ...
    def get_init_guess(self, mf, nstates=None, wfnsym=None, return_symmetry: bool = False): ...
    nstates: Incomplete
    xy: Incomplete
    def kernel(self, x0=None, nstates=None): ...
    Gradients: Incomplete
    def to_gpu(self): ...
RPA = TDHF
TDRHF = TDHF
