from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, lib as lib, scf as scf, symm as symm
from pyscf.data import nist as nist
from pyscf.lib import logger as logger
from pyscf.scf import uhf_symm as uhf_symm
from pyscf.tdscf import rhf as rhf
from pyscf.tdscf._lr_eig import real_eig as real_eig

OUTPUT_THRESHOLD: Incomplete
REAL_EIG_THRESHOLD: Incomplete
MO_BASE: Incomplete

def gen_tda_operation(mf, fock_ao=None, wfnsym=None, with_nlc: bool = True): ...
gen_tda_hop = gen_tda_operation

def get_frozen_mask(td): ...
def get_ab(mf, frozen=None, mo_energy=None, mo_coeff=None, mo_occ=None): ...
def get_nto(tdobj, state: int = 1, threshold=..., verbose=None): ...
def analyze(tdobj, verbose=None): ...

class TDBase(rhf.TDBase):
    def get_ab(self, mf=None, frozen=None): ...
    get_frozen_mask = get_frozen_mask
    analyze = analyze
    get_nto = get_nto

class TDA(TDBase):
    singlet: Incomplete
    def gen_vind(self, mf=None): ...
    def get_init_guess(self, mf, nstates=None, wfnsym=None, return_symmetry: bool = False): ...
    nstates: Incomplete
    xy: Incomplete
    def kernel(self, x0=None, nstates=None): ...
    def Gradients(self): ...
    def to_gpu(self): ...
CIS = TDA

def gen_tdhf_operation(mf, fock_ao=None, wfnsym=None, with_nlc: bool = True): ...

class TDHF(TDBase):
    singlet: Incomplete
    def gen_vind(self, mf=None): ...
    def get_init_guess(self, mf, nstates=None, wfnsym=None, return_symmetry: bool = False): ...
    nstates: Incomplete
    xy: Incomplete
    def kernel(self, x0=None, nstates=None): ...
    Gradients: Incomplete
    def to_gpu(self): ...
RPA = TDHF
TDUHF = TDHF
