from _typeshed import Incomplete
from pyscf import dft as dft, gto as gto, hessian as hessian, scf as scf
from pyscf.data.nist import MP_ME as MP_ME
from pyscf.lib import logger as logger

CUTOFF_FREQUENCY: Incomplete
KEEP_IMAG_FREQUENCY: Incomplete

def run_mfs(mf, mols_a, mols_b): ...
def get_mode(mf, cutoff_frequency=..., keep_imag_frequency=...): ...
def gen_moles(mol, disp): ...
def get_vmat(mf, mfset, disp): ...
def kernel(mf, disp: float = 0.0001, mo_rep: bool = False, cutoff_frequency=..., keep_imag_frequency=...): ...
