from pyscf.pbc import gto as gto
from pyscf.pbc.dft import gks as gks, kgks as kgks, krks as krks, krks_ksymm as krks_ksymm, krkspu as krkspu, krkspu_ksymm as krkspu_ksymm, kroks as kroks, kuks as kuks, kuks_ksymm as kuks_ksymm, kukspu as kukspu, kukspu_ksymm as kukspu_ksymm, rks as rks, roks as roks, uks as uks
from pyscf.pbc.dft.gen_grid import BeckeGrids as BeckeGrids, UniformGrids as UniformGrids
from pyscf.pbc.dft.rks import KohnShamDFT as KohnShamDFT

def KRKS(cell, *args, **kwargs): ...
def KUKS(cell, *args, **kwargs): ...
KROKS = kroks.KROKS
KGKS = kgks.KGKS

def KRKSpU(cell, *args, **kwargs): ...
def KUKSpU(cell, *args, **kwargs): ...
def RKS(cell, *args, **kwargs): ...
def UKS(cell, *args, **kwargs): ...
def GKS(cell, *args, **kwargs): ...
def ROKS(cell, *args, **kwargs): ...
def KS(cell, *args, **kwargs): ...
def KKS(cell, *args, **kwargs): ...
