from pyscf.pbc import gto as gto
from pyscf.pbc.dft import gks as gks, kgks as kgks, krks as krks, krks_ksymm as krks_ksymm, krkspu as krkspu, krkspu_ksymm as krkspu_ksymm, kroks as kroks, kuks as kuks, kuks_ksymm as kuks_ksymm, kukspu as kukspu, kukspu_ksymm as kukspu_ksymm, rks as rks, roks as roks, uks as uks
from pyscf.pbc.dft.gen_grid import BeckeGrids as BeckeGrids, UniformGrids as UniformGrids
from pyscf.pbc.dft.rks import RKS, KohnShamDFT as KohnShamDFT
from pyscf.pbc.dft.gks import GKS
from pyscf.pbc.dft.krks import KRKS
from pyscf.pbc.dft.krks_ksymm import KsymAdaptedKRKS
from pyscf.pbc.dft.krkspu import KRKSpU
from pyscf.pbc.dft.krkspu_ksymm import KsymAdaptedKRKSpU
from pyscf.pbc.dft.kuks import KUKS
from pyscf.pbc.dft.kuks_ksymm import KsymAdaptedKUKS
from pyscf.pbc.dft.kukspu import KUKSpU
from pyscf.pbc.dft.kukspu_ksymm import KsymAdaptedKUKSpU
from pyscf.pbc.dft.roks import ROKS
from pyscf.pbc.dft.uks import UKS
from pyscf.pbc.gto.cell import Cell
from typing import Union

def KRKS(cell: Cell, *args, **kwargs) -> Union[KRKS, KsymAdaptedKRKS]: ...
def KUKS(cell: Cell, *args, **kwargs) -> Union[KsymAdaptedKUKS, KUKS]: ...
KROKS = kroks.KROKS
KGKS = kgks.KGKS

def KRKSpU(cell: Cell, *args, **kwargs) -> Union[KsymAdaptedKRKSpU, KRKSpU]: ...
def KUKSpU(cell: Cell, *args, **kwargs) -> Union[KUKSpU, KsymAdaptedKUKSpU]: ...
def RKS(cell: Cell, *args, **kwargs) -> Union[ROKS, RKS]: ...
def UKS(cell: Cell, *args, **kwargs) -> UKS: ...
def GKS(cell: Cell, *args, **kwargs) -> GKS: ...
def ROKS(cell: Cell, *args, **kwargs) -> ROKS: ...
def KS(cell: Cell, *args, **kwargs) -> Union[UKS, RKS]: ...
def KKS(cell: Cell, *args, **kwargs) -> Union[KRKS, KsymAdaptedKRKS, KUKS]: ...
