from _typeshed import Incomplete
from pyscf import dft as dft, lib as lib
from pyscf.dft.gen_grid import BLKSIZE as BLKSIZE, CUTOFF as CUTOFF, NBINS as NBINS, gen_atomic_grids as gen_atomic_grids, nwchem_prune as nwchem_prune, original_becke as original_becke, sg1_prune as sg1_prune, stratmann as stratmann, treutler_prune as treutler_prune
from pyscf.lib import logger as logger
from pyscf.pbc.gto.cell import Cell, gen_uniform_grids as gen_uniform_grids, get_uniform_grids as get_uniform_grids
from numpy import int64, ndarray
from typing import Callable, Dict, Optional, Tuple

libpbc: Incomplete

def make_mask(cell: Cell, coords: ndarray, relativity: int = 0, shls_slice: None=None, cutoff: None=None, verbose: None=None) -> ndarray: ...

class UniformGrids(lib.StreamObject):
    cutoff = CUTOFF
    cell: Incomplete
    stdout: Incomplete
    verbose: Incomplete
    mesh: Incomplete
    non0tab: Incomplete
    def __init__(self, cell: Cell) -> None: ...
    @property
    def coords(self): ...
    @coords.setter
    def coords(self, x) -> None: ...
    @property
    def weights(self): ...
    @weights.setter
    def weights(self, x) -> None: ...
    @property
    def size(self) -> int64: ...
    def build(self, cell: None=None, with_non0tab: bool = False) -> "UniformGrids": ...
    def reset(self, cell: Optional[Cell]=None) -> "UniformGrids": ...
    def dump_flags(self, verbose: None=None) -> "UniformGrids": ...
    def kernel(self, cell=None, with_non0tab: bool = False): ...
    def make_mask(self, cell: Optional[Cell]=None, coords: Optional[ndarray]=None, relativity: int = 0, shls_slice: None=None, verbose: None=None) -> ndarray: ...
    to_gpu = lib.to_gpu

def get_becke_grids(cell: Cell, atom_grid: Dict[str, Tuple[int, int]]={}, radi_method: Callable=..., level: int = 3, prune: Callable=...) -> Tuple[ndarray, ndarray]: ...
gen_becke_grids = get_becke_grids

class BeckeGrids(dft.gen_grid.Grids):
    cell: Incomplete
    def __init__(self, cell: Cell) -> None: ...
    non0tab: Incomplete
    def build(self, cell: None=None, with_non0tab: bool = False) -> "BeckeGrids": ...
    def make_mask(self, cell: Optional[Cell]=None, coords: Optional[ndarray]=None, relativity: int = 0, shls_slice: None=None, verbose: None=None) -> ndarray: ...
    to_gpu = lib.to_gpu
AtomicGrids = BeckeGrids
