from _typeshed import Incomplete
from pyscf import dft as dft, lib as lib
from pyscf.dft.gen_grid import BLKSIZE as BLKSIZE, CUTOFF as CUTOFF, NBINS as NBINS, gen_atomic_grids as gen_atomic_grids, nwchem_prune as nwchem_prune, original_becke as original_becke, sg1_prune as sg1_prune, stratmann as stratmann, treutler_prune as treutler_prune
from pyscf.lib import logger as logger
from pyscf.pbc.gto.cell import gen_uniform_grids as gen_uniform_grids, get_uniform_grids as get_uniform_grids

libpbc: Incomplete

def make_mask(cell, coords, relativity: int = 0, shls_slice=None, cutoff=None, verbose=None): ...

class UniformGrids(lib.StreamObject):
    cutoff = CUTOFF
    cell: Incomplete
    stdout: Incomplete
    verbose: Incomplete
    mesh: Incomplete
    non0tab: Incomplete
    def __init__(self, cell) -> None: ...
    @property
    def coords(self): ...
    @coords.setter
    def coords(self, x) -> None: ...
    @property
    def weights(self): ...
    @weights.setter
    def weights(self, x) -> None: ...
    @property
    def size(self): ...
    def build(self, cell=None, with_non0tab: bool = False): ...
    def reset(self, cell=None): ...
    def dump_flags(self, verbose=None): ...
    def kernel(self, cell=None, with_non0tab: bool = False): ...
    def make_mask(self, cell=None, coords=None, relativity: int = 0, shls_slice=None, verbose=None): ...
    to_gpu = lib.to_gpu

def get_becke_grids(cell, atom_grid={}, radi_method=..., level: int = 3, prune=...): ...
gen_becke_grids = get_becke_grids

class BeckeGrids(dft.gen_grid.Grids):
    cell: Incomplete
    def __init__(self, cell) -> None: ...
    non0tab: Incomplete
    def build(self, cell=None, with_non0tab: bool = False): ...
    def make_mask(self, cell=None, coords=None, relativity: int = 0, shls_slice=None, verbose=None): ...
    to_gpu = lib.to_gpu
AtomicGrids = BeckeGrids
