from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc.dft import gen_grid as gen_grid, multigrid as multigrid, rks as rks
from pyscf.pbc.dft.numint2c import NumInt2C as NumInt2C
from pyscf.pbc.scf import ghf as pbcghf

def get_veff(ks, cell=None, dm=None, dm_last: int = 0, vhf_last: int = 0, hermi: int = 1, kpt=None, kpts_band=None): ...

class GKS(rks.KohnShamDFT, pbcghf.GHF):
    collinear: Incomplete
    spin_samples: Incomplete
    get_veff = get_veff
    energy_elec: Incomplete
    def __init__(self, cell, kpt=None, xc: str = 'LDA,VWN', exxdiv=...) -> None: ...
    def dump_flags(self, verbose=None): ...
    def x2c1e(self): ...
    x2c = x2c1e
    def stability(self) -> None: ...
    def nuc_grad_method(self) -> None: ...
    def to_hf(self): ...
    to_gpu = lib.to_gpu
