from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc.dft import gen_grid as gen_grid, multigrid as multigrid, rks as rks
from pyscf.pbc.scf import khf as khf

def get_veff(ks, cell=None, dm=None, dm_last: int = 0, vhf_last: int = 0, hermi: int = 1, kpts=None, kpts_band=None): ...
def get_rho(mf, dm=None, grids=None, kpts=None): ...
def energy_elec(mf, dm_kpts=None, h1e_kpts=None, vhf=None): ...
def gen_response(mf, mo_coeff=None, mo_occ=None, singlet=None, hermi: int = 0, max_memory=None, with_nlc: bool = True): ...

class KRKS(rks.KohnShamDFT, khf.KRHF):
    get_veff = get_veff
    energy_elec = energy_elec
    get_rho = get_rho
    gen_response = gen_response
    def __init__(self, cell, kpts=None, xc: str = 'LDA,VWN', exxdiv=...) -> None: ...
    def dump_flags(self, verbose=None): ...
    def Gradients(self): ...
    def to_hf(self): ...
    def multigrid_numint(self, mesh=None): ...
    to_gpu = lib.to_gpu
