from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import lib as lib
from pyscf.dft import numint as numint
from pyscf.dft.gen_grid import ALIGNMENT_UNIT as ALIGNMENT_UNIT, CUTOFF as CUTOFF, NBINS as NBINS
from pyscf.dft.numint import OCCDROP as OCCDROP, eval_mat as eval_mat
from pyscf.pbc.dft.gen_grid import BeckeGrids, UniformGrids, BLKSIZE as BLKSIZE, make_mask as make_mask
from pyscf.pbc.lib.kpts import KPoints, KPoints as KPoints
from pyscf.pbc.lib.kpts_helper import KPT_DIFF_TOL as KPT_DIFF_TOL, is_zero as is_zero
from numpy import float64, ndarray
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.gto.cell import Cell
from typing import Callable, Iterator, List, Optional, Tuple, Union

def eval_ao(cell: Cell, coords: ndarray, kpt: ndarray=..., deriv: int = 0, relativity: int = 0, shls_slice: Optional[Tuple[int, int]]=None, non0tab: Optional[ndarray]=None, cutoff: Optional[float]=None, out: None=None, verbose: None=None) -> ndarray: ...
def eval_ao_kpts(cell: Cell, coords: ndarray, kpts: Optional[ndarray]=None, deriv: int = 0, relativity: int = 0, shls_slice: Optional[Tuple[int, int]]=None, non0tab: Optional[ndarray]=None, cutoff: Optional[float]=None, out: None=None, verbose: None=None, **kwargs) -> List[ndarray]: ...
def eval_rho(cell: Cell, ao: ndarray, dm: ndarray, non0tab: Optional[ndarray]=None, xctype: str = 'LDA', hermi: int = 0, with_lapl: bool = True, verbose: None=None) -> ndarray: ...
def eval_rho2(cell: Cell, ao: ndarray, mo_coeff: Union[ndarray, NPArrayWithTag], mo_occ: ndarray, non0tab: Optional[ndarray]=None, xctype: str = 'LDA', with_lapl: bool = True, verbose: None=None) -> ndarray: ...
def nr_rks(ni: Union[KNumInt, NumInt], cell: Cell, grids: Union[UniformGrids, BeckeGrids], xc_code: str, dms: Union[ndarray, NPArrayWithTag, List[ndarray]], spin: int = 0, relativity: int = 0, hermi: int = 1, kpts: Optional[Union[ndarray, KPoints]]=None, kpts_band: Optional[ndarray]=None, max_memory: Union[float, int] = 2000, verbose: None=None) -> Union[Tuple[float64, float64, ndarray], Tuple[int, int, int], Tuple[ndarray, ndarray, ndarray]]: ...
def nr_uks(ni: Union[KNumInt, NumInt], cell: Cell, grids: Union[UniformGrids, BeckeGrids], xc_code: str, dms: Union[ndarray, NPArrayWithTag, Tuple[ndarray, ndarray]], spin: int = 1, relativity: int = 0, hermi: int = 1, kpts: Optional[Union[ndarray, KPoints]]=None, kpts_band: Optional[ndarray]=None, max_memory: Union[float, int] = 2000, verbose: None=None) -> Union[Tuple[ndarray, float64, ndarray], Tuple[int, int, ndarray]]: ...
nr_rks_vxc = nr_rks
nr_uks_vxc = nr_uks

def nr_nlc_vxc(ni: Union[KNumInt, NumInt], cell: Cell, grids: Union[UniformGrids, BeckeGrids], xc_code: str, dms: ndarray, relativity: int = 0, hermi: int = 1, kpts: Optional[ndarray]=None, kpts_band: None=None, max_memory: int = 2000, verbose: None=None) -> Tuple[float64, float64, ndarray]: ...
def nr_rks_fxc(ni: Union[KNumInt, NumInt], cell: Cell, grids: Union[UniformGrids, BeckeGrids], xc_code: str, dm0: Optional[ndarray], dms: ndarray, relativity: int = 0, hermi: int = 0, rho0: Optional[ndarray]=None, vxc: Optional[ndarray]=None, fxc: Optional[ndarray]=None, kpts: Optional[Union[ndarray, KPoints]]=None, max_memory: Union[float, int] = 2000, verbose: None=None) -> ndarray: ...
def nr_rks_fxc_st(ni: Union[KNumInt, NumInt], cell: Cell, grids: Union[UniformGrids, BeckeGrids], xc_code: str, dm0: Optional[ndarray], dms_alpha: ndarray, hermi: int = 0, singlet: bool = True, rho0: Optional[ndarray]=None, vxc: Optional[ndarray]=None, fxc: Optional[ndarray]=None, kpts: Optional[ndarray]=None, max_memory: Union[float, int] = 2000, verbose: None=None) -> ndarray: ...
def nr_uks_fxc(ni: Union[KNumInt, NumInt], cell: Cell, grids: Union[UniformGrids, BeckeGrids], xc_code: str, dm0: Optional[Union[Tuple[ndarray, ndarray], ndarray]], dms: Union[ndarray, Tuple[ndarray, ndarray]], relativity: int = 0, hermi: int = 0, rho0: Optional[ndarray]=None, vxc: Optional[ndarray]=None, fxc: Optional[ndarray]=None, kpts: Optional[ndarray]=None, max_memory: Union[float, int] = 2000, verbose: None=None) -> ndarray: ...
def cache_xc_kernel(ni: Union[KNumInt, NumInt], cell: Cell, grids: Union[UniformGrids, BeckeGrids], xc_code: str, mo_coeff: Union[ndarray, Tuple[ndarray, ndarray]], mo_occ: Union[ndarray, Tuple[ndarray, ndarray]], spin: int = 0, kpts: Optional[Union[ndarray, KPoints]]=None, max_memory: int = 2000) -> Tuple[ndarray, ndarray, ndarray]: ...
def cache_xc_kernel1(ni: Union[KNumInt, NumInt], cell: Cell, grids: UniformGrids, xc_code: str, dm: Union[ndarray, Tuple[ndarray, ndarray]], spin: int = 0, kpts: Optional[ndarray]=None, max_memory: int = 2000) -> Tuple[ndarray, ndarray, ndarray]: ...
def get_rho(ni: Union[KNumInt, NumInt], cell: Cell, dm: Union[ndarray, NPArrayWithTag], grids: UniformGrids, kpts: Optional[Union[ndarray, KPoints]]=None, max_memory: int = 2000) -> ndarray: ...

class NumInt(lib.StreamObject, numint.LibXCMixin):
    cutoff: Incomplete
    def reset(self, cell: Optional[Cell]=None) -> "NumInt": ...
    def nr_vxc(self, cell, grids, xc_code, dms, spin: int = 0, relativity: int = 0, hermi: int = 1, kpt=None, kpts_band=None, max_memory: int = 2000, verbose=None): ...
    get_vxc = nr_vxc
    def nr_rks(self, cell: Cell, grids: Union[UniformGrids, BeckeGrids], xc_code: str, dms: Union[ndarray, NPArrayWithTag], relativity: int = 0, hermi: int = 1, kpt: ndarray=..., kpts_band: None=None, max_memory: Union[float, int] = 2000, verbose: None=None) -> Tuple[float64, float64, ndarray]: ...
    def nr_uks(self, cell: Cell, grids: Union[UniformGrids, BeckeGrids], xc_code: str, dms: Union[ndarray, NPArrayWithTag, Tuple[ndarray, ndarray]], relativity: int = 0, hermi: int = 1, kpt: ndarray=..., kpts_band: None=None, max_memory: Union[float, int] = 2000, verbose: None=None) -> Tuple[ndarray, float64, ndarray]: ...
    def nr_fxc(self, cell, grids, xc_code, dm0, dms, spin: int = 0, relativity: int = 0, hermi: int = 0, rho0=None, vxc=None, fxc=None, kpt=None, max_memory: int = 2000, verbose=None): ...
    get_fxc = nr_fxc
    def cache_xc_kernel(self, cell: Cell, grids: Union[UniformGrids, BeckeGrids], xc_code: str, mo_coeff: Union[ndarray, Tuple[ndarray, ndarray]], mo_occ: Union[ndarray, Tuple[ndarray, ndarray]], spin: int = 0, kpt: Optional[ndarray]=None, max_memory: int = 2000) -> Tuple[ndarray, ndarray, ndarray]: ...
    def cache_xc_kernel1(self, cell: Cell, grids: UniformGrids, xc_code: str, dm: ndarray, spin: int = 0, kpt: None=None, max_memory: int = 2000) -> Tuple[ndarray, ndarray, ndarray]: ...
    def block_loop(self, cell: Cell, grids: Union[UniformGrids, BeckeGrids], nao: Optional[int]=None, deriv: int = 0, kpt: Optional[ndarray]=None, kpts_band: None=None, max_memory: Union[float, int] = 2000, non0tab: None=None, blksize: None=None) -> Iterator[Tuple[ndarray, ndarray, ndarray, ndarray, ndarray]]: ...
    nr_rks_fxc = nr_rks_fxc
    nr_uks_fxc = nr_uks_fxc
    nr_rks_fxc_st = nr_rks_fxc_st
    nr_nlc_vxc = nr_nlc_vxc
    make_mask: Incomplete
    eval_ao: Incomplete
    eval_rho: Incomplete
    eval_rho2: Incomplete
    get_rho = get_rho
    def eval_rho1(self, cell: Cell, ao: ndarray, dm: ndarray, screen_index: Optional[ndarray]=None, xctype: str = 'LDA', hermi: int = 0, with_lapl: bool = True, cutoff: None=None, ao_cutoff: None=None, verbose: None=None) -> ndarray: ...
    def to_gpu(self): ...

class KNumInt(lib.StreamObject, numint.LibXCMixin):
    def __init__(self, *args, **kwargs) -> None: ...
    def reset(self, cell: Optional[Cell]=None) -> "KNumInt": ...
    eval_ao: Incomplete
    def make_mask(self, cell, coords, relativity: int = 0, shls_slice=None, verbose=None): ...
    def eval_rho(self, cell: Cell, ao_kpts: List[ndarray], dm_kpts: ndarray, non0tab: Optional[ndarray]=None, xctype: str = 'LDA', hermi: int = 0, with_lapl: bool = True, verbose: None=None) -> ndarray: ...
    def eval_rho1(self, cell: Cell, ao_kpts: List[ndarray], dm_kpts: ndarray, non0tab: Optional[ndarray]=None, xctype: str = 'LDA', hermi: int = 0, with_lapl: bool = True, cutoff: float=..., grids: None=None, verbose: None=None) -> ndarray: ...
    def eval_rho2(self, cell: Cell, ao_kpts: Union[ndarray, List[ndarray]], mo_coeff_kpts: Union[ndarray, List[Union[NPArrayWithTag, ndarray]], List[ndarray]], mo_occ_kpts: Union[ndarray, List[ndarray]], non0tab: Optional[ndarray]=None, xctype: str = 'LDA', with_lapl: bool = True, verbose: None=None) -> ndarray: ...
    def nr_vxc(self, cell, grids, xc_code, dms, spin: int = 0, relativity: int = 0, hermi: int = 1, kpts=None, kpts_band=None, max_memory: int = 2000, verbose=None): ...
    get_vxc = nr_vxc
    def nr_rks(self, cell: Cell, grids: Union[UniformGrids, BeckeGrids], xc_code: str, dms: Union[ndarray, NPArrayWithTag, List[ndarray]], relativity: int = 0, hermi: int = 1, kpts: Optional[Union[ndarray, KPoints]]=None, kpts_band: Optional[ndarray]=None, max_memory: Union[float, int] = 2000, verbose: None=None, **kwargs) -> Union[Tuple[float64, float64, ndarray], Tuple[int, int, int], Tuple[ndarray, ndarray, ndarray]]: ...
    def nr_uks(self, cell: Cell, grids: Union[UniformGrids, BeckeGrids], xc_code: str, dms: Union[ndarray, NPArrayWithTag, Tuple[ndarray, ndarray]], relativity: int = 0, hermi: int = 1, kpts: Optional[Union[ndarray, KPoints]]=None, kpts_band: Optional[ndarray]=None, max_memory: Union[float, int] = 2000, verbose: None=None, **kwargs) -> Union[Tuple[ndarray, float64, ndarray], Tuple[int, int, ndarray]]: ...
    def nr_fxc(self, cell, grids, xc_code, dm0, dms, spin: int = 0, relativity: int = 0, hermi: int = 0, rho0=None, vxc=None, fxc=None, kpts=None, max_memory: int = 2000, verbose=None): ...
    get_fxc = nr_fxc
    def block_loop(self, cell: Cell, grids: Union[UniformGrids, BeckeGrids], nao: Optional[int]=None, deriv: int = 0, kpts: Optional[ndarray]=None, kpts_band: Optional[ndarray]=None, max_memory: Union[float, int] = 2000, non0tab: None=None, blksize: None=None) -> Iterator[Tuple[List[ndarray], List[ndarray], ndarray, ndarray, ndarray]]: ...
    nr_rks_fxc = nr_rks_fxc
    nr_uks_fxc = nr_uks_fxc
    nr_rks_fxc_st = nr_rks_fxc_st
    cache_xc_kernel = cache_xc_kernel
    cache_xc_kernel1 = cache_xc_kernel1
    get_rho = get_rho
    def to_gpu(self): ...
