from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import lib as lib
from pyscf.dft import numint as numint
from pyscf.dft.gen_grid import ALIGNMENT_UNIT as ALIGNMENT_UNIT, CUTOFF as CUTOFF, NBINS as NBINS
from pyscf.dft.numint import OCCDROP as OCCDROP, eval_mat as eval_mat
from pyscf.pbc.dft.gen_grid import BLKSIZE as BLKSIZE, make_mask as make_mask
from pyscf.pbc.lib.kpts import KPoints as KPoints
from pyscf.pbc.lib.kpts_helper import KPT_DIFF_TOL as KPT_DIFF_TOL, is_zero as is_zero

def eval_ao(cell, coords, kpt=..., deriv: int = 0, relativity: int = 0, shls_slice=None, non0tab=None, cutoff=None, out=None, verbose=None): ...
def eval_ao_kpts(cell, coords, kpts=None, deriv: int = 0, relativity: int = 0, shls_slice=None, non0tab=None, cutoff=None, out=None, verbose=None, **kwargs): ...
def eval_rho(cell, ao, dm, non0tab=None, xctype: str = 'LDA', hermi: int = 0, with_lapl: bool = True, verbose=None): ...
def eval_rho2(cell, ao, mo_coeff, mo_occ, non0tab=None, xctype: str = 'LDA', with_lapl: bool = True, verbose=None): ...
def nr_rks(ni, cell, grids, xc_code, dms, spin: int = 0, relativity: int = 0, hermi: int = 1, kpts=None, kpts_band=None, max_memory: int = 2000, verbose=None): ...
def nr_uks(ni, cell, grids, xc_code, dms, spin: int = 1, relativity: int = 0, hermi: int = 1, kpts=None, kpts_band=None, max_memory: int = 2000, verbose=None): ...
nr_rks_vxc = nr_rks
nr_uks_vxc = nr_uks

def nr_nlc_vxc(ni, cell, grids, xc_code, dms, relativity: int = 0, hermi: int = 1, kpts=None, kpts_band=None, max_memory: int = 2000, verbose=None): ...
def nr_rks_fxc(ni, cell, grids, xc_code, dm0, dms, relativity: int = 0, hermi: int = 0, rho0=None, vxc=None, fxc=None, kpts=None, max_memory: int = 2000, verbose=None): ...
def nr_rks_fxc_st(ni, cell, grids, xc_code, dm0, dms_alpha, hermi: int = 0, singlet: bool = True, rho0=None, vxc=None, fxc=None, kpts=None, max_memory: int = 2000, verbose=None): ...
def nr_uks_fxc(ni, cell, grids, xc_code, dm0, dms, relativity: int = 0, hermi: int = 0, rho0=None, vxc=None, fxc=None, kpts=None, max_memory: int = 2000, verbose=None): ...
def cache_xc_kernel(ni, cell, grids, xc_code, mo_coeff, mo_occ, spin: int = 0, kpts=None, max_memory: int = 2000): ...
def cache_xc_kernel1(ni, cell, grids, xc_code, dm, spin: int = 0, kpts=None, max_memory: int = 2000): ...
def get_rho(ni, cell, dm, grids, kpts=None, max_memory: int = 2000): ...

class NumInt(lib.StreamObject, numint.LibXCMixin):
    cutoff: Incomplete
    def reset(self, cell=None): ...
    def nr_vxc(self, cell, grids, xc_code, dms, spin: int = 0, relativity: int = 0, hermi: int = 1, kpt=None, kpts_band=None, max_memory: int = 2000, verbose=None): ...
    get_vxc = nr_vxc
    def nr_rks(self, cell, grids, xc_code, dms, relativity: int = 0, hermi: int = 1, kpt=..., kpts_band=None, max_memory: int = 2000, verbose=None): ...
    def nr_uks(self, cell, grids, xc_code, dms, relativity: int = 0, hermi: int = 1, kpt=..., kpts_band=None, max_memory: int = 2000, verbose=None): ...
    def nr_fxc(self, cell, grids, xc_code, dm0, dms, spin: int = 0, relativity: int = 0, hermi: int = 0, rho0=None, vxc=None, fxc=None, kpt=None, max_memory: int = 2000, verbose=None): ...
    get_fxc = nr_fxc
    def cache_xc_kernel(self, cell, grids, xc_code, mo_coeff, mo_occ, spin: int = 0, kpt=None, max_memory: int = 2000): ...
    def cache_xc_kernel1(self, cell, grids, xc_code, dm, spin: int = 0, kpt=None, max_memory: int = 2000): ...
    def block_loop(self, cell, grids, nao=None, deriv: int = 0, kpt=None, kpts_band=None, max_memory: int = 2000, non0tab=None, blksize=None) -> Generator[Incomplete]: ...
    nr_rks_fxc = nr_rks_fxc
    nr_uks_fxc = nr_uks_fxc
    nr_rks_fxc_st = nr_rks_fxc_st
    nr_nlc_vxc = nr_nlc_vxc
    make_mask: Incomplete
    eval_ao: Incomplete
    eval_rho: Incomplete
    eval_rho2: Incomplete
    get_rho = get_rho
    def eval_rho1(self, cell, ao, dm, screen_index=None, xctype: str = 'LDA', hermi: int = 0, with_lapl: bool = True, cutoff=None, ao_cutoff=None, verbose=None): ...
    def to_gpu(self): ...

class KNumInt(lib.StreamObject, numint.LibXCMixin):
    def __init__(self, *args, **kwargs) -> None: ...
    def reset(self, cell=None): ...
    eval_ao: Incomplete
    def make_mask(self, cell, coords, relativity: int = 0, shls_slice=None, verbose=None): ...
    def eval_rho(self, cell, ao_kpts, dm_kpts, non0tab=None, xctype: str = 'LDA', hermi: int = 0, with_lapl: bool = True, verbose=None): ...
    def eval_rho1(self, cell, ao_kpts, dm_kpts, non0tab=None, xctype: str = 'LDA', hermi: int = 0, with_lapl: bool = True, cutoff=..., grids=None, verbose=None): ...
    def eval_rho2(self, cell, ao_kpts, mo_coeff_kpts, mo_occ_kpts, non0tab=None, xctype: str = 'LDA', with_lapl: bool = True, verbose=None): ...
    def nr_vxc(self, cell, grids, xc_code, dms, spin: int = 0, relativity: int = 0, hermi: int = 1, kpts=None, kpts_band=None, max_memory: int = 2000, verbose=None): ...
    get_vxc = nr_vxc
    def nr_rks(self, cell, grids, xc_code, dms, relativity: int = 0, hermi: int = 1, kpts=None, kpts_band=None, max_memory: int = 2000, verbose=None, **kwargs): ...
    def nr_uks(self, cell, grids, xc_code, dms, relativity: int = 0, hermi: int = 1, kpts=None, kpts_band=None, max_memory: int = 2000, verbose=None, **kwargs): ...
    def nr_fxc(self, cell, grids, xc_code, dm0, dms, spin: int = 0, relativity: int = 0, hermi: int = 0, rho0=None, vxc=None, fxc=None, kpts=None, max_memory: int = 2000, verbose=None): ...
    get_fxc = nr_fxc
    def block_loop(self, cell, grids, nao=None, deriv: int = 0, kpts=None, kpts_band=None, max_memory: int = 2000, non0tab=None, blksize=None) -> Generator[Incomplete]: ...
    nr_rks_fxc = nr_rks_fxc
    nr_uks_fxc = nr_uks_fxc
    nr_rks_fxc_st = nr_rks_fxc_st
    cache_xc_kernel = cache_xc_kernel
    cache_xc_kernel1 = cache_xc_kernel1
    get_rho = get_rho
    def to_gpu(self): ...
