from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.dft import rks as mol_ks
from pyscf.lib import logger as logger
from pyscf.pbc.dft import gen_grid as gen_grid, multigrid as multigrid, numint as numint
from pyscf.pbc.lib.kpts import KPoints as KPoints
from pyscf.pbc.scf import addons as addons, hf as pbchf, khf as khf

def get_veff(ks, cell=None, dm=None, dm_last: int = 0, vhf_last: int = 0, hermi: int = 1, kpt=None, kpts_band=None): ...

NELEC_ERROR_TOL: Incomplete

def prune_small_rho_grids_(ks, cell, dm, grids, kpts): ...
def get_rho(mf, dm=None, grids=None, kpt=None): ...
def gen_response(mf, mo_coeff=None, mo_occ=None, singlet=None, hermi: int = 0, max_memory=None, with_nlc: bool = True): ...

class KohnShamDFT(mol_ks.KohnShamDFT):
    small_rho_cutoff: Incomplete
    get_rho = get_rho
    density_fit: Incomplete
    rs_density_fit: Incomplete
    mix_density_fit: Incomplete
    gen_response = NotImplemented
    xc: Incomplete
    grids: Incomplete
    nlc: str
    nlcgrids: Incomplete
    def __init__(self, xc: str = 'LDA,VWN') -> None: ...
    def dump_flags(self, verbose=None): ...
    def reset(self, cell=None): ...
    kpts: Incomplete
    kpt: Incomplete
    rsjk: Incomplete
    def build(self, cell=None): ...
    def jk_method(self, J: str = 'FFTDF', K=None): ...
    def to_rks(self, xc=None): ...
    def to_uks(self, xc=None): ...
    def to_gks(self, xc=None): ...
    def to_hf(self) -> None: ...
    def initialize_grids(self, cell, dm, kpts, ground_state: bool = True): ...
    def to_gpu(self) -> None: ...

class RKS(KohnShamDFT, pbchf.RHF):
    get_vsap = mol_ks.get_vsap
    init_guess_by_vsap = mol_ks.init_guess_by_vsap
    get_veff = get_veff
    energy_elec = mol_ks.energy_elec
    gen_response = gen_response
    def __init__(self, cell, kpt=None, xc: str = 'LDA,VWN', exxdiv=...) -> None: ...
    def dump_flags(self, verbose=None): ...
    def to_hf(self): ...
    def multigrid_numint(self, mesh=None): ...
    def Gradients(self): ...
    to_gpu = lib.to_gpu
