from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.dft import rks as mol_ks
from pyscf.lib import logger as logger
from pyscf.pbc.dft import gen_grid as gen_grid, multigrid as multigrid, numint as numint
from pyscf.pbc.lib.kpts import KPoints, KPoints as KPoints
from pyscf.pbc.scf import addons as addons, hf as pbchf, khf as khf
from numpy import ndarray
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.dft.krks import KRKS
from pyscf.pbc.dft.krks_ksymm import KsymAdaptedKRKS
from pyscf.pbc.dft.kuks import KUKS
from pyscf.pbc.dft.kuks_ksymm import KsymAdaptedKUKS
from pyscf.pbc.dft.roks import ROKS
from pyscf.pbc.dft.uks import UKS
from pyscf.pbc.gto.cell import Cell
from typing import Callable, Optional, Tuple, Union

def get_veff(ks: "RKS", cell: Optional[Cell]=None, dm: Optional[Union[ndarray, NPArrayWithTag]]=None, dm_last: Union[ndarray, int, NPArrayWithTag] = 0, vhf_last: Union[int, NPArrayWithTag] = 0, hermi: int = 1, kpt: None=None, kpts_band: None=None) -> NPArrayWithTag: ...

NELEC_ERROR_TOL: Incomplete

def prune_small_rho_grids_(ks, cell, dm, grids, kpts): ...
def get_rho(mf, dm=None, grids=None, kpt=None): ...
def gen_response(mf: "RKS", mo_coeff: None=None, mo_occ: None=None, singlet: Optional[bool]=None, hermi: int = 0, max_memory: Optional[float]=None, with_nlc: bool = True) -> Callable: ...

class KohnShamDFT(mol_ks.KohnShamDFT):
    small_rho_cutoff: Incomplete
    get_rho = get_rho
    density_fit: Incomplete
    rs_density_fit: Incomplete
    mix_density_fit: Incomplete
    gen_response = NotImplemented
    xc: Incomplete
    grids: Incomplete
    nlc: str
    nlcgrids: Incomplete
    def __init__(self, xc: str = 'LDA,VWN') -> None: ...
    def dump_flags(self, verbose: None=None) -> "KohnShamDFT": ...
    def reset(self, cell: Optional[Cell]=None) -> "KohnShamDFT": ...
    kpts: Incomplete
    kpt: Incomplete
    rsjk: Incomplete
    def build(self, cell: Optional[Cell]=None) -> "KohnShamDFT": ...
    def jk_method(self, J: str = 'FFTDF', K: None=None) -> Union[KRKS, RKS]: ...
    def to_rks(self, xc: None=None) -> KsymAdaptedKRKS: ...
    def to_uks(self, xc: None=None) -> Union[KUKS, KsymAdaptedKUKS]: ...
    def to_gks(self, xc=None): ...
    def to_hf(self) -> None: ...
    def initialize_grids(self, cell: Cell, dm: Union[ndarray, NPArrayWithTag], kpts: Union[ndarray, KPoints], ground_state: bool = True) -> "KohnShamDFT": ...
    def to_gpu(self) -> None: ...

class RKS(KohnShamDFT, pbchf.RHF):
    get_vsap = mol_ks.get_vsap
    init_guess_by_vsap = mol_ks.init_guess_by_vsap
    get_veff = get_veff
    energy_elec = mol_ks.energy_elec
    gen_response = gen_response
    def __init__(self, cell: Cell, kpt: Optional[ndarray]=None, xc: str = 'LDA,VWN', exxdiv: str=...) -> None: ...
    def dump_flags(self, verbose: None=None) -> "RKS": ...
    def to_hf(self): ...
    def multigrid_numint(self, mesh: None=None) -> Union[UKS, RKS]: ...
    def Gradients(self): ...
    to_gpu = lib.to_gpu
