from pyscf import df as df, gto as gto, lib as lib
from pyscf.dft import gen_grid as gen_grid, numint as numint
from pyscf.lib import logger as logger
from pyscf.solvent import ddcosmo as ddcosmo
from pyscf.solvent.grad.pcm import make_grad_object as make_grad_object
from pyscf.symm import sph as sph
from numpy import ndarray
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.solvent.ddcosmo import ddCOSMO
from pyscf.solvent.ddpcm import ddPCM
from typing import Dict, List, Optional, Tuple, Union

def kernel(pcmobj: Union[ddCOSMO, ddPCM], dm: Union[ndarray, NPArrayWithTag], verbose: Optional[int]=None) -> ndarray: ...
def make_L1(pcmobj: Union[ddCOSMO, ddPCM], r_vdw: ndarray, ylm_1sph: ndarray, fi: ndarray) -> ndarray: ...
def multipoles1(r: ndarray, lmax: int, reorder_dipole: bool = True) -> List[ndarray]: ...
def regularize_xt1(t: ndarray, eta: float) -> ndarray: ...
def make_fi1(pcmobj: Union[ddCOSMO, ddPCM], r_vdw: ndarray) -> ndarray: ...
def make_phi1(pcmobj: Union[ddCOSMO, ddPCM], dm: Union[ndarray, NPArrayWithTag], r_vdw: ndarray, ui: ndarray, ylm_1sph: ndarray) -> ndarray: ...
def make_e_psi1(pcmobj: Union[ddCOSMO, ddPCM], dm: Union[ndarray, NPArrayWithTag], r_vdw: ndarray, ui: ndarray, ylm_1sph: ndarray, cached_pol: Dict[str, Tuple[List[ndarray], ndarray]], Xvec: ndarray, L: ndarray) -> ndarray: ...
