from _typeshed import Incomplete
from pyscf import df as df, dft as dft, gto as gto, lib as lib, scf as scf
from pyscf.dft import numint as numint
from pyscf.lib import logger as logger
from pyscf.scf import cphf as cphf, ucphf as ucphf
from pyscf.solvent import ddcosmo as ddcosmo
from pyscf.solvent.grad import ddcosmo_grad as ddcosmo_grad
from numpy import ndarray
from pyscf.solvent.ddcosmo import ddCOSMO
from pyscf.solvent.ddpcm import ddPCM
from typing import Dict, List, Tuple, Union

def make_grad_object(td_base_method): ...

class WithSolventGrad:
    de_solvent: Incomplete
    de_solute: Incomplete
    def __init__(self, grad_method: Union[Incomplete, Incomplete, Incomplete, Incomplete]) -> None: ...
    def undo_solvent(self): ...
    def grad_elec(self, xy, singlet, atmlst=None): ...
    de: Incomplete
    def kernel(self, *args, dm=None, **kwargs): ...

def tdrhf_grad_elec(td_grad, x_y, singlet: bool = True, atmlst=None, max_memory: int = 2000, verbose=...): ...
def tdrks_grad_elec(td_grad, x_y, singlet: bool = True, atmlst=None, max_memory: int = 2000, verbose=...): ...
def tduhf_grad_elec(td_grad, x_y, atmlst=None, max_memory: int = 2000, verbose=...): ...
def tduks_grad_elec(td_grad, x_y, atmlst=None, max_memory: int = 2000, verbose=...): ...
