from pyscf import df as df, gto as gto, lib as lib
from pyscf.dft import gen_grid as gen_grid, numint as numint
from pyscf.lib import logger as logger
from pyscf.solvent import ddcosmo as ddcosmo
from pyscf.solvent.grad.pcm import make_grad_object as make_grad_object
from pyscf.symm import sph as sph

def kernel(pcmobj, dm, verbose=None): ...
def make_L1(pcmobj, r_vdw, ylm_1sph, fi): ...
def multipoles1(r, lmax, reorder_dipole: bool = True): ...
def regularize_xt1(t, eta): ...
def make_fi1(pcmobj, r_vdw): ...
def make_phi1(pcmobj, dm, r_vdw, ui, ylm_1sph): ...
def make_e_psi1(pcmobj, dm, r_vdw, ui, ylm_1sph, cached_pol, Xvec, L): ...
