from _typeshed import Incomplete
from pyscf import df as df, gto as gto, lib as lib
from pyscf.lib import logger as logger
from pyscf.solvent.pcm import PCM, PCM as PCM, PI as PI, switch_h as switch_h
from numpy import int64, ndarray
from pyscf.grad.rhf import GradientsBase
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.solvent.smd import SMD
from typing import Dict, List, Optional, Tuple, Union

def grad_switch_h(x: ndarray) -> ndarray: ...
def get_dF_dA(surface: Dict[str, Union[int, List[List[Union[int, int64]]], ndarray]], surface_discretization_method: str = 'SWIG') -> Tuple[ndarray, ndarray]: ...
def get_dD_dS(surface: Dict[str, Union[int, List[List[Union[int, int64]]], ndarray]], dF: ndarray, with_S: bool = True, with_D: bool = False) -> Union[Tuple[None, ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]]: ...
def grad_nuc(pcmobj: Union[SMD, PCM], dm: Union[ndarray, NPArrayWithTag], q_sym: Optional[ndarray]=None) -> ndarray: ...
def grad_qv(pcmobj: Union[SMD, PCM], dm: Union[ndarray, NPArrayWithTag], q_sym: Optional[ndarray]=None) -> ndarray: ...
def grad_solver(pcmobj: PCM, dm: Union[ndarray, NPArrayWithTag]) -> ndarray: ...
def make_grad_object(base_method): ...

class WithSolventGrad:
    de_solvent: Incomplete
    de_solute: Incomplete
    def __init__(self, grad_method: GradientsBase) -> None: ...
    def undo_solvent(self): ...
    def to_gpu(self): ...
    de: Incomplete
    def kernel(self, *args, dm=None, atmlst=None, **kwargs): ...
