from _typeshed import Incomplete
from pyscf import df as df, gto as gto, lib as lib
from pyscf.lib import logger as logger
from pyscf.solvent.pcm import PCM as PCM, PI as PI, switch_h as switch_h

def grad_switch_h(x): ...
def get_dF_dA(surface, surface_discretization_method: str = 'SWIG'): ...
def get_dD_dS(surface, dF, with_S: bool = True, with_D: bool = False): ...
def grad_nuc(pcmobj, dm, q_sym=None): ...
def grad_qv(pcmobj, dm, q_sym=None): ...
def grad_solver(pcmobj, dm): ...
def make_grad_object(base_method): ...

class WithSolventGrad:
    de_solvent: Incomplete
    de_solute: Incomplete
    def __init__(self, grad_method) -> None: ...
    def undo_solvent(self): ...
    def to_gpu(self): ...
    de: Incomplete
    def kernel(self, *args, dm=None, atmlst=None, **kwargs): ...
