from pyscf.mcscf.addons import *
from pyscf.mcscf import addons as addons, casci as casci, casci_symm as casci_symm, chkfile as chkfile, df as df, mc1step as mc1step, mc1step_symm as mc1step_symm, ucasci as ucasci, umc1step as umc1step

casci_uhf = ucasci
mc1step_uhf = umc1step

def CASSCF(mf_or_mol, ncas, nelecas, ncore=None, frozen=None): ...
RCASSCF = CASSCF

def CASCI(mf_or_mol, ncas, nelecas, ncore=None): ...
RCASCI = CASCI

def UCASCI(mf_or_mol, ncas, nelecas, ncore=None): ...
def UCASSCF(mf_or_mol, ncas, nelecas, ncore=None, frozen=None): ...
def newton(mc): ...
def DFCASSCF(mf_or_mol, ncas, nelecas, auxbasis=None, ncore=None, frozen=None): ...
def DFCASCI(mf_or_mol, ncas, nelecas, auxbasis=None, ncore=None): ...
approx_hessian = df.approx_hessian

def density_fit(mc, auxbasis=None, with_df=None): ...
