from _typeshed import Incomplete
from pyscf import __config__ as __config__, fci as fci, gto as gto, lib as lib, scf as scf, symm as symm
from pyscf.lib import logger as logger
from numpy import float64, int64, ndarray
from pyscf.fci.addons import SpinPenaltyFCISolver
from pyscf.fci.cistring import OIndexList
from pyscf.fci.direct_spin1 import FCIvector
from pyscf.gto.mole import Mole
from pyscf.lib.logger import Logger
from pyscf.lib.misc import StreamObject
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.mcscf.casci import CASBase, CASCI
from pyscf.mcscf.casci_symm import SymAdaptedCASCI
from pyscf.mcscf.mc1step import CASSCF, CASSCF_Scanner
from pyscf.mcscf.mc1step_symm import SymAdaptedCASSCF
from pyscf.mcscf.ucasci import UCASCI
from pyscf.mcscf.umc1step import UCASSCF
from typing import Any, Dict, Iterator, List, Optional, Tuple, Union

BASE: Incomplete
MAP2HF_TOL: Incomplete
RANGE_TYPE = range

def sort_mo(casscf: Union[SymAdaptedCASCI, SymAdaptedCASSCF, UCASSCF, CASSCF, UCASCI], mo_coeff: Union[ndarray, NPArrayWithTag, Tuple[NPArrayWithTag, NPArrayWithTag], Tuple[ndarray, ndarray]], caslst: Union[ndarray, List[List[int]], List[int]], base: int=...) -> Union[ndarray, NPArrayWithTag, Tuple[NPArrayWithTag, NPArrayWithTag], Tuple[ndarray, ndarray]]: ...
def select_mo_by_irrep(casscf, cas_occ_num, mo=None, base=...) -> None: ...
def caslst_by_irrep(casscf: Union[SymAdaptedCASSCF, SymAdaptedCASCI], mo_coeff: NPArrayWithTag, cas_irrep_nocc: Union[Dict[str, int], Tuple[int, int, int, int, int, int, int, int], Dict[Union[str, int], int], Dict[int, int]], cas_irrep_ncore: Optional[Union[Dict[str, int], Dict[int, int]]]=None, s: None=None, base: int=...) -> ndarray: ...
def sort_mo_by_irrep(casscf: Union[SymAdaptedCASSCF, SymAdaptedCASCI], mo_coeff: NPArrayWithTag, cas_irrep_nocc: Union[Dict[str, int], Tuple[int, int, int, int, int, int, int, int], Dict[Union[str, int], int], Dict[int, int]], cas_irrep_ncore: Optional[Dict[int, int]]=None, s: None=None) -> NPArrayWithTag: ...
def make_natural_orbitals(method_obj: StreamObject) -> Tuple[ndarray, ndarray]: ...
def project_init_guess(casscf: Union[SymAdaptedCASSCF, UCASSCF, CASSCF_Scanner], mo_init: Union[ndarray, NPArrayWithTag, Tuple[NPArrayWithTag, NPArrayWithTag]], prev_mol: Optional[Mole]=None, priority: Optional[Union[List[List[List[int]]], List[List[int]], str]]=None, use_hf_core: Optional[bool]=None) -> Union[ndarray, Tuple[ndarray, ndarray]]: ...
def project_init_guess_old(casscf, init_mo, prev_mol=None): ...
def make_rdm1(casscf: SymAdaptedCASSCF, mo_coeff: None=None, ci: None=None, **kwargs) -> ndarray: ...
def make_rdm1s(casscf: Union[SymAdaptedCASSCF, UCASSCF], mo_coeff: None=None, ci: None=None, **kwargs) -> Tuple[ndarray, ndarray]: ...
def get_spin_square(casdm1, casdm2): ...
def make_spin_casdm1(casdm1, casdm2, spin=None, nelec=None): ...
def make_rdm12(casscf: SymAdaptedCASSCF, mo_coeff: None=None, ci: None=None) -> Tuple[NPArrayWithTag, NPArrayWithTag]: ...
def get_fock(casscf: SymAdaptedCASSCF, mo_coeff: None=None, ci: None=None) -> ndarray: ...
def cas_natorb(casscf: SymAdaptedCASSCF, mo_coeff: None=None, ci: None=None, sort: bool = False) -> Tuple[NPArrayWithTag, ndarray, ndarray]: ...
def map2hf(casscf: Union[SymAdaptedCASSCF, CASSCF, SymAdaptedCASCI, CASCI], mf_mo: Optional[Union[ndarray, NPArrayWithTag]]=None, base: int=..., tol: float=...) -> ndarray: ...
def spin_square(casscf: Union[SymAdaptedCASSCF, UCASSCF, UCASCI], mo_coeff: None=None, ci: None=None, ovlp: None=None) -> Union[Tuple[float64, float64], Tuple[ndarray, ndarray]]: ...

class StateAverageMCSCFSolver: ...

def state_average(casscf, weights=(0.5, 0.5), wfnsym=None): ...

class StateAverageFCISolver:
    __name_mixin__: str
    nroots: Incomplete
    weights: Incomplete
    wfnsym: Incomplete
    e_states: Incomplete
    def __init__(self, fcibase: Union[Incomplete, SpinPenaltyFCISolver, Incomplete, Incomplete], weights: Union[List[float], Tuple[float, float]], wfnsym: None) -> None: ...
    def undo_state_average(self) -> Union[Incomplete, Incomplete]: ...
    def dump_flags(self, verbose: Optional[int]=None) -> Union[StateAverageFCISolver, StateAverageMixFCISolver]: ...
    def kernel(self, h1: Union[ndarray, NPArrayWithTag, Tuple[ndarray, ndarray]], h2: Union[ndarray, Tuple[ndarray, ndarray, ndarray]], norb: int, nelec: Tuple[int, int], ci0: Optional[Union[List[FCIvector], FCIvector, List[ndarray]]]=None, **kwargs) -> Tuple[float64, List[FCIvector]]: ...
    def approx_kernel(self, h1: Union[ndarray, Tuple[ndarray, ndarray]], h2: Union[ndarray, Tuple[ndarray, ndarray, ndarray]], norb: int, nelec: Tuple[int, int], ci0: Optional[List[FCIvector]]=None, **kwargs) -> Tuple[float64, List[FCIvector]]: ...
    def states_make_rdm1(self, ci0: List[FCIvector], norb: int, nelec: Tuple[int, int], *args, **kwargs) -> List[ndarray]: ...
    def make_rdm1(self, ci0: List[FCIvector], norb: int, nelec: Tuple[int, int], *args, **kwargs) -> ndarray: ...
    def states_make_rdm1s(self, ci0: List[Union[FCIvector, ndarray]], norb: int, nelec: Tuple[int, int], *args, **kwargs) -> Tuple[List[ndarray], List[ndarray]]: ...
    def make_rdm1s(self, ci0: List[Union[FCIvector, ndarray]], norb: int, nelec: Tuple[int, int], *args, **kwargs) -> Tuple[ndarray, ndarray]: ...
    def states_make_rdm12(self, ci0: List[Union[FCIvector, ndarray]], norb: int, nelec: Tuple[int, int], *args, **kwargs) -> Tuple[List[ndarray], List[ndarray]]: ...
    def make_rdm12(self, ci0: List[Union[FCIvector, ndarray]], norb: int, nelec: Tuple[int, int], *args, **kwargs) -> Tuple[ndarray, ndarray]: ...
    def states_make_rdm12s(self, ci0: List[FCIvector], norb: int, nelec: Tuple[int, int], *args, **kwargs) -> Tuple[Tuple[List[ndarray], List[ndarray]], Tuple[List[ndarray], List[ndarray], List[ndarray]]]: ...
    def make_rdm12s(self, ci0: List[FCIvector], norb: int, nelec: Tuple[int, int], *args, **kwargs) -> Tuple[ndarray, ndarray]: ...
    def states_trans_rdm12(self, ci1: List[ndarray], ci0: List[Union[FCIvector, ndarray]], norb: int, nelec: Tuple[int, int], *args, **kwargs) -> Tuple[List[ndarray], List[ndarray]]: ...
    def trans_rdm12(self, ci1: List[ndarray], ci0: List[Union[FCIvector, ndarray]], norb: int, nelec: Tuple[int, int], *args, **kwargs) -> Tuple[ndarray, ndarray]: ...

class StateAverageMCSCF(StateAverageMCSCFSolver):
    __name_mixin__: str
    fcisolver: Incomplete
    def __init__(self, my_mc: CASBase, fcisolver: Union[StateAverageFCISolver, StateAverageMixFCISolver]) -> None: ...
    def undo_state_average(self): ...
    @property
    def weights(self): ...
    @weights.setter
    def weights(self, x): ...
    @property
    def e_average(self): ...
    @property
    def e_states(self): ...
    def nuc_grad_method(self, state=None): ...
    Gradients = nuc_grad_method
    def nac_method(self): ...
    NACs = nac_method

def state_average_(casscf, weights=(0.5, 0.5), wfnsym=None): ...
def state_specific_(casscf: SymAdaptedCASSCF, state: int = 1, wfnsym: None=None) -> SymAdaptedCASSCF: ...
state_specific = state_specific_

class StateSpecificFCISolver:
    __name_mixin__: str
    state: Incomplete
    nroots: Incomplete
    wfnsym: Incomplete
    def __init__(self, fcibase: Incomplete, state: int, wfnsym: None) -> None: ...
    def undo_state_specific(self): ...
    def kernel(self, h1: ndarray, h2: ndarray, norb: int, nelec: Tuple[int, int], ci0: Optional[FCIvector]=None, **kwargs) -> Tuple[float64, FCIvector]: ...
    def approx_kernel(self, h1: ndarray, h2: ndarray, norb: int, nelec: Tuple[int, int], ci0: Optional[FCIvector]=None, **kwargs) -> Tuple[float64, FCIvector]: ...

class StateAverageMixFCISolver_solver_args:
    def __init__(self, data: Any) -> None: ...
    def __getitem__(self, key: Union[int, slice]) -> Any: ...

class StateAverageMixFCISolver_state_args(StateAverageMixFCISolver_solver_args): ...

class StateAverageMixFCISolver(StateAverageFCISolver):
    __name_mixin__: str
    nroots: Incomplete
    weights: Incomplete
    e_states: Incomplete
    fcisolvers: Incomplete
    def __init__(self, fcisolvers: List[Any], weights: Union[ndarray, List[float], Tuple[float, float, float]]) -> None: ...
    def undo_state_average(self): ...
    converged: Incomplete
    def kernel(self, h1: Union[ndarray, Tuple[ndarray, ndarray]], h2: Union[ndarray, Tuple[ndarray, ndarray, ndarray]], norb: int, nelec: Tuple[int, int], ci0: Optional[Union[List[FCIvector], List[ndarray]]]=None, verbose: Logger = 0, **kwargs) -> Tuple[float64, List[FCIvector]]: ...
    def approx_kernel(self, h1: Union[ndarray, Tuple[ndarray, ndarray]], h2: Union[ndarray, Tuple[ndarray, ndarray, ndarray]], norb: int, nelec: Tuple[int, int], ci0: Optional[List[FCIvector]]=None, **kwargs) -> Tuple[float64, List[FCIvector]]: ...
    def states_make_rdm1(self, ci0: List[FCIvector], norb: int, nelec: Tuple[int, int], link_index: None=None, **kwargs) -> List[ndarray]: ...
    def make_rdm1(self, ci0: List[FCIvector], norb: int, nelec: Tuple[int, int], link_index: None=None, **kwargs) -> ndarray: ...
    def states_make_rdm1s(self, ci0: List[FCIvector], norb: int, nelec: Tuple[int, int], link_index: None=None, **kwargs) -> Tuple[List[ndarray], List[ndarray]]: ...
    def make_rdm1s(self, ci0: List[FCIvector], norb: int, nelec: Tuple[int, int], link_index: None=None, **kwargs) -> Tuple[ndarray, ndarray]: ...
    def states_make_rdm12(self, ci0: List[Union[FCIvector, ndarray]], norb: int, nelec: Tuple[int, int], link_index: Optional[Union[List[Union[ndarray, Tuple[ndarray, ndarray]]], List[Tuple[ndarray, ndarray]]]]=None, **kwargs) -> Tuple[List[ndarray], List[ndarray]]: ...
    def make_rdm12(self, ci0: List[Union[FCIvector, ndarray]], norb: int, nelec: Tuple[int, int], link_index: Optional[Union[List[Tuple[ndarray, ndarray]], List[Union[ndarray, Tuple[ndarray, ndarray]]]]]=None, **kwargs) -> Tuple[ndarray, ndarray]: ...
    def states_make_rdm12s(self, ci0: List[FCIvector], norb: int, nelec: Tuple[int, int], link_index: None=None, **kwargs) -> Tuple[Tuple[List[ndarray], List[ndarray]], Tuple[List[ndarray], List[ndarray], List[ndarray]]]: ...
    def make_rdm12s(self, ci0: List[FCIvector], norb: int, nelec: Tuple[int, int], link_index: None=None, **kwargs) -> Tuple[ndarray, ndarray]: ...
    def states_trans_rdm12(self, ci1: List[ndarray], ci0: List[FCIvector], norb: int, nelec: Tuple[int, int], link_index: Optional[List[Union[ndarray, Tuple[ndarray, ndarray]]]]=None, **kwargs) -> Tuple[List[ndarray], List[ndarray]]: ...
    def trans_rdm12(self, ci1: List[ndarray], ci0: List[FCIvector], norb: int, nelec: Tuple[int, int], link_index: Optional[List[Union[ndarray, Tuple[ndarray, ndarray]]]]=None, **kwargs) -> Tuple[ndarray, ndarray]: ...
    spin_square: Incomplete
    large_ci: Incomplete
    transform_ci_for_orbital_rotation: Incomplete

def state_average_mix(casscf, fcisolvers, weights=(0.5, 0.5)): ...
def state_average_mix_(casscf, fcisolvers, weights=(0.5, 0.5)): ...
