from _typeshed import Incomplete
from pyscf import __config__ as __config__, fci as fci, gto as gto, lib as lib, scf as scf, symm as symm
from pyscf.lib import logger as logger

BASE: Incomplete
MAP2HF_TOL: Incomplete
RANGE_TYPE = range

def sort_mo(casscf, mo_coeff, caslst, base=...): ...
def select_mo_by_irrep(casscf, cas_occ_num, mo=None, base=...) -> None: ...
def caslst_by_irrep(casscf, mo_coeff, cas_irrep_nocc, cas_irrep_ncore=None, s=None, base=...): ...
def sort_mo_by_irrep(casscf, mo_coeff, cas_irrep_nocc, cas_irrep_ncore=None, s=None): ...
def make_natural_orbitals(method_obj): ...
def project_init_guess(casscf, mo_init, prev_mol=None, priority=None, use_hf_core=None): ...
def project_init_guess_old(casscf, init_mo, prev_mol=None): ...
def make_rdm1(casscf, mo_coeff=None, ci=None, **kwargs): ...
def make_rdm1s(casscf, mo_coeff=None, ci=None, **kwargs): ...
def get_spin_square(casdm1, casdm2): ...
def make_spin_casdm1(casdm1, casdm2, spin=None, nelec=None): ...
def make_rdm12(casscf, mo_coeff=None, ci=None): ...
def get_fock(casscf, mo_coeff=None, ci=None): ...
def cas_natorb(casscf, mo_coeff=None, ci=None, sort: bool = False): ...
def map2hf(casscf, mf_mo=None, base=..., tol=...): ...
def spin_square(casscf, mo_coeff=None, ci=None, ovlp=None): ...

class StateAverageMCSCFSolver: ...

def state_average(casscf, weights=(0.5, 0.5), wfnsym=None): ...

class StateAverageFCISolver:
    __name_mixin__: str
    nroots: Incomplete
    weights: Incomplete
    wfnsym: Incomplete
    e_states: Incomplete
    def __init__(self, fcibase, weights, wfnsym) -> None: ...
    def undo_state_average(self): ...
    def dump_flags(self, verbose=None): ...
    def kernel(self, h1, h2, norb, nelec, ci0=None, **kwargs): ...
    def approx_kernel(self, h1, h2, norb, nelec, ci0=None, **kwargs): ...
    def states_make_rdm1(self, ci0, norb, nelec, *args, **kwargs): ...
    def make_rdm1(self, ci0, norb, nelec, *args, **kwargs): ...
    def states_make_rdm1s(self, ci0, norb, nelec, *args, **kwargs): ...
    def make_rdm1s(self, ci0, norb, nelec, *args, **kwargs): ...
    def states_make_rdm12(self, ci0, norb, nelec, *args, **kwargs): ...
    def make_rdm12(self, ci0, norb, nelec, *args, **kwargs): ...
    def states_make_rdm12s(self, ci0, norb, nelec, *args, **kwargs): ...
    def make_rdm12s(self, ci0, norb, nelec, *args, **kwargs): ...
    def states_trans_rdm12(self, ci1, ci0, norb, nelec, *args, **kwargs): ...
    def trans_rdm12(self, ci1, ci0, norb, nelec, *args, **kwargs): ...

class StateAverageMCSCF(StateAverageMCSCFSolver):
    __name_mixin__: str
    fcisolver: Incomplete
    def __init__(self, my_mc, fcisolver) -> None: ...
    def undo_state_average(self): ...
    @property
    def weights(self): ...
    @weights.setter
    def weights(self, x): ...
    @property
    def e_average(self): ...
    @property
    def e_states(self): ...
    def nuc_grad_method(self, state=None): ...
    Gradients = nuc_grad_method
    def nac_method(self): ...
    NACs = nac_method

def state_average_(casscf, weights=(0.5, 0.5), wfnsym=None): ...
def state_specific_(casscf, state: int = 1, wfnsym=None): ...
state_specific = state_specific_

class StateSpecificFCISolver:
    __name_mixin__: str
    state: Incomplete
    nroots: Incomplete
    wfnsym: Incomplete
    def __init__(self, fcibase, state, wfnsym) -> None: ...
    def undo_state_specific(self): ...
    def kernel(self, h1, h2, norb, nelec, ci0=None, **kwargs): ...
    def approx_kernel(self, h1, h2, norb, nelec, ci0=None, **kwargs): ...

class StateAverageMixFCISolver_solver_args:
    def __init__(self, data) -> None: ...
    def __getitem__(self, key): ...

class StateAverageMixFCISolver_state_args(StateAverageMixFCISolver_solver_args): ...

class StateAverageMixFCISolver(StateAverageFCISolver):
    __name_mixin__: str
    nroots: Incomplete
    weights: Incomplete
    e_states: Incomplete
    fcisolvers: Incomplete
    def __init__(self, fcisolvers, weights) -> None: ...
    def undo_state_average(self): ...
    converged: Incomplete
    def kernel(self, h1, h2, norb, nelec, ci0=None, verbose: int = 0, **kwargs): ...
    def approx_kernel(self, h1, h2, norb, nelec, ci0=None, **kwargs): ...
    def states_make_rdm1(self, ci0, norb, nelec, link_index=None, **kwargs): ...
    def make_rdm1(self, ci0, norb, nelec, link_index=None, **kwargs): ...
    def states_make_rdm1s(self, ci0, norb, nelec, link_index=None, **kwargs): ...
    def make_rdm1s(self, ci0, norb, nelec, link_index=None, **kwargs): ...
    def states_make_rdm12(self, ci0, norb, nelec, link_index=None, **kwargs): ...
    def make_rdm12(self, ci0, norb, nelec, link_index=None, **kwargs): ...
    def states_make_rdm12s(self, ci0, norb, nelec, link_index=None, **kwargs): ...
    def make_rdm12s(self, ci0, norb, nelec, link_index=None, **kwargs): ...
    def states_trans_rdm12(self, ci1, ci0, norb, nelec, link_index=None, **kwargs): ...
    def trans_rdm12(self, ci1, ci0, norb, nelec, link_index=None, **kwargs): ...
    spin_square: Incomplete
    large_ci: Incomplete
    transform_ci_for_orbital_rotation: Incomplete

def state_average_mix(casscf, fcisolvers, weights=(0.5, 0.5)): ...
def state_average_mix_(casscf, fcisolvers, weights=(0.5, 0.5)): ...
