from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, fci as fci, gto as gto, lib as lib, scf as scf
from pyscf.lib import logger as logger
from pyscf.mcscf import addons as addons

WITH_META_LOWDIN: Incomplete
LARGE_CI_TOL: Incomplete
PENALTY: Incomplete
FRAC_OCC_THRESHOLD: float
RANGE_TYPE = range

def h1e_for_cas(casci, mo_coeff=None, ncas=None, ncore=None): ...
def analyze(casscf, mo_coeff=None, ci=None, verbose=None, large_ci_tol=..., with_meta_lowdin=..., **kwargs): ...
def get_fock(mc, mo_coeff=None, ci=None, eris=None, casdm1=None, verbose=None): ...
def cas_natorb(mc, mo_coeff=None, ci=None, eris=None, sort: bool = False, casdm1=None, verbose=None, with_meta_lowdin=...): ...
def canonicalize(mc, mo_coeff=None, ci=None, eris=None, sort: bool = False, cas_natorb: bool = False, casdm1=None, verbose=..., with_meta_lowdin=..., stav_dm1: bool = False): ...
def kernel(casci, mo_coeff=None, ci0=None, verbose=..., envs=None): ...
def as_scanner(mc): ...

class CASCI_Scanner(lib.SinglePointScanner):
    def __init__(self, mc) -> None: ...
    mol: Incomplete
    def __call__(self, mol_or_geom, mo_coeff=None, ci0=None): ...

class CASBase(lib.StreamObject):
    natorb: Incomplete
    canonicalization: Incomplete
    sorting_mo_energy: Incomplete
    mol: Incomplete
    verbose: Incomplete
    stdout: Incomplete
    max_memory: Incomplete
    ncas: Incomplete
    nelecas: Incomplete
    fcisolver: Incomplete
    frozen: Incomplete
    extrasym: Incomplete
    e_tot: int
    e_cas: Incomplete
    ci: Incomplete
    mo_coeff: Incomplete
    mo_energy: Incomplete
    mo_occ: Incomplete
    converged: bool
    def __init__(self, mf_or_mol, ncas: int = 0, nelecas: int = 0, ncore=None) -> None: ...
    @property
    def ncore(self): ...
    @ncore.setter
    def ncore(self, x) -> None: ...
    def dump_flags(self, verbose=None): ...
    def check_sanity(self): ...
    def reset(self, mol=None): ...
    def energy_nuc(self): ...
    def get_hcore(self, mol=None): ...
    def get_jk(self, mol, dm, hermi: int = 1, with_j: bool = True, with_k: bool = True, omega=None): ...
    def get_veff(self, mol=None, dm=None, hermi: int = 1): ...
    def get_h2cas(self, mo_coeff=None): ...
    def get_h2eff(self, mo_coeff=None) -> None: ...
    def ao2mo(self, mo_coeff=None) -> None: ...
    def get_h1cas(self, mo_coeff=None, ncas=None, ncore=None): ...
    get_h1eff = h1e_for_cas
    h1e_for_cas = h1e_for_cas
    def casci(self, mo_coeff=None, ci0=None, verbose=None) -> None: ...
    def kernel(self, mo_coeff=None, ci0=None, verbose=None) -> None: ...
    def cas_natorb(self, mo_coeff=None, ci=None, eris=None, sort: bool = False, casdm1=None, verbose=None, with_meta_lowdin=...): ...
    def cas_natorb_(self, mo_coeff=None, ci=None, eris=None, sort: bool = False, casdm1=None, verbose=None, with_meta_lowdin=...): ...
    def get_fock(self, mo_coeff=None, ci=None, eris=None, casdm1=None, verbose=None): ...
    canonicalize = canonicalize
    def canonicalize_(self, mo_coeff=None, ci=None, eris=None, sort: bool = False, cas_natorb: bool = False, casdm1=None, verbose=None, with_meta_lowdin=...): ...
    analyze = analyze
    def sort_mo(self, caslst, mo_coeff=None, base: int = 1): ...
    def state_average_(self, weights=(0.5, 0.5), wfnsym=None): ...
    def state_average(self, weights=(0.5, 0.5), wfnsym=None): ...
    def state_average_mix(self, fcisolvers=None, weights=(0.5, 0.5)): ...
    def state_average_mix_(self, fcisolvers=None, weights=(0.5, 0.5)): ...
    def state_specific_(self, state: int = 1): ...
    def make_rdm1s(self, mo_coeff=None, ci=None, ncas=None, nelecas=None, ncore=None, **kwargs): ...
    def make_rdm1(self, mo_coeff=None, ci=None, ncas=None, nelecas=None, ncore=None, **kwargs): ...
    def fix_spin_(self, shift=..., ss=None): ...
    fix_spin = fix_spin_
    def density_fit(self, auxbasis=None, with_df=None): ...
    def sfx2c1e(self): ...
    x2c = sfx2c1e
    x2c1e = sfx2c1e
    def nuc_grad_method(self) -> None: ...

class CASCI(CASBase):
    def get_h2eff(self, mo_coeff=None): ...
    def casci(self, mo_coeff=None, ci0=None, verbose=None): ...
    mo_coeff: Incomplete
    converged: Incomplete
    def kernel(self, mo_coeff=None, ci0=None, verbose=None): ...
    as_scanner = as_scanner
    def nuc_grad_method(self): ...
    to_gpu = lib.to_gpu
