from _typeshed import Incomplete
from pyscf import fci as fci, lib as lib, scf as scf, symm as symm
from pyscf.lib import logger as logger
from pyscf.mcscf import addons as addons, casci as casci
from pyscf.scf.hf_symm import map_degeneracy as map_degeneracy

class SymAdaptedCASCI(casci.CASCI):
    fcisolver: Incomplete
    def __init__(self, mf_or_mol, ncas: int = 0, nelecas: int = 0, ncore=None) -> None: ...
    @property
    def wfnsym(self): ...
    @wfnsym.setter
    def wfnsym(self, wfnsym) -> None: ...
    mo_coeff: Incomplete
    def kernel(self, mo_coeff=None, ci0=None, verbose=None): ...
    def sort_mo_by_irrep(self, cas_irrep_nocc, cas_irrep_ncore=None, mo_coeff=None, s=None): ...
    to_gpu = lib.to_gpu
CASCI = SymAdaptedCASCI

def eig(mat, orbsym): ...
def label_symmetry_(mc, mo_coeff, ci0=None): ...
