from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, fci as fci, gto as gto, lib as lib, scf as scf
from pyscf.lib import logger as logger
from pyscf.mcscf import addons as addons
from numpy import float64, ndarray
from pyscf.dft.rks import RKS
from pyscf.fci.direct_spin1 import FCIvector
from pyscf.gto.mole import Mole
from pyscf.lib.logger import Logger
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.mcscf.casci_symm import SymAdaptedCASCI
from pyscf.mcscf.mc1step import CASSCF, CASSCF_Scanner
from pyscf.mcscf.mc1step_symm import SymAdaptedCASSCF
from pyscf.mcscf.mc_ao2mo import _ERIS
from pyscf.mcscf.ucasci import UCASCI
from pyscf.mcscf.umc1step import UCASSCF
from pyscf.scf.hf import RHF
from pyscf.scf.hf_symm import SymAdaptedRHF, SymAdaptedROHF
from pyscf.scf.rohf import ROHF
from typing import Any, List, Optional, Tuple, Union

WITH_META_LOWDIN: Incomplete
LARGE_CI_TOL: Incomplete
PENALTY: Incomplete
FRAC_OCC_THRESHOLD: float
RANGE_TYPE = range

def h1e_for_cas(casci: Union[CASCI, CASCI_Scanner, SymAdaptedCASCI, SymAdaptedCASSCF], mo_coeff: Optional[Union[ndarray, NPArrayWithTag]]=None, ncas: None=None, ncore: None=None) -> Union[Tuple[NPArrayWithTag, float64], Tuple[ndarray, float64]]: ...
def analyze(casscf: Union[SymAdaptedCASSCF, SymAdaptedCASCI, CASSCF, CASCI], mo_coeff: None=None, ci: None=None, verbose: None=None, large_ci_tol: float=..., with_meta_lowdin: bool=..., **kwargs) -> Union[Tuple[ndarray, None], Tuple[ndarray, ndarray]]: ...
def get_fock(mc: Any, mo_coeff: Optional[Union[ndarray, NPArrayWithTag]]=None, ci: Optional[Union[List[FCIvector], FCIvector]]=None, eris: Optional[_ERIS]=None, casdm1: Optional[ndarray]=None, verbose: Optional[Union[Logger, int]]=None) -> ndarray: ...
def cas_natorb(mc: Union[SymAdaptedCASSCF, SymAdaptedCASCI, CASSCF, CASCI], mo_coeff: Optional[Union[NPArrayWithTag, ndarray]]=None, ci: Optional[Union[List[FCIvector], FCIvector]]=None, eris: Optional[_ERIS]=None, sort: bool = False, casdm1: Optional[ndarray]=None, verbose: Optional[Union[Logger, int]]=None, with_meta_lowdin: bool=...) -> Union[Tuple[NPArrayWithTag, ndarray, ndarray], Tuple[NPArrayWithTag, FCIvector, ndarray], Tuple[ndarray, List[ndarray], ndarray], Tuple[ndarray, ndarray, ndarray]]: ...
def canonicalize(mc: Any, mo_coeff: Optional[Union[ndarray, NPArrayWithTag]]=None, ci: Optional[Union[List[FCIvector], FCIvector]]=None, eris: Optional[_ERIS]=None, sort: bool = False, cas_natorb: Union[bool, int] = False, casdm1: Optional[ndarray]=None, verbose: Union[Logger, int]=..., with_meta_lowdin: bool=..., stav_dm1: bool = False) -> Any: ...
def kernel(casci: Union[CASCI, CASCI_Scanner, SymAdaptedCASCI], mo_coeff: Optional[Union[ndarray, NPArrayWithTag]]=None, ci0: Optional[Union[List[FCIvector], FCIvector, ndarray]]=None, verbose: Logger=..., envs: Optional[Any]=None) -> Union[Tuple[ndarray, ndarray, List[FCIvector]], Tuple[float64, float64, FCIvector], Tuple[float64, float64, List[FCIvector]]]: ...
def as_scanner(mc: Union[CASCI, CASCI_Scanner]) -> "CASCI_Scanner": ...

class CASCI_Scanner(lib.SinglePointScanner):
    def __init__(self, mc: Union[CASCI, UCASCI]) -> None: ...
    mol: Incomplete
    def __call__(self, mol_or_geom: Mole, mo_coeff: None=None, ci0: None=None) -> float64: ...

class CASBase(lib.StreamObject):
    natorb: Incomplete
    canonicalization: Incomplete
    sorting_mo_energy: Incomplete
    mol: Incomplete
    verbose: Incomplete
    stdout: Incomplete
    max_memory: Incomplete
    ncas: Incomplete
    nelecas: Incomplete
    fcisolver: Incomplete
    frozen: Incomplete
    extrasym: Incomplete
    e_tot: int
    e_cas: Incomplete
    ci: Incomplete
    mo_coeff: Incomplete
    mo_energy: Incomplete
    mo_occ: Incomplete
    converged: bool
    def __init__(self, mf_or_mol: Union[ROHF, SymAdaptedROHF, RHF, SymAdaptedRHF, RKS], ncas: int = 0, nelecas: Union[int, Tuple[int, int]] = 0, ncore: Optional[int]=None) -> None: ...
    @property
    def ncore(self): ...
    @ncore.setter
    def ncore(self, x) -> None: ...
    def dump_flags(self, verbose: Optional[Logger]=None) -> Union[CASCI, CASCI_Scanner, SymAdaptedCASCI]: ...
    def check_sanity(self) -> Any: ...
    def reset(self, mol: Optional[Mole]=None) -> Union[CASCI_Scanner, CASSCF_Scanner]: ...
    def energy_nuc(self) -> Union[int, float64]: ...
    def get_hcore(self, mol: None=None) -> ndarray: ...
    def get_jk(self, mol: Mole, dm: Union[ndarray, Tuple[ndarray, NPArrayWithTag], Tuple[ndarray, ndarray]], hermi: int = 1, with_j: bool = True, with_k: bool = True, omega: None=None) -> Tuple[ndarray, ndarray]: ...
    def get_veff(self, mol: Optional[Mole]=None, dm: Optional[ndarray]=None, hermi: int = 1) -> ndarray: ...
    def get_h2cas(self, mo_coeff=None): ...
    def get_h2eff(self, mo_coeff=None) -> None: ...
    def ao2mo(self, mo_coeff=None) -> None: ...
    def get_h1cas(self, mo_coeff=None, ncas=None, ncore=None): ...
    get_h1eff = h1e_for_cas
    h1e_for_cas = h1e_for_cas
    def casci(self, mo_coeff=None, ci0=None, verbose=None) -> None: ...
    def kernel(self, mo_coeff=None, ci0=None, verbose=None) -> None: ...
    def cas_natorb(self, mo_coeff: Optional[Union[ndarray, NPArrayWithTag]]=None, ci: Optional[Union[List[FCIvector], FCIvector]]=None, eris: Optional[_ERIS]=None, sort: bool = False, casdm1: Optional[ndarray]=None, verbose: Optional[Union[Logger, int]]=None, with_meta_lowdin: bool=...) -> Union[Tuple[NPArrayWithTag, ndarray, ndarray], Tuple[ndarray, List[ndarray], ndarray], Tuple[ndarray, ndarray, ndarray]]: ...
    def cas_natorb_(self, mo_coeff: None=None, ci: None=None, eris: Optional[_ERIS]=None, sort: bool = False, casdm1: Optional[ndarray]=None, verbose: None=None, with_meta_lowdin: bool=...) -> Tuple[NPArrayWithTag, FCIvector, ndarray]: ...
    def get_fock(self, mo_coeff: Optional[Union[ndarray, NPArrayWithTag]]=None, ci: Optional[Union[List[FCIvector], FCIvector]]=None, eris: Optional[_ERIS]=None, casdm1: Optional[ndarray]=None, verbose: Optional[Union[Logger, int]]=None) -> ndarray: ...
    canonicalize = canonicalize
    def canonicalize_(self, mo_coeff: Optional[Union[ndarray, NPArrayWithTag]]=None, ci: Optional[Union[List[FCIvector], FCIvector]]=None, eris: None=None, sort: bool = False, cas_natorb: Union[bool, int] = False, casdm1: None=None, verbose: Optional[Logger]=None, with_meta_lowdin: bool=...) -> Union[Tuple[NPArrayWithTag, FCIvector, ndarray], Tuple[ndarray, ndarray, ndarray], Tuple[ndarray, List[FCIvector], ndarray], Tuple[ndarray, FCIvector, ndarray], Tuple[ndarray, List[ndarray], ndarray]]: ...
    analyze = analyze
    def sort_mo(self, caslst: List[int], mo_coeff: None=None, base: int = 1) -> Union[ndarray, NPArrayWithTag]: ...
    def state_average_(self, weights=(0.5, 0.5), wfnsym=None): ...
    def state_average(self, weights=(0.5, 0.5), wfnsym=None): ...
    def state_average_mix(self, fcisolvers=None, weights=(0.5, 0.5)): ...
    def state_average_mix_(self, fcisolvers=None, weights=(0.5, 0.5)): ...
    def state_specific_(self, state: int = 1) -> SymAdaptedCASSCF: ...
    def make_rdm1s(self, mo_coeff: None=None, ci: None=None, ncas: None=None, nelecas: None=None, ncore: None=None, **kwargs) -> Tuple[ndarray, ndarray]: ...
    def make_rdm1(self, mo_coeff: None=None, ci: None=None, ncas: None=None, nelecas: None=None, ncore: None=None, **kwargs) -> ndarray: ...
    def fix_spin_(self, shift: float=..., ss: Optional[Union[float, int]]=None) -> Union[SymAdaptedCASSCF, CASCI]: ...
    fix_spin = fix_spin_
    def density_fit(self, auxbasis=None, with_df=None): ...
    def sfx2c1e(self) -> Union[UCASCI, UCASSCF, SymAdaptedCASSCF, CASCI, CASSCF]: ...
    x2c = sfx2c1e
    x2c1e = sfx2c1e
    def nuc_grad_method(self) -> None: ...

class CASCI(CASBase):
    def get_h2eff(self, mo_coeff: Optional[Union[ndarray, NPArrayWithTag]]=None) -> ndarray: ...
    def casci(self, mo_coeff: Optional[NPArrayWithTag]=None, ci0: None=None, verbose: None=None) -> Union[Tuple[float64, float64, FCIvector, NPArrayWithTag, ndarray], Tuple[float64, float64, FCIvector, ndarray, ndarray]]: ...
    mo_coeff: Incomplete
    converged: Incomplete
    def kernel(self, mo_coeff: Optional[Union[ndarray, NPArrayWithTag]]=None, ci0: Optional[FCIvector]=None, verbose: None=None) -> Union[Tuple[float64, float64, FCIvector, ndarray, ndarray], Tuple[float64, float64, ndarray, ndarray, ndarray], Tuple[ndarray, ndarray, List[FCIvector], ndarray, ndarray], Tuple[float64, float64, FCIvector, NPArrayWithTag, ndarray], Tuple[ndarray, ndarray, List[ndarray], ndarray, ndarray]]: ...
    as_scanner = as_scanner
    def nuc_grad_method(self): ...
    to_gpu = lib.to_gpu
