from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import df as df, lib as lib
from pyscf.lib import logger as logger
from pyscf.mcscf.casci import CASCI, CASCI as CASCI
from pyscf.df.df import DF
from pyscf.mcscf.casci_symm import SymAdaptedCASCI
from pyscf.mcscf.mc1step import CASSCF
from pyscf.mcscf.mc1step_symm import SymAdaptedCASSCF
from pyscf.mcscf.ucasci import UCASCI
from typing import Iterator, Tuple, Union

def density_fit(casscf, auxbasis=None, with_df=None): ...

class _DFCAS:
    __name_mixin__: str
    with_df: Incomplete
    def __init__(self, mc: Union[CASCI, CASSCF, SymAdaptedCASCI, SymAdaptedCASSCF], with_df: DF) -> None: ...
    def undo_df(self): ...
    def dump_flags(self, verbose=None): ...
    def reset(self, mol=None): ...
    def get_veff(self, mol=None, dm=None, hermi: int = 1): ...
    def get_jk(self, mol, dm, hermi: int = 1, with_j: bool = True, with_k: bool = True, omega=None): ...
    def nuc_grad_method(self) -> None: ...

class _DFCASCI(_DFCAS):
    def get_h2eff(self, mo_coeff=None): ...

class _DFCASSCF(_DFCAS):
    get_h2eff: Incomplete
    def ao2mo(self, mo_coeff=None): ...
    def nuc_grad_method(self): ...

def approx_hessian(casscf: CASCI, auxbasis: None=None, with_df: None=None) -> CASCI: ...

class _DFHessianCASSCF:
    __name_mixin__: str
    with_df: Incomplete
    def __init__(self, mc: Union[CASSCF, SymAdaptedCASSCF, UCASCI], with_df: DF) -> None: ...
    def undo_df(self): ...
    def dump_flags(self, verbose=None) -> None: ...
    def reset(self, mol=None): ...
    def ao2mo(self, mo_coeff): ...
    def get_jk(self, mol, dm, hermi: int = 1, with_j: bool = True, with_k: bool = True, omega=None): ...

class _ERIS:
    feri: Incomplete
    ppaa: Incomplete
    papa: Incomplete
    j_pc: Incomplete
    k_pc: Incomplete
    vhf_c: Incomplete
    def __init__(self, casscf, mo, with_df) -> None: ...

def prange(start: int, end: int, step: int) -> Iterator[Tuple[int, int]]: ...
