from _typeshed import Incomplete
from pyscf import fci as fci, lib as lib, scf as scf
from pyscf.lib import logger as logger
from pyscf.mcscf import addons as addons, casci_symm as casci_symm, mc1step as mc1step, mc2step as mc2step

class SymAdaptedCASSCF(mc1step.CASSCF):
    __doc__: Incomplete
    fcisolver: Incomplete
    def __init__(self, mf_or_mol, ncas, nelecas, ncore=None, frozen=None) -> None: ...
    @property
    def wfnsym(self): ...
    @wfnsym.setter
    def wfnsym(self, wfnsym) -> None: ...
    def mc1step(self, mo_coeff=None, ci0=None, callback=None): ...
    def mc2step(self, mo_coeff=None, ci0=None, callback=None): ...
    mo_coeff: Incomplete
    def kernel(self, mo_coeff=None, ci0=None, callback=None, _kern=None): ...
    def uniq_var_indices(self, nmo, ncore, ncas, frozen): ...
    def rotate_mo(self, mo, u, log=None): ...
    def sort_mo_by_irrep(self, cas_irrep_nocc, cas_irrep_ncore=None, mo_coeff=None, s=None): ...
    def newton(self): ...
CASSCF = SymAdaptedCASSCF
