from _typeshed import Incomplete
from pyscf import fci as fci, lib as lib, scf as scf
from pyscf.lib import logger as logger
from pyscf.mcscf import addons as addons, casci_symm as casci_symm, mc1step as mc1step, mc2step as mc2step
from numpy import float64, ndarray
from pyscf.fci.direct_spin1 import FCIvector
from pyscf.lib.logger import Logger
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.mcscf.newton_casscf_symm import CASSCF
from pyscf.scf.hf_symm import SymAdaptedRHF, SymAdaptedROHF
from typing import Callable, Dict, List, Optional, Tuple, Union

class SymAdaptedCASSCF(mc1step.CASSCF):
    __doc__: Incomplete
    fcisolver: Incomplete
    def __init__(self, mf_or_mol: Union[SymAdaptedRHF, SymAdaptedROHF], ncas: int, nelecas: Union[int, Tuple[int, int]], ncore: Optional[int]=None, frozen: None=None) -> None: ...
    @property
    def wfnsym(self): ...
    @wfnsym.setter
    def wfnsym(self, wfnsym) -> None: ...
    def mc1step(self, mo_coeff: None=None, ci0: None=None, callback: None=None) -> Tuple[float64, float64, FCIvector, NPArrayWithTag, ndarray]: ...
    def mc2step(self, mo_coeff: Optional[NPArrayWithTag]=None, ci0: None=None, callback: None=None) -> Union[Tuple[float64, float64, ndarray, NPArrayWithTag, ndarray], Tuple[float64, float64, FCIvector, NPArrayWithTag, ndarray]]: ...
    mo_coeff: Incomplete
    def kernel(self, mo_coeff: Optional[NPArrayWithTag]=None, ci0: None=None, callback: None=None, _kern: Optional[Callable]=None) -> Union[Tuple[float64, float64, ndarray, NPArrayWithTag, ndarray], Tuple[float64, float64, FCIvector, NPArrayWithTag, ndarray]]: ...
    def uniq_var_indices(self, nmo: int, ncore: int, ncas: int, frozen: Optional[Union[int, List[int]]]) -> ndarray: ...
    def rotate_mo(self, mo: NPArrayWithTag, u: ndarray, log: Optional[Logger]=None) -> NPArrayWithTag: ...
    def sort_mo_by_irrep(self, cas_irrep_nocc: Dict[str, int], cas_irrep_ncore: None=None, mo_coeff: None=None, s: None=None) -> NPArrayWithTag: ...
    def newton(self) -> "CASSCF": ...
CASSCF = SymAdaptedCASSCF
