from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, ao2mo as ao2mo, gto as gto, lib as lib, scf as scf
from pyscf.lib import logger as logger
from pyscf.mcscf import casci as casci, chkfile as chkfile, mc_ao2mo as mc_ao2mo
from pyscf.mcscf.casci import CASCI as CASCI, canonicalize as canonicalize, cas_natorb as cas_natorb, get_fock as get_fock
from pyscf.soscf import ciah as ciah

WITH_MICRO_SCHEDULER: Incomplete
WITH_STEPSIZE_SCHEDULER: Incomplete

def gen_g_hop(casscf, mo, u, casdm1, casdm2, eris): ...
def rotate_orb_cc(casscf, mo, fcivec, fcasdm1, fcasdm2, eris, x0_guess=None, conv_tol_grad: float = 0.0001, max_stepsize=None, verbose=None) -> Generator[Incomplete, None, Incomplete]: ...
def kernel(casscf, mo_coeff, tol: float = 1e-07, conv_tol_grad=None, ci0=None, callback=None, verbose=..., dump_chk: bool = True): ...
def as_scanner(mc): ...

class CASSCF_Scanner(lib.SinglePointScanner):
    def __init__(self, mc) -> None: ...
    mol: Incomplete
    def __call__(self, mol_or_geom, mo_coeff=None, ci0=None): ...

def max_stepsize_scheduler(casscf, envs): ...

class CASSCF(casci.CASBase):
    __doc__: Incomplete
    max_stepsize: Incomplete
    max_cycle_macro: Incomplete
    max_cycle_micro: Incomplete
    conv_tol: Incomplete
    conv_tol_grad: Incomplete
    ah_level_shift: Incomplete
    ah_conv_tol: Incomplete
    ah_max_cycle: Incomplete
    ah_lindep: Incomplete
    ah_start_tol: Incomplete
    ah_start_cycle: Incomplete
    ah_grad_trust_region: Incomplete
    internal_rotation: Incomplete
    ci_response_space: Incomplete
    ci_grad_trust_region: Incomplete
    with_dep4: Incomplete
    chk_ci: Incomplete
    kf_interval: Incomplete
    kf_trust_region: Incomplete
    ao2mo_level: Incomplete
    natorb: Incomplete
    canonicalization: Incomplete
    sorting_mo_energy: Incomplete
    scale_restoration: Incomplete
    small_rot_tol: Incomplete
    extrasym: Incomplete
    callback: Incomplete
    frozen: Incomplete
    chkfile: Incomplete
    e_tot: Incomplete
    e_cas: Incomplete
    ci: Incomplete
    mo_coeff: Incomplete
    mo_energy: Incomplete
    converged: bool
    def __init__(self, mf_or_mol, ncas: int = 0, nelecas: int = 0, ncore=None, frozen=None) -> None: ...
    def dump_flags(self, verbose=None): ...
    def kernel(self, mo_coeff=None, ci0=None, callback=None, _kern=...): ...
    def mc1step(self, mo_coeff=None, ci0=None, callback=None): ...
    def mc2step(self, mo_coeff=None, ci0=None, callback=None): ...
    def casci(self, mo_coeff, ci0=None, eris=None, verbose=None, envs=None): ...
    as_scanner = as_scanner
    def uniq_var_indices(self, nmo, ncore, ncas, frozen): ...
    def pack_uniq_var(self, mat): ...
    def unpack_uniq_var(self, v): ...
    def update_rotate_matrix(self, dx, u0: int = 1): ...
    gen_g_hop = gen_g_hop
    rotate_orb_cc = rotate_orb_cc
    def update_ao2mo(self, mo) -> None: ...
    def ao2mo(self, mo_coeff=None): ...
    get_h2eff: Incomplete
    def update_jk_in_ah(self, mo, r, casdm1, eris): ...
    def update_casdm(self, mo, u, fcivec, e_cas, eris, envs={}): ...
    def solve_approx_ci(self, h1, h2, ci0, ecore, e_cas, envs): ...
    def get_grad(self, mo_coeff=None, casdm1_casdm2=None, eris=None): ...
    def dump_chk(self, envs_or_file): ...
    def update_from_chk(self, chkfile=None): ...
    update = update_from_chk
    def rotate_mo(self, mo, u, log=None): ...
    def micro_cycle_scheduler(self, envs): ...
    max_stepsize_scheduler = max_stepsize_scheduler
    def ah_scheduler(self, envs) -> None: ...
    @property
    def max_orb_stepsize(self): ...
    @max_orb_stepsize.setter
    def max_orb_stepsize(self, x) -> None: ...
    @property
    def ci_update_dep(self): ...
    @ci_update_dep.setter
    def ci_update_dep(self, x) -> None: ...
    grad_update_dep = ci_update_dep
    @property
    def max_cycle(self): ...
    @max_cycle.setter
    def max_cycle(self, x) -> None: ...
    def approx_hessian(self, auxbasis=None, with_df=None): ...
    def nuc_grad_method(self): ...
    def newton(self): ...
    def reset(self, mol=None) -> None: ...
    to_gpu = lib.to_gpu

def expmat(a): ...
