from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, ao2mo as ao2mo, gto as gto, lib as lib, scf as scf
from pyscf.lib import logger as logger
from pyscf.mcscf import casci as casci, chkfile as chkfile, mc_ao2mo as mc_ao2mo
from pyscf.mcscf.casci import CASCI, CASCI as CASCI, canonicalize as canonicalize, cas_natorb as cas_natorb, get_fock as get_fock
from pyscf.soscf import ciah as ciah
from numpy import float64, ndarray
from pyscf.dft.rks import RKS
from pyscf.fci.direct_spin1 import FCIvector
from pyscf.gto.mole import Mole
from pyscf.lib.logger import Logger
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.mcscf.mc1step_symm import SymAdaptedCASSCF
from pyscf.mcscf.umc1step import UCASSCF
from pyscf.scf.hf import RHF
from pyscf.scf.hf_symm import SymAdaptedRHF, SymAdaptedROHF
from pyscf.scf.rohf import ROHF
from typing import Any, Callable, Dict, Iterator, List, Optional, Tuple, Union

WITH_MICRO_SCHEDULER: Incomplete
WITH_STEPSIZE_SCHEDULER: Incomplete

def gen_g_hop(casscf: Union[Incomplete, Incomplete, SymAdaptedCASSCF, CASSCF_Scanner], mo: Union[ndarray, NPArrayWithTag], u: int, casdm1: ndarray, casdm2: ndarray, eris: Incomplete) -> Tuple[ndarray, Callable, Callable, ndarray]: ...
def rotate_orb_cc(casscf: Union[Incomplete, SymAdaptedCASSCF, CASSCF_Scanner, UCASSCF], mo: Union[ndarray, NPArrayWithTag, Tuple[ndarray, ndarray], Tuple[NPArrayWithTag, NPArrayWithTag]], fcivec: Callable, fcasdm1: Callable, fcasdm2: Callable, eris: Union[Incomplete, Incomplete], x0_guess: Optional[ndarray]=None, conv_tol_grad: Union[float, float64] = 0.0001, max_stepsize: Optional[float]=None, verbose: Optional[Logger]=None) -> Iterator[Union[Tuple[Tuple[ndarray, ndarray], ndarray, int, ndarray], Tuple[ndarray, ndarray, int, ndarray]]]: ...
def kernel(casscf: Union[Incomplete, SymAdaptedCASSCF, CASSCF_Scanner], mo_coeff: Union[ndarray, NPArrayWithTag], tol: float = 1e-07, conv_tol_grad: Optional[float]=None, ci0: Optional[FCIvector]=None, callback: Optional[Callable]=None, verbose: int=..., dump_chk: bool = True) -> Union[Tuple[bool, float64, float64, FCIvector, ndarray, ndarray], Tuple[bool, float64, float64, FCIvector, NPArrayWithTag, ndarray], Tuple[bool, float64, float64, ndarray, ndarray, ndarray], Tuple[bool, float64, float64, ndarray, NPArrayWithTag, ndarray]]: ...
def as_scanner(mc: Union[Incomplete, CASSCF_Scanner]) -> "CASSCF_Scanner": ...

class CASSCF_Scanner(lib.SinglePointScanner):
    def __init__(self, mc: Union[Incomplete, SymAdaptedCASSCF, UCASSCF]) -> None: ...
    mol: Incomplete
    def __call__(self, mol_or_geom: Union[Mole, str], mo_coeff: None=None, ci0: None=None) -> float64: ...

def max_stepsize_scheduler(casscf: Union[CASSCF_Scanner, Incomplete, SymAdaptedCASSCF, UCASSCF], envs: Dict[str, Any]) -> float: ...

class CASSCF(casci.CASBase):
    __doc__: Incomplete
    max_stepsize: Incomplete
    max_cycle_macro: Incomplete
    max_cycle_micro: Incomplete
    conv_tol: Incomplete
    conv_tol_grad: Incomplete
    ah_level_shift: Incomplete
    ah_conv_tol: Incomplete
    ah_max_cycle: Incomplete
    ah_lindep: Incomplete
    ah_start_tol: Incomplete
    ah_start_cycle: Incomplete
    ah_grad_trust_region: Incomplete
    internal_rotation: Incomplete
    ci_response_space: Incomplete
    ci_grad_trust_region: Incomplete
    with_dep4: Incomplete
    chk_ci: Incomplete
    kf_interval: Incomplete
    kf_trust_region: Incomplete
    ao2mo_level: Incomplete
    natorb: Incomplete
    canonicalization: Incomplete
    sorting_mo_energy: Incomplete
    scale_restoration: Incomplete
    small_rot_tol: Incomplete
    extrasym: Incomplete
    callback: Incomplete
    frozen: Incomplete
    chkfile: Incomplete
    e_tot: Incomplete
    e_cas: Incomplete
    ci: Incomplete
    mo_coeff: Incomplete
    mo_energy: Incomplete
    converged: bool
    def __init__(self, mf_or_mol: Union[RHF, ROHF, SymAdaptedRHF, SymAdaptedROHF, RKS], ncas: int = 0, nelecas: Union[int, Tuple[int, int]] = 0, ncore: Optional[int]=None, frozen: None=None) -> None: ...
    def dump_flags(self, verbose: None=None) -> Union[Incomplete, SymAdaptedCASSCF, CASSCF_Scanner]: ...
    def kernel(self, mo_coeff: Optional[ndarray]=None, ci0: Optional[FCIvector]=None, callback: None=None, _kern: Callable=...) -> Union[Tuple[float64, float64, FCIvector, ndarray, ndarray], Tuple[float64, float64, ndarray, ndarray, ndarray]]: ...
    def mc1step(self, mo_coeff: Optional[ndarray]=None, ci0: None=None, callback: None=None) -> Tuple[float64, float64, FCIvector, ndarray, ndarray]: ...
    def mc2step(self, mo_coeff: Optional[ndarray]=None, ci0: None=None, callback: None=None) -> Tuple[float64, float64, FCIvector, ndarray, ndarray]: ...
    def casci(self, mo_coeff: Union[ndarray, NPArrayWithTag], ci0: Optional[Union[FCIvector, ndarray]]=None, eris: Optional[Incomplete]=None, verbose: Optional[Logger]=None, envs: Optional[Any]=None) -> Tuple[float64, float64, FCIvector]: ...
    as_scanner = as_scanner
    def uniq_var_indices(self, nmo: int, ncore: int, ncas: int, frozen: Optional[Union[int, List[int]]]) -> ndarray: ...
    def pack_uniq_var(self, mat: ndarray) -> ndarray: ...
    def unpack_uniq_var(self, v: ndarray) -> ndarray: ...
    def update_rotate_matrix(self, dx: ndarray, u0: Union[ndarray, int] = 1) -> ndarray: ...
    gen_g_hop = gen_g_hop
    rotate_orb_cc = rotate_orb_cc
    def update_ao2mo(self, mo) -> None: ...
    def ao2mo(self, mo_coeff: Optional[Union[NPArrayWithTag, ndarray]]=None) -> Incomplete: ...
    get_h2eff: Incomplete
    def update_jk_in_ah(self, mo: Union[ndarray, NPArrayWithTag], r: ndarray, casdm1: ndarray, eris: Incomplete) -> Union[Tuple[ndarray, ndarray], Tuple[ndarray, NPArrayWithTag]]: ...
    def update_casdm(self, mo: Union[ndarray, NPArrayWithTag], u: ndarray, fcivec: Union[ndarray, FCIvector], e_cas: float64, eris: Incomplete, envs: Dict[str, Any]={}) -> Union[Tuple[ndarray, ndarray, None, FCIvector], Tuple[ndarray, ndarray, ndarray, FCIvector], Tuple[ndarray, ndarray, ndarray, ndarray]]: ...
    def solve_approx_ci(self, h1: ndarray, h2: ndarray, ci0: Union[ndarray, FCIvector], ecore: float64, e_cas: float64, envs: Dict[str, Any]) -> Union[Tuple[ndarray, ndarray], Tuple[FCIvector, None], Tuple[FCIvector, ndarray]]: ...
    def get_grad(self, mo_coeff: None=None, casdm1_casdm2: None=None, eris: None=None) -> ndarray: ...
    def dump_chk(self, envs_or_file: Dict[str, Any]) -> Union[Incomplete, SymAdaptedCASSCF, CASSCF_Scanner]: ...
    def update_from_chk(self, chkfile: Optional[str]=None) -> Incomplete: ...
    update = update_from_chk
    def rotate_mo(self, mo: Union[ndarray, NPArrayWithTag], u: ndarray, log: Optional[Logger]=None) -> Union[ndarray, NPArrayWithTag]: ...
    def micro_cycle_scheduler(self, envs: Dict[str, Any]) -> int: ...
    max_stepsize_scheduler = max_stepsize_scheduler
    def ah_scheduler(self, envs) -> None: ...
    @property
    def max_orb_stepsize(self): ...
    @max_orb_stepsize.setter
    def max_orb_stepsize(self, x) -> None: ...
    @property
    def ci_update_dep(self): ...
    @ci_update_dep.setter
    def ci_update_dep(self, x) -> None: ...
    grad_update_dep = ci_update_dep
    @property
    def max_cycle(self): ...
    @max_cycle.setter
    def max_cycle(self, x) -> None: ...
    def approx_hessian(self, auxbasis=None, with_df=None): ...
    def nuc_grad_method(self): ...
    def newton(self) -> Incomplete: ...
    def reset(self, mol: Optional[Mole]=None) -> None: ...
    to_gpu = lib.to_gpu

def expmat(a: ndarray) -> ndarray: ...
