from pyscf import gto as gto

def mdot(*args): ...
def MakeShellsForElement(mol, Element): ...
def MakeShells(mol, Elements): ...
def Atoms_w_Coords(mol): ...
def MakePiOS(mol, mf, PiAtomsList, nPiOcc=None, nPiVirt=None): ...
def rmsd(a, b=None): ...
def MakeSmh(S): ...
def MakeIaosRaw(COcc, S1, S2, S12): ...
def GetPzOrientation(iTargetAtoms, Coords_, Elements_): ...
def FindValenceAoIndices(iAt, Shells, TargetL): ...
def MakePzMinaoVectors(iTargetAtoms, vPz, Shells): ...
def GetCovalentRadius(At): ...
def GetNumPiElec(iAt, Elements, Coords): ...
def SemiCanonicalize(COut, Fock, S1, Name, Print: bool = True): ...
def MakeOverlappingOrbSubspace(Space, Name, COrb, nOrbExpected, CTargetIb, S1, Fock): ...
def MakePiSystemOrbitals(TargetName, iTargetAtomsForPlane_, iTargetAtomsForBasis_, Elements, Coords, CIb, Shells, S1, S12, S2, Fock, COcc, CVir): ...
