from _typeshed import Incomplete
from pyscf import __config__ as __config__, fci as fci, gto as gto, lib as lib, scf as scf
from pyscf.lib import logger as logger
from pyscf.mcscf import addons as addons
from pyscf.mcscf.casci import CASBase as CASBase, as_scanner as as_scanner

WITH_META_LOWDIN: Incomplete
LARGE_CI_TOL: Incomplete
RANGE_TYPE = range

def extract_orbs(mo_coeff, ncas, nelecas, ncore): ...
def h1e_for_cas(casci, mo_coeff=None, ncas=None, ncore=None): ...
def kernel(casci, mo_coeff=None, ci0=None, verbose=..., envs=None): ...

class UCASBase(CASBase):
    mol: Incomplete
    verbose: Incomplete
    stdout: Incomplete
    max_memory: Incomplete
    ncas: Incomplete
    nelecas: Incomplete
    fcisolver: Incomplete
    mo_coeff: Incomplete
    ci: Incomplete
    e_tot: int
    e_cas: int
    def __init__(self, mf_or_mol, ncas: int = 0, nelecas: int = 0, ncore=None) -> None: ...
    @property
    def ncore(self): ...
    @ncore.setter
    def ncore(self, x) -> None: ...
    def dump_flags(self, verbose=None): ...
    def check_sanity(self): ...
    def get_hcore(self, mol=None): ...
    def get_veff(self, mol=None, dm=None, hermi: int = 1): ...
    get_h1eff = h1e_for_cas
    def cas_natorb(self, mo_coeff=None, ci0=None): ...
    def cas_natorb_(self, mo_coeff=None, ci0=None): ...
    def analyze(self, mo_coeff=None, ci=None, verbose=None, large_ci_tol=..., with_meta_lowdin=..., **kwargs): ...
    def spin_square(self, fcivec=None, mo_coeff=None, ovlp=None): ...
    fix_spin_: Incomplete
    fix_spin: Incomplete
    def sort_mo(self, caslst, mo_coeff=None, base: int = 1): ...
    def make_rdm1s(self, mo_coeff=None, ci=None, ncas=None, nelecas=None, ncore=None, **kwargs): ...
    def make_rdm1(self, mo_coeff=None, ci=None, ncas=None, nelecas=None, ncore=None, **kwargs): ...

class UCASCI(UCASBase):
    def get_h2eff(self, mo_coeff=None): ...
    def casci(self, mo_coeff=None, ci0=None): ...
    mo_coeff: Incomplete
    def kernel(self, mo_coeff=None, ci0=None): ...
    as_scanner = as_scanner
CASCI = UCASCI
