from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.mcscf import chkfile as chkfile, ucasci as ucasci, umc_ao2mo as umc_ao2mo
from pyscf.mcscf.mc1step import as_scanner as as_scanner, expmat as expmat, max_stepsize_scheduler as max_stepsize_scheduler, rotate_orb_cc as rotate_orb_cc
from numpy import float64, ndarray
from pyscf.fci.direct_spin1 import FCIvector
from pyscf.lib.logger import Logger
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.mcscf.ucasci import UCASCI
from pyscf.mcscf.umc_ao2mo import _ERIS
from pyscf.scf.uhf import UHF
from pyscf.scf.uhf_symm import SymAdaptedUHF
from typing import Any, Callable, Dict, List, Optional, Tuple, Union

def gen_g_hop(casscf: "UCASSCF", mo: Union[ndarray, Tuple[ndarray, ndarray], Tuple[NPArrayWithTag, NPArrayWithTag]], u: int, casdm1s: Tuple[ndarray, ndarray], casdm2s: Tuple[ndarray, ndarray, ndarray], eris: _ERIS) -> Tuple[ndarray, Callable, Callable, ndarray]: ...
def kernel(casscf: "UCASSCF", mo_coeff: Union[ndarray, Tuple[NPArrayWithTag, NPArrayWithTag]], tol: float = 1e-07, conv_tol_grad: Optional[float]=None, ci0: None=None, callback: None=None, verbose: Optional[int]=None, dump_chk: bool = True) -> Union[Tuple[bool, float64, float64, FCIvector, ndarray], Tuple[bool, float64, float64, FCIvector, Tuple[NPArrayWithTag, NPArrayWithTag]], Tuple[bool, float64, float64, FCIvector, Tuple[ndarray, ndarray]]]: ...

class UCASSCF(ucasci.UCASBase):
    max_stepsize: Incomplete
    max_cycle_macro: Incomplete
    max_cycle_micro: Incomplete
    conv_tol: Incomplete
    conv_tol_grad: Incomplete
    ah_level_shift: Incomplete
    ah_conv_tol: Incomplete
    ah_max_cycle: Incomplete
    ah_lindep: Incomplete
    ah_start_tol: Incomplete
    ah_start_cycle: Incomplete
    ah_grad_trust_region: Incomplete
    internal_rotation: Incomplete
    ci_response_space: Incomplete
    with_dep4: Incomplete
    chk_ci: Incomplete
    kf_interval: Incomplete
    kf_trust_region: Incomplete
    natorb: Incomplete
    callback: Incomplete
    frozen: Incomplete
    chkfile: Incomplete
    e_tot: Incomplete
    e_cas: Incomplete
    ci: Incomplete
    mo_coeff: Incomplete
    converged: bool
    def __init__(self, mf_or_mol: Union[SymAdaptedUHF, UHF], ncas: int = 0, nelecas: Union[int, Tuple[int, int]] = 0, ncore: None=None, frozen: None=None) -> None: ...
    def dump_flags(self, verbose: None=None) -> None: ...
    def kernel(self, mo_coeff: None=None, ci0: None=None, callback: None=None, _kern: Callable=...) -> Union[Tuple[float64, float64, FCIvector, Tuple[ndarray, ndarray]], Tuple[float64, float64, FCIvector, ndarray], Tuple[float64, float64, FCIvector, Tuple[NPArrayWithTag, NPArrayWithTag]]]: ...
    def mc1step(self, mo_coeff: None=None, ci0: None=None, callback: None=None) -> Tuple[float64, float64, FCIvector, Tuple[NPArrayWithTag, NPArrayWithTag]]: ...
    def mc2step(self, mo_coeff=None, ci0=None, callback=None): ...
    get_h2eff: Incomplete
    def casci(self, mo_coeff: Union[ndarray, Tuple[ndarray, ndarray], Tuple[NPArrayWithTag, NPArrayWithTag]], ci0: Optional[Union[ndarray, FCIvector]]=None, eris: Optional[_ERIS]=None, verbose: Optional[Logger]=None, envs: Optional[Any]=None) -> Tuple[float64, float64, FCIvector]: ...
    def uniq_var_indices(self, nmo: int, ncore: int, ncas: int, frozen: Optional[int]) -> ndarray: ...
    def pack_uniq_var(self, mat: Union[List[ndarray], Tuple[ndarray, ndarray]]) -> ndarray: ...
    def unpack_uniq_var(self, v: ndarray) -> ndarray: ...
    def update_rotate_matrix(self, dx: ndarray, u0: Union[int, Tuple[ndarray, ndarray]] = 1) -> Tuple[ndarray, ndarray]: ...
    def gen_g_hop(self, *args) -> Tuple[ndarray, Callable, Callable, ndarray]: ...
    rotate_orb_cc = rotate_orb_cc
    def ao2mo(self, mo_coeff: Optional[Union[ndarray, Tuple[ndarray, ndarray], Tuple[NPArrayWithTag, NPArrayWithTag]]]=None) -> _ERIS: ...
    def update_jk_in_ah(self, mo: Union[ndarray, Tuple[ndarray, ndarray], Tuple[NPArrayWithTag, NPArrayWithTag]], r: Tuple[ndarray, ndarray], casdm1s: Tuple[ndarray, ndarray], eris: _ERIS) -> Tuple[Tuple[ndarray, ndarray], Tuple[ndarray, ndarray]]: ...
    def update_casdm(self, mo: Union[ndarray, Tuple[ndarray, ndarray], Tuple[NPArrayWithTag, NPArrayWithTag]], u: Tuple[ndarray, ndarray], fcivec: Union[ndarray, FCIvector], e_cas: float64, eris: _ERIS) -> Union[Tuple[Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray], None, FCIvector], Tuple[Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray], ndarray, ndarray]]: ...
    def approx_cas_integral(self, mo: Union[ndarray, Tuple[ndarray, ndarray], Tuple[NPArrayWithTag, NPArrayWithTag]], u: Tuple[ndarray, ndarray], eris: _ERIS) -> Tuple[float64, Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]]: ...
    def solve_approx_ci(self, h1: Tuple[ndarray, ndarray], h2: Tuple[ndarray, ndarray, ndarray], ci0: Union[ndarray, FCIvector], ecore: float64, e_cas: float64) -> Union[Tuple[ndarray, ndarray], Tuple[FCIvector, None]]: ...
    def dump_chk(self, envs_or_file: Dict[str, Any]) -> "UCASSCF": ...
    def rotate_mo(self, mo: Union[ndarray, Tuple[ndarray, ndarray], Tuple[NPArrayWithTag, NPArrayWithTag]], u: Tuple[ndarray, ndarray], log: Optional[Logger]=None) -> Union[Tuple[ndarray, ndarray], Tuple[NPArrayWithTag, NPArrayWithTag]]: ...
    def micro_cycle_scheduler(self, envs: Dict[str, Any]) -> int: ...
    max_stepsize_scheduler = max_stepsize_scheduler
    as_scanner = as_scanner
    @property
    def max_orb_stepsize(self): ...
    @max_orb_stepsize.setter
    def max_orb_stepsize(self, x) -> None: ...
    def reset(self, mol=None) -> None: ...
CASSCF = UCASSCF
