from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.mcscf import chkfile as chkfile, ucasci as ucasci, umc_ao2mo as umc_ao2mo
from pyscf.mcscf.mc1step import as_scanner as as_scanner, expmat as expmat, max_stepsize_scheduler as max_stepsize_scheduler, rotate_orb_cc as rotate_orb_cc

def gen_g_hop(casscf, mo, u, casdm1s, casdm2s, eris): ...
def kernel(casscf, mo_coeff, tol: float = 1e-07, conv_tol_grad=None, ci0=None, callback=None, verbose=None, dump_chk: bool = True): ...

class UCASSCF(ucasci.UCASBase):
    max_stepsize: Incomplete
    max_cycle_macro: Incomplete
    max_cycle_micro: Incomplete
    conv_tol: Incomplete
    conv_tol_grad: Incomplete
    ah_level_shift: Incomplete
    ah_conv_tol: Incomplete
    ah_max_cycle: Incomplete
    ah_lindep: Incomplete
    ah_start_tol: Incomplete
    ah_start_cycle: Incomplete
    ah_grad_trust_region: Incomplete
    internal_rotation: Incomplete
    ci_response_space: Incomplete
    with_dep4: Incomplete
    chk_ci: Incomplete
    kf_interval: Incomplete
    kf_trust_region: Incomplete
    natorb: Incomplete
    callback: Incomplete
    frozen: Incomplete
    chkfile: Incomplete
    e_tot: Incomplete
    e_cas: Incomplete
    ci: Incomplete
    mo_coeff: Incomplete
    converged: bool
    def __init__(self, mf_or_mol, ncas: int = 0, nelecas: int = 0, ncore=None, frozen=None) -> None: ...
    def dump_flags(self, verbose=None) -> None: ...
    def kernel(self, mo_coeff=None, ci0=None, callback=None, _kern=...): ...
    def mc1step(self, mo_coeff=None, ci0=None, callback=None): ...
    def mc2step(self, mo_coeff=None, ci0=None, callback=None): ...
    get_h2eff: Incomplete
    def casci(self, mo_coeff, ci0=None, eris=None, verbose=None, envs=None): ...
    def uniq_var_indices(self, nmo, ncore, ncas, frozen): ...
    def pack_uniq_var(self, mat): ...
    def unpack_uniq_var(self, v): ...
    def update_rotate_matrix(self, dx, u0: int = 1): ...
    def gen_g_hop(self, *args): ...
    rotate_orb_cc = rotate_orb_cc
    def ao2mo(self, mo_coeff=None): ...
    def update_jk_in_ah(self, mo, r, casdm1s, eris): ...
    def update_casdm(self, mo, u, fcivec, e_cas, eris): ...
    def approx_cas_integral(self, mo, u, eris): ...
    def solve_approx_ci(self, h1, h2, ci0, ecore, e_cas): ...
    def dump_chk(self, envs_or_file): ...
    def rotate_mo(self, mo, u, log=None): ...
    def micro_cycle_scheduler(self, envs): ...
    max_stepsize_scheduler = max_stepsize_scheduler
    as_scanner = as_scanner
    @property
    def max_orb_stepsize(self): ...
    @max_orb_stepsize.setter
    def max_orb_stepsize(self, x) -> None: ...
    def reset(self, mol=None) -> None: ...
CASSCF = UCASSCF
