from pyscf import scf as scf
from pyscf.mp import dfgmp2 as dfgmp2, dfmp2 as dfmp2, dfump2 as dfump2, gmp2 as gmp2, mp2 as mp2, ump2 as ump2

def MP2(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def RMP2(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def UMP2(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def GMP2(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
