from _typeshed import Incomplete
from pyscf import __config__ as __config__, df as df, lib as lib, scf as scf
from pyscf.lib import logger as logger
from pyscf.mp import mp2 as mp2
from pyscf.mp.mp2 import make_rdm1 as make_rdm1, make_rdm2 as make_rdm2

WITH_T2: Incomplete
THRESH_LINDEP: Incomplete
libmp: Incomplete

def kernel(mp, mo_energy=None, mo_coeff=None, eris=None, with_t2=..., verbose=None): ...

class DFRMP2(mp2.RMP2):
    mo_energy: Incomplete
    with_df: Incomplete
    force_outcore: bool
    def __init__(self, mf, frozen=None, mo_coeff=None, mo_occ=None, mo_energy=None) -> None: ...
    kernel: Incomplete
    def split_mo_coeff(self, mo_coeff=None): ...
    def split_mo_energy(self, mo_energy=None): ...
    def split_mo_occ(self, mo_occ=None): ...
    def reset(self, mol=None): ...
    def ao2mo(self, mo_coeff=None, ovL=None, ovL_to_save=None): ...
    def make_rdm1(self, t2=None, ao_repr: bool = False, with_frozen: bool = True): ...
    def make_rdm2(self, t2=None, ao_repr: bool = False): ...
    def nuc_grad_method(self) -> None: ...
    def update_amps(self, t2, eris) -> None: ...
    def init_amps(self, mo_energy=None, mo_coeff=None, eris=None, with_t2=...): ...
    Gradients = NotImplemented
MP2 = DFRMP2
DFMP2 = DFRMP2

def get_mo_energy(mf, mo_coeff, mo_occ, mo_energy=None): ...

class _DFINCOREERIS:
    with_df: Incomplete
    occ_coeff: Incomplete
    vir_coeff: Incomplete
    max_memory: Incomplete
    verbose: Incomplete
    stdout: Incomplete
    dtype: Incomplete
    dsize: int
    ovL: Incomplete
    def __init__(self, with_df, occ_coeff, vir_coeff, max_memory, ovL=None, verbose=None, stdout=None) -> None: ...
    @property
    def nocc(self): ...
    @property
    def nvir(self): ...
    @property
    def naux(self): ...
    def build(self) -> None: ...
    def get_occ_blk(self, i0, i1): ...
    def get_ov_blk(self, ia0, ia1): ...

class _DFOUTCOREERIS(_DFINCOREERIS):
    def __init__(self, with_df, occ_coeff, vir_coeff, max_memory, ovL=None, ovL_to_save=None, verbose=None, stdout=None) -> None: ...
    feri: Incomplete
    ovL: Incomplete
    def build(self) -> None: ...
