from _typeshed import Incomplete
from pyscf import __config__ as __config__, df as df, lib as lib, scf as scf
from pyscf.lib import logger as logger
from pyscf.mp import mp2 as mp2
from pyscf.mp.mp2 import make_rdm1 as make_rdm1, make_rdm2 as make_rdm2
from h5py._hl.dataset import Dataset
from io import TextIOWrapper
from numpy import ndarray
from pyscf.df.df import DF
from pyscf.gto.mole import Mole
from pyscf.lib.logger import Logger
from pyscf.lib.misc import H5FileWrap, H5TmpFile
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.mp.dfmp2_slow import DFMP2
from pyscf.pbc.df.df import GDF
from pyscf.scf.ghf import GHF
from typing import List, Optional, Tuple, Union

WITH_T2: Incomplete
THRESH_LINDEP: Incomplete
libmp: Incomplete

def kernel(mp: "DFRMP2", mo_energy: Optional[ndarray]=None, mo_coeff: Optional[ndarray]=None, eris: Optional[Union[_DFOUTCOREERIS, _DFINCOREERIS]]=None, with_t2: bool=..., verbose: None=None) -> Union[Tuple[NPArrayWithTag, None], Tuple[NPArrayWithTag, ndarray]]: ...

class DFRMP2(mp2.RMP2):
    mo_energy: Incomplete
    with_df: Incomplete
    force_outcore: bool
    def __init__(self, mf: Union[Incomplete, GHF, Incomplete, Incomplete, Incomplete], frozen: Optional[Union[ndarray, int, List[List[int]], List[int]]]=None, mo_coeff: Optional[ndarray]=None, mo_occ: Optional[ndarray]=None, mo_energy: None=None) -> None: ...
    kernel: Incomplete
    def split_mo_coeff(self, mo_coeff: None=None) -> List[ndarray]: ...
    def split_mo_energy(self, mo_energy: None=None) -> List[ndarray]: ...
    def split_mo_occ(self, mo_occ=None): ...
    def reset(self, mol: Optional[Mole]=None) -> "DFRMP2": ...
    def ao2mo(self, mo_coeff: Optional[ndarray]=None, ovL: Optional[Union[str, ndarray]]=None, ovL_to_save: Optional[str]=None) -> Union[_DFOUTCOREERIS, _DFINCOREERIS]: ...
    def make_rdm1(self, t2: None=None, ao_repr: bool = False, with_frozen: bool = True) -> ndarray: ...
    def make_rdm2(self, t2=None, ao_repr: bool = False): ...
    def nuc_grad_method(self) -> None: ...
    def update_amps(self, t2, eris) -> None: ...
    def init_amps(self, mo_energy: Optional[ndarray]=None, mo_coeff: Optional[ndarray]=None, eris: Optional[Union[_DFOUTCOREERIS, _DFINCOREERIS]]=None, with_t2: bool=...) -> Union[Tuple[NPArrayWithTag, None], Tuple[NPArrayWithTag, ndarray]]: ...
    Gradients = NotImplemented
MP2 = DFRMP2
DFMP2 = DFRMP2

def get_mo_energy(mf: Union[Incomplete, GHF, Incomplete, Incomplete, Incomplete], mo_coeff: ndarray, mo_occ: ndarray, mo_energy: None=None) -> ndarray: ...

class _DFINCOREERIS:
    with_df: Incomplete
    occ_coeff: Incomplete
    vir_coeff: Incomplete
    max_memory: Incomplete
    verbose: Incomplete
    stdout: Incomplete
    dtype: Incomplete
    dsize: int
    ovL: Incomplete
    def __init__(self, with_df: Union[GDF, DF], occ_coeff: ndarray, vir_coeff: ndarray, max_memory: int, ovL: Optional[ndarray]=None, verbose: Optional[int]=None, stdout: Optional[TextIOWrapper]=None) -> None: ...
    @property
    def nocc(self) -> int: ...
    @property
    def nvir(self) -> int: ...
    @property
    def naux(self) -> int: ...
    def build(self) -> None: ...
    def get_occ_blk(self, i0: int, i1: int) -> ndarray: ...
    def get_ov_blk(self, ia0, ia1): ...

class _DFOUTCOREERIS(_DFINCOREERIS):
    def __init__(self, with_df: Union[GDF, DF], occ_coeff: ndarray, vir_coeff: ndarray, max_memory: int, ovL: Optional[str]=None, ovL_to_save: Optional[str]=None, verbose: Optional[int]=None, stdout: Optional[TextIOWrapper]=None) -> None: ...
    feri: Incomplete
    ovL: Incomplete
    def build(self) -> None: ...
