import types
from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import df as df, gto as gto, lib as lib, scf as scf
from pyscf.scf import cphf as cphf
from h5py._hl.dataset import Dataset
from numpy import float64, ndarray
from pyscf.gto.mole import Mole
from pyscf.lib.logger import Logger
from pyscf.lib.misc import H5TmpFile
from pyscf.mp.dfump2_native import DFUMP2, SCSDFUMP2
from pyscf.scf.hf import RHF
from typing import Iterator, List, Optional, Tuple, Union

class DFRMP2(lib.StreamObject):
    mo_coeff: Incomplete
    mo_energy: Incomplete
    nocc: Incomplete
    nmo: Incomplete
    e_scf: Incomplete
    frozen_mask: Incomplete
    occ_mask: Incomplete
    mol: Incomplete
    auxmol: Incomplete
    verbose: Incomplete
    stdout: Incomplete
    max_memory: Incomplete
    e_corr: Incomplete
    ps: float
    pt: float
    cphf_max_cycle: int
    cphf_tol: Incomplete
    def __init__(self, mf: RHF, frozen: Optional[Union[int, List[int]]]=None, auxbasis: None=None) -> None: ...
    def dump_flags(self, logger: Optional[Logger]=None) -> None: ...
    @property
    def e_tot(self) -> float64: ...
    def calculate_energy(self) -> float64: ...
    def make_rdm1(self, relaxed: bool = False, ao_repr: bool = False) -> ndarray: ...
    def make_rdm1_unrelaxed(self, ao_repr: bool = False): ...
    def make_rdm1_relaxed(self, ao_repr: bool = False): ...
    def make_natorbs(self, rdm1_mo: None=None, relaxed: bool = False) -> Tuple[ndarray, ndarray]: ...
    @property
    def has_ints(self) -> bool: ...
    def calculate_integrals_(self) -> None: ...
    def delete(self) -> None: ...
    def __enter__(self) -> Union[SCSDFRMP2, SCSDFUMP2, DFRMP2, DFUMP2]: ...
    def __exit__(self, exception_type: None, exception_value: None, traceback: None) -> None: ...
    def kernel(self) -> float64: ...
    def nuc_grad_method(self) -> None: ...
    to_gpu = lib.to_gpu
MP2 = DFRMP2
RMP2 = DFRMP2
DFMP2 = DFRMP2

class SCSDFRMP2(DFRMP2):
    ps: Incomplete
    pt: Incomplete
    def __init__(self, mf: RHF, ps: float=..., pt: float=..., *args, **kwargs) -> None: ...
    def dump_flags(self, logger: None=None) -> None: ...
SCSMP2 = SCSDFRMP2
SCSRMP2 = SCSDFRMP2
SCSDFMP2 = SCSDFRMP2

def ints3c_cholesky(mol: Mole, auxmol: Mole, mo_coeff1: ndarray, mo_coeff2: ndarray, max_memory: Union[float, int], logger: Logger) -> H5TmpFile: ...
def emp2_rhf(intsfile: H5TmpFile, mo_energy: ndarray, frozen_mask: ndarray, logger: Logger, ps: float = 1.0, pt: float = 1.0) -> float64: ...
def make_rdm1(mp2: Union[SCSDFRMP2, DFRMP2], relaxed: bool, logger: Optional[Logger]=None) -> ndarray: ...
def rmp2_densities_contribs(intsfile: H5TmpFile, mo_energy: ndarray, frozen_mask: ndarray, max_memory: Union[float, int], logger: Logger, calcGamma: bool = False, auxmol: Optional[Mole]=None, ps: float = 1.0, pt: float = 1.0) -> Union[Tuple[ndarray, H5TmpFile], Tuple[ndarray, None]]: ...

class BatchSizeError(Exception): ...

def shellBatchGenerator(mol: Mole, nao_max: int) -> Iterator[Tuple[Tuple[int, int], Tuple[int, int]]]: ...
def orbgrad_from_Gamma(mol: Mole, auxmol: Mole, Gamma: Dataset, mo_coeff: ndarray, frozen_mask: ndarray, max_memory: Union[float, int], logger: Logger) -> Tuple[ndarray, ndarray]: ...
def fock_response_rhf(mf: RHF, dm: ndarray, full: bool = True) -> ndarray: ...
def solve_cphf_rhf(mf: RHF, Lvo: ndarray, max_cycle: int, tol: float, logger: Logger) -> ndarray: ...
