import types
from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import df as df, gto as gto, lib as lib, scf as scf
from pyscf.scf import cphf as cphf

class DFRMP2(lib.StreamObject):
    mo_coeff: Incomplete
    mo_energy: Incomplete
    nocc: Incomplete
    nmo: Incomplete
    e_scf: Incomplete
    frozen_mask: Incomplete
    occ_mask: Incomplete
    mol: Incomplete
    auxmol: Incomplete
    verbose: Incomplete
    stdout: Incomplete
    max_memory: Incomplete
    e_corr: Incomplete
    ps: float
    pt: float
    cphf_max_cycle: int
    cphf_tol: Incomplete
    def __init__(self, mf, frozen=None, auxbasis=None) -> None: ...
    def dump_flags(self, logger=None) -> None: ...
    @property
    def e_tot(self): ...
    def calculate_energy(self): ...
    def make_rdm1(self, relaxed: bool = False, ao_repr: bool = False): ...
    def make_rdm1_unrelaxed(self, ao_repr: bool = False): ...
    def make_rdm1_relaxed(self, ao_repr: bool = False): ...
    def make_natorbs(self, rdm1_mo=None, relaxed: bool = False): ...
    @property
    def has_ints(self): ...
    def calculate_integrals_(self) -> None: ...
    def delete(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exception_type: type[BaseException] | None, exception_value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
    def kernel(self): ...
    def nuc_grad_method(self) -> None: ...
    to_gpu = lib.to_gpu
MP2 = DFRMP2
RMP2 = DFRMP2
DFMP2 = DFRMP2

class SCSDFRMP2(DFRMP2):
    ps: Incomplete
    pt: Incomplete
    def __init__(self, mf, ps=..., pt=..., *args, **kwargs) -> None: ...
    def dump_flags(self, logger=None) -> None: ...
SCSMP2 = SCSDFRMP2
SCSRMP2 = SCSDFRMP2
SCSDFMP2 = SCSDFRMP2

def ints3c_cholesky(mol, auxmol, mo_coeff1, mo_coeff2, max_memory, logger): ...
def emp2_rhf(intsfile, mo_energy, frozen_mask, logger, ps: float = 1.0, pt: float = 1.0): ...
def make_rdm1(mp2, relaxed, logger=None): ...
def rmp2_densities_contribs(intsfile, mo_energy, frozen_mask, max_memory, logger, calcGamma: bool = False, auxmol=None, ps: float = 1.0, pt: float = 1.0): ...

class BatchSizeError(Exception): ...

def shellBatchGenerator(mol, nao_max) -> Generator[Incomplete]: ...
def orbgrad_from_Gamma(mol, auxmol, Gamma, mo_coeff, frozen_mask, max_memory, logger): ...
def fock_response_rhf(mf, dm, full: bool = True): ...
def solve_cphf_rhf(mf, Lvo, max_cycle, tol, logger): ...
