from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, lib as lib, scf as scf
from pyscf.lib import logger as logger
from pyscf.mp import mp2 as mp2

WITH_T2: Incomplete

def kernel(mp, mo_energy=None, mo_coeff=None, eris=None, with_t2=..., verbose=None): ...
def energy(mp, t2, eris): ...
def update_amps(mp, t2, eris): ...
def make_rdm1(mp, t2=None, ao_repr: bool = False, with_frozen: bool = True): ...
def make_rdm2(mp, t2=None, ao_repr: bool = False): ...

class GMP2(mp2.MP2Base):
    def __init__(self, mf, frozen=None, mo_coeff=None, mo_occ=None) -> None: ...
    def ao2mo(self, mo_coeff=None): ...
    make_rdm1 = make_rdm1
    make_rdm2 = make_rdm2
    def density_fit(self, auxbasis=None, with_df=None): ...
    def nuc_grad_method(self) -> None: ...
    energy = energy
    update_amps = update_amps
    def init_amps(self, mo_energy=None, mo_coeff=None, eris=None, with_t2=...): ...
MP2 = GMP2

class _PhysicistsERIs:
    mol: Incomplete
    mo_coeff: Incomplete
    nocc: Incomplete
    fock: Incomplete
    orbspin: Incomplete
    oovv: Incomplete
    def __init__(self, mol=None) -> None: ...
