from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, gto as gto, lib as lib, scf as scf
from pyscf.lib import logger as logger
from h5py._hl.dataset import Dataset
from numpy import complex128, float64, ndarray
from pyscf.gto.mole import Mole
from pyscf.lib.logger import Logger
from pyscf.lib.misc import H5TmpFile
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.mp.dfmp2 import DFRMP2
from pyscf.mp.dfmp2_slow import DFMP2
from pyscf.mp.gmp2 import GMP2, _PhysicistsERIs
from pyscf.mp.ump2 import UMP2
from pyscf.scf.hf import SCF
from typing import Any, Callable, List, Optional, Tuple, Union

WITH_T2: Incomplete

def kernel(mp: Union[Incomplete, Incomplete], mo_energy: Optional[ndarray]=None, mo_coeff: Optional[ndarray]=None, eris: Optional[Union[Incomplete, Callable]]=None, with_t2: bool=..., verbose: None=None) -> Union[Tuple[NPArrayWithTag, ndarray], Tuple[NPArrayWithTag, None]]: ...
def energy(mp: Incomplete, t2: ndarray, eris: Incomplete) -> NPArrayWithTag: ...
def update_amps(mp: Incomplete, t2: ndarray, eris: Incomplete) -> ndarray: ...
def make_rdm1(mp: Union[DFRMP2, Incomplete], t2: Optional[ndarray]=None, eris: Optional[Incomplete]=None, ao_repr: bool = False, with_frozen: bool = True) -> ndarray: ...
def make_fno(mp: Union[DFRMP2, Incomplete], thresh: float = 1e-06, pct_occ: None=None, nvir_act: None=None, t2: None=None) -> Tuple[ndarray, ndarray]: ...
def make_rdm2(mp: Incomplete, t2: None=None, eris: None=None, ao_repr: bool = False) -> ndarray: ...
def get_nocc(mp: Any) -> int: ...
def get_nmo(mp: Any) -> int: ...
def get_frozen_mask(mp: Any) -> ndarray: ...
def get_e_hf(mp: Any, mo_coeff: Optional[Union[List[ndarray], ndarray]]=None) -> Union[complex128, float64]: ...
def as_scanner(mp): ...

class MP2_Scanner(lib.SinglePointScanner):
    def __init__(self, mp: Incomplete) -> None: ...
    mo_coeff: Incomplete
    mo_occ: Incomplete
    def __call__(self, mol_or_geom, **kwargs): ...

class MP2Base(lib.StreamObject):
    max_cycle: Incomplete
    conv_tol: Incomplete
    conv_tol_normt: Incomplete
    mol: Incomplete
    verbose: Incomplete
    stdout: Incomplete
    max_memory: Incomplete
    frozen: Incomplete
    level_shift: int
    mo_coeff: Incomplete
    mo_occ: Incomplete
    e_hf: Incomplete
    e_corr: Incomplete
    e_corr_ss: Incomplete
    e_corr_os: Incomplete
    t2: Incomplete
    def __init__(self, mf: SCF, frozen: Optional[Any]=None, mo_coeff: Optional[Union[List[ndarray], NPArrayWithTag, ndarray]]=None, mo_occ: Optional[ndarray]=None) -> None: ...
    @property
    def nocc(self): ...
    @nocc.setter
    def nocc(self, n) -> None: ...
    @property
    def nmo(self): ...
    @nmo.setter
    def nmo(self, n) -> None: ...
    def reset(self, mol: Optional[Mole]=None) -> DFRMP2: ...
    get_nocc = get_nocc
    get_nmo = get_nmo
    get_frozen_mask = get_frozen_mask
    get_e_hf = get_e_hf
    def set_frozen(self, method: str = 'auto', window: Tuple[float, float]=(-1000.0, 1000.0)) -> Union[GMP2, Incomplete]: ...
    def dump_flags(self, verbose: None=None) -> "MP2Base": ...
    @property
    def emp2(self) -> float: ...
    @property
    def emp2_scs(self) -> float64: ...
    @property
    def e_tot(self) -> Union[complex128, float64]: ...
    @property
    def e_tot_scs(self) -> Union[complex128, float64]: ...
    def kernel(self, mo_energy: Optional[ndarray]=None, mo_coeff: Optional[ndarray]=None, eris: Optional[Any]=None, with_t2: bool=...) -> Union[Tuple[float, None], Tuple[float, Tuple[ndarray, ndarray, ndarray]], Tuple[float, ndarray], Tuple[float, List[ndarray]]]: ...
    ao2mo = NotImplemented
    def make_fno(mp, thresh: float = 1e-06, pct_occ=None, nvir_act=None, t2=None) -> None: ...
    def make_rdm1(mp, t2=None, eris=None, ao_repr: bool = False, with_frozen: bool = True) -> None: ...
    def make_rdm2(mp, t2=None, eris=None, ao_repr: bool = False) -> None: ...
    as_scanner = as_scanner
    def energy(self, t2, eris) -> None: ...
    def nuc_grad_method(self) -> None: ...
    def init_amps(self, mo_energy=None, mo_coeff=None, eris=None, with_t2=...) -> None: ...
    def update_amps(self, t2, eris) -> None: ...
    def density_fit(self, auxbasis=None, with_df=None) -> None: ...
    to_gpu = lib.to_gpu

class RMP2(MP2Base):
    make_rdm1 = make_rdm1
    make_fno = make_fno
    make_rdm2 = make_rdm2
    update_amps = update_amps
    energy = energy
    def init_amps(self, mo_energy: Optional[ndarray]=None, mo_coeff: Optional[ndarray]=None, eris: Optional[Union[Incomplete, Callable]]=None, with_t2: bool=...) -> Union[Tuple[NPArrayWithTag, ndarray], Tuple[NPArrayWithTag, None]]: ...
    def ao2mo(self, mo_coeff: Optional[ndarray]=None) -> Incomplete: ...
    def density_fit(self, auxbasis: Optional[str]=None, with_df: None=None) -> DFRMP2: ...
    def nuc_grad_method(self): ...
MP2 = RMP2

class _ChemistsERIs:
    mol: Incomplete
    mo_coeff: Incomplete
    nocc: Incomplete
    fock: Incomplete
    orbspin: Incomplete
    ovov: Incomplete
    def __init__(self, mol: None=None) -> None: ...
