from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, gto as gto, lib as lib, scf as scf
from pyscf.lib import logger as logger

WITH_T2: Incomplete

def kernel(mp, mo_energy=None, mo_coeff=None, eris=None, with_t2=..., verbose=None): ...
def energy(mp, t2, eris): ...
def update_amps(mp, t2, eris): ...
def make_rdm1(mp, t2=None, eris=None, ao_repr: bool = False, with_frozen: bool = True): ...
def make_fno(mp, thresh: float = 1e-06, pct_occ=None, nvir_act=None, t2=None): ...
def make_rdm2(mp, t2=None, eris=None, ao_repr: bool = False): ...
def get_nocc(mp): ...
def get_nmo(mp): ...
def get_frozen_mask(mp): ...
def get_e_hf(mp, mo_coeff=None): ...
def as_scanner(mp): ...

class MP2_Scanner(lib.SinglePointScanner):
    def __init__(self, mp) -> None: ...
    mo_coeff: Incomplete
    mo_occ: Incomplete
    def __call__(self, mol_or_geom, **kwargs): ...

class MP2Base(lib.StreamObject):
    max_cycle: Incomplete
    conv_tol: Incomplete
    conv_tol_normt: Incomplete
    mol: Incomplete
    verbose: Incomplete
    stdout: Incomplete
    max_memory: Incomplete
    frozen: Incomplete
    level_shift: int
    mo_coeff: Incomplete
    mo_occ: Incomplete
    e_hf: Incomplete
    e_corr: Incomplete
    e_corr_ss: Incomplete
    e_corr_os: Incomplete
    t2: Incomplete
    def __init__(self, mf, frozen=None, mo_coeff=None, mo_occ=None) -> None: ...
    @property
    def nocc(self): ...
    @nocc.setter
    def nocc(self, n) -> None: ...
    @property
    def nmo(self): ...
    @nmo.setter
    def nmo(self, n) -> None: ...
    def reset(self, mol=None): ...
    get_nocc = get_nocc
    get_nmo = get_nmo
    get_frozen_mask = get_frozen_mask
    get_e_hf = get_e_hf
    def set_frozen(self, method: str = 'auto', window=(-1000.0, 1000.0)): ...
    def dump_flags(self, verbose=None): ...
    @property
    def emp2(self): ...
    @property
    def emp2_scs(self): ...
    @property
    def e_tot(self): ...
    @property
    def e_tot_scs(self): ...
    def kernel(self, mo_energy=None, mo_coeff=None, eris=None, with_t2=...): ...
    ao2mo = NotImplemented
    def make_fno(mp, thresh: float = 1e-06, pct_occ=None, nvir_act=None, t2=None) -> None: ...
    def make_rdm1(mp, t2=None, eris=None, ao_repr: bool = False, with_frozen: bool = True) -> None: ...
    def make_rdm2(mp, t2=None, eris=None, ao_repr: bool = False) -> None: ...
    as_scanner = as_scanner
    def energy(self, t2, eris) -> None: ...
    def nuc_grad_method(self) -> None: ...
    def init_amps(self, mo_energy=None, mo_coeff=None, eris=None, with_t2=...) -> None: ...
    def update_amps(self, t2, eris) -> None: ...
    def density_fit(self, auxbasis=None, with_df=None) -> None: ...
    to_gpu = lib.to_gpu

class RMP2(MP2Base):
    make_rdm1 = make_rdm1
    make_fno = make_fno
    make_rdm2 = make_rdm2
    update_amps = update_amps
    energy = energy
    def init_amps(self, mo_energy=None, mo_coeff=None, eris=None, with_t2=...): ...
    def ao2mo(self, mo_coeff=None): ...
    def density_fit(self, auxbasis=None, with_df=None): ...
    def nuc_grad_method(self): ...
MP2 = RMP2

class _ChemistsERIs:
    mol: Incomplete
    mo_coeff: Incomplete
    nocc: Incomplete
    fock: Incomplete
    orbspin: Incomplete
    ovov: Incomplete
    def __init__(self, mol=None) -> None: ...
