from pyscf import ao2mo as ao2mo, gto as gto, lib as lib
from pyscf.lib import logger as logger
from pyscf.mp import mp2 as mp2
from pyscf.scf import jk as jk

def find_cabs(mol, auxmol, lindep: float = 1e-08): ...
def trans(eri, mos): ...
def energy_f12(mf, auxmol, zeta): ...
