from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, gto as gto, lib as lib, scf as scf
from pyscf.lib import logger as logger
from pyscf.mp import mp2 as mp2
from numpy import ndarray
from pyscf.lib.logger import Logger
from pyscf.lib.misc import H5TmpFile, StreamObject
from pyscf.lib.numpy_helper import NPArrayWithTag
from typing import Callable, List, Optional, Tuple, Union

WITH_T2: Incomplete

def kernel(mp: "UMP2", mo_energy: Optional[ndarray]=None, mo_coeff: Optional[ndarray]=None, eris: Optional[Union[_ChemistsERIs, Callable]]=None, with_t2: bool=..., verbose: None=None) -> Union[Tuple[NPArrayWithTag, None], Tuple[NPArrayWithTag, Tuple[ndarray, ndarray, ndarray]]]: ...
def energy(mp: "UMP2", t2: List[ndarray], eris: "_ChemistsERIs") -> NPArrayWithTag: ...
def update_amps(mp: "UMP2", t2: Union[List[ndarray], Tuple[ndarray, ndarray, ndarray]], eris: "_ChemistsERIs") -> Tuple[ndarray, ndarray, ndarray]: ...
def get_nocc(mp: StreamObject) -> Tuple[int, int]: ...
def get_nmo(mp: StreamObject) -> Tuple[int, int]: ...
def get_frozen_mask(mp: StreamObject) -> Tuple[ndarray, ndarray]: ...
def make_rdm1(mp: "UMP2", t2: Optional[Tuple[ndarray, ndarray, ndarray]]=None, ao_repr: bool = False, with_frozen: bool = True) -> Tuple[ndarray, ndarray]: ...
def make_fno(mp: "UMP2", thresh: float = 1e-06, pct_occ: None=None, nvir_act: None=None, t2: None=None, eris: None=None) -> Tuple[List[ndarray], List[ndarray]]: ...
def make_rdm2(mp: "UMP2", t2: None=None, ao_repr: bool = False) -> Tuple[ndarray, ndarray, ndarray]: ...

class UMP2(mp2.MP2Base):
    get_nocc = get_nocc
    get_nmo = get_nmo
    get_frozen_mask = get_frozen_mask
    def ao2mo(self, mo_coeff: Optional[ndarray]=None) -> "_ChemistsERIs": ...
    make_rdm1 = make_rdm1
    make_fno = make_fno
    make_rdm2 = make_rdm2
    def nuc_grad_method(self): ...
    energy = energy
    update_amps = update_amps
    def init_amps(self, mo_energy: Optional[ndarray]=None, mo_coeff: Optional[ndarray]=None, eris: Optional[Union[_ChemistsERIs, Callable]]=None, with_t2: bool=...) -> Union[Tuple[NPArrayWithTag, None], Tuple[NPArrayWithTag, Tuple[ndarray, ndarray, ndarray]]]: ...
    def density_fit(self, auxbasis=None, with_df=None): ...
MP2 = UMP2

class _ChemistsERIs(mp2._ChemistsERIs):
    OVOV: Incomplete
    ovOV: Incomplete
    def __init__(self, mol: None=None) -> None: ...
