from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, gto as gto, lib as lib, scf as scf
from pyscf.lib import logger as logger
from pyscf.mp import mp2 as mp2

WITH_T2: Incomplete

def kernel(mp, mo_energy=None, mo_coeff=None, eris=None, with_t2=..., verbose=None): ...
def energy(mp, t2, eris): ...
def update_amps(mp, t2, eris): ...
def get_nocc(mp): ...
def get_nmo(mp): ...
def get_frozen_mask(mp): ...
def make_rdm1(mp, t2=None, ao_repr: bool = False, with_frozen: bool = True): ...
def make_fno(mp, thresh: float = 1e-06, pct_occ=None, nvir_act=None, t2=None, eris=None): ...
def make_rdm2(mp, t2=None, ao_repr: bool = False): ...

class UMP2(mp2.MP2Base):
    get_nocc = get_nocc
    get_nmo = get_nmo
    get_frozen_mask = get_frozen_mask
    def ao2mo(self, mo_coeff=None): ...
    make_rdm1 = make_rdm1
    make_fno = make_fno
    make_rdm2 = make_rdm2
    def nuc_grad_method(self): ...
    energy = energy
    update_amps = update_amps
    def init_amps(self, mo_energy=None, mo_coeff=None, eris=None, with_t2=...): ...
    def density_fit(self, auxbasis=None, with_df=None): ...
MP2 = UMP2

class _ChemistsERIs(mp2._ChemistsERIs):
    OVOV: Incomplete
    ovOV: Incomplete
    def __init__(self, mol=None) -> None: ...
