from _typeshed import Incomplete
from pyscf import lib as lib
from pyscf.agf2 import mpi_helper as mpi_helper

libagf2: Incomplete

def cholesky_build(vv, vev, eps: float = 1e-16): ...
def build_mats_ragf2_incore(qeri, e_occ, e_vir, os_factor: float = 1.0, ss_factor: float = 1.0): ...
def build_mats_ragf2_outcore(qeri, e_occ, e_vir, os_factor: float = 1.0, ss_factor: float = 1.0): ...
def build_mats_dfragf2_incore(qxi, qja, e_occ, e_vir, os_factor: float = 1.0, ss_factor: float = 1.0): ...
def build_mats_dfragf2_lowmem(qxi, qja, e_occ, e_vir, os_factor: float = 1.0, ss_factor: float = 1.0): ...
def build_mats_dfragf2_outcore(qxi, qja, e_occ, e_vir, os_factor: float = 1.0, ss_factor: float = 1.0): ...
def build_mats_uagf2_incore(qeri, e_occ, e_vir, os_factor: float = 1.0, ss_factor: float = 1.0): ...
def build_mats_uagf2_outcore(qeri, e_occ, e_vir, os_factor: float = 1.0, ss_factor: float = 1.0): ...
def build_mats_dfuagf2_incore(qxi, qja, e_occ, e_vir, os_factor: float = 1.0, ss_factor: float = 1.0): ...
def build_mats_dfuagf2_lowmem(qxi, qja, e_occ, e_vir, os_factor: float = 1.0, ss_factor: float = 1.0): ...
def build_mats_dfuagf2_outcore(qxi, qja, e_occ, e_vir, os_factor: float = 1.0, ss_factor: float = 1.0): ...
def get_blksize(max_memory_total, *sizes): ...
