from _typeshed import Incomplete
from pyscf import lib as lib
from pyscf.agf2 import mpi_helper as mpi_helper
from h5py._hl.dataset import Dataset
from numpy import ndarray
from typing import Tuple, Union

libagf2: Incomplete

def cholesky_build(vv: ndarray, vev: ndarray, eps: float = 1e-16) -> Tuple[ndarray, ndarray]: ...
def build_mats_ragf2_incore(qeri: ndarray, e_occ: ndarray, e_vir: ndarray, os_factor: float = 1.0, ss_factor: float = 1.0) -> Tuple[ndarray, ndarray]: ...
def build_mats_ragf2_outcore(qeri: Union[ndarray, Dataset], e_occ: ndarray, e_vir: ndarray, os_factor: float = 1.0, ss_factor: float = 1.0) -> Tuple[ndarray, ndarray]: ...
def build_mats_dfragf2_incore(qxi: ndarray, qja: ndarray, e_occ: ndarray, e_vir: ndarray, os_factor: float = 1.0, ss_factor: float = 1.0) -> Tuple[ndarray, ndarray]: ...
def build_mats_dfragf2_lowmem(qxi, qja, e_occ, e_vir, os_factor: float = 1.0, ss_factor: float = 1.0): ...
def build_mats_dfragf2_outcore(qxi: ndarray, qja: ndarray, e_occ: ndarray, e_vir: ndarray, os_factor: float = 1.0, ss_factor: float = 1.0) -> Tuple[ndarray, ndarray]: ...
def build_mats_uagf2_incore(qeri: Union[ndarray, Tuple[ndarray, ndarray]], e_occ: Tuple[ndarray, ndarray], e_vir: Tuple[ndarray, ndarray], os_factor: float = 1.0, ss_factor: float = 1.0) -> Tuple[ndarray, ndarray]: ...
def build_mats_uagf2_outcore(qeri: Union[ndarray, Tuple[Dataset, Dataset]], e_occ: Tuple[ndarray, ndarray], e_vir: Tuple[ndarray, ndarray], os_factor: float = 1.0, ss_factor: float = 1.0) -> Tuple[ndarray, ndarray]: ...
def build_mats_dfuagf2_incore(qxi: Union[ndarray, Tuple[ndarray, ndarray]], qja: Union[ndarray, Tuple[ndarray, ndarray]], e_occ: Tuple[ndarray, ndarray], e_vir: Tuple[ndarray, ndarray], os_factor: float = 1.0, ss_factor: float = 1.0) -> Tuple[ndarray, ndarray]: ...
def build_mats_dfuagf2_lowmem(qxi, qja, e_occ, e_vir, os_factor: float = 1.0, ss_factor: float = 1.0): ...
def build_mats_dfuagf2_outcore(qxi: ndarray, qja: ndarray, e_occ: Tuple[ndarray, ndarray], e_vir: Tuple[ndarray, ndarray], os_factor: float = 1.0, ss_factor: float = 1.0) -> Tuple[ndarray, ndarray]: ...
def get_blksize(max_memory_total: int, *sizes) -> int: ...
