from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.lib.parameters import LARGE_DENOM as LARGE_DENOM

class AuxiliarySpace:
    energy: Incomplete
    coupling: Incomplete
    chempot: Incomplete
    def __init__(self, energy, coupling, chempot: float = 0.0) -> None: ...
    def sort(self) -> None: ...
    def real_freq_spectrum(self, *args, **kwargs) -> None: ...
    def compress(self, *args, **kwargs) -> None: ...
    def get_occupied(self): ...
    def get_virtual(self): ...
    def get_array(self, phys, out=None, chempot: float = 0.0): ...
    def dot(self, phys, vec, out=None, chempot: float = 0.0): ...
    def eig(self, phys, out=None, chempot: float = 0.0): ...
    def moment(self, n, squeeze: bool = True): ...
    def remove_uncoupled(self, tol) -> None: ...
    def save(self, chkfile, key=None) -> None: ...
    @classmethod
    def load(cls, chkfile, key=None): ...
    def copy(self): ...
    @property
    def nphys(self): ...
    @property
    def naux(self): ...

class SelfEnergy(AuxiliarySpace):
    def real_freq_spectrum(self, grid, eta: float = 0.02) -> None: ...
    def get_greens_function(self, phys): ...
    def make_rdm1(self, phys, chempot=None, occupancy: int = 2): ...
    def compress(self, phys=None, n=(None, 0), tol: float = 1e-12): ...

class GreensFunction(AuxiliarySpace):
    def real_freq_spectrum(self, grid, eta: float = 0.02): ...
    def make_rdm1(self, chempot=None, occupancy: int = 2): ...
    def compress(self, *args, **kwargs) -> None: ...

def combine(*auxspcs): ...
def davidson(auxspc, phys, chempot=None, nroots: int = 1, which: str = 'SM', tol: float = 1e-14, maxiter=None, ntrial=None): ...
def compress_via_se(se, n: int = 0): ...
def compress_via_gf(se, phys, n: int = 0, tol: float = 1e-12): ...
