from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.lib.parameters import LARGE_DENOM as LARGE_DENOM
from numpy import float64, ndarray
from typing import Optional, Tuple, Union

class AuxiliarySpace:
    energy: Incomplete
    coupling: Incomplete
    chempot: Incomplete
    def __init__(self, energy: ndarray, coupling: ndarray, chempot: Union[float, float64] = 0.0) -> None: ...
    def sort(self) -> None: ...
    def real_freq_spectrum(self, *args, **kwargs) -> None: ...
    def compress(self, *args, **kwargs) -> None: ...
    def get_occupied(self) -> Union[GreensFunction, SelfEnergy]: ...
    def get_virtual(self) -> Union[GreensFunction, SelfEnergy]: ...
    def get_array(self, phys: ndarray, out: Optional[ndarray]=None, chempot: Union[ndarray, float] = 0.0) -> ndarray: ...
    def dot(self, phys: ndarray, vec: ndarray, out: None=None, chempot: float = 0.0) -> ndarray: ...
    def eig(self, phys: ndarray, out: Optional[ndarray]=None, chempot: Union[ndarray, float] = 0.0) -> Tuple[ndarray, ndarray]: ...
    def moment(self, n: int, squeeze: bool = True) -> ndarray: ...
    def remove_uncoupled(self, tol: float) -> None: ...
    def save(self, chkfile, key=None) -> None: ...
    @classmethod
    def load(cls, chkfile, key=None): ...
    def copy(self) -> "SelfEnergy": ...
    @property
    def nphys(self) -> int: ...
    @property
    def naux(self) -> int: ...

class SelfEnergy(AuxiliarySpace):
    def real_freq_spectrum(self, grid, eta: float = 0.02) -> None: ...
    def get_greens_function(self, phys: ndarray) -> "GreensFunction": ...
    def make_rdm1(self, phys, chempot=None, occupancy: int = 2): ...
    def compress(self, phys: Optional[ndarray]=None, n: Union[Tuple[int, None], Tuple[None, None], Tuple[None, int]]=(None, 0), tol: float = 1e-12) -> "SelfEnergy": ...

class GreensFunction(AuxiliarySpace):
    def real_freq_spectrum(self, grid, eta: float = 0.02): ...
    def make_rdm1(self, chempot: None=None, occupancy: int = 2) -> ndarray: ...
    def compress(self, *args, **kwargs) -> None: ...

def combine(*auxspcs) -> SelfEnergy: ...
def davidson(auxspc, phys, chempot=None, nroots: int = 1, which: str = 'SM', tol: float = 1e-14, maxiter=None, ntrial=None): ...
def compress_via_se(se: SelfEnergy, n: int = 0) -> SelfEnergy: ...
def compress_via_gf(se: SelfEnergy, phys: ndarray, n: int = 0, tol: float = 1e-12) -> SelfEnergy: ...
