from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger

def binsearch_chempot(fock, nphys, nelec, occupancy: int = 2): ...
def minimize_chempot(se, fock, nelec, occupancy: int = 2, x0: float = 0.0, tol: float = 1e-06, maxiter: int = 200, jac: bool = True): ...
