from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.agf2 import mpi_helper as mpi_helper
from pyscf.agf2.aux_space import GreensFunction, SelfEnergy, GreensFunction as GreensFunction, SelfEnergy as SelfEnergy
from pyscf.lib import logger as logger
from numpy import bool, float64, int64, ndarray
from pyscf.agf2.ragf2 import RAGF2
from typing import Dict, Optional, Tuple, Union

def load(chkfile: str, key: str) -> Dict[str, Union[int64, bool, float64, Dict[str, Union[float64, ndarray]], ndarray]]: ...
def load_mol(chkfile): ...
def load_agf2(chkfile): ...
def dump_agf2(agf2: RAGF2, chkfile: Optional[str]=None, key: str = 'agf2', gf: Optional[Union[GreensFunction, Tuple[GreensFunction, GreensFunction]]]=None, se: Optional[Union[Tuple[SelfEnergy, SelfEnergy], SelfEnergy]]=None, frozen: None=None, nmom: None=None, mo_energy: None=None, mo_coeff: None=None, mo_occ: None=None) -> RAGF2: ...
