from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.agf2 import mpi_helper as mpi_helper
from pyscf.agf2.aux_space import GreensFunction as GreensFunction, SelfEnergy as SelfEnergy
from pyscf.lib import logger as logger

def load(chkfile, key): ...
def load_mol(chkfile): ...
def load_agf2(chkfile): ...
def dump_agf2(agf2, chkfile=None, key: str = 'agf2', gf=None, se=None, frozen=None, nmom=None, mo_energy=None, mo_coeff=None, mo_occ=None): ...
