from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, ao2mo as ao2mo, df as df, lib as lib
from pyscf.agf2 import mpi_helper as mpi_helper, ragf2 as ragf2
from pyscf.lib import logger as logger

BLKMIN: Incomplete

def build_se_part(agf2, eri, gf_occ, gf_vir, os_factor: float = 1.0, ss_factor: float = 1.0): ...
def get_jk(agf2, eri, rdm1, with_j: bool = True, with_k: bool = True): ...

class DFRAGF2(ragf2.RAGF2):
    allow_lowmem_build: bool
    def __init__(self, mf, frozen=None, mo_energy=None, mo_coeff=None, mo_occ=None) -> None: ...
    build_se_part = build_se_part
    get_jk = get_jk
    def ao2mo(self, mo_coeff=None): ...
    def reset(self, mol=None): ...
    @property
    def with_df(self): ...
    @with_df.setter
    def with_df(self, val) -> None: ...

class DF(df.DF):
    def prange(self, start=None, stop=None, step=None) -> Generator[Incomplete, Incomplete]: ...

class _ChemistsERIs(ragf2._ChemistsERIs): ...
