from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, df as df, lib as lib
from pyscf.agf2 import dfragf2 as dfragf2, mpi_helper as mpi_helper, uagf2 as uagf2
from pyscf.lib import logger as logger

BLKMIN: Incomplete

def build_se_part(agf2, eri, gf_occ, gf_vir, os_factor: float = 1.0, ss_factor: float = 1.0): ...

class DFUAGF2(uagf2.UAGF2):
    allow_lowmem_build: bool
    def __init__(self, mf, frozen=None, mo_energy=None, mo_coeff=None, mo_occ=None) -> None: ...
    build_se_part = build_se_part
    get_jk = dfragf2.get_jk
    def ao2mo(self, mo_coeff=None): ...
    def reset(self, mol=None): ...
    @property
    def with_df(self): ...
    @with_df.setter
    def with_df(self, val) -> None: ...

class _ChemistsERIs(uagf2._ChemistsERIs): ...
