from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from numpy import bool, float64, int64, ndarray
from typing import Dict, Iterator, Tuple, Union

INT_MAX: int
BLKSIZE: Incomplete
comm: Incomplete
size: Incomplete
rank: Incomplete
SCALE_PRANGE_STEP: bool

def bcast(buf: Union[ndarray, float64], root: int = 0) -> Union[ndarray, float64]: ...
def bcast_dict(buf: Dict[str, Union[int64, bool, float64, Dict[str, Union[float64, ndarray]], ndarray]], root: int = 0) -> Dict[str, Union[int64, bool, float64, Dict[str, Union[float64, ndarray]], ndarray]]: ...
def reduce(sendbuf, root: int = 0, op=...): ...
def allreduce(sendbuf: float64, root: int = 0, op: None=...) -> float64: ...
def allreduce_safe_inplace(array: ndarray) -> ndarray: ...
def barrier() -> None: ...
def nrange(start: int, stop: None=None, step: int = 1) -> Iterator[int]: ...
def prange(start: int, stop: int, step: int) -> Iterator[Tuple[int, int]]: ...
