from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger

INT_MAX: int
BLKSIZE: Incomplete
comm: Incomplete
size: Incomplete
rank: Incomplete
SCALE_PRANGE_STEP: bool

def bcast(buf, root: int = 0): ...
def bcast_dict(buf, root: int = 0): ...
def reduce(sendbuf, root: int = 0, op=...): ...
def allreduce(sendbuf, root: int = 0, op=...): ...
def allreduce_safe_inplace(array): ...
def barrier() -> None: ...
def nrange(start, stop=None, step: int = 1) -> Generator[Incomplete, Incomplete]: ...
def prange(start, stop, step) -> Generator[Incomplete, None, Incomplete]: ...
