from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, lib as lib
from pyscf.agf2 import mpi_helper as mpi_helper
from pyscf.agf2.chempot import binsearch_chempot as binsearch_chempot, minimize_chempot as minimize_chempot
from pyscf.lib import logger as logger

BLKMIN: Incomplete

def kernel(agf2, eri=None, gf=None, se=None, verbose=None, dump_chk: bool = True): ...
def build_se_part(agf2, eri, gf_occ, gf_vir, os_factor: float = 1.0, ss_factor: float = 1.0): ...
def get_jk(agf2, eri, rdm1, with_j: bool = True, with_k: bool = True): ...
def get_fock(agf2, eri, gf=None, rdm1=None): ...
def fock_loop(agf2, eri, gf, se): ...
def energy_1body(agf2, eri, gf): ...
def energy_2body(agf2, gf, se): ...
def energy_mp2(agf2, mo_energy, se): ...

class RAGF2(lib.StreamObject):
    async_io: Incomplete
    incore_complete: Incomplete
    mol: Incomplete
    verbose: Incomplete
    stdout: Incomplete
    max_memory: Incomplete
    conv_tol: Incomplete
    conv_tol_rdm1: Incomplete
    conv_tol_nelec: Incomplete
    max_cycle: Incomplete
    max_cycle_outer: Incomplete
    max_cycle_inner: Incomplete
    weight_tol: Incomplete
    fock_diis_space: Incomplete
    fock_diis_min_space: Incomplete
    diis: Incomplete
    diis_space: Incomplete
    diis_min_space: Incomplete
    os_factor: Incomplete
    ss_factor: Incomplete
    damping: Incomplete
    mo_energy: Incomplete
    mo_coeff: Incomplete
    mo_occ: Incomplete
    se: Incomplete
    gf: Incomplete
    e_1b: Incomplete
    e_2b: float
    e_init: float
    frozen: Incomplete
    converged: bool
    chkfile: Incomplete
    def __init__(self, mf, frozen=None, mo_energy=None, mo_coeff=None, mo_occ=None) -> None: ...
    energy_1body = energy_1body
    energy_2body = energy_2body
    fock_loop = fock_loop
    build_se_part = build_se_part
    get_jk = get_jk
    def ao2mo(self, mo_coeff=None): ...
    def make_rdm1(self, gf=None): ...
    def get_fock(self, eri=None, gf=None, rdm1=None): ...
    def energy_mp2(self, mo_energy=None, se=None): ...
    def init_gf(self, frozen: bool = False): ...
    def build_gf(self, eri=None, gf=None, se=None): ...
    def build_se(self, eri=None, gf=None, os_factor=None, ss_factor=None, se_prev=None): ...
    def run_diis(self, se, diis=None): ...
    def energy_nuc(self): ...
    def dump_flags(self, verbose=None): ...
    def reset(self, mol=None): ...
    def kernel(self, eri=None, gf=None, se=None, dump_chk: bool = True): ...
    def dump_chk(self, chkfile=None, key: str = 'agf2', gf=None, se=None, frozen=None, nmom=None, mo_energy=None, mo_coeff=None, mo_occ=None): ...
    def update_from_chk_(self, chkfile=None, key: str = 'agf2'): ...
    update = update_from_chk_
    update_from_chk = update_from_chk_
    def density_fit(self, auxbasis=None, with_df=None): ...
    def get_ip(self, gf, nroots: int = 5): ...
    def ipagf2(self, nroots: int = 5): ...
    def get_ea(self, gf, nroots: int = 5): ...
    def eaagf2(self, nroots: int = 5): ...
    @property
    def nocc(self): ...
    @nocc.setter
    def nocc(self, val) -> None: ...
    @property
    def nmo(self): ...
    @nmo.setter
    def nmo(self, val) -> None: ...
    @property
    def e_tot(self): ...
    @property
    def e_corr(self): ...
    @property
    def qmo_energy(self): ...
    @property
    def qmo_coeff(self): ...
    @property
    def qmo_occ(self): ...

def get_frozen_mask(agf2): ...

class _ChemistsERIs:
    mol: Incomplete
    mo_coeff: Incomplete
    nmo: Incomplete
    nocc: Incomplete
    fock: Incomplete
    h1e: Incomplete
    eri: Incomplete
    e_hf: Incomplete
    def __init__(self, mol=None) -> None: ...
