from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, lib as lib
from pyscf.agf2 import mpi_helper as mpi_helper
from pyscf.agf2.chempot import binsearch_chempot as binsearch_chempot, minimize_chempot as minimize_chempot
from pyscf.lib import logger as logger
from h5py._hl.dataset import Dataset
from numpy import float64, ndarray
from pyscf.agf2.aux_space import GreensFunction, SelfEnergy
from pyscf.agf2.dfragf2 import DFRAGF2
from pyscf.lib.diis import DIIS
from pyscf.scf.hf import RHF
from pyscf.scf.uhf import UHF
from typing import List, Optional, Tuple, Union

BLKMIN: Incomplete

def kernel(agf2: Incomplete, eri: Optional[Union[Incomplete, Incomplete, Incomplete, Incomplete]]=None, gf: Optional[Union[GreensFunction, Tuple[GreensFunction, GreensFunction]]]=None, se: Optional[Union[Tuple[SelfEnergy, SelfEnergy], SelfEnergy]]=None, verbose: Optional[int]=None, dump_chk: bool = True) -> Union[Tuple[bool, float64, float64, GreensFunction, SelfEnergy], Tuple[bool, float64, float64, Tuple[GreensFunction, GreensFunction], Tuple[SelfEnergy, SelfEnergy]]]: ...
def build_se_part(agf2: Incomplete, eri: Incomplete, gf_occ: GreensFunction, gf_vir: GreensFunction, os_factor: float = 1.0, ss_factor: float = 1.0) -> SelfEnergy: ...
def get_jk(agf2: Union[Incomplete, Incomplete, Incomplete, Incomplete], eri: Union[ndarray, Dataset], rdm1: ndarray, with_j: bool = True, with_k: bool = True) -> Union[Tuple[ndarray, ndarray], Tuple[ndarray, None]]: ...
def get_fock(agf2: Union[DFRAGF2, Incomplete, Incomplete], eri: Union[Incomplete, Incomplete], gf: Optional[GreensFunction]=None, rdm1: None=None) -> ndarray: ...
def fock_loop(agf2: Union[Incomplete, Incomplete, DFRAGF2], eri: Union[Incomplete, Incomplete], gf: GreensFunction, se: SelfEnergy) -> Tuple[GreensFunction, SelfEnergy, bool]: ...
def energy_1body(agf2: Union[Incomplete, Incomplete, DFRAGF2], eri: Union[Incomplete, Incomplete], gf: GreensFunction) -> float64: ...
def energy_2body(agf2: Incomplete, gf: GreensFunction, se: SelfEnergy) -> float64: ...
def energy_mp2(agf2: Incomplete, mo_energy: ndarray, se: SelfEnergy) -> float64: ...

class RAGF2(lib.StreamObject):
    async_io: Incomplete
    incore_complete: Incomplete
    mol: Incomplete
    verbose: Incomplete
    stdout: Incomplete
    max_memory: Incomplete
    conv_tol: Incomplete
    conv_tol_rdm1: Incomplete
    conv_tol_nelec: Incomplete
    max_cycle: Incomplete
    max_cycle_outer: Incomplete
    max_cycle_inner: Incomplete
    weight_tol: Incomplete
    fock_diis_space: Incomplete
    fock_diis_min_space: Incomplete
    diis: Incomplete
    diis_space: Incomplete
    diis_min_space: Incomplete
    os_factor: Incomplete
    ss_factor: Incomplete
    damping: Incomplete
    mo_energy: Incomplete
    mo_coeff: Incomplete
    mo_occ: Incomplete
    se: Incomplete
    gf: Incomplete
    e_1b: Incomplete
    e_2b: float
    e_init: float
    frozen: Incomplete
    converged: bool
    chkfile: Incomplete
    def __init__(self, mf: Union[RHF, UHF], frozen: None=None, mo_energy: None=None, mo_coeff: None=None, mo_occ: None=None) -> None: ...
    energy_1body = energy_1body
    energy_2body = energy_2body
    fock_loop = fock_loop
    build_se_part = build_se_part
    get_jk = get_jk
    def ao2mo(self, mo_coeff: None=None) -> Incomplete: ...
    def make_rdm1(self, gf: Optional[GreensFunction]=None) -> ndarray: ...
    def get_fock(self, eri: Optional[Union[Incomplete, Incomplete]]=None, gf: Optional[GreensFunction]=None, rdm1: None=None) -> ndarray: ...
    def energy_mp2(self, mo_energy: Optional[ndarray]=None, se: Optional[SelfEnergy]=None) -> float64: ...
    def init_gf(self, frozen: bool = False) -> GreensFunction: ...
    def build_gf(self, eri=None, gf=None, se=None): ...
    def build_se(self, eri: Optional[Union[Incomplete, Incomplete]]=None, gf: Optional[GreensFunction]=None, os_factor: None=None, ss_factor: None=None, se_prev: None=None) -> SelfEnergy: ...
    def run_diis(self, se: SelfEnergy, diis: Optional[DIIS]=None) -> SelfEnergy: ...
    def energy_nuc(self) -> float64: ...
    def dump_flags(self, verbose: None=None) -> Incomplete: ...
    def reset(self, mol=None): ...
    def kernel(self, eri: Optional[Incomplete]=None, gf: None=None, se: None=None, dump_chk: bool = True) -> Union[Tuple[bool, float64, float64, GreensFunction, SelfEnergy], Tuple[bool, float64, float64, Tuple[GreensFunction, GreensFunction], Tuple[SelfEnergy, SelfEnergy]]]: ...
    def dump_chk(self, chkfile: None=None, key: str = 'agf2', gf: Optional[Union[Tuple[GreensFunction, GreensFunction], GreensFunction]]=None, se: Optional[Union[SelfEnergy, Tuple[SelfEnergy, SelfEnergy]]]=None, frozen: None=None, nmom: None=None, mo_energy: None=None, mo_coeff: None=None, mo_occ: None=None) -> Incomplete: ...
    def update_from_chk_(self, chkfile=None, key: str = 'agf2'): ...
    update = update_from_chk_
    update_from_chk = update_from_chk_
    def density_fit(self, auxbasis=None, with_df=None): ...
    def get_ip(self, gf: GreensFunction, nroots: int = 5) -> Tuple[List[float64], List[ndarray]]: ...
    def ipagf2(self, nroots: int = 5) -> Union[Tuple[List[float64], List[ndarray]], Tuple[float64, ndarray]]: ...
    def get_ea(self, gf: GreensFunction, nroots: int = 5) -> Tuple[List[float64], List[ndarray]]: ...
    def eaagf2(self, nroots: int = 5) -> Union[Tuple[List[float64], List[ndarray]], Tuple[float64, ndarray]]: ...
    @property
    def nocc(self): ...
    @nocc.setter
    def nocc(self, val) -> None: ...
    @property
    def nmo(self): ...
    @nmo.setter
    def nmo(self, val) -> None: ...
    @property
    def e_tot(self) -> float64: ...
    @property
    def e_corr(self) -> float64: ...
    @property
    def qmo_energy(self): ...
    @property
    def qmo_coeff(self): ...
    @property
    def qmo_occ(self): ...

def get_frozen_mask(agf2: Union[Incomplete, Incomplete, DFRAGF2]) -> ndarray: ...

class _ChemistsERIs:
    mol: Incomplete
    mo_coeff: Incomplete
    nmo: Incomplete
    nocc: Incomplete
    fock: Incomplete
    h1e: Incomplete
    eri: Incomplete
    e_hf: Incomplete
    def __init__(self, mol: None=None) -> None: ...
