from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, lib as lib
from pyscf.agf2 import mpi_helper as mpi_helper, ragf2 as ragf2
from pyscf.agf2.chempot import binsearch_chempot as binsearch_chempot, minimize_chempot as minimize_chempot
from pyscf.lib import logger as logger

BLKMIN: Incomplete

def build_se_part(agf2, eri, gf_occ, gf_vir, os_factor: float = 1.0, ss_factor: float = 1.0): ...
def get_fock(agf2, eri, gf=None, rdm1=None): ...
def fock_loop(agf2, eri, gf, se): ...
def energy_1body(agf2, eri, gf): ...
def energy_2body(agf2, gf, se): ...
def energy_mp2(agf2, gf, se): ...

class UAGF2(ragf2.RAGF2):
    energy_1body = energy_1body
    energy_2body = energy_2body
    fock_loop = fock_loop
    build_se_part = build_se_part
    def ao2mo(self, mo_coeff=None): ...
    def make_rdm1(self, gf=None): ...
    def get_fock(self, eri=None, gf=None, rdm1=None): ...
    e_init: Incomplete
    def energy_mp2(self, mo_energy=None, se=None): ...
    def init_gf(self, frozen: bool = False): ...
    def build_gf(self, eri=None, gf=None, se=None): ...
    def build_se(self, eri=None, gf=None, os_factor=None, ss_factor=None, se_prev=None): ...
    def run_diis(self, se, diis=None): ...
    def density_fit(self, auxbasis=None, with_df=None): ...
    def get_ip(self, gf, nroots: int = 5): ...
    def ipagf2(self, nroots: int = 5): ...
    def get_ea(self, gf, nroots: int = 5): ...
    def eaagf2(self, nroots: int = 5): ...
    @property
    def nocc(self): ...
    @nocc.setter
    def nocc(self, val) -> None: ...
    @property
    def nmo(self): ...
    @nmo.setter
    def nmo(self, val) -> None: ...
    @property
    def qmo_energy(self): ...
    @property
    def qmo_coeff(self): ...
    @property
    def qmo_occ(self): ...

def get_frozen_mask(agf2): ...

class _ChemistsERIs:
    mol: Incomplete
    mo_coeff: Incomplete
    nocc: Incomplete
    nmo: Incomplete
    fock: Incomplete
    h1e: Incomplete
    eri: Incomplete
    e_hf: Incomplete
    def __init__(self, mol=None) -> None: ...
