from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, lib as lib
from pyscf.agf2 import mpi_helper as mpi_helper, ragf2 as ragf2
from pyscf.agf2.chempot import binsearch_chempot as binsearch_chempot, minimize_chempot as minimize_chempot
from pyscf.lib import logger as logger
from h5py._hl.dataset import Dataset
from numpy import float64, int64, ndarray
from pyscf.agf2.aux_space import GreensFunction, SelfEnergy
from pyscf.agf2.dfuagf2 import DFUAGF2
from pyscf.lib.diis import DIIS
from typing import List, Optional, Tuple, Union

BLKMIN: Incomplete

def build_se_part(agf2: Incomplete, eri: Incomplete, gf_occ: Tuple[GreensFunction, GreensFunction], gf_vir: Tuple[GreensFunction, GreensFunction], os_factor: float = 1.0, ss_factor: float = 1.0) -> Tuple[SelfEnergy, SelfEnergy]: ...
def get_fock(agf2: Union[Incomplete, Incomplete, DFUAGF2], eri: Union[Incomplete, Incomplete], gf: Optional[Tuple[GreensFunction, GreensFunction]]=None, rdm1: None=None) -> Tuple[ndarray, ndarray]: ...
def fock_loop(agf2: Union[Incomplete, DFUAGF2, Incomplete], eri: Union[Incomplete, Incomplete], gf: Tuple[GreensFunction, GreensFunction], se: Tuple[SelfEnergy, SelfEnergy]) -> Tuple[Tuple[GreensFunction, GreensFunction], Tuple[SelfEnergy, SelfEnergy], bool]: ...
def energy_1body(agf2: Union[Incomplete, DFUAGF2, Incomplete], eri: Union[Incomplete, Incomplete], gf: Tuple[GreensFunction, GreensFunction]) -> float64: ...
def energy_2body(agf2: Union[Incomplete, Incomplete, DFUAGF2], gf: Tuple[GreensFunction, GreensFunction], se: Tuple[SelfEnergy, SelfEnergy]) -> float64: ...
def energy_mp2(agf2: Union[Incomplete, DFUAGF2, Incomplete], gf: ndarray, se: Tuple[SelfEnergy, SelfEnergy]) -> float64: ...

class UAGF2(ragf2.RAGF2):
    energy_1body = energy_1body
    energy_2body = energy_2body
    fock_loop = fock_loop
    build_se_part = build_se_part
    def ao2mo(self, mo_coeff: None=None) -> Incomplete: ...
    def make_rdm1(self, gf: Optional[Tuple[GreensFunction, GreensFunction]]=None) -> Tuple[ndarray, ndarray]: ...
    def get_fock(self, eri: Optional[Union[Incomplete, Incomplete]]=None, gf: Optional[Tuple[GreensFunction, GreensFunction]]=None, rdm1: None=None) -> Tuple[ndarray, ndarray]: ...
    e_init: Incomplete
    def energy_mp2(self, mo_energy: Optional[ndarray]=None, se: Optional[Tuple[SelfEnergy, SelfEnergy]]=None) -> float64: ...
    def init_gf(self, frozen: bool = False) -> Tuple[GreensFunction, GreensFunction]: ...
    def build_gf(self, eri=None, gf=None, se=None): ...
    def build_se(self, eri: Optional[Union[Incomplete, Incomplete]]=None, gf: Optional[Tuple[GreensFunction, GreensFunction]]=None, os_factor: None=None, ss_factor: None=None, se_prev: None=None) -> Tuple[SelfEnergy, SelfEnergy]: ...
    def run_diis(self, se: Tuple[SelfEnergy, SelfEnergy], diis: Optional[DIIS]=None) -> Tuple[SelfEnergy, SelfEnergy]: ...
    def density_fit(self, auxbasis=None, with_df=None): ...
    def get_ip(self, gf: Tuple[GreensFunction, GreensFunction], nroots: int = 5) -> Tuple[List[float64], List[ndarray], List[int64]]: ...
    def ipagf2(self, nroots: int = 5) -> Union[Tuple[float64, ndarray], Tuple[List[float64], List[ndarray]]]: ...
    def get_ea(self, gf: Tuple[GreensFunction, GreensFunction], nroots: int = 5) -> Tuple[List[float64], List[ndarray], List[int64]]: ...
    def eaagf2(self, nroots: int = 5) -> Union[Tuple[float64, ndarray], Tuple[List[float64], List[ndarray]]]: ...
    @property
    def nocc(self): ...
    @nocc.setter
    def nocc(self, val) -> None: ...
    @property
    def nmo(self): ...
    @nmo.setter
    def nmo(self, val) -> None: ...
    @property
    def qmo_energy(self): ...
    @property
    def qmo_coeff(self): ...
    @property
    def qmo_occ(self): ...

def get_frozen_mask(agf2: Union[Incomplete, Incomplete, DFUAGF2]) -> Tuple[ndarray, ndarray]: ...

class _ChemistsERIs:
    mol: Incomplete
    mo_coeff: Incomplete
    nocc: Incomplete
    nmo: Incomplete
    fock: Incomplete
    h1e: Incomplete
    eri: Incomplete
    e_hf: Incomplete
    def __init__(self, mol: None=None) -> None: ...
