from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, lib as lib
from pyscf.agf2 import ragf2 as ragf2, ragf2_slow as ragf2_slow, uagf2 as uagf2
from pyscf.lib import logger as logger

def build_se_part(agf2, eri, gf_occ, gf_vir, os_factor: float = 1.0, ss_factor: float = 1.0): ...

class UAGF2(uagf2.UAGF2):
    nmom: Incomplete
    def __init__(self, mf, nmom=(None, 0), frozen=None, mo_energy=None, mo_coeff=None, mo_occ=None) -> None: ...
    build_se_part = build_se_part
    def build_se(self, eri=None, gf=None, os_factor=None, ss_factor=None, se_prev=None): ...
    def dump_flags(self, verbose=None): ...
    def run_diis(self, se, diis=None): ...

class _ChemistsERIs(uagf2._ChemistsERIs): ...
