from _typeshed import Incomplete
from pyscf import lib as lib, mcpdft as mcpdft
from pyscf.fci import direct_spin1 as direct_spin1
from pyscf.grad import mspdft as mspdft_grad

def nac_model(mc_grad, mo_coeff=None, ci=None, si_bra=None, si_ket=None, mf_grad=None, atmlst=None): ...

class NonAdiabaticCouplings(mspdft_grad.Gradients):
    mult_ediff: Incomplete
    use_etfs: Incomplete
    state: Incomplete
    def __init__(self, mc, state=None, mult_ediff: bool = False, use_etfs: bool = False) -> None: ...
    def get_wfn_response(self, si_bra=None, si_ket=None, state=None, si=None, verbose=None, **kwargs): ...
    def get_ham_response(self, **kwargs): ...
    def nac_model(self, mo_coeff=None, ci=None, si=None, si_bra=None, si_ket=None, state=None, mf_grad=None, atmlst=None, **kwargs): ...
    def kernel(self, *args, **kwargs): ...
