from _typeshed import Incomplete
from pyscf import lib as lib
from pyscf.fci import direct_spin1 as direct_spin1
from pyscf.grad import sacasscf as sacasscf_grad
from pyscf.lib import logger as logger
from pyscf.mcscf import newton_casscf as newton_casscf

def grad_elec_core(mc_grad, mo_coeff=None, atmlst=None, eris=None, mf_grad=None): ...
def grad_elec_active(mc_grad, mo_coeff=None, ci=None, atmlst=None, eris=None, mf_grad=None, verbose=None): ...
def gen_g_hop_active(mc, mo, ci0, eris, verbose=None): ...
def nac_csf(mc_grad, mo_coeff=None, ci=None, state=None, mf_grad=None, atmlst=None): ...

class NonAdiabaticCouplings(sacasscf_grad.Gradients):
    mult_ediff: Incomplete
    use_etfs: Incomplete
    def __init__(self, mc, state=None, mult_ediff: bool = False, use_etfs: bool = False) -> None: ...
    def make_fcasscf_nacs(self, state=None, casscf_attr=None, fcisolver_attr=None): ...
    def get_wfn_response(self, atmlst=None, state=None, verbose=None, mo=None, ci=None, **kwargs): ...
    def get_ham_response(self, state=None, atmlst=None, verbose=None, mo=None, ci=None, eris=None, mf_grad=None, **kwargs): ...
    def nac_csf(self, mo_coeff=None, ci=None, state=None, mf_grad=None, atmlst=None): ...
    def kernel(self, *args, **kwargs): ...
