from pyscf.pbc import scf as scf
from pyscf.pbc.ci import cisd as cisd, kcis_rhf as kcis_rhf
from pyscf.pbc.ci.kcis_rhf import KCIS
from pyscf.pbc.scf.khf import KRHF

def RCISD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
CISD = RCISD

def UCISD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def GCISD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def KCIS(mf: KRHF, frozen: None=None, mo_coeff: None=None, mo_occ: None=None) -> KCIS: ...
CIS = KCIS
