from pyscf.pbc import scf as scf
from pyscf.pbc.ci import cisd as cisd, kcis_rhf as kcis_rhf

def RCISD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
CISD = RCISD

def UCISD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def GCISD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def KCIS(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
CIS = KCIS
