from pyscf import lib as lib
from pyscf.ci import cisd as cisd, gcisd as gcisd, ucisd as ucisd
from pyscf.pbc import mp as mp, scf as scf

class RCISD(cisd.RCISD):
    def __init__(self, mf, frozen=None, mo_coeff=None, mo_occ=None) -> None: ...
    def ao2mo(self, mo_coeff=None): ...

class UCISD(ucisd.UCISD):
    def __init__(self, mf, frozen=None, mo_coeff=None, mo_occ=None) -> None: ...
    def ao2mo(self, mo_coeff=None): ...

class GCISD(gcisd.GCISD):
    def __init__(self, mf, frozen=None, mo_coeff=None, mo_occ=None) -> None: ...
    def ao2mo(self, mo_coeff=None): ...
