from _typeshed import Incomplete
from pyscf import gto as gto, lib as lib
from pyscf.data import nist as nist
from pyscf.lib import logger as logger
from pyscf.scf import ghf as ghf, hf as hf
from pyscf.x2c import x2c as x2c
from numpy import ndarray
from pyscf.gto.mole import Mole
from pyscf.scf.hf import RHF
from pyscf.scf.hf_symm import SymAdaptedRHF
from pyscf.scf.uhf import UHF
from typing import Callable, Optional, Tuple, Union

def sfx2c1e(mf): ...
sfx2c = sfx2c1e

class SFX2C1E_SCF(x2c._X2C_SCF):
    __name_mixin__: str
    with_x2c: Incomplete
    def __init__(self, mf: Union[RHF, SymAdaptedRHF, UHF]) -> None: ...
    def undo_x2c(self): ...
    def get_hcore(self, mol=None): ...
    def dip_moment(self, mol=None, dm=None, unit: str = 'Debye', verbose=..., picture_change: bool = True, **kwargs): ...
    def to_gpu(self): ...

class SpinFreeX2CHelper(x2c.X2CHelperBase):
    def get_hcore(self, mol: Optional[Mole]=None) -> ndarray: ...
    def picture_change(self, even_operator: Tuple[str, ndarray]=(None, None), odd_operator: Optional[ndarray]=None) -> ndarray: ...
    def get_xmat(self, mol: None=None) -> ndarray: ...
    def hcore_deriv_generator(self, mol: None=None, deriv: int = 1) -> Callable: ...
SpinFreeX2C = SpinFreeX2CHelper
