from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.data import nist as nist
from pyscf.gto import mole as mole
from pyscf.lib import logger as logger
from pyscf.scf import dhf as dhf, ghf as ghf, hf as hf

LINEAR_DEP_THRESHOLD: float

class X2CHelperBase(lib.StreamObject):
    approx: Incomplete
    xuncontract: Incomplete
    basis: Incomplete
    mol: Incomplete
    stdout: Incomplete
    verbose: Incomplete
    def __init__(self, mol) -> None: ...
    def dump_flags(self, verbose=None): ...
    def get_xmol(self, mol=None): ...
    def get_hcore(self, mol=None): ...
    def picture_change(self, even_operator=(None, None), odd_operator=None): ...
    def get_xmat(self, mol=None): ...
    def reset(self, mol=None): ...

class SpinorX2CHelper(X2CHelperBase): ...
X2C = SpinorX2CHelper

class SpinOrbitalX2CHelper(X2CHelperBase):
    def get_hcore(self, mol=None): ...
    def picture_change(self, even_operator=(None, None), odd_operator=None): ...
    def get_xmat(self, mol=None): ...

def get_hcore(mol): ...
def get_jk(mol, dm, hermi: int = 1, mf_opt=None, with_j: bool = True, with_k: bool = True, omega=None): ...
make_rdm1 = hf.make_rdm1

def init_guess_by_minao(mol): ...
def init_guess_by_1e(mol): ...
def init_guess_by_atom(mol): ...
def init_guess_by_chkfile(mol, chkfile_name, project=None): ...
def get_init_guess(mol, key: str = 'minao'): ...

class SCF(hf.SCF):
    with_x2c: Incomplete
    def __init__(self, mol) -> None: ...
    opt: Incomplete
    def build(self, mol=None): ...
    def dump_flags(self, verbose=None): ...
    def init_guess_by_minao(self, mol=None): ...
    def init_guess_by_atom(self, mol=None): ...
    def init_guess_by_chkfile(self, chkfile=None, project=None): ...
    def get_hcore(self, mol=None): ...
    def get_ovlp(self, mol=None): ...
    def get_occ(self, mo_energy=None, mo_coeff=None): ...
    make_rdm1: Incomplete
    def init_direct_scf(self, mol=None): ...
    def get_jk(self, mol=None, dm=None, hermi: int = 1, with_j: bool = True, with_k: bool = True, omega=None): ...
    def get_veff(self, mol=None, dm=None, dm_last: int = 0, vhf_last: int = 0, hermi: int = 1): ...
    def analyze(self, verbose=None): ...
    def dip_moment(self, mol=None, dm=None, unit: str = 'Debye', verbose=..., picture_change: bool = True, **kwargs): ...
    def x2c1e(self): ...
    x2c = x2c1e
    def sfx2c1e(self) -> None: ...
    def newton(self): ...
    def stability(self, internal=None, external=None, verbose=None, return_status: bool = False): ...
    def nuc_grad_method(self) -> None: ...
X2C_SCF = SCF

class UHF(SCF):
    def to_ks(self, xc: str = 'HF'): ...
    to_gpu = lib.to_gpu
X2C_UHF = UHF

class RHF(SCF):
    def __init__(self, mol) -> None: ...
    def to_ks(self, xc: str = 'HF'): ...
    to_gpu = lib.to_gpu
X2C_RHF = RHF

def x2c1e_ghf(mf): ...

class _X2C_SCF:
    def dump_flags(self, verbose=None): ...
    def reset(self, mol=None): ...

class X2C1E_GSCF(_X2C_SCF):
    __name_mixin__: str
    with_x2c: Incomplete
    def __init__(self, mf) -> None: ...
    def undo_x2c(self): ...
    def get_hcore(self, mol=None): ...
    def dip_moment(self, mol=None, dm=None, unit: str = 'Debye', verbose=..., picture_change: bool = True, **kwargs): ...
    def to_ks(self, xc: str = 'HF') -> None: ...
    def to_gpu(self): ...
