from pyscf import lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc.df import df as df
from pyscf.pbc.mp.kmp2 import get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc, padded_mo_coeff as padded_mo_coeff, padding_k_idx as padding_k_idx

def transform_integrals_incore(myadc): ...
def transform_integrals_outcore(myadc): ...
def transform_integrals_df(myadc): ...
def calculate_chunk_size(myadc): ...
