from pyscf import lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc.df import df as df
from pyscf.pbc.mp.kmp2 import get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc, padded_mo_coeff as padded_mo_coeff, padding_k_idx as padding_k_idx
from pyscf.pbc.adc.kadc_rhf import RADC
from typing import Callable

def transform_integrals_incore(myadc: RADC) -> Callable: ...
def transform_integrals_outcore(myadc): ...
def transform_integrals_df(myadc: RADC) -> Callable: ...
def calculate_chunk_size(myadc: RADC) -> int: ...
