from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.lo import cholesky_mos as cholesky_mos, orth as orth
from pyscf.soscf import ciah as ciah

def kernel(localizer, mo_coeff=None, callback=None, verbose=None): ...
def dipole_integral(mol, mo_coeff, charge_center=None): ...
def atomic_init_guess(mol, mo_coeff): ...

class OrbitalLocalizer(lib.StreamObject, ciah.CIAHOptimizerMixin):
    conv_tol: Incomplete
    conv_tol_grad: Incomplete
    max_cycle: Incomplete
    max_iters: Incomplete
    max_stepsize: Incomplete
    ah_trust_region: Incomplete
    ah_start_tol: Incomplete
    ah_max_cycle: Incomplete
    init_guess: Incomplete
    mol: Incomplete
    stdout: Incomplete
    verbose: Incomplete
    mo_coeff: Incomplete
    def __init__(self, mol, mo_coeff=None) -> None: ...
    def dump_flags(self, verbose=None) -> None: ...
    def get_init_guess(self, key: str = 'atomic'): ...
    def gen_g_hop(self, u) -> None: ...
    def get_grad(self, u=None) -> None: ...
    def cost_function(self, u=None) -> None: ...
    kernel = kernel

class Boys(OrbitalLocalizer):
    def gen_g_hop(self, u): ...
    def get_grad(self, u=None): ...
    def cost_function(self, u=None): ...
FB = Boys
BF = Boys
