from pyscf.lo import boys as boys
from pyscf.scf import hf as hf

class EdmistonRuedenberg(boys.OrbitalLocalizer):
    def get_jk(self, u): ...
    def gen_g_hop(self, u): ...
    def get_grad(self, u): ...
    def cost_function(self, u): ...
ER = EdmistonRuedenberg
Edmiston = EdmistonRuedenberg
