from _typeshed import Incomplete
from pyscf import __config__ as __config__
from pyscf.lib import logger as logger
from pyscf.lo import iao as iao, orth as orth, pipek as pipek

MINAO: Incomplete

def ibo(mol, orbocc, locmethod: str = 'IBO', iaos=None, s=None, exponent: int = 4, grad_tol: float = 1e-08, max_iter: int = 200, minao=..., verbose=...): ...
def ibo_loc(mol, orbocc, iaos, s, exponent, grad_tol, max_iter, minao=..., verbose=...): ...
def PipekMezey(mol, orbocc, iaos, s, exponent, minao=...): ...
PM = PipekMezey
Pipek = PipekMezey

def shell_str(l, n_cor, n_val): ...
def MakeAtomInfos(): ...
def MakeAtomIbOffsets(Atoms): ...
