from _typeshed import Incomplete
from pyscf import __config__ as __config__, gto as gto
from pyscf.lib import logger as logger, param as param

REF_BASIS: Incomplete
ORTH_METHOD: Incomplete
PROJECT_ECP_BASIS: Incomplete

def lowdin(s): ...
def schmidt(s): ...
def vec_lowdin(c, s: int = 1): ...
def vec_schmidt(c, s: int = 1): ...
def weight_orth(s, weight): ...
def pre_orth_ao(mol, method=...): ...
restore_ao_character = pre_orth_ao

def project_to_atomic_orbitals(mol, ref_basis): ...
pre_orth_project_ano = project_to_atomic_orbitals

def pre_orth_ao_atm_scf(mol): ...
def orth_ao(mf_or_mol, method=..., pre_orth_ao=..., s=None): ...
