from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.lo import boys as boys, orth as orth, pipek_jacobi as pipek_jacobi

def atomic_pops(mol, mo_coeff, method: str = 'meta_lowdin', mf=None, s=None, charge_matrices=None): ...
def becke_charge_matrices(mol): ...

class PipekMezey(boys.OrbitalLocalizer):
    pop_method: Incomplete
    conv_tol: Incomplete
    exponent: Incomplete
    def __init__(self, mol, mo_coeff=None, mf=None, pop_method=None) -> None: ...
    def dump_flags(self, verbose=None) -> None: ...
    def gen_g_hop(self, u): ...
    def get_grad(self, u=None): ...
    def cost_function(self, u=None): ...
    def atomic_pops(self, mol, mo_coeff, method=None, s=None): ...
    def stability_jacobi(self): ...
PM = PipekMezey
Pipek = PipekMezey
