from pyscf import __config__ as __config__
from pyscf.lo import iao as iao, ibo as ibo, orth as orth

def vvo(mol, orbocc, orbvirt, iaos=None, s=None, verbose=None): ...
def livvo(mol, orbocc, orbvirt, locmethod: str = 'IBO', iaos=None, s=None, exponent: int = 4, grad_tol: float = 1e-08, max_iter: int = 200, verbose=None): ...
