from pyscf import __config__ as __config__, df as df, gto as gto, lib as lib, mcscf as mcscf, scf as scf
from pyscf.ao2mo.outcore import balance_partition as balance_partition
from pyscf.grad.rhf import GradientsBase as GradientsBase

def get_int3c_mo(mol, auxmol, mo_coeff, compact=..., max_memory=None): ...
def solve_df_rdm2(mc_or_mc_grad, mo_cas=None, ci=None, casdm2=None): ...
def solve_df_eri(mc_or_mc_grad, mo_cas=None, compact: bool = True): ...
def energy_elec_dferi(mc, mo_cas=None, ci=None, dfcasdm2=None, casdm2=None): ...
def gfock_dferi(mc, mo_cas=None, ci=None, dfcasdm2=None, casdm2=None, max_memory=None, ao_basis: bool = True): ...
def grad_elec_auxresponse_dferi(mc_grad, mo_cas=None, ci=None, dfcasdm2=None, casdm2=None, atmlst=None, max_memory=None, dferi=None, incl_2c: bool = True): ...
def grad_elec_dferi(mc_grad, mo_cas=None, ci=None, dfcasdm2=None, casdm2=None, atmlst=None, max_memory=None): ...
