from pyscf import __config__ as __config__, df as df, gto as gto, lib as lib, mcscf as mcscf, scf as scf
from pyscf.ao2mo.outcore import balance_partition as balance_partition
from pyscf.grad.rhf import GradientsBase as GradientsBase
from numpy import ndarray
from pyscf.df.grad.casscf import Gradients
from pyscf.gto.mole import Mole
from typing import List, Optional, Tuple, Union

def get_int3c_mo(mol: Mole, auxmol: Mole, mo_coeff: Union[ndarray, Tuple[ndarray, ndarray]], compact: bool=..., max_memory: Optional[int]=None) -> ndarray: ...
def solve_df_rdm2(mc_or_mc_grad: Gradients, mo_cas: Optional[ndarray]=None, ci: None=None, casdm2: Optional[ndarray]=None) -> List[ndarray]: ...
def solve_df_eri(mc_or_mc_grad, mo_cas=None, compact: bool = True): ...
def energy_elec_dferi(mc, mo_cas=None, ci=None, dfcasdm2=None, casdm2=None): ...
def gfock_dferi(mc, mo_cas=None, ci=None, dfcasdm2=None, casdm2=None, max_memory=None, ao_basis: bool = True): ...
def grad_elec_auxresponse_dferi(mc_grad: Gradients, mo_cas: Optional[ndarray]=None, ci: None=None, dfcasdm2: Optional[List[ndarray]]=None, casdm2: None=None, atmlst: Optional[range]=None, max_memory: Optional[int]=None, dferi: None=None, incl_2c: bool = True) -> ndarray: ...
def grad_elec_dferi(mc_grad: Gradients, mo_cas: Optional[ndarray]=None, ci: None=None, dfcasdm2: Optional[List[ndarray]]=None, casdm2: None=None, atmlst: Optional[range]=None, max_memory: Optional[int]=None) -> ndarray: ...
