from pyscf import lib as lib
from pyscf.grad import mspdft as mspdft_grad

class Gradients(mspdft_grad.Gradients):
    auxbasis_response: bool
    def __init__(self, pdft) -> None: ...
    def make_fcasscf(self, state=None, casscf_attr={}, fcisolver_attr={}): ...
    def get_ham_response(self, **kwargs): ...
    def get_LdotJnuc(self, Lvec, **kwargs): ...
