from pyscf import df as df, gto as gto, lib as lib, scf as scf
from pyscf.ao2mo.outcore import balance_partition as balance_partition
from pyscf.df import df_jk as df_jk
from pyscf.df.incore import LINEAR_DEP_THR as LINEAR_DEP_THR
from pyscf.grad import rhf as rhf_grad
from pyscf.gto.moleintor import getints as getints, make_cintopt as make_cintopt
from pyscf.lib import logger as logger

LINEAR_DEP_THRESHOLD = LINEAR_DEP_THR

def get_jk(mf_grad, mol=None, dm=None, hermi: int = 0, with_j: bool = True, with_k: bool = True, decompose_j2c: str = 'CD', lindep=...): ...
def get_j(mf_grad, mol=None, dm=None, hermi: int = 0): ...

class Gradients(rhf_grad.Gradients):
    def __init__(self, mf) -> None: ...
    auxbasis_response: bool
    def check_sanity(self) -> None: ...
    def get_jk(self, mol=None, dm=None, hermi: int = 0, with_j: bool = True, with_k: bool = True, omega=None): ...
    def get_j(self, mol=None, dm=None, hermi: int = 0, omega=None): ...
    def get_k(self, mol=None, dm=None, hermi: int = 0, omega=None): ...
    def get_veff(self, mol=None, dm=None): ...
    def extra_force(self, atom_id, envs): ...
Grad = Gradients
