from pyscf import df as df, gto as gto, lib as lib, scf as scf
from pyscf.ao2mo.outcore import balance_partition as balance_partition
from pyscf.df import df_jk as df_jk
from pyscf.df.incore import LINEAR_DEP_THR as LINEAR_DEP_THR
from pyscf.grad import rhf as rhf_grad
from pyscf.gto.moleintor import getints as getints, make_cintopt as make_cintopt
from pyscf.lib import logger as logger
from _typeshed import Incomplete
from numpy import ndarray
from pyscf.gto.mole import Mole
from pyscf.lib.numpy_helper import NPArrayWithTag
from typing import Callable, List, Optional, Tuple, Union

LINEAR_DEP_THRESHOLD = LINEAR_DEP_THR

def get_jk(mf_grad: Union[Incomplete, Incomplete, Incomplete, Incomplete, Incomplete], mol: Optional[Mole]=None, dm: Optional[Union[Tuple[ndarray, ndarray, ndarray, ndarray], Tuple[ndarray, ndarray], NPArrayWithTag]]=None, hermi: int = 0, with_j: bool = True, with_k: bool = True, decompose_j2c: str = 'CD', lindep: float=...) -> Union[Tuple[ndarray, ndarray], Tuple[None, NPArrayWithTag], Tuple[NPArrayWithTag, NPArrayWithTag]]: ...
def get_j(mf_grad: Union[Incomplete, Incomplete], mol: Optional[Mole]=None, dm: Optional[NPArrayWithTag]=None, hermi: int = 0) -> Union[ndarray, NPArrayWithTag]: ...

class Gradients(rhf_grad.Gradients):
    def __init__(self, mf) -> None: ...
    auxbasis_response: bool
    def check_sanity(self) -> None: ...
    def get_jk(self, mol: Optional[Mole]=None, dm: Optional[Union[Tuple[ndarray, ndarray, ndarray, ndarray], Tuple[ndarray, ndarray], NPArrayWithTag]]=None, hermi: int = 0, with_j: bool = True, with_k: bool = True, omega: Optional[float]=None) -> Union[Tuple[ndarray, ndarray], Tuple[None, NPArrayWithTag], Tuple[NPArrayWithTag, NPArrayWithTag]]: ...
    def get_j(self, mol: Optional[Mole]=None, dm: Optional[NPArrayWithTag]=None, hermi: int = 0, omega: None=None) -> Union[ndarray, NPArrayWithTag]: ...
    def get_k(self, mol: Optional[Mole]=None, dm: Optional[NPArrayWithTag]=None, hermi: int = 0, omega: Optional[float]=None) -> NPArrayWithTag: ...
    def get_veff(self, mol: Optional[Mole]=None, dm: Optional[NPArrayWithTag]=None) -> Union[ndarray, NPArrayWithTag]: ...
    def extra_force(self, atom_id, envs): ...
Grad = Gradients
