from _typeshed import Incomplete
from pyscf import df as df, grad as grad, gto as gto, lib as lib, mcscf as mcscf, scf as scf
from pyscf.lib import logger as logger
from pyscf.qmmm import mm_mole as mm_mole

def add_mm_charges(scf_method, atoms_or_coords, charges, radii=None, unit=None): ...
mm_charge = add_mm_charges

def qmmm_for_scf(method, mm_mol): ...

class QMMM:
    __name_mixin__: str

class QMMMSCF(QMMM):
    mm_mol: Incomplete
    def __init__(self, method, mm_mol=None) -> None: ...
    def undo_qmmm(self): ...
    def dump_flags(self, verbose=None): ...
    def get_hcore(self, mol=None): ...
    def energy_nuc(self): ...
    def to_gpu(self): ...
    def nuc_grad_method(self): ...
    Gradients = nuc_grad_method

class QMMMPostSCF(QMMM):
    mo_coeff: Incomplete
    mo_energy: Incomplete
    def __init__(self, method, mm_mol=None) -> None: ...
    def undo_qmmm(self): ...
    to_gpu: Incomplete

def add_mm_charges_grad(scf_grad, atoms_or_coords, charges, radii=None, unit=None): ...
mm_charge_grad = add_mm_charges_grad

def qmmm_grad_for_scf(scf_grad): ...

class QMMMGrad:
    __name_mixin__: str
    def __init__(self, scf_grad) -> None: ...
    def dump_flags(self, verbose=None): ...
    def get_hcore(self, mol=None): ...
    def grad_hcore_mm(self, dm, mol=None): ...
    contract_hcore_mm = grad_hcore_mm
    def grad_nuc(self, mol=None, atmlst=None): ...
    def grad_nuc_mm(self, mol=None): ...
    def to_gpu(self): ...
