from _typeshed import Incomplete

H: Incomplete
He: Incomplete
Li: Incomplete
Be: Incomplete
B: Incomplete
C: Incomplete
N: Incomplete
O: Incomplete
F: Incomplete
Ne: Incomplete
Na: Incomplete
Mg: Incomplete
Al: Incomplete
Si: Incomplete
P: Incomplete
S: Incomplete
Cl: Incomplete
Ar: Incomplete
Ca: Incomplete
Sc: Incomplete
Ti: Incomplete
V: Incomplete
Cr: Incomplete
Mn: Incomplete
Fe: Incomplete
Co: Incomplete
Ni: Incomplete
Cu: Incomplete
Zn: Incomplete
Ga: Incomplete
Ge: Incomplete
As: Incomplete
Se: Incomplete
Br: Incomplete
Kr: Incomplete
Y: Incomplete
Zr: Incomplete
Nb: Incomplete
Mo: Incomplete
Tc: Incomplete
Ru: Incomplete
Rh: Incomplete
Pd: Incomplete
Ag: Incomplete
Cd: Incomplete
In: Incomplete
Sn: Incomplete
Sb: Incomplete
Te: Incomplete
I: Incomplete
Xe: Incomplete
Hf: Incomplete
Ta: Incomplete
W: Incomplete
Re: Incomplete
Os: Incomplete
Ir: Incomplete
Pt: Incomplete
Au: Incomplete
Hg: Incomplete
Tl: Incomplete
Pb: Incomplete
Bi: Incomplete
Po: Incomplete
At: Incomplete
Rn: Incomplete
