from numpy import float64
from typing import Any, List, Optional, Union

__all__ = ['parse', 'load', 'convert_ecp_to_nwchem']

def parse(string: str, symb: Optional[str]=None) -> List[Union[int, List[List[Union[int, List[List[Any]], List[List[Union[Any, List[float]]]]]]], List[List[Union[int, List[List[Union[Any, List[float]]]], List[List[Union[List[Union[float, float64]], Any]]]]]], List[List[Union[int, List[List[Union[Any, List[float]]]]]]]]]: ...
def load(basisfile: str, symb: str) -> List[Union[int, List[List[Union[int, List[List[Union[Any, List[float]]]]]]], Any]]: ...
def convert_ecp_to_nwchem(symb: str, ecp: List[Union[int, List[List[Union[int, List[List[Union[Any, List[float]]]], List[List[Union[List[Union[float, float64]], Any]]]]]]]]) -> str: ...
