from pyscf.gto.basis.parse_nwchem_ecp import convert_ecp_to_nwchem as convert_ecp_to_nwchem, load as load_ecp, parse as parse_ecp

__all__ = ['parse', 'load', 'parse_ecp', 'load_ecp', 'convert_basis_to_nwchem', 'convert_ecp_to_nwchem', 'optimize_contraction', 'remove_zero', 'to_general_contraction']

def parse(string, symb=None, optimize: bool = True): ...
def load(basisfile, symb, optimize: bool = True): ...
def convert_basis_to_nwchem(symb, basis): ...
def optimize_contraction(basis): ...
def to_general_contraction(basis): ...
def remove_zero(basis): ...
