from typing import Any, List, Union

__all__ = ['parse', 'load']

def parse(string: str, optimize: bool = True) -> List[List[Union[int, List[float]]]]: ...
def load(basisfile, symb, optimize: bool = True): ...
