from _typeshed import Incomplete
from pyscf.lib.exceptions import BasisNotFoundError as BasisNotFoundError

MAPSPDF: Incomplete

def parse(symb, basistype): ...
def parse_ecp(symb): ...
def search_seg(basisfile, symb): ...
