from pyscf.lib.exceptions import BasisNotFoundError as BasisNotFoundError
from typing import Any, List, Optional, Union

def parse(string: str, symb: Optional[str]=None) -> List[Any]: ...
def load(pseudofile: str, symb: str, suffix: None=None) -> List[Any]: ...
def search_seg(pseudofile: str, symb: str, suffix: None=None) -> List[str]: ...
