from typing import List, Union

__all__ = ['parse', 'load']

def parse(string: str, optimize: bool = True) -> List[List[Union[int, List[float]]]]: ...
def load(basisfile: str, symb: str, optimize: bool = True) -> List[List[Union[int, List[float]]]]: ...
