from pyscf.lib.exceptions import BasisNotFoundError as BasisNotFoundError

def parse(string, symb=None): ...
def load(pseudofile, symb, suffix=None): ...
def search_seg(pseudofile, symb, suffix=None): ...
