from pyscf.gto.basis.parse_nwchem_ecp import convert_ecp_to_nwchem as convert_ecp_to_nwchem, load as load_ecp, parse as parse_ecp
from typing import Any, List, Optional, Union

__all__ = ['parse', 'load', 'parse_ecp', 'load_ecp', 'convert_basis_to_nwchem', 'convert_ecp_to_nwchem', 'optimize_contraction', 'remove_zero', 'to_general_contraction']

def parse(string: str, symb: Optional[str]=None, optimize: bool = True) -> List[List[Union[int, List[float]]]]: ...
def load(basisfile: str, symb: str, optimize: bool = True) -> List[List[Union[int, List[float]]]]: ...
def convert_basis_to_nwchem(symb: str, basis: List[List[Union[int, List[Union[int, float]], List[float]]]]) -> str: ...
def optimize_contraction(basis: List[List[Union[int, List[float]]]]) -> List[List[Union[int, List[float]]]]: ...
def to_general_contraction(basis: List[List[Union[int, List[float]]]]) -> List[List[Union[int, List[float]]]]: ...
def remove_zero(basis: List[List[Union[int, List[float]]]]) -> List[List[Union[int, List[float]]]]: ...
