from pyscf import scf as scf
from pyscf.cc import qcisd as qcisd
from pyscf.ci import cisd as cisd, gcisd as gcisd, ucisd as ucisd
from pyscf.ci.cisd import RCISD
from pyscf.ci.gcisd import GCISD
from pyscf.ci.ucisd import UCISD
from pyscf.scf.ghf import GHF
from pyscf.scf.hf import RHF
from pyscf.scf.rohf import ROHF
from pyscf.scf.uhf import UHF
from typing import Union

def CISD(mf: Union[RHF, ROHF, UHF], frozen: None=None, mo_coeff: None=None, mo_occ: None=None) -> Union[RCISD, UCISD]: ...
def RCISD(mf: RHF, frozen: None=None, mo_coeff: None=None, mo_occ: None=None) -> RCISD: ...
def UCISD(mf: Union[ROHF, UHF], frozen: None=None, mo_coeff: None=None, mo_occ: None=None) -> UCISD: ...
def GCISD(mf: Union[GHF, ROHF, UHF], frozen: None=None, mo_coeff: None=None, mo_occ: None=None) -> GCISD: ...
def QCISD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def RQCISD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
