from pyscf import scf as scf
from pyscf.cc import qcisd as qcisd
from pyscf.ci import cisd as cisd, gcisd as gcisd, ucisd as ucisd

def CISD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def RCISD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def UCISD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def GCISD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def QCISD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def RQCISD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
