from _typeshed import Incomplete
from pyscf import __config__ as __config__, gto as gto, lib as lib, scf as scf
from pyscf.cc import ccsd as ccsd, ccsd_rdm as ccsd_rdm
from pyscf.fci import cistring as cistring
from pyscf.lib import logger as logger

BLKMIN: Incomplete

def kernel(myci, eris, ci0=None, max_cycle: int = 50, tol: float = 1e-08, verbose=...): ...
def make_diagonal(myci, eris): ...
def contract(myci, civec, eris): ...
def amplitudes_to_cisdvec(c0, c1, c2): ...
def cisdvec_to_amplitudes(civec, nmo, nocc, copy: bool = True): ...
def dot(v1, v2, nmo, nocc): ...
def t1strs(norb, nelec): ...
def tn_addrs_signs(norb, nelec, n_excite): ...
def to_fcivec(cisdvec, norb, nelec, frozen=None): ...
def from_fcivec(ci0, norb, nelec, frozen=None): ...
def overlap(cibra, ciket, nmo, nocc, s=None): ...
def make_rdm1(myci, civec=None, nmo=None, nocc=None, ao_repr: bool = False): ...
def make_rdm2(myci, civec=None, nmo=None, nocc=None, ao_repr: bool = False): ...
def trans_rdm1(myci, cibra, ciket, nmo=None, nocc=None): ...
def as_scanner(ci): ...

class CISD_Scanner(lib.SinglePointScanner):
    def __init__(self, ci) -> None: ...
    mo_coeff: Incomplete
    mo_occ: Incomplete
    ci: Incomplete
    def __call__(self, mol_or_geom, ci0=None, **kwargs): ...

class CISD(lib.StreamObject):
    conv_tol: Incomplete
    max_cycle: Incomplete
    max_space: Incomplete
    lindep: Incomplete
    level_shift: Incomplete
    direct: Incomplete
    async_io: Incomplete
    mol: Incomplete
    verbose: Incomplete
    stdout: Incomplete
    max_memory: Incomplete
    nroots: int
    frozen: Incomplete
    chkfile: Incomplete
    converged: bool
    mo_coeff: Incomplete
    mo_occ: Incomplete
    e_hf: Incomplete
    e_corr: Incomplete
    emp2: Incomplete
    ci: Incomplete
    def __init__(self, mf, frozen=None, mo_coeff=None, mo_occ=None) -> None: ...
    def dump_flags(self, verbose=None): ...
    @property
    def e_tot(self): ...
    @property
    def nstates(self): ...
    @nstates.setter
    def nstates(self, x) -> None: ...
    @property
    def nocc(self): ...
    @nocc.setter
    def nocc(self, n) -> None: ...
    @property
    def nmo(self): ...
    @nmo.setter
    def nmo(self, n) -> None: ...
    def vector_size(self): ...
    def reset(self, mol=None): ...
    get_nocc = ccsd.get_nocc
    get_nmo = ccsd.get_nmo
    get_frozen_mask = ccsd.get_frozen_mask
    get_e_hf = ccsd.get_e_hf
    def kernel(self, ci0=None, eris=None): ...
    def cisd(self, ci0=None, eris=None): ...
    def get_init_guess(self, eris=None, nroots: int = 1, diag=None): ...
    contract = contract
    make_diagonal = make_diagonal
    def ao2mo(self, mo_coeff=None): ...
    def to_fcivec(self, cisdvec, norb=None, nelec=None, frozen=None): ...
    def from_fcivec(self, fcivec, norb=None, nelec=None): ...
    make_rdm1 = make_rdm1
    make_rdm2 = make_rdm2
    trans_rdm1 = trans_rdm1
    as_scanner = as_scanner
    def dump_chk(self, ci=None, frozen=None, mo_coeff=None, mo_occ=None): ...
    def amplitudes_to_cisdvec(self, c0, c1, c2): ...
    def cisdvec_to_amplitudes(self, civec, nmo=None, nocc=None, copy: bool = True): ...
    def density_fit(self) -> None: ...
    def nuc_grad_method(self): ...
    to_gpu = lib.to_gpu

class RCISD(CISD): ...
