from _typeshed import Incomplete
from pyscf import __config__ as __config__, gto as gto, lib as lib, scf as scf
from pyscf.cc import ccsd as ccsd, ccsd_rdm as ccsd_rdm
from pyscf.fci import cistring as cistring
from pyscf.lib import logger as logger
from h5py._hl.dataset import Dataset
from numpy import bool, complex128, float64, ndarray
from pyscf.cc.gccsd import _PhysicistsERIs
from pyscf.ci.ucisd import UCISD
from pyscf.gto.mole import Mole
from pyscf.lib.misc import H5TmpFile
from pyscf.pbc.ci.cisd import RCISD
from pyscf.scf.hf import SCF
from typing import List, Optional, Tuple, Union

BLKMIN: Incomplete

def kernel(myci: "CISD", eris: Union[Incomplete, Incomplete, _PhysicistsERIs, Incomplete], ci0: None=None, max_cycle: int = 50, tol: float = 1e-08, verbose: int=...) -> Union[Tuple[bool, float64, ndarray], Tuple[ndarray, ndarray, List[ndarray]]]: ...
def make_diagonal(myci: Union[RCISD, CISD, RCISD], eris: Union[Incomplete, Incomplete]) -> ndarray: ...
def contract(myci: Union[RCISD, CISD, RCISD], civec: ndarray, eris: Union[Incomplete, Incomplete]) -> ndarray: ...
def amplitudes_to_cisdvec(c0: Union[complex128, int, float64, ndarray], c1: ndarray, c2: ndarray) -> ndarray: ...
def cisdvec_to_amplitudes(civec: ndarray, nmo: int, nocc: int, copy: bool = True) -> Union[Tuple[complex128, ndarray, ndarray], Tuple[float64, ndarray, ndarray]]: ...
def dot(v1: ndarray, v2: ndarray, nmo: int, nocc: int) -> float64: ...
def t1strs(norb: int, nelec: int) -> Tuple[ndarray, ndarray]: ...
def tn_addrs_signs(norb: int, nelec: int, n_excite: int) -> Tuple[ndarray, ndarray]: ...
def to_fcivec(cisdvec: ndarray, norb: int, nelec: Union[int, Tuple[int, int]], frozen: Optional[List[int]]=None) -> ndarray: ...
def from_fcivec(ci0: ndarray, norb: int, nelec: Union[int, Tuple[int, int]], frozen: None=None) -> ndarray: ...
def overlap(cibra: ndarray, ciket: ndarray, nmo: int, nocc: int, s: Optional[ndarray]=None) -> float64: ...
def make_rdm1(myci: Union[RCISD, CISD], civec: Optional[ndarray]=None, nmo: Optional[int]=None, nocc: Optional[int]=None, ao_repr: bool = False) -> ndarray: ...
def make_rdm2(myci: Union[RCISD, CISD], civec: Optional[ndarray]=None, nmo: Optional[int]=None, nocc: Optional[int]=None, ao_repr: bool = False) -> ndarray: ...
def trans_rdm1(myci: "RCISD", cibra: ndarray, ciket: ndarray, nmo: Optional[int]=None, nocc: Optional[int]=None) -> ndarray: ...
def as_scanner(ci): ...

class CISD_Scanner(lib.SinglePointScanner):
    def __init__(self, ci: "RCISD") -> None: ...
    mo_coeff: Incomplete
    mo_occ: Incomplete
    ci: Incomplete
    def __call__(self, mol_or_geom, ci0=None, **kwargs): ...

class CISD(lib.StreamObject):
    conv_tol: Incomplete
    max_cycle: Incomplete
    max_space: Incomplete
    lindep: Incomplete
    level_shift: Incomplete
    direct: Incomplete
    async_io: Incomplete
    mol: Incomplete
    verbose: Incomplete
    stdout: Incomplete
    max_memory: Incomplete
    nroots: int
    frozen: Incomplete
    chkfile: Incomplete
    converged: bool
    mo_coeff: Incomplete
    mo_occ: Incomplete
    e_hf: Incomplete
    e_corr: Incomplete
    emp2: Incomplete
    ci: Incomplete
    def __init__(self, mf: SCF, frozen: None=None, mo_coeff: None=None, mo_occ: None=None) -> None: ...
    def dump_flags(self, verbose: None=None) -> "CISD": ...
    @property
    def e_tot(self) -> Union[ndarray, float64]: ...
    @property
    def nstates(self): ...
    @nstates.setter
    def nstates(self, x) -> None: ...
    @property
    def nocc(self): ...
    @nocc.setter
    def nocc(self, n) -> None: ...
    @property
    def nmo(self): ...
    @nmo.setter
    def nmo(self, n) -> None: ...
    def vector_size(self) -> int: ...
    def reset(self, mol: Optional[Mole]=None) -> UCISD: ...
    get_nocc = ccsd.get_nocc
    get_nmo = ccsd.get_nmo
    get_frozen_mask = ccsd.get_frozen_mask
    get_e_hf = ccsd.get_e_hf
    def kernel(self, ci0: None=None, eris: Optional[Union[Incomplete, _PhysicistsERIs, Incomplete]]=None) -> Union[Tuple[ndarray, List[ndarray]], Tuple[float64, ndarray]]: ...
    def cisd(self, ci0: None=None, eris: Optional[Union[Incomplete, _PhysicistsERIs, Incomplete]]=None) -> Union[Tuple[ndarray, List[ndarray]], Tuple[float64, ndarray]]: ...
    def get_init_guess(self, eris: Optional[Union[Incomplete, Incomplete]]=None, nroots: int = 1, diag: Optional[ndarray]=None) -> Union[Tuple[float64, List[ndarray]], Tuple[float64, ndarray]]: ...
    contract = contract
    make_diagonal = make_diagonal
    def ao2mo(self, mo_coeff: Optional[ndarray]=None) -> Incomplete: ...
    def to_fcivec(self, cisdvec: ndarray, norb: Optional[int]=None, nelec: Optional[Union[int, Tuple[int, int]]]=None, frozen: None=None) -> ndarray: ...
    def from_fcivec(self, fcivec: ndarray, norb: Optional[int]=None, nelec: Optional[int]=None) -> ndarray: ...
    make_rdm1 = make_rdm1
    make_rdm2 = make_rdm2
    trans_rdm1 = trans_rdm1
    as_scanner = as_scanner
    def dump_chk(self, ci: None=None, frozen: None=None, mo_coeff: None=None, mo_occ: None=None): ...
    def amplitudes_to_cisdvec(self, c0: Union[complex128, float64], c1: ndarray, c2: ndarray) -> ndarray: ...
    def cisdvec_to_amplitudes(self, civec: ndarray, nmo: Optional[int]=None, nocc: Optional[int]=None, copy: bool = True) -> Union[Tuple[complex128, ndarray, ndarray], Tuple[float64, ndarray, ndarray]]: ...
    def density_fit(self) -> None: ...
    def nuc_grad_method(self): ...
    to_gpu = lib.to_gpu

class RCISD(CISD): ...
