from _typeshed import Incomplete
from pyscf import lib as lib, scf as scf
from pyscf.cc import ccsd as ccsd, gccsd as gccsd, gccsd_rdm as gccsd_rdm
from pyscf.cc.addons import spatial2spin as spatial2spin, spin2spatial as spin2spatial
from pyscf.ci import cisd as cisd, ucisd as ucisd
from pyscf.lib import logger as logger

def make_diagonal(myci, eris): ...
def contract(myci, civec, eris): ...
def amplitudes_to_cisdvec(c0, c1, c2): ...
def cisdvec_to_amplitudes(civec, nmo, nocc, copy: bool = True): ...
def from_ucisdvec(civec, nocc, orbspin): ...
from_rcisdvec = from_ucisdvec

def to_ucisdvec(civec, nmo, nocc, orbspin): ...
def to_fcivec(cisdvec, nelec, orbspin, frozen=None): ...
def from_fcivec(ci0, nelec, orbspin, frozen=None): ...
def make_rdm1(myci, civec=None, nmo=None, nocc=None, ao_repr: bool = False): ...
def make_rdm2(myci, civec=None, nmo=None, nocc=None, ao_repr: bool = False): ...
def trans_rdm1(myci, cibra, ciket, nmo=None, nocc=None): ...

class GCISD(cisd.CISD):
    def vector_size(self): ...
    emp2: Incomplete
    def get_init_guess(self, eris=None, nroots: int = 1, diag=None): ...
    def ao2mo(self, mo_coeff=None): ...
    contract = contract
    make_diagonal = make_diagonal
    def to_fcivec(self, cisdvec, nelec, orbspin, frozen=None): ...
    def from_fcivec(self, fcivec, nelec, orbspin, frozen=None): ...
    make_rdm1 = make_rdm1
    make_rdm2 = make_rdm2
    trans_rdm1 = trans_rdm1
    def amplitudes_to_cisdvec(self, c0, c1, c2): ...
    def cisdvec_to_amplitudes(self, civec, nmo=None, nocc=None, copy: bool = True): ...
    def from_ucisdvec(self, civec, nocc=None, orbspin=None): ...
    from_rcisdvec = from_ucisdvec
    def to_ucisdvec(self, civec, orbspin=None): ...
    def spatial2spin(self, tx, orbspin=None): ...
    def spin2spatial(self, tx, orbspin=None): ...
CISD = GCISD
