from _typeshed import Incomplete
from pyscf import lib as lib, scf as scf
from pyscf.cc import ccsd as ccsd, gccsd as gccsd, gccsd_rdm as gccsd_rdm
from pyscf.cc.addons import spatial2spin as spatial2spin, spin2spatial as spin2spatial
from pyscf.ci import cisd as cisd, ucisd as ucisd
from pyscf.lib import logger as logger
from numpy import complex128, float64, ndarray
from pyscf.cc.gccsd import _PhysicistsERIs
from pyscf.fci.direct_spin1 import FCIvector
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.ci.cisd import GCISD
from typing import List, Optional, Tuple, Union

def make_diagonal(myci: Union[GCISD, GCISD], eris: _PhysicistsERIs) -> ndarray: ...
def contract(myci: Union[GCISD, GCISD], civec: ndarray, eris: _PhysicistsERIs) -> ndarray: ...
def amplitudes_to_cisdvec(c0: Union[complex128, float, float64, int], c1: Union[ndarray, NPArrayWithTag], c2: Union[ndarray, NPArrayWithTag]) -> ndarray: ...
def cisdvec_to_amplitudes(civec: ndarray, nmo: int, nocc: int, copy: bool = True) -> Union[Tuple[float64, ndarray, ndarray], Tuple[complex128, ndarray, ndarray]]: ...
def from_ucisdvec(civec: ndarray, nocc: Union[int, Tuple[int, int]], orbspin: ndarray) -> ndarray: ...
from_rcisdvec = from_ucisdvec

def to_ucisdvec(civec: ndarray, nmo: int, nocc: int, orbspin: ndarray) -> ndarray: ...
def to_fcivec(cisdvec: ndarray, nelec: int, orbspin: ndarray, frozen: Optional[List[int]]=None) -> ndarray: ...
def from_fcivec(ci0: Union[ndarray, FCIvector], nelec: int, orbspin: ndarray, frozen: None=None) -> ndarray: ...
def make_rdm1(myci: "GCISD", civec: Optional[ndarray]=None, nmo: Optional[int]=None, nocc: Optional[int]=None, ao_repr: bool = False) -> ndarray: ...
def make_rdm2(myci: "GCISD", civec: Optional[ndarray]=None, nmo: Optional[int]=None, nocc: Optional[int]=None, ao_repr: bool = False) -> ndarray: ...
def trans_rdm1(myci: "GCISD", cibra: ndarray, ciket: ndarray, nmo: Optional[int]=None, nocc: Optional[int]=None) -> ndarray: ...

class GCISD(cisd.CISD):
    def vector_size(self) -> int: ...
    emp2: Incomplete
    def get_init_guess(self, eris: Optional[_PhysicistsERIs]=None, nroots: int = 1, diag: Optional[ndarray]=None) -> Union[Tuple[float64, ndarray], Tuple[float64, List[ndarray]]]: ...
    def ao2mo(self, mo_coeff: Optional[Union[NPArrayWithTag, ndarray]]=None) -> _PhysicistsERIs: ...
    contract = contract
    make_diagonal = make_diagonal
    def to_fcivec(self, cisdvec: ndarray, nelec: int, orbspin: ndarray, frozen: None=None) -> ndarray: ...
    def from_fcivec(self, fcivec: Union[ndarray, FCIvector], nelec: int, orbspin: ndarray, frozen: None=None) -> ndarray: ...
    make_rdm1 = make_rdm1
    make_rdm2 = make_rdm2
    trans_rdm1 = trans_rdm1
    def amplitudes_to_cisdvec(self, c0: Union[complex128, float], c1: Union[ndarray, NPArrayWithTag], c2: Union[ndarray, NPArrayWithTag]) -> ndarray: ...
    def cisdvec_to_amplitudes(self, civec: ndarray, nmo: Optional[int]=None, nocc: Optional[int]=None, copy: bool = True) -> Tuple[float64, ndarray, ndarray]: ...
    def from_ucisdvec(self, civec: ndarray, nocc: Optional[Tuple[int, int]]=None, orbspin: Optional[ndarray]=None) -> ndarray: ...
    from_rcisdvec = from_ucisdvec
    def to_ucisdvec(self, civec: ndarray, orbspin: Optional[ndarray]=None) -> ndarray: ...
    def spatial2spin(self, tx: Union[ndarray, List[ndarray], Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]], orbspin: None=None) -> NPArrayWithTag: ...
    def spin2spatial(self, tx: ndarray, orbspin: None=None) -> Union[Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]]: ...
CISD = GCISD
