from _typeshed import Incomplete
from pyscf import lib as lib, scf as scf
from pyscf.cc import uccsd as uccsd, uccsd_rdm as uccsd_rdm
from pyscf.ci import cisd as cisd
from pyscf.fci import cistring as cistring
from pyscf.lib import logger as logger

def make_diagonal(myci, eris): ...
def contract(myci, civec, eris): ...
def amplitudes_to_cisdvec(c0, c1, c2): ...
def cisdvec_to_amplitudes(civec, nmo, nocc, copy: bool = True): ...
def to_fcivec(cisdvec, norb, nelec, frozen=None): ...
def from_fcivec(ci0, norb, nelec, frozen=None): ...
def overlap(cibra, ciket, nmo, nocc, s=None): ...
def make_rdm1(myci, civec=None, nmo=None, nocc=None, ao_repr: bool = False): ...
def make_rdm2(myci, civec=None, nmo=None, nocc=None, ao_repr: bool = False): ...
def trans_rdm1(myci, cibra, ciket, nmo=None, nocc=None): ...

class UCISD(cisd.CISD):
    def vector_size(self): ...
    get_nocc: Incomplete
    get_nmo: Incomplete
    get_frozen_mask: Incomplete
    emp2: Incomplete
    def get_init_guess(self, eris=None, nroots: int = 1, diag=None): ...
    contract = contract
    make_diagonal = make_diagonal
    def ao2mo(self, mo_coeff=None): ...
    def to_fcivec(self, cisdvec, nmo=None, nocc=None): ...
    def from_fcivec(self, fcivec, nmo=None, nocc=None): ...
    def amplitudes_to_cisdvec(self, c0, c1, c2): ...
    def cisdvec_to_amplitudes(self, civec, nmo=None, nocc=None, copy: bool = True): ...
    make_rdm1 = make_rdm1
    make_rdm2 = make_rdm2
    trans_rdm1 = trans_rdm1
    def nuc_grad_method(self): ...
CISD = UCISD
