from _typeshed import Incomplete
from pyscf import lib as lib, scf as scf
from pyscf.cc import uccsd as uccsd, uccsd_rdm as uccsd_rdm
from pyscf.ci import cisd as cisd
from pyscf.fci import cistring as cistring
from pyscf.lib import logger as logger
from h5py._hl.dataset import Dataset
from numpy import complex128, float64, ndarray
from pyscf.cc.uccsd import _ChemistsERIs
from pyscf.fci.direct_spin1 import FCIvector
from pyscf.pbc.ci.cisd import UCISD
from typing import List, Optional, Tuple, Union

def make_diagonal(myci: Union[UCISD, UCISD], eris: _ChemistsERIs) -> ndarray: ...
def contract(myci: Union[UCISD, UCISD], civec: ndarray, eris: _ChemistsERIs) -> ndarray: ...
def amplitudes_to_cisdvec(c0: Union[complex128, float, float64, int], c1: Union[List[ndarray], Tuple[ndarray, ndarray]], c2: Union[Tuple[ndarray, ndarray, ndarray], List[ndarray]]) -> ndarray: ...
def cisdvec_to_amplitudes(civec: ndarray, nmo: Tuple[int, int], nocc: Tuple[int, int], copy: bool = True) -> Union[Tuple[float64, Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]], Tuple[complex128, Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]]]: ...
def to_fcivec(cisdvec: ndarray, norb: int, nelec: Union[int, Tuple[int, int]], frozen: Optional[Union[Tuple[ndarray, ndarray], List[List[int]]]]=None) -> ndarray: ...
def from_fcivec(ci0: Union[ndarray, FCIvector], norb: int, nelec: Union[int, Tuple[int, int]], frozen: None=None) -> ndarray: ...
def overlap(cibra: ndarray, ciket: ndarray, nmo: int, nocc: Tuple[int, int], s: Optional[Tuple[ndarray, ndarray]]=None) -> float64: ...
def make_rdm1(myci: "UCISD", civec: Optional[ndarray]=None, nmo: Optional[Tuple[int, int]]=None, nocc: Optional[Tuple[int, int]]=None, ao_repr: bool = False) -> Tuple[ndarray, ndarray]: ...
def make_rdm2(myci: "UCISD", civec: Optional[ndarray]=None, nmo: Optional[Tuple[int, int]]=None, nocc: Optional[Tuple[int, int]]=None, ao_repr: bool = False) -> Tuple[ndarray, ndarray, ndarray]: ...
def trans_rdm1(myci: "UCISD", cibra: ndarray, ciket: ndarray, nmo: Optional[Tuple[int, int]]=None, nocc: Optional[Tuple[int, int]]=None) -> Tuple[ndarray, ndarray]: ...

class UCISD(cisd.CISD):
    def vector_size(self) -> int: ...
    get_nocc: Incomplete
    get_nmo: Incomplete
    get_frozen_mask: Incomplete
    emp2: Incomplete
    def get_init_guess(self, eris: Optional[_ChemistsERIs]=None, nroots: int = 1, diag: Optional[ndarray]=None) -> Union[Tuple[float64, ndarray], Tuple[float64, List[ndarray]]]: ...
    contract = contract
    make_diagonal = make_diagonal
    def ao2mo(self, mo_coeff: Optional[ndarray]=None) -> _ChemistsERIs: ...
    def to_fcivec(self, cisdvec: ndarray, nmo: Optional[int]=None, nocc: Optional[Tuple[int, int]]=None) -> ndarray: ...
    def from_fcivec(self, fcivec: FCIvector, nmo: Optional[int]=None, nocc: Optional[Tuple[int, int]]=None) -> ndarray: ...
    def amplitudes_to_cisdvec(self, c0: Union[complex128, float], c1: Union[List[ndarray], Tuple[ndarray, ndarray]], c2: Union[Tuple[ndarray, ndarray, ndarray], List[ndarray]]) -> ndarray: ...
    def cisdvec_to_amplitudes(self, civec: ndarray, nmo: Optional[Tuple[int, int]]=None, nocc: Optional[Tuple[int, int]]=None, copy: bool = True) -> Tuple[float64, Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]]: ...
    make_rdm1 = make_rdm1
    make_rdm2 = make_rdm2
    trans_rdm1 = trans_rdm1
    def nuc_grad_method(self): ...
CISD = UCISD
