from _typeshed import Incomplete
from pyscf import gto as gto, lib as lib
from pyscf.ci import cisd as cisd
from pyscf.grad import rhf as rhf_grad
from pyscf.lib import logger as logger

def grad_elec(cigrad, civec=None, eris=None, atmlst=None, verbose=...): ...
def as_scanner(grad_ci, state: int = 0): ...

class CISD_GradScanner(lib.GradScanner):
    state: Incomplete
    def __init__(self, g, state) -> None: ...
    def __call__(self, mol_or_geom, state=None, **kwargs): ...
    @property
    def converged(self): ...

class Gradients(rhf_grad.GradientsBase):
    state: int
    def __init__(self, myci) -> None: ...
    def dump_flags(self, verbose=None): ...
    grad_elec = grad_elec
    atmlst: Incomplete
    de: Incomplete
    def kernel(self, civec=None, eris=None, atmlst=None, state=None, verbose=None): ...
    def grad_nuc(self, mol=None, atmlst=None): ...
    as_scanner = as_scanner
    to_gpu = lib.to_gpu
Grad = Gradients
