from pyscf import ao2mo as ao2mo, lib as lib
from pyscf.lib import logger as logger
from pyscf.mcpdft.cmspdft import coulomb_tensor as coulomb_tensor
from pyscf.mcscf import newton_casscf as newton_casscf

def diab_response(mc_grad, Lis, mo=None, ci=None, eris=None, **kwargs): ...
def diab_response_o0(mc_grad, Lis, mo=None, ci=None, eris=None, **kwargs): ...
def diab_grad(mc_grad, Lis, atmlst=None, mo=None, ci=None, eris=None, mf_grad=None, **kwargs): ...
def diab_grad_o0(mc_grad, Lis, atmlst=None, mo=None, ci=None, eris=None, mf_grad=None, **kwargs): ...
