from _typeshed import Incomplete
from pyscf import lib as lib, scf as scf
from pyscf.grad import rhf as rhf_grad
from pyscf.lib import logger as logger

def grad_elec(mf_grad, mo_energy=None, mo_coeff=None, mo_occ=None, atmlst=None): ...
grad_nuc = rhf_grad.grad_nuc

def get_hcore(mol): ...
def get_ovlp(mol): ...
make_rdm1e = rhf_grad.make_rdm1e

def get_coulomb_hf(mol, dm, level: str = 'SSSS'): ...
get_veff = get_coulomb_hf

class GradientsBase(rhf_grad.GradientsBase):
    def get_hcore(self, mol=None): ...
    def hcore_generator(self, mol): ...
    def get_ovlp(self, mol=None): ...

class Gradients(GradientsBase):
    level: str
    def __init__(self, scf_method) -> None: ...
    def get_veff(self, mol, dm): ...
    def make_rdm1e(self, mo_energy=None, mo_coeff=None, mo_occ=None): ...
    grad_elec = grad_elec
    def extra_force(self, atom_id, envs): ...
    atmlst: Incomplete
    de: Incomplete
    def kernel(self, mo_energy=None, mo_coeff=None, mo_occ=None, atmlst=None): ...
    as_scanner = rhf_grad.as_scanner
    to_gpu = lib.to_gpu
Grad = Gradients
