from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.grad import rhf as rhf_grad
from pyscf.lib import logger as logger
from pyscf.soscf import ciah as ciah
from scipy import optimize as optimize

default_level_shift: Incomplete
default_conv_atol: Incomplete
default_conv_rtol: Incomplete
default_max_cycle: Incomplete

class Gradients(rhf_grad.GradientsBase):
    def get_wfn_response(self, **kwargs): ...
    def get_Aop_Adiag(self, **kwargs): ...
    def get_ham_response(self, **kwargs): ...
    def get_LdotJnuc(self, Lvec, **kwargs): ...
    Lvec: Incomplete
    nlag: Incomplete
    level_shift: Incomplete
    conv_atol: Incomplete
    conv_rtol: Incomplete
    max_cycle: Incomplete
    def __init__(self, method, nlag) -> None: ...
    def debug_lagrange(self, Lvec, bvec, Aop, Adiag, **kwargs) -> None: ...
    def get_lagrange_callback(self, Lvec_last, itvec, geff_op): ...
    def get_lagrange_precond(self, Adiag, level_shift=None, **kwargs): ...
    def get_init_guess(self, bvec, Adiag, Aop, precond): ...
    @property
    def converged(self): ...
    @converged.setter
    def converged(self, x): ...
    def solve_lagrange(self, Lvec_guess=None, level_shift=None, **kwargs): ...
    atmlst: Incomplete
    de: Incomplete
    def kernel(self, level_shift=None, **kwargs): ...

class LagPrec:
    Adiag: Incomplete
    level_shift: Incomplete
    def __init__(self, Adiag=None, level_shift=None, **kwargs) -> None: ...
    def __call__(self, x): ...
