from _typeshed import Incomplete
from pyscf.dft import gen_grid as gen_grid
from pyscf.grad import sacasscf as sacasscf
from pyscf.lib import current_memory as current_memory, logger as logger, pack_tril as pack_tril, tag_array as tag_array
from pyscf.mcpdft import mspdft as mspdft
from pyscf.mcpdft.otpd import get_ontop_pair_density as get_ontop_pair_density
from pyscf.mcpdft.tfnal_derivs import contract_fot as contract_fot, contract_vot as contract_vot, unpack_vot as unpack_vot
from pyscf.mcscf import casci as casci, mc1step as mc1step, newton_casscf as newton_casscf
from pyscf.mcscf.casci import cas_natorb as cas_natorb

BLKSIZE: Incomplete

def get_ontop_response(mc, ot, state, atmlst, casdm1, casdm1_0, mo_coeff=None, ci=None, max_memory=None): ...
def lpdft_HellmanFeynman_grad(mc, ot, state, feff1, feff2, mo_coeff=None, ci=None, atmlst=None, mf_grad=None, verbose=None, max_memory=None, auxbasis_response: bool = False): ...

class Gradients(sacasscf.Gradients):
    state: Incomplete
    def kernel(self, **kwargs): ...
    def get_wfn_response(self, state=None, verbose=None, mo=None, ci=None, feff1=None, feff2=None, **kwargs): ...
    def get_ham_response(self, state=None, atmlst=None, verbose=None, mo=None, ci=None, mf_grad=None, feff1=None, feff2=None, **kwargs): ...
    def get_otp_gradient_response(self, mo=None, ci=None, state: int = 0): ...
    def get_Aop_Adiag(self, verbose=None, mo=None, ci=None, eris=None, state=None, **kwargs): ...
