from _typeshed import Incomplete
from pyscf.dft import gen_grid as gen_grid
from pyscf.grad import sacasscf as sacasscf
from pyscf.lib import current_memory as current_memory, einsum as einsum, logger as logger, pack_tril as pack_tril, tag_array as tag_array
from pyscf.mcpdft.otpd import get_ontop_pair_density as get_ontop_pair_density
from pyscf.mcscf import casci as casci, mc1step as mc1step, newton_casscf as newton_casscf
from pyscf.mcscf.casci import cas_natorb as cas_natorb

BLKSIZE: Incomplete

def gfock_sym(mc, mo_coeff, casdm1, casdm2, h1e, eris): ...
def xc_response(ot, vot, rho, Pi, weights, moval_occ, aoval, mo_occ, mo_occup, ncore, nocc, casdm2_pack, ndpi, mo_cas): ...
def pack_casdm2(cascm2, ncas): ...
def sum_terms(mf_grad, mol, atmlst, dm1, gfock, coul_term, dvxc): ...
def mcpdft_HellmanFeynman_grad(mc, ot, veff1, veff2, mo_coeff=None, ci=None, atmlst=None, mf_grad=None, verbose=None, max_memory=None, auxbasis_response: bool = False): ...

class Gradients(sacasscf.Gradients):
    state: int
    e_mcscf: Incomplete
    def __init__(self, pdft, state=None) -> None: ...
    def get_wfn_response(self, state=None, verbose=None, mo=None, ci=None, veff1=None, veff2=None, nlag=None, **kwargs): ...
    def get_ham_response(self, state=None, atmlst=None, verbose=None, mo=None, ci=None, eris=None, mf_grad=None, veff1=None, veff2=None, **kwargs): ...
    def get_init_guess(self, bvec, Adiag, Aop, precond): ...
    def kernel(self, **kwargs): ...
    def project_Aop(self, Aop, ci, state): ...
