from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib, mcpdft as mcpdft
from pyscf.csf_fci.csf import CSFFCISolver as CSFFCISolver
from pyscf.fci import direct_spin1 as direct_spin1
from pyscf.grad import mcpdft as mcpdft_grad, sacasscf as sacasscf_grad
from pyscf.lib import logger as logger
from pyscf.mcscf import mc1step as mc1step, newton_casscf as newton_casscf

class CSFFCISolver: ...

CONV_TOL_DIABATIZE: Incomplete
SING_TOL_DIABATIZE: Incomplete
SING_STEP_TOL: Incomplete

def make_rdm12_heff_offdiag(mc, ci, si_bra, si_ket): ...
def mspdft_heff_response(mc_grad, mo=None, ci=None, si_bra=None, si_ket=None, state=None, heff_mcscf=None, eris=None): ...
def mspdft_heff_HellmanFeynman(mc_grad, atmlst=None, mo=None, ci=None, si=None, si_bra=None, si_ket=None, state=None, eris=None, mf_grad=None, verbose=None, **kwargs): ...
def get_diabfns(obj): ...

class Gradients(mcpdft_grad.Gradients):
    get_init_guess: Incomplete
    project_Aop: Incomplete
    conv_rtol: int
    conv_atol: Incomplete
    sing_step_tol: Incomplete
    def __init__(self, mc) -> None: ...
    @property
    def nis(self): ...
    def diab_response(self, Lis, **kwargs): ...
    def diab_grad(self, Lis, **kwargs): ...
    state: Incomplete
    def kernel(self, state=None, mo=None, ci=None, si=None, _freeze_is: bool = False, **kwargs): ...
    def pack_uniq_var(self, xorb, xci, xis=None): ...
    def unpack_uniq_var(self, x): ...
    def get_wfn_response(self, si_bra=None, si_ket=None, state=None, mo=None, ci=None, si=None, eris=None, veff1=None, veff2=None, _freeze_is: bool = False, d2f=None, **kwargs): ...
    def get_Aop_Adiag(self, verbose=None, mo=None, ci=None, eris=None, level_shift=None, d2f=None, **kwargs): ...
    def get_lagrange_precond(self, Adiag, level_shift=None, ci=None, d2f=None, **kwargs): ...
    def get_ham_response(self, si_bra=None, si_ket=None, state=None, mo=None, ci=None, si=None, eris=None, veff1=None, veff2=None, mf_grad=None, atmlst=None, verbose=None, **kwargs): ...
    def get_LdotJnuc(self, Lvec, atmlst=None, verbose=None, mo=None, ci=None, eris=None, mf_grad=None, d2f=None, **kwargs): ...
    def get_lagrange_callback(self, Lvec_last, itvec, geff_op): ...
    def debug_lagrange(self, Lvec, bvec, Aop, Adiag, state=None, mo=None, ci=None, d2f=None, verbose=None, eris=None, **kwargs) -> None: ...

class MSPDFTLagPrec(sacasscf_grad.SACASLagPrec):
    grad_method: Incomplete
    sing_tol: Incomplete
    sing_step_tol: Incomplete
    sing_warned: bool
    log: Incomplete
    verbose: Incomplete
    def __init__(self, Adiag=None, level_shift=None, ci=None, grad_method=None, d2f=None, **kwargs) -> None: ...
    def unpack_uniq_var(self, x): ...
    def pack_uniq_var(self, x0, x1, x2=None): ...
    def __call__(self, x): ...
    def is_prec(self, xis): ...
    def do_sing_warn(self) -> None: ...
