from _typeshed import Incomplete
from pyscf import gto as gto, lib as lib, scf as scf
from pyscf.gto.mole import is_au as is_au
from pyscf.lib import logger as logger
from pyscf.scf import hf as hf

def grad_elec(mf_grad, mo_energy=None, mo_coeff=None, mo_occ=None, atmlst=None): ...
def grad_nuc(mol, atmlst=None): ...
def get_hcore(mol): ...
def hcore_generator(mf, mol=None): ...
def get_ovlp(mol): ...
def get_jk(mol, dm): ...
def get_j(mol, dm): ...
def get_k(mol, dm): ...
def get_veff(mf_grad, mol, dm): ...
def make_rdm1e(mo_energy, mo_coeff, mo_occ): ...
def symmetrize(mol, de, atmlst=None): ...
def as_scanner(mf_grad): ...

class SCF_GradScanner(lib.GradScanner):
    def __init__(self, g) -> None: ...
    def __call__(self, mol_or_geom, **kwargs): ...

class GradientsBase(lib.StreamObject):
    verbose: Incomplete
    stdout: Incomplete
    mol: Incomplete
    base: Incomplete
    max_memory: Incomplete
    unit: str
    atmlst: Incomplete
    de: Incomplete
    def __init__(self, method) -> None: ...
    def dump_flags(self, verbose=None): ...
    def reset(self, mol=None): ...
    def get_hcore(self, mol=None): ...
    hcore_generator = hcore_generator
    def get_ovlp(self, mol=None): ...
    def get_jk(self, mol=None, dm=None, hermi: int = 0, omega=None): ...
    def get_j(self, mol=None, dm=None, hermi: int = 0, omega=None): ...
    def get_k(self, mol=None, dm=None, hermi: int = 0, omega=None): ...
    def get_veff(self, mol=None, dm=None) -> None: ...
    def make_rdm1e(self, mo_energy=None, mo_coeff=None, mo_occ=None) -> None: ...
    def grad_nuc(self, mol=None, atmlst=None): ...
    def optimizer(self, solver: str = 'geometric'): ...
    def symmetrize(self, de, atmlst=None): ...
    def grad_elec(self) -> None: ...
    def extra_force(self, atom_id, envs): ...
    def kernel(self, mo_energy=None, mo_coeff=None, mo_occ=None, atmlst=None): ...
    grad: Incomplete
    as_scanner = as_scanner
    to_gpu = lib.to_gpu
GradientsMixin = GradientsBase

class Gradients(GradientsBase):
    def get_veff(self, mol=None, dm=None): ...
    def make_rdm1e(self, mo_energy=None, mo_coeff=None, mo_occ=None): ...
    grad_elec = grad_elec
Grad = Gradients
