from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, dft as dft, gto as gto, lib as lib
from pyscf.dft import gen_grid as gen_grid, numint as numint, radi as radi, xc_deriv as xc_deriv
from pyscf.dft.numint import libdft as libdft
from pyscf.grad import rhf as rhf_grad
from pyscf.lib import logger as logger

def get_veff(ks_grad, mol=None, dm=None): ...
def get_vxc(ni, mol, grids, xc_code, dms, relativity: int = 0, hermi: int = 1, max_memory: int = 2000, verbose=None): ...
def get_nlc_vxc(ni, mol, grids, xc_code, dm, relativity: int = 0, hermi: int = 1, max_memory: int = 2000, verbose=None): ...
def get_vxc_full_response(ni, mol, grids, xc_code, dms, relativity: int = 0, hermi: int = 1, max_memory: int = 2000, verbose=None): ...
def get_nlc_vxc_full_response(ni, mol, grids, xc_code, dms, relativity: int = 0, hermi: int = 1, max_memory: int = 2000, verbose=None): ...
def grids_response_becke(grids) -> Generator[Incomplete, None, Incomplete]: ...
def get_dw_partition(mol, ia, atom_grids_tab, radii_adjust=None, atomic_radii=..., concat: bool = True, wtonly: bool = False): ...
def get_dw_partition_sorted(mol, ialist, coords, weights, radii_adjust=None, atomic_radii=...): ...
def grids_response_lko(grids) -> Generator[Incomplete]: ...
def grids_noresponse_cc(grids) -> Generator[Incomplete]: ...
def grids_response_cc(grids) -> Generator[Incomplete]: ...

class Gradients(rhf_grad.Gradients):
    grid_response: Incomplete
    grids: Incomplete
    nlcgrids: Incomplete
    def __init__(self, mf) -> None: ...
    def dump_flags(self, verbose=None): ...
    get_veff = get_veff
    def extra_force(self, atom_id, envs): ...
Grad = Gradients
