from _typeshed import Incomplete
from pyscf import ao2mo as ao2mo, gto as gto, lib as lib, mcscf as mcscf
from pyscf.fci import cistring as cistring
from pyscf.fci.addons import SpinPenaltyFCISolver as SpinPenaltyFCISolver, fix_spin_ as fix_spin_
from pyscf.fci.spin_op import spin_square as spin_square
from pyscf.grad import lagrange as lagrange
from pyscf.lib import logger as logger
from pyscf.mcscf import mc1step as mc1step, mc1step_symm as mc1step_symm, newton_casscf as newton_casscf
from pyscf.mcscf.addons import StateAverageFCISolver as StateAverageFCISolver, StateAverageMCSCFSolver as StateAverageMCSCFSolver, StateAverageMixFCISolver as StateAverageMixFCISolver, state_average_mix_ as state_average_mix_

def Lorb_dot_dgorb_dx(Lorb, mc, mo_coeff=None, ci=None, atmlst=None, mf_grad=None, eris=None, verbose=None): ...
def Lci_dot_dgci_dx(Lci, weights, mc, mo_coeff=None, ci=None, atmlst=None, mf_grad=None, eris=None, verbose=None): ...
def as_scanner(mcscf_grad, state=None): ...

class CASSCF_GradScanner(lib.GradScanner):
    state: Incomplete
    def __init__(self, g, state) -> None: ...
    e_mcscf: Incomplete
    def __call__(self, mol_or_geom, **kwargs): ...
    @property
    def converged(self): ...
    @converged.setter
    def converged(self, x) -> None: ...

class Gradients(lagrange.Gradients):
    ngorb: Incomplete
    nroots: Incomplete
    spin_states: Incomplete
    na_states: Incomplete
    nb_states: Incomplete
    nci: Incomplete
    state: Incomplete
    eris: Incomplete
    weights: Incomplete
    e_states: Incomplete
    max_cycle: Incomplete
    def __init__(self, mc, state=None) -> None: ...
    def pack_uniq_var(self, xorb, xci): ...
    def unpack_uniq_var(self, x): ...
    def make_fcasscf(self, state=None, casscf_attr={}, fcisolver_attr={}): ...
    def make_fcasscf_sa(self, casscf_attr={}, fcisolver_attr={}): ...
    def kernel(self, state=None, atmlst=None, verbose=None, mo=None, ci=None, eris=None, mf_grad=None, e_states=None, level_shift=None, **kwargs): ...
    def get_wfn_response(self, atmlst=None, state=None, verbose=None, mo=None, ci=None, **kwargs): ...
    def get_Aop_Adiag(self, atmlst=None, state=None, verbose=None, mo=None, ci=None, eris=None, level_shift=None, **kwargs): ...
    def get_ham_response(self, state=None, atmlst=None, verbose=None, mo=None, ci=None, eris=None, mf_grad=None, **kwargs): ...
    def get_LdotJnuc(self, Lvec, state=None, atmlst=None, verbose=None, mo=None, ci=None, eris=None, mf_grad=None, **kwargs): ...
    def debug_lagrange(self, Lvec, bvec, Aop, Adiag, state=None, mo=None, ci=None, **kwargs) -> None: ...
    def get_lagrange_precond(self, Adiag, level_shift=None, ci=None, **kwargs): ...
    def get_lagrange_callback(self, Lvec_last, itvec, geff_op): ...
    def project_Aop(self, Aop, ci, state): ...
    as_scanner = as_scanner

class SACASLagPrec(lagrange.LagPrec):
    level_shift: Incomplete
    nroots: Incomplete
    nlag: Incomplete
    ngorb: Incomplete
    spin_states: Incomplete
    na_states: Incomplete
    nb_states: Incomplete
    grad_method: Incomplete
    def __init__(self, Adiag=None, level_shift=None, ci=None, grad_method=None) -> None: ...
    def unpack_uniq_var(self, x): ...
    def pack_uniq_var(self, xorb, xci): ...
    def __call__(self, x): ...
    def orb_prec(self, xorb): ...
    def ci_prec(self, xci_spins): ...
