from pyscf import lib as lib, scf as scf
from pyscf.grad import rhf as rhf_grad
from pyscf.lib import logger as logger

def grad_elec(mf_grad, mo_energy=None, mo_coeff=None, mo_occ=None, atmlst=None): ...
def get_veff(mf_grad, mol, dm): ...
def make_rdm1e(mo_energy, mo_coeff, mo_occ): ...

class Gradients(rhf_grad.GradientsBase):
    def get_veff(self, mol=None, dm=None): ...
    def make_rdm1e(self, mo_energy=None, mo_coeff=None, mo_occ=None): ...
    grad_elec = grad_elec
Grad = Gradients
