from pyscf import lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc import tools as tools
from pyscf.pbc.lib.kpts import KPoints as KPoints
from pyscf.pbc.lib.kpts_helper import group_by_conj_pairs as group_by_conj_pairs

def kpts_to_kmesh(cell, kpts, precision=None, rcut=None, bound_by_supmol: bool = True): ...
def translation_vectors_for_kmesh(cell, kmesh, wrap_around: bool = False): ...
def get_phase(cell, kpts, kmesh=None, wrap_around: bool = False): ...
def double_translation_indices(kmesh): ...
def translation_map(nk): ...
def mo_k2gamma(cell, mo_energy, mo_coeff, kpts, kmesh=None): ...
def k2gamma(kmf, kmesh=None): ...
def to_supercell_ao_integrals(cell, kpts, ao_ints, kmesh=None, force_real: bool = True): ...
def to_supercell_mo_integrals(kmf, mo_ints): ...
