from pyscf import lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc import tools as tools
from pyscf.pbc.lib.kpts import KPoints as KPoints
from pyscf.pbc.lib.kpts_helper import group_by_conj_pairs as group_by_conj_pairs
from numpy import int64, ndarray
from pyscf.pbc.df.ft_ao import _RangeSeparatedCell
from pyscf.pbc.dft.krks_ksymm import KsymAdaptedKRKS
from pyscf.pbc.dft.kuks import KUKS
from pyscf.pbc.dft.rks import RKS
from pyscf.pbc.dft.uks import UKS
from pyscf.pbc.gto.cell import Cell
from typing import List, Optional, Tuple, Union

def kpts_to_kmesh(cell: Cell, kpts: Union[ndarray, List[ndarray]], precision: None=None, rcut: None=None, bound_by_supmol: bool = True) -> ndarray: ...
def translation_vectors_for_kmesh(cell: Union[Cell, _RangeSeparatedCell], kmesh: Union[ndarray, List[int]], wrap_around: bool = False) -> ndarray: ...
def get_phase(cell: Cell, kpts: ndarray, kmesh: Optional[ndarray]=None, wrap_around: bool = False) -> Tuple[Cell, ndarray]: ...
def double_translation_indices(kmesh: Union[ndarray, List[int]]) -> ndarray: ...
def translation_map(nk: Union[int64, int]) -> ndarray: ...
def mo_k2gamma(cell: Cell, mo_energy: Union[ndarray, List[ndarray]], mo_coeff: Union[ndarray, List[ndarray]], kpts: ndarray, kmesh: None=None) -> Tuple[Cell, ndarray, ndarray, ndarray]: ...
def k2gamma(kmf: Union[KsymAdaptedKRKS, KUKS], kmesh: None=None) -> Union[UKS, RKS]: ...
def to_supercell_ao_integrals(cell: Cell, kpts: ndarray, ao_ints: ndarray, kmesh: Optional[ndarray]=None, force_real: bool = True) -> ndarray: ...
def to_supercell_mo_integrals(kmf, mo_ints): ...
