A2B: float

def get_ase_atom(formula): ...
def get_ase_wurtzite(A: str = 'Zn', B: str = 'O'): ...
def get_bandpath_fcc(ase_atom, npoints: int = 30): ...
def get_ase_zincblende(A: str = 'Ga', B: str = 'As'): ...
def get_ase_rocksalt(A: str = 'Li', B: str = 'Cl'): ...
def get_ase_alkali_halide(A: str = 'Li', B: str = 'Cl'): ...
def get_ase_diamond_primitive(atom: str = 'C'): ...
def get_ase_diamond_cubic(atom: str = 'C'): ...
def get_ase_graphene(vacuum: float = 5.0): ...
def get_ase_graphene_xxx(vacuum: float = 5.0): ...
