from pyscf import gto as gto, scf as scf
from pyscf.pbc.ao2mo import eris as eris
from pyscf.pbc.gto.cell import Cell
from typing import List

def make_cell(L, mesh): ...
def test_cell_n0(L: float = 5, mesh: List[int]=...) -> Cell: ...
def test_cell_n1(L: float = 5, mesh: List[int]=...) -> Cell: ...
def test_cell_n2(L: int = 5, mesh=...): ...
def test_cell_n3(mesh: List[int]=...) -> Cell: ...
def test_cell_n3_diffuse(precision: float = 1e-08) -> Cell: ...
def test_cell_cu_metallic(mesh: List[int]=..., precision: float = 1e-08) -> Cell: ...
