from pyscf import gto as gto, scf as scf
from pyscf.pbc.ao2mo import eris as eris

def make_cell(L, mesh): ...
def test_cell_n0(L: int = 5, mesh=...): ...
def test_cell_n1(L: int = 5, mesh=...): ...
def test_cell_n2(L: int = 5, mesh=...): ...
def test_cell_n3(mesh=...): ...
def test_cell_n3_diffuse(precision: float = 1e-08): ...
def test_cell_cu_metallic(mesh=..., precision: float = 1e-08): ...
