from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.gto import ATM_SLOTS as ATM_SLOTS, ATOM_OF as ATOM_OF, BAS_SLOTS as BAS_SLOTS, PTR_COORD as PTR_COORD
from pyscf.lib import logger as logger
from pyscf.pbc.lib.kpts_helper import get_kconserv as get_kconserv, get_kconserv3 as get_kconserv3, intersection as intersection
from numpy import float64, int64, ndarray
from pyscf.pbc.df.ft_ao import ExtendedMole, _RangeSeparatedCell
from pyscf.pbc.df.rsdf_builder import _ExtendedMoleFT
from pyscf.pbc.gto.cell import Cell
from typing import Any, Dict, List, Optional, Tuple, Union

FFT_ENGINE: Incomplete
nproc: Incomplete
libfft: Incomplete

def fft(f: ndarray, mesh: Union[ndarray, Tuple[int64, int64, int64], Tuple[int, int, int], List[int]]) -> ndarray: ...
def ifft(g: ndarray, mesh: Union[ndarray, List[int]]) -> ndarray: ...
def fftk(f: ndarray, mesh: Union[Tuple[int, int, int], List[int]], expmikr: ndarray) -> ndarray: ...
def ifftk(g: ndarray, mesh: List[int], expikr: ndarray) -> ndarray: ...
def get_coulG(cell: Cell, k: ndarray=..., exx: Optional[Union[bool, str]] = False, mf: Optional[Any]=None, mesh: Optional[Union[ndarray, List[int]]]=None, Gv: Optional[ndarray]=None, wrap_around: bool = True, omega: Optional[Union[float, float64]]=None, **kwargs) -> ndarray: ...
def precompute_exx(cell: Cell, kpts: Optional[ndarray]=None) -> Dict[str, Union[float64, Cell, ndarray]]: ...
def madelung(cell: Cell, kpts: Optional[Union[ndarray, List[ndarray], List[int]]]=None, omega: None=None) -> Union[int, float64]: ...
def get_monkhorst_pack_size(cell: Cell, kpts: Union[ndarray, List[ndarray], List[int]], tol: float = 1e-05) -> ndarray: ...
def get_lattice_Ls(cell: Union[_RangeSeparatedCell, Cell], nimgs: None=None, rcut: Optional[Union[float, int, float64]]=None, dimension: None=None, discard: bool = True) -> ndarray: ...
def check_lattice_sum_range(cell: Cell, Ls: ndarray) -> float64: ...
def super_cell(cell: Union[_RangeSeparatedCell, Cell], ncopy: Union[ndarray, Tuple[int, int, int], List[int]], wrap_around: bool = False) -> Union[_RangeSeparatedCell, Cell]: ...
def cell_plus_imgs(cell: Cell, nimgs: Union[ndarray, List[Union[int64, int]], List[int]]) -> Cell: ...
def cutoff_to_mesh(a: ndarray, cutoff: Union[float, int, float64]) -> ndarray: ...
def mesh_to_cutoff(a: ndarray, mesh: Union[ndarray, Tuple[int, int, int], List[int]]) -> ndarray: ...
def cutoff_to_gs(a, cutoff): ...
def gs_to_cutoff(a, gs): ...
def round_to_cell0(r: ndarray, tol: float = 1e-06) -> ndarray: ...
