from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.gto import ATM_SLOTS as ATM_SLOTS, ATOM_OF as ATOM_OF, BAS_SLOTS as BAS_SLOTS, PTR_COORD as PTR_COORD
from pyscf.lib import logger as logger
from pyscf.pbc.lib.kpts_helper import get_kconserv as get_kconserv, get_kconserv3 as get_kconserv3, intersection as intersection

FFT_ENGINE: Incomplete
nproc: Incomplete
libfft: Incomplete

def fft(f, mesh): ...
def ifft(g, mesh): ...
def fftk(f, mesh, expmikr): ...
def ifftk(g, mesh, expikr): ...
def get_coulG(cell, k=..., exx: bool = False, mf=None, mesh=None, Gv=None, wrap_around: bool = True, omega=None, **kwargs): ...
def precompute_exx(cell, kpts=None): ...
def madelung(cell, kpts=None, omega=None): ...
def get_monkhorst_pack_size(cell, kpts, tol: float = 1e-05): ...
def get_lattice_Ls(cell, nimgs=None, rcut=None, dimension=None, discard: bool = True): ...
def check_lattice_sum_range(cell, Ls): ...
def super_cell(cell, ncopy, wrap_around: bool = False): ...
def cell_plus_imgs(cell, nimgs): ...
def cutoff_to_mesh(a, cutoff): ...
def mesh_to_cutoff(a, mesh): ...
def cutoff_to_gs(a, cutoff): ...
def gs_to_cutoff(a, gs): ...
def round_to_cell0(r, tol: float = 1e-06): ...
