from _typeshed import Incomplete
from ase.calculators.calculator import Calculator
from pyscf import lib as lib
from pyscf.data.nist import BOHR as BOHR, HARTREE2EV as HARTREE2EV
from pyscf.gto.mole import charge as charge
from pyscf.pbc.gto.cell import Cell as Cell

def pyscf_to_ase_atoms(pyscf_obj): ...
def ase_atoms_to_pyscf(ase_atoms): ...
atoms_from_ase = ase_atoms_to_pyscf

def cell_from_ase(ase_atoms): ...
def bandpath(cell, npoints=None): ...
def plot_band_structure(bandpath, e_kn, ax=None, color: str = 'k'): ...

class PySCF(Calculator):
    implemented_properties: Incomplete
    default_parameters: Incomplete
    method: Incomplete
    pbc: Incomplete
    mol: Incomplete
    method_scan: Incomplete
    def __init__(self, restart=None, label: str = 'PySCF', atoms=None, directory: str = '.', method=None, **kwargs) -> None: ...
    def set(self, **kwargs) -> None: ...
    def calculate(self, atoms=None, properties=['energy'], system_changes=...) -> None: ...
    def get_fermi_level(self): ...
    def get_eigenvalues(self, kpt: int = 0, spin: int = 0): ...
    def get_occupation_numbers(self, kpt: int = 0, spin: int = 0): ...
    def get_number_of_spins(self): ...
    def band_structure(self): ...
