from _typeshed import Incomplete
from pyscf import lib as lib
from pyscf.pbc import df as df
from pyscf.pbc.dft import gen_grid as gen_grid, numint as numint

def save_kmf(kmf, chkfile) -> None: ...
def load_kmf(chkfile): ...
def angle(v1, v2): ...
def transform(x_vec, z_vec): ...
def cartesian_prod(arrays, out=None, order: str = 'C'): ...
def periodic_grid(cell, grid=[50, 50, 50], supercell=[1, 1, 1], order: str = 'C'): ...
def R_r(r_norm, r: int = 1, zona: int = 1): ...
def theta(func, cost, phi): ...
def theta_lmr(l, mr, cost, phi): ...
def g_r(grids_coor, site, l, mr, r, zona, x_axis=[1, 0, 0], z_axis=[0, 0, 1], unit: str = 'B'): ...
def get_wigner_seitz_supercell(w90, ws_search_size=[2, 2, 2], ws_distance_tol: float = 1e-06): ...
def R_wz_sc(w90, R_in, R0, ws_search_size=[2, 2, 2], ws_distance_tol: float = 1e-06): ...
def ws_translate_dist(w90, irvec, ws_search_size=[2, 2, 2], ws_distance_tol: float = 1e-06): ...

class W90:
    kmf: Incomplete
    cell: Incomplete
    num_wann: Incomplete
    keywords: Incomplete
    num_bands_tot: Incomplete
    num_kpts_loc: Incomplete
    mp_grid_loc: Incomplete
    real_lattice_loc: Incomplete
    recip_lattice_loc: Incomplete
    kpt_latt_loc: Incomplete
    num_atoms_loc: Incomplete
    atom_symbols_loc: Incomplete
    atom_atomic_loc: Incomplete
    atoms_cart_loc: Incomplete
    gamma_only: int
    spinors: int
    num_bands_loc: Incomplete
    num_wann_loc: Incomplete
    nntot_loc: Incomplete
    nn_list: Incomplete
    proj_site: Incomplete
    proj_l: Incomplete
    proj_m: Incomplete
    proj_radial: Incomplete
    proj_z: Incomplete
    proj_x: Incomplete
    proj_zona: Incomplete
    exclude_bands: Incomplete
    proj_s: Incomplete
    proj_s_qaxis: Incomplete
    band_included_list: Incomplete
    A_matrix_loc: Incomplete
    M_matrix_loc: Incomplete
    eigenvalues_loc: Incomplete
    U_matrix: Incomplete
    U_matrix_opt: Incomplete
    lwindow: Incomplete
    wann_centres: Incomplete
    wann_spreads: Incomplete
    spread: Incomplete
    use_bloch_phases: bool
    spin_up: Incomplete
    mo_energy_kpts: Incomplete
    mo_coeff_kpts: Incomplete
    def __init__(self, kmf, cell, mp_grid, num_wann, gamma: bool = False, spinors: bool = False, spin_up=None, other_keywords=None) -> None: ...
    def kernel(self, external_AME=None) -> None: ...
    def make_win(self) -> None: ...
    def get_M_mat(self): ...
    def read_M_mat(self, filename=None): ...
    def get_A_mat(self): ...
    def read_A_mat(self, filename=None): ...
    def get_epsilon_mat(self): ...
    def read_epsilon_mat(self, filename=None): ...
    def setup(self) -> None: ...
    def run(self) -> None: ...
    get_wigner_seitz_supercell = get_wigner_seitz_supercell
    R_wz_sc = R_wz_sc
    ws_translate_dist = ws_translate_dist
    def get_hamiltonian_kpts(self): ...
    def get_hamiltonian_Rs(self, Rs, ham_kpts=None): ...
    def interpolate_ham_kpts(self, frac_kpts, ham_kpts=None, use_ws_distance: bool = True, ws_search_size=[2, 2, 2], ws_distance_tol: float = 1e-06): ...
    def interpolate_band(self, frac_kpts, ham_kpts=None, use_ws_distance: bool = True, ws_search_size=[2, 2, 2], ws_distance_tol: float = 1e-06): ...
    def is_real(self, threshold: float = 1e-06): ...
    def export_unk(self, grid=[50, 50, 50]) -> None: ...
    def export_AME(self, grid=[50, 50, 50]) -> None: ...
    def get_wannier(self, supercell=[1, 1, 1], grid=[50, 50, 50]): ...
    def get_guess_orb(self, frac_site=[0, 0, 0], l: int = 0, mr: int = 1, r: int = 1, zona: float = 1.0, x_axis=[1, 0, 0], z_axis=[0, 0, 1], supercell=[1, 1, 1], grid=[50, 50, 50]): ...
    def plot_wf(self, outfile: str = 'MLWF', wf_list=None, supercell=[1, 1, 1], grid=[50, 50, 50]) -> None: ...
    def plot_guess_orbs(self, outfile: str = 'guess_orb', frac_site=[0, 0, 0], l: int = 0, mr: int = 1, r: int = 1, zona: float = 1.0, x_axis=[1, 0, 0], z_axis=[0, 0, 1], supercell=[1, 1, 1], grid=[50, 50, 50]) -> None: ...
