from pyscf.scf.addons import *
from pyscf import gto as gto
from pyscf.scf import addons as addons, chkfile as chkfile, dhf as dhf, diis as diis, dispersion as dispersion, ghf as ghf, ghf_symm as ghf_symm, hf as hf, hf_symm as hf_symm, rohf as rohf, uhf as uhf, uhf_symm as uhf_symm
from pyscf.scf.diis import ADIIS as ADIIS, CDIIS as CDIIS, DIIS as DIIS, EDIIS as EDIIS
from pyscf.scf.hf import get_init_guess as get_init_guess
from pyscf.scf.uhf import spin_square as spin_square

rhf = hf
rhf_symm = hf_symm

def HF(mol, *args): ...
def RHF(mol, *args): ...
def ROHF(mol, *args): ...
def UHF(mol, *args): ...
def GHF(mol, *args): ...
def DHF(mol, *args): ...
def X2C(mol, *args): ...
X2C_HF = X2C

def sfx2c1e(mf): ...
sfx2c = sfx2c1e

def density_fit(mf, auxbasis=None, with_df=None, only_dfj: bool = False): ...
def newton(mf): ...
fast_newton = addons.fast_newton

def KS(mol, *args, **kwargs): ...
def RKS(mol, *args, **kwargs): ...
def ROKS(mol, *args, **kwargs): ...
def UKS(mol, *args, **kwargs): ...
def GKS(mol, *args, **kwargs): ...
def DKS(mol, *args, **kwargs): ...
