import ctypes
from _typeshed import Incomplete
from pyscf import gto as gto, lib as lib
from pyscf.gto.moleintor import ascint3 as ascint3, make_cintopt as make_cintopt, make_loc as make_loc

libcvhf: Incomplete

class VHFOpt:
    def __init__(self, mol, intor=None, prescreen: str = 'CVHFnoscreen', qcondname=None, dmcondname=None) -> None: ...
    def init_cvhf_direct(self, mol, intor, qcondname) -> None: ...
    @property
    def direct_scf_tol(self): ...
    @direct_scf_tol.setter
    def direct_scf_tol(self, v) -> None: ...
    @property
    def prescreen(self): ...
    @prescreen.setter
    def prescreen(self, v) -> None: ...
    def set_dm(self, dm, atm, bas, env) -> None: ...
    def __del__(self) -> None: ...
    def get_q_cond(self, shape=None): ...
    q_cond: Incomplete
    def get_dm_cond(self, shape=None): ...
    dm_cond: Incomplete

class _VHFOpt:
    mol: Incomplete
    def __init__(self, mol, intor=None, prescreen: str = 'CVHFnoscreen', qcondname=None, dmcondname=None, direct_scf_tol: float = 1e-14) -> None: ...
    def init_cvhf_direct(self, mol, intor, qcondname) -> None: ...
    @property
    def direct_scf_tol(self): ...
    @direct_scf_tol.setter
    def direct_scf_tol(self, v) -> None: ...
    @property
    def prescreen(self): ...
    @prescreen.setter
    def prescreen(self, v) -> None: ...
    def set_dm(self, dm, atm, bas, env) -> None: ...
    def get_q_cond(self): ...
    q_cond: Incomplete
    @q_cond.setter
    def q_cond(self, q_cond) -> None: ...
    def get_dm_cond(self): ...
    dm_cond: Incomplete
    @dm_cond.setter
    def dm_cond(self, dm_cond) -> None: ...

class _CVHFOpt(ctypes.Structure): ...

def incore(eri, dms, hermi: int = 0, with_j: bool = True, with_k: bool = True): ...
def direct(dms, atm, bas, env, vhfopt=None, hermi: int = 0, cart: bool = False, with_j: bool = True, with_k: bool = True, out=None, optimize_sr: bool = False): ...
def direct_mapdm(intor, aosym, jkdescript, dms, ncomp, atm, bas, env, vhfopt=None, cintopt=None, shls_slice=None, shls_excludes=None, out=None, optimize_sr: bool = False): ...
def direct_bindm(intor, aosym, jkdescript, dms, ncomp, atm, bas, env, vhfopt=None, cintopt=None, shls_slice=None, shls_excludes=None, out=None, optimize_sr: bool = False): ...
def nr_direct_drv(intor, aosym, jkscript, dms, ncomp, atm, bas, env, cvhfopt=None, cintopt=None, shls_slice=None, shls_excludes=None, out=None, optimize_sr: bool = True): ...
def int2e_sph(atm, bas, env, cart: bool = False): ...
def rdirect_mapdm(intor, aosym, jkdescript, dms, ncomp, atm, bas, env, vhfopt=None, cintopt=None, shls_slice=None): ...
def rdirect_bindm(intor, aosym, jkdescript, dms, ncomp, atm, bas, env, vhfopt=None, cintopt=None, shls_slice=None): ...
def get_dims(descr_sym, shls_slice, ao_loc): ...
