from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.gto import mole as mole
from pyscf.lib import logger as logger
from pyscf.lib.scipy_helper import pivoted_cholesky as pivoted_cholesky
from pyscf.scf.smearing import SMEARING_METHOD as SMEARING_METHOD, smearing as smearing, smearing_ as smearing_

LINEAR_DEP_THRESHOLD: Incomplete
CHOLESKY_THRESHOLD: Incomplete
FORCE_PIVOTED_CHOLESKY: Incomplete
LINEAR_DEP_TRIGGER: Incomplete

def frac_occ_(mf, tol: float = 0.001): ...
frac_occ = frac_occ_

def dynamic_occ_(mf, tol: float = 0.001): ...
dynamic_occ = dynamic_occ_

def dynamic_level_shift_(mf, factor: float = 1.0): ...
dynamic_level_shift = dynamic_level_shift_

def float_occ_(mf): ...
dynamic_sz_ = float_occ_
float_occ = float_occ_

def follow_state_(mf, occorb=None): ...
follow_state = follow_state_

def mom_occ_(mf, occorb, setocc): ...
mom_occ = mom_occ_

def project_mo_nr2nr(mol1, mo1, mol2): ...
def project_mo_nr2r(mol1, mo1, mol2): ...
def project_mo_r2r(mol1, mo1, mol2): ...
def project_dm_nr2nr(mol1, dm1, mol2): ...
def project_dm_nr2r(mol1, dm1, mol2): ...
def project_dm_r2r(mol1, dm1, mol2): ...
def canonical_orth_(S, thr: float = 1e-07): ...
def partial_cholesky_orth_(S, canthr: float = 1e-07, cholthr: float = 1e-09): ...
def remove_linear_dep_(mf, threshold=..., lindep=..., cholesky_threshold=..., force_pivoted_cholesky=...): ...
remove_linear_dep = remove_linear_dep_

def convert_to_uhf(mf, out=None, remove_df: bool = False): ...
def convert_to_rhf(mf, out=None, remove_df: bool = False): ...
def convert_to_ghf(mf, out=None, remove_df: bool = False): ...
def get_ghf_orbspin(mo_energy, mo_occ, is_rhf=None): ...
def fast_newton(mf, mo_coeff=None, mo_occ=None, dm0=None, auxbasis=None, dual_basis=None, **newton_kwargs): ...
