from _typeshed import Incomplete
from pyscf import gto as gto
from pyscf.data import elements as elements
from pyscf.lib import logger as logger, param as param
from pyscf.scf import addons as addons, hf as hf, rohf as rohf

def get_atm_nrhf(mol, atomic_configuration=...): ...

class AtomSphAverageRHF(hf.RHF):
    atomic_configuration: Incomplete
    init_guess: str
    def __init__(self, mol) -> None: ...
    def check_sanity(self) -> None: ...
    def dump_flags(self, verbose=None) -> None: ...
    def eig(self, f, s, overwrite: bool = False, x=None): ...
    def get_occ(self, mo_energy=None, mo_coeff=None): ...
    def get_grad(self, mo_coeff, mo_occ, fock=None): ...
    def scf(self, *args, **kwargs): ...
AtomSphericAverageRHF = AtomSphAverageRHF

class AtomHF1e(rohf.HF1e, AtomSphAverageRHF):
    eig: Incomplete

def frac_occ(symb, l, atomic_configuration=...): ...
