from _typeshed import Incomplete
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.data import nist as nist
from pyscf.lib import logger as logger
from pyscf.scf import _vhf, chkfile as chkfile, hf as hf

zquatev: Incomplete
DEBUG: bool

def kernel(mf, conv_tol: float = 1e-09, conv_tol_grad=None, dump_chk: bool = True, dm0=None, callback=None, conv_check: bool = True): ...
def energy_elec(mf, dm=None, h1e=None, vhf=None): ...
def get_jk_coulomb(mol, dm, hermi: int = 1, coulomb_allow: str = 'SSSS', opt_llll=None, opt_ssll=None, opt_ssss=None, omega=None, verbose=None): ...
get_jk = get_jk_coulomb

def get_hcore(mol): ...
def get_ovlp(mol): ...
make_rdm1 = hf.make_rdm1

def init_guess_by_minao(mol): ...
def init_guess_by_1e(mol): ...
def init_guess_by_atom(mol): ...
def init_guess_by_huckel(mol): ...
def init_guess_by_mod_huckel(mol): ...
def init_guess_by_sap(mol, mf): ...
def init_guess_by_chkfile(mol, chkfile_name, project=None): ...
def get_init_guess(mol, key: str = 'minao', **kwargs): ...
def time_reversal_matrix(mol, mat): ...
def analyze(mf, verbose=..., **kwargs): ...
def mulliken_pop(mol, dm, s=None, verbose=...): ...
def dip_moment(mol, dm, unit: str = 'Debye', verbose=..., **kwargs): ...
def get_grad(mo_coeff, mo_occ, fock_ao): ...

class DHF(hf.SCF):
    __doc__: Incomplete
    conv_tol: Incomplete
    with_ssss: Incomplete
    with_gaunt: Incomplete
    with_breit: Incomplete
    ssss_approx: Incomplete
    screening: bool
    def __init__(self, mol) -> None: ...
    def dump_flags(self, verbose=None): ...
    def get_hcore(self, mol=None): ...
    def get_ovlp(self, mol=None): ...
    def get_grad(self, mo_coeff, mo_occ, fock=None): ...
    def init_guess_by_minao(self, mol=None): ...
    def init_guess_by_atom(self, mol=None): ...
    def init_guess_by_huckel(self, mol=None): ...
    def init_guess_by_mod_huckel(self, mol=None): ...
    def init_guess_by_sap(self, mol=None, **kwargs): ...
    def init_guess_by_chkfile(self, chkfile=None, project=None): ...
    def build(self, mol=None): ...
    def get_occ(self, mo_energy=None, mo_coeff=None): ...
    make_rdm1: Incomplete
    energy_elec = energy_elec
    def init_direct_scf(self, mol=None): ...
    def get_jk(self, mol=None, dm=None, hermi: int = 1, with_j: bool = True, with_k: bool = True, omega=None): ...
    def get_veff(self, mol=None, dm=None, dm_last: int = 0, vhf_last: int = 0, hermi: int = 1): ...
    def scf(self, dm0=None): ...
    def analyze(self, verbose=None): ...
    def mulliken_pop(self, mol=None, dm=None, s=None, verbose=...): ...
    def dip_moment(self, mol=None, dm=None, unit: str = 'Debye', verbose=..., **kwargs): ...
    def sfx2c1e(self) -> None: ...
    def x2c1e(self): ...
    x2c = x2c1e
    def nuc_grad_method(self): ...
    mol: Incomplete
    def reset(self, mol=None): ...
    def stability(self, internal=None, external=None, verbose=None, return_status: bool = False, **kwargs): ...
    def to_rhf(self) -> None: ...
    def to_uhf(self) -> None: ...
    def to_ghf(self) -> None: ...
    def to_rks(self, xc=None) -> None: ...
    def to_uks(self, xc=None) -> None: ...
    def to_gks(self, xc=None) -> None: ...
    def to_dhf(self): ...
    def to_dks(self, xc: str = 'HF'): ...
    to_ks = to_dks
    to_gpu = lib.to_gpu
UHF = DHF
UDHF = DHF

class HF1e(DHF):
    scf: Incomplete

class RDHF(DHF):
    def __init__(self, mol) -> None: ...
    def x2c1e(self): ...
    x2c = x2c1e
    def to_dks(self, xc: str = 'HF'): ...
RHF = RDHF

class _VHFOpt(_vhf._VHFOpt):
    dm_cond: Incomplete
    def set_dm(self, dm, atm, bas, env) -> None: ...
