from _typeshed import Incomplete
from pyscf import lib as lib
from pyscf.lib import logger as logger

DEBUG: bool

class CDIIS(lib.diis.DIIS):
    rollback: int
    space: int
    Corth: Incomplete
    damp: int
    def __init__(self, mf=None, filename=None, Corth=None) -> None: ...
    def update(self, s, d, f, *args, **kwargs): ...
    def get_num_vec(self): ...
SCFDIIS = CDIIS
SCF_DIIS = CDIIS
DIIS = CDIIS

def get_err_vec_orig(s, d, f): ...
def get_err_vec_orth(s, d, f, Corth): ...
def get_err_vec(s, d, f, Corth=None): ...

class EDIIS(lib.diis.DIIS):
    def update(self, s, d, f, mf, h1e, vhf, *args, **kwargs): ...

def ediis_minimize(es, ds, fs): ...

class ADIIS(lib.diis.DIIS):
    def update(self, s, d, f, mf, h1e, vhf, *args, **kwargs): ...

def adiis_minimize(ds, fs, idnewest): ...
