from _typeshed import Incomplete
from pyscf import scf as scf
from pyscf.lib import logger as logger

DISP_VERSIONS: Incomplete
XC_MAP: Incomplete

def parse_dft(xc_code): ...
def parse_disp(dft_method=None, disp=None): ...
def check_disp(mf, disp=None): ...
def get_dispersion(mf, disp=None, with_3body=None, verbose=None): ...
