from _typeshed import Incomplete
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.lib import logger as logger
from pyscf.scf import chkfile as chkfile, hf as hf, uhf as uhf

WITH_META_LOWDIN: Incomplete
PRE_ORTH_METHOD: Incomplete
MO_BASE: Incomplete

def init_guess_by_chkfile(mol, chkfile_name, project=None): ...
def get_jk(mol, dm, hermi: int = 0, with_j: bool = True, with_k: bool = True, jkbuild=..., omega=None): ...
def get_occ(mf, mo_energy=None, mo_coeff=None): ...
def spin_square(mo, s: int = 1): ...
def analyze(mf, verbose=..., with_meta_lowdin=..., origin=None, **kwargs): ...
def mulliken_pop(mol, dm, s=None, verbose=...): ...
def mulliken_meta(mol, dm_ao, verbose=..., pre_orth_method=..., s=None): ...
def det_ovlp(mo1, mo2, occ1, occ2, ovlp): ...
def dip_moment(mol, dm, unit_symbol: str = 'Debye', origin=None, verbose=...): ...
canonicalize = hf.canonicalize

def guess_orbspin(mo_coeff): ...

class GHF(hf.SCF):
    __doc__: Incomplete
    with_soc: Incomplete
    get_init_guess: Incomplete
    get_occ = get_occ
    def get_hcore(self, mol=None): ...
    def get_ovlp(self, mol=None): ...
    def get_grad(self, mo_coeff, mo_occ, fock=None): ...
    def init_guess_by_minao(self, mol=None): ...
    def init_guess_by_atom(self, mol=None): ...
    def init_guess_by_huckel(self, mol=None): ...
    def init_guess_by_mod_huckel(self, mol=None): ...
    def init_guess_by_sap(self, mol=None, **kwargs): ...
    def init_guess_by_chkfile(self, chkfile=None, project=None): ...
    def get_jk(self, mol=None, dm=None, hermi: int = 0, with_j: bool = True, with_k: bool = True, omega=None): ...
    def get_veff(self, mol=None, dm=None, dm_last: int = 0, vhf_last: int = 0, hermi: int = 1): ...
    def analyze(self, verbose=None, **kwargs): ...
    def mulliken_pop(self, mol=None, dm=None, s=None, verbose=...): ...
    def mulliken_meta(self, mol=None, dm=None, verbose=..., pre_orth_method=..., s=None): ...
    def spin_square(self, mo_coeff=None, s=None): ...
    def det_ovlp(self, mo1, mo2, occ1, occ2, ovlp=None): ...
    def dip_moment(self, mol=None, dm=None, unit_symbol: str = 'Debye', origin=None, verbose=...): ...
    def convert_from_(self, mf): ...
    def stability(self, internal=None, external=None, verbose=None, return_status: bool = False, **kwargs): ...
    def nuc_grad_method(self) -> None: ...
    def x2c1e(self): ...
    x2c = x2c1e
    def to_ks(self, xc: str = 'HF'): ...
    to_gpu = lib.to_gpu

class HF1e(GHF):
    scf: Incomplete
