from _typeshed import Incomplete
from functools import reduce as reduce
from pyscf import __config__ as __config__, lib as lib, symm as symm
from pyscf.lib import logger as logger
from pyscf.scf import chkfile as chkfile, ghf as ghf, hf as hf, hf_symm as hf_symm

WITH_META_LOWDIN: Incomplete
MO_BASE: Incomplete

def analyze(mf, verbose=..., with_meta_lowdin=..., **kwargs): ...
def canonicalize(mf, mo_coeff, mo_occ, fock=None): ...

class SymAdaptedGHF(ghf.GHF):
    __doc__: Incomplete
    irrep_nelec: Incomplete
    def __init__(self, mol) -> None: ...
    def dump_flags(self, verbose=None): ...
    def build(self, mol=None): ...
    def check_linear_dependency(self, s, verbose=None): ...
    def eig(self, h, s, overwrite: bool = False, x=None, symm_orb=None, irrep_id=None): ...
    def get_grad(self, mo_coeff, mo_occ, fock=None): ...
    def get_occ(self, mo_energy=None, mo_coeff=None): ...
    def analyze(self, verbose=None, **kwargs): ...
    def get_irrep_nelec(self, mol=None, mo_coeff=None, mo_occ=None, s=None): ...
    canonicalize = canonicalize
    def get_orbsym(self, mo_coeff=None, s=None): ...
    orbsym: Incomplete
    to_gpu = lib.to_gpu
GHF = SymAdaptedGHF

class HF1e(GHF):
    scf: Incomplete

def get_orbsym(mol, mo_coeff, s=None, check: bool = False, symm_orb=None, irrep_id=None): ...
