from _typeshed import Incomplete
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.data import nist as nist
from pyscf.lib import logger as logger
from pyscf.scf import chkfile as chkfile, diis as diis, dispersion as dispersion, smearing as smearing

WITH_META_LOWDIN: Incomplete
PRE_ORTH_METHOD: Incomplete
MO_BASE: Incomplete
TIGHT_GRAD_CONV_TOL: Incomplete
MUTE_CHKFILE: Incomplete
remove_overlap_zero_eigenvalue: Incomplete
overlap_zero_eigenvalue_threshold: Incomplete

def kernel(mf, conv_tol: float = 1e-10, conv_tol_grad=None, dump_chk: bool = True, dm0=None, callback=None, conv_check: bool = True, **kwargs): ...
def energy_elec(mf, dm=None, h1e=None, vhf=None): ...
def energy_tot(mf, dm=None, h1e=None, vhf=None): ...
def get_hcore(mol): ...
def get_ovlp(mol): ...
def init_guess_by_minao(mol): ...
def init_guess_by_1e(mol): ...
def init_guess_by_atom(mol): ...
def init_guess_by_huckel(mol): ...
def init_guess_by_mod_huckel(mol): ...
def Kgwh(Ei, Ej, updated_rule: bool = False): ...
def init_guess_by_chkfile(mol, chkfile_name, project=None): ...
def init_guess_by_sap(mol, sap_basis, **kwargs): ...
def get_init_guess(mol, key: str = 'minao', **kwargs): ...
def level_shift(s, d, f, factor): ...
def damping(f, f_prev, factor): ...
def make_sap(mol, sap_basis): ...
def make_rdm1(mo_coeff, mo_occ, **kwargs): ...
def make_rdm2(mo_coeff, mo_occ, **kwargs): ...
def dot_eri_dm(eri, dm, hermi: int = 0, with_j: bool = True, with_k: bool = True): ...
def get_jk(mol, dm, hermi: int = 1, vhfopt=None, with_j: bool = True, with_k: bool = True, omega=None): ...
def get_veff(mol, dm, dm_last=None, vhf_last=None, hermi: int = 1, vhfopt=None): ...
def get_fock(mf, h1e=None, s1e=None, vhf=None, dm=None, cycle: int = -1, diis=None, diis_start_cycle=None, level_shift_factor=None, damp_factor=None, fock_last=None): ...
def get_occ(mf, mo_energy=None, mo_coeff=None): ...
def get_grad(mo_coeff, mo_occ, fock_ao): ...
def analyze(mf, verbose=..., with_meta_lowdin=..., origin=None, **kwargs): ...
def dump_scf_summary(mf, verbose=...) -> None: ...
def mulliken_pop(mol, dm, s=None, verbose=...): ...
def mulliken_meta(mol, dm, verbose=..., pre_orth_method=..., s=None): ...
mulliken_pop_meta_lowdin_ao = mulliken_meta

def check_linear_dependency(s, log=None): ...
def canonical_orthogonalization(s): ...
def eig(h, s, overwrite: bool = False): ...
def canonicalize(mf, mo_coeff, mo_occ, fock=None): ...
def dip_moment(mol, dm, unit: str = 'Debye', origin=None, verbose=..., **kwargs): ...
def quad_moment(mol, dm, unit: str = 'DebyeAngstrom', origin=None, verbose=..., **kwargs): ...
def uniq_var_indices(mo_occ): ...
def pack_uniq_var(x, mo_occ): ...
def unpack_uniq_var(dx, mo_occ): ...
def as_scanner(mf): ...

class SCF_Scanner(lib.SinglePointScanner):
    def __init__(self, mf_obj) -> None: ...
    mo_coeff: Incomplete
    def __call__(self, mol_or_geom, **kwargs): ...

class SCF(lib.StreamObject):
    conv_tol: Incomplete
    conv_tol_grad: Incomplete
    conv_tol_cpscf: Incomplete
    max_cycle: Incomplete
    init_guess: Incomplete
    sap_basis: str
    disp: Incomplete
    DIIS: Incomplete
    diis: Incomplete
    diis_space: Incomplete
    diis_damp: Incomplete
    diis_start_cycle: Incomplete
    diis_file: Incomplete
    diis_space_rollback: int
    damp: Incomplete
    level_shift: Incomplete
    direct_scf: Incomplete
    direct_scf_tol: Incomplete
    conv_check: Incomplete
    callback: Incomplete
    mol: Incomplete
    verbose: Incomplete
    max_memory: Incomplete
    stdout: Incomplete
    chkfile: Incomplete
    mo_energy: Incomplete
    mo_coeff: Incomplete
    mo_occ: Incomplete
    e_tot: int
    converged: bool
    cycles: int
    scf_summary: Incomplete
    def __init__(self, mol) -> None: ...
    def __getattr__(self, key): ...
    def build(self, mol=None): ...
    @property
    def opt(self): ...
    @opt.setter
    def opt(self, x) -> None: ...
    def dump_flags(self, verbose=None): ...
    def check_linear_dependency(self, s, verbose=None): ...
    def eig(self, h, s, overwrite: bool = False, x=None): ...
    def get_hcore(self, mol=None): ...
    def get_ovlp(self, mol=None): ...
    get_fock = get_fock
    get_occ = get_occ
    def get_grad(self, mo_coeff, mo_occ, fock=None): ...
    def dump_chk(self, envs_or_file): ...
    def init_guess_by_minao(self, mol=None): ...
    def init_guess_by_atom(self, mol=None): ...
    def init_guess_by_huckel(self, mol=None): ...
    def init_guess_by_mod_huckel(self, updated_rule, mol=None): ...
    def init_guess_by_1e(self, mol=None): ...
    def init_guess_by_sap(self, mol=None, **kwargs): ...
    def init_guess_by_chkfile(self, chkfile=None, project=None): ...
    def from_chk(self, chkfile=None, project=None): ...
    def get_init_guess(self, mol=None, key: str = 'minao', **kwargs): ...
    make_rdm1: Incomplete
    make_rdm2: Incomplete
    energy_elec = energy_elec
    energy_tot = energy_tot
    do_disp = dispersion.check_disp
    get_dispersion = dispersion.get_dispersion
    smearing = smearing.smearing
    def energy_nuc(self): ...
    check_convergence: Incomplete
    def scf(self, dm0=None, **kwargs): ...
    kernel: Incomplete
    def init_direct_scf(self, mol=None): ...
    def get_jk(self, mol=None, dm=None, hermi: int = 1, with_j: bool = True, with_k: bool = True, omega=None): ...
    def get_j(self, mol=None, dm=None, hermi: int = 1, omega=None): ...
    def get_k(self, mol=None, dm=None, hermi: int = 1, omega=None): ...
    def get_veff(self, mol=None, dm=None, dm_last: int = 0, vhf_last: int = 0, hermi: int = 1): ...
    def analyze(self, verbose=None, with_meta_lowdin=..., **kwargs): ...
    dump_scf_summary = dump_scf_summary
    def mulliken_pop(self, mol=None, dm=None, s=None, verbose=...): ...
    def mulliken_meta(self, mol=None, dm=None, verbose=..., pre_orth_method=..., s=None): ...
    def pop(self, *args, **kwargs): ...
    mulliken_pop_meta_lowdin_ao = pop
    canonicalize = canonicalize
    def dip_moment(self, mol=None, dm=None, unit: str = 'Debye', origin=None, verbose=..., **kwargs): ...
    def quad_moment(self, mol=None, dm=None, unit: str = 'DebyeAngstrom', origin=None, verbose=..., **kwargs): ...
    def density_fit(self, auxbasis=None, with_df=None, only_dfj: bool = False): ...
    def multigrid_numint(self, margin=None, mesh=None) -> None: ...
    def sfx2c1e(self): ...
    x2c1e = sfx2c1e
    x2c = x2c1e
    def newton(self): ...
    def remove_soscf(self): ...
    def stability(self) -> None: ...
    def nuc_grad_method(self): ...
    def Gradients(self) -> None: ...
    def update_(self, chkfile=None): ...
    update_from_chk = update_
    update_from_chk_ = update_
    update = update_
    as_scanner = as_scanner
    def reset(self, mol=None): ...
    def apply(self, fn, *args, **kwargs): ...
    def to_rhf(self): ...
    def to_uhf(self): ...
    def to_ghf(self): ...
    def to_rks(self, xc: str = 'HF'): ...
    def to_uks(self, xc: str = 'HF'): ...
    def to_gks(self, xc: str = 'HF'): ...
    def convert_from_(self, mf) -> None: ...
    def to_ks(self, xc: str = 'HF') -> None: ...
    def to_gpu(self) -> None: ...
    def istype(self, type_code): ...

class KohnShamDFT: ...

class RHF(SCF):
    __doc__: Incomplete
    def check_sanity(self): ...
    def get_init_guess(self, mol=None, key: str = 'minao', **kwargs): ...
    def get_jk(self, mol=None, dm=None, hermi: int = 1, with_j: bool = True, with_k: bool = True, omega=None): ...
    def get_veff(self, mol=None, dm=None, dm_last: int = 0, vhf_last: int = 0, hermi: int = 1): ...
    def convert_from_(self, mf): ...
    def spin_square(self, mo_coeff=None, s=None): ...
    def stability(self, internal=..., external=..., verbose=None, return_status: bool = False, **kwargs): ...
    def nuc_grad_method(self): ...
    def to_ks(self, xc: str = 'HF'): ...
    to_gpu = lib.to_gpu
