from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.scf import hf as hf, uhf as uhf

WITH_META_LOWDIN: Incomplete
MO_BASE: Incomplete

def init_guess_by_minao(mol): ...
def init_guess_by_atom(mol): ...
def init_guess_by_sap(mol, sap_basis, **kwargs): ...
init_guess_by_huckel = uhf.init_guess_by_huckel
init_guess_by_mod_huckel = uhf.init_guess_by_mod_huckel

def init_guess_by_chkfile(mol, chkfile_name, project=None): ...
def get_fock(mf, h1e=None, s1e=None, vhf=None, dm=None, cycle: int = -1, diis=None, diis_start_cycle=None, level_shift_factor=None, damp_factor=None, fock_last=None): ...
def get_roothaan_fock(focka_fockb, dma_dmb, s): ...
def get_occ(mf, mo_energy=None, mo_coeff=None): ...
def get_grad(mo_coeff, mo_occ, fock): ...
def make_rdm1(mo_coeff, mo_occ, **kwargs): ...
def energy_elec(mf, dm=None, h1e=None, vhf=None): ...
get_veff = uhf.get_veff

def analyze(mf, verbose=..., with_meta_lowdin=..., origin=None, **kwargs): ...
mulliken_pop = hf.mulliken_pop
mulliken_meta = hf.mulliken_meta

def canonicalize(mf, mo_coeff, mo_occ, fock=None): ...
dip_moment = hf.dip_moment

class ROHF(hf.RHF):
    __doc__: Incomplete
    def __init__(self, mol) -> None: ...
    @property
    def nelec(self): ...
    @nelec.setter
    def nelec(self, x) -> None: ...
    @property
    def nelectron_alpha(self): ...
    @nelectron_alpha.setter
    def nelectron_alpha(self, x) -> None: ...
    check_sanity: Incomplete
    def dump_flags(self, verbose=None) -> None: ...
    get_init_guess: Incomplete
    def init_guess_by_minao(self, mol=None): ...
    def init_guess_by_atom(self, mol=None): ...
    def init_guess_by_huckel(self, mol=None): ...
    def init_guess_by_mod_huckel(self, mol=None): ...
    def init_guess_by_1e(self, mol=None): ...
    def init_guess_by_sap(self, mol=None, **kwargs): ...
    def init_guess_by_chkfile(self, chkfile=None, project=None): ...
    get_fock = get_fock
    get_occ = get_occ
    def eig(self, fock, s, overwrite: bool = False, x=None): ...
    def get_grad(self, mo_coeff, mo_occ, fock=None): ...
    def make_rdm1(self, mo_coeff=None, mo_occ=None, **kwargs): ...
    energy_elec = energy_elec
    def get_veff(self, mol=None, dm=None, dm_last: int = 0, vhf_last: int = 0, hermi: int = 1): ...
    def analyze(self, verbose=None, with_meta_lowdin=..., **kwargs): ...
    canonicalize = canonicalize
    def spin_square(self, mo_coeff=None, s=None): ...
    def stability(self, internal=..., external=..., verbose=None, return_status: bool = False, **kwargs): ...
    def nuc_grad_method(self): ...
    convert_from_: Incomplete
    def to_ks(self, xc: str = 'HF'): ...
    to_gpu = lib.to_gpu

class HF1e(ROHF):
    scf: Incomplete
