from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger

SMEARING_METHOD: Incomplete

def smearing(mf, sigma=None, method=..., mu0=None, fix_spin: bool = False): ...
def smearing_(mf, *args, **kwargs): ...

class _SmearingSCF:
    __name_mixin__: str
    sigma: Incomplete
    smearing_method: Incomplete
    mu0: Incomplete
    fix_spin: Incomplete
    entropy: Incomplete
    e_free: Incomplete
    e_zero: Incomplete
    def __init__(self, mf, sigma, method, mu0, fix_spin) -> None: ...
    def undo_smearing(self): ...
    def get_occ(self, mo_energy=None, mo_coeff=None): ...
    def get_grad(self, mo_coeff, mo_occ, fock=None): ...
    def energy_tot(self, dm=None, h1e=None, vhf=None): ...
    def to_gpu(self): ...
