from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.scf import hf as hf, hf_symm as hf_symm, uhf_symm as uhf_symm
from pyscf.soscf import newton_ah as newton_ah

STAB_NROOTS: Incomplete
STAB_TOL: Incomplete

def rhf_stability(mf, internal: bool = True, external: bool = False, verbose=None, return_status: bool = False, nroots=..., tol=...): ...
def uhf_stability(mf, internal: bool = True, external: bool = False, verbose=None, return_status: bool = False, nroots=..., tol=...): ...
def rohf_stability(mf, internal: bool = True, external: bool = False, verbose=None, return_status: bool = False, nroots=..., tol=...): ...
def dump_status(log, stable, method_class, stab_type) -> None: ...
def ghf_stability(mf, verbose=None, return_status: bool = False, nroots=..., tol=...): ...
def dhf_stability(mf, verbose=None, return_status: bool = False, nroots=..., tol=...): ...
def rhf_internal(mf, with_symmetry: bool = True, verbose=None, return_status: bool = False, nroots=..., tol=...): ...
def rhf_external(mf, with_symmetry: bool = True, verbose=None, return_status: bool = False, nroots=..., tol=...): ...
def rohf_internal(mf, with_symmetry: bool = True, verbose=None, return_status: bool = False, nroots=..., tol=...): ...
def rohf_external(mf, with_symmetry: bool = True, verbose=None, return_status: bool = False, nroots=..., tol=...) -> None: ...
def uhf_internal(mf, with_symmetry: bool = True, verbose=None, return_status: bool = False, nroots=..., tol=...): ...
def uhf_external(mf, with_symmetry: bool = True, verbose=None, return_status: bool = False, nroots=..., tol=...): ...
