from _typeshed import Incomplete
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.lib import logger as logger
from pyscf.scf import chkfile as chkfile, hf as hf

WITH_META_LOWDIN: Incomplete
PRE_ORTH_METHOD: Incomplete
MO_BASE: Incomplete

def init_guess_by_minao(mol, breaksym=None): ...
def init_guess_by_1e(mol, breaksym=None): ...
def init_guess_by_atom(mol, breaksym=None): ...
def init_guess_by_huckel(mol, breaksym=None): ...
def init_guess_by_mod_huckel(mol, breaksym=None): ...
def init_guess_by_sap(mol, sap_basis, breaksym=None, **kwargs): ...
def init_guess_by_chkfile(mol, chkfile_name, project=None): ...
def get_init_guess(mol, key: str = 'minao', **kwargs): ...
def make_rdm1(mo_coeff, mo_occ, **kwargs): ...
def make_rdm2(mo_coeff, mo_occ): ...
def get_veff(mol, dm, dm_last: int = 0, vhf_last: int = 0, hermi: int = 1, vhfopt=None): ...
def get_fock(mf, h1e=None, s1e=None, vhf=None, dm=None, cycle: int = -1, diis=None, diis_start_cycle=None, level_shift_factor=None, damp_factor=None, fock_last=None): ...
def get_occ(mf, mo_energy=None, mo_coeff=None): ...
def get_grad(mo_coeff, mo_occ, fock_ao): ...
def energy_elec(mf, dm=None, h1e=None, vhf=None): ...
def spin_square(mo, s: int = 1): ...
def analyze(mf, verbose=..., with_meta_lowdin=..., **kwargs): ...
def mulliken_pop(mol, dm, s=None, verbose=...): ...
def mulliken_spin_pop(mol, dm, s=None, verbose=...): ...
def mulliken_meta(mol, dm_ao, verbose=..., pre_orth_method=..., s=None): ...
mulliken_pop_meta_lowdin_ao = mulliken_meta

def mulliken_meta_spin(mol, dm_ao, verbose=..., pre_orth_method=..., s=None): ...
mulliken_spin_pop_meta_lowdin_ao = mulliken_meta_spin

def canonicalize(mf, mo_coeff, mo_occ, fock=None): ...
def det_ovlp(mo1, mo2, occ1, occ2, ovlp): ...
def make_asym_dm(mo1, mo2, occ1, occ2, x): ...
dip_moment = hf.dip_moment

class UHF(hf.SCF):
    __doc__: Incomplete
    init_guess_breaksym: Incomplete
    def __init__(self, mol) -> None: ...
    @property
    def nelec(self): ...
    @nelec.setter
    def nelec(self, x) -> None: ...
    @property
    def nelectron_alpha(self): ...
    @nelectron_alpha.setter
    def nelectron_alpha(self, x) -> None: ...
    def dump_flags(self, verbose=None) -> None: ...
    def eig(self, fock, s, overwrite: bool = False, x=None): ...
    get_fock = get_fock
    get_occ = get_occ
    def get_grad(self, mo_coeff, mo_occ, fock=None): ...
    def make_rdm1(self, mo_coeff=None, mo_occ=None, **kwargs): ...
    def make_rdm2(self, mo_coeff=None, mo_occ=None, **kwargs): ...
    energy_elec = energy_elec
    def get_init_guess(self, mol=None, key: str = 'minao', **kwargs): ...
    def init_guess_by_minao(self, mol=None, breaksym=None): ...
    def init_guess_by_atom(self, mol=None, breaksym=None): ...
    def init_guess_by_huckel(self, mol=None, breaksym=None): ...
    def init_guess_by_mod_huckel(self, mol=None, breaksym=None): ...
    def init_guess_by_1e(self, mol=None, breaksym=None): ...
    def init_guess_by_sap(self, mol=None, breaksym=None, **kwargs): ...
    def init_guess_by_chkfile(self, chkfile=None, project=None): ...
    def get_jk(self, mol=None, dm=None, hermi: int = 1, with_j: bool = True, with_k: bool = True, omega=None): ...
    def get_veff(self, mol=None, dm=None, dm_last: int = 0, vhf_last: int = 0, hermi: int = 1): ...
    def analyze(self, verbose=None, with_meta_lowdin=..., **kwargs): ...
    def mulliken_pop(self, mol=None, dm=None, s=None, verbose=...): ...
    def mulliken_spin_pop(self, mol=None, dm=None, s=None, verbose=...): ...
    def mulliken_meta(self, mol=None, dm=None, verbose=..., pre_orth_method=..., s=None): ...
    def mulliken_meta_spin(self, mol=None, dm=None, verbose=..., pre_orth_method=..., s=None): ...
    def spin_square(self, mo_coeff=None, s=None): ...
    canonicalize = canonicalize
    def det_ovlp(self, mo1, mo2, occ1, occ2, ovlp=None): ...
    def make_asym_dm(self, mo1, mo2, occ1, occ2, x): ...
    def convert_from_(self, mf): ...
    def stability(self, internal=..., external=..., verbose=None, return_status: bool = False, **kwargs): ...
    def nuc_grad_method(self): ...
    def to_ks(self, xc: str = 'HF'): ...
    to_gpu = lib.to_gpu

class HF1e(UHF):
    scf: Incomplete
    def spin_square(self, mo_coeff=None, s=None): ...
