from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib, symm as symm
from pyscf.lib import logger as logger
from pyscf.lib.exceptions import PointGroupSymmetryError as PointGroupSymmetryError
from pyscf.scf import chkfile as chkfile, hf as hf, hf_symm as hf_symm, uhf as uhf

WITH_META_LOWDIN: Incomplete
MO_BASE: Incomplete

def analyze(mf, verbose=..., with_meta_lowdin=..., **kwargs): ...
def get_irrep_nelec(mol, mo_coeff, mo_occ, s=None): ...
def canonicalize(mf, mo_coeff, mo_occ, fock=None): ...
def get_orbsym(mol, mo_coeff, s=None, check: bool = False): ...
def get_wfnsym(mf, mo_coeff=None, mo_occ=None, orbsym=None): ...

class SymAdaptedUHF(uhf.UHF):
    __doc__: Incomplete
    irrep_nelec: Incomplete
    def __init__(self, mol) -> None: ...
    def dump_flags(self, verbose=None): ...
    def build(self, mol=None): ...
    check_linear_dependency: Incomplete
    def eig(self, h, s, overwrite: bool = False, x=None, symm_orb=None, irrep_id=None): ...
    def get_grad(self, mo_coeff, mo_occ, fock=None): ...
    def get_occ(self, mo_energy=None, mo_coeff=None): ...
    def analyze(self, verbose=None, with_meta_lowdin=..., **kwargs): ...
    def get_irrep_nelec(self, mol=None, mo_coeff=None, mo_occ=None, s=None): ...
    def get_orbsym(self, mo_coeff=None, s=None): ...
    orbsym: Incomplete
    get_wfnsym = get_wfnsym
    wfnsym: Incomplete
    canonicalize = canonicalize
    to_gpu = lib.to_gpu
UHF = SymAdaptedUHF

class HF1e(UHF):
    scf: Incomplete
