from _typeshed import Incomplete
from pyscf import ao2mo as ao2mo, fci as fci, lib as lib
from pyscf.lib import logger as logger
from pyscf.mcscf import casci as casci, mc1step as mc1step, mc_ao2mo as mc_ao2mo
from h5py._hl.dataset import Dataset
from numpy import float64, ndarray
from pyscf.fci.direct_spin1 import FCIvector
from pyscf.gto.mole import Mole
from pyscf.mcscf.casci import CASCI
from pyscf.mcscf.mc1step import CASSCF
from tempfile import _TemporaryFileWrapper
from typing import Callable, Dict, Optional, Tuple, Union

libmc: Incomplete
NUMERICAL_ZERO: float

def make_a16(h1e: ndarray, h2e: ndarray, dms: Dict[str, Optional[ndarray]], civec: Union[FCIvector, ndarray], norb: int, nelec: Tuple[int, int], link_index: None=None) -> ndarray: ...
def make_a22(h1e: ndarray, h2e: ndarray, dms: Dict[str, Optional[ndarray]], civec: Union[FCIvector, ndarray], norb: int, nelec: Tuple[int, int], link_index: None=None) -> ndarray: ...
def make_a17(h1e: ndarray, h2e: ndarray, dm2: ndarray, dm3: ndarray) -> ndarray: ...
def make_a19(h1e: ndarray, h2e: ndarray, dm1: ndarray, dm2: ndarray) -> ndarray: ...
def make_a23(h1e: ndarray, h2e: ndarray, dm1: ndarray, dm2: ndarray, dm3: ndarray) -> ndarray: ...
def make_a25(h1e: ndarray, h2e: ndarray, dm1: ndarray, dm2: ndarray) -> ndarray: ...
def make_hdm3(dm1: ndarray, dm2: ndarray, dm3: ndarray, hdm1: ndarray, hdm2: ndarray) -> ndarray: ...
def make_hdm2(dm1: ndarray, dm2: ndarray) -> ndarray: ...
def make_hdm1(dm1: ndarray) -> ndarray: ...
def make_a3(h1e: ndarray, h2e: ndarray, dm1: ndarray, dm2: ndarray, hdm1: ndarray) -> ndarray: ...
def make_k27(h1e: ndarray, h2e: ndarray, dm1: ndarray, dm2: ndarray) -> ndarray: ...
def make_a7(h1e: ndarray, h2e: ndarray, dm1: ndarray, dm2: ndarray, dm3: ndarray) -> Tuple[ndarray, ndarray]: ...
def make_a9(h1e: ndarray, h2e: ndarray, hdm1: ndarray, hdm2: ndarray, hdm3: ndarray) -> ndarray: ...
def make_a12(h1e: ndarray, h2e: ndarray, dm1: ndarray, dm2: ndarray, dm3: ndarray) -> ndarray: ...
def make_a13(h1e: ndarray, h2e: ndarray, dm1: ndarray, dm2: ndarray, dm3: ndarray) -> ndarray: ...
def Sr(mc: Union[CASCI, NEVPT], ci: Union[FCIvector, ndarray], dms: Dict[str, Optional[ndarray]], eris: Optional[Dict[str, Union[ndarray, _TemporaryFileWrapper]]]=None, verbose: None=None) -> Tuple[float64, float64]: ...
def Si(mc: Union[CASCI, NEVPT], ci: Union[FCIvector, ndarray], dms: Dict[str, Optional[ndarray]], eris: Optional[Dict[str, Union[ndarray, _TemporaryFileWrapper]]]=None, verbose: None=None) -> Tuple[float64, float64]: ...
def Sijrs(mc: Union[CASCI, NEVPT], eris: Dict[str, Union[ndarray, _TemporaryFileWrapper]], verbose: None=None) -> Tuple[float64, float64]: ...
def Sijr(mc: Union[CASCI, NEVPT], dms: Dict[str, Optional[ndarray]], eris: Dict[str, Union[ndarray, _TemporaryFileWrapper]], verbose: None=None) -> Tuple[float64, float64]: ...
def Srsi(mc: Union[CASCI, NEVPT], dms: Dict[str, Optional[ndarray]], eris: Dict[str, Union[ndarray, _TemporaryFileWrapper]], verbose: None=None) -> Tuple[float64, float64]: ...
def Srs(mc: Union[CASCI, NEVPT], dms: Dict[str, Optional[ndarray]], eris: Optional[Dict[str, Union[ndarray, _TemporaryFileWrapper]]]=None, verbose: None=None) -> Tuple[float64, float64]: ...
def Sij(mc: "NEVPT", dms: Dict[str, Optional[ndarray]], eris: Dict[str, Union[ndarray, _TemporaryFileWrapper]], verbose: None=None) -> Tuple[float64, float64]: ...
def Sir(mc: Union[CASCI, NEVPT], dms: Dict[str, Optional[ndarray]], eris: Dict[str, Union[ndarray, _TemporaryFileWrapper]], verbose: None=None) -> Tuple[float64, float64]: ...

class NEVPT(lib.StreamObject):
    ncore: Incomplete
    root: Incomplete
    compressed_mps: bool
    density_fit: Incomplete
    e_corr: Incomplete
    canonicalized: bool
    onerdm: Incomplete
    def __init__(self, mc: Union[CASCI, CASSCF], root: int = 0, density_fit: bool = True) -> None: ...
    mol: Incomplete
    def reset(self, mol: Optional[Mole]=None) -> "NEVPT": ...
    def get_hcore(self) -> ndarray: ...
    def canonicalize(self, mo_coeff: Optional[ndarray]=None, ci: Optional[FCIvector]=None, eris: None=None, sort: bool = False, cas_natorb: bool = False, casdm1: None=None, verbose: int=...) -> Tuple[ndarray, ndarray, ndarray]: ...
    def get_veff(self, mol=None, dm=None, hermi: int = 1): ...
    def h1e_for_cas(self, mo_coeff=None, ncas=None, ncore=None): ...
    def load_ci(self, root: None=None) -> Union[ndarray, FCIvector]: ...
    def for_dmrg(self): ...
    nevptsolver: Incomplete
    maxM: Incomplete
    tol: Incomplete
    stored_integral: Incomplete
    def compress_approx(self, maxM: int = 500, nevptsolver=None, tol: float = 1e-07, stored_integral: bool = False): ...
    def dump_flags(self, verbose: None=None) -> None: ...
    ci: Incomplete
    def kernel(self) -> float64: ...

def kernel(mc, *args, **kwargs): ...
def sc_nevpt(mc, ci=None, verbose=None): ...
def trans_e1_incore(mc: Union[CASCI, NEVPT], mo: ndarray) -> Tuple[ndarray, ndarray, ndarray, ndarray]: ...
def trans_e1_outcore(mc: Union[CASCI, NEVPT], mo: ndarray, max_memory: Optional[float]=None, ioblk_size: int = 256, tmpdir: None=None, verbose: int = 0) -> Tuple[ndarray, ndarray, ndarray, _TemporaryFileWrapper]: ...
