from _typeshed import Incomplete
from pyscf import ao2mo as ao2mo, fci as fci, lib as lib
from pyscf.lib import logger as logger
from pyscf.mcscf import casci as casci, mc1step as mc1step, mc_ao2mo as mc_ao2mo

libmc: Incomplete
NUMERICAL_ZERO: float

def make_a16(h1e, h2e, dms, civec, norb, nelec, link_index=None): ...
def make_a22(h1e, h2e, dms, civec, norb, nelec, link_index=None): ...
def make_a17(h1e, h2e, dm2, dm3): ...
def make_a19(h1e, h2e, dm1, dm2): ...
def make_a23(h1e, h2e, dm1, dm2, dm3): ...
def make_a25(h1e, h2e, dm1, dm2): ...
def make_hdm3(dm1, dm2, dm3, hdm1, hdm2): ...
def make_hdm2(dm1, dm2): ...
def make_hdm1(dm1): ...
def make_a3(h1e, h2e, dm1, dm2, hdm1): ...
def make_k27(h1e, h2e, dm1, dm2): ...
def make_a7(h1e, h2e, dm1, dm2, dm3): ...
def make_a9(h1e, h2e, hdm1, hdm2, hdm3): ...
def make_a12(h1e, h2e, dm1, dm2, dm3): ...
def make_a13(h1e, h2e, dm1, dm2, dm3): ...
def Sr(mc, ci, dms, eris=None, verbose=None): ...
def Si(mc, ci, dms, eris=None, verbose=None): ...
def Sijrs(mc, eris, verbose=None): ...
def Sijr(mc, dms, eris, verbose=None): ...
def Srsi(mc, dms, eris, verbose=None): ...
def Srs(mc, dms, eris=None, verbose=None): ...
def Sij(mc, dms, eris, verbose=None): ...
def Sir(mc, dms, eris, verbose=None): ...

class NEVPT(lib.StreamObject):
    ncore: Incomplete
    root: Incomplete
    compressed_mps: bool
    density_fit: Incomplete
    e_corr: Incomplete
    canonicalized: bool
    onerdm: Incomplete
    def __init__(self, mc, root: int = 0, density_fit: bool = True) -> None: ...
    mol: Incomplete
    def reset(self, mol=None): ...
    def get_hcore(self): ...
    def canonicalize(self, mo_coeff=None, ci=None, eris=None, sort: bool = False, cas_natorb: bool = False, casdm1=None, verbose=...): ...
    def get_veff(self, mol=None, dm=None, hermi: int = 1): ...
    def h1e_for_cas(self, mo_coeff=None, ncas=None, ncore=None): ...
    def load_ci(self, root=None): ...
    def for_dmrg(self): ...
    nevptsolver: Incomplete
    maxM: Incomplete
    tol: Incomplete
    stored_integral: Incomplete
    def compress_approx(self, maxM: int = 500, nevptsolver=None, tol: float = 1e-07, stored_integral: bool = False): ...
    def dump_flags(self, verbose=None) -> None: ...
    ci: Incomplete
    def kernel(self): ...

def kernel(mc, *args, **kwargs): ...
def sc_nevpt(mc, ci=None, verbose=None): ...
def trans_e1_incore(mc, mo): ...
def trans_e1_outcore(mc, mo, max_memory=None, ioblk_size: int = 256, tmpdir=None, verbose: int = 0): ...
