from pyscf import gto as gto, lib as lib
from pyscf.gto.moleintor import libcgto as libcgto

def ft_aopair(mol, Gv, shls_slice=None, aosym: str = 's1', b=..., gxyz=None, Gvbase=None, out=None, intor: str = 'GTO_ft_ovlp', comp: int = 1, q=..., return_complex: bool = True, ovlp_mask=None, verbose=None): ...
def ft_ao(mol, Gv, shls_slice=None, b=..., gxyz=None, Gvbase=None, verbose=None): ...
