from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.data import elements as elements
from pyscf.data.elements import ELEMENTS as ELEMENTS, ELEMENTS_PROTON as ELEMENTS_PROTON, charge as charge, is_ghost_atom as is_ghost_atom
from pyscf.gto import basis as basis, cmd_args as cmd_args, moleintor as moleintor
from pyscf.gto.ecp import core_configuration as core_configuration
from pyscf.gto.eval_gto import eval_gto as eval_gto
from pyscf.lib import logger as logger, param as param
from pyscf.lib.exceptions import BasisNotFoundError as BasisNotFoundError, PointGroupSymmetryError as PointGroupSymmetryError

CHARGE_OF: int
PTR_COORD: int
NUC_MOD_OF: int
PTR_ZETA: int
PTR_FRAC_CHARGE: int
PTR_RADIUS: int
ATM_SLOTS: int
ATOM_OF: int
ANG_OF: int
NPRIM_OF: int
NCTR_OF: int
RADI_POWER: int
KAPPA_OF: int
SO_TYPE_OF: int
PTR_EXP: int
PTR_COEFF: int
BAS_SLOTS: int
PTR_EXPCUTOFF: int
PTR_COMMON_ORIG: int
PTR_RINV_ORIG: int
PTR_RINV_ZETA: int
PTR_RANGE_OMEGA: int
PTR_F12_ZETA: int
PTR_GTG_ZETA: int
NGRIDS: int
PTR_GRIDS: int
AS_RINV_ORIG_ATOM: int
AS_ECPBAS_OFFSET: int
AS_NECPBAS: int
PTR_ENV_START: int
NUC_POINT: int
NUC_GAUSS: int
NUC_FRAC_CHARGE: int
NUC_ECP: int
BASE: Incomplete
NORMALIZE_GTO: Incomplete
DISABLE_EVAL: Incomplete
ARGPARSE: Incomplete
DUMPINPUT: Incomplete
BSE_META: Incomplete

def M(*args, **kwargs): ...
def gaussian_int(n, alpha): ...
def gto_norm(l, expnt): ...
def cart2sph(l, c_tensor=None, normalized=None): ...
def cart2spinor_kappa(kappa, l=None, normalized=None): ...
cart2j_kappa = cart2spinor_kappa

def cart2spinor_l(l, normalized=None): ...
cart2j_l = cart2spinor_l

def sph2spinor_kappa(kappa, l=None): ...
def sph2spinor_l(l): ...
def ao_rotation_matrix(mol, orientation): ...
def atom_types(atoms, basis=None, magmom=None): ...
def format_atom(atoms, origin: int = 0, axes=None, unit=...): ...
def format_basis(basis_tab, sort_basis: bool = True): ...
def uncontracted_basis(_basis): ...
uncontract = uncontracted_basis
contract: Incomplete
contracted_basis: Incomplete

def to_uncontracted_cartesian_basis(mol): ...
def decontract_basis(mol, atoms=None, to_cart: bool = False, aggregate: bool = False): ...
def format_ecp(ecp_tab): ...
def format_pseudo(pseudo_tab): ...
def expand_etb(l, n, alpha, beta): ...
def expand_etbs(etbs): ...
etbs = expand_etbs

def conc_env(atm1, bas1, env1, atm2, bas2, env2): ...
def conc_mol(mol1, mol2): ...
def intor_cross(intor, mol1, mol2, comp=None, grids=None): ...
def make_atm_env(atom, ptr: int = 0, nuclear_model=..., nucprop={}): ...
def make_bas_env(basis_add, atom_id: int = 0, ptr: int = 0): ...
def make_env(atoms, basis, pre_env=[], nucmod={}, nucprop={}): ...
def make_ecp_env(mol, _atm, ecp, pre_env=[]): ...
def tot_electrons(mol): ...
def copy(mol, deep: bool = True): ...
def pack(mol): ...
def unpack(moldic): ...
def dumps(mol): ...
def loads(molstr): ...
def len_spinor(l, kappa): ...
def len_cart(l): ...
def npgto_nr(mol, cart=None): ...
def nao_nr(mol, cart=None): ...
def nao_cart(mol): ...
def nao_nr_range(mol, bas_id0, bas_id1): ...
def nao_2c(mol): ...
def nao_2c_range(mol, bas_id0, bas_id1): ...
def ao_loc_nr(mol, cart=None): ...
def ao_loc_2c(mol): ...
def time_reversal_map(mol): ...

CHECK_GEOM: Incomplete

def classical_coulomb_energy(mol, charges=None, coords=None): ...
energy_nuc = classical_coulomb_energy

def inter_distance(mol, coords=None): ...
def sph_labels(mol, fmt: bool = True, base=...): ...
spheric_labels = sph_labels
spherical_labels = sph_labels

def cart_labels(mol, fmt: bool = True, base=...): ...
def ao_labels(mol, fmt: bool = True, base=...): ...
def spinor_labels(mol, fmt: bool = True, base=...): ...
def search_ao_label(mol, label): ...
def search_shell_id(mol, atm_id, l): ...
def search_ao_nr(mol, atm_id, l, m, atmshell): ...
def search_ao_r(mol, atm_id, l, j, m, atmshell) -> None: ...
def offset_2c_by_atom(mol): ...
def aoslice_by_atom(mol, ao_loc=None): ...
offset_nr_by_atom = aoslice_by_atom

def same_basis_set(mol1, mol2): ...
def same_mol(mol1, mol2, tol: float = 1e-05, cmp_basis: bool = True, ignore_chiral: bool = False): ...
is_same_mol = same_mol

def chiral_mol(mol1, mol2=None): ...
def inertia_moment(mol, mass=None, coords=None): ...
def atom_mass_list(mol, isotope_avg: bool = False, mass_table=None): ...
def condense_to_shell(mol, mat, compressor: str = 'max'): ...
def get_overlap_cond(mol, shls_slice=None): ...
def tostring(mol, format: str = 'raw'): ...
def tofile(mol, filename, format=None): ...
def fromfile(filename, format=None): ...
def fromstring(string, format: str = 'xyz'): ...
def is_au(unit): ...

class MoleBase(lib.StreamObject):
    output: Incomplete
    max_memory: Incomplete
    verbose: Incomplete
    unit: Incomplete
    incore_anyway: Incomplete
    cart: Incomplete
    charge: int
    spin: int
    symmetry: bool
    symmetry_subgroup: Incomplete
    atom: Incomplete
    basis: str
    nucmod: Incomplete
    ecp: Incomplete
    nucprop: Incomplete
    magmom: Incomplete
    pseudo: Incomplete
    groupname: str
    topgroup: str
    symm_orb: Incomplete
    irrep_id: Incomplete
    irrep_name: Incomplete
    def __init__(self) -> None: ...
    @property
    def natm(self): ...
    @property
    def nbas(self): ...
    @property
    def nelec(self): ...
    @nelec.setter
    def nelec(self, neleca_nelecb) -> None: ...
    @property
    def nelectron(self): ...
    @nelectron.setter
    def nelectron(self, n) -> None: ...
    @property
    def multiplicity(self): ...
    @multiplicity.setter
    def multiplicity(self, x) -> None: ...
    @property
    def ms(self): ...
    @ms.setter
    def ms(self, x) -> None: ...
    @property
    def enuc(self): ...
    @enuc.setter
    def enuc(self, x) -> None: ...
    copy = copy
    pack = pack
    @classmethod
    def unpack(cls, moldic): ...
    def unpack_(self, moldic): ...
    dumps = dumps
    @classmethod
    def loads(cls, molstr): ...
    def loads_(self, molstr): ...
    stdout: Incomplete
    def build(self, dump_input=..., parse_arg=..., verbose=None, output=None, max_memory=None, atom=None, basis=None, unit=None, nucmod=None, ecp=None, pseudo=None, charge=None, spin: int = 0, symmetry=None, symmetry_subgroup=None, cart=None, magmom=None): ...
    kernel = build
    def check_sanity(self): ...
    format_atom: Incomplete
    format_basis: Incomplete
    format_pseudo: Incomplete
    format_ecp: Incomplete
    expand_etb: Incomplete
    expand_etbs: Incomplete
    etbs: Incomplete
    def make_env(self, atoms, basis, pre_env=[], nucmod={}, nucprop=None): ...
    def make_atm_env(self, atom, ptr: int = 0, nucmod=..., nucprop=None): ...
    def make_bas_env(self, basis_add, atom_id: int = 0, ptr: int = 0): ...
    def make_ecp_env(self, _atm, _ecp, pre_env=[]): ...
    tot_electrons = tot_electrons
    def gto_norm(self, l, expnt): ...
    def dump_input(self): ...
    def set_common_origin(self, coord): ...
    set_common_orig = set_common_origin
    set_common_orig_ = set_common_orig
    set_common_origin_ = set_common_orig
    def with_common_origin(self, coord): ...
    with_common_orig = with_common_origin
    def set_rinv_origin(self, coord): ...
    set_rinv_orig = set_rinv_origin
    set_rinv_orig_ = set_rinv_orig
    set_rinv_origin_ = set_rinv_orig
    def with_rinv_origin(self, coord): ...
    with_rinv_orig = with_rinv_origin
    def set_range_coulomb(self, omega) -> None: ...
    set_range_coulomb_ = set_range_coulomb
    @property
    def omega(self): ...
    omega: Incomplete
    def with_range_coulomb(self, omega): ...
    def with_long_range_coulomb(self, omega): ...
    def with_short_range_coulomb(self, omega): ...
    def set_f12_zeta(self, zeta) -> None: ...
    def set_nuc_mod(self, atm_id, zeta): ...
    set_nuc_mod_ = set_nuc_mod
    def set_rinv_zeta(self, zeta): ...
    set_rinv_zeta_ = set_rinv_zeta
    def with_rinv_zeta(self, zeta): ...
    def with_rinv_at_nucleus(self, atm_id): ...
    with_rinv_as_nucleus = with_rinv_at_nucleus
    def with_integral_screen(self, threshold): ...
    def set_geom_(self, atoms_or_coords, unit=None, symmetry=None, inplace: bool = True): ...
    def update(self, chkfile): ...
    def update_from_chk(self, chkfile): ...
    def has_ecp(self): ...
    def has_ecp_soc(self): ...
    def atom_symbol(self, atm_id): ...
    def atom_pure_symbol(self, atm_id): ...
    @property
    def elements(self): ...
    def atom_charge(self, atm_id): ...
    def atom_charges(self): ...
    def atom_nelec_core(self, atm_id): ...
    def atom_coord(self, atm_id, unit: str = 'Bohr'): ...
    def atom_coords(self, unit: str = 'Bohr'): ...
    atom_mass_list = atom_mass_list
    def atom_nshells(self, atm_id): ...
    def atom_shell_ids(self, atm_id): ...
    def bas_coord(self, bas_id): ...
    def bas_atom(self, bas_id): ...
    def bas_angular(self, bas_id): ...
    def bas_nctr(self, bas_id): ...
    def bas_nprim(self, bas_id): ...
    def bas_kappa(self, bas_id): ...
    def bas_exp(self, bas_id): ...
    def bas_exps(self): ...
    def bas_ctr_coeff(self, bas_id): ...
    def bas_len_spinor(self, bas_id): ...
    def bas_len_cart(self, bas_id): ...
    npgto_nr = npgto_nr
    nao_nr = nao_nr
    nao_2c = nao_2c
    nao_cart = nao_cart
    nao_nr_range = nao_nr_range
    nao_2c_range = nao_2c_range
    ao_loc_nr = ao_loc_nr
    ao_loc_2c = ao_loc_2c
    @property
    def nao(self): ...
    @nao.setter
    def nao(self, x) -> None: ...
    ao_loc: Incomplete
    tmap = time_reversal_map
    time_reversal_map = time_reversal_map
    def intor(self, intor, comp=None, hermi: int = 0, aosym: str = 's1', out=None, shls_slice=None, grids=None): ...
    def intor_symmetric(self, intor, comp=None, grids=None): ...
    def intor_asymmetric(self, intor, comp=None, grids=None): ...
    def intor_by_shell(self, intor, shells, comp=None, grids=None): ...
    eval_ao = eval_gto
    eval_gto = eval_gto
    energy_nuc = energy_nuc
    def get_enuc(self): ...
    def get_ao_indices(self, bas_list, ao_loc=None): ...
    sph_labels = sph_labels
    spheric_labels = sph_labels
    cart_labels = cart_labels
    ao_labels = ao_labels
    spinor_labels = spinor_labels
    search_ao_label = search_ao_label
    def search_shell_id(self, atm_id, l): ...
    search_ao_nr = search_ao_nr
    search_ao_r = search_ao_r
    aoslice_by_atom = aoslice_by_atom
    aoslice_nr_by_atom = aoslice_by_atom
    offset_ao_by_atom = aoslice_by_atom
    offset_nr_by_atom = aoslice_by_atom
    aoslice_2c_by_atom = offset_2c_by_atom
    offset_2c_by_atom = offset_2c_by_atom
    condense_to_shell = condense_to_shell
    get_overlap_cond = get_overlap_cond
    to_uncontracted_cartesian_basis = to_uncontracted_cartesian_basis
    decontract_basis = decontract_basis
    ao_rotation_matrix = ao_rotation_matrix
    def cart2sph_coeff(self, normalized: str = 'sp'): ...
    def sph2spinor_coeff(self): ...
    def apply(self, fn, *args, **kwargs): ...

class Mole(MoleBase):
    __add__ = conc_mol
    inertia_moment = inertia_moment
    tostring = tostring
    tofile = tofile
    def __init__(self, **kwargs) -> None: ...
    def fromstring(self, string, format: str = 'xyz'): ...
    def fromfile(self, filename, format=None): ...
    def __getattr__(self, key): ...
    def ao2mo(self, mo_coeffs, erifile=None, dataname: str = 'eri_mo', intor: str = 'int2e', **kwargs): ...
    def to_cell(self, box=None, dimension: int = 3, margin=None): ...
    def to_gpu(self): ...

def from_zmatrix(atomstr): ...
zmat2cart = from_zmatrix
zmat = from_zmatrix

def cart2zmat(coord): ...
def dyall_nuc_mod(nuc_charge, nucprop={}): ...
def filatov_nuc_mod(nuc_charge, nucprop={}): ...
def fakemol_for_charges(coords, expnt: float = 1e+16): ...
def fakemol_for_cgtf_charge(coord, expnt: float = 1e+16, contr_coeff: int = 1): ...
def classify_ecp_pseudo(mol, ecp, pp): ...
def bse_predefined_ecp(basis_name, elements): ...
def extract_pgto_params(mol, op: str = 'diffuse'): ...
def most_diffuse_pgto(mol): ...

class _MoleLazyCallAdapter:
    fn: Incomplete
    name: Incomplete
    def __init__(self, fn, name) -> None: ...
    def __call__(self, *args, **kwargs): ...
    def __getattr__(self, key): ...
