import ctypes
from _typeshed import Incomplete
from pyscf import lib as lib

libcgto: Incomplete
ANG_OF: int
NPRIM_OF: int
NCTR_OF: int
KAPPA_OF: int
PTR_EXP: int
PTR_COEFF: int
BAS_SLOTS: int
NGRIDS: int
PTR_GRIDS: int

def getints(intor_name, atm, bas, env, shls_slice=None, comp=None, hermi: int = 0, aosym: str = 's1', ao_loc=None, cintopt=None, out=None): ...
def getints2c(intor_name, atm, bas, env, shls_slice=None, comp: int = 1, hermi: int = 0, ao_loc=None, cintopt=None, out=None): ...
def getints3c(intor_name, atm, bas, env, shls_slice=None, comp: int = 1, aosym: str = 's1', ao_loc=None, cintopt=None, out=None): ...
def getints4c(intor_name, atm, bas, env, shls_slice=None, comp: int = 1, aosym: str = 's1', ao_loc=None, cintopt=None, out=None): ...
def getints_by_shell(intor_name, shls, atm, bas, env, comp: int = 1): ...
def make_loc(bas, key): ...
def make_cintopt(atm, bas, env, intor): ...

class _cintoptHandler(ctypes.c_void_p):
    def __del__(self) -> None: ...

def ascint3(intor_name): ...
