import ctypes
from _typeshed import Incomplete
from pyscf import lib as lib
from numpy import int64, ndarray
from typing import Any, List, Optional, Tuple, Union

libcgto: Incomplete
ANG_OF: int
NPRIM_OF: int
NCTR_OF: int
KAPPA_OF: int
PTR_EXP: int
PTR_COEFF: int
BAS_SLOTS: int
NGRIDS: int
PTR_GRIDS: int

def getints(intor_name: str, atm: ndarray, bas: ndarray, env: ndarray, shls_slice: Optional[Any]=None, comp: Optional[int]=None, hermi: int = 0, aosym: str = 's1', ao_loc: None=None, cintopt: Optional[_cintoptHandler]=None, out: None=None) -> ndarray: ...
def getints2c(intor_name: str, atm: ndarray, bas: ndarray, env: ndarray, shls_slice: Optional[Union[Tuple[int64, int64, int, int], Tuple[int, int, int, int]]]=None, comp: int = 1, hermi: int = 0, ao_loc: None=None, cintopt: None=None, out: None=None) -> ndarray: ...
def getints3c(intor_name: str, atm: ndarray, bas: ndarray, env: ndarray, shls_slice: Optional[Union[Tuple[int, int, int, int, int64, int64], Tuple[int, int, int, int, int, int], Tuple[int64, int64, int, int, int, int]]]=None, comp: int = 1, aosym: str = 's1', ao_loc: Optional[ndarray]=None, cintopt: Optional[_cintoptHandler]=None, out: Optional[ndarray]=None) -> ndarray: ...
def getints4c(intor_name: str, atm: ndarray, bas: ndarray, env: ndarray, shls_slice: Optional[Union[Tuple[int, int, int, int, int, int, int, int], Tuple[int, int, int, int], List[int], Tuple[int64, int64, int, int, int, int, int, int]]]=None, comp: int = 1, aosym: str = 's1', ao_loc: None=None, cintopt: None=None, out: None=None) -> ndarray: ...
def getints_by_shell(intor_name: str, shls: Union[Tuple[int, int, int], Tuple[int, int, int, int], Tuple[int, int]], atm: ndarray, bas: ndarray, env: ndarray, comp: Optional[int] = 1) -> ndarray: ...
def make_loc(bas: ndarray, key: str) -> ndarray: ...
def make_cintopt(atm: ndarray, bas: ndarray, env: ndarray, intor: str) -> "_cintoptHandler": ...

class _cintoptHandler(ctypes.c_void_p):
    def __del__(self) -> None: ...

def ascint3(intor_name: str) -> str: ...
