from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.data import elements as elements
from pyscf.data.elements import ELEMENTS as ELEMENTS, ELEMENTS_PROTON as ELEMENTS_PROTON, charge as charge, is_ghost_atom as is_ghost_atom
from pyscf.gto import basis as basis, cmd_args as cmd_args, moleintor as moleintor
from pyscf.gto.ecp import core_configuration as core_configuration
from pyscf.gto.eval_gto import eval_gto as eval_gto
from pyscf.lib import logger as logger, param as param
from pyscf.lib.exceptions import BasisNotFoundError as BasisNotFoundError, PointGroupSymmetryError as PointGroupSymmetryError
from contextlib import _GeneratorContextManager, nullcontext
from numpy import float64, int32, int64, ndarray
from pyscf.lib.misc import StreamObject
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.mp.ump2 import UMP2
from pyscf.pbc.df.ft_ao import ExtendedMole, _RangeSeparatedCell
from pyscf.pbc.gto.cell import Cell
from pyscf.scf.hf_symm import SymAdaptedROHF
from pyscf.scf.uhf import UHF
from typing import Any, Callable, Dict, Iterator, List, Optional, Set, Tuple, Type, Union

CHARGE_OF: int
PTR_COORD: int
NUC_MOD_OF: int
PTR_ZETA: int
PTR_FRAC_CHARGE: int
PTR_RADIUS: int
ATM_SLOTS: int
ATOM_OF: int
ANG_OF: int
NPRIM_OF: int
NCTR_OF: int
RADI_POWER: int
KAPPA_OF: int
SO_TYPE_OF: int
PTR_EXP: int
PTR_COEFF: int
BAS_SLOTS: int
PTR_EXPCUTOFF: int
PTR_COMMON_ORIG: int
PTR_RINV_ORIG: int
PTR_RINV_ZETA: int
PTR_RANGE_OMEGA: int
PTR_F12_ZETA: int
PTR_GTG_ZETA: int
NGRIDS: int
PTR_GRIDS: int
AS_RINV_ORIG_ATOM: int
AS_ECPBAS_OFFSET: int
AS_NECPBAS: int
PTR_ENV_START: int
NUC_POINT: int
NUC_GAUSS: int
NUC_FRAC_CHARGE: int
NUC_ECP: int
BASE: Incomplete
NORMALIZE_GTO: Incomplete
DISABLE_EVAL: Incomplete
ARGPARSE: Incomplete
DUMPINPUT: Incomplete
BSE_META: Incomplete

def M(*args, **kwargs) -> "Mole": ...
def gaussian_int(n: Union[ndarray, int], alpha: Union[ndarray, float, float64]) -> Union[ndarray, float64]: ...
def gto_norm(l: Union[ndarray, int], expnt: Union[ndarray, float]) -> Union[ndarray, float64]: ...
def cart2sph(l: int, c_tensor: Optional[ndarray]=None, normalized: Optional[str]=None) -> ndarray: ...
def cart2spinor_kappa(kappa: int, l: Optional[int]=None, normalized: Optional[str]=None) -> ndarray: ...
cart2j_kappa = cart2spinor_kappa

def cart2spinor_l(l: int, normalized: None=None) -> ndarray: ...
cart2j_l = cart2spinor_l

def sph2spinor_kappa(kappa: int, l: Optional[int]=None) -> Tuple[ndarray, ndarray]: ...
def sph2spinor_l(l: int) -> Tuple[ndarray, ndarray]: ...
def ao_rotation_matrix(mol: "Mole", orientation: ndarray) -> ndarray: ...
def atom_types(atoms: List[Union[Tuple[str, List[float]], List[Union[str, Tuple[int, int, int]]]]], basis: Optional[Any]=None, magmom: None=None) -> Dict[str, List[int]]: ...
def format_atom(atoms: Any, origin: Union[ndarray, int] = 0, axes: Optional[ndarray]=None, unit: Union[int, str]=...) -> List[Union[Tuple[str, List[float]], Any]]: ...
def format_basis(basis_tab: Any, sort_basis: bool = True) -> Dict[str, Any]: ...
def uncontracted_basis(_basis: List[List[Union[int, List[Union[float, int]], List[float]]]]) -> List[List[Union[int, List[Union[float, int]]]]]: ...
uncontract = uncontracted_basis
contract: Incomplete
contracted_basis: Incomplete

def to_uncontracted_cartesian_basis(mol: "Mole") -> Tuple[Mole, List[ndarray]]: ...
def decontract_basis(mol: "Mole", atoms: Optional[Union[List[int], bool]]=None, to_cart: bool = False, aggregate: bool = False) -> Union[Tuple[Mole, List[ndarray]], Tuple[Mole, ndarray]]: ...
def format_ecp(ecp_tab: Union[Dict[str, str], Dict[str, List[Union[int, List[List[Union[int, List[List[Union[Any, List[float]]]]]]]]]], Dict[str, List[Union[int, List[List[Union[int, List[List[Any]], List[List[Union[Any, List[float]]]]]]]]]], Dict[Union[str, int], str]]) -> Dict[str, Union[List[Union[int, List[List[Union[int, List[List[Union[Any, List[float]]]]]]]]], List[Union[int, List[List[Union[int, List[List[Any]], List[List[Union[Any, List[float]]]]]]]]], List[Union[int, List[List[Union[int, List[List[Union[Any, List[float]]]], List[List[Union[List[Union[float, float64]], Any]]]]]]]]]]: ...
def format_pseudo(pseudo_tab: Dict[str, Union[str, List[Union[List[int], float, int, List[float], List[Union[float, int, List[List[float]]]]]]]]) -> Dict[str, Union[List[Union[List[int], float, int, List[float], List[Union[float, int, List[List[float]]]], List[Union[float, int]]]], List[Union[List[int], float, int, List[float], List[Union[float, int, List[List[float]]]]]]]]: ...
def expand_etb(l: int, n: Union[int64, int], alpha: Union[float, int, float64], beta: Union[float, float64]) -> List[List[Union[int, List[Union[float64, int]], List[Union[float, int]]]]]: ...
def expand_etbs(etbs: Union[List[Tuple[int, int64, float64, float]], List[Tuple[int, int, float, float]], Tuple[Tuple[int, int, int, float], Tuple[int, int, int, float], Tuple[int, int, int, float]], List[Union[Tuple[int, int64, float64, float], Tuple[int, int64, float64, float64]]]]) -> List[List[Union[int, List[Union[float64, int]], List[Union[float, int]]]]]: ...
etbs = expand_etbs

def conc_env(atm1: ndarray, bas1: ndarray, env1: ndarray, atm2: ndarray, bas2: ndarray, env2: ndarray) -> Tuple[ndarray, ndarray, ndarray]: ...
def conc_mol(mol1: "Mole", mol2: "Mole") -> "Mole": ...
def intor_cross(intor: str, mol1: Union[Mole, Cell], mol2: "Mole", comp: None=None, grids: None=None) -> ndarray: ...
def make_atm_env(atom: Union[Tuple[str, List[float]], List[Union[str, Tuple[float, float, float]]]], ptr: int = 0, nuclear_model: Union[int, Callable]=..., nucprop: Dict[str, int]={}) -> Tuple[ndarray, ndarray]: ...
def make_bas_env(basis_add: List[List[Union[int, List[Union[float64, int]], List[float], List[int], List[Union[float, int]]]]], atom_id: int = 0, ptr: int = 0) -> Tuple[ndarray, ndarray]: ...
def make_env(atoms: List[Union[Tuple[str, List[float]], List[Union[str, Tuple[float, float, float]]], Any]], basis: Dict[str, Any], pre_env: ndarray=[], nucmod: Optional[Union[Dict[str, Callable], str, Dict[Union[str, int], str]]]={}, nucprop: Dict[str, Dict[str, int]]={}) -> Tuple[ndarray, ndarray, ndarray]: ...
def make_ecp_env(mol: "Mole", _atm: ndarray, ecp: Dict[str, Union[List[Union[int, List[List[Union[int, List[List[Union[Any, List[float]]]]]]]]], List[Union[int, List[List[Union[int, List[List[Any]], List[List[Union[Any, List[float]]]]]]]]], List[Union[int, List[List[Union[int, List[List[Union[Any, List[float]]]], List[List[Union[List[Union[float, float64]], Any]]]]]]]]]], pre_env: ndarray=[]) -> Tuple[ndarray, ndarray, ndarray]: ...
def tot_electrons(mol: "Mole") -> int: ...
def copy(mol: Union[Cell, Mole, _RangeSeparatedCell], deep: bool = True) -> Union[Cell, Mole, _RangeSeparatedCell]: ...
def pack(mol: "Mole") -> Dict[str, Any]: ...
def unpack(moldic: Dict[str, Any]) -> "Mole": ...
def dumps(mol: "Mole") -> str: ...
def loads(molstr: Union[bytes, str]) -> "Mole": ...
def len_spinor(l: Union[int32, int], kappa: Union[int32, int]) -> Union[int32, int]: ...
def len_cart(l: int32) -> int32: ...
def npgto_nr(mol: Union[Mole, ExtendedMole], cart: None=None) -> int: ...
def nao_nr(mol: Union[Mole, ExtendedMole, Cell], cart: Optional[bool]=None) -> int: ...
def nao_cart(mol: "Mole") -> int: ...
def nao_nr_range(mol: "Mole", bas_id0: int, bas_id1: int) -> Tuple[int, int]: ...
def nao_2c(mol: "Mole") -> int: ...
def nao_2c_range(mol: "Mole", bas_id0: int, bas_id1: int) -> Tuple[int, int]: ...
def ao_loc_nr(mol: Union[Mole, Cell], cart: Optional[bool]=None) -> ndarray: ...
def ao_loc_2c(mol: "Mole") -> ndarray: ...
def time_reversal_map(mol: "Mole") -> ndarray: ...

CHECK_GEOM: Incomplete

def classical_coulomb_energy(mol: "Mole", charges: None=None, coords: None=None) -> float64: ...
energy_nuc = classical_coulomb_energy

def inter_distance(mol: "Mole", coords: Optional[ndarray]=None) -> ndarray: ...
def sph_labels(mol: "Mole", fmt: Optional[Union[str, bool]] = True, base: int=...) -> List[Union[str, Tuple[int, str, str, str]]]: ...
spheric_labels = sph_labels
spherical_labels = sph_labels

def cart_labels(mol: "Mole", fmt: Optional[Union[str, bool]] = True, base: int=...) -> List[Union[str, Tuple[int, str, str, str]]]: ...
def ao_labels(mol: "Mole", fmt: Optional[Union[bool, str]] = True, base: int=...) -> List[Union[str, Tuple[int, str, str, str]]]: ...
def spinor_labels(mol: "Mole", fmt: Optional[Union[bool, str]] = True, base: int=...) -> List[Union[str, Tuple[int, str, str, str]]]: ...
def search_ao_label(mol: "Mole", label: Union[List[str], Callable, str, List[int]]) -> ndarray: ...
def search_shell_id(mol: "Mole", atm_id: int, l: int) -> int: ...
def search_ao_nr(mol: "Mole", atm_id: int, l: int, m: int, atmshell: int) -> int: ...
def search_ao_r(mol, atm_id, l, j, m, atmshell) -> None: ...
def offset_2c_by_atom(mol: "Mole") -> ndarray: ...
def aoslice_by_atom(mol: "Mole", ao_loc: Optional[ndarray]=None) -> ndarray: ...
offset_nr_by_atom = aoslice_by_atom

def same_basis_set(mol1: "Mole", mol2: "Mole"): ...
def same_mol(mol1: "Mole", mol2: "Mole", tol: float = 1e-05, cmp_basis: bool = True, ignore_chiral: bool = False) -> bool: ...
is_same_mol = same_mol

def chiral_mol(mol1: "Mole", mol2: Optional[Mole]=None) -> bool: ...
def inertia_moment(mol: "Mole", mass: Optional[ndarray]=None, coords: Optional[ndarray]=None) -> ndarray: ...
def atom_mass_list(mol: "Mole", isotope_avg: bool = False, mass_table: None=None) -> ndarray: ...
def condense_to_shell(mol: "Mole", mat: Union[ndarray, NPArrayWithTag], compressor: str = 'max') -> ndarray: ...
def get_overlap_cond(mol: "Mole", shls_slice: None=None) -> ndarray: ...
def tostring(mol: "Mole", format: str = 'raw') -> str: ...
def tofile(mol: "Mole", filename: str, format: Optional[str]=None) -> str: ...
def fromfile(filename: str, format: None=None) -> str: ...
def fromstring(string: str, format: str = 'xyz') -> str: ...
def is_au(unit: str) -> bool: ...

class MoleBase(lib.StreamObject):
    output: Incomplete
    max_memory: Incomplete
    verbose: Incomplete
    unit: Incomplete
    incore_anyway: Incomplete
    cart: Incomplete
    charge: int
    spin: int
    symmetry: bool
    symmetry_subgroup: Incomplete
    atom: Incomplete
    basis: str
    nucmod: Incomplete
    ecp: Incomplete
    nucprop: Incomplete
    magmom: Incomplete
    pseudo: Incomplete
    groupname: str
    topgroup: str
    symm_orb: Incomplete
    irrep_id: Incomplete
    irrep_name: Incomplete
    def __init__(self) -> None: ...
    @property
    def natm(self) -> int: ...
    @property
    def nbas(self) -> int: ...
    @property
    def nelec(self): ...
    @nelec.setter
    def nelec(self, neleca_nelecb) -> None: ...
    @property
    def nelectron(self): ...
    @nelectron.setter
    def nelectron(self, n) -> None: ...
    @property
    def multiplicity(self): ...
    @multiplicity.setter
    def multiplicity(self, x) -> None: ...
    @property
    def ms(self): ...
    @ms.setter
    def ms(self, x) -> None: ...
    @property
    def enuc(self): ...
    @enuc.setter
    def enuc(self, x) -> None: ...
    copy = copy
    pack = pack
    @classmethod
    def unpack(cls, moldic: Dict[str, Any]) -> "Mole": ...
    def unpack_(self, moldic: Dict[str, Any]) -> "Mole": ...
    dumps = dumps
    @classmethod
    def loads(cls, molstr: str) -> "Mole": ...
    def loads_(self, molstr: str) -> "Mole": ...
    stdout: Incomplete
    def build(self, dump_input: Union[bool, int, str]=..., parse_arg: Union[bool, int]=..., verbose: Optional[int]=None, output: Optional[str]=None, max_memory: Optional[int]=None, atom: Optional[Any]=None, basis: Optional[Any]=None, unit: Optional[str]=None, nucmod: None=None, ecp: Optional[Union[Dict[str, List[Union[int, List[List[Union[int, List[List[Union[Any, List[float]]]]]]]]]], Dict[str, List[Union[int, List[List[Union[int, List[List[Any]], List[List[Union[Any, List[float]]]]]]]]]], Dict[str, str], str]]=None, pseudo: Optional[str]=None, charge: Optional[int]=None, spin: Optional[int] = 0, symmetry: Optional[Union[int, str, bool]]=None, symmetry_subgroup: None=None, cart: Optional[bool]=None, magmom: None=None) -> Union[Mole, Cell]: ...
    kernel = build
    def check_sanity(self) -> Union[Mole, Cell]: ...
    format_atom: Incomplete
    format_basis: Incomplete
    format_pseudo: Incomplete
    format_ecp: Incomplete
    expand_etb: Incomplete
    expand_etbs: Incomplete
    etbs: Incomplete
    def make_env(self, atoms: List[Union[Tuple[str, List[float]], List[Union[str, Tuple[float, float, float]]], Any]], basis: Dict[str, Any], pre_env: ndarray=[], nucmod: Optional[Union[Dict[str, Callable], str, Dict[Union[str, int], str]]]={}, nucprop: Optional[Dict[str, Dict[str, int]]]=None) -> Tuple[ndarray, ndarray, ndarray]: ...
    def make_atm_env(self, atom, ptr: int = 0, nucmod=..., nucprop=None): ...
    def make_bas_env(self, basis_add, atom_id: int = 0, ptr: int = 0): ...
    def make_ecp_env(self, _atm: ndarray, _ecp: Dict[str, Union[List[Union[int, List[List[Union[int, List[List[Union[Any, List[float]]]]]]]]], List[Union[int, List[List[Union[int, List[List[Any]], List[List[Union[Any, List[float]]]]]]]]], List[Union[int, List[List[Union[int, List[List[Union[Any, List[float]]]], List[List[Union[List[Union[float, float64]], Any]]]]]]]]]], pre_env: ndarray=[]) -> Tuple[ndarray, ndarray, ndarray]: ...
    tot_electrons = tot_electrons
    def gto_norm(self, l: int, expnt: float): ...
    def dump_input(self) -> "Mole": ...
    def set_common_origin(self, coord: Union[ndarray, Tuple[int, int, int]]) -> "Mole": ...
    set_common_orig = set_common_origin
    set_common_orig_ = set_common_orig
    set_common_origin_ = set_common_orig
    def with_common_origin(self, coord: Tuple[int, int, int]) -> _GeneratorContextManager: ...
    with_common_orig = with_common_origin
    def set_rinv_origin(self, coord: Union[ndarray, Tuple[int, int, int], Tuple[float, float, float]]) -> "Mole": ...
    set_rinv_orig = set_rinv_origin
    set_rinv_orig_ = set_rinv_orig
    set_rinv_origin_ = set_rinv_orig
    def with_rinv_origin(self, coord: Union[ndarray, Tuple[int, int, int], Tuple[float, float, float]]) -> _GeneratorContextManager: ...
    with_rinv_orig = with_rinv_origin
    def set_range_coulomb(self, omega: Union[float, int, float64]) -> None: ...
    set_range_coulomb_ = set_range_coulomb
    @property
    def omega(self): ...
    omega: Incomplete
    def with_range_coulomb(self, omega: Optional[Union[float, int]]) -> Union[_GeneratorContextManager, nullcontext]: ...
    def with_long_range_coulomb(self, omega): ...
    def with_short_range_coulomb(self, omega): ...
    def set_f12_zeta(self, zeta: float) -> None: ...
    def set_nuc_mod(self, atm_id: int, zeta: int) -> "Mole": ...
    set_nuc_mod_ = set_nuc_mod
    def set_rinv_zeta(self, zeta: Union[float, int, float64]) -> "Mole": ...
    set_rinv_zeta_ = set_rinv_zeta
    def with_rinv_zeta(self, zeta: Union[float, int]) -> _GeneratorContextManager: ...
    def with_rinv_at_nucleus(self, atm_id: int) -> _GeneratorContextManager: ...
    with_rinv_as_nucleus = with_rinv_at_nucleus
    def with_integral_screen(self, threshold: Optional[float]) -> _GeneratorContextManager: ...
    def set_geom_(self, atoms_or_coords: Union[ndarray, List[Tuple[str, List[float]]], List[List[Union[int, Tuple[float, float, float], str]]], str], unit: Optional[Union[float, str]]=None, symmetry: Optional[bool]=None, inplace: bool = True) -> "Mole": ...
    def update(self, chkfile: str) -> "Mole": ...
    def update_from_chk(self, chkfile: str) -> "Mole": ...
    def has_ecp(self) -> Dict[Any, Any]: ...
    def has_ecp_soc(self): ...
    def atom_symbol(self, atm_id: Union[int64, int]) -> str: ...
    def atom_pure_symbol(self, atm_id: int) -> str: ...
    @property
    def elements(self) -> List[str]: ...
    def atom_charge(self, atm_id: Union[int64, int]) -> Union[int, float64]: ...
    def atom_charges(self) -> ndarray: ...
    def atom_nelec_core(self, atm_id: int) -> int: ...
    def atom_coord(self, atm_id: int, unit: str = 'Bohr') -> ndarray: ...
    def atom_coords(self, unit: str = 'Bohr') -> ndarray: ...
    atom_mass_list = atom_mass_list
    def atom_nshells(self, atm_id: int) -> int: ...
    def atom_shell_ids(self, atm_id: int) -> ndarray: ...
    def bas_coord(self, bas_id: int) -> ndarray: ...
    def bas_atom(self, bas_id: int) -> int: ...
    def bas_angular(self, bas_id: int) -> int: ...
    def bas_nctr(self, bas_id: Union[int64, int]) -> int: ...
    def bas_nprim(self, bas_id: Union[int64, int]) -> int: ...
    def bas_kappa(self, bas_id: int) -> int: ...
    def bas_exp(self, bas_id: int) -> ndarray: ...
    def bas_exps(self) -> List[ndarray]: ...
    def bas_ctr_coeff(self, bas_id: int) -> ndarray: ...
    def bas_len_spinor(self, bas_id: int) -> int: ...
    def bas_len_cart(self, bas_id: int) -> int32: ...
    npgto_nr = npgto_nr
    nao_nr = nao_nr
    nao_2c = nao_2c
    nao_cart = nao_cart
    nao_nr_range = nao_nr_range
    nao_2c_range = nao_2c_range
    ao_loc_nr = ao_loc_nr
    ao_loc_2c = ao_loc_2c
    @property
    def nao(self): ...
    @nao.setter
    def nao(self, x) -> None: ...
    ao_loc: Incomplete
    tmap = time_reversal_map
    time_reversal_map = time_reversal_map
    def intor(self, intor: str, comp: Optional[int]=None, hermi: int = 0, aosym: str = 's1', out: None=None, shls_slice: Optional[Any]=None, grids: None=None) -> ndarray: ...
    def intor_symmetric(self, intor: str, comp: None=None, grids: None=None) -> ndarray: ...
    def intor_asymmetric(self, intor: str, comp: None=None, grids: None=None) -> ndarray: ...
    def intor_by_shell(self, intor: str, shells: Union[Tuple[int, int, int], Tuple[int, int, int, int], Tuple[int, int]], comp: Optional[int]=None, grids: None=None) -> ndarray: ...
    eval_ao = eval_gto
    eval_gto = eval_gto
    energy_nuc = energy_nuc
    def get_enuc(self) -> float64: ...
    def get_ao_indices(self, bas_list, ao_loc=None): ...
    sph_labels = sph_labels
    spheric_labels = sph_labels
    cart_labels = cart_labels
    ao_labels = ao_labels
    spinor_labels = spinor_labels
    search_ao_label = search_ao_label
    def search_shell_id(self, atm_id: int, l: int) -> int: ...
    search_ao_nr = search_ao_nr
    search_ao_r = search_ao_r
    aoslice_by_atom = aoslice_by_atom
    aoslice_nr_by_atom = aoslice_by_atom
    offset_ao_by_atom = aoslice_by_atom
    offset_nr_by_atom = aoslice_by_atom
    aoslice_2c_by_atom = offset_2c_by_atom
    offset_2c_by_atom = offset_2c_by_atom
    condense_to_shell = condense_to_shell
    get_overlap_cond = get_overlap_cond
    to_uncontracted_cartesian_basis = to_uncontracted_cartesian_basis
    decontract_basis = decontract_basis
    ao_rotation_matrix = ao_rotation_matrix
    def cart2sph_coeff(self, normalized: str = 'sp') -> ndarray: ...
    def sph2spinor_coeff(self) -> ndarray: ...
    def apply(self, fn: Union[Type[UHF], Callable, str], *args, **kwargs) -> Union[SymAdaptedROHF, UMP2, UHF]: ...

class Mole(MoleBase):
    __add__ = conc_mol
    inertia_moment = inertia_moment
    tostring = tostring
    tofile = tofile
    def __init__(self, **kwargs) -> None: ...
    def fromstring(self, string: str, format: str = 'xyz') -> "Mole": ...
    def fromfile(self, filename: str, format: None=None) -> "Mole": ...
    def __getattr__(self, key: str) -> "_MoleLazyCallAdapter": ...
    def ao2mo(self, mo_coeffs: ndarray, erifile: None=None, dataname: str = 'eri_mo', intor: str = 'int2e', **kwargs) -> ndarray: ...
    def to_cell(self, box: None=None, dimension: int = 3, margin: None=None) -> Cell: ...
    def to_gpu(self): ...

def from_zmatrix(atomstr: str) -> List[Tuple[str, ndarray]]: ...
zmat2cart = from_zmatrix
zmat = from_zmatrix

def cart2zmat(coord: Union[ndarray, List[ndarray]]) -> str: ...
def dyall_nuc_mod(nuc_charge: int, nucprop: Dict[str, int]={}) -> float: ...
def filatov_nuc_mod(nuc_charge: int, nucprop: Dict[str, int]={}) -> float: ...
def fakemol_for_charges(coords: ndarray, expnt: float = 1e+16) -> Mole: ...
def fakemol_for_cgtf_charge(coord, expnt: float = 1e+16, contr_coeff: int = 1): ...
def classify_ecp_pseudo(mol: Union[Mole, Cell], ecp: Dict[Any, Any], pp: Union[Dict[str, Union[str, List[Union[List[int], float, int, List[float], List[Union[float, int, List[List[float]]]]]]]], str]) -> Union[Tuple[Dict[Any, Any], Dict[str, Union[str, List[Union[List[int], float, int, List[float], List[Union[float, int, List[List[float]]]]]]]]], Tuple[Dict[Any, Any], str]]: ...
def bse_predefined_ecp(basis_name: str, elements: Union[int, List[str], str]) -> Union[Tuple[None, Set[Any]], Tuple[None, None], Tuple[str, Set[int]]]: ...
def extract_pgto_params(mol: Cell, op: str = 'diffuse') -> Tuple[ndarray, ndarray]: ...
def most_diffuse_pgto(mol): ...

class _MoleLazyCallAdapter:
    fn: Incomplete
    name: Incomplete
    def __init__(self, fn: Callable, name: str) -> None: ...
    def __call__(self, *args, **kwargs) -> StreamObject: ...
    def __getattr__(self, key: str) -> Callable: ...
