from pyscf import gto as gto, lib as lib
from pyscf.df import incore as incore
from pyscf.gto import ft_ao as ft_ao
from pyscf.gto.mole import ATOM_OF as ATOM_OF
from pyscf.pbc.gto.pseudo import pp_int as pp_int

def get_gth_pp_nl_velgauge(mol, q): ...
def get_gth_pp_nl_velgauge_commutator(mol, q, origin=(0, 0, 0)): ...
def get_gth_pp_velgauge(mol, q): ...
def get_gth_pp_loc(mol): ...
