from pyscf import gto as gto, lib as lib
from pyscf.df import incore as incore
from pyscf.gto import ft_ao as ft_ao
from pyscf.gto.mole import Mole, ATOM_OF as ATOM_OF
from pyscf.pbc.gto.pseudo import pp_int as pp_int
from numpy import ndarray
from typing import Tuple

def get_gth_pp_nl_velgauge(mol: Mole, q: ndarray) -> ndarray: ...
def get_gth_pp_nl_velgauge_commutator(mol: Mole, q: ndarray, origin: Tuple[int, int, int]=(0, 0, 0)) -> ndarray: ...
def get_gth_pp_velgauge(mol, q): ...
def get_gth_pp_loc(mol): ...
