from pyscf.data.nist import MP_ME as MP_ME
from pyscf.eph.rhf import solve_hmat as solve_hmat
from pyscf.lib import logger as logger, param as param
from pyscf.pbc import dft as dft, gto as gto, scf as scf

def copy_mf(mf, cell): ...
def run_mfs(mf, cells_a, cells_b): ...
def gen_cells(cell, disp): ...
def get_vmat(mf, mfset, disp): ...
def run_hess(mfset, disp): ...
def kernel(mf, disp: float = 0.0001, mo_rep: bool = False): ...
