from pyscf import lib as lib
from pyscf.gto import mole as mole
from pyscf.lib import Ylm as Ylm
from pyscf.pbc.gto.pseudo import pp_int as pp_int
from numpy import float64, ndarray
from pyscf.pbc.gto.cell import Cell
from typing import Any, List, Optional, Tuple, Union

def get_alphas(cell: Cell) -> ndarray: ...
def get_alphas_gth(cell: Cell) -> ndarray: ...
def get_vlocG(cell: Cell, Gv: Optional[ndarray]=None) -> ndarray: ...
def get_gth_vlocG(cell: Cell, Gv: ndarray) -> ndarray: ...
def get_projG(cell: Cell, kpt: ndarray=...) -> Tuple[List[List[ndarray]], List[List[List[List[Union[ndarray, Any]]]]]]: ...
def get_gth_projG(cell: Cell, Gvs: ndarray) -> Tuple[List[List[ndarray]], List[List[List[List[Union[ndarray, Any]]]]]]: ...
def projG_li(G: ndarray, l: int, i: int, rl: float) -> ndarray: ...
def Ylm_real(l, m, theta, phi): ...
def cart2polar(rvec: ndarray) -> Tuple[ndarray, ndarray, ndarray]: ...
def get_pp(cell: Cell, kpt: ndarray=...) -> ndarray: ...
def get_jvloc_G0(cell, kpt=...): ...
