from _typeshed import Incomplete
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.pbc.lib.kpts_helper import gamma_point as gamma_point
from numpy import ndarray
from pyscf.gto.mole import Mole
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.gto.cell import Cell
from typing import Any, List, Optional, Tuple, Union

EPS_PPL: Incomplete
HL_TABLE_SLOTS: int
ATOM_OF: int
ANG_OF: int
HL_DIM_OF: int
HL_DATA_OF: int
HL_OFFSET0: int
HF_OFFSET1: int
HF_OFFSET2: int
libpbc: Incomplete

def get_pp_loc_part1(cell, kpts=None) -> None: ...
def get_gth_vlocG_part1(cell: Cell, Gv: ndarray) -> ndarray: ...
def get_pp_loc_part2(cell: Cell, kpts: Optional[ndarray]=None) -> Union[ndarray, List[ndarray]]: ...
def get_pp_loc_part2_gamma(cell: Cell) -> ndarray: ...
def vpploc_part2_nuc_grad(cell: Cell, dm: Union[ndarray, NPArrayWithTag], kpts: None=None) -> ndarray: ...
def get_pp_nl(cell: Cell, kpts: Optional[Union[ndarray, Tuple[ndarray, ndarray]]]=None) -> Union[ndarray, List[ndarray]]: ...
def vppnl_nuc_grad(cell: Cell, dm: Union[ndarray, NPArrayWithTag], kpts: Optional[ndarray]=None) -> ndarray: ...
def fake_cell_vloc(cell: Union[Cell, Mole], cn: int = 0, atm_id: None=None) -> Union[Cell, Mole]: ...
def fake_cell_vnl(cell: Union[Cell, Mole]) -> Union[Tuple[Mole, List[ndarray]], Tuple[Cell, List[ndarray]], Tuple[Cell, List[Any]]]: ...
