from _typeshed import Incomplete
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.pbc.lib.kpts_helper import gamma_point as gamma_point

EPS_PPL: Incomplete
HL_TABLE_SLOTS: int
ATOM_OF: int
ANG_OF: int
HL_DIM_OF: int
HL_DATA_OF: int
HL_OFFSET0: int
HF_OFFSET1: int
HF_OFFSET2: int
libpbc: Incomplete

def get_pp_loc_part1(cell, kpts=None) -> None: ...
def get_gth_vlocG_part1(cell, Gv): ...
def get_pp_loc_part2(cell, kpts=None): ...
def get_pp_loc_part2_gamma(cell): ...
def vpploc_part2_nuc_grad(cell, dm, kpts=None): ...
def get_pp_nl(cell, kpts=None): ...
def vppnl_nuc_grad(cell, dm, kpts=None): ...
def fake_cell_vloc(cell, cn: int = 0, atm_id=None): ...
def fake_cell_vnl(cell): ...
