from pyscf.pbc import gto as gto
from pyscf.pbc.scf import addons as addons, ghf as ghf, hf as hf, kghf as kghf, kghf_ksymm as kghf_ksymm, khf as khf, khf_ksymm as khf_ksymm, krohf as krohf, kuhf as kuhf, kuhf_ksymm as kuhf_ksymm, newton_ah as newton_ah, rohf as rohf, uhf as uhf
from pyscf.pbc.dft.krks import KRKS
from pyscf.pbc.dft.krks_ksymm import KsymAdaptedKRKS
from pyscf.pbc.dft.kroks import KROKS
from pyscf.pbc.dft.kuks import KUKS
from pyscf.pbc.dft.kuks_ksymm import KsymAdaptedKUKS
from pyscf.pbc.dft.rks import RKS
from pyscf.pbc.dft.roks import ROKS
from pyscf.pbc.dft.uks import UKS
from pyscf.pbc.gto.cell import Cell
from pyscf.pbc.scf.ghf import GHF
from pyscf.pbc.scf.hf import RHF
from pyscf.pbc.scf.kghf import KGHF
from pyscf.pbc.scf.kghf_ksymm import KsymAdaptedKGHF
from pyscf.pbc.scf.khf import KRHF
from pyscf.pbc.scf.khf_ksymm import KsymAdaptedKRHF
from pyscf.pbc.scf.kuhf import KUHF
from pyscf.pbc.scf.kuhf_ksymm import KsymAdaptedKUHF
from pyscf.pbc.scf.rohf import ROHF
from pyscf.pbc.scf.uhf import UHF
from typing import Union

rhf = hf
krhf = khf

def RHF(cell: Cell, *args, **kwargs) -> Union[RHF, ROHF]: ...
def UHF(cell: Cell, *args, **kwargs) -> UHF: ...
def GHF(cell: Cell, *args, **kwargs) -> GHF: ...
def ROHF(cell: Cell, *args, **kwargs) -> ROHF: ...
def KRHF(cell: Cell, *args, **kwargs) -> Union[KsymAdaptedKRHF, KRHF]: ...
def KUHF(cell: Cell, *args, **kwargs) -> Union[KsymAdaptedKUHF, KUHF]: ...
KROHF = krohf.KROHF

def KGHF(cell: Cell, *args, **kwargs) -> Union[KGHF, KsymAdaptedKGHF]: ...
newton = newton_ah.newton

def HF(cell: Cell, *args, **kwargs) -> Union[RHF, UHF]: ...
def KHF(cell: Cell, *args, **kwargs) -> Union[KsymAdaptedKRHF, KUHF, KRHF]: ...
def KS(cell: Cell, *args, **kwargs) -> Union[UKS, RKS]: ...
def KKS(cell: Cell, *args, **kwargs) -> Union[KRKS, KUKS]: ...
def RKS(cell: Cell, *args, **kwargs) -> Union[RKS, ROKS]: ...
def ROKS(cell: Cell, *args, **kwargs) -> ROKS: ...
def UKS(cell: Cell, *args, **kwargs) -> UKS: ...
def KRKS(cell: Cell, *args, **kwargs) -> Union[KsymAdaptedKRKS, KRKS]: ...
def KROKS(cell: Cell, *args, **kwargs) -> KROKS: ...
def KUKS(cell: Cell, *args, **kwargs) -> Union[KUKS, KsymAdaptedKUKS]: ...
