from pyscf.pbc import gto as gto
from pyscf.pbc.scf import addons as addons, ghf as ghf, hf as hf, kghf as kghf, kghf_ksymm as kghf_ksymm, khf as khf, khf_ksymm as khf_ksymm, krohf as krohf, kuhf as kuhf, kuhf_ksymm as kuhf_ksymm, newton_ah as newton_ah, rohf as rohf, uhf as uhf

rhf = hf
krhf = khf

def RHF(cell, *args, **kwargs): ...
def UHF(cell, *args, **kwargs): ...
def GHF(cell, *args, **kwargs): ...
def ROHF(cell, *args, **kwargs): ...
def KRHF(cell, *args, **kwargs): ...
def KUHF(cell, *args, **kwargs): ...
KROHF = krohf.KROHF

def KGHF(cell, *args, **kwargs): ...
newton = newton_ah.newton

def HF(cell, *args, **kwargs): ...
def KHF(cell, *args, **kwargs): ...
def KS(cell, *args, **kwargs): ...
def KKS(cell, *args, **kwargs): ...
def RKS(cell, *args, **kwargs): ...
def ROKS(cell, *args, **kwargs): ...
def UKS(cell, *args, **kwargs): ...
def KRKS(cell, *args, **kwargs): ...
def KROKS(cell, *args, **kwargs): ...
def KUKS(cell, *args, **kwargs): ...
