from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc.scf.smearing import SMEARING_METHOD as SMEARING_METHOD, smearing as smearing, smearing_ as smearing_
from pyscf.pbc.tools import k2gamma as k2gamma

def project_mo_nr2nr(cell1, mo1, cell2, kpts=None): ...
def project_dm_k2k(cell, dm, kpts1, kpts2): ...
def canonical_occ_(mf, nelec=None): ...
canonical_occ = canonical_occ_

def convert_to_uhf(mf, out=None): ...
def convert_to_rhf(mf, out=None): ...
def convert_to_ghf(mf, out=None): ...
def convert_to_kscf(mf, out=None): ...
convert_to_khf = convert_to_kscf

def mo_energy_with_exxdiv_none(mf, mo_coeff=None): ...
