from pyscf import lib as lib
from pyscf.lib import logger as logger

def solve(fvind, mo_energy, mo_occ, h1, s1=None, max_cycle: int = 20, tol: float = 1e-09, hermi: bool = False, verbose=...): ...
kernel = solve

def solve_nos1(fvind, mo_energy, mo_occ, h1, max_cycle: int = 20, tol: float = 1e-09, hermi: bool = False, verbose=...): ...
def solve_withs1(fvind, mo_energy, mo_occ, h1, s1, max_cycle: int = 20, tol: float = 1e-09, hermi: bool = False, verbose=...): ...
