from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.data import nist as nist
from pyscf.lib import logger as logger
from pyscf.pbc import df as df, gto as gto, tools as tools
from pyscf.pbc.gto.pseudo import get_pp as get_pp
from pyscf.pbc.lib.kpts_helper import gamma_point as gamma_point
from pyscf.pbc.scf import addons as addons, smearing as smearing
from pyscf.pbc.scf.rsjk import RangeSeparatedJKBuilder as RangeSeparatedJKBuilder
from pyscf.scf import hf as mol_hf
from pyscf.soscf import newton_ah as newton_ah
from numpy import float64, ndarray
from pyscf.lib.logger import Logger
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.df.df import GDF
from pyscf.pbc.dft.gen_grid import UniformGrids
from pyscf.pbc.dft.gks import GKS
from pyscf.pbc.dft.krks import KRKS
from pyscf.pbc.dft.krks_ksymm import KsymAdaptedKRKS
from pyscf.pbc.dft.kuks import KUKS
from pyscf.pbc.dft.rks import RKS
from pyscf.pbc.gto.cell import Cell
from pyscf.pbc.scf.ghf import GHF
from pyscf.pbc.scf.kuhf import KUHF
from pyscf.pbc.scf.rohf import ROHF
from pyscf.pbc.scf.uhf import UHF
from typing import Any, Callable, Dict, List, Optional, Tuple, Union

INVALID_ORBITAL_ENERGY: float

def get_ovlp(cell: Cell, kpt: ndarray=...) -> ndarray: ...
def get_hcore(cell: Cell, kpt: ndarray=...) -> ndarray: ...
def get_t(cell, kpt=...): ...
def get_nuc(cell, kpt=...): ...
def get_j(cell, dm, hermi: int = 1, vhfopt=None, kpt=..., kpts_band=None): ...
def get_jk(mf: "RHF", cell: Cell, dm: ndarray, hermi: int = 1, vhfopt: None=None, kpt: ndarray=..., kpts_band: None=None, with_j: bool = True, with_k: bool = True, omega: None=None, **kwargs) -> Tuple[ndarray, ndarray]: ...
def get_bands(mf: "RHF", kpts_band: ndarray, cell: None=None, dm: None=None, kpt: None=None) -> Tuple[ndarray, ndarray]: ...
def init_guess_by_chkfile(cell: Cell, chkfile_name: str, project: None=None, kpt: Optional[ndarray]=None) -> ndarray: ...
get_fock = mol_hf.get_fock
get_occ = mol_hf.get_occ
get_grad = mol_hf.get_grad
make_rdm1 = mol_hf.make_rdm1
energy_elec = mol_hf.energy_elec

def eigh_with_canonical_orth(h: ndarray, s: ndarray) -> Tuple[ndarray, ndarray]: ...
def dip_moment(cell: Cell, dm: Union[ndarray, NPArrayWithTag], unit: str = 'Debye', verbose: Union[Logger, int]=..., grids: None=None, rho: Optional[ndarray]=None, kpt: ndarray=..., origin: None=None) -> ndarray: ...
def get_rho(mf: Union[UHF, RHF, ROHF], dm: Optional[NPArrayWithTag]=None, grids: Optional[UniformGrids]=None, kpt: None=None) -> ndarray: ...
def makov_payne_correction(mf: Union[KUKS, KUHF, RHF]) -> ndarray: ...
def gen_response(mf: "RHF", mo_coeff: Optional[ndarray]=None, mo_occ: Optional[ndarray]=None, singlet: Optional[bool]=None, hermi: int = 0, max_memory: Optional[float]=None, with_nlc: bool = True) -> Callable: ...

class SCF(mol_hf.SCF):
    init_direct_scf: Incomplete
    get_bands = get_bands
    get_rho = get_rho
    smearing = smearing.smearing
    with_df: Incomplete
    rsjk: Incomplete
    exxdiv: Incomplete
    conv_tol: Incomplete
    def __init__(self, cell: Cell, kpt: Optional[ndarray]=None, exxdiv: Optional[str]=...) -> None: ...
    @property
    def kpt(self): ...
    @kpt.setter
    def kpt(self, x) -> None: ...
    @property
    def kpts(self) -> ndarray: ...
    def build(self, cell: Optional[Cell]=None) -> Union[GHF, UHF, ROHF, RHF]: ...
    cell: Incomplete
    def reset(self, cell: Optional[Cell]=None) -> "SCF": ...
    @property
    def mol(self): ...
    @mol.setter
    def mol(self, x) -> None: ...
    def dump_flags(self, verbose: None=None) -> "SCF": ...
    def check_sanity(self) -> "SCF": ...
    def get_hcore(self, cell: Optional[Cell]=None, kpt: Optional[ndarray]=None) -> ndarray: ...
    def get_ovlp(self, cell: Optional[Cell]=None, kpt: Optional[ndarray]=None) -> ndarray: ...
    def get_jk(self, cell: Optional[Cell]=None, dm: Optional[Union[ndarray, List[ndarray], NPArrayWithTag]]=None, hermi: int = 1, kpt: Optional[ndarray]=None, kpts_band: Optional[ndarray]=None, with_j: bool = True, with_k: bool = True, omega: Optional[float]=None, **kwargs) -> Union[Tuple[ndarray, None], Tuple[ndarray, ndarray], Tuple[None, ndarray]]: ...
    def get_j(self, cell: Optional[Cell]=None, dm: Optional[Union[ndarray, NPArrayWithTag]]=None, hermi: int = 1, kpt: Optional[ndarray]=None, kpts_band: None=None, omega: None=None) -> ndarray: ...
    def get_k(self, cell: Optional[Cell]=None, dm: Optional[Union[ndarray, NPArrayWithTag]]=None, hermi: int = 1, kpt: Optional[ndarray]=None, kpts_band: None=None, omega: Optional[float]=None) -> ndarray: ...
    def get_veff(self, cell: Optional[Cell]=None, dm: Optional[Union[ndarray, NPArrayWithTag]]=None, dm_last: Union[ndarray, int, NPArrayWithTag] = 0, vhf_last: Union[ndarray, int] = 0, hermi: int = 1, kpt: Optional[ndarray]=None, kpts_band: Optional[ndarray]=None) -> ndarray: ...
    def get_jk_incore(self, cell: Optional[Cell]=None, dm: Optional[ndarray]=None, hermi: int = 1, kpt: None=None, omega: None=None, **kwargs) -> Tuple[ndarray, ndarray]: ...
    def energy_nuc(self) -> Union[int, float64]: ...
    def dip_moment(self, cell: Optional[Cell]=None, dm: Optional[NPArrayWithTag]=None, unit: str = 'Debye', verbose: Union[Logger, int]=..., **kwargs) -> ndarray: ...
    def get_init_guess(self, cell: Optional[Cell]=None, key: str = 'minao', s1e: Optional[ndarray]=None) -> Union[ndarray, NPArrayWithTag]: ...
    def init_guess_by_1e(self, cell: Optional[Cell]=None) -> NPArrayWithTag: ...
    def init_guess_by_chkfile(self, chk: Optional[str]=None, project: None=None, kpt: None=None) -> ndarray: ...
    def from_chk(self, chk: Optional[str]=None, project: None=None, kpt: None=None) -> ndarray: ...
    def dump_chk(self, envs_or_file: Dict[str, Any]) -> "SCF": ...
    def analyze(self, verbose=None, with_meta_lowdin=None, **kwargs) -> None: ...
    def mulliken_pop(self) -> None: ...
    def density_fit(self, auxbasis: Optional[Union[Dict[str, List[List[Union[int, List[Union[float64, int]]]]]], str]]=None, with_df: Optional[GDF]=None) -> "SCF": ...
    def rs_density_fit(self, auxbasis: Optional[str]=None, with_df: None=None) -> "SCF": ...
    def mix_density_fit(self, auxbasis: Optional[str]=None, with_df: None=None) -> Union[RKS, KRKS, UHF, KsymAdaptedKRKS, RHF]: ...
    def multigrid_numint(self, mesh=None) -> None: ...
    def sfx2c1e(self): ...
    x2c = sfx2c1e
    x2c1e = sfx2c1e
    def to_rhf(self) -> "RHF": ...
    def to_uhf(self) -> UHF: ...
    def to_ghf(self) -> GHF: ...
    def to_kscf(self): ...
    def jk_method(self, J: str = 'FFTDF', K: Optional[str]=None) -> "SCF": ...
    def to_gpu(self) -> None: ...
    def Gradients(self) -> None: ...
    def nuc_grad_method(self) -> Union[Incomplete, Incomplete, Incomplete, Incomplete]: ...
    def gen_response(mf, mo_coeff=None, mo_occ=None, **kwargs) -> None: ...

class KohnShamDFT: ...

class RHF(SCF):
    analyze: Incomplete
    spin_square: Incomplete
    stability: Incomplete
    gen_response = gen_response
    to_gpu = lib.to_gpu
    def get_fermi(self): ...
    def to_ks(self, xc: str = 'HF'): ...
    def convert_from_(self, mf: Union[UHF, ROHF, KUHF, RHF]) -> Union[ROHF, RHF]: ...
    def Gradients(self): ...

def normalize_dm_(mf: Union[GHF, GKS, RKS, RHF], dm: Union[ndarray, NPArrayWithTag], s1e: Optional[ndarray]=None) -> Union[ndarray, NPArrayWithTag]: ...
