import pyscf.scf.ghf as mol_ghf
from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc.scf import addons as addons, khf as khf

WITH_META_LOWDIN: Incomplete
PRE_ORTH_METHOD: Incomplete

def get_jk(mf, cell=None, dm_kpts=None, hermi: int = 0, kpts=None, kpts_band=None, with_j: bool = True, with_k: bool = True, **kwargs): ...
def get_occ(mf, mo_energy_kpts=None, mo_coeff_kpts=None): ...
def mulliken_meta(cell, dm_ao_kpts, kpts, verbose=..., pre_orth_method=..., s=None): ...

class KGHF(khf.KSCF):
    with_soc: Incomplete
    def __init__(self, cell, kpts=None, exxdiv=...) -> None: ...
    get_init_guess: Incomplete
    init_guess_by_minao: Incomplete
    init_guess_by_atom: Incomplete
    init_guess_by_chkfile = mol_ghf.init_guess_by_chkfile
    get_jk = get_jk
    get_occ = get_occ
    analyze = khf.analyze
    convert_from_: Incomplete
    gen_response = NotImplemented
    to_gpu = lib.to_gpu
    def get_hcore(self, cell=None, kpts=None): ...
    def get_ovlp(self, cell=None, kpts=None): ...
    def get_j(self, cell=None, dm_kpts=None, hermi: int = 0, kpts=None, kpts_band=None): ...
    def get_k(self, cell=None, dm_kpts=None, hermi: int = 0, kpts=None, kpts_band=None): ...
    def get_veff(self, cell=None, dm_kpts=None, dm_last: int = 0, vhf_last: int = 0, hermi: int = 1, kpts=None, kpts_band=None): ...
    def get_grad(self, mo_coeff_kpts, mo_occ_kpts, fock=None): ...
    def get_bands(self, kpts_band, cell=None, dm_kpts=None, kpts=None) -> None: ...
    def mulliken_meta(self, cell=None, dm=None, kpts=None, verbose=..., pre_orth_method=..., s=None): ...
    def mulliken_pop(self) -> None: ...
    def x2c1e(self): ...
    x2c = x2c1e
    def to_ks(self, xc: str = 'HF'): ...
