import pyscf.scf.ghf as mol_ghf
from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc.scf import addons as addons, khf as khf
from numpy import ndarray
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.dft.kgks import KGKS
from pyscf.pbc.gto.cell import Cell
from pyscf.pbc.lib.kpts import KPoints
from typing import Callable, List, Optional, Tuple, Union

WITH_META_LOWDIN: Incomplete
PRE_ORTH_METHOD: Incomplete

def get_jk(mf: Union[KGKS, KGHF], cell: Optional[Cell]=None, dm_kpts: Optional[Union[NPArrayWithTag, ndarray]]=None, hermi: int = 0, kpts: Optional[ndarray]=None, kpts_band: None=None, with_j: bool = True, with_k: bool = True, **kwargs) -> Union[Tuple[ndarray, ndarray], Tuple[ndarray, None]]: ...
def get_occ(mf: Union[KGKS, KGHF], mo_energy_kpts: Optional[ndarray]=None, mo_coeff_kpts: Optional[ndarray]=None) -> List[ndarray]: ...
def mulliken_meta(cell: Cell, dm_ao_kpts: NPArrayWithTag, kpts: ndarray, verbose: int=..., pre_orth_method: str=..., s: Optional[ndarray]=None) -> Tuple[Tuple[ndarray, ndarray], ndarray]: ...

class KGHF(khf.KSCF):
    with_soc: Incomplete
    def __init__(self, cell: Cell, kpts: Optional[Union[KPoints, List[List[int]], ndarray]]=None, exxdiv: Optional[str]=...) -> None: ...
    get_init_guess: Incomplete
    init_guess_by_minao: Incomplete
    init_guess_by_atom: Incomplete
    init_guess_by_chkfile = mol_ghf.init_guess_by_chkfile
    get_jk = get_jk
    get_occ = get_occ
    analyze = khf.analyze
    convert_from_: Incomplete
    gen_response = NotImplemented
    to_gpu = lib.to_gpu
    def get_hcore(self, cell: Optional[Cell]=None, kpts: None=None) -> ndarray: ...
    def get_ovlp(self, cell: Optional[Cell]=None, kpts: None=None) -> ndarray: ...
    def get_j(self, cell: Optional[Cell]=None, dm_kpts: Optional[Union[ndarray, NPArrayWithTag]]=None, hermi: int = 0, kpts: Optional[ndarray]=None, kpts_band: None=None) -> ndarray: ...
    def get_k(self, cell=None, dm_kpts=None, hermi: int = 0, kpts=None, kpts_band=None): ...
    def get_veff(self, cell: Optional[Cell]=None, dm_kpts: Optional[Union[ndarray, NPArrayWithTag]]=None, dm_last: Union[ndarray, int, NPArrayWithTag] = 0, vhf_last: Union[ndarray, int] = 0, hermi: int = 1, kpts: None=None, kpts_band: None=None) -> ndarray: ...
    def get_grad(self, mo_coeff_kpts: ndarray, mo_occ_kpts: List[ndarray], fock: Optional[ndarray]=None) -> ndarray: ...
    def get_bands(self, kpts_band, cell=None, dm_kpts=None, kpts=None) -> None: ...
    def mulliken_meta(self, cell: Optional[Cell]=None, dm: Optional[NPArrayWithTag]=None, kpts: Optional[ndarray]=None, verbose: int=..., pre_orth_method: str=..., s: Optional[ndarray]=None) -> Tuple[Tuple[ndarray, ndarray], ndarray]: ...
    def mulliken_pop(self) -> None: ...
    def x2c1e(self): ...
    x2c = x2c1e
    def to_ks(self, xc: str = 'HF'): ...
