from _typeshed import Incomplete
from functools import reduce as reduce
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc import df as df, tools as tools
from pyscf.pbc.lib.kpts import KPoints as KPoints
from pyscf.pbc.lib.kpts_helper import is_trim as is_trim
from pyscf.pbc.scf import addons as addons, chkfile as chkfile, hf as pbchf, smearing as smearing
from pyscf.pbc.scf.rsjk import RangeSeparatedJKBuilder as RangeSeparatedJKBuilder

WITH_META_LOWDIN: Incomplete
PRE_ORTH_METHOD: Incomplete
CHECK_COULOMB_IMAG: Incomplete

def get_ovlp(mf, cell=None, kpts=None): ...
def get_hcore(mf, cell=None, kpts=None): ...
def get_j(mf, cell, dm_kpts, kpts, kpts_band=None): ...
def get_jk(mf, cell, dm_kpts, kpts, kpts_band=None, with_j: bool = True, with_k: bool = True, omega=None, **kwargs): ...
def get_fock(mf, h1e=None, s1e=None, vhf=None, dm=None, cycle: int = -1, diis=None, diis_start_cycle=None, level_shift_factor=None, damp_factor=None, fock_last=None): ...
def get_fermi(mf, mo_energy_kpts=None, mo_occ_kpts=None): ...
def get_occ(mf, mo_energy_kpts=None, mo_coeff_kpts=None): ...
def get_grad(mo_coeff_kpts, mo_occ_kpts, fock): ...
def make_rdm1(mo_coeff_kpts, mo_occ_kpts, **kwargs): ...
def energy_elec(mf, dm_kpts=None, h1e_kpts=None, vhf_kpts=None): ...
def analyze(mf, verbose=None, with_meta_lowdin=..., **kwargs): ...
def mulliken_meta(cell, dm_ao_kpts, kpts, verbose=..., pre_orth_method=..., s=None): ...
def canonicalize(mf, mo_coeff_kpts, mo_occ_kpts, fock=None): ...
def init_guess_by_minao(cell, kpts=None): ...
def init_guess_by_atom(cell, kpts=None): ...
def init_guess_by_chkfile(cell, chkfile_name, project=None, kpts=None): ...
def dip_moment(cell, dm_kpts, unit: str = 'Debye', verbose=..., grids=None, rho=None, kpts=...): ...
def get_rho(mf, dm=None, grids=None, kpts=None): ...
def gen_response(mf, mo_coeff=None, mo_occ=None, singlet=None, hermi: int = 0, max_memory=None, with_nlc: bool = True): ...

class KSCF(pbchf.SCF):
    conv_tol_grad: Incomplete
    mol: Incomplete
    check_sanity: Incomplete
    init_direct_scf: Incomplete
    get_hcore = get_hcore
    get_ovlp = get_ovlp
    get_fock = get_fock
    get_fermi = get_fermi
    get_occ = get_occ
    get_jk_incore: Incomplete
    energy_elec = energy_elec
    energy_nuc: Incomplete
    get_rho = get_rho
    init_guess_by_minao: Incomplete
    init_guess_by_atom: Incomplete
    canonicalize = canonicalize
    smearing = smearing.smearing
    with_df: Incomplete
    rsjk: Incomplete
    exxdiv: Incomplete
    conv_tol: Incomplete
    exx_built: bool
    def __init__(self, cell, kpts=None, exxdiv=...) -> None: ...
    @property
    def mo_energy_kpts(self): ...
    @property
    def mo_coeff_kpts(self): ...
    @property
    def mo_occ_kpts(self): ...
    @property
    def kpts(self): ...
    @kpts.setter
    def kpts(self, x) -> None: ...
    @property
    def kmesh(self): ...
    @kmesh.setter
    def kmesh(self, x) -> None: ...
    def build(self, cell=None): ...
    def reset(self, cell=None): ...
    def dump_flags(self, verbose=None): ...
    def get_init_guess(self, cell=None, key: str = 'minao', s1e=None) -> None: ...
    def init_guess_by_1e(self, cell=None): ...
    def get_j(self, cell=None, dm_kpts=None, hermi: int = 1, kpts=None, kpts_band=None, omega=None): ...
    def get_k(self, cell=None, dm_kpts=None, hermi: int = 1, kpts=None, kpts_band=None, omega=None): ...
    def get_jk(self, cell=None, dm_kpts=None, hermi: int = 1, kpts=None, kpts_band=None, with_j: bool = True, with_k: bool = True, omega=None, **kwargs): ...
    def get_veff(self, cell=None, dm_kpts=None, dm_last: int = 0, vhf_last: int = 0, hermi: int = 1, kpts=None, kpts_band=None): ...
    def get_grad(self, mo_coeff_kpts, mo_occ_kpts, fock=None): ...
    def check_linear_dependency(self, s, verbose=None): ...
    def eig(self, h_kpts, s_kpts, overwrite: bool = False, x=None): ...
    def make_rdm1(self, mo_coeff_kpts=None, mo_occ_kpts=None, **kwargs): ...
    def make_rdm2(self, mo_coeff_kpts, mo_occ_kpts, **kwargs) -> None: ...
    def get_bands(self, kpts_band, cell=None, dm_kpts=None, kpts=None): ...
    def init_guess_by_chkfile(self, chk=None, project=None, kpts=None): ...
    def from_chk(self, chk=None, project=None, kpts=None): ...
    def dump_chk(self, envs_or_file): ...
    def analyze(mf, verbose=None, with_meta_lowdin=..., **kwargs) -> None: ...
    def mulliken_meta(self, cell=None, dm=None, kpts=None, verbose=..., pre_orth_method=..., s=None) -> None: ...
    def mulliken_pop(self) -> None: ...
    def dip_moment(self, cell=None, dm=None, unit: str = 'Debye', verbose=..., **kwargs): ...
    def density_fit(self, auxbasis=None, with_df=None): ...
    def rs_density_fit(self, auxbasis=None, with_df=None): ...
    def mix_density_fit(self, auxbasis=None, with_df=None): ...
    def newton(self): ...
    def sfx2c1e(self): ...
    x2c = sfx2c1e
    x2c1e = sfx2c1e
    def to_rhf(self): ...
    def to_uhf(self): ...
    def to_ghf(self): ...
    def to_kscf(self): ...
    def to_khf(self): ...
    def convert_from_(self, mf) -> None: ...

class KRHF(KSCF):
    analyze = analyze
    spin_square: Incomplete
    gen_response = gen_response
    to_gpu = lib.to_gpu
    def check_sanity(self): ...
    def get_init_guess(self, cell=None, key: str = 'minao', s1e=None): ...
    def mulliken_meta(self, cell=None, dm=None, kpts=None, verbose=..., pre_orth_method=..., s=None): ...
    def Gradients(self): ...
    def stability(self, internal=..., external=..., verbose=None, return_status: bool = False): ...
    def to_ks(self, xc: str = 'HF'): ...
    def convert_from_(self, mf): ...
