from _typeshed import Incomplete
from functools import reduce as reduce
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc import df as df, tools as tools
from pyscf.pbc.lib.kpts import KPoints, KPoints as KPoints
from pyscf.pbc.lib.kpts_helper import is_trim as is_trim
from pyscf.pbc.scf import addons as addons, chkfile as chkfile, hf as pbchf, smearing as smearing
from pyscf.pbc.scf.rsjk import RangeSeparatedJKBuilder as RangeSeparatedJKBuilder
from numpy import float64, int64, ndarray
from pyscf.lib.logger import Logger
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.dft.gen_grid import UniformGrids
from pyscf.pbc.dft.krks import KRKS
from pyscf.pbc.dft.krks_ksymm import KsymAdaptedKRKS
from pyscf.pbc.dft.krkspu import KRKSpU
from pyscf.pbc.grad.krhf import Gradients
from pyscf.pbc.gto.cell import Cell
from pyscf.pbc.scf.hf import SCF
from pyscf.pbc.scf.kghf import KGHF
from pyscf.pbc.scf.khf_ksymm import KsymAdaptedKRHF
from pyscf.pbc.scf.krohf import KROHF
from pyscf.pbc.scf.kuhf import KUHF
from pyscf.pbc.scf.kuhf_ksymm import KsymAdaptedKUHF
from pyscf.scf.diis import CDIIS
from typing import Any, Callable, Dict, List, Optional, Tuple, Union

WITH_META_LOWDIN: Incomplete
PRE_ORTH_METHOD: Incomplete
CHECK_COULOMB_IMAG: Incomplete

def get_ovlp(mf: "KSCF", cell: Optional[Cell]=None, kpts: Optional[ndarray]=None) -> ndarray: ...
def get_hcore(mf: "KSCF", cell: Optional[Cell]=None, kpts: Optional[Union[List[ndarray], ndarray]]=None) -> ndarray: ...
def get_j(mf, cell, dm_kpts, kpts, kpts_band=None): ...
def get_jk(mf, cell, dm_kpts, kpts, kpts_band=None, with_j: bool = True, with_k: bool = True, omega=None, **kwargs): ...
def get_fock(mf: "KSCF", h1e: Optional[Union[ndarray, int]]=None, s1e: Optional[Union[ndarray, int]]=None, vhf: Optional[Union[ndarray, NPArrayWithTag]]=None, dm: Optional[Union[ndarray, NPArrayWithTag, int]]=None, cycle: int = -1, diis: Optional[CDIIS]=None, diis_start_cycle: Optional[int]=None, level_shift_factor: Optional[int]=None, damp_factor: Optional[float]=None, fock_last: Optional[ndarray]=None) -> ndarray: ...
def get_fermi(mf: Union[KsymAdaptedKRKS, KRHF], mo_energy_kpts: Optional[List[ndarray]]=None, mo_occ_kpts: Optional[List[ndarray]]=None) -> Union[int64, float64]: ...
def get_occ(mf: Union[KRKSpU, KRHF, KRKS], mo_energy_kpts: Optional[ndarray]=None, mo_coeff_kpts: Optional[ndarray]=None) -> ndarray: ...
def get_grad(mo_coeff_kpts: Union[ndarray, List[NPArrayWithTag]], mo_occ_kpts: ndarray, fock: ndarray) -> ndarray: ...
def make_rdm1(mo_coeff_kpts: Union[List[NPArrayWithTag], List[ndarray], ndarray], mo_occ_kpts: Union[ndarray, List[ndarray]], **kwargs) -> NPArrayWithTag: ...
def energy_elec(mf: Union[KRHF, KGHF], dm_kpts: Optional[Union[ndarray, NPArrayWithTag]]=None, h1e_kpts: Optional[ndarray]=None, vhf_kpts: Optional[ndarray]=None) -> Tuple[float64, float64]: ...
def analyze(mf: Union[KROHF, KRHF, KUHF, KGHF], verbose: None=None, with_meta_lowdin: bool=..., **kwargs) -> Union[Tuple[Tuple[ndarray, ndarray], None], Tuple[Tuple[Tuple[ndarray, ndarray], ndarray], None]]: ...
def mulliken_meta(cell: Cell, dm_ao_kpts: Union[ndarray, NPArrayWithTag], kpts: ndarray, verbose: int=..., pre_orth_method: str=..., s: Optional[ndarray]=None) -> Tuple[ndarray, ndarray]: ...
def canonicalize(mf: "KSCF", mo_coeff_kpts: ndarray, mo_occ_kpts: ndarray, fock: Optional[ndarray]=None) -> Tuple[ndarray, ndarray]: ...
def init_guess_by_minao(cell, kpts=None): ...
def init_guess_by_atom(cell, kpts=None): ...
def init_guess_by_chkfile(cell: Cell, chkfile_name: str, project: None=None, kpts: Optional[ndarray]=None) -> ndarray: ...
def dip_moment(cell, dm_kpts, unit: str = 'Debye', verbose=..., grids=None, rho=None, kpts=...): ...
def get_rho(mf: Union[KRKS, KsymAdaptedKRHF, KRHF, KsymAdaptedKUHF, KUHF], dm: Optional[NPArrayWithTag]=None, grids: Optional[UniformGrids]=None, kpts: Optional[ndarray]=None) -> ndarray: ...
def gen_response(mf: "KRHF", mo_coeff: Optional[ndarray]=None, mo_occ: Optional[ndarray]=None, singlet: Optional[bool]=None, hermi: int = 0, max_memory: Optional[float]=None, with_nlc: bool = True) -> Callable: ...

class KSCF(pbchf.SCF):
    conv_tol_grad: Incomplete
    mol: Incomplete
    check_sanity: Incomplete
    init_direct_scf: Incomplete
    get_hcore = get_hcore
    get_ovlp = get_ovlp
    get_fock = get_fock
    get_fermi = get_fermi
    get_occ = get_occ
    get_jk_incore: Incomplete
    energy_elec = energy_elec
    energy_nuc: Incomplete
    get_rho = get_rho
    init_guess_by_minao: Incomplete
    init_guess_by_atom: Incomplete
    canonicalize = canonicalize
    smearing = smearing.smearing
    with_df: Incomplete
    rsjk: Incomplete
    exxdiv: Incomplete
    conv_tol: Incomplete
    exx_built: bool
    def __init__(self, cell: Cell, kpts: Optional[Any]=None, exxdiv: Optional[str]=...) -> None: ...
    @property
    def mo_energy_kpts(self): ...
    @property
    def mo_coeff_kpts(self): ...
    @property
    def mo_occ_kpts(self): ...
    @property
    def kpts(self): ...
    @kpts.setter
    def kpts(self, x) -> None: ...
    @property
    def kmesh(self): ...
    @kmesh.setter
    def kmesh(self, x) -> None: ...
    def build(self, cell: Optional[Cell]=None) -> "KSCF": ...
    def reset(self, cell: Optional[Cell]=None) -> "KSCF": ...
    def dump_flags(self, verbose: None=None) -> "KSCF": ...
    def get_init_guess(self, cell=None, key: str = 'minao', s1e=None) -> None: ...
    def init_guess_by_1e(self, cell: Optional[Cell]=None) -> NPArrayWithTag: ...
    def get_j(self, cell: Optional[Cell]=None, dm_kpts: Optional[Union[ndarray, NPArrayWithTag]]=None, hermi: int = 1, kpts: Optional[Union[ndarray, KPoints]]=None, kpts_band: Optional[ndarray]=None, omega: None=None) -> ndarray: ...
    def get_k(self, cell: Optional[Cell]=None, dm_kpts: Optional[Union[ndarray, NPArrayWithTag]]=None, hermi: int = 1, kpts: Optional[Union[ndarray, KPoints]]=None, kpts_band: Optional[ndarray]=None, omega: Optional[float]=None) -> ndarray: ...
    def get_jk(self, cell: Optional[Cell]=None, dm_kpts: Optional[Union[ndarray, NPArrayWithTag]]=None, hermi: int = 1, kpts: Optional[ndarray]=None, kpts_band: Optional[ndarray]=None, with_j: bool = True, with_k: bool = True, omega: Optional[float]=None, **kwargs) -> Union[Tuple[ndarray, ndarray], Tuple[None, ndarray], Tuple[ndarray, None]]: ...
    def get_veff(self, cell: Optional[Cell]=None, dm_kpts: Optional[Union[ndarray, NPArrayWithTag]]=None, dm_last: Union[ndarray, int, NPArrayWithTag] = 0, vhf_last: Union[ndarray, int] = 0, hermi: int = 1, kpts: Optional[ndarray]=None, kpts_band: Optional[ndarray]=None) -> ndarray: ...
    def get_grad(self, mo_coeff_kpts: Union[ndarray, List[NPArrayWithTag]], mo_occ_kpts: ndarray, fock: Optional[ndarray]=None) -> ndarray: ...
    def check_linear_dependency(self, s: ndarray, verbose: Optional[Logger]=None) -> List[ndarray]: ...
    def eig(self, h_kpts: Union[ndarray, NPArrayWithTag], s_kpts: Union[ndarray, List[ndarray]], overwrite: bool = False, x: Optional[Union[List[ndarray], List[NPArrayWithTag]]]=None) -> Tuple[ndarray, ndarray]: ...
    def make_rdm1(self, mo_coeff_kpts: Optional[Union[List[NPArrayWithTag], List[ndarray], ndarray]]=None, mo_occ_kpts: Optional[Union[ndarray, List[ndarray]]]=None, **kwargs) -> NPArrayWithTag: ...
    def make_rdm2(self, mo_coeff_kpts, mo_occ_kpts, **kwargs) -> None: ...
    def get_bands(self, kpts_band: ndarray, cell: None=None, dm_kpts: None=None, kpts: Optional[KPoints]=None) -> Tuple[ndarray, ndarray]: ...
    def init_guess_by_chkfile(self, chk: Optional[str]=None, project: None=None, kpts: Optional[ndarray]=None) -> ndarray: ...
    def from_chk(self, chk: Optional[str]=None, project: None=None, kpts: None=None) -> ndarray: ...
    def dump_chk(self, envs_or_file: Dict[str, Any]) -> "KSCF": ...
    def analyze(mf, verbose=None, with_meta_lowdin=..., **kwargs) -> None: ...
    def mulliken_meta(self, cell=None, dm=None, kpts=None, verbose=..., pre_orth_method=..., s=None) -> None: ...
    def mulliken_pop(self) -> None: ...
    def dip_moment(self, cell=None, dm=None, unit: str = 'Debye', verbose=..., **kwargs): ...
    def density_fit(self, auxbasis: Optional[Union[List[List[Union[int, Tuple[float, float]]]], Dict[str, List[List[Union[int, List[Union[float64, int]]]]]]]]=None, with_df: None=None) -> "KSCF": ...
    def rs_density_fit(self, auxbasis: Optional[str]=None, with_df: None=None) -> Union[KRHF, KUHF]: ...
    def mix_density_fit(self, auxbasis: None=None, with_df: None=None) -> Union[KsymAdaptedKRHF, KRHF, KsymAdaptedKUHF, KUHF, KROHF]: ...
    def newton(self): ...
    def sfx2c1e(self): ...
    x2c = sfx2c1e
    x2c1e = sfx2c1e
    def to_rhf(self) -> Union[KsymAdaptedKRHF, KRHF]: ...
    def to_uhf(self) -> Union[KsymAdaptedKUHF, KUHF]: ...
    def to_ghf(self) -> KGHF: ...
    def to_kscf(self): ...
    def to_khf(self) -> "KRHF": ...
    def convert_from_(self, mf) -> None: ...

class KRHF(KSCF):
    analyze = analyze
    spin_square: Incomplete
    gen_response = gen_response
    to_gpu = lib.to_gpu
    def check_sanity(self) -> "KRHF": ...
    def get_init_guess(self, cell: Optional[Cell]=None, key: str = 'minao', s1e: Optional[ndarray]=None) -> Union[ndarray, NPArrayWithTag]: ...
    def mulliken_meta(self, cell: Optional[Cell]=None, dm: Optional[NPArrayWithTag]=None, kpts: Optional[ndarray]=None, verbose: int=..., pre_orth_method: str=..., s: Optional[ndarray]=None) -> Tuple[ndarray, ndarray]: ...
    def Gradients(self) -> Gradients: ...
    def stability(self, internal: bool=..., external: bool=..., verbose: None=None, return_status: bool = False) -> Tuple[ndarray, Tuple[ndarray, ndarray]]: ...
    def to_ks(self, xc: str = 'HF'): ...
    def convert_from_(self, mf: SCF) -> Union[KsymAdaptedKRHF, KsymAdaptedKRKS, KRHF, KROHF]: ...
