from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc import tools as tools
from pyscf.pbc.lib.kpts_helper import is_trim as is_trim
from pyscf.pbc.scf import khf as khf
from pyscf.scf.hf_symm import so2ao_mo_coeff as so2ao_mo_coeff
from pyscf.symm import symmetrize_matrix as symmetrize_matrix

def get_occ(mf, mo_energy_kpts=None, mo_coeff_kpts=None): ...
def energy_elec(mf, dm_kpts=None, h1e_kpts=None, vhf_kpts=None): ...
def get_rho(mf, dm=None, grids=None, kpts=None): ...
def eig(kmf, h_kpts, s_kpts, overwrite: bool = False, x=None): ...
def eig_trs(kmf, h_kpts, s_kpts, overwrite: bool = False, x=None): ...
def ksymm_scf_common_init(kmf, cell, kpts, use_ao_symmetry: bool = True): ...

class KsymAdaptedKSCF(khf.KSCF):
    get_occ = get_occ
    get_rho = get_rho
    energy_elec = energy_elec
    def __init__(self, cell, kpts=..., exxdiv=..., use_ao_symmetry: bool = True) -> None: ...
    @property
    def kpts(self): ...
    @kpts.setter
    def kpts(self, kpts) -> None: ...
    @property
    def kmesh(self): ...
    @kmesh.setter
    def kmesh(self, x) -> None: ...
    def reset(self, cell=None): ...
    def dump_flags(self, verbose=None): ...
    def check_linear_dependency(self, s, verbose=None): ...
    def get_ovlp(self, cell=None, kpts=None): ...
    def get_hcore(self, cell=None, kpts=None): ...
    def get_jk(self, cell=None, dm_kpts=None, hermi: int = 1, kpts=None, kpts_band=None, with_j: bool = True, with_k: bool = True, omega=None, **kwargs): ...
    def init_guess_by_chkfile(self, chk=None, project=None, kpts=None): ...
    def dump_chk(self, envs): ...
    def eig(self, h_kpts, s_kpts, overwrite: bool = False, x=None): ...
    def get_orbsym(self, mo_coeff=None, s=None): ...
    orbsym: Incomplete
    def to_khf(self): ...
    def sfx2c1e(self) -> None: ...
    x2c = sfx2c1e
    x2c1e = sfx2c1e

class KsymAdaptedKRHF(KsymAdaptedKSCF, khf.KRHF):
    to_ks: Incomplete
    convert_from_: Incomplete
    def get_init_guess(self, cell=None, key: str = 'minao', s1e=None): ...
KRHF = KsymAdaptedKRHF
