from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc import tools as tools
from pyscf.pbc.lib.kpts_helper import is_trim as is_trim
from pyscf.pbc.scf import khf as khf
from pyscf.scf.hf_symm import so2ao_mo_coeff as so2ao_mo_coeff
from pyscf.symm import symmetrize_matrix as symmetrize_matrix
from numpy import float64, ndarray
from pyscf.lib.logger import Logger
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.dft.krks import KRKS
from pyscf.pbc.dft.krks_ksymm import KsymAdaptedKRKS
from pyscf.pbc.dft.krkspu_ksymm import KsymAdaptedKRKSpU
from pyscf.pbc.dft.kuks import KUKS
from pyscf.pbc.dft.kuks_ksymm import KsymAdaptedKUKS
from pyscf.pbc.gto.cell import Cell
from pyscf.pbc.lib.kpts import KPoints
from pyscf.pbc.scf.kghf import KGHF
from pyscf.pbc.scf.kghf_ksymm import KsymAdaptedKGHF
from pyscf.pbc.scf.khf import KRHF
from pyscf.pbc.scf.kuhf import KUHF
from pyscf.pbc.scf.kuhf_ksymm import KsymAdaptedKUHF
from typing import Any, Dict, List, Optional, Tuple, Union

def get_occ(mf: Union[KsymAdaptedKRKSpU, KsymAdaptedKRKS, KsymAdaptedKRHF], mo_energy_kpts: Optional[Union[ndarray, List[ndarray]]]=None, mo_coeff_kpts: Optional[Union[ndarray, List[NPArrayWithTag]]]=None) -> ndarray: ...
def energy_elec(mf: Union[KsymAdaptedKGHF, KsymAdaptedKRHF], dm_kpts: Optional[Union[ndarray, NPArrayWithTag]]=None, h1e_kpts: Optional[ndarray]=None, vhf_kpts: Optional[ndarray]=None) -> Tuple[float64, float64]: ...
def get_rho(mf: Union[KsymAdaptedKUHF, KsymAdaptedKRHF], dm: None=None, grids: None=None, kpts: None=None) -> ndarray: ...
def eig(kmf: Union[KsymAdaptedKRKS, KsymAdaptedKRHF], h_kpts: ndarray, s_kpts: ndarray, overwrite: bool = False, x: Optional[List[NPArrayWithTag]]=None) -> Tuple[List[ndarray], List[NPArrayWithTag]]: ...
def eig_trs(kmf: Union[KsymAdaptedKUKS, KsymAdaptedKRHF], h_kpts: ndarray, s_kpts: ndarray, overwrite: bool = False, x: Optional[List[ndarray]]=None) -> Tuple[ndarray, ndarray]: ...
def ksymm_scf_common_init(kmf: "KsymAdaptedKSCF", cell: Cell, kpts: KPoints, use_ao_symmetry: bool = True) -> "KsymAdaptedKSCF": ...

class KsymAdaptedKSCF(khf.KSCF):
    get_occ = get_occ
    get_rho = get_rho
    energy_elec = energy_elec
    def __init__(self, cell: Cell, kpts: KPoints=..., exxdiv: Optional[str]=..., use_ao_symmetry: bool = True) -> None: ...
    @property
    def kpts(self): ...
    @kpts.setter
    def kpts(self, kpts) -> None: ...
    @property
    def kmesh(self): ...
    @kmesh.setter
    def kmesh(self, x) -> None: ...
    def reset(self, cell: Optional[Cell]=None) -> Union[KsymAdaptedKRKS, KsymAdaptedKUKS, KsymAdaptedKRHF, KsymAdaptedKUHF, KsymAdaptedKGHF]: ...
    def dump_flags(self, verbose: None=None) -> "KsymAdaptedKSCF": ...
    def check_linear_dependency(self, s: ndarray, verbose: Optional[Logger]=None) -> List[Union[NPArrayWithTag, ndarray]]: ...
    def get_ovlp(self, cell: Optional[Cell]=None, kpts: Optional[ndarray]=None) -> ndarray: ...
    def get_hcore(self, cell: Optional[Cell]=None, kpts: Optional[ndarray]=None) -> ndarray: ...
    def get_jk(self, cell: Optional[Cell]=None, dm_kpts: Optional[Union[ndarray, NPArrayWithTag]]=None, hermi: int = 1, kpts: Optional[KPoints]=None, kpts_band: Optional[ndarray]=None, with_j: bool = True, with_k: bool = True, omega: Optional[float]=None, **kwargs) -> Union[Tuple[ndarray, ndarray], Tuple[ndarray, None], Tuple[None, ndarray]]: ...
    def init_guess_by_chkfile(self, chk: Optional[str]=None, project: None=None, kpts: None=None) -> ndarray: ...
    def dump_chk(self, envs: Dict[str, Any]) -> "KsymAdaptedKSCF": ...
    def eig(self, h_kpts: ndarray, s_kpts: ndarray, overwrite: bool = False, x: Optional[Union[List[NPArrayWithTag], List[ndarray]]]=None) -> Union[Tuple[ndarray, ndarray], Tuple[List[ndarray], List[NPArrayWithTag]]]: ...
    def get_orbsym(self, mo_coeff: None=None, s: None=None) -> List[ndarray]: ...
    orbsym: Incomplete
    def to_khf(self) -> Union[KUKS, KUHF, KRKS, KRHF, KGHF]: ...
    def sfx2c1e(self) -> None: ...
    x2c = sfx2c1e
    x2c1e = sfx2c1e

class KsymAdaptedKRHF(KsymAdaptedKSCF, khf.KRHF):
    to_ks: Incomplete
    convert_from_: Incomplete
    def get_init_guess(self, cell: Optional[Cell]=None, key: str = 'minao', s1e: Optional[ndarray]=None) -> ndarray: ...
KRHF = KsymAdaptedKRHF
