from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc.scf import addons as addons, khf as khf, kuhf as kuhf
from numpy import ndarray
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.gto.cell import Cell
from pyscf.scf.diis import CDIIS
from typing import List, Optional, Tuple, Union

PRE_ORTH_METHOD: Incomplete

def make_rdm1(mo_coeff_kpts: ndarray, mo_occ_kpts: ndarray, **kwargs) -> NPArrayWithTag: ...
def get_fock(mf: "KROHF", h1e: Optional[ndarray]=None, s1e: Optional[ndarray]=None, vhf: Optional[ndarray]=None, dm: Optional[Union[ndarray, NPArrayWithTag]]=None, cycle: int = -1, diis: Optional[CDIIS]=None, diis_start_cycle: None=None, level_shift_factor: Optional[int]=None, damp_factor: None=None, fock_last: Optional[NPArrayWithTag]=None) -> NPArrayWithTag: ...
def get_roothaan_fock(focka_fockb: Tuple[ndarray, ndarray], dma_dmb: Union[ndarray, NPArrayWithTag], s: ndarray) -> NPArrayWithTag: ...
def get_occ(mf: "KROHF", mo_energy_kpts: Optional[Union[ndarray, NPArrayWithTag]]=None, mo_coeff_kpts: Optional[ndarray]=None) -> ndarray: ...
energy_elec = kuhf.energy_elec
dip_moment = kuhf.dip_moment
get_rho: Incomplete

def mulliken_meta(cell: Cell, dm_ao_kpts: NPArrayWithTag, kpts: ndarray, verbose: int=..., pre_orth_method: str=..., s: Optional[ndarray]=None) -> Tuple[ndarray, ndarray]: ...
def canonicalize(mf: "KROHF", mo_coeff_kpts: ndarray, mo_occ_kpts: ndarray, fock: Optional[NPArrayWithTag]=None) -> Tuple[NPArrayWithTag, ndarray]: ...
init_guess_by_chkfile = kuhf.init_guess_by_chkfile

class KROHF(khf.KRHF):
    conv_tol_grad: Incomplete
    get_init_guess: Incomplete
    init_guess_by_minao: Incomplete
    init_guess_by_atom: Incomplete
    init_guess_by_huckel: Incomplete
    init_guess_by_mod_huckel: Incomplete
    get_fock = get_fock
    get_occ = get_occ
    energy_elec = energy_elec
    get_rho = get_rho
    analyze = khf.analyze
    spin_square: Incomplete
    canonicalize = canonicalize
    gen_response = kuhf.gen_response
    to_gpu = lib.to_gpu
    def __init__(self, cell: Cell, kpts: Optional[Union[List[List[float]], List[ndarray], ndarray]]=None, exxdiv: str=...) -> None: ...
    @property
    def nelec(self): ...
    @nelec.setter
    def nelec(self, x) -> None: ...
    def dump_flags(self, verbose: None=None) -> "KROHF": ...
    def get_veff(self, cell: Optional[Cell]=None, dm_kpts: Optional[Union[ndarray, NPArrayWithTag]]=None, dm_last: Union[ndarray, NPArrayWithTag, int] = 0, vhf_last: Union[ndarray, int] = 0, hermi: int = 1, kpts: None=None, kpts_band: None=None) -> ndarray: ...
    def get_grad(self, mo_coeff_kpts: ndarray, mo_occ_kpts: ndarray, fock: Optional[NPArrayWithTag]=None) -> ndarray: ...
    def eig(self, fock: Union[ndarray, NPArrayWithTag], s: ndarray, overwrite: bool = False, x: Optional[List[ndarray]]=None) -> Union[Tuple[ndarray, ndarray], Tuple[NPArrayWithTag, ndarray]]: ...
    def make_rdm1(self, mo_coeff_kpts: Optional[ndarray]=None, mo_occ_kpts: Optional[ndarray]=None, **kwargs) -> NPArrayWithTag: ...
    def init_guess_by_chkfile(self, chk=None, project: bool = True, kpts=None): ...
    def mulliken_meta(self, cell: Optional[Cell]=None, dm: Optional[NPArrayWithTag]=None, kpts: Optional[ndarray]=None, verbose: int=..., pre_orth_method: str=..., s: Optional[ndarray]=None) -> Tuple[ndarray, ndarray]: ...
    def stability(self, internal=..., external=..., verbose=None) -> None: ...
    def to_ks(self, xc: str = 'HF'): ...
