from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc.scf import addons as addons, khf as khf, kuhf as kuhf

PRE_ORTH_METHOD: Incomplete

def make_rdm1(mo_coeff_kpts, mo_occ_kpts, **kwargs): ...
def get_fock(mf, h1e=None, s1e=None, vhf=None, dm=None, cycle: int = -1, diis=None, diis_start_cycle=None, level_shift_factor=None, damp_factor=None, fock_last=None): ...
def get_roothaan_fock(focka_fockb, dma_dmb, s): ...
def get_occ(mf, mo_energy_kpts=None, mo_coeff_kpts=None): ...
energy_elec = kuhf.energy_elec
dip_moment = kuhf.dip_moment
get_rho: Incomplete

def mulliken_meta(cell, dm_ao_kpts, kpts, verbose=..., pre_orth_method=..., s=None): ...
def canonicalize(mf, mo_coeff_kpts, mo_occ_kpts, fock=None): ...
init_guess_by_chkfile = kuhf.init_guess_by_chkfile

class KROHF(khf.KRHF):
    conv_tol_grad: Incomplete
    get_init_guess: Incomplete
    init_guess_by_minao: Incomplete
    init_guess_by_atom: Incomplete
    init_guess_by_huckel: Incomplete
    init_guess_by_mod_huckel: Incomplete
    get_fock = get_fock
    get_occ = get_occ
    energy_elec = energy_elec
    get_rho = get_rho
    analyze = khf.analyze
    spin_square: Incomplete
    canonicalize = canonicalize
    gen_response = kuhf.gen_response
    to_gpu = lib.to_gpu
    def __init__(self, cell, kpts=None, exxdiv=...) -> None: ...
    @property
    def nelec(self): ...
    @nelec.setter
    def nelec(self, x) -> None: ...
    def dump_flags(self, verbose=None): ...
    def get_veff(self, cell=None, dm_kpts=None, dm_last: int = 0, vhf_last: int = 0, hermi: int = 1, kpts=None, kpts_band=None): ...
    def get_grad(self, mo_coeff_kpts, mo_occ_kpts, fock=None): ...
    def eig(self, fock, s, overwrite: bool = False, x=None): ...
    def make_rdm1(self, mo_coeff_kpts=None, mo_occ_kpts=None, **kwargs): ...
    def init_guess_by_chkfile(self, chk=None, project: bool = True, kpts=None): ...
    def mulliken_meta(self, cell=None, dm=None, kpts=None, verbose=..., pre_orth_method=..., s=None): ...
    def stability(self, internal=..., external=..., verbose=None) -> None: ...
    def to_ks(self, xc: str = 'HF'): ...
