from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc.scf import addons as addons, chkfile as chkfile, khf as khf

PRE_ORTH_METHOD: Incomplete
CHECK_COULOMB_IMAG: Incomplete
canonical_occ = addons.canonical_occ_
canonical_occ_ = addons.canonical_occ_

def make_rdm1(mo_coeff_kpts, mo_occ_kpts, **kwargs): ...
def get_fock(mf, h1e=None, s1e=None, vhf=None, dm=None, cycle: int = -1, diis=None, diis_start_cycle=None, level_shift_factor=None, damp_factor=None, fock_last=None): ...
def get_fermi(mf, mo_energy_kpts=None, mo_occ_kpts=None): ...
def get_occ(mf, mo_energy_kpts=None, mo_coeff_kpts=None): ...
def energy_elec(mf, dm_kpts=None, h1e_kpts=None, vhf_kpts=None): ...
def mulliken_meta(cell, dm_ao_kpts, kpts, verbose=..., pre_orth_method=..., s=None): ...
def mulliken_meta_spin(cell, dm_ao_kpts, kpts, verbose=..., pre_orth_method=..., s=None): ...
def canonicalize(mf, mo_coeff_kpts, mo_occ_kpts, fock=None): ...
def init_guess_by_chkfile(cell, chkfile_name, project=None, kpts=None): ...
def dip_moment(cell, dm_kpts, unit: str = 'Debye', verbose=..., grids=None, rho=None, kpts=...): ...
get_rho = khf.get_rho

def gen_response(mf, mo_coeff=None, mo_occ=None, with_j: bool = True, hermi: int = 0, max_memory=None, with_nlc: bool = True): ...

class KUHF(khf.KSCF):
    conv_tol_grad: Incomplete
    init_guess_breaksym: Incomplete
    init_guess_by_1e: Incomplete
    init_guess_by_minao: Incomplete
    init_guess_by_atom: Incomplete
    init_guess_by_huckel: Incomplete
    init_guess_by_mod_huckel: Incomplete
    get_fock = get_fock
    get_fermi = get_fermi
    get_occ = get_occ
    energy_elec = energy_elec
    get_rho = get_rho
    analyze = khf.analyze
    canonicalize = canonicalize
    gen_response = gen_response
    to_gpu = lib.to_gpu
    def __init__(self, cell, kpts=None, exxdiv=...) -> None: ...
    @property
    def nelec(self): ...
    @nelec.setter
    def nelec(self, x) -> None: ...
    def dump_flags(self, verbose=None): ...
    def get_init_guess(self, cell=None, key: str = 'minao', s1e=None): ...
    def get_veff(self, cell=None, dm_kpts=None, dm_last: int = 0, vhf_last: int = 0, hermi: int = 1, kpts=None, kpts_band=None): ...
    def get_grad(self, mo_coeff_kpts, mo_occ_kpts, fock=None): ...
    def eig(self, h_kpts, s_kpts, overwrite: bool = False, x=None): ...
    def make_rdm1(self, mo_coeff_kpts=None, mo_occ_kpts=None, **kwargs): ...
    def get_bands(self, kpts_band, cell=None, dm_kpts=None, kpts=None): ...
    def init_guess_by_chkfile(self, chk=None, project: bool = True, kpts=None): ...
    def mulliken_meta(self, cell=None, dm=None, kpts=None, verbose=..., pre_orth_method=..., s=None): ...
    def mulliken_meta_spin(self, cell=None, dm=None, kpts=None, verbose=..., pre_orth_method=..., s=None): ...
    def mulliken_pop(self) -> None: ...
    def dip_moment(self, cell=None, dm=None, unit: str = 'Debye', verbose=..., **kwargs): ...
    def spin_square(self, mo_coeff=None, s=None): ...
    def stability(self, internal=..., external=..., verbose=None): ...
    def Gradients(self): ...
    def to_ks(self, xc: str = 'HF'): ...
    def convert_from_(self, mf): ...
