from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc.scf import addons as addons, chkfile as chkfile, khf as khf
from numpy import float64, int64, ndarray
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.dft.krks_ksymm import KsymAdaptedKRKS
from pyscf.pbc.dft.kuks import KUKS
from pyscf.pbc.dft.kuks_ksymm import KsymAdaptedKUKS
from pyscf.pbc.dft.kukspu import KUKSpU
from pyscf.pbc.grad.kuhf import Gradients
from pyscf.pbc.gto.cell import Cell
from pyscf.pbc.lib.kpts import KPoints
from pyscf.pbc.scf.khf import KRHF
from pyscf.pbc.scf.khf_ksymm import KsymAdaptedKRHF
from pyscf.pbc.scf.krohf import KROHF
from pyscf.pbc.scf.kuhf_ksymm import KsymAdaptedKUHF
from pyscf.pbc.scf.uhf import UHF
from pyscf.scf.diis import CDIIS
from typing import Any, Callable, List, Optional, Tuple, Union

PRE_ORTH_METHOD: Incomplete
CHECK_COULOMB_IMAG: Incomplete
canonical_occ = addons.canonical_occ_
canonical_occ_ = addons.canonical_occ_

def make_rdm1(mo_coeff_kpts: Union[ndarray, Tuple[ndarray, ndarray], List[ndarray], List[List[ndarray]]], mo_occ_kpts: Union[ndarray, List[List[ndarray]], Tuple[List[ndarray], List[ndarray]]], **kwargs) -> NPArrayWithTag: ...
def get_fock(mf: "KUHF", h1e: Optional[ndarray]=None, s1e: Optional[ndarray]=None, vhf: Optional[Union[ndarray, NPArrayWithTag]]=None, dm: Optional[Union[ndarray, NPArrayWithTag]]=None, cycle: int = -1, diis: Optional[CDIIS]=None, diis_start_cycle: None=None, level_shift_factor: Optional[int]=None, damp_factor: None=None, fock_last: Optional[ndarray]=None) -> ndarray: ...
def get_fermi(mf: Union[KsymAdaptedKUKS, KUHF], mo_energy_kpts: Optional[List[List[ndarray]]]=None, mo_occ_kpts: Optional[List[List[ndarray]]]=None) -> Union[Tuple[int64, float64], Tuple[float64, float64]]: ...
def get_occ(mf: Union[KUKS, KUKSpU, KUHF], mo_energy_kpts: Optional[Union[ndarray, List[ndarray]]]=None, mo_coeff_kpts: Optional[ndarray]=None) -> ndarray: ...
def energy_elec(mf: Union[KROHF, KUHF], dm_kpts: Optional[Union[ndarray, NPArrayWithTag]]=None, h1e_kpts: Optional[ndarray]=None, vhf_kpts: Optional[ndarray]=None) -> Tuple[float64, float64]: ...
def mulliken_meta(cell: Cell, dm_ao_kpts: Union[ndarray, NPArrayWithTag], kpts: ndarray, verbose: int=..., pre_orth_method: str=..., s: Optional[ndarray]=None) -> Tuple[Tuple[ndarray, ndarray], ndarray]: ...
def mulliken_meta_spin(cell: Cell, dm_ao_kpts: ndarray, kpts: ndarray, verbose: int=..., pre_orth_method: str=..., s: Optional[ndarray]=None) -> Tuple[ndarray, ndarray]: ...
def canonicalize(mf: Union[KUKS, KsymAdaptedKUKS, KUHF, KsymAdaptedKUHF], mo_coeff_kpts: ndarray, mo_occ_kpts: ndarray, fock: Optional[ndarray]=None) -> Tuple[ndarray, ndarray]: ...
def init_guess_by_chkfile(cell: Cell, chkfile_name: str, project: None=None, kpts: Optional[ndarray]=None) -> ndarray: ...
def dip_moment(cell, dm_kpts, unit: str = 'Debye', verbose=..., grids=None, rho=None, kpts=...): ...
get_rho = khf.get_rho

def gen_response(mf: "KUHF", mo_coeff: Optional[ndarray]=None, mo_occ: Optional[ndarray]=None, with_j: bool = True, hermi: int = 0, max_memory: Optional[float]=None, with_nlc: bool = True) -> Callable: ...

class KUHF(khf.KSCF):
    conv_tol_grad: Incomplete
    init_guess_breaksym: Incomplete
    init_guess_by_1e: Incomplete
    init_guess_by_minao: Incomplete
    init_guess_by_atom: Incomplete
    init_guess_by_huckel: Incomplete
    init_guess_by_mod_huckel: Incomplete
    get_fock = get_fock
    get_fermi = get_fermi
    get_occ = get_occ
    energy_elec = energy_elec
    get_rho = get_rho
    analyze = khf.analyze
    canonicalize = canonicalize
    gen_response = gen_response
    to_gpu = lib.to_gpu
    def __init__(self, cell: Cell, kpts: Optional[Any]=None, exxdiv: Optional[str]=...) -> None: ...
    @property
    def nelec(self): ...
    @nelec.setter
    def nelec(self, x) -> None: ...
    def dump_flags(self, verbose: None=None) -> Union[KUKS, KUKSpU, KUHF]: ...
    def get_init_guess(self, cell: Optional[Cell]=None, key: str = 'minao', s1e: Optional[ndarray]=None) -> Union[ndarray, NPArrayWithTag]: ...
    def get_veff(self, cell: Optional[Cell]=None, dm_kpts: Optional[Union[ndarray, NPArrayWithTag]]=None, dm_last: Union[ndarray, int, NPArrayWithTag] = 0, vhf_last: Union[ndarray, int] = 0, hermi: int = 1, kpts: Optional[ndarray]=None, kpts_band: Optional[ndarray]=None) -> ndarray: ...
    def get_grad(self, mo_coeff_kpts: Union[ndarray, Tuple[ndarray, ndarray]], mo_occ_kpts: ndarray, fock: Optional[ndarray]=None) -> ndarray: ...
    def eig(self, h_kpts: Union[ndarray, Tuple[ndarray, ndarray]], s_kpts: Union[ndarray, List[ndarray]], overwrite: bool = False, x: Optional[List[ndarray]]=None) -> Tuple[ndarray, ndarray]: ...
    def make_rdm1(self, mo_coeff_kpts: Optional[Union[ndarray, Tuple[ndarray, ndarray], List[List[ndarray]]]]=None, mo_occ_kpts: Optional[ndarray]=None, **kwargs) -> NPArrayWithTag: ...
    def get_bands(self, kpts_band: ndarray, cell: None=None, dm_kpts: None=None, kpts: Optional[KPoints]=None) -> Tuple[Tuple[ndarray, ndarray], Tuple[ndarray, ndarray]]: ...
    def init_guess_by_chkfile(self, chk: Optional[str]=None, project: None = True, kpts: Optional[ndarray]=None) -> ndarray: ...
    def mulliken_meta(self, cell: Optional[Cell]=None, dm: Optional[Union[ndarray, NPArrayWithTag]]=None, kpts: Optional[ndarray]=None, verbose: int=..., pre_orth_method: str=..., s: Optional[ndarray]=None) -> Tuple[Tuple[ndarray, ndarray], ndarray]: ...
    def mulliken_meta_spin(self, cell: Optional[Cell]=None, dm: Optional[ndarray]=None, kpts: Optional[ndarray]=None, verbose: int=..., pre_orth_method: str=..., s: None=None) -> Tuple[ndarray, ndarray]: ...
    def mulliken_pop(self) -> None: ...
    def dip_moment(self, cell=None, dm=None, unit: str = 'Debye', verbose=..., **kwargs): ...
    def spin_square(self, mo_coeff: None=None, s: None=None) -> Tuple[float64, float64]: ...
    def stability(self, internal: bool=..., external: bool=..., verbose: None=None) -> Tuple[ndarray, None]: ...
    def Gradients(self) -> Gradients: ...
    def to_ks(self, xc: str = 'HF'): ...
    def convert_from_(self, mf: Union[UHF, KRHF, KsymAdaptedKRKS, KsymAdaptedKRHF, KROHF]) -> Union[KsymAdaptedKUHF, KUHF, KsymAdaptedKUKS]: ...
