from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc.lib.kpts import KPoints as KPoints
from pyscf.pbc.scf import khf as khf, khf_ksymm as khf_ksymm, kuhf as kuhf

def get_occ(mf, mo_energy_kpts=None, mo_coeff_kpts=None): ...
def energy_elec(mf, dm_kpts=None, h1e_kpts=None, vhf_kpts=None): ...
get_rho = khf_ksymm.get_rho

class KsymAdaptedKUHF(khf_ksymm.KsymAdaptedKSCF, kuhf.KUHF):
    get_occ = get_occ
    energy_elec = energy_elec
    get_rho = get_rho
    to_ks: Incomplete
    convert_from_: Incomplete
    def __init__(self, cell, kpts=..., exxdiv=..., use_ao_symmetry: bool = True) -> None: ...
    @property
    def nelec(self): ...
    @nelec.setter
    def nelec(self, x) -> None: ...
    def dump_flags(self, verbose=None): ...
    def get_init_guess(self, cell=None, key: str = 'minao', s1e=None): ...
    def eig(self, h_kpts, s_kpts, overwrite: bool = False, x=None): ...
    def get_orbsym(self, mo_coeff=None, s=None): ...
    orbsym: Incomplete
KUHF = KsymAdaptedKUHF
