from pyscf import lib as lib
from pyscf.soscf import newton_ah as newton_ah

def gen_g_hop_rhf(mf, mo_coeff, mo_occ, fock_ao=None, h1e=None): ...
def gen_g_hop_uhf(mf, mo_coeff, mo_occ, fock_ao=None, h1e=None): ...
def gen_g_hop_rohf(mf, mo_coeff, mo_occ, fock_ao=None, h1e=None): ...

class _SecondOrderKRHF(newton_ah._CIAH_SOSCF):
    gen_g_hop = gen_g_hop_rhf
    def update_rotate_matrix(self, dx, mo_occ, u0: int = 1, mo_coeff=None): ...
    def rotate_mo(self, mo_coeff, u, log=None): ...

class _SecondOrderKUHF(newton_ah._CIAH_SOSCF):
    gen_g_hop = gen_g_hop_uhf
    def update_rotate_matrix(self, dx, mo_occ, u0: int = 1, mo_coeff=None): ...
    def rotate_mo(self, mo_coeff, u, log=None): ...

class _SecondOrderKROHF(_SecondOrderKRHF):
    gen_g_hop = gen_g_hop_rohf

def newton(mf): ...
