def get_hcore(cell, kpt=None): ...
def get_int1e_cross(intor, cell1, cell2, kpt=None, comp: int = 1): ...
def get_int1e(intor, cell, kpt=None): ...
def get_ovlp(cell, kpt=None): ...
def get_t(cell, kpt=None): ...
