from pyscf import lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc.scf import newton_ah as newton_ah
from numpy import ndarray
from pyscf.pbc.scf.khf import KRHF
from pyscf.pbc.scf.kuhf import KUHF
from typing import Callable, List, Tuple

def rhf_stability(mf: KRHF, internal: bool = True, external: bool = False, verbose: None=None, return_status: bool = False) -> Tuple[ndarray, Tuple[ndarray, ndarray]]: ...
def uhf_stability(mf: KUHF, internal: bool = True, external: bool = False, verbose: None=None) -> Tuple[ndarray, None]: ...
def rhf_internal(mf: KRHF, verbose: None=None, return_status: bool = False) -> Tuple[ndarray, bool]: ...
def rhf_external(mf: KRHF, verbose: None=None, return_status: bool = False) -> Tuple[Tuple[ndarray, ndarray], bool]: ...
def uhf_internal(mf: KUHF, verbose: None=None) -> ndarray: ...
def uhf_external(mf: KUHF, verbose: None=None) -> None: ...
