from pyscf import lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc.scf import newton_ah as newton_ah

def rhf_stability(mf, internal: bool = True, external: bool = False, verbose=None, return_status: bool = False): ...
def uhf_stability(mf, internal: bool = True, external: bool = False, verbose=None): ...
def rhf_internal(mf, verbose=None, return_status: bool = False): ...
def rhf_external(mf, verbose=None, return_status: bool = False): ...
def uhf_internal(mf, verbose=None): ...
def uhf_external(mf, verbose=None): ...
