from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc.scf import addons as addons, chkfile as chkfile, hf as pbchf

def init_guess_by_chkfile(cell, chkfile_name, project=None, kpt=None): ...
def dip_moment(cell, dm, unit: str = 'Debye', verbose=..., grids=None, rho=None, kpt=...): ...
get_rho = pbchf.get_rho

def gen_response(mf, mo_coeff=None, mo_occ=None, with_j: bool = True, hermi: int = 0, max_memory=None, with_nlc: bool = True): ...

class UHF(pbchf.SCF):
    init_guess_breaksym: Incomplete
    init_guess_by_minao: Incomplete
    init_guess_by_atom: Incomplete
    init_guess_by_huckel: Incomplete
    init_guess_by_mod_huckel: Incomplete
    eig: Incomplete
    get_fock: Incomplete
    get_grad: Incomplete
    get_occ: Incomplete
    make_rdm1: Incomplete
    make_rdm2: Incomplete
    energy_elec: Incomplete
    get_rho = get_rho
    analyze: Incomplete
    mulliken_pop: Incomplete
    mulliken_meta: Incomplete
    mulliken_meta_spin: Incomplete
    canonicalize: Incomplete
    spin_square: Incomplete
    stability: Incomplete
    gen_response = gen_response
    to_gpu = lib.to_gpu
    def __init__(self, cell, kpt=None, exxdiv=...) -> None: ...
    @property
    def nelec(self): ...
    @nelec.setter
    def nelec(self, x) -> None: ...
    def dump_flags(self, verbose=None): ...
    def get_veff(self, cell=None, dm=None, dm_last: int = 0, vhf_last: int = 0, hermi: int = 1, kpt=None, kpts_band=None): ...
    def get_bands(self, kpts_band, cell=None, dm=None, kpt=None): ...
    def dip_moment(self, cell=None, dm=None, unit: str = 'Debye', verbose=..., **kwargs): ...
    def get_init_guess(self, cell=None, key: str = 'minao', s1e=None): ...
    def init_guess_by_1e(self, cell=None): ...
    def init_guess_by_chkfile(self, chk=None, project: bool = True, kpt=None): ...
    def get_fermi(self): ...
    def to_ks(self, xc: str = 'HF'): ...
    def convert_from_(self, mf): ...
    def Gradients(self): ...
