from pyscf import scf as scf
from pyscf.cc import addons as addons, ccsd as ccsd, ccsd_lambda as ccsd_lambda, ccsd_rdm as ccsd_rdm, eom_gccsd as eom_gccsd, eom_rccsd as eom_rccsd, eom_uccsd as eom_uccsd, gccsd as gccsd, qcisd as qcisd, rccsd as rccsd, rccsdt as rccsdt, rccsdt_highm as rccsdt_highm, rccsdtq as rccsdtq, rccsdtq_highm as rccsdtq_highm, uccsd as uccsd, uccsdt as uccsdt, uccsdt_highm as uccsdt_highm

def CCSD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def RCCSD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def UCCSD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def GCCSD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def QCISD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def RQCISD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def FNOCCSD(mf, thresh: float = 1e-06, pct_occ=None, nvir_act=None, frozen=None): ...
def BCCD(mf, frozen=None, u=None, conv_tol_normu: float = 1e-05, max_cycle: int = 20, diis: bool = True, canonicalization: bool = True): ...
def CCSDT(mf, frozen=None, mo_coeff=None, mo_occ=None, compact_tamps: bool = True): ...
def RCCSDT(mf, frozen=None, mo_coeff=None, mo_occ=None, compact_tamps: bool = True): ...
def UCCSDT(mf, frozen=None, mo_coeff=None, mo_occ=None, compact_tamps: bool = True): ...
def CCSDTQ(mf, frozen=None, mo_coeff=None, mo_occ=None, compact_tamps: bool = True): ...
def RCCSDTQ(mf, frozen=None, mo_coeff=None, mo_occ=None, compact_tamps: bool = True): ...
