from pyscf import scf as scf
from pyscf.cc import addons as addons, ccsd as ccsd, ccsd_lambda as ccsd_lambda, ccsd_rdm as ccsd_rdm, eom_gccsd as eom_gccsd, eom_rccsd as eom_rccsd, eom_uccsd as eom_uccsd, gccsd as gccsd, qcisd as qcisd, rccsd as rccsd, rccsdt as rccsdt, rccsdt_highm as rccsdt_highm, rccsdtq as rccsdtq, rccsdtq_highm as rccsdtq_highm, uccsd as uccsd, uccsdt as uccsdt, uccsdt_highm as uccsdt_highm
from _typeshed import Incomplete
from numpy import ndarray
from pyscf.cc.gccsd import GCCSD
from pyscf.cc.rccsd import RCCSD
from pyscf.cc.uccsd import UCCSD
from pyscf.scf.ghf import GHF
from pyscf.scf.hf import RHF
from pyscf.scf.hf_symm import SymAdaptedRHF
from pyscf.scf.rohf import ROHF
from pyscf.scf.uhf import UHF
from pyscf.scf.uhf_symm import SymAdaptedUHF
from typing import List, Optional, Union

def CCSD(mf: Union[UHF, GHF, RHF, SymAdaptedRHF], frozen: Optional[Union[List[ndarray], int, ndarray]]=None, mo_coeff: Optional[Union[List[ndarray], ndarray]]=None, mo_occ: None=None) -> Union[GCCSD, RCCSD, Incomplete, UCCSD]: ...
def RCCSD(mf: Union[ROHF, SymAdaptedRHF, RHF], frozen: Optional[Union[int, ndarray]]=None, mo_coeff: Optional[ndarray]=None, mo_occ: None=None) -> Union[RCCSD, Incomplete, UCCSD]: ...
def UCCSD(mf: Union[UHF, RHF, SymAdaptedUHF], frozen: Optional[Union[List[ndarray], int, List[List[int]]]]=None, mo_coeff: Optional[List[ndarray]]=None, mo_occ: None=None) -> UCCSD: ...
def GCCSD(mf: Union[UHF, GHF, RHF], frozen: None=None, mo_coeff: None=None, mo_occ: None=None) -> GCCSD: ...
def QCISD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def RQCISD(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def FNOCCSD(mf: Union[UHF, RHF], thresh: float = 1e-06, pct_occ: None=None, nvir_act: None=None, frozen: Optional[int]=None) -> Union[Incomplete, UCCSD]: ...
def BCCD(mf, frozen=None, u=None, conv_tol_normu: float = 1e-05, max_cycle: int = 20, diis: bool = True, canonicalization: bool = True): ...
def CCSDT(mf, frozen=None, mo_coeff=None, mo_occ=None, compact_tamps: bool = True): ...
def RCCSDT(mf: Union[ROHF, RHF], frozen: None=None, mo_coeff: None=None, mo_occ: None=None, compact_tamps: bool = True) -> Union[Incomplete, Incomplete, Incomplete]: ...
def UCCSDT(mf: UHF, frozen: Optional[List[List[int]]]=None, mo_coeff: None=None, mo_occ: None=None, compact_tamps: bool = True) -> Union[Incomplete, Incomplete]: ...
def CCSDTQ(mf, frozen=None, mo_coeff=None, mo_occ=None, compact_tamps: bool = True): ...
def RCCSDTQ(mf: RHF, frozen: None=None, mo_coeff: None=None, mo_occ: None=None, compact_tamps: bool = True) -> Union[Incomplete, Incomplete]: ...
