from pyscf import lib as lib
from pyscf.cc.bccd import bccd_kernel_ as bccd_kernel_

def spatial2spin(tx, orbspin=None): ...
spatial2spinorb = spatial2spin

def spin2spatial(tx, orbspin): ...
def convert_to_uccsd(mycc): ...
def convert_to_gccsd(mycc): ...
