from pyscf import lib as lib
from numpy import ndarray
from pyscf.cc.ccsd import CCSD
from pyscf.cc.gccsd import GCCSD
from pyscf.cc.uccsd import UCCSD
from pyscf.lib.numpy_helper import NPArrayWithTag
from typing import List, Optional, Tuple, Union

def get_umat_from_t1(t1: Union[ndarray, Tuple[ndarray, ndarray], NPArrayWithTag]) -> ndarray: ...
def transform_t1_to_bo(t1: Union[ndarray, Tuple[ndarray, ndarray], NPArrayWithTag], umat: Union[ndarray, List[ndarray]]) -> Union[ndarray, List[ndarray]]: ...
def transform_t2_to_bo(t2: Union[ndarray, Tuple[ndarray, ndarray, ndarray], NPArrayWithTag], umat: Union[ndarray, List[ndarray]], umat_b: Optional[ndarray]=None) -> Union[ndarray, List[ndarray]]: ...
transform_l1_to_bo = transform_t1_to_bo
transform_l2_to_bo = transform_t2_to_bo

def get_mo_ovlp(mo1: Union[ndarray, NPArrayWithTag], mo2: ndarray, ovlp: ndarray) -> ndarray: ...
def logm(mrot: ndarray) -> ndarray: ...
def bccd_kernel_(mycc: Union[GCCSD, CCSD, UCCSD], u: None=None, conv_tol_normu: float = 1e-05, max_cycle: int = 20, diis: bool = True, canonicalization: bool = True, verbose: int = 4) -> Union[GCCSD, CCSD, UCCSD]: ...
