from pyscf import lib as lib

def get_umat_from_t1(t1): ...
def transform_t1_to_bo(t1, umat): ...
def transform_t2_to_bo(t2, umat, umat_b=None): ...
transform_l1_to_bo = transform_t1_to_bo
transform_l2_to_bo = transform_t2_to_bo

def get_mo_ovlp(mo1, mo2, ovlp): ...
def logm(mrot): ...
def bccd_kernel_(mycc, u=None, conv_tol_normu: float = 1e-05, max_cycle: int = 20, diis: bool = True, canonicalization: bool = True, verbose: int = 4): ...
