from pyscf.cc import ccsd as ccsd, ccsd_lambda as ccsd_lambda, ccsd_rdm as ccsd_rdm

class CCD(ccsd.CCSD):
    def update_amps(self, t1, t2, eris): ...
    def kernel(self, t2=None, eris=None): ...
    def solve_lambda(self, t2=None, l2=None, eris=None): ...
    def make_rdm1(self, t2=None, l2=None, ao_repr: bool = False): ...
    def make_rdm2(self, t1=None, t2=None, l1=None, l2=None, ao_repr: bool = False): ...
