from pyscf.cc import ccsd as ccsd, ccsd_lambda as ccsd_lambda, ccsd_rdm as ccsd_rdm
from numpy import float64, ndarray
from pyscf.cc.ccsd import _ChemistsERIs
from typing import Optional, Tuple

class CCD(ccsd.CCSD):
    def update_amps(self, t1: ndarray, t2: ndarray, eris: _ChemistsERIs) -> Tuple[ndarray, ndarray]: ...
    def kernel(self, t2: None=None, eris: None=None) -> Tuple[float64, ndarray]: ...
    def solve_lambda(self, t2: Optional[ndarray]=None, l2: None=None, eris: None=None) -> ndarray: ...
    def make_rdm1(self, t2: None=None, l2: None=None, ao_repr: bool = False) -> ndarray: ...
    def make_rdm2(self, t1: None=None, t2: None=None, l1: None=None, l2: None=None, ao_repr: bool = False) -> ndarray: ...
