from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, gto as gto, lib as lib
from pyscf.lib import logger as logger
from pyscf.mp.mp2 import get_e_hf as get_e_hf, get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc
from h5py._hl.dataset import Dataset
from numpy import float64, ndarray
from pyscf.cc.ccd import CCD
from pyscf.cc.eom_rccsd import EOMEA, EOMEE, EOMIP
from pyscf.cc.qcisd import QCISD
from pyscf.df.df import DF
from pyscf.gto.mole import Mole
from pyscf.lib.diis import DIIS
from pyscf.lib.logger import Logger
from pyscf.lib.misc import H5TmpFile
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.ci.cisd import RCISD, UCISD
from pyscf.pbc.gto.cell import Cell
from pyscf.pbc.lib.ktensor import KsymmArray
from pyscf.scf.hf import SCF
from typing import Any, List, Optional, Tuple, Union

BLKMIN: Incomplete
MEMORYMIN: Incomplete

def kernel(mycc: Any, eris: Optional[Any]=None, t1: Optional[Union[List[ndarray], ndarray]]=None, t2: Optional[Union[List[ndarray], ndarray]]=None, max_cycle: int = 50, tol: float = 1e-08, tolnormt: float = 1e-06, verbose: Optional[int]=None, callback: None=None) -> Union[Tuple[bool, float64, KsymmArray, KsymmArray], Tuple[bool, float, ndarray, ndarray], Tuple[bool, float64, Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]], Tuple[bool, float64, ndarray, ndarray]]: ...
def update_amps(mycc: Union[Incomplete, CCSD_Scanner, CCSD, CCD], t1: ndarray, t2: ndarray, eris: Union[Incomplete, Incomplete]) -> Tuple[ndarray, ndarray]: ...
def amplitudes_to_vector(t1: ndarray, t2: ndarray, out: None=None) -> ndarray: ...
def vector_to_amplitudes(vector: ndarray, nmo: int, nocc: int) -> Tuple[ndarray, ndarray]: ...
def amplitudes_to_vector_s4(t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], out: Optional[ndarray]=None) -> ndarray: ...
def vector_to_amplitudes_s4(vector: ndarray, nmo: int, nocc: int) -> Tuple[ndarray, ndarray]: ...
def energy(mycc: Union[Incomplete, CCSD, CCD, CCSD_Scanner], t1: Optional[ndarray]=None, t2: Optional[ndarray]=None, eris: Optional[Union[Incomplete, Incomplete, Incomplete]]=None) -> float64: ...
def restore_from_diis_(mycc: "CCSD", diis_file: str, inplace: bool = True) -> "CCSD": ...
def get_t1_diagnostic(t1: ndarray) -> float64: ...
def get_d1_diagnostic(t1: ndarray) -> float64: ...
def get_d2_diagnostic(t2: ndarray) -> float64: ...
def set_frozen(mycc: Union[Incomplete, Incomplete, Incomplete, Incomplete, Incomplete], method: str = 'auto', window: Tuple[float, float]=(-1000.0, 1000.0), is_gcc: bool = False) -> Union[Incomplete, Incomplete, Incomplete, Incomplete, Incomplete]: ...
def as_scanner(cc: Union[CCSD, CCSD_Scanner]) -> "CCSD_Scanner": ...

class CCSD_Scanner(lib.SinglePointScanner):
    def __init__(self, cc: Union[QCISD, CCSD]) -> None: ...
    mo_coeff: Incomplete
    mo_occ: Incomplete
    t1: Incomplete
    def __call__(self, mol_or_geom: Union[Mole, str], **kwargs) -> float64: ...

class CCSDBase(lib.StreamObject):
    max_cycle: Incomplete
    conv_tol: Incomplete
    iterative_damping: Incomplete
    conv_tol_normt: Incomplete
    diis: Incomplete
    diis_space: Incomplete
    diis_file: Incomplete
    diis_start_cycle: Incomplete
    diis_start_energy_diff: Incomplete
    direct: Incomplete
    async_io: Incomplete
    incore_complete: Incomplete
    cc2: Incomplete
    callback: Incomplete
    mol: Incomplete
    verbose: Incomplete
    stdout: Incomplete
    max_memory: Incomplete
    frozen: Incomplete
    level_shift: int
    mo_coeff: Incomplete
    mo_occ: Incomplete
    converged: bool
    cycles: Incomplete
    converged_lambda: bool
    emp2: Incomplete
    e_hf: Incomplete
    e_corr: Incomplete
    t1: Incomplete
    t2: Incomplete
    l1: Incomplete
    l2: Incomplete
    chkfile: Incomplete
    def __init__(self, mf: SCF, frozen: Optional[Any]=None, mo_coeff: Optional[Union[List[ndarray], ndarray]]=None, mo_occ: Optional[ndarray]=None) -> None: ...
    @property
    def ecc(self) -> float64: ...
    @property
    def e_tot(self) -> float64: ...
    @property
    def nocc(self): ...
    @nocc.setter
    def nocc(self, n) -> None: ...
    @property
    def nmo(self): ...
    @nmo.setter
    def nmo(self, n) -> None: ...
    def reset(self, mol: Optional[Mole]=None) -> Union[CCSD, Incomplete, Incomplete, CCSD_Scanner, Incomplete]: ...
    get_nocc = get_nocc
    get_nmo = get_nmo
    get_frozen_mask = get_frozen_mask
    get_e_hf = get_e_hf
    def set_frozen(self, method: str = 'auto', window: Tuple[float, float]=(-1000.0, 1000.0)) -> Union[Incomplete, Incomplete, Incomplete, Incomplete, Incomplete]: ...
    def dump_flags(self, verbose: None=None) -> Any: ...
    def get_init_guess(self, eris: Optional[Any]=None) -> Union[Tuple[Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]], Tuple[KsymmArray, KsymmArray], Tuple[ndarray, ndarray]]: ...
    def init_amps(self, eris: Optional[Union[Incomplete, Incomplete, Incomplete]]=None) -> Tuple[float64, ndarray, ndarray]: ...
    energy = energy
    update_amps = update_amps
    def kernel(self, t1: Optional[ndarray]=None, t2: Optional[ndarray]=None, eris: Optional[Union[Incomplete, Incomplete]]=None) -> Tuple[float64, ndarray, ndarray]: ...
    def ccsd(self, t1: Optional[Union[List[ndarray], ndarray]]=None, t2: Optional[Union[List[ndarray], ndarray]]=None, eris: Optional[Any]=None) -> Union[Tuple[float64, ndarray, ndarray], Tuple[float64, Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]]]: ...
    as_scanner = as_scanner
    restore_from_diis_ = restore_from_diis_
    def solve_lambda(self, t1=None, t2=None, l1=None, l2=None, eris=None) -> None: ...
    def ccsd_t(self, t1=None, t2=None, eris=None) -> None: ...
    def ipccsd(self, nroots: int = 1, left: bool = False, koopmans: bool = False, guess=None, partition=None, eris=None) -> None: ...
    def eaccsd(self, nroots: int = 1, left: bool = False, koopmans: bool = False, guess=None, partition=None, eris=None) -> None: ...
    def eeccsd(self, nroots: int = 1, koopmans: bool = False, guess=None, eris=None) -> None: ...
    def eomee_ccsd_singlet(self, nroots: int = 1, koopmans: bool = False, guess=None, eris=None) -> None: ...
    def eomee_ccsd_triplet(self, nroots: int = 1, koopmans: bool = False, guess=None, eris=None) -> None: ...
    def eomsf_ccsd(self, nroots: int = 1, koopmans: bool = False, guess=None, eris=None) -> None: ...
    def eomip_method(self) -> None: ...
    def eomea_method(self) -> None: ...
    def eomee_method(self) -> None: ...
    def make_rdm1(self, t1=None, t2=None, l1=None, l2=None, ao_repr: bool = False, with_frozen: bool = True, with_mf: bool = True) -> None: ...
    def make_rdm2(self, t1=None, t2=None, l1=None, l2=None, ao_repr: bool = False, with_frozen: bool = True, with_dm1: bool = True) -> None: ...
    def ao2mo(self, mo_coeff: Optional[Union[ndarray, NPArrayWithTag]]=None) -> Incomplete: ...
    def run_diis(self, t1: Union[ndarray, KsymmArray, Tuple[ndarray, ndarray]], t2: Union[ndarray, KsymmArray, Tuple[ndarray, ndarray, ndarray]], istep: int, normt: float64, de: Union[float, int, float64], adiis: Optional[DIIS]) -> Union[Tuple[Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]], Tuple[KsymmArray, KsymmArray], Tuple[ndarray, ndarray]]: ...
    def amplitudes_to_vector(self, t1: ndarray, t2: ndarray, out: None=None) -> ndarray: ...
    def vector_to_amplitudes(self, vec: ndarray, nmo: None=None, nocc: None=None) -> Tuple[ndarray, ndarray]: ...
    def vector_size(self, nmo: None=None, nocc: None=None) -> int: ...
    def dump_chk(self, t1_t2: None=None, frozen: None=None, mo_coeff: None=None, mo_occ: None=None): ...
    def density_fit(self, auxbasis=None, with_df=None) -> None: ...
    def nuc_grad_method(self) -> None: ...
    to_gpu = lib.to_gpu

class CCSD(CCSDBase):
    __doc__: Incomplete
    def dump_flags(self, verbose: None=None) -> Any: ...
    def solve_lambda(self, t1: Optional[ndarray]=None, t2: Optional[ndarray]=None, l1: Optional[ndarray]=None, l2: Optional[ndarray]=None, eris: None=None) -> Tuple[ndarray, ndarray]: ...
    def ccsd_t(self, t1: None=None, t2: None=None, eris: Optional[Incomplete]=None) -> float64: ...
    def ipccsd(self, nroots: int = 1, left: bool = False, koopmans: bool = False, guess: Optional[List[ndarray]]=None, partition: Optional[str]=None, eris: None=None) -> Union[Tuple[float64, ndarray], Tuple[ndarray, List[ndarray]]]: ...
    def eaccsd(self, nroots: int = 1, left: bool = False, koopmans: bool = False, guess: Optional[List[ndarray]]=None, partition: Optional[str]=None, eris: None=None) -> Union[Tuple[float64, ndarray], Tuple[ndarray, List[ndarray]]]: ...
    def eeccsd(self, nroots: int = 1, koopmans: bool = False, guess: Optional[List[Optional[ndarray]]]=None, eris: None=None) -> Union[Tuple[float64, ndarray], Tuple[ndarray, List[Optional[ndarray]]]]: ...
    def eomee_ccsd_singlet(self, nroots: int = 1, koopmans: bool = False, guess: None=None, eris: None=None) -> Tuple[float64, ndarray]: ...
    def eomee_ccsd_triplet(self, nroots: int = 1, koopmans: bool = False, guess: None=None, eris: None=None) -> Tuple[float64, ndarray]: ...
    def eomsf_ccsd(self, nroots: int = 1, koopmans: bool = False, guess: None=None, eris: None=None) -> Tuple[float64, ndarray]: ...
    def eomip_method(self) -> EOMIP: ...
    def eomea_method(self) -> EOMEA: ...
    def eomee_method(self) -> EOMEE: ...
    def make_rdm1(self, t1: Optional[ndarray]=None, t2: Optional[ndarray]=None, l1: Optional[ndarray]=None, l2: Optional[ndarray]=None, ao_repr: bool = False, with_frozen: bool = True, with_mf: bool = True) -> ndarray: ...
    def make_rdm2(self, t1: Optional[ndarray]=None, t2: Optional[ndarray]=None, l1: Optional[ndarray]=None, l2: Optional[ndarray]=None, ao_repr: bool = False, with_frozen: bool = True, with_dm1: bool = True) -> ndarray: ...
    def density_fit(self, auxbasis: Optional[str]=None, with_df: Optional[DF]=None) -> Incomplete: ...
    def nuc_grad_method(self): ...
    def get_t1_diagnostic(self, t1: None=None) -> float64: ...
    def get_d1_diagnostic(self, t1: None=None) -> float64: ...
    def get_d2_diagnostic(self, t2: None=None) -> float64: ...
CC = CCSD
RCCSD = CCSD

class _ChemistsERIs:
    mol: Incomplete
    mo_coeff: Incomplete
    nocc: Incomplete
    fock: Incomplete
    oooo: Incomplete
    ovoo: Incomplete
    oovv: Incomplete
    ovvo: Incomplete
    ovov: Incomplete
    ovvv: Incomplete
    vvvv: Incomplete
    def __init__(self, mol: Optional[Mole]=None) -> None: ...
    def get_ovvv(self, *slices) -> ndarray: ...
