from pyscf import lib as lib
from pyscf.cc import ccsd_rdm as ccsd_rdm
from _typeshed import Incomplete
from numpy import ndarray
from pyscf.cc.ccsd import CCSD
from pyscf.cc.rccsd import RCCSD
from typing import Optional, Tuple, Union

def make_rdm1(mycc: CCSD, t1: ndarray, t2: ndarray, l1: ndarray, l2: ndarray, eris: Optional[Incomplete]=None, ao_repr: bool = False) -> ndarray: ...
def make_rdm2(mycc: CCSD, t1: ndarray, t2: ndarray, l1: ndarray, l2: ndarray, eris: Optional[Incomplete]=None) -> ndarray: ...
def p6(t: ndarray) -> ndarray: ...
def r6(w: ndarray) -> ndarray: ...
