from pyscf import lib as lib
from pyscf.cc import ccsd_rdm as ccsd_rdm
from pyscf.lib import logger as logger

def make_rdm1(mycc, t1, t2, l1, l2, eris=None, ao_repr: bool = False): ...
def make_rdm2(mycc, t1, t2, l1, l2, eris=None): ...
def t3_symm_ip_py(A, nocc3, nvir, pattern, alpha: float = 1.0, beta: float = 0.0): ...
