from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, gto as gto, lib as lib
from pyscf.lib import logger as logger
from pyscf.mp.mp2 import get_e_hf as get_e_hf, get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc

BLKMIN: Incomplete
MEMORYMIN: Incomplete

def kernel(mycc, eris=None, t1=None, t2=None, max_cycle: int = 50, tol: float = 1e-08, tolnormt: float = 1e-06, verbose=None, callback=None): ...
def update_amps(mycc, t1, t2, eris): ...
def amplitudes_to_vector(t1, t2, out=None): ...
def vector_to_amplitudes(vector, nmo, nocc): ...
def amplitudes_to_vector_s4(t1, t2, out=None): ...
def vector_to_amplitudes_s4(vector, nmo, nocc): ...
def energy(mycc, t1=None, t2=None, eris=None): ...
def restore_from_diis_(mycc, diis_file, inplace: bool = True): ...
def get_t1_diagnostic(t1): ...
def get_d1_diagnostic(t1): ...
def get_d2_diagnostic(t2): ...
def set_frozen(mycc, method: str = 'auto', window=(-1000.0, 1000.0), is_gcc: bool = False): ...
def as_scanner(cc): ...

class CCSD_Scanner(lib.SinglePointScanner):
    def __init__(self, cc) -> None: ...
    mo_coeff: Incomplete
    mo_occ: Incomplete
    t1: Incomplete
    def __call__(self, mol_or_geom, **kwargs): ...

class CCSDBase(lib.StreamObject):
    max_cycle: Incomplete
    conv_tol: Incomplete
    iterative_damping: Incomplete
    conv_tol_normt: Incomplete
    diis: Incomplete
    diis_space: Incomplete
    diis_file: Incomplete
    diis_start_cycle: Incomplete
    diis_start_energy_diff: Incomplete
    direct: Incomplete
    async_io: Incomplete
    incore_complete: Incomplete
    cc2: Incomplete
    callback: Incomplete
    mol: Incomplete
    verbose: Incomplete
    stdout: Incomplete
    max_memory: Incomplete
    frozen: Incomplete
    level_shift: int
    mo_coeff: Incomplete
    mo_occ: Incomplete
    converged: bool
    cycles: Incomplete
    converged_lambda: bool
    emp2: Incomplete
    e_hf: Incomplete
    e_corr: Incomplete
    t1: Incomplete
    t2: Incomplete
    l1: Incomplete
    l2: Incomplete
    chkfile: Incomplete
    def __init__(self, mf, frozen=None, mo_coeff=None, mo_occ=None) -> None: ...
    @property
    def ecc(self): ...
    @property
    def e_tot(self): ...
    @property
    def nocc(self): ...
    @nocc.setter
    def nocc(self, n) -> None: ...
    @property
    def nmo(self): ...
    @nmo.setter
    def nmo(self, n) -> None: ...
    def reset(self, mol=None): ...
    get_nocc = get_nocc
    get_nmo = get_nmo
    get_frozen_mask = get_frozen_mask
    get_e_hf = get_e_hf
    def set_frozen(self, method: str = 'auto', window=(-1000.0, 1000.0)): ...
    def dump_flags(self, verbose=None): ...
    def get_init_guess(self, eris=None): ...
    def init_amps(self, eris=None): ...
    energy = energy
    update_amps = update_amps
    def kernel(self, t1=None, t2=None, eris=None): ...
    def ccsd(self, t1=None, t2=None, eris=None): ...
    as_scanner = as_scanner
    restore_from_diis_ = restore_from_diis_
    def solve_lambda(self, t1=None, t2=None, l1=None, l2=None, eris=None) -> None: ...
    def ccsd_t(self, t1=None, t2=None, eris=None) -> None: ...
    def ipccsd(self, nroots: int = 1, left: bool = False, koopmans: bool = False, guess=None, partition=None, eris=None) -> None: ...
    def eaccsd(self, nroots: int = 1, left: bool = False, koopmans: bool = False, guess=None, partition=None, eris=None) -> None: ...
    def eeccsd(self, nroots: int = 1, koopmans: bool = False, guess=None, eris=None) -> None: ...
    def eomee_ccsd_singlet(self, nroots: int = 1, koopmans: bool = False, guess=None, eris=None) -> None: ...
    def eomee_ccsd_triplet(self, nroots: int = 1, koopmans: bool = False, guess=None, eris=None) -> None: ...
    def eomsf_ccsd(self, nroots: int = 1, koopmans: bool = False, guess=None, eris=None) -> None: ...
    def eomip_method(self) -> None: ...
    def eomea_method(self) -> None: ...
    def eomee_method(self) -> None: ...
    def make_rdm1(self, t1=None, t2=None, l1=None, l2=None, ao_repr: bool = False, with_frozen: bool = True, with_mf: bool = True) -> None: ...
    def make_rdm2(self, t1=None, t2=None, l1=None, l2=None, ao_repr: bool = False, with_frozen: bool = True, with_dm1: bool = True) -> None: ...
    def ao2mo(self, mo_coeff=None): ...
    def run_diis(self, t1, t2, istep, normt, de, adiis): ...
    def amplitudes_to_vector(self, t1, t2, out=None): ...
    def vector_to_amplitudes(self, vec, nmo=None, nocc=None): ...
    def vector_size(self, nmo=None, nocc=None): ...
    def dump_chk(self, t1_t2=None, frozen=None, mo_coeff=None, mo_occ=None): ...
    def density_fit(self, auxbasis=None, with_df=None) -> None: ...
    def nuc_grad_method(self) -> None: ...
    to_gpu = lib.to_gpu

class CCSD(CCSDBase):
    __doc__: Incomplete
    def dump_flags(self, verbose=None): ...
    def solve_lambda(self, t1=None, t2=None, l1=None, l2=None, eris=None): ...
    def ccsd_t(self, t1=None, t2=None, eris=None): ...
    def ipccsd(self, nroots: int = 1, left: bool = False, koopmans: bool = False, guess=None, partition=None, eris=None): ...
    def eaccsd(self, nroots: int = 1, left: bool = False, koopmans: bool = False, guess=None, partition=None, eris=None): ...
    def eeccsd(self, nroots: int = 1, koopmans: bool = False, guess=None, eris=None): ...
    def eomee_ccsd_singlet(self, nroots: int = 1, koopmans: bool = False, guess=None, eris=None): ...
    def eomee_ccsd_triplet(self, nroots: int = 1, koopmans: bool = False, guess=None, eris=None): ...
    def eomsf_ccsd(self, nroots: int = 1, koopmans: bool = False, guess=None, eris=None): ...
    def eomip_method(self): ...
    def eomea_method(self): ...
    def eomee_method(self): ...
    def make_rdm1(self, t1=None, t2=None, l1=None, l2=None, ao_repr: bool = False, with_frozen: bool = True, with_mf: bool = True): ...
    def make_rdm2(self, t1=None, t2=None, l1=None, l2=None, ao_repr: bool = False, with_frozen: bool = True, with_dm1: bool = True): ...
    def density_fit(self, auxbasis=None, with_df=None): ...
    def nuc_grad_method(self): ...
    def get_t1_diagnostic(self, t1=None): ...
    def get_d1_diagnostic(self, t1=None): ...
    def get_d2_diagnostic(self, t2=None): ...
CC = CCSD
RCCSD = CCSD

class _ChemistsERIs:
    mol: Incomplete
    mo_coeff: Incomplete
    nocc: Incomplete
    fock: Incomplete
    oooo: Incomplete
    ovoo: Incomplete
    oovv: Incomplete
    ovvo: Incomplete
    ovov: Incomplete
    ovvv: Incomplete
    vvvv: Incomplete
    def __init__(self, mol=None) -> None: ...
    def get_ovvv(self, *slices): ...
