from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, lib as lib
from pyscf.cc import ccsd as ccsd
from pyscf.lib import logger as logger, module_method as module_method

def kernel(eom, nroots: int = 1, koopmans: bool = False, guess=None, left: bool = False, eris=None, imds=None, **kwargs): ...

class EOM(lib.StreamObject):
    mol: Incomplete
    verbose: Incomplete
    stdout: Incomplete
    max_memory: Incomplete
    max_space: Incomplete
    max_cycle: Incomplete
    conv_tol: Incomplete
    partition: Incomplete
    e: Incomplete
    v: Incomplete
    nocc: Incomplete
    nmo: Incomplete
    def __init__(self, cc) -> None: ...
    def dump_flags(self, verbose=None): ...
    def reset(self, mol=None): ...

def perturbed_ccsd_kernel(eom, nroots: int = 1, koopmans: bool = False, right_guess=None, left_guess=None, eris=None, imds=None): ...
def ipccsd(eom, nroots: int = 1, left: bool = False, koopmans: bool = False, guess=None, partition=None, eris=None, imds=None): ...
def ipccsd_star(eom, nroots: int = 1, koopmans: bool = False, right_guess=None, left_guess=None, eris=None, imds=None): ...
def vector_to_amplitudes_ip(vector, nmo, nocc): ...
def amplitudes_to_vector_ip(r1, r2): ...
def spatial2spin_ip(rx, orbspin=None): ...
def ipccsd_matvec(eom, vector, imds=None, diag=None): ...
def lipccsd_matvec(eom, vector, imds=None, diag=None): ...
def ipccsd_diag(eom, imds=None): ...
def ipccsd_star_contract(eom, ipccsd_evals, ipccsd_evecs, lipccsd_evecs, imds=None): ...

class EOMIP(EOM):
    def get_init_guess(self, nroots: int = 1, koopmans: bool = True, diag=None): ...
    kernel = ipccsd
    ipccsd = ipccsd
    ipccsd_star = ipccsd_star
    matvec = ipccsd_matvec
    l_matvec = lipccsd_matvec
    get_diag = ipccsd_diag
    ccsd_star_contract = ipccsd_star_contract
    def ipccsd_star_contract(self, ipccsd_evals, ipccsd_evecs, lipccsd_evecs, imds=None): ...
    def gen_matvec(self, imds=None, left: bool = False, **kwargs): ...
    amplitudes_to_vector: Incomplete
    vector_to_amplitudes: Incomplete
    spatial2spin: Incomplete
    def vector_size(self): ...
    def make_imds(self, eris=None): ...
    @property
    def eip(self): ...

class EOMIP_Ta(EOMIP):
    def make_imds(self, eris=None): ...

def eaccsd(eom, nroots: int = 1, left: bool = False, koopmans: bool = False, guess=None, partition=None, eris=None, imds=None): ...
def eaccsd_star(eom, nroots: int = 1, koopmans: bool = False, right_guess=None, left_guess=None, eris=None, imds=None, **kwargs): ...
def vector_to_amplitudes_ea(vector, nmo, nocc): ...
def amplitudes_to_vector_ea(r1, r2): ...
def spatial2spin_ea(rx, orbspin=None): ...
def eaccsd_matvec(eom, vector, imds=None, diag=None): ...
def leaccsd_matvec(eom, vector, imds=None, diag=None): ...
def eaccsd_diag(eom, imds=None): ...
def eaccsd_star_contract(eom, eaccsd_evals, eaccsd_evecs, leaccsd_evecs, imds=None): ...

class EOMEA(EOM):
    def get_init_guess(self, nroots: int = 1, koopmans: bool = True, diag=None): ...
    kernel = eaccsd
    eaccsd = eaccsd
    eaccsd_star = eaccsd_star
    matvec = eaccsd_matvec
    l_matvec = leaccsd_matvec
    get_diag = eaccsd_diag
    ccsd_star_contract = eaccsd_star_contract
    def eaccsd_star_contract(self, eaccsd_evals, eaccsd_evecs, leaccsd_evecs, imds=None): ...
    def gen_matvec(self, imds=None, left: bool = False, **kwargs): ...
    amplitudes_to_vector: Incomplete
    vector_to_amplitudes: Incomplete
    spatial2spin: Incomplete
    def vector_size(self): ...
    def make_imds(self, eris=None): ...
    @property
    def eea(self): ...

class EOMEA_Ta(EOMEA):
    def make_imds(self, eris=None): ...

def eeccsd(eom, nroots: int = 1, koopmans: bool = False, guess=None, eris=None, imds=None): ...
def eomee_ccsd_singlet(eom, nroots: int = 1, koopmans: bool = False, guess=None, eris=None, imds=None, diag=None): ...
def eomee_ccsd_triplet(eom, nroots: int = 1, koopmans: bool = False, guess=None, eris=None, imds=None, diag=None): ...
def eomsf_ccsd(eom, nroots: int = 1, koopmans: bool = False, guess=None, eris=None, imds=None, diag=None): ...
vector_to_amplitudes_ee = ccsd.vector_to_amplitudes
vector_to_amplitudes_singlet = ccsd.vector_to_amplitudes
amplitudes_to_vector_ee = ccsd.amplitudes_to_vector
amplitudes_to_vector_singlet = ccsd.amplitudes_to_vector

def spatial2spin_singlet(rx, orbspin=None): ...
def amplitudes_to_vector_eomsf(t1, t2, out=None): ...
def vector_to_amplitudes_eomsf(vector, nmo, nocc): ...
def spatial2spin_eomsf(rx, orbspin=None): ...
def amplitudes_to_vector_triplet(t1, t2, out=None): ...
def vector_to_amplitudes_triplet(vector, nmo, nocc): ...
def spatial2spin_triplet(rx, orbspin=None): ...
def eeccsd_matvec_singlet(eom, vector, imds=None): ...
def eeccsd_matvec_triplet(eom, vector, imds=None): ...
def eeccsd_matvec_sf(eom, vector, imds=None): ...
def eeccsd_diag(eom, imds=None): ...

class EOMEE(EOM):
    def get_init_guess(self, nroots: int = 1, koopmans: bool = True, diag=None): ...
    kernel = eeccsd
    eeccsd = eeccsd
    get_diag = eeccsd_diag
    def vector_size(self): ...
    def make_imds(self, eris=None): ...
    @property
    def eee(self): ...

class EOMEESinglet(EOMEE):
    kernel = eomee_ccsd_singlet
    eomee_ccsd_singlet = eomee_ccsd_singlet
    matvec = eeccsd_matvec_singlet
    def get_diag(self, imds=None): ...
    def gen_matvec(self, imds=None, diag=None, **kwargs): ...
    amplitudes_to_vector: Incomplete
    vector_to_amplitudes: Incomplete
    spatial2spin: Incomplete
    def vector_size(self): ...

class EOMEETriplet(EOMEE):
    kernel = eomee_ccsd_triplet
    eomee_ccsd_triplet = eomee_ccsd_triplet
    matvec = eeccsd_matvec_triplet
    def get_diag(self, imds=None): ...
    def gen_matvec(self, imds=None, diag=None, **kwargs): ...
    amplitudes_to_vector: Incomplete
    vector_to_amplitudes: Incomplete
    spatial2spin: Incomplete
    def vector_size(self): ...

class EOMEESpinFlip(EOMEE):
    kernel = eomsf_ccsd
    eomsf_ccsd = eomsf_ccsd
    matvec = eeccsd_matvec_sf
    def get_diag(self, imds=None): ...
    def gen_matvec(self, imds=None, diag=None, **kwargs): ...
    amplitudes_to_vector: Incomplete
    vector_to_amplitudes: Incomplete
    spatial2spin: Incomplete
    def vector_size(self): ...

class _IMDS:
    verbose: Incomplete
    stdout: Incomplete
    max_memory: Incomplete
    t1: Incomplete
    t2: Incomplete
    eris: Incomplete
    def __init__(self, cc, eris=None) -> None: ...
    Woooo: Incomplete
    Wooov: Incomplete
    Wovoo: Incomplete
    def make_ip(self, ip_partition=None): ...
    def make_t3p2_ip(self, cc, ip_partition=None): ...
    Wvovv: Incomplete
    Wvvvo: Incomplete
    Wvvvv: Incomplete
    def make_ea(self, ea_partition=None): ...
    def make_t3p2_ea(self, cc, ea_partition=None): ...
    saved: Incomplete
    wvOvV: Incomplete
    woVvO: Incomplete
    woVVo: Incomplete
    woOoV: Incomplete
    Fov: Incomplete
    Foo: Incomplete
    Fvv: Incomplete
    woOoO: Incomplete
    woVoO: Incomplete
    made_ee_imds: bool
    def make_ee(self): ...
