from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, lib as lib
from pyscf.cc import ccsd as ccsd
from pyscf.lib import logger as logger, module_method as module_method
from numpy import bool, float64, ndarray
from pyscf.cc.ccsd import CCSD, CCSDBase
from pyscf.cc.eom_gccsd import EOMEA_Ta, EOMEE, EOMIP, EOMIP_Ta
from pyscf.lib.numpy_helper import NPArrayWithTag
from typing import Callable, List, Optional, Tuple, Union

def kernel(eom: "EOM", nroots: int = 1, koopmans: bool = False, guess: Optional[List[ndarray]]=None, left: bool = False, eris: Optional[Union[Incomplete, Incomplete, Incomplete]]=None, imds: Optional[Union[Incomplete, Incomplete, Incomplete]]=None, **kwargs) -> Union[Tuple[ndarray, ndarray, List[ndarray]], Tuple[bool, float64, ndarray]]: ...

class EOM(lib.StreamObject):
    mol: Incomplete
    verbose: Incomplete
    stdout: Incomplete
    max_memory: Incomplete
    max_space: Incomplete
    max_cycle: Incomplete
    conv_tol: Incomplete
    partition: Incomplete
    e: Incomplete
    v: Incomplete
    nocc: Incomplete
    nmo: Incomplete
    def __init__(self, cc: CCSDBase) -> None: ...
    def dump_flags(self, verbose: None=None) -> "EOM": ...
    def reset(self, mol=None): ...

def perturbed_ccsd_kernel(eom: EOM, nroots: int = 1, koopmans: bool = False, right_guess: None=None, left_guess: None=None, eris: None=None, imds: None=None) -> List[float64]: ...
def ipccsd(eom: EOM, nroots: int = 1, left: bool = False, koopmans: bool = False, guess: Optional[List[ndarray]]=None, partition: Optional[str]=None, eris: None=None, imds: None=None) -> Union[Tuple[ndarray, List[ndarray]], Tuple[float64, ndarray]]: ...
def ipccsd_star(eom: Union[EOMIP, EOMIP_Ta, EOMIP_Ta, EOMIP], nroots: int = 1, koopmans: bool = False, right_guess: None=None, left_guess: None=None, eris: None=None, imds: None=None) -> List[float64]: ...
def vector_to_amplitudes_ip(vector: ndarray, nmo: int, nocc: int) -> Tuple[ndarray, ndarray]: ...
def amplitudes_to_vector_ip(r1: ndarray, r2: ndarray) -> ndarray: ...
def spatial2spin_ip(rx: ndarray, orbspin: Optional[ndarray]=None) -> ndarray: ...
def ipccsd_matvec(eom: Union[EOMIP_Ta, EOMIP], vector: ndarray, imds: Optional[Incomplete]=None, diag: Optional[ndarray]=None) -> ndarray: ...
def lipccsd_matvec(eom: Union[EOMIP_Ta, EOMIP], vector: ndarray, imds: Optional[Incomplete]=None, diag: Optional[ndarray]=None) -> ndarray: ...
def ipccsd_diag(eom: Union[EOMIP_Ta, EOMIP], imds: Optional[Incomplete]=None) -> ndarray: ...
def ipccsd_star_contract(eom: Union[EOMIP_Ta, EOMIP], ipccsd_evals: ndarray, ipccsd_evecs: Union[ndarray, List[ndarray]], lipccsd_evecs: Union[ndarray, List[ndarray]], imds: Optional[Incomplete]=None) -> List[float64]: ...

class EOMIP(EOM):
    def get_init_guess(self, nroots: int = 1, koopmans: bool = True, diag: Optional[ndarray]=None) -> List[ndarray]: ...
    kernel = ipccsd
    ipccsd = ipccsd
    ipccsd_star = ipccsd_star
    matvec = ipccsd_matvec
    l_matvec = lipccsd_matvec
    get_diag = ipccsd_diag
    ccsd_star_contract = ipccsd_star_contract
    def ipccsd_star_contract(self, ipccsd_evals: ndarray, ipccsd_evecs: List[ndarray], lipccsd_evecs: List[ndarray], imds: None=None) -> List[float64]: ...
    def gen_matvec(self, imds: Optional[Union[Incomplete, Incomplete, Incomplete]]=None, left: bool = False, **kwargs) -> Tuple[Callable, ndarray]: ...
    amplitudes_to_vector: Incomplete
    vector_to_amplitudes: Incomplete
    spatial2spin: Incomplete
    def vector_size(self) -> int: ...
    def make_imds(self, eris: Optional[Union[Incomplete, Incomplete]]=None) -> Incomplete: ...
    @property
    def eip(self) -> float64: ...

class EOMIP_Ta(EOMIP):
    def make_imds(self, eris: None=None) -> Incomplete: ...

def eaccsd(eom: Union[Incomplete, Incomplete, Incomplete], nroots: int = 1, left: bool = False, koopmans: bool = False, guess: Optional[List[ndarray]]=None, partition: Optional[str]=None, eris: None=None, imds: None=None) -> Union[Tuple[ndarray, List[ndarray]], Tuple[float64, ndarray]]: ...
def eaccsd_star(eom: Union[EOMEA_Ta, Incomplete, EOMEA_Ta, Incomplete], nroots: int = 1, koopmans: bool = False, right_guess: None=None, left_guess: None=None, eris: None=None, imds: None=None, **kwargs) -> List[float64]: ...
def vector_to_amplitudes_ea(vector: ndarray, nmo: int, nocc: int) -> Tuple[ndarray, ndarray]: ...
def amplitudes_to_vector_ea(r1: ndarray, r2: ndarray) -> ndarray: ...
def spatial2spin_ea(rx: ndarray, orbspin: Optional[ndarray]=None) -> ndarray: ...
def eaccsd_matvec(eom: Union[EOMEA_Ta, Incomplete], vector: ndarray, imds: Optional[Incomplete]=None, diag: Optional[ndarray]=None) -> ndarray: ...
def leaccsd_matvec(eom: Union[EOMEA_Ta, Incomplete], vector: ndarray, imds: Optional[Incomplete]=None, diag: Optional[ndarray]=None) -> ndarray: ...
def eaccsd_diag(eom: Union[EOMEA_Ta, Incomplete], imds: Optional[Incomplete]=None) -> ndarray: ...
def eaccsd_star_contract(eom: Union[EOMEA_Ta, Incomplete], eaccsd_evals: ndarray, eaccsd_evecs: Union[ndarray, List[ndarray]], leaccsd_evecs: Union[ndarray, List[ndarray]], imds: Optional[Incomplete]=None) -> List[float64]: ...

class EOMEA(EOM):
    def get_init_guess(self, nroots: int = 1, koopmans: bool = True, diag: Optional[ndarray]=None) -> List[ndarray]: ...
    kernel = eaccsd
    eaccsd = eaccsd
    eaccsd_star = eaccsd_star
    matvec = eaccsd_matvec
    l_matvec = leaccsd_matvec
    get_diag = eaccsd_diag
    ccsd_star_contract = eaccsd_star_contract
    def eaccsd_star_contract(self, eaccsd_evals: ndarray, eaccsd_evecs: List[ndarray], leaccsd_evecs: List[ndarray], imds: None=None) -> List[float64]: ...
    def gen_matvec(self, imds: Optional[Union[Incomplete, Incomplete, Incomplete]]=None, left: bool = False, **kwargs) -> Tuple[Callable, ndarray]: ...
    amplitudes_to_vector: Incomplete
    vector_to_amplitudes: Incomplete
    spatial2spin: Incomplete
    def vector_size(self) -> int: ...
    def make_imds(self, eris: Optional[Union[Incomplete, Incomplete]]=None) -> Incomplete: ...
    @property
    def eea(self) -> float64: ...

class EOMEA_Ta(EOMEA):
    def make_imds(self, eris: None=None) -> Incomplete: ...

def eeccsd(eom: "EOMEE", nroots: int = 1, koopmans: bool = False, guess: Optional[List[Optional[ndarray]]]=None, eris: None=None, imds: None=None) -> Union[Tuple[float64, ndarray], Tuple[ndarray, List[Optional[ndarray]]]]: ...
def eomee_ccsd_singlet(eom: Union[EOMEETriplet, EOMEESinglet, EOMEE, EOMEESpinFlip], nroots: int = 1, koopmans: bool = False, guess: Optional[List[ndarray]]=None, eris: Optional[Union[Incomplete, Incomplete, Incomplete]]=None, imds: Optional[Incomplete]=None, diag: Optional[ndarray]=None) -> Union[Tuple[ndarray, List[ndarray]], Tuple[float64, ndarray]]: ...
def eomee_ccsd_triplet(eom: "EOMEETriplet", nroots: int = 1, koopmans: bool = False, guess: Optional[List[ndarray]]=None, eris: Optional[Union[Incomplete, Incomplete, Incomplete]]=None, imds: Optional[Incomplete]=None, diag: Optional[ndarray]=None) -> Tuple[float64, ndarray]: ...
def eomsf_ccsd(eom: "EOMEESpinFlip", nroots: int = 1, koopmans: bool = False, guess: Optional[List[ndarray]]=None, eris: Optional[Union[Incomplete, Incomplete, Incomplete]]=None, imds: Optional[Incomplete]=None, diag: Optional[ndarray]=None) -> Tuple[float64, ndarray]: ...
vector_to_amplitudes_ee = ccsd.vector_to_amplitudes
vector_to_amplitudes_singlet = ccsd.vector_to_amplitudes
amplitudes_to_vector_ee = ccsd.amplitudes_to_vector
amplitudes_to_vector_singlet = ccsd.amplitudes_to_vector

def spatial2spin_singlet(rx: ndarray, orbspin: Optional[ndarray]=None) -> NPArrayWithTag: ...
def amplitudes_to_vector_eomsf(t1: ndarray, t2: Union[ndarray, Tuple[ndarray, ndarray]], out: None=None) -> ndarray: ...
def vector_to_amplitudes_eomsf(vector: ndarray, nmo: int, nocc: int) -> Tuple[ndarray, Tuple[ndarray, ndarray]]: ...
def spatial2spin_eomsf(rx: Union[ndarray, Tuple[ndarray, ndarray]], orbspin: Optional[ndarray]=None) -> ndarray: ...
def amplitudes_to_vector_triplet(t1: ndarray, t2: Union[ndarray, Tuple[ndarray, ndarray]], out: None=None) -> ndarray: ...
def vector_to_amplitudes_triplet(vector: ndarray, nmo: int, nocc: int) -> Tuple[ndarray, Tuple[ndarray, ndarray]]: ...
def spatial2spin_triplet(rx, orbspin=None): ...
def eeccsd_matvec_singlet(eom: "EOMEESinglet", vector: ndarray, imds: Optional[Incomplete]=None) -> ndarray: ...
def eeccsd_matvec_triplet(eom: "EOMEETriplet", vector: ndarray, imds: Optional[Incomplete]=None) -> ndarray: ...
def eeccsd_matvec_sf(eom: "EOMEESpinFlip", vector: ndarray, imds: Optional[Incomplete]=None) -> ndarray: ...
def eeccsd_diag(eom: Union[EOMEESinglet, EOMEETriplet, EOMEE, EOMEESpinFlip], imds: Optional[Incomplete]=None) -> Tuple[ndarray, ndarray, ndarray]: ...

class EOMEE(EOM):
    def get_init_guess(self, nroots: int = 1, koopmans: bool = True, diag: Optional[ndarray]=None) -> List[ndarray]: ...
    kernel = eeccsd
    eeccsd = eeccsd
    get_diag = eeccsd_diag
    def vector_size(self) -> int: ...
    def make_imds(self, eris: Optional[Union[Incomplete, Incomplete, Incomplete]]=None) -> Incomplete: ...
    @property
    def eee(self) -> float64: ...

class EOMEESinglet(EOMEE):
    kernel = eomee_ccsd_singlet
    eomee_ccsd_singlet = eomee_ccsd_singlet
    matvec = eeccsd_matvec_singlet
    def get_diag(self, imds: Optional[Incomplete]=None) -> ndarray: ...
    def gen_matvec(self, imds: Optional[Incomplete]=None, diag: Optional[ndarray]=None, **kwargs) -> Tuple[Callable, ndarray]: ...
    amplitudes_to_vector: Incomplete
    vector_to_amplitudes: Incomplete
    spatial2spin: Incomplete
    def vector_size(self) -> int: ...

class EOMEETriplet(EOMEE):
    kernel = eomee_ccsd_triplet
    eomee_ccsd_triplet = eomee_ccsd_triplet
    matvec = eeccsd_matvec_triplet
    def get_diag(self, imds: Optional[Incomplete]=None) -> ndarray: ...
    def gen_matvec(self, imds: Optional[Incomplete]=None, diag: Optional[ndarray]=None, **kwargs) -> Tuple[Callable, ndarray]: ...
    amplitudes_to_vector: Incomplete
    vector_to_amplitudes: Incomplete
    spatial2spin: Incomplete
    def vector_size(self) -> int: ...

class EOMEESpinFlip(EOMEE):
    kernel = eomsf_ccsd
    eomsf_ccsd = eomsf_ccsd
    matvec = eeccsd_matvec_sf
    def get_diag(self, imds: Optional[Incomplete]=None) -> ndarray: ...
    def gen_matvec(self, imds: Optional[Incomplete]=None, diag: Optional[ndarray]=None, **kwargs) -> Tuple[Callable, ndarray]: ...
    amplitudes_to_vector: Incomplete
    vector_to_amplitudes: Incomplete
    spatial2spin: Incomplete
    def vector_size(self) -> int: ...

class _IMDS:
    verbose: Incomplete
    stdout: Incomplete
    max_memory: Incomplete
    t1: Incomplete
    t2: Incomplete
    eris: Incomplete
    def __init__(self, cc: Union[Incomplete, CCSD, Incomplete], eris: Optional[Union[Incomplete, Incomplete, Incomplete]]=None) -> None: ...
    Woooo: Incomplete
    Wooov: Incomplete
    Wovoo: Incomplete
    def make_ip(self, ip_partition: Optional[str]=None) -> Incomplete: ...
    def make_t3p2_ip(self, cc: CCSD, ip_partition: None=None) -> Incomplete: ...
    Wvovv: Incomplete
    Wvvvo: Incomplete
    Wvvvv: Incomplete
    def make_ea(self, ea_partition: Optional[str]=None) -> Incomplete: ...
    def make_t3p2_ea(self, cc: CCSD, ea_partition: None=None) -> Incomplete: ...
    saved: Incomplete
    wvOvV: Incomplete
    woVvO: Incomplete
    woVVo: Incomplete
    woOoV: Incomplete
    Fov: Incomplete
    Foo: Incomplete
    Fvv: Incomplete
    woOoO: Incomplete
    woVoO: Incomplete
    made_ee_imds: bool
    def make_ee(self) -> Incomplete: ...
