from _typeshed import Incomplete
from pyscf import lib as lib
from pyscf.cc import ccsd as ccsd, eom_rccsd as eom_rccsd, gccsd as gccsd
from pyscf.lib import logger as logger, module_method as module_method
from numpy import float64, ndarray
from pyscf.cc.gccsd import GCCSD, _PhysicistsERIs
from typing import Callable, List, Optional, Tuple, Union

def vector_to_amplitudes_ip(vector: ndarray, nmo: int, nocc: int) -> Tuple[ndarray, ndarray]: ...
def amplitudes_to_vector_ip(r1: ndarray, r2: ndarray) -> ndarray: ...
def ipccsd_matvec(eom: Union[EOMIP, EOMIP_Ta], vector: ndarray, imds: Optional[_IMDS]=None, diag: Optional[ndarray]=None) -> ndarray: ...
def lipccsd_matvec(eom: Union[EOMIP, EOMIP_Ta], vector: ndarray, imds: Optional[_IMDS]=None, diag: Optional[ndarray]=None) -> ndarray: ...
def ipccsd_diag(eom: Union[EOMIP, EOMIP_Ta], imds: Optional[_IMDS]=None) -> ndarray: ...
def ipccsd_star_contract(eom: Union[EOMIP, EOMIP_Ta], ipccsd_evals: ndarray, ipccsd_evecs: Union[ndarray, List[ndarray]], lipccsd_evecs: Union[ndarray, List[ndarray]], imds: Optional[_IMDS]=None) -> List[float64]: ...

class EOMIP(eom_rccsd.EOMIP):
    matvec = ipccsd_matvec
    l_matvec = lipccsd_matvec
    get_diag = ipccsd_diag
    ccsd_star_contract = ipccsd_star_contract
    amplitudes_to_vector: Incomplete
    vector_to_amplitudes: Incomplete
    def vector_size(self) -> int: ...
    def make_imds(self, eris: Optional[_PhysicistsERIs]=None) -> "_IMDS": ...

class EOMIP_Ta(EOMIP):
    def make_imds(self, eris: None=None) -> "_IMDS": ...

def vector_to_amplitudes_ea(vector: ndarray, nmo: int, nocc: int) -> Tuple[ndarray, ndarray]: ...
def amplitudes_to_vector_ea(r1: ndarray, r2: ndarray) -> ndarray: ...
def eaccsd_matvec(eom: Union[EOMEA_Ta, EOMEA], vector: ndarray, imds: Optional[_IMDS]=None, diag: Optional[ndarray]=None) -> ndarray: ...
def leaccsd_matvec(eom: Union[EOMEA_Ta, EOMEA], vector: ndarray, imds: Optional[_IMDS]=None, diag: Optional[ndarray]=None) -> ndarray: ...
def eaccsd_diag(eom: Union[EOMEA_Ta, EOMEA], imds: Optional[_IMDS]=None) -> ndarray: ...
def eaccsd_star_contract(eom: Union[EOMEA_Ta, EOMEA], eaccsd_evals: ndarray, eaccsd_evecs: Union[ndarray, List[ndarray]], leaccsd_evecs: Union[ndarray, List[ndarray]], imds: Optional[_IMDS]=None) -> List[float64]: ...

class EOMEA(eom_rccsd.EOMEA):
    matvec = eaccsd_matvec
    l_matvec = leaccsd_matvec
    get_diag = eaccsd_diag
    ccsd_star_contract = eaccsd_star_contract
    amplitudes_to_vector: Incomplete
    vector_to_amplitudes: Incomplete
    def vector_size(self) -> int: ...
    def make_imds(self, eris: Optional[_PhysicistsERIs]=None) -> "_IMDS": ...

class EOMEA_Ta(EOMEA):
    def make_imds(self, eris: None=None) -> "_IMDS": ...
vector_to_amplitudes_ee = ccsd.vector_to_amplitudes_s4
amplitudes_to_vector_ee = ccsd.amplitudes_to_vector_s4

def eeccsd_matvec(eom: "EOMEE", vector: ndarray, imds: Optional[_IMDS]=None, diag: None=None) -> ndarray: ...
def eeccsd_diag(eom: "EOMEE", imds: Optional[_IMDS]=None) -> ndarray: ...
def eeccsd(eom: "EOMEE", nroots: int = 1, koopmans: bool = False, guess: Optional[List[ndarray]]=None, eris: None=None, imds: None=None) -> Tuple[ndarray, List[ndarray]]: ...

class EOMEE(eom_rccsd.EOMEE):
    kernel = eeccsd
    eeccsd = eeccsd
    matvec = eeccsd_matvec
    get_diag = eeccsd_diag
    def gen_matvec(self, imds: Optional[_IMDS]=None, **kwargs) -> Tuple[Callable, ndarray]: ...
    amplitudes_to_vector: Incomplete
    vector_to_amplitudes: Incomplete
    def vector_size(self) -> int: ...
    def make_imds(self, eris: Optional[_PhysicistsERIs]=None) -> "_IMDS": ...

class _IMDS:
    verbose: Incomplete
    stdout: Incomplete
    t1: Incomplete
    t2: Incomplete
    eris: Incomplete
    made_ip_imds: bool
    made_ea_imds: bool
    made_ee_imds: bool
    def __init__(self, cc: GCCSD, eris: Optional[_PhysicistsERIs]=None) -> None: ...
    Woooo: Incomplete
    Wooov: Incomplete
    Wovoo: Incomplete
    def make_ip(self) -> "_IMDS": ...
    def make_t3p2_ip(self, cc: GCCSD) -> "_IMDS": ...
    Wvovv: Incomplete
    Wvvvv: Incomplete
    Wvvvo: Incomplete
    def make_ea(self) -> "_IMDS": ...
    def make_t3p2_ea(self, cc: GCCSD) -> "_IMDS": ...
    def make_ee(self) -> "_IMDS": ...
