from _typeshed import Incomplete
from pyscf import lib as lib
from pyscf.cc import ccsd as ccsd, eom_rccsd as eom_rccsd, gccsd as gccsd
from pyscf.lib import logger as logger, module_method as module_method

def vector_to_amplitudes_ip(vector, nmo, nocc): ...
def amplitudes_to_vector_ip(r1, r2): ...
def ipccsd_matvec(eom, vector, imds=None, diag=None): ...
def lipccsd_matvec(eom, vector, imds=None, diag=None): ...
def ipccsd_diag(eom, imds=None): ...
def ipccsd_star_contract(eom, ipccsd_evals, ipccsd_evecs, lipccsd_evecs, imds=None): ...

class EOMIP(eom_rccsd.EOMIP):
    matvec = ipccsd_matvec
    l_matvec = lipccsd_matvec
    get_diag = ipccsd_diag
    ccsd_star_contract = ipccsd_star_contract
    amplitudes_to_vector: Incomplete
    vector_to_amplitudes: Incomplete
    def vector_size(self): ...
    def make_imds(self, eris=None): ...

class EOMIP_Ta(EOMIP):
    def make_imds(self, eris=None): ...

def vector_to_amplitudes_ea(vector, nmo, nocc): ...
def amplitudes_to_vector_ea(r1, r2): ...
def eaccsd_matvec(eom, vector, imds=None, diag=None): ...
def leaccsd_matvec(eom, vector, imds=None, diag=None): ...
def eaccsd_diag(eom, imds=None): ...
def eaccsd_star_contract(eom, eaccsd_evals, eaccsd_evecs, leaccsd_evecs, imds=None): ...

class EOMEA(eom_rccsd.EOMEA):
    matvec = eaccsd_matvec
    l_matvec = leaccsd_matvec
    get_diag = eaccsd_diag
    ccsd_star_contract = eaccsd_star_contract
    amplitudes_to_vector: Incomplete
    vector_to_amplitudes: Incomplete
    def vector_size(self): ...
    def make_imds(self, eris=None): ...

class EOMEA_Ta(EOMEA):
    def make_imds(self, eris=None): ...
vector_to_amplitudes_ee = ccsd.vector_to_amplitudes_s4
amplitudes_to_vector_ee = ccsd.amplitudes_to_vector_s4

def eeccsd_matvec(eom, vector, imds=None, diag=None): ...
def eeccsd_diag(eom, imds=None): ...
def eeccsd(eom, nroots: int = 1, koopmans: bool = False, guess=None, eris=None, imds=None): ...

class EOMEE(eom_rccsd.EOMEE):
    kernel = eeccsd
    eeccsd = eeccsd
    matvec = eeccsd_matvec
    get_diag = eeccsd_diag
    def gen_matvec(self, imds=None, **kwargs): ...
    amplitudes_to_vector: Incomplete
    vector_to_amplitudes: Incomplete
    def vector_size(self): ...
    def make_imds(self, eris=None): ...

class _IMDS:
    verbose: Incomplete
    stdout: Incomplete
    t1: Incomplete
    t2: Incomplete
    eris: Incomplete
    made_ip_imds: bool
    made_ea_imds: bool
    made_ee_imds: bool
    def __init__(self, cc, eris=None) -> None: ...
    Woooo: Incomplete
    Wooov: Incomplete
    Wovoo: Incomplete
    def make_ip(self): ...
    def make_t3p2_ip(self, cc): ...
    Wvovv: Incomplete
    Wvvvv: Incomplete
    Wvvvo: Incomplete
    def make_ea(self): ...
    def make_t3p2_ea(self, cc): ...
    def make_ee(self): ...
