from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, lib as lib, scf as scf
from pyscf.cc import ccsd as ccsd
from pyscf.cc.addons import spatial2spin as spatial2spin, spin2spatial as spin2spatial
from pyscf.lib import logger as logger
from numpy import float64, ndarray
from pyscf.gto.mole import Mole
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.ci.cisd import GCISD
from pyscf.pbc.scf.kghf import KGHF
from pyscf.scf.ghf import GHF
from typing import Any, Callable, List, Optional, Tuple, Union

MEMORYMIN: Incomplete
einsum = lib.einsum

def update_amps(cc: "GCCSD", t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: "_PhysicistsERIs") -> Tuple[ndarray, ndarray]: ...
def energy(cc: "GCCSD", t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: "_PhysicistsERIs") -> float64: ...
vector_to_amplitudes = ccsd.vector_to_amplitudes_s4
amplitudes_to_vector = ccsd.amplitudes_to_vector_s4

def amplitudes_from_rccsd(t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], orbspin: Optional[ndarray]=None) -> Tuple[NPArrayWithTag, NPArrayWithTag]: ...

class GCCSD(ccsd.CCSDBase):
    conv_tol: Incomplete
    conv_tol_normt: Incomplete
    def __init__(self, mf: Union[KGHF, GHF], frozen: Optional[Union[int, List[List[int]], List[List[Union[int, Any]]], List[int]]]=None, mo_coeff: None=None, mo_occ: None=None) -> None: ...
    emp2: Incomplete
    def init_amps(self, eris: Optional[_PhysicistsERIs]=None) -> Tuple[float64, ndarray, ndarray]: ...
    energy = energy
    update_amps = update_amps
    def kernel(self, t1: Optional[ndarray]=None, t2: Optional[ndarray]=None, eris: Optional[_PhysicistsERIs]=None, mbpt2: bool = False) -> Union[Tuple[float64, NPArrayWithTag, NPArrayWithTag], Tuple[float64, ndarray, ndarray], Tuple[float, ndarray, ndarray]]: ...
    t1: Incomplete
    mo_coeff: Incomplete
    t2: Incomplete
    def ccsd(self, t1: Optional[ndarray]=None, t2: Optional[ndarray]=None, eris: Optional[_PhysicistsERIs]=None, mbpt2: bool = False) -> Union[Tuple[float64, NPArrayWithTag, NPArrayWithTag], Tuple[float64, ndarray, ndarray], Tuple[float, ndarray, ndarray]]: ...
    def amplitudes_to_vector(self, t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], out: None=None) -> ndarray: ...
    def vector_to_amplitudes(self, vec: ndarray, nmo: None=None, nocc: None=None) -> Tuple[ndarray, ndarray]: ...
    def vector_size(self, nmo: None=None, nocc: None=None) -> int: ...
    def amplitudes_from_rccsd(self, t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], orbspin: Optional[ndarray]=None) -> Tuple[NPArrayWithTag, NPArrayWithTag]: ...
    def solve_lambda(self, t1: Optional[ndarray]=None, t2: Optional[ndarray]=None, l1: None=None, l2: None=None, eris: Optional[_PhysicistsERIs]=None) -> Tuple[ndarray, ndarray]: ...
    def ccsd_t(self, t1: None=None, t2: None=None, eris: None=None) -> float64: ...
    def ipccsd(self, nroots: int = 1, left: bool = False, koopmans: bool = False, guess: Optional[List[ndarray]]=None, partition: None=None, eris: None=None) -> Union[Tuple[float64, ndarray], Tuple[ndarray, List[ndarray]]]: ...
    def eaccsd(self, nroots: int = 1, left: bool = False, koopmans: bool = False, guess: Optional[List[ndarray]]=None, partition: None=None, eris: None=None) -> Union[Tuple[float64, ndarray], Tuple[ndarray, List[ndarray]]]: ...
    def eeccsd(self, nroots: int = 1, koopmans: bool = False, guess: Optional[List[ndarray]]=None, eris: None=None) -> Tuple[ndarray, List[ndarray]]: ...
    def eomip_method(self): ...
    def eomea_method(self): ...
    def eomee_method(self): ...
    def make_rdm1(self, t1: Optional[NPArrayWithTag]=None, t2: Optional[NPArrayWithTag]=None, l1: Optional[NPArrayWithTag]=None, l2: Optional[NPArrayWithTag]=None, ao_repr: bool = False, with_frozen: bool = True, with_mf: bool = True) -> ndarray: ...
    def make_rdm2(self, t1: Optional[NPArrayWithTag]=None, t2: Optional[NPArrayWithTag]=None, l1: Optional[NPArrayWithTag]=None, l2: Optional[NPArrayWithTag]=None, ao_repr: bool = False, with_frozen: bool = True, with_dm1: bool = True) -> ndarray: ...
    def ao2mo(self, mo_coeff: Optional[Union[NPArrayWithTag, ndarray]]=None) -> "_PhysicistsERIs": ...
    def amplitudes_from_ccsd(self, t1: ndarray, t2: ndarray) -> Tuple[NPArrayWithTag, NPArrayWithTag]: ...
    def spatial2spin(self, tx: Union[ndarray, Tuple[ndarray, ndarray], List[ndarray], Tuple[ndarray, ndarray, ndarray]], orbspin: Optional[ndarray]=None) -> NPArrayWithTag: ...
    def spin2spatial(self, tx: Union[ndarray, NPArrayWithTag], orbspin: Optional[ndarray]=None) -> Union[Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]]: ...
    to_gpu = lib.to_gpu
CCSD = GCCSD

class _PhysicistsERIs:
    mol: Incomplete
    mo_coeff: Incomplete
    nocc: Incomplete
    fock: Incomplete
    orbspin: Incomplete
    oooo: Incomplete
    ooov: Incomplete
    oovv: Incomplete
    ovvo: Incomplete
    ovov: Incomplete
    ovvv: Incomplete
    vvvv: Incomplete
    def __init__(self, mol: Optional[Mole]=None) -> None: ...
