from pyscf import lib as lib
from pyscf.cc import ccsd_lambda as ccsd_lambda
from pyscf.lib import logger as logger

einsum = lib.einsum

def kernel(mycc, eris=None, t1=None, t2=None, l1=None, l2=None, max_cycle: int = 50, tol: float = 1e-08, verbose=...): ...
def make_intermediates(mycc, t1, t2, eris): ...
def update_lambda(mycc, t1, t2, l1, l2, eris, imds): ...
