from pyscf import lib as lib
from pyscf.lib import logger as logger

einsum = lib.einsum

def make_tau(t2, t1a, t1b, fac: int = 1, out=None): ...
def cc_Fvv(t1, t2, eris): ...
def cc_Foo(t1, t2, eris): ...
def cc_Fov(t1, t2, eris): ...
def cc_Woooo(t1, t2, eris): ...
def cc_Wvvvv(t1, t2, eris): ...
def cc_Wovvo(t1, t2, eris): ...
def Fvv(t1, t2, eris): ...
def Foo(t1, t2, eris): ...
def Fov(t1, t2, eris): ...
def Woooo(t1, t2, eris): ...
def Wvvvv(t1, t2, eris): ...
def Wovvo(t1, t2, eris): ...
def Wooov(t1, t2, eris): ...
def Wvovv(t1, t2, eris): ...
def Wovoo(t1, t2, eris): ...
def Wvvvo(t1, t2, eris, _Wvvvv=None): ...
def get_t3p2_imds_slow(cc, t1, t2, eris=None, t3p2_ip_out=None, t3p2_ea_out=None): ...
