from pyscf import lib as lib
from pyscf.lib import logger as logger
from numpy import float64, ndarray
from pyscf.cc.gccsd import GCCSD, _PhysicistsERIs
from pyscf.lib.numpy_helper import NPArrayWithTag
from typing import Optional, Tuple, Union

einsum = lib.einsum

def make_tau(t2: Union[ndarray, NPArrayWithTag], t1a: Union[ndarray, NPArrayWithTag], t1b: Union[ndarray, NPArrayWithTag], fac: Union[float, int] = 1, out: None=None) -> ndarray: ...
def cc_Fvv(t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs) -> ndarray: ...
def cc_Foo(t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs) -> ndarray: ...
def cc_Fov(t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs) -> ndarray: ...
def cc_Woooo(t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs) -> ndarray: ...
def cc_Wvvvv(t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs) -> ndarray: ...
def cc_Wovvo(t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs) -> ndarray: ...
def Fvv(t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs) -> ndarray: ...
def Foo(t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs) -> ndarray: ...
def Fov(t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs) -> ndarray: ...
def Woooo(t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs) -> ndarray: ...
def Wvvvv(t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs) -> ndarray: ...
def Wovvo(t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs) -> ndarray: ...
def Wooov(t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs) -> ndarray: ...
def Wvovv(t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs) -> ndarray: ...
def Wovoo(t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs) -> ndarray: ...
def Wvvvo(t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: _PhysicistsERIs, _Wvvvv: Optional[ndarray]=None) -> ndarray: ...
def get_t3p2_imds_slow(cc: GCCSD, t1: Union[ndarray, NPArrayWithTag], t2: Union[ndarray, NPArrayWithTag], eris: Optional[_PhysicistsERIs]=None, t3p2_ip_out: None=None, t3p2_ea_out: None=None) -> Tuple[float64, ndarray, ndarray, ndarray, ndarray]: ...
