from _typeshed import Incomplete
from pyscf import ao2mo as ao2mo, cc as cc, lib as lib
from pyscf.agf2 import mpi_helper as mpi_helper
from pyscf.lib import logger as logger

def kernel(gfccsd, hole_moments=None, part_moments=None, t1=None, t2=None, l1=None, l2=None, eris=None, imds=None, verbose=None): ...
def mat_sqrt(m, hermi: bool = False): ...
def mat_isqrt(m, tol: float = 1e-16, hermi: bool = False): ...
def build_block_tridiagonal(a, b, c=None): ...
def eig_block_tridiagonal(gfccsd, a, b, c, orth=None): ...
def eigh_block_tridiagonal(gfccsd, a, b, orth=None): ...
def block_lanczos_symm(gfccsd, moments, verbose=None): ...
def block_lanczos_nosymm(gfccsd, moments, verbose=None): ...
def contract_ket_hole(gfccsd, eom, t1, t2, v, orb): ...
def build_ket_hole(gfccsd, eom, t1, t2, orb): ...
def build_bra_hole(gfccsd, eom, t1, t2, l1, l2, orb): ...
def contract_ket_part(gfccsd, eom, t1, t2, v, orb): ...
def build_ket_part(gfccsd, eom, t1, t2, orb): ...
def build_bra_part(gfccsd, eom, t1, t2, l1, l2, orb): ...

class MomGFCCSD(lib.StreamObject):
    verbose: Incomplete
    stdout: Incomplete
    niter: Incomplete
    weight_tol: float
    hermi_moments: bool
    hermi_solver: bool
    eh: Incomplete
    ep: Incomplete
    vh: Incomplete
    vp: Incomplete
    chkfile: Incomplete
    def __init__(self, mycc, niter=(2, 2)) -> None: ...
    def dump_flags(self, verbose=None) -> None: ...
    def reset(self, mol=None): ...
    @property
    def eomip_method(self): ...
    @property
    def eomea_method(self): ...
    build_bra_hole = build_bra_hole
    build_bra_part = build_bra_part
    contract_ket_hole = contract_ket_hole
    contract_ket_part = contract_ket_part
    def make_imds(self, eris=None, ip: bool = True, ea: bool = True): ...
    def build_hole_moments(self, t1=None, t2=None, l1=None, l2=None, imds=None, niter=None): ...
    def build_part_moments(self, t1=None, t2=None, l1=None, l2=None, imds=None, niter=None): ...
    def make_rdm1(self, ao_repr: bool = False, eris=None, imds=None): ...
    def kernel(self, **kwargs): ...
    def dump_chk(self, chkfile=None, key: str = 'gfccsd'): ...
    def update_from_chk_(self, chkfile=None, key: str = 'gfccsd') -> None: ...
    update = update_from_chk_
    update_from_chk = update_from_chk_
    def ipgfccsd(self, nroots: int = 5): ...
    def eagfccsd(self, nroots: int = 5): ...
    @property
    def nmo(self): ...
    @property
    def nocc(self): ...
