from _typeshed import Incomplete
from pyscf import ao2mo as ao2mo, cc as cc, lib as lib
from pyscf.agf2 import mpi_helper as mpi_helper
from pyscf.lib import logger as logger
from numpy import float64, ndarray
from pyscf.cc.ccsd import CCSD
from pyscf.cc.eom_rccsd import EOMEA, EOMIP, _IMDS
from typing import Optional, Tuple, Union

def kernel(gfccsd: "MomGFCCSD", hole_moments: Optional[ndarray]=None, part_moments: Optional[ndarray]=None, t1: Optional[ndarray]=None, t2: Optional[ndarray]=None, l1: Optional[ndarray]=None, l2: Optional[ndarray]=None, eris: None=None, imds: Optional[_IMDS]=None, verbose: None=None) -> Tuple[ndarray, Tuple[ndarray, ndarray], ndarray, Tuple[ndarray, ndarray]]: ...
def mat_sqrt(m: ndarray, hermi: bool = False) -> ndarray: ...
def mat_isqrt(m: ndarray, tol: float = 1e-16, hermi: bool = False) -> ndarray: ...
def build_block_tridiagonal(a: ndarray, b: ndarray, c: Optional[ndarray]=None) -> ndarray: ...
def eig_block_tridiagonal(gfccsd: "MomGFCCSD", a: ndarray, b: ndarray, c: ndarray, orth: Optional[ndarray]=None) -> Tuple[ndarray, Tuple[ndarray, ndarray]]: ...
def eigh_block_tridiagonal(gfccsd: "MomGFCCSD", a: ndarray, b: ndarray, orth: Optional[ndarray]=None) -> Tuple[ndarray, Tuple[ndarray, ndarray]]: ...
def block_lanczos_symm(gfccsd: "MomGFCCSD", moments: ndarray, verbose: None=None) -> Tuple[ndarray, ndarray]: ...
def block_lanczos_nosymm(gfccsd: "MomGFCCSD", moments: ndarray, verbose: None=None) -> Tuple[ndarray, ndarray, ndarray]: ...
def contract_ket_hole(gfccsd: "MomGFCCSD", eom: EOMIP, t1: ndarray, t2: ndarray, v: ndarray, orb: int) -> float64: ...
def build_ket_hole(gfccsd, eom, t1, t2, orb): ...
def build_bra_hole(gfccsd: "MomGFCCSD", eom: EOMIP, t1: ndarray, t2: ndarray, l1: ndarray, l2: ndarray, orb: int) -> ndarray: ...
def contract_ket_part(gfccsd: "MomGFCCSD", eom: EOMEA, t1: ndarray, t2: ndarray, v: ndarray, orb: int) -> float64: ...
def build_ket_part(gfccsd, eom, t1, t2, orb): ...
def build_bra_part(gfccsd: "MomGFCCSD", eom: EOMEA, t1: ndarray, t2: ndarray, l1: ndarray, l2: ndarray, orb: int) -> ndarray: ...

class MomGFCCSD(lib.StreamObject):
    verbose: Incomplete
    stdout: Incomplete
    niter: Incomplete
    weight_tol: float
    hermi_moments: bool
    hermi_solver: bool
    eh: Incomplete
    ep: Incomplete
    vh: Incomplete
    vp: Incomplete
    chkfile: Incomplete
    def __init__(self, mycc: CCSD, niter: Tuple[int, int]=(2, 2)) -> None: ...
    def dump_flags(self, verbose: None=None) -> None: ...
    def reset(self, mol: None=None) -> "MomGFCCSD": ...
    @property
    def eomip_method(self) -> EOMIP: ...
    @property
    def eomea_method(self) -> EOMEA: ...
    build_bra_hole = build_bra_hole
    build_bra_part = build_bra_part
    contract_ket_hole = contract_ket_hole
    contract_ket_part = contract_ket_part
    def make_imds(self, eris: None=None, ip: bool = True, ea: bool = True) -> _IMDS: ...
    def build_hole_moments(self, t1: Optional[ndarray]=None, t2: Optional[ndarray]=None, l1: Optional[ndarray]=None, l2: Optional[ndarray]=None, imds: Optional[_IMDS]=None, niter: Optional[int]=None) -> ndarray: ...
    def build_part_moments(self, t1: Optional[ndarray]=None, t2: Optional[ndarray]=None, l1: Optional[ndarray]=None, l2: Optional[ndarray]=None, imds: Optional[_IMDS]=None, niter: None=None) -> ndarray: ...
    def make_rdm1(self, ao_repr: bool = False, eris: None=None, imds: None=None) -> ndarray: ...
    def kernel(self, **kwargs) -> Tuple[ndarray, Tuple[ndarray, ndarray], ndarray, Tuple[ndarray, ndarray]]: ...
    def dump_chk(self, chkfile: Optional[str]=None, key: str = 'gfccsd') -> "MomGFCCSD": ...
    def update_from_chk_(self, chkfile: Optional[str]=None, key: str = 'gfccsd') -> None: ...
    update = update_from_chk_
    update_from_chk = update_from_chk_
    def ipgfccsd(self, nroots: int = 5) -> Union[Tuple[float64, ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]]: ...
    def eagfccsd(self, nroots: int = 5) -> Union[Tuple[ndarray, ndarray, ndarray], Tuple[float64, ndarray, ndarray]]: ...
    @property
    def nmo(self) -> int: ...
    @property
    def nocc(self) -> int: ...
