from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.cc import rccsd_slow as rccsd
from pyscf.lib import logger as logger

BLKMIN: Incomplete
MEMORYMIN: Incomplete

def kernel(mycc, eris=None, t1=None, t2=None, max_cycle: int = 50, tol: float = 1e-08, tolnormt: float = 1e-06, verbose=None): ...
def update_amps(cc, t1, t2, eris): ...

class QCISD(rccsd.RCCSD):
    def kernel(self, t1=None, t2=None, eris=None): ...
    e_hf: Incomplete
    def qcisd(self, t1=None, t2=None, eris=None): ...
    def energy(self, t1=None, t2=None, eris=None): ...
    update_amps = update_amps
    def qcisd_t(self, t1=None, t2=None, eris=None): ...
    def density_fit(self, auxbasis=None, with_df=None) -> None: ...
