from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, lib as lib
from pyscf.cc import ccsd as ccsd
from pyscf.lib import logger as logger
from pyscf.mp.mp2 import get_e_hf as get_e_hf, get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc
from numpy import float64, int64, ndarray
from pyscf.cc.ccsd import CCSDBase
from pyscf.cc.rccsdtq import _IMDS
from pyscf.lib.diis import DIIS
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.scf.hf import RHF
from typing import List, Optional, Tuple, Type, Union

def t3_spin_summation_inplace_(A: ndarray, nocc3: int, nvir: int, pattern: str, alpha: float = 1.0, beta: float = 0.0) -> ndarray: ...
def unpack_t3_tri2block_(t3: ndarray, t3_blk: ndarray, map_: ndarray, mask: ndarray, i0: int, i1: int, j0: int, j1: int, k0: int, k1: int, nocc: int, nvir: int, blk_i: int, blk_j: int, blk_k: int) -> ndarray: ...
def unpack_t3_tri2single_pair_(t3: ndarray, t3_blk: ndarray, map_: ndarray, mask: ndarray, i0: int, j0: int, k0: int, nocc: int, nvir: int) -> ndarray: ...
def unpack_t3_tri2block_pair_(t3: ndarray, t3_blk: ndarray, map_: ndarray, mask: ndarray, i0: int, i1: int, j0: int, j1: int, k0: int, k1: int, nocc: int, nvir: int, blk_i: int, blk_j: int, blk_k: int) -> ndarray: ...
def accumulate_t3_block2tri_(t3: ndarray, t3_blk: ndarray, map_: ndarray, i0: int, i1: int, j0: int, j1: int, k0: int, k1: int, nocc: int, nvir: int, blk_i: int, blk_j: int, blk_k: int, alpha: float, beta: float) -> ndarray: ...
def accumulate_t3_single2tri_(t3: ndarray, t3_blk: ndarray, map_: ndarray, i0: int, j0: int, k0: int, nocc: int, nvir: int, alpha: float, beta: float) -> ndarray: ...
def setup_tri2block_rhf(mycc: Union[Incomplete, Incomplete]) -> Union[Tuple[ndarray, ndarray, List[Tuple[int, int, int, int]]], Tuple[ndarray, ndarray, List[Tuple[int, int, int, int, int]]]]: ...
def update_xy(mycc: Union[Incomplete, Incomplete, Incomplete, Incomplete], t1: ndarray) -> Tuple[ndarray, ndarray]: ...
def update_fock(mycc: Union[Incomplete, Incomplete, Incomplete, Incomplete], x: ndarray, y: ndarray, t1: ndarray, eris: Incomplete) -> ndarray: ...
def update_eris(mycc: Union[Incomplete, Incomplete, Incomplete, Incomplete], x: ndarray, y: ndarray, eris: Incomplete) -> ndarray: ...
def update_t1_fock_eris(mycc: Union[Incomplete, Incomplete, Incomplete, Incomplete], imds: Union[Type[_IMDS], _IMDS, _IMDS], t1: ndarray, eris: Optional[Incomplete]=None) -> Union[Type[_IMDS], _IMDS, _IMDS]: ...
def symmetrize_tamps_tri_(r: ndarray, nocc: int) -> ndarray: ...
def purify_tamps_tri_(r: ndarray, nocc: int) -> ndarray: ...
def init_amps_rhf(mycc: Union[Incomplete, Incomplete, Incomplete, Incomplete], eris: Optional[Incomplete]=None) -> Tuple[float64, List[ndarray]]: ...
def energy_rhf(mycc: Union[Incomplete, Incomplete, Incomplete, Incomplete], tamps: List[ndarray], eris: Optional[Incomplete]=None) -> NPArrayWithTag: ...
def intermediates_t1t2(mycc: Union[Incomplete, Incomplete, Incomplete, Incomplete], imds: Union[Type[_IMDS], _IMDS, _IMDS], t2: ndarray) -> Union[Type[_IMDS], _IMDS, _IMDS]: ...
def compute_r1r2(mycc: Union[Incomplete, Incomplete, Incomplete, Incomplete], imds: Union[Type[_IMDS], _IMDS, _IMDS], t2: ndarray) -> Tuple[ndarray, ndarray]: ...
def r1r2_add_t3_tri_(mycc: Incomplete, imds: "_IMDS", r1: ndarray, r2: ndarray, t3: ndarray) -> Tuple[ndarray, ndarray]: ...
def r1r2_divide_e_(mycc: Union[Incomplete, Incomplete, Incomplete, Incomplete], r1: ndarray, r2: ndarray, mo_energy: ndarray) -> Tuple[ndarray, ndarray]: ...
def intermediates_t3(mycc: Union[Incomplete, Incomplete, Incomplete, Incomplete], imds: Union[Type[_IMDS], _IMDS, _IMDS], t2: ndarray) -> Union[Type[_IMDS], _IMDS, _IMDS]: ...
def intermediates_t3_add_t3_tri(mycc: Incomplete, imds: "_IMDS", t3: ndarray) -> "_IMDS": ...
def compute_r3_tri(mycc: Incomplete, imds: "_IMDS", t2: ndarray, t3: ndarray) -> ndarray: ...
def r3_tri_divide_e_(mycc: Incomplete, r3: ndarray, mo_energy: ndarray) -> ndarray: ...
def update_amps_rccsdt_tri_(mycc: Incomplete, tamps: List[ndarray], eris: Incomplete) -> List[float64]: ...
def amplitudes_to_vector_rhf(mycc: Union[Incomplete, Incomplete, Incomplete, Incomplete], tamps: List[ndarray]) -> ndarray: ...
def vector_to_amplitudes_rhf(mycc: Union[Incomplete, Incomplete, Incomplete, Incomplete], vector: ndarray) -> List[ndarray]: ...
def restore_t_(t: ndarray, nocc: int, order: int = 1, do_tri: bool = False, unique_tamps_map: Optional[List[Union[List[slice], Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray], Tuple[ndarray, ndarray, ndarray, ndarray]]]]=None) -> ndarray: ...
def run_diis(mycc: CCSDBase, tamps: List[Union[Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray], List[ndarray], ndarray]], istep: int, normt: float64, de: float64, adiis: Optional[DIIS]) -> List[Union[Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray], List[ndarray], ndarray]]: ...
def kernel(mycc: CCSDBase, eris: Optional[Union[Incomplete, Incomplete]]=None, tamps: Optional[Union[List[ndarray], List[List[ndarray]]]]=None, tol: float = 1e-08, tolnormt: float = 1e-06, max_cycle: int = 50, verbose: int = 5, callback: None=None) -> Union[Tuple[bool, NPArrayWithTag, List[ndarray]], Tuple[bool, NPArrayWithTag, List[List[ndarray]]]]: ...
def restore_from_diis_(mycc: Union[Incomplete, Incomplete, Incomplete, Incomplete], diis_file: str, inplace: bool = True) -> Union[Incomplete, Incomplete, Incomplete, Incomplete]: ...
def build_unique_tamps_map_rhf(mycc: Union[Incomplete, Incomplete, Incomplete, Incomplete]) -> List[List[Union[List[slice], Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray], Tuple[ndarray, ndarray, ndarray, ndarray]]]]: ...
def dump_flags(mycc: CCSDBase, verbose: None=None) -> CCSDBase: ...
def vector_size_rhf(mycc: Union[Incomplete, Incomplete, Incomplete, Incomplete], nmo: None=None, nocc: None=None) -> int64: ...
def format_size(i: Union[float, int], suffix: str = 'B') -> str: ...
def memory_estimate_log_rccsdt(mycc: Union[Incomplete, Incomplete]) -> Union[Incomplete, Incomplete]: ...
def dump_chk(mycc: Union[Incomplete, Incomplete], tamps: None=None, frozen: None=None, mo_coeff: None=None, mo_occ: None=None) -> Union[Incomplete, Incomplete]: ...
def tamps_tri2full_rhf(mycc: Union[Incomplete, Incomplete], tamps_tri: ndarray) -> ndarray: ...
def tamps_full2tri_rhf(mycc: Union[Incomplete, Incomplete], tamps_full: ndarray) -> ndarray: ...

class RCCSDT(ccsd.CCSDBase):
    __doc__: Incomplete
    conv_tol: Incomplete
    conv_tol_normt: Incomplete
    cc_order: int
    do_diis_max_t: Incomplete
    blksize: Incomplete
    blksize_oovv: Incomplete
    blksize_oooo: Incomplete
    einsum_backend: Incomplete
    tamps: Incomplete
    unique_tamps_map: Incomplete
    def __init__(self, mf: RHF, frozen: Optional[int]=None, mo_coeff: None=None, mo_occ: None=None) -> None: ...
    @property
    def t1(self): ...
    @t1.setter
    def t1(self, val) -> None: ...
    @property
    def t2(self): ...
    @t2.setter
    def t2(self, val) -> None: ...
    @property
    def t3(self): ...
    @t3.setter
    def t3(self, val) -> None: ...
    do_tri_max_t: Incomplete
    def set_einsum_backend(self, backend) -> None: ...
    get_nocc = get_nocc
    get_nmo = get_nmo
    get_frozen_mask = get_frozen_mask
    get_e_hf = get_e_hf
    ao2mo: Incomplete
    init_amps = init_amps_rhf
    energy = energy_rhf
    restore_from_diis_ = restore_from_diis_
    memory_estimate_log = memory_estimate_log_rccsdt
    update_amps_ = update_amps_rccsdt_tri_
    amplitudes_to_vector = amplitudes_to_vector_rhf
    vector_to_amplitudes = vector_to_amplitudes_rhf
    build_unique_tamps_map = build_unique_tamps_map_rhf
    setup_tri2block = setup_tri2block_rhf
    vector_size = vector_size_rhf
    run_diis = run_diis
    dump_flags = dump_flags
    dump_chk = dump_chk
    tamps_tri2full = tamps_tri2full_rhf
    tamps_full2tri = tamps_full2tri_rhf
    def kernel(self, tamps: Optional[List[ndarray]]=None, eris: Optional[Incomplete]=None) -> Tuple[NPArrayWithTag, List[ndarray]]: ...
    e_hf: Incomplete
    def ccsdt(self, tamps: Optional[List[ndarray]]=None, eris: Optional[Incomplete]=None) -> Tuple[NPArrayWithTag, List[ndarray]]: ...
    def ccsdt_q(self, tamps, eris=None) -> None: ...

class _IMDS:
    t1_fock: Incomplete
    t1_eris: Incomplete
    F_oo: Incomplete
    F_vv: Incomplete
    W_oooo: Incomplete
    W_ovvo: Incomplete
    W_ovov: Incomplete
    W_vooo: Incomplete
    W_vvvo: Incomplete
    W_vvvv: Incomplete
    def __init__(self) -> None: ...

class _PhysicistsERIs:
    mol: Incomplete
    mo_coeff: Incomplete
    nocc: Incomplete
    fock: Incomplete
    def __init__(self, mol: None=None) -> None: ...
