from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.cc import rccsdt as rccsdt
from pyscf.cc.rccsdt import compute_r1r2 as compute_r1r2, intermediates_t1t2 as intermediates_t1t2, intermediates_t3 as intermediates_t3, r1r2_divide_e_ as r1r2_divide_e_, t3_spin_summation_inplace_ as t3_spin_summation_inplace_, update_t1_fock_eris as update_t1_fock_eris
from pyscf.lib import logger as logger
from pyscf.mp.mp2 import get_e_hf as get_e_hf, get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc

def t3_spin_summation(A, B, nocc3, nvir, pattern, alpha: float = 1.0, beta: float = 0.0): ...
def t3_perm_symmetrize_inplace_(A, nocc, nvir, alpha: float = 1.0, beta: float = 0.0): ...
def purify_tamps_(r): ...
def r1r2_add_t3_(mycc, imds, r1, r2, t3): ...
def intermediates_t3_add_t3(mycc, imds, t3): ...
def compute_r3(mycc, imds, t2, t3): ...
def r3_divide_e_(mycc, r3, mo_energy): ...
def update_amps_rccsdt_(mycc, tamps, eris): ...

class RCCSDT(rccsdt.RCCSDT):
    def __init__(self, mf, frozen: int = 0, mo_coeff=None, mo_occ=None) -> None: ...
    do_tri_max_t: Incomplete
    update_amps_ = update_amps_rccsdt_
