from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.cc import rccsdt as rccsdt
from pyscf.cc.rccsdt import _PhysicistsERIs, compute_r1r2 as compute_r1r2, intermediates_t1t2 as intermediates_t1t2, intermediates_t3 as intermediates_t3, r1r2_divide_e_ as r1r2_divide_e_, t3_spin_summation_inplace_ as t3_spin_summation_inplace_, update_t1_fock_eris as update_t1_fock_eris
from pyscf.lib import logger as logger
from pyscf.mp.mp2 import get_e_hf as get_e_hf, get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc
from numpy import float64, ndarray
from pyscf.scf.hf import RHF
from typing import List, Optional, Tuple, Type, Union

def t3_spin_summation(A: ndarray, B: ndarray, nocc3: int, nvir: int, pattern: str, alpha: float = 1.0, beta: float = 0.0) -> ndarray: ...
def t3_perm_symmetrize_inplace_(A: ndarray, nocc: int, nvir: int, alpha: float = 1.0, beta: float = 0.0) -> ndarray: ...
def purify_tamps_(r: ndarray) -> ndarray: ...
def r1r2_add_t3_(mycc: Union[Incomplete, Incomplete, RCCSDT], imds: Union[Incomplete, Type[Incomplete], Incomplete], r1: ndarray, r2: ndarray, t3: ndarray) -> Tuple[ndarray, ndarray]: ...
def intermediates_t3_add_t3(mycc: Union[Incomplete, Incomplete, RCCSDT], imds: Union[Incomplete, Type[Incomplete], Incomplete], t3: ndarray) -> Union[Incomplete, Type[Incomplete], Incomplete]: ...
def compute_r3(mycc: Union[Incomplete, Incomplete, RCCSDT], imds: Union[Incomplete, Type[Incomplete], Incomplete], t2: ndarray, t3: ndarray) -> ndarray: ...
def r3_divide_e_(mycc: Union[Incomplete, Incomplete, RCCSDT], r3: ndarray, mo_energy: ndarray) -> ndarray: ...
def update_amps_rccsdt_(mycc: "RCCSDT", tamps: List[ndarray], eris: _PhysicistsERIs) -> List[float64]: ...

class RCCSDT(rccsdt.RCCSDT):
    def __init__(self, mf: RHF, frozen: Optional[int] = 0, mo_coeff: None=None, mo_occ: None=None) -> None: ...
    do_tri_max_t: Incomplete
    update_amps_ = update_amps_rccsdt_
