from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, lib as lib
from pyscf.cc import ccsd as ccsd
from pyscf.lib import logger as logger
from pyscf.mp.mp2 import get_e_hf as get_e_hf, get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc

def t3_spin_summation_inplace_(A, nocc3, nvir, pattern, alpha: float = 1.0, beta: float = 0.0): ...
def unpack_t3_tri2block_(t3, t3_blk, map_, mask, i0, i1, j0, j1, k0, k1, nocc, nvir, blk_i, blk_j, blk_k): ...
def unpack_t3_tri2single_pair_(t3, t3_blk, map_, mask, i0, j0, k0, nocc, nvir): ...
def unpack_t3_tri2block_pair_(t3, t3_blk, map_, mask, i0, i1, j0, j1, k0, k1, nocc, nvir, blk_i, blk_j, blk_k): ...
def accumulate_t3_block2tri_(t3, t3_blk, map_, i0, i1, j0, j1, k0, k1, nocc, nvir, blk_i, blk_j, blk_k, alpha, beta): ...
def accumulate_t3_single2tri_(t3, t3_blk, map_, i0, j0, k0, nocc, nvir, alpha, beta): ...
def setup_tri2block_rhf(mycc): ...
def update_xy(mycc, t1): ...
def update_fock(mycc, x, y, t1, eris): ...
def update_eris(mycc, x, y, eris): ...
def update_t1_fock_eris(mycc, imds, t1, eris=None): ...
def symmetrize_tamps_tri_(r, nocc): ...
def purify_tamps_tri_(r, nocc): ...
def init_amps_rhf(mycc, eris=None): ...
def energy_rhf(mycc, tamps, eris=None): ...
def intermediates_t1t2(mycc, imds, t2): ...
def compute_r1r2(mycc, imds, t2): ...
def r1r2_add_t3_tri_(mycc, imds, r1, r2, t3): ...
def r1r2_divide_e_(mycc, r1, r2, mo_energy): ...
def intermediates_t3(mycc, imds, t2): ...
def intermediates_t3_add_t3_tri(mycc, imds, t3): ...
def compute_r3_tri(mycc, imds, t2, t3): ...
def r3_tri_divide_e_(mycc, r3, mo_energy): ...
def update_amps_rccsdt_tri_(mycc, tamps, eris): ...
def amplitudes_to_vector_rhf(mycc, tamps): ...
def vector_to_amplitudes_rhf(mycc, vector): ...
def restore_t_(t, nocc, order: int = 1, do_tri: bool = False, unique_tamps_map=None): ...
def run_diis(mycc, tamps, istep, normt, de, adiis): ...
def kernel(mycc, eris=None, tamps=None, tol: float = 1e-08, tolnormt: float = 1e-06, max_cycle: int = 50, verbose: int = 5, callback=None): ...
def restore_from_diis_(mycc, diis_file, inplace: bool = True): ...
def build_unique_tamps_map_rhf(mycc): ...
def dump_flags(mycc, verbose=None): ...
def vector_size_rhf(mycc, nmo=None, nocc=None): ...
def format_size(i, suffix: str = 'B'): ...
def memory_estimate_log_rccsdt(mycc): ...
def dump_chk(mycc, tamps=None, frozen=None, mo_coeff=None, mo_occ=None): ...
def tamps_tri2full_rhf(mycc, tamps_tri): ...
def tamps_full2tri_rhf(mycc, tamps_full): ...

class RCCSDT(ccsd.CCSDBase):
    __doc__: Incomplete
    conv_tol: Incomplete
    conv_tol_normt: Incomplete
    cc_order: int
    do_diis_max_t: Incomplete
    blksize: Incomplete
    blksize_oovv: Incomplete
    blksize_oooo: Incomplete
    einsum_backend: Incomplete
    tamps: Incomplete
    unique_tamps_map: Incomplete
    def __init__(self, mf, frozen=None, mo_coeff=None, mo_occ=None) -> None: ...
    @property
    def t1(self): ...
    @t1.setter
    def t1(self, val) -> None: ...
    @property
    def t2(self): ...
    @t2.setter
    def t2(self, val) -> None: ...
    @property
    def t3(self): ...
    @t3.setter
    def t3(self, val) -> None: ...
    do_tri_max_t: Incomplete
    def set_einsum_backend(self, backend) -> None: ...
    get_nocc = get_nocc
    get_nmo = get_nmo
    get_frozen_mask = get_frozen_mask
    get_e_hf = get_e_hf
    ao2mo: Incomplete
    init_amps = init_amps_rhf
    energy = energy_rhf
    restore_from_diis_ = restore_from_diis_
    memory_estimate_log = memory_estimate_log_rccsdt
    update_amps_ = update_amps_rccsdt_tri_
    amplitudes_to_vector = amplitudes_to_vector_rhf
    vector_to_amplitudes = vector_to_amplitudes_rhf
    build_unique_tamps_map = build_unique_tamps_map_rhf
    setup_tri2block = setup_tri2block_rhf
    vector_size = vector_size_rhf
    run_diis = run_diis
    dump_flags = dump_flags
    dump_chk = dump_chk
    tamps_tri2full = tamps_tri2full_rhf
    tamps_full2tri = tamps_full2tri_rhf
    def kernel(self, tamps=None, eris=None): ...
    e_hf: Incomplete
    def ccsdt(self, tamps=None, eris=None): ...
    def ccsdt_q(self, tamps, eris=None) -> None: ...

class _IMDS:
    t1_fock: Incomplete
    t1_eris: Incomplete
    F_oo: Incomplete
    F_vv: Incomplete
    W_oooo: Incomplete
    W_ovvo: Incomplete
    W_ovov: Incomplete
    W_vooo: Incomplete
    W_vvvo: Incomplete
    W_vvvv: Incomplete
    def __init__(self) -> None: ...

class _PhysicistsERIs:
    mol: Incomplete
    mo_coeff: Incomplete
    nocc: Incomplete
    fock: Incomplete
    def __init__(self, mol=None) -> None: ...
