from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.cc import rccsdtq as rccsdtq
from pyscf.cc.rccsdt import compute_r1r2 as compute_r1r2, intermediates_t1t2 as intermediates_t1t2, intermediates_t3 as intermediates_t3, r1r2_divide_e_ as r1r2_divide_e_, t3_spin_summation_inplace_ as t3_spin_summation_inplace_, update_t1_fock_eris as update_t1_fock_eris
from pyscf.cc.rccsdt_highm import compute_r3 as compute_r3, intermediates_t3_add_t3 as intermediates_t3_add_t3, purify_tamps_ as purify_tamps_, r1r2_add_t3_ as r1r2_add_t3_, r3_divide_e_ as r3_divide_e_, t3_perm_symmetrize_inplace_ as t3_perm_symmetrize_inplace_, t3_spin_summation as t3_spin_summation
from pyscf.cc.rccsdtq import t4_add_ as t4_add_, t4_spin_summation_inplace_ as t4_spin_summation_inplace_
from pyscf.lib import logger as logger
from pyscf.mp.mp2 import get_e_hf as get_e_hf, get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc

def t4_spin_summation(A, B, nocc4, nvir, pattern, alpha: float = 1.0, beta: float = 0.0): ...
def t4_perm_symmetrize_inplace_(A, nocc, nvir, alpha: float = 1.0, beta: float = 0.0): ...
def eijkl_division_(A, eia, nocc, nvir): ...
def r2_add_t4_(mycc, imds, r2, t4): ...
def r3_add_t4_(mycc, imds, r3, t4): ...
def intermediates_t4(mycc, imds, t2, t3, t4): ...
def compute_r4(mycc, imds, t2, t3, t4): ...
def r4_divide_e_(mycc, r4, mo_energy): ...
def update_amps_rccsdtq_(mycc, tamps, eris): ...

class RCCSDTQ(rccsdtq.RCCSDTQ):
    def __init__(self, mf, frozen: int = 0, mo_coeff=None, mo_occ=None) -> None: ...
    do_tri_max_t: Incomplete
    update_amps_ = update_amps_rccsdtq_
