from _typeshed import Incomplete
from pyscf import ao2mo as ao2mo, lib as lib
from pyscf.cc import ccsd as ccsd
from pyscf.lib import linalg_helper as linalg_helper, logger as logger

einsum = lib.einsum

def update_amps(cc, t1, t2, eris): ...
def energy(cc, t1, t2, eris): ...

class RCCSD(ccsd.CCSD):
    max_space: int
    def __init__(self, mf, frozen=None, mo_coeff=None, mo_occ=None) -> None: ...
    def dump_flags(self, verbose=None) -> None: ...
    emp2: Incomplete
    def init_amps(self, eris): ...
    def kernel(self, t1=None, t2=None, eris=None, mbpt2: bool = False, cc2: bool = False): ...
    e_hf: Incomplete
    eris: Incomplete
    cc2: bool
    def ccsd(self, t1=None, t2=None, eris=None, mbpt2: bool = False, cc2: bool = False): ...
    def ao2mo(self, mo_coeff=None): ...
    energy = energy
    update_amps = update_amps
    def nip(self): ...
    def nea(self): ...
    def nee(self): ...
    ip_partition: Incomplete
    eip: Incomplete
    def ipccsd(self, nroots: int = 1, left: bool = False, koopmans: bool = False, guess=None, partition=None): ...
    imds: Incomplete
    def ipccsd_matvec(self, vector): ...
    def lipccsd_matvec(self, vector): ...
    def ipccsd_diag(self): ...
    def vector_to_amplitudes_ip(self, vector): ...
    def amplitudes_to_vector_ip(self, r1, r2): ...
    def ipccsd_star_contract(self, ipccsd_evals, ipccsd_evecs, lipccsd_evecs): ...
    ea_partition: Incomplete
    eea: Incomplete
    def eaccsd(self, nroots: int = 1, left: bool = False, koopmans: bool = False, guess=None, partition=None): ...
    def eaccsd_matvec(self, vector): ...
    def leaccsd_matvec(self, vector): ...
    def eaccsd_diag(self): ...
    def vector_to_amplitudes_ea(self, vector): ...
    def amplitudes_to_vector_ea(self, r1, r2): ...
    def eaccsd_star_contract(self, eaccsd_evals, eaccsd_evecs, leaccsd_evecs): ...
    ee_partition: Incomplete
    eee: Incomplete
    def eeccsd(self, nroots: int = 1, koopmans: bool = False, guess=None, partition=None): ...
    def eeccsd_matvec(self, vector) -> None: ...
    def eeccsd_diag(self) -> None: ...
    def vector_to_amplitudes_ee(self, vector): ...
    def amplitudes_to_vector_ee(self, r1, r2): ...

class _ChemistsERIs:
    mo_coeff: Incomplete
    fock: Incomplete
    oooo: Incomplete
    ooov: Incomplete
    ovoo: Incomplete
    ovov: Incomplete
    oovv: Incomplete
    ovvo: Incomplete
    ovvv: Incomplete
    vvvv: Incomplete
    def __init__(self, cc, mo_coeff=None, method: str = 'incore', ao2mofn=...) -> None: ...
    def get_ovvv(self, *slices): ...

class _IMDS:
    verbose: Incomplete
    stdout: Incomplete
    t1: Incomplete
    t2: Incomplete
    eris: Incomplete
    made_ip_imds: bool
    made_ea_imds: bool
    def __init__(self, cc) -> None: ...
    Woooo: Incomplete
    Wooov: Incomplete
    Wovoo: Incomplete
    def make_ip(self, ip_partition=None) -> None: ...
    Wvovv: Incomplete
    Wvvvo: Incomplete
    Wvvvv: Incomplete
    def make_ea(self, ea_partition=None) -> None: ...
    def make_ee(self) -> None: ...
