from pyscf import ao2mo as ao2mo, lib as lib
from pyscf.lib import logger as logger

def cc_Foo(t1, t2, eris): ...
def cc_Fvv(t1, t2, eris): ...
def cc_Fov(t1, t2, eris): ...
def Loo(t1, t2, eris): ...
def Lvv(t1, t2, eris): ...
def cc_Woooo(t1, t2, eris): ...
def cc_Wvvvv(t1, t2, eris): ...
def cc_Wvoov(t1, t2, eris): ...
def cc_Wvovo(t1, t2, eris): ...
def Wooov(t1, t2, eris): ...
def Wvovv(t1, t2, eris): ...
def W1ovvo(t1, t2, eris): ...
def W2ovvo(t1, t2, eris): ...
def Wovvo(t1, t2, eris): ...
def W1ovov(t1, t2, eris): ...
def W2ovov(t1, t2, eris): ...
def Wovov(t1, t2, eris): ...
def Woooo(t1, t2, eris): ...
def Wvvvv(t1, t2, eris): ...
def Wvvvo(t1, t2, eris, _Wvvvv=None): ...
def Wovoo(t1, t2, eris): ...
def get_t3p2_imds_slow(cc, t1, t2, eris=None, t3p2_ip_out=None, t3p2_ea_out=None): ...
