from pyscf import ao2mo as ao2mo, lib as lib
from pyscf.lib import logger as logger
from _typeshed import Incomplete
from numpy import float64, ndarray
from pyscf.cc.ccsd import CCSD
from pyscf.cc.rccsd import RCCSD
from typing import Optional, Tuple, Union

def cc_Foo(t1: ndarray, t2: ndarray, eris: Union[Incomplete, Incomplete, Incomplete]) -> ndarray: ...
def cc_Fvv(t1: ndarray, t2: ndarray, eris: Union[Incomplete, Incomplete, Incomplete]) -> ndarray: ...
def cc_Fov(t1: ndarray, t2: ndarray, eris: Union[Incomplete, Incomplete, Incomplete]) -> ndarray: ...
def Loo(t1: ndarray, t2: ndarray, eris: Union[Incomplete, Incomplete, Incomplete]) -> ndarray: ...
def Lvv(t1: ndarray, t2: ndarray, eris: Union[Incomplete, Incomplete, Incomplete]) -> ndarray: ...
def cc_Woooo(t1: ndarray, t2: ndarray, eris: Incomplete) -> ndarray: ...
def cc_Wvvvv(t1: ndarray, t2: ndarray, eris: Incomplete) -> ndarray: ...
def cc_Wvoov(t1: ndarray, t2: ndarray, eris: Incomplete) -> ndarray: ...
def cc_Wvovo(t1: ndarray, t2: ndarray, eris: Incomplete) -> ndarray: ...
def Wooov(t1: ndarray, t2: ndarray, eris: Union[Incomplete, Incomplete, Incomplete]) -> ndarray: ...
def Wvovv(t1: ndarray, t2: ndarray, eris: Union[Incomplete, Incomplete, Incomplete]) -> ndarray: ...
def W1ovvo(t1: ndarray, t2: ndarray, eris: Union[Incomplete, Incomplete, Incomplete]) -> ndarray: ...
def W2ovvo(t1: ndarray, t2: ndarray, eris: Union[Incomplete, Incomplete, Incomplete]) -> ndarray: ...
def Wovvo(t1: ndarray, t2: ndarray, eris: Union[Incomplete, Incomplete, Incomplete]) -> ndarray: ...
def W1ovov(t1: ndarray, t2: ndarray, eris: Union[Incomplete, Incomplete, Incomplete]) -> ndarray: ...
def W2ovov(t1: ndarray, t2: ndarray, eris: Union[Incomplete, Incomplete, Incomplete]) -> ndarray: ...
def Wovov(t1: ndarray, t2: ndarray, eris: Union[Incomplete, Incomplete, Incomplete]) -> ndarray: ...
def Woooo(t1: ndarray, t2: ndarray, eris: Union[Incomplete, Incomplete, Incomplete]) -> ndarray: ...
def Wvvvv(t1: ndarray, t2: ndarray, eris: Union[Incomplete, Incomplete, Incomplete]) -> ndarray: ...
def Wvvvo(t1: ndarray, t2: ndarray, eris: Union[Incomplete, Incomplete, Incomplete], _Wvvvv: Optional[ndarray]=None) -> ndarray: ...
def Wovoo(t1: ndarray, t2: ndarray, eris: Union[Incomplete, Incomplete, Incomplete]) -> ndarray: ...
def get_t3p2_imds_slow(cc: Union[CCSD, RCCSD], t1: ndarray, t2: ndarray, eris: Optional[Union[Incomplete, Incomplete]]=None, t3p2_ip_out: None=None, t3p2_ea_out: None=None) -> Tuple[float64, ndarray, ndarray, ndarray, ndarray]: ...
