from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.cc import uccsdt as uccsdt
from pyscf.cc.rccsdt import run_diis as run_diis
from pyscf.cc.uccsdt import _IMDS, _PhysicistsERIs, antisymmetrize_r2_uhf_ as antisymmetrize_r2_uhf_, compute_r1r2_uhf as compute_r1r2_uhf, intermediates_t1t2_uhf as intermediates_t1t2_uhf, intermediates_t3_uhf as intermediates_t3_uhf, r1r2_divide_e_uhf_ as r1r2_divide_e_uhf_, update_t1_fock_eris_uhf as update_t1_fock_eris_uhf
from pyscf.lib import logger as logger
from pyscf.mp.mp2 import get_e_hf as get_e_hf
from pyscf.mp.ump2 import get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc
from numpy import float64, ndarray
from pyscf.scf.uhf import HF1e, UHF
from typing import List, Optional, Tuple, Union

def r1r2_add_t3_uhf_(mycc: "UCCSDT", imds: _IMDS, r1: List[ndarray], r2: List[ndarray], t3: List[ndarray]) -> Tuple[List[ndarray], List[ndarray]]: ...
def intermediates_t3_add_t3_uhf(mycc: "UCCSDT", imds: _IMDS, t3: List[ndarray]) -> _IMDS: ...
def compute_r3_uhf(mycc: "UCCSDT", imds: _IMDS, t2: Union[List[ndarray], Tuple[ndarray, ndarray, ndarray]], t3: List[ndarray]) -> List[ndarray]: ...
def antisymmetrize_r3_uhf_(r3: List[ndarray]) -> List[ndarray]: ...
def r3_divide_e_uhf_(mycc: "UCCSDT", r3: List[ndarray], mo_energy: Tuple[ndarray, ndarray]) -> List[ndarray]: ...
def update_amps_uccsdt_(mycc: "UCCSDT", tamps: List[Union[Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray], List[ndarray]]], eris: _PhysicistsERIs) -> List[float64]: ...

class UCCSDT(uccsdt.UCCSDT):
    def __init__(self, mf: Union[HF1e, UHF], frozen: Optional[List[List[int]]]=None, mo_coeff: None=None, mo_occ: None=None) -> None: ...
    do_tri_max_t: Incomplete
    update_amps_ = update_amps_uccsdt_
