from pyscf import lib as lib
from pyscf.cc import uccsd_rdm as uccsd_rdm
from numpy import ndarray
from pyscf.cc.uccsd import UCCSD, _ChemistsERIs
from typing import Optional, Tuple

def make_rdm1(mycc: UCCSD, t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], l1: Tuple[ndarray, ndarray], l2: Tuple[ndarray, ndarray, ndarray], eris: Optional[_ChemistsERIs]=None, ao_repr: bool = False) -> Tuple[ndarray, ndarray]: ...
def make_rdm2(mycc: UCCSD, t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], l1: Tuple[ndarray, ndarray], l2: Tuple[ndarray, ndarray, ndarray], eris: Optional[_ChemistsERIs]=None) -> Tuple[ndarray, ndarray, ndarray]: ...
def p6(t: ndarray) -> ndarray: ...
def r6(w: ndarray) -> ndarray: ...
def r4(w: ndarray) -> ndarray: ...
