from pyscf import lib as lib
from pyscf.cc import uccsd_rdm as uccsd_rdm

def make_rdm1(mycc, t1, t2, l1, l2, eris=None, ao_repr: bool = False): ...
def make_rdm2(mycc, t1, t2, l1, l2, eris=None): ...
def p6(t): ...
def r6(w): ...
def r4(w): ...
