from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, lib as lib, scf as scf
from pyscf.cc import ccsd as ccsd
from pyscf.lib import logger as logger
from pyscf.mp import ump2 as ump2
from h5py._hl.dataset import Dataset
from numpy import float64, ndarray
from pyscf.cc.eom_uccsd import EOMEA, EOMEE, EOMIP
from pyscf.gto.mole import Mole
from pyscf.lib.logger import Logger
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.ci.cisd import UCISD
from pyscf.pbc.scf.kuhf import KUHF
from pyscf.scf.uhf import HF1e
from pyscf.scf.uhf_symm import SymAdaptedUHF
from typing import Callable, List, Optional, Tuple, Union

MEMORYMIN: Incomplete

def update_amps(cc: Union[Incomplete, Incomplete, Incomplete], t1: Union[List[ndarray], Tuple[ndarray, ndarray]], t2: Union[List[ndarray], Tuple[ndarray, ndarray, ndarray]], eris: Union[Incomplete, Incomplete]) -> Tuple[Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]]: ...
def energy(cc: Union[Incomplete, Incomplete, Incomplete], t1: Optional[Union[List[ndarray], Tuple[ndarray, ndarray]]]=None, t2: Optional[Union[List[ndarray], Tuple[ndarray, ndarray, ndarray]]]=None, eris: Optional[Union[Incomplete, Incomplete]]=None) -> float64: ...
get_nocc = ump2.get_nocc
get_nmo = ump2.get_nmo
get_frozen_mask = ump2.get_frozen_mask

def amplitudes_to_vector(t1: Union[List[ndarray], Tuple[ndarray, ndarray]], t2: Union[List[ndarray], Tuple[ndarray, ndarray, ndarray]], out: None=None) -> ndarray: ...
def vector_to_amplitudes(vector: ndarray, nmo: Tuple[int, int], nocc: Tuple[int, int]) -> Tuple[Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]]: ...
def amplitudes_from_rccsd(t1: ndarray, t2: ndarray) -> Tuple[Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]]: ...

class UCCSD(ccsd.CCSDBase):
    conv_tol: Incomplete
    conv_tol_normt: Incomplete
    def __init__(self, mf: Union[HF1e, Incomplete, SymAdaptedUHF, KUHF, Incomplete], frozen: Optional[Union[int, List[List[int]], List[ndarray], Tuple[List[List[int]], List[List[int]]]]]=None, mo_coeff: Optional[List[ndarray]]=None, mo_occ: None=None) -> None: ...
    get_nocc = get_nocc
    get_nmo = get_nmo
    get_frozen_mask = get_frozen_mask
    emp2: Incomplete
    def init_amps(self, eris: Optional[Union[Incomplete, Incomplete]]=None) -> Tuple[float64, Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]]: ...
    energy = energy
    update_amps = update_amps
    def kernel(self, t1: Optional[List[ndarray]]=None, t2: Optional[List[ndarray]]=None, eris: Optional[Incomplete]=None, mbpt2: bool = False) -> Union[Tuple[float, Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]], Tuple[float64, Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]]]: ...
    t1: Incomplete
    def ccsd(self, t1: Optional[List[ndarray]]=None, t2: Optional[List[ndarray]]=None, eris: Optional[Incomplete]=None, mbpt2: bool = False) -> Union[Tuple[float, Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]], Tuple[float64, Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]]]: ...
    def solve_lambda(self, t1: Optional[Tuple[ndarray, ndarray]]=None, t2: Optional[Tuple[ndarray, ndarray, ndarray]]=None, l1: None=None, l2: None=None, eris: Optional[Incomplete]=None) -> Tuple[Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]]: ...
    def ccsd_t(self, t1: Optional[List[ndarray]]=None, t2: Optional[List[ndarray]]=None, eris: Optional[Incomplete]=None) -> float64: ...
    uccsd_t = ccsd_t
    def make_rdm1(self, t1: Optional[Union[ndarray, List[ndarray], Tuple[ndarray, ndarray]]]=None, t2: Optional[Union[List[ndarray], Tuple[ndarray, ndarray, ndarray]]]=None, l1: Optional[Union[ndarray, List[ndarray], Tuple[ndarray, ndarray]]]=None, l2: Optional[Union[List[ndarray], Tuple[ndarray, ndarray, ndarray]]]=None, ao_repr: bool = False, with_frozen: bool = True, with_mf: bool = True) -> Tuple[ndarray, ndarray]: ...
    def make_rdm2(self, t1: Optional[Union[List[ndarray], Tuple[ndarray, ndarray], ndarray]]=None, t2: Optional[Union[List[ndarray], Tuple[ndarray, ndarray, ndarray]]]=None, l1: Optional[Union[List[ndarray], Tuple[ndarray, ndarray], ndarray]]=None, l2: Optional[Union[List[ndarray], Tuple[ndarray, ndarray, ndarray]]]=None, ao_repr: bool = False, with_frozen: bool = True, with_dm1: bool = True) -> Tuple[ndarray, ndarray, ndarray]: ...
    def spin_square(self, mo_coeff=None, s=None): ...
    def ao2mo(self, mo_coeff: Optional[Union[ndarray, Tuple[NPArrayWithTag, NPArrayWithTag]]]=None) -> Incomplete: ...
    def ipccsd(self, nroots: int = 1, left: bool = False, koopmans: bool = False, guess: Optional[List[ndarray]]=None, partition: None=None, eris: None=None) -> Tuple[ndarray, List[ndarray]]: ...
    def eaccsd(self, nroots: int = 1, left: bool = False, koopmans: bool = False, guess: Optional[List[ndarray]]=None, partition: None=None, eris: None=None) -> Tuple[ndarray, List[ndarray]]: ...
    def eeccsd(self, nroots: int = 1, koopmans: bool = False, guess: Optional[List[ndarray]]=None, eris: None=None) -> Tuple[ndarray, List[ndarray]]: ...
    def eomee_ccsd(self, nroots: int = 1, koopmans: bool = False, guess: None=None, eris: None=None) -> Tuple[ndarray, List[ndarray]]: ...
    def eomsf_ccsd(self, nroots: int = 1, koopmans: bool = False, guess: None=None, eris: None=None) -> Tuple[ndarray, List[ndarray]]: ...
    def eomip_method(self) -> EOMIP: ...
    def eomea_method(self) -> EOMEA: ...
    def eomee_method(self) -> EOMEE: ...
    def density_fit(self, auxbasis: Optional[str]=None, with_df: None=None) -> Incomplete: ...
    def nuc_grad_method(self): ...
    def amplitudes_to_vector(self, t1: Union[List[ndarray], Tuple[ndarray, ndarray]], t2: Union[List[ndarray], Tuple[ndarray, ndarray, ndarray]], out: None=None) -> ndarray: ...
    def vector_to_amplitudes(self, vector: ndarray, nmo: None=None, nocc: None=None) -> Tuple[Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]]: ...
    def vector_size(self, nmo: None=None, nocc: None=None) -> int: ...
    def amplitudes_from_rccsd(self, t1: ndarray, t2: ndarray) -> Tuple[Tuple[ndarray, ndarray], Tuple[ndarray, ndarray, ndarray]]: ...
CCSD = UCCSD

class _ChemistsERIs(ccsd._ChemistsERIs):
    OOOO: Incomplete
    OVOO: Incomplete
    OVOV: Incomplete
    OOVV: Incomplete
    OVVO: Incomplete
    OVVV: Incomplete
    VVVV: Incomplete
    ooOO: Incomplete
    ovOO: Incomplete
    ovOV: Incomplete
    ooVV: Incomplete
    ovVO: Incomplete
    ovVV: Incomplete
    vvVV: Incomplete
    OVoo: Incomplete
    OOvv: Incomplete
    OVvo: Incomplete
    def __init__(self, mol: Optional[Mole]=None) -> None: ...
    def get_ovvv(self, *slices) -> ndarray: ...
    def get_ovVV(self, *slices) -> ndarray: ...
    def get_OVvv(self, *slices) -> ndarray: ...
    def get_OVVV(self, *slices) -> ndarray: ...

def make_tau(t2: Union[List[ndarray], Tuple[ndarray, ndarray, ndarray]], t1: Union[List[ndarray], Tuple[ndarray, ndarray]], r1: Union[List[ndarray], Tuple[ndarray, ndarray]], fac: Union[float, int] = 1, out: None=None) -> Tuple[ndarray, ndarray, ndarray]: ...
def make_tau_aa(t2aa: ndarray, t1a: ndarray, r1a: ndarray, fac: Union[float, int] = 1, out: None=None) -> ndarray: ...
def make_tau_ab(t2ab: ndarray, t1: Union[List[ndarray], Tuple[ndarray, ndarray]], r1: Union[List[ndarray], Tuple[ndarray, ndarray]], fac: Union[float, int] = 1, out: None=None) -> ndarray: ...
