from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.cc import uccsdt as uccsdt
from pyscf.cc.rccsdt import run_diis as run_diis
from pyscf.cc.uccsdt import antisymmetrize_r2_uhf_ as antisymmetrize_r2_uhf_, compute_r1r2_uhf as compute_r1r2_uhf, intermediates_t1t2_uhf as intermediates_t1t2_uhf, intermediates_t3_uhf as intermediates_t3_uhf, r1r2_divide_e_uhf_ as r1r2_divide_e_uhf_, update_t1_fock_eris_uhf as update_t1_fock_eris_uhf
from pyscf.lib import logger as logger
from pyscf.mp.mp2 import get_e_hf as get_e_hf
from pyscf.mp.ump2 import get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc

def r1r2_add_t3_uhf_(mycc, imds, r1, r2, t3): ...
def intermediates_t3_add_t3_uhf(mycc, imds, t3): ...
def compute_r3_uhf(mycc, imds, t2, t3): ...
def antisymmetrize_r3_uhf_(r3): ...
def r3_divide_e_uhf_(mycc, r3, mo_energy): ...
def update_amps_uccsdt_(mycc, tamps, eris): ...

class UCCSDT(uccsdt.UCCSDT):
    def __init__(self, mf, frozen=None, mo_coeff=None, mo_occ=None) -> None: ...
    do_tri_max_t: Incomplete
    update_amps_ = update_amps_uccsdt_
