from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, lib as lib, scf as scf
from pyscf.cc import ccsd as ccsd
from pyscf.lib import logger as logger
from pyscf.mp import ump2 as ump2

MEMORYMIN: Incomplete

def update_amps(cc, t1, t2, eris): ...
def energy(cc, t1=None, t2=None, eris=None): ...
get_nocc = ump2.get_nocc
get_nmo = ump2.get_nmo
get_frozen_mask = ump2.get_frozen_mask

def amplitudes_to_vector(t1, t2, out=None): ...
def vector_to_amplitudes(vector, nmo, nocc): ...
def amplitudes_from_rccsd(t1, t2): ...

class UCCSD(ccsd.CCSDBase):
    conv_tol: Incomplete
    conv_tol_normt: Incomplete
    def __init__(self, mf, frozen=None, mo_coeff=None, mo_occ=None) -> None: ...
    get_nocc = get_nocc
    get_nmo = get_nmo
    get_frozen_mask = get_frozen_mask
    emp2: Incomplete
    def init_amps(self, eris=None): ...
    energy = energy
    update_amps = update_amps
    def kernel(self, t1=None, t2=None, eris=None, mbpt2: bool = False): ...
    t1: Incomplete
    def ccsd(self, t1=None, t2=None, eris=None, mbpt2: bool = False): ...
    def solve_lambda(self, t1=None, t2=None, l1=None, l2=None, eris=None): ...
    def ccsd_t(self, t1=None, t2=None, eris=None): ...
    uccsd_t = ccsd_t
    def make_rdm1(self, t1=None, t2=None, l1=None, l2=None, ao_repr: bool = False, with_frozen: bool = True, with_mf: bool = True): ...
    def make_rdm2(self, t1=None, t2=None, l1=None, l2=None, ao_repr: bool = False, with_frozen: bool = True, with_dm1: bool = True): ...
    def spin_square(self, mo_coeff=None, s=None): ...
    def ao2mo(self, mo_coeff=None): ...
    def ipccsd(self, nroots: int = 1, left: bool = False, koopmans: bool = False, guess=None, partition=None, eris=None): ...
    def eaccsd(self, nroots: int = 1, left: bool = False, koopmans: bool = False, guess=None, partition=None, eris=None): ...
    def eeccsd(self, nroots: int = 1, koopmans: bool = False, guess=None, eris=None): ...
    def eomee_ccsd(self, nroots: int = 1, koopmans: bool = False, guess=None, eris=None): ...
    def eomsf_ccsd(self, nroots: int = 1, koopmans: bool = False, guess=None, eris=None): ...
    def eomip_method(self): ...
    def eomea_method(self): ...
    def eomee_method(self): ...
    def density_fit(self, auxbasis=None, with_df=None): ...
    def nuc_grad_method(self): ...
    def amplitudes_to_vector(self, t1, t2, out=None): ...
    def vector_to_amplitudes(self, vector, nmo=None, nocc=None): ...
    def vector_size(self, nmo=None, nocc=None): ...
    def amplitudes_from_rccsd(self, t1, t2): ...
CCSD = UCCSD

class _ChemistsERIs(ccsd._ChemistsERIs):
    OOOO: Incomplete
    OVOO: Incomplete
    OVOV: Incomplete
    OOVV: Incomplete
    OVVO: Incomplete
    OVVV: Incomplete
    VVVV: Incomplete
    ooOO: Incomplete
    ovOO: Incomplete
    ovOV: Incomplete
    ooVV: Incomplete
    ovVO: Incomplete
    ovVV: Incomplete
    vvVV: Incomplete
    OVoo: Incomplete
    OOvv: Incomplete
    OVvo: Incomplete
    def __init__(self, mol=None) -> None: ...
    def get_ovvv(self, *slices): ...
    def get_ovVV(self, *slices): ...
    def get_OVvv(self, *slices): ...
    def get_OVVV(self, *slices): ...

def make_tau(t2, t1, r1, fac: int = 1, out=None): ...
def make_tau_aa(t2aa, t1a, r1a, fac: int = 1, out=None): ...
def make_tau_ab(t2ab, t1, r1, fac: int = 1, out=None): ...
