from _typeshed import Incomplete
from pyscf import ao2mo as ao2mo, lib as lib
from pyscf.cc import ccsd as ccsd, uccsd as uccsd
from pyscf.lib import logger as logger
from pyscf.mp import ump2 as ump2

einsum = lib.einsum

def update_amps(cc, t1, t2, eris): ...
def energy(cc, t1, t2, eris): ...
get_frozen_mask = ump2.get_frozen_mask

class UCCSD(ccsd.CCSD):
    conv_tol_normt: float
    def __init__(self, mf, frozen=None, mo_coeff=None, mo_occ=None) -> None: ...
    @property
    def nocc(self): ...
    @property
    def nmo(self): ...
    get_nocc: Incomplete
    get_nmo: Incomplete
    get_frozen_mask = get_frozen_mask
    emp2: Incomplete
    def init_amps(self, eris): ...
    energy = energy
    def kernel(self, t1=None, t2=None, eris=None, mbpt2: bool = False): ...
    eris: Incomplete
    def ccsd(self, t1=None, t2=None, eris=None, mbpt2: bool = False): ...
    def ao2mo(self, mo_coeff=None): ...
    def update_amps(self, t1, t2, eris): ...
    def nip(self): ...
    def nea(self): ...
    def nee(self): ...
    imds: Incomplete
    def ipccsd_matvec(self, vector): ...
    def ipccsd_diag(self): ...
    def vector_to_amplitudes_ip(self, vector): ...
    def amplitudes_to_vector_ip(self, r1, r2): ...
    def eaccsd_matvec(self, vector): ...
    def eaccsd_diag(self): ...
    def vector_to_amplitudes_ea(self, vector): ...
    def amplitudes_to_vector_ea(self, r1, r2): ...
    def eeccsd_matvec(self, vector): ...
    def eeccsd_diag(self): ...
    def vector_to_amplitudes_ee(self, vector): ...
    def amplitudes_to_vector_ee(self, r1, r2): ...
    def amplitudes_from_rccsd(self, t1, t2): ...

class _PhysicistsERIs:
    mo_coeff: Incomplete
    dtype: Incomplete
    oooo: Incomplete
    ooov: Incomplete
    ovoo: Incomplete
    oovv: Incomplete
    ovov: Incomplete
    ovvv: Incomplete
    vvvv: Incomplete
    feri1: Incomplete
    def __init__(self, cc, mo_coeff=None, method: str = 'incore', ao2mofn=...) -> None: ...

def uspatial2spin(cc, moidx, mo_coeff): ...

class _IMDS:
    cc: Incomplete
    made_ip_imds: bool
    made_ea_imds: bool
    made_ee_imds: bool
    def __init__(self, cc) -> None: ...
    Woooo: Incomplete
    Wooov: Incomplete
    Wovoo: Incomplete
    def make_ip(self) -> None: ...
    Wvovv: Incomplete
    Wvvvv: Incomplete
    Wvvvo: Incomplete
    def make_ea(self) -> None: ...
    def make_ee(self) -> None: ...
