from pyscf import ao2mo as ao2mo, lib as lib
from pyscf.cc.ccsd import BLKMIN as BLKMIN

def make_tau(t2, t1, r1, fac: int = 1, out=None): ...
def make_tau_aa(t2aa, t1a, r1a, fac: int = 1, out=None): ...
def make_tau_ab(t2ab, t1, r1, fac: int = 1, out=None): ...
def Foo(t1, t2, eris): ...
def Fvv(t1, t2, eris): ...
def Fov(t1, t2, eris): ...
def Woooo(t1, t2, eris): ...
def Wooov(t1, t2, eris): ...
def Woovo(t1, t2, eris): ...
def Wovvo(t1, t2, eris): ...
def Wvvov(t1, t2, eris): ...
def Wvvvo(t1, t2, eris): ...
