from pyscf import ao2mo as ao2mo, lib as lib
from pyscf.cc.ccsd import BLKMIN as BLKMIN
from _typeshed import Incomplete
from numpy import ndarray
from typing import Tuple, Union

def make_tau(t2: Tuple[ndarray, ndarray, ndarray], t1: Tuple[ndarray, ndarray], r1: Tuple[ndarray, ndarray], fac: Union[float, int] = 1, out: None=None) -> Tuple[ndarray, ndarray, ndarray]: ...
def make_tau_aa(t2aa: ndarray, t1a: ndarray, r1a: ndarray, fac: Union[float, int] = 1, out: None=None) -> ndarray: ...
def make_tau_ab(t2ab: ndarray, t1: Tuple[ndarray, ndarray], r1: Tuple[ndarray, ndarray], fac: Union[float, int] = 1, out: None=None) -> ndarray: ...
def Foo(t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: Union[Incomplete, Incomplete]) -> Tuple[ndarray, ndarray]: ...
def Fvv(t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: Union[Incomplete, Incomplete]) -> Tuple[ndarray, ndarray]: ...
def Fov(t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: Union[Incomplete, Incomplete]) -> Tuple[ndarray, ndarray]: ...
def Woooo(t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: Union[Incomplete, Incomplete]) -> Tuple[ndarray, ndarray, None, ndarray]: ...
def Wooov(t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: Union[Incomplete, Incomplete]) -> Tuple[ndarray, ndarray, ndarray, ndarray]: ...
def Woovo(t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: Union[Incomplete, Incomplete]) -> Tuple[ndarray, ndarray, ndarray, ndarray]: ...
def Wovvo(t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: Union[Incomplete, Incomplete]) -> Tuple[ndarray, ndarray, ndarray, ndarray, ndarray, ndarray]: ...
def Wvvov(t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: Union[Incomplete, Incomplete]) -> Tuple[ndarray, ndarray, ndarray, ndarray]: ...
def Wvvvo(t1: Tuple[ndarray, ndarray], t2: Tuple[ndarray, ndarray, ndarray], eris: Union[Incomplete, Incomplete]) -> Tuple[ndarray, ndarray, ndarray, ndarray]: ...
