from pyscf import lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc import df as df, tools as tools
from pyscf.pbc.dft.gen_grid import gen_uniform_grids as gen_uniform_grids
from pyscf.pbc.dft.numint import eval_ao as eval_ao

einsum = lib.einsum

def general(cell, mo_coeffs, kpts=None, compact: bool = False): ...
def get_mo_eri(cell, mo_coeffs, kpts=None): ...
def get_mo_pairs_G(cell, mo_coeffs, kpts=None, q=None): ...
def get_mo_pairs_invG(cell, mo_coeffs, kpts=None, q=None): ...
def assemble_eri(cell, orb_pair_invG1, orb_pair_G2, q=None, verbose=...): ...
def get_ao_pairs_G(cell, kpts=None): ...
def get_ao_eri(cell, kpts=None): ...
