from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib, symm as symm
from pyscf.fci import cistring as cistring

LARGE_CI_TOL: Incomplete
RETURN_STRS: Incomplete
PENALTY: Incomplete

def large_ci(ci, norb, nelec, tol=..., return_strs=...): ...
def initguess_triplet(norb, nelec, binstring): ...
def symm_initguess(norb, nelec, orbsym, wfnsym: int = 0, irrep_nelec=None) -> None: ...
def cylindrical_init_guess(mol, norb, nelec, orbsym, wfnsym: int = 0, singlet: bool = True, nroots: int = 1): ...
def symmetrize_wfn(ci, norb, nelec, orbsym, wfnsym: int = 0): ...
def guess_wfnsym(ci, norb, nelec, orbsym): ...
def des_a(ci0, norb, neleca_nelecb, ap_id): ...
def des_b(ci0, norb, neleca_nelecb, ap_id): ...
def cre_a(ci0, norb, neleca_nelecb, ap_id): ...
def cre_b(ci0, norb, neleca_nelecb, ap_id): ...
def det_overlap(string1, string2, norb, s=None): ...
def overlap(bra, ket, norb, nelec, s=None): ...

class SpinPenaltyFCISolver:
    __name_mixin__: str
    base: Incomplete
    ss_value: Incomplete
    ss_penalty: Incomplete
    davidson_only: bool
    def __init__(self, fcibase, shift, ss_value) -> None: ...
    def undo_fix_spin(self): ...
    def base_contract_2e(self, *args, **kwargs): ...
    def contract_2e(self, eri, fcivec, norb, nelec, link_index=None, **kwargs): ...

def fix_spin(fciobj, shift=..., ss=None, **kwargs): ...
def fix_spin_(fciobj, shift: float = 0.1, ss=None): ...
def transform_ci_for_orbital_rotation(ci, norb, nelec, u): ...
def transform_ci(ci, nelec, u): ...
def civec_spinless_repr_generator(ci0_r, norb, nelec_r): ...
def civec_spinless_repr(ci0_r, norb, nelec_r): ...
