import numpy
from _typeshed import Incomplete
from pyscf import lib as lib

libfci: Incomplete

def make_strings(orb_list, nelec): ...
gen_strings4orblist = make_strings

def gen_occslst(orb_list, nelec): ...

class OIndexList(numpy.ndarray): ...
num_strings = lib.comb

def gen_linkstr_index_o1(orb_list, nelec, strs=None, tril: bool = False): ...
def gen_linkstr_index(orb_list, nocc, strs=None, tril: bool = False): ...
def reform_linkstr_index(link_index): ...
def gen_linkstr_index_trilidx(orb_list, nocc, strs=None): ...
def gen_cre_str_index(orb_list, nelec): ...
def gen_des_str_index(orb_list, nelec): ...
def cre_des_sign(p, q, string0): ...
def cre_sign(p, string0): ...
def des_sign(p, string0): ...
def parity(string0, string1): ...
def addr2str(norb, nelec, addr): ...
def addrs2str(norb, nelec, addrs): ...
def str2addr(norb, nelec, string): ...
def strs2addr(norb, nelec, strings): ...
def sub_addrs(norb, nelec, orbital_indices, sub_nelec: int = 0): ...
def tn_strs(norb, nelec, n): ...
