from _typeshed import Incomplete
from pyscf import ao2mo as ao2mo, lib as lib
from pyscf.fci import cistring as cistring, direct_spin1 as direct_spin1

libfci: Incomplete

def contract_1e(h1e, fcivec, norb, nelec, link_index=None): ...
def contract_2e(eri, fcivec, norb, nelec, link_index=None): ...
def absorb_h1e(h1e, eri, norb, nelec, fac: int = 1): ...
def energy(h1e, eri, fcivec, norb, nelec, link_index=None): ...
def make_hdiag(h1e, eri, norb, nelec, compress: bool = False): ...

class FCISolver(direct_spin1.FCISolver):
    davidson_only: bool
    def __init__(self, *args, **kwargs) -> None: ...
    def contract_1e(self, h1e, fcivec, norb, nelec, link_index=None): ...
    def contract_2e(self, eri, fcivec, norb, nelec, link_index=None): ...
    def absorb_h1e(self, h1e, eri, norb, nelec, fac: int = 1): ...
    def make_hdiag(self, h1e, eri, norb, nelec, compress: bool = False): ...
    def kernel(self, h1e, eri, norb, nelec, ci0=None, tol=None, lindep=None, max_cycle=None, max_space=None, nroots=None, davidson_only=None, pspace_size=None, orbsym=None, wfnsym=None, ecore: int = 0, **kwargs): ...
    converged: bool
    def eig(self, op, x0=None, precond=None, **kwargs): ...
FCI = FCISolver
