import numpy
from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, lib as lib
from pyscf.fci import addons as addons, cistring as cistring, rdm as rdm, spin_op as spin_op
from pyscf.fci.addons import civec_spinless_repr as civec_spinless_repr
from pyscf.fci.spin_op import contract_ss as contract_ss
from pyscf.lib import logger as logger

libfci: Incomplete

def contract_1e(f1e, fcivec, norb, nelec, link_index=None): ...
def contract_2e(eri, fcivec, norb, nelec, link_index=None): ...
def make_hdiag(h1e, eri, norb, nelec, compress: bool = False): ...
def absorb_h1e(h1e, eri, norb, nelec, fac: int = 1): ...
def pspace(h1e, eri, norb, nelec, hdiag=None, np: int = 400): ...
def kernel(h1e, eri, norb, nelec, ci0=None, level_shift: float = 0.001, tol: float = 1e-10, lindep: float = 1e-14, max_cycle: int = 50, max_space: int = 12, nroots: int = 1, davidson_only: bool = False, pspace_size: int = 400, orbsym=None, wfnsym=None, ecore: int = 0, **kwargs): ...
def energy(h1e, eri, fcivec, norb, nelec, link_index=None): ...
def make_rdm1s(fcivec, norb, nelec, link_index=None): ...
def make_rdm1(fcivec, norb, nelec, link_index=None): ...
def make_rdm12s(fcivec, norb, nelec, link_index=None, reorder: bool = True): ...
def make_rdm12(fcivec, norb, nelec, link_index=None, reorder: bool = True): ...
def make_rdm123(fcivec, norb, nelec, link_index=None, reorder: bool = True): ...
def make_rdm123s(fcivec, norb, nelec, link_index=None, reorder: bool = True): ...
def make_rdm1234(fcivec, norb, nelec, link_index=None, reorder: bool = True): ...
def make_rdm1234s(fcivec, norb, nelec, link_index=None, reorder: bool = True): ...
def trans_rdm1s(cibra, ciket, norb, nelec, link_index=None): ...
def trans_rdm1(cibra, ciket, norb, nelec, link_index=None): ...
def trans_rdm12s(cibra, ciket, norb, nelec, link_index=None, reorder: bool = True): ...
def trans_rdm12(cibra, ciket, norb, nelec, link_index=None, reorder: bool = True): ...
def get_init_guess(norb, nelec, nroots, hdiag): ...
def kernel_ms1(fci, h1e, eri, norb, nelec, ci0=None, link_index=None, tol=None, lindep=None, max_cycle=None, max_space=None, nroots=None, davidson_only=None, pspace_size=None, hop=None, max_memory=None, verbose=None, ecore: int = 0, **kwargs): ...
def make_pspace_precond(hdiag, pspaceig, pspaceci, addr, level_shift: int = 0): ...
def make_diag_precond(hdiag, pspaceig, pspaceci, addr, level_shift: int = 0): ...

class FCIBase(lib.StreamObject):
    max_cycle: Incomplete
    max_space: Incomplete
    conv_tol: Incomplete
    conv_tol_residual: Incomplete
    lindep: Incomplete
    level_shift: Incomplete
    davidson_only: Incomplete
    pspace_size: Incomplete
    threads: Incomplete
    lessio: Incomplete
    verbose: Incomplete
    max_memory: Incomplete
    stdout: Incomplete
    mol: Incomplete
    nroots: int
    spin: Incomplete
    orbsym: Incomplete
    wfnsym: Incomplete
    converged: bool
    norb: Incomplete
    nelec: Incomplete
    eci: Incomplete
    ci: Incomplete
    def __init__(self, mol=None) -> None: ...
    @property
    def e_tot(self): ...
    @property
    def nstates(self): ...
    @nstates.setter
    def nstates(self, x) -> None: ...
    def dump_flags(self, verbose=None): ...
    def absorb_h1e(self, h1e, eri, norb, nelec, fac: int = 1): ...
    def make_hdiag(self, h1e, eri, norb, nelec, compress: bool = False): ...
    def pspace(self, h1e, eri, norb, nelec, hdiag=None, np: int = 400): ...
    def contract_1e(self, f1e, fcivec, norb, nelec, link_index=None, **kwargs): ...
    def contract_2e(self, eri, fcivec, norb, nelec, link_index=None, **kwargs): ...
    def eig(self, op, x0=None, precond=None, **kwargs): ...
    def make_precond(self, hdiag, pspaceig=None, pspaceci=None, addr=None): ...
    def get_init_guess(self, norb, nelec, nroots, hdiag): ...
    def kernel(self, h1e, eri, norb, nelec, ci0=None, tol=None, lindep=None, max_cycle=None, max_space=None, nroots=None, davidson_only=None, pspace_size=None, orbsym=None, wfnsym=None, ecore: int = 0, **kwargs): ...
    def energy(self, h1e, eri, fcivec, norb, nelec, link_index=None): ...
    def spin_square(self, fcivec, norb, nelec): ...
    def make_rdm1s(self, fcivec, norb, nelec, link_index=None): ...
    def make_rdm1(self, fcivec, norb, nelec, link_index=None): ...
    def make_rdm12s(self, fcivec, norb, nelec, link_index=None, reorder: bool = True): ...
    def make_rdm12(self, fcivec, norb, nelec, link_index=None, reorder: bool = True): ...
    def make_rdm123s(self, fcivec, norb, nelec, link_index=None, reorder: bool = True): ...
    def make_rdm123(self, fcivec, norb, nelec, link_index=None, reorder: bool = True): ...
    def make_rdm1234s(self, fcivec, norb, nelec, link_index=None, reorder: bool = True): ...
    def make_rdm1234(self, fcivec, norb, nelec, link_index=None, reorder: bool = True): ...
    def make_rdm2(self, fcivec, norb, nelec, link_index=None, reorder: bool = True): ...
    def trans_rdm1s(self, cibra, ciket, norb, nelec, link_index=None): ...
    def trans_rdm1(self, cibra, ciket, norb, nelec, link_index=None): ...
    def trans_rdm12s(self, cibra, ciket, norb, nelec, link_index=None, reorder: bool = True): ...
    def trans_rdm12(self, cibra, ciket, norb, nelec, link_index=None, reorder: bool = True): ...
    def large_ci(self, fcivec, norb, nelec, tol=..., return_strs=...): ...
    def contract_ss(self, fcivec, norb, nelec): ...
    def gen_linkstr(self, norb, nelec, tril: bool = True, spin=None): ...

class FCISolver(FCIBase):
    def transform_ci_for_orbital_rotation(self, fcivec, norb, nelec, u): ...
    to_gpu = lib.to_gpu
FCI = FCISolver

class FCIvector(numpy.ndarray):
    def __array_wrap__(self, out, context=None, return_scalar: bool = False): ...
