from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, lib as lib, symm as symm
from pyscf.fci import addons as addons, cistring as cistring, direct_nosym as direct_nosym, direct_spin1 as direct_spin1, direct_spin1_symm as direct_spin1_symm
from pyscf.lib import logger as logger
from pyscf.scf.hf_symm import map_degeneracy as map_degeneracy

libfci: Incomplete

def contract_2e(eri, fcivec, norb, nelec, link_index=None, orbsym=None, wfnsym: int = 0): ...
def reorder_eri(eri, norb, orbsym, max_momentum, max_gerades): ...
def argsort_strs_by_irrep(strs, orbsym, max_momentum, max_gerades): ...
def gen_str_irrep(strs, orbsym, link_index, rank_eri, irrep_eri, max_momentum, max_gerades): ...
def get_init_guess(norb, nelec, nroots, hdiag, orbsym, wfnsym: int = 0, sym_allowed_idx=None): ...
def guess_wfnsym(solver, norb, nelec, fcivec=None, orbsym=None, wfnsym=None, **kwargs): ...
def sym_allowed_indices(nelec, orbsym, wfnsym): ...

class FCISolver(direct_spin1_symm.FCISolver):
    def contract_1e(self, f1e, fcivec, norb, nelec, link_index=None, **kwargs) -> None: ...
    def contract_2e(self, eri, fcivec, norb, nelec, link_index=None, orbsym=None, wfnsym=None, **kwargs): ...
    def get_init_guess(self, norb, nelec, nroots, hdiag, orbsym=None, wfnsym=None): ...
    def pspace(self, h1e, eri, norb, nelec, hdiag, np: int = 400): ...
    absorb_h1e: Incomplete
    make_hdiag: Incomplete
    guess_wfnsym = guess_wfnsym
    make_rdm1: Incomplete
    make_rdm1s: Incomplete
    make_rdm12: Incomplete
    make_rdm12s: Incomplete
    trans_rdm1: Incomplete
    trans_rdm1s: Incomplete
    trans_rdm12: Incomplete
    trans_rdm12s: Incomplete
    norb: Incomplete
    nelec: Incomplete
    sym_allowed_idx: Incomplete
    orbsym: Incomplete
    def kernel(self, h1e, eri, norb, nelec, ci0=None, tol=None, lindep=None, max_cycle=None, max_space=None, nroots=None, davidson_only=None, pspace_size=None, orbsym=None, wfnsym=None, ecore: int = 0, **kwargs): ...
FCI = FCISolver
