from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, lib as lib, symm as symm
from pyscf.fci import addons as addons, cistring as cistring, direct_spin1 as direct_spin1
from pyscf.fci.spin_op import contract_ss as contract_ss
from pyscf.lib import logger as logger
from pyscf.scf.hf_symm import map_degeneracy as map_degeneracy

libfci: Incomplete
TOTIRREPS: int

def contract_2e(eri, fcivec, norb, nelec, link_index=None, orbsym=None, wfnsym: int = 0): ...
def kernel(h1e, eri, norb, nelec, ci0=None, level_shift: float = 0.001, tol: float = 1e-10, lindep: float = 1e-14, max_cycle: int = 50, max_space: int = 12, nroots: int = 1, davidson_only: bool = False, pspace_size: int = 400, orbsym=None, wfnsym=None, ecore: int = 0, **kwargs): ...
make_rdm1 = direct_spin1.make_rdm1
make_rdm1s = direct_spin1.make_rdm1s
make_rdm12 = direct_spin1.make_rdm12
trans_rdm1s = direct_spin1.trans_rdm1s
trans_rdm1 = direct_spin1.trans_rdm1
trans_rdm12 = direct_spin1.trans_rdm12

def energy(h1e, eri, fcivec, norb, nelec, link_index=None, orbsym=None, wfnsym: int = 0): ...
def get_init_guess(norb, nelec, nroots, hdiag, orbsym, wfnsym: int = 0): ...
def get_init_guess_cyl_sym(norb, nelec, nroots, hdiag, orbsym, wfnsym: int = 0): ...
def reorder_eri(eri, norb, orbsym): ...
def argsort_strs_by_irrep(strs, orbsym): ...
def gen_str_irrep(strs, orbsym, link_index, rank_eri, irrep_eri): ...
def guess_wfnsym(solver, norb, nelec, fcivec=None, orbsym=None, wfnsym=None, **kwargs): ...
def sym_allowed_indices(nelec, orbsym, wfnsym): ...

class FCISolver(direct_spin1.FCISolver):
    pspace_size: Incomplete
    wfnsym: Incomplete
    sym_allowed_idx: Incomplete
    def __init__(self, mol=None, **kwargs) -> None: ...
    def dump_flags(self, verbose=None): ...
    absorb_h1e: Incomplete
    def make_hdiag(self, h1e, eri, norb, nelec, compress: bool = False): ...
    def pspace(self, h1e, eri, norb, nelec, hdiag, np: int = 400): ...
    def contract_1e(self, f1e, fcivec, norb, nelec, link_index=None, **kwargs): ...
    def contract_2e(self, eri, fcivec, norb, nelec, link_index=None, orbsym=None, wfnsym=None, **kwargs): ...
    def contract_ss(self, fcivec, norb, nelec): ...
    def get_init_guess(self, norb, nelec, nroots, hdiag, orbsym=None, wfnsym=None): ...
    guess_wfnsym = guess_wfnsym
    norb: Incomplete
    nelec: Incomplete
    orbsym: Incomplete
    def kernel(self, h1e, eri, norb, nelec, ci0=None, tol=None, lindep=None, max_cycle=None, max_space=None, nroots=None, davidson_only=None, pspace_size=None, orbsym=None, wfnsym=None, ecore: int = 0, **kwargs): ...
FCI = FCISolver
