from _typeshed import Incomplete
from pyscf import ao2mo as ao2mo, lib as lib
from pyscf.fci import cistring as cistring, direct_spin1 as direct_spin1, rdm as rdm
from pyscf.fci.spin_op import contract_ss as contract_ss
from pyscf.lib import logger as logger

libfci: Incomplete

def contract_1e(f1e, fcivec, norb, nelec, link_index=None): ...
def contract_2e(eri, fcivec, norb, nelec, link_index=None): ...
absorb_h1e = direct_spin1.absorb_h1e

def make_hdiag(h1e, eri, norb, nelec, compress: bool = False): ...
pspace = direct_spin1.pspace

def kernel(h1e, eri, norb, nelec, ci0=None, level_shift: float = 0.001, tol: float = 1e-10, lindep: float = 1e-14, max_cycle: int = 50, max_space: int = 12, nroots: int = 1, davidson_only: bool = False, pspace_size: int = 400, orbsym=None, wfnsym=None, ecore: int = 0, **kwargs): ...
def make_rdm1(fcivec, norb, nelec, link_index=None): ...
def make_rdm1s(fcivec, norb, nelec, link_index=None): ...
def make_rdm12(fcivec, norb, nelec, link_index=None, reorder: bool = True): ...
def trans_rdm1s(cibra, ciket, norb, nelec, link_index=None): ...
def trans_rdm1(cibra, ciket, norb, nelec, link_index=None): ...
def trans_rdm12(cibra, ciket, norb, nelec, link_index=None, reorder: bool = True): ...
def energy(h1e, eri, fcivec, norb, nelec, link_index=None): ...
def get_init_guess(norb, nelec, nroots, hdiag): ...
def kernel_ms0(fci, h1e, eri, norb, nelec, ci0=None, link_index=None, tol=None, lindep=None, max_cycle=None, max_space=None, nroots=None, davidson_only=None, pspace_size=None, hop=None, max_memory=None, verbose=None, ecore: int = 0, **kwargs): ...

class FCISolver(direct_spin1.FCISolver):
    make_hdiag: Incomplete
    def contract_1e(self, f1e, fcivec, norb, nelec, link_index=None, **kwargs): ...
    def contract_2e(self, eri, fcivec, norb, nelec, link_index=None, **kwargs): ...
    def get_init_guess(self, norb, nelec, nroots, hdiag): ...
    norb: Incomplete
    nelec: Incomplete
    eci: Incomplete
    ci: Incomplete
    def kernel(self, h1e, eri, norb, nelec, ci0=None, tol=None, lindep=None, max_cycle=None, max_space=None, nroots=None, davidson_only=None, pspace_size=None, orbsym=None, wfnsym=None, ecore: int = 0, **kwargs): ...
    def energy(self, h1e, eri, fcivec, norb, nelec, link_index=None): ...
    def make_rdm1s(self, fcivec, norb, nelec, link_index=None): ...
    def make_rdm1(self, fcivec, norb, nelec, link_index=None): ...
    def make_rdm12(self, fcivec, norb, nelec, link_index=None, reorder: bool = True): ...
    def trans_rdm1s(self, cibra, ciket, norb, nelec, link_index=None): ...
    def trans_rdm1(self, cibra, ciket, norb, nelec, link_index=None): ...
    def trans_rdm12(self, cibra, ciket, norb, nelec, link_index=None, reorder: bool = True): ...
    def gen_linkstr(self, norb, nelec, tril: bool = True, spin=None): ...
FCI = FCISolver
