from pyscf import ao2mo as ao2mo, lib as lib
from pyscf.fci import cistring as cistring, rdm as rdm

def contract_all(t, u, g, hpp, ci0, nsite, nelec, nphonon): ...
def make_shape(nsite, nelec, nphonon): ...
def contract_1e(h1e, fcivec, nsite, nelec, nphonon): ...
def contract_2e(eri, fcivec, nsite, nelec, nphonon): ...
def contract_2e_hubbard(u, fcivec, nsite, nelec, nphonon): ...
def slices_for(psite_id, nsite, nphonon): ...
def slices_for_cre(psite_id, nsite, nphonon): ...
def slices_for_des(psite_id, nsite, nphonon): ...
def contract_ep(g, fcivec, nsite, nelec, nphonon): ...
def cre_phonon(fcivec, nsite, nelec, nphonon, site_id): ...
def des_phonon(fcivec, nsite, nelec, nphonon, site_id): ...
def contract_pp(hpp, fcivec, nsite, nelec, nphonon): ...
def make_hdiag(t, u, g, hpp, nsite, nelec, nphonon): ...
def kernel(t, u, g, hpp, nsite, nelec, nphonon, tol: float = 1e-09, max_cycle: int = 100, verbose: int = 0, ecore: int = 0, **kwargs): ...
def make_rdm1e(fcivec, nsite, nelec): ...
def make_rdm12e(fcivec, nsite, nelec): ...
def make_rdm1p(fcivec, nsite, nelec, nphonon): ...
