from pyscf import ao2mo as ao2mo, lib as lib
from pyscf.fci import cistring as cistring

def contract_1e(f1e, fcivec, norb, nelec): ...
def contract_2e(eri, fcivec, norb, nelec, link_index=None): ...
def contract_2e_hubbard(u, fcivec, norb, nelec, opt=None): ...
def absorb_h1e(h1e, eri, norb, nelec, fac: int = 1): ...
def make_hdiag(h1e, eri, norb, nelec, opt=None): ...
def kernel(h1e, eri, norb, nelec, ecore: int = 0): ...
def make_rdm1(fcivec, norb, nelec, opt=None): ...
def make_rdm12(fcivec, norb, nelec, opt=None): ...
def reorder_rdm(rdm1, rdm2, inplace: bool = True): ...
