from _typeshed import Incomplete
from pyscf import ao2mo as ao2mo, lib as lib
from pyscf.fci import cistring as cistring, direct_spin1 as direct_spin1
from pyscf.lib import logger as logger

def contract_2e(eri, fcivec, norb, nelec, opt=None): ...
def absorb_h1e(h1e, eri, norb, nelec, fac: int = 1): ...
def make_hdiag(h1e, eri, norb, nelec, opt=None): ...
def kernel(h1e, eri, norb, nelec, ecore: int = 0, nroots: int = 1, verbose: int = 3): ...
def make_rdm1_slow(fcivec, norb, nelec, link_index=None): ...
def make_rdm1(fcivec, norb, nelec, link_index=None): ...
def make_rdm12(fcivec, norb, nelec, link_index=None, reorder: bool = True): ...
def reorder_rdm(rdm1, rdm2, inplace: bool = True): ...
def get_init_guess(norb, nelec, nroots, hdiag): ...
def kernel_dhf(fci, h1e, eri, norb, nelec, ci0=None, link_index=None, tol=None, lindep=None, max_cycle=None, max_space=None, nroots=None, davidson_only=None, pspace_size=None, max_memory=None, verbose=None, ecore: int = 0, **kwargs): ...

class FCISolver(direct_spin1.FCISolver):
    def absorb_h1e(self, h1e, eri, norb, nelec, fac: int = 1): ...
    def make_hdiag(self, h1e, eri, norb, nelec): ...
    def pspace(self, h1e, eri, norb, nelec, hdiag, np: int = 400): ...
    def contract_1e(self, f1e, fcivec, norb, nelec, link_index=None, **kwargs): ...
    def contract_2e(self, eri, fcivec, norb, nelec, link_index=None, **kwargs): ...
    def spin_square(self, fcivec, norb, nelec): ...
    def make_rdm1(self, fcivec, norb, nelec, link_index=None): ...
    def make_rdm12(self, fcivec, norb, nelec, link_index=None, reorder: bool = True): ...
    def make_rdm2(self, fcivec, norb, nelec, link_index=None, reorder: bool = True): ...
    def energy(self, h1e, eri, fcivec, norb, nelec, link_index=None): ...
    def get_init_guess(self, norb, nelec, nroots, hdiag): ...
    norb: Incomplete
    nelec: Incomplete
    def kernel(self, h1e, eri, norb, nelec, ci0=None, tol=None, lindep=None, max_cycle=None, max_space=None, nroots=None, davidson_only=None, pspace_size=None, orbsym=None, wfnsym=None, ecore: int = 0, **kwargs): ...
FCI = FCISolver
