from _typeshed import Incomplete
from pyscf import lib as lib
from pyscf.fci import cistring as cistring

librdm: Incomplete

def reorder_rdm(rdm1, rdm2, inplace: bool = False): ...
def make_rdm1_ms0(fname, cibra, ciket, norb, nelec, link_index=None): ...
def make_rdm12_ms0(fname, cibra, ciket, norb, nelec, link_index=None, symm: int = 0): ...
make_rdm1 = make_rdm1_ms0
make_rdm12 = make_rdm12_ms0

def make_rdm1_spin1(fname, cibra, ciket, norb, nelec, link_index=None): ...
def make_rdm12_spin1(fname, cibra, ciket, norb, nelec, link_index=None, symm: int = 0): ...
def make_dm123(fname, cibra, ciket, norb, nelec): ...
def make_dm1234(fname, cibra, ciket, norb, nelec): ...
def reorder_dm12(rdm1, rdm2, inplace: bool = True): ...
def reorder_dm123(rdm1, rdm2, rdm3, inplace: bool = True): ...
def reorder_dm1234(rdm1, rdm2, rdm3, rdm4, inplace: bool = True): ...
