from pyscf import ao2mo as ao2mo, lib as lib
from pyscf.fci import cistring as cistring, direct_spin1 as direct_spin1
from pyscf.lib import logger as logger

def contract_2e(eri, civec_strs, norb, nelec, link_index=None): ...
def enlarge_space(myci, civec_strs, eri, norb, nelec): ...
def cre_des_linkstr(strs, norb, nelec): ...
def des_des_linkstr(strs, norb, nelec): ...
def make_hdiag(h1e, g2e, ci_strs, norb, nelec): ...
def kernel(h1e, eri, norb, nelec, ecore: int = 0, verbose=...): ...
def make_rdm1(civec_strs, norb, nelec): ...
def make_rdm2(civec_strs, norb, nelec): ...

class SelectedCI:
    ci_coeff_cutoff: float
    select_cutoff: float
    float_tol: float
    conv_tol: float
    def __init__(self) -> None: ...
