import numpy
from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, lib as lib
from pyscf.fci import cistring as cistring, direct_spin1 as direct_spin1, rdm as rdm
from pyscf.lib import logger as logger

libfci: Incomplete

def contract_2e(eri, civec_strs, norb, nelec, link_index=None): ...
def select_strs(myci, eri, eri_pq_max, civec_max, strs, norb, nelec): ...
def enlarge_space(myci, civec_strs, eri, norb, nelec): ...
def cre_des_linkstr(strs, norb, nelec, tril: bool = False): ...
def cre_des_linkstr_tril(strs, norb, nelec): ...
def des_des_linkstr(strs, norb, nelec, tril: bool = False): ...
def des_des_linkstr_tril(strs, norb, nelec): ...
def gen_des_linkstr(strs, norb, nelec): ...
def gen_cre_linkstr(strs, norb, nelec): ...
def make_hdiag(h1e, eri, ci_strs, norb, nelec, compress: bool = False): ...
def kernel_fixed_space(myci, h1e, eri, norb, nelec, ci_strs, ci0=None, tol=None, lindep=None, max_cycle=None, max_space=None, nroots=None, davidson_only=None, max_memory=None, verbose=None, ecore: int = 0, **kwargs): ...
def kernel_float_space(myci, h1e, eri, norb, nelec, ci0=None, tol=None, lindep=None, max_cycle=None, max_space=None, nroots=None, davidson_only=None, max_memory=None, verbose=None, ecore: int = 0, **kwargs): ...
def kernel(h1e, eri, norb, nelec, ci0=None, level_shift: float = 0.001, tol: float = 1e-10, lindep: float = 1e-14, max_cycle: int = 50, max_space: int = 12, nroots: int = 1, davidson_only: bool = False, pspace_size: int = 400, orbsym=None, wfnsym=None, select_cutoff: float = 0.001, ci_coeff_cutoff: float = 0.001, ecore: int = 0, **kwargs): ...
def make_rdm1s(civec_strs, norb, nelec, link_index=None): ...
def make_rdm1(civec_strs, norb, nelec, link_index=None): ...
def make_rdm2s(civec_strs, norb, nelec, link_index=None, **kwargs): ...
def make_rdm2(civec_strs, norb, nelec, link_index=None, **kwargs): ...
def trans_rdm1s(cibra_strs, ciket_strs, norb, nelec, link_index=None): ...
def trans_rdm1(cibra_strs, ciket_strs, norb, nelec, link_index=None): ...
def spin_square(civec_strs, norb, nelec): ...
def contract_ss(civec_strs, norb, nelec): ...
def to_fci(civec_strs, norb, nelec): ...
def from_fci(fcivec, ci_strs, norb, nelec): ...

class SelectedCI(direct_spin1.FCISolver):
    ci_coeff_cutoff: Incomplete
    select_cutoff: Incomplete
    conv_tol: Incomplete
    start_tol: Incomplete
    tol_decay_rate: Incomplete
    def __init__(self, mol=None) -> None: ...
    def dump_flags(self, verbose=None) -> None: ...
    def contract_2e(self, eri, civec_strs, norb, nelec, link_index=None, **kwargs): ...
    def get_init_guess(self, ci_strs, norb, nelec, nroots, hdiag): ...
    make_hdiag: Incomplete
    enlarge_space = enlarge_space
    kernel = kernel_float_space
    kernel_fixed_space = kernel_fixed_space
    def spin_square(self, civec_strs, norb, nelec): ...
    def large_ci(self, civec_strs, norb, nelec, tol: float = 0.1, return_strs: bool = True): ...
    def contract_ss(self, fcivec, norb, nelec): ...
    def make_rdm1s(self, civec_strs, norb, nelec, link_index=None): ...
    def make_rdm1(self, civec_strs, norb, nelec, link_index=None): ...
    def make_rdm2s(self, civec_strs, norb, nelec, link_index=None, **kwargs): ...
    def make_rdm2(self, civec_strs, norb, nelec, link_index=None, **kwargs): ...
    def make_rdm12s(self, civec_strs, norb, nelec, link_index=None, **kwargs): ...
    def make_rdm12(self, civec_strs, norb, nelec, link_index=None, **kwargs): ...
    def trans_rdm1s(self, cibra, ciket, norb, nelec, link_index=None): ...
    def trans_rdm1(self, cibra, ciket, norb, nelec, link_index=None): ...
    def gen_linkstr(self, norb, nelec, tril: bool = True, spin=None, ci_strs=None): ...
SCI = SelectedCI

class SCIvector(numpy.ndarray):
    def __array_finalize__(self, obj) -> None: ...
    def __array_wrap__(self, out, context=None, return_scalar: bool = False): ...
