from _typeshed import Incomplete
from pyscf import lib as lib
from pyscf.fci import cistring as cistring

librdm: Incomplete

def spin_square_general(dm1a, dm1b, dm2aa, dm2ab, dm2bb, mo_coeff, ovlp: int = 1): ...
def spin_square(fcivec, norb, nelec, mo_coeff=None, ovlp: int = 1, fcisolver=None): ...
def spin_square0(fcivec, norb, nelec): ...
def local_spin(fcivec, norb, nelec, mo_coeff=None, ovlp: int = 1, aolst=[]): ...
def make_rdm2_baab(fcivec, norb, nelec): ...
def make_rdm2_abba(fcivec, norb, nelec): ...
def contract_ss(fcivec, norb, nelec): ...
