from _typeshed import Incomplete
from pyscf import __config__ as __config__, df as df, lib as lib, scf as scf
from pyscf.lib import logger as logger
from pyscf.mp.mp2 import get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc
from scipy.optimize import least_squares as least_squares

einsum = lib.einsum

def kernel(gw, mo_energy, mo_coeff, Lpq=None, orbs=None, nw=None, vhf_df: bool = False, verbose=...): ...
def get_sigma_diag(gw, ep, p, Lpq, Wmn, freqs, wts): ...
def get_rho_response(omega, mo_energy, Lpq): ...
def get_WmnI_diag(gw, orbs, Lpq, freqs): ...
def get_sigmaI_diag(gw, omega, Wmn, sign, freqs, wts): ...
def get_rho_response_R(gw, omega, Lpq): ...
def get_sigmaR_diag(gw, omega, orbp, ef, Lpq): ...

class GWCD(lib.StreamObject):
    eta: Incomplete
    linearized: Incomplete
    mol: Incomplete
    verbose: Incomplete
    stdout: Incomplete
    max_memory: Incomplete
    frozen: Incomplete
    with_df: Incomplete
    mo_energy: Incomplete
    mo_coeff: Incomplete
    mo_occ: Incomplete
    sigma: Incomplete
    def __init__(self, mf, frozen=None) -> None: ...
    def dump_flags(self): ...
    @property
    def nocc(self): ...
    @nocc.setter
    def nocc(self, n) -> None: ...
    @property
    def nmo(self): ...
    @nmo.setter
    def nmo(self, n) -> None: ...
    get_nocc = get_nocc
    get_nmo = get_nmo
    get_frozen_mask = get_frozen_mask
    def kernel(self, mo_energy=None, mo_coeff=None, Lpq=None, orbs=None, nw: int = 100, vhf_df: bool = False): ...
    def ao2mo(self, mo_coeff=None): ...
