from _typeshed import Incomplete
from pyscf.lib import direct_sum as direct_sum, einsum as einsum, logger as logger

class AbstractIMDS:
    orb_dims: int
    td: Incomplete
    eri: Incomplete
    def __init__(self, td, eri=None) -> None: ...
    def get_rhs(self, p) -> None: ...
    def entire_space(self) -> None: ...
    def get_sigma_element(self, omega, p, **kwargs) -> None: ...
    def quasiparticle_eq(self, p, **kwargs): ...
    def initial_guess(self, p) -> None: ...

def corrected_moe(eri, p): ...

class IMDS(AbstractIMDS):
    nocc: Incomplete
    td_xy: Incomplete
    td_e: Incomplete
    tdm: Incomplete
    def __init__(self, td, eri=None) -> None: ...
    def __getitem__(self, item): ...
    def get_rhs(self, p): ...
    def construct_tdm(self): ...
    def get_sigma_element(self, omega, p, eta, vir_sgn: int = 1): ...
    def initial_guess(self, p): ...
    @property
    def entire_space(self): ...

class LoggingFunction:
    m: Incomplete
    __x__: Incomplete
    __y__: Incomplete
    def __init__(self, m) -> None: ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    def __call__(self, x): ...
    def plot_call_history(self, title: str = '') -> None: ...

def kernel(imds, orbs=None, linearized: bool = False, eta: float = 0.001, tol: float = 1e-09, method: str = 'fallback'): ...

class GW:
    base_imds = IMDS
    td: Incomplete
    imds: Incomplete
    mo_energy: Incomplete
    orbs: Incomplete
    method: str
    eta: float
    def __init__(self, td, eri=None) -> None: ...
    def kernel(self): ...
