from _typeshed import Incomplete
from pyscf import df as df, lib as lib, scf as scf
from pyscf.lib import logger as logger
from pyscf.mp import dfmp2 as dfmp2

einsum = lib.einsum

def kernel(rpa, eris=None, nw: int = 40, x0: float = 0.5, verbose=None): ...
def make_dielectric_matrix(omega, e_ov, f_ov, eris, blksize=None): ...

class RPA(dfmp2.DFMP2):
    def dump_flags(self, verbose=None): ...
    def kernel(self, eris=None, nw: int = 40, x0: float = 0.5): ...
    e_hf: Incomplete
    def get_e_hf(self): ...
    def make_e_ov(self): ...
    def make_f_ov(self): ...
    def make_dielectric_matrix(self, omega, e_ov=None, f_ov=None, eris=None, max_memory=None, blksize=None): ...
dRPA = RPA
DirectRPA = RPA
