from _typeshed import Incomplete
from pyscf import dft as dft, lib as lib, scf as scf
from pyscf.ao2mo._ao2mo import nr_e2 as nr_e2
from pyscf.gw.gw_ac import GWAC as GWAC
from pyscf.gw.utils.ac_grid import PadeAC as PadeAC, TwoPoleAC as TwoPoleAC
from pyscf.gw.utils.gw_np_helper import get_id_minus_pi_inv_minus_id as get_id_minus_pi_inv_minus_id, mkslice as mkslice
from pyscf.lib import einsum as einsum, logger as logger, temporary_env as temporary_env
from pyscf.mp.ump2 import get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc

def kernel(gw): ...
def get_rho_response(omega, mo_energy, Lpqa, Lpqb): ...
def get_rho_response_metal(omega, mo_energy, mo_occ, Lpqa, Lpqb): ...
def get_sigma(gw, orbs, Lpq, quad_freqs, quad_wts, ef, mo_energy, mo_occ=None, iw_cutoff=None, eval_freqs=None, mo_energy_w=None, fullsigma: bool = False): ...
def get_sigma_outcore(gw, orbs, quad_freqs, quad_wts, ef, mo_energy, mo_coeff, mo_occ=None, iw_cutoff=None, eval_freqs=None, mo_energy_w=None, fullsigma: bool = False): ...
def get_g0(omega, mo_energy, eta): ...
def set_frozen_orbs(gw) -> None: ...

class UGWAC(GWAC):
    def __init__(self, mf, frozen=None, auxbasis=None) -> None: ...
    def dump_flags(self, verbose=None) -> None: ...
    get_nocc = get_nocc
    get_nmo = get_nmo
    get_frozen_mask = get_frozen_mask
    nw: Incomplete
    ac_pade_npts: int
    ac_pade_step_ratio: Incomplete
    frozen: Incomplete
    def kernel(self) -> None: ...
    def ao2mo(self, mo_coeff=None): ...
    def loop_ao2mo(self, mo_coeff=None, spin=None, ijslicea=None, ijsliceb=None): ...
    def get_ef(self, mo_energy=None): ...
    def make_rdm1(self, ao_repr: bool = False, mode: str = 'linear'): ...
    def make_gf(self, omega, eta: float = 0.0, mode: str = 'dyson'): ...
