from _typeshed import Incomplete
from pyscf import lib as lib
from pyscf.grad import rhf as molgrad
from pyscf.gto import mole as mole
from pyscf.lib import logger as logger
from pyscf.pbc import gto as gto, tools as tools
from pyscf.pbc.dft.numint import eval_ao_kpts as eval_ao_kpts
from pyscf.pbc.gto.pseudo import pp_int as pp_int
from pyscf.pbc.gto.pseudo.pp import get_alphas as get_alphas, get_projG as get_projG, get_vlocG as get_vlocG, projG_li as projG_li

def grad_elec(mf_grad, mo_energy=None, mo_coeff=None, mo_occ=None, atmlst=None): ...
def get_hcore(cell, kpts): ...
def get_ovlp(cell, kpts): ...
def hcore_generator(mf_grad, cell=None, kpts=None): ...
def grad_nuc(cell, atmlst): ...
def get_jk(mf_grad, dm, kpts): ...
def get_j(mf_grad, dm, kpts): ...
def get_k(mf_grad, dm, kpts): ...
def get_veff(mf_grad, dm, kpts): ...
def make_rdm1e(mo_energy, mo_coeff, mo_occ): ...

class GradientsBase(molgrad.GradientsBase):
    cell: Incomplete
    def __init__(self, method) -> None: ...
    @property
    def kpts(self): ...
    def reset(self, cell=None): ...
    def get_hcore(self, cell=None, kpts=None): ...
    hcore_generator = hcore_generator
    def get_ovlp(self, cell=None, kpts=None): ...
    def get_jk(self, dm=None, kpts=None): ...
    def get_j(self, dm=None, kpts=None): ...
    def get_k(self, dm=None, kpts=None, kpts_band=None): ...
    def grad_nuc(self, cell=None, atmlst=None): ...
    def optimizer(self, solver: str = 'ase'): ...

def as_scanner(mf_grad): ...

class SCF_GradScanner(lib.GradScanner):
    def __init__(self, g) -> None: ...
    cell: Incomplete
    def __call__(self, cell_or_geom, **kwargs): ...

class Gradients(GradientsBase):
    def get_veff(self, dm=None, kpts=None): ...
    def make_rdm1e(self, mo_energy=None, mo_coeff=None, mo_occ=None): ...
    def extra_force(self, atom_id, envs): ...
    grad_elec = grad_elec
    as_scanner = as_scanner
    atmlst: Incomplete
    de: Incomplete
    def kernel(self, mo_energy=None, mo_coeff=None, mo_occ=None, atmlst=None): ...
