from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.grad import rhf as mol_rhf
from pyscf.lib import logger as logger
from pyscf.pbc.dft.multigrid import MultiGridNumInt2 as MultiGridNumInt2
from pyscf.pbc.gto.pseudo import pp_int as pp_int
from pyscf.pbc.lib.kpts_helper import gamma_point as gamma_point

SCREEN_VHF_DM_CONTRA: Incomplete
libpbc: Incomplete

def grad_elec(mf_grad, mo_energy=None, mo_coeff=None, mo_occ=None, atmlst=None, kpt=...): ...
def get_ovlp(cell, kpt=...): ...
def get_veff(mf_grad, mol, dm, kpt=...): ...
def grad_nuc(cell, atmlst=None, ew_eta=None, ew_cut=None): ...

class GradientsBase(mol_rhf.GradientsBase):
    def grad_nuc(self, mol=None, atmlst=None): ...
    def get_ovlp(self, mol=None, kpt=...): ...
    def optimizer(self, solver: str = 'ase'): ...

class Gradients(GradientsBase):
    def get_veff(self, mol=None, dm=None, kpt=...): ...
    make_rdm1e: Incomplete
    grad_elec = grad_elec
