from pyscf import gto as gto, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc.df import FFTDF as FFTDF, ft_ao as ft_ao
from pyscf.pbc.dft.gen_grid import UniformGrids, UniformGrids as UniformGrids
from pyscf.pbc.dft.numint import NumInt as NumInt
from pyscf.pbc.gto import pseudo as pseudo
from pyscf.pbc.lib.kpts_helper import is_zero as is_zero
from numpy import float64, ndarray
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.grad.rks import Gradients
from pyscf.pbc.gto.cell import Cell
from typing import List, Optional, Tuple, Union

def strain_tensor_dispalcement(x: int, y: int, disp: float) -> ndarray: ...
def get_ovlp(cell: Cell) -> List[ndarray]: ...
def get_kin(cell: Cell) -> List[ndarray]: ...
def get_vxc(ks_grad: Gradients, cell: Cell, dm: Union[ndarray, NPArrayWithTag], with_j: bool = False, with_nuc: bool = False) -> ndarray: ...
def ewald(cell: Cell) -> ndarray: ...
def kernel(mf_grad: Gradients) -> ndarray: ...
