from _typeshed import Incomplete

def davidson_nosymm(matvec, size, nroots, Adiag=None): ...

VERBOSE: bool

class Arnoldi:
    matrMultiply: Incomplete
    size: Incomplete
    nEigen: Incomplete
    maxM: Incomplete
    maxOuterLoop: int
    tol: Incomplete
    x0: Incomplete
    iteration: int
    totalIter: int
    converged: bool
    preCon: Incomplete
    def __init__(self, matr_multiply, xStart, inPreCon, nroots: int = 1, tol: float = 1e-06) -> None: ...
    currentSize: Incomplete
    deflated: int
    def solve(self): ...
    subH: Incomplete
    sol: Incomplete
    dgks: Incomplete
    nConv: Incomplete
    eigs: Incomplete
    evecs: Incomplete
    oldeigs: Incomplete
    deigs: Incomplete
    outeigs: Incomplete
    outevecs: Incomplete
    Ax: Incomplete
    res: Incomplete
    vlist: Incomplete
    cv: Incomplete
    cAv: Incomplete
    Avlist: Incomplete
    dres: float
    resnorm: float
    cvEig: float
    ciEig: int
    def allocateVecs(self) -> None: ...
    def guessInitial(self) -> None: ...
    def hMult(self) -> None: ...
    def push_Av(self) -> None: ...
    def constructSubspace(self) -> None: ...
    def solveSubspace(self) -> None: ...
    def constructAllSolV(self) -> None: ...
    def constructSol(self) -> None: ...
    def constructSolV(self) -> None: ...
    def constructSolAv(self) -> None: ...
    def computeResidual(self) -> None: ...
    def updateVecs(self) -> None: ...
    def checkConvergence(self) -> None: ...
    def gramSchmidtCurrentVec(self, northo) -> None: ...
    def checkDeflate(self) -> None: ...
    def constructDeflatedSub(self) -> None: ...
