from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, lib as lib

KPT_DIFF_TOL: Incomplete

def is_zero(kpt): ...
is_gamma_point = is_zero
gamma_point = is_zero

def is_trim(cell, kpts, tol=...): ...
def round_to_fbz(kpts, wrap_around: bool = False, tol=...): ...
def member(kpt, kpts): ...
def intersection(kpts1, kpts2): ...
def unique(kpts): ...
def unique_with_wrap_around(cell, kpts): ...
def members_with_wrap_around(cell, kpts, test_kpts): ...
def group_by_conj_pairs(cell, kpts, wrap_around: bool = True, return_kpts_pairs: bool = True): ...
def kk_adapted_iter(cell, kpts, kk_idx=None, time_reversal_symmetry: bool = True) -> Generator[Incomplete]: ...
def loop_kkk(nkpts): ...
def conj_mapping(cell, kpts): ...
def get_kconserv(cell, kpts): ...
def get_kconserv_ria(cell, kpts): ...
def check_kpt_antiperm_symmetry(array, idx1, idx2, tolerance: float = 1e-08): ...
def get_kconserv3(cell, kpts, kijkab): ...

class VectorComposer:
    __dtype__: Incomplete
    __transactions__: Incomplete
    __total_size__: int
    __data__: Incomplete
    def __init__(self, dtype) -> None: ...
    def put(self, a) -> None: ...
    def flush(self): ...

class VectorSplitter:
    __data__: Incomplete
    __offset__: int
    def __init__(self, vector) -> None: ...
    def get(self, destination, slc=None): ...
    def truncate(self) -> None: ...

class KptsHelper(lib.StreamObject):
    kconserv: Incomplete
    nkpts: Incomplete
    symm_map: Incomplete
    def __init__(self, cell, kpts, init_symm_map: bool = True) -> None: ...
    def build_symm_map(self, kptlist=None): ...
    def transform_symm(self, eri_kpt, kp, kq, kr): ...

class KPointSymmetryError(RuntimeError): ...
