from _typeshed import Incomplete
from collections.abc import Generator
from pyscf import __config__ as __config__, lib as lib
from itertools import product
from numpy import bool, int32, int64, ndarray
from pyscf.pbc.gto.cell import Cell
from pyscf.pbc.lib.kpts import KPoints
from typing import Any, Iterator, List, Optional, Tuple, Union

KPT_DIFF_TOL: Incomplete

def is_zero(kpt: Union[ndarray, List[ndarray], Tuple[ndarray, ndarray]]) -> bool: ...
is_gamma_point = is_zero
gamma_point = is_zero

def is_trim(cell: Cell, kpts: ndarray, tol: float=...) -> ndarray: ...
def round_to_fbz(kpts: ndarray, wrap_around: bool = False, tol: float=...) -> ndarray: ...
def member(kpt: ndarray, kpts: ndarray) -> ndarray: ...
def intersection(kpts1: ndarray, kpts2: ndarray) -> ndarray: ...
def unique(kpts: ndarray) -> Tuple[ndarray, ndarray, ndarray]: ...
def unique_with_wrap_around(cell: Cell, kpts: ndarray) -> Tuple[ndarray, ndarray, ndarray]: ...
def members_with_wrap_around(cell: Cell, kpts: ndarray, test_kpts: ndarray) -> ndarray: ...
def group_by_conj_pairs(cell: Cell, kpts: ndarray, wrap_around: bool = True, return_kpts_pairs: bool = True) -> Any: ...
def kk_adapted_iter(cell: Cell, kpts: ndarray, kk_idx: Optional[ndarray]=None, time_reversal_symmetry: bool = True) -> Iterator[Union[Tuple[ndarray, ndarray, ndarray, bool], Tuple[ndarray, ndarray, ndarray, bool]]]: ...
def loop_kkk(nkpts: Union[int64, int]) -> product: ...
def conj_mapping(cell: Cell, kpts: ndarray) -> ndarray: ...
def get_kconserv(cell: Cell, kpts: ndarray) -> ndarray: ...
def get_kconserv_ria(cell: Cell, kpts: ndarray) -> ndarray: ...
def check_kpt_antiperm_symmetry(array, idx1, idx2, tolerance: float = 1e-08): ...
def get_kconserv3(cell: Cell, kpts: ndarray, kijkab: List[Union[int, range]]) -> ndarray: ...

class VectorComposer:
    __dtype__: Incomplete
    __transactions__: Incomplete
    __total_size__: int
    __data__: Incomplete
    def __init__(self, dtype) -> None: ...
    def put(self, a) -> None: ...
    def flush(self): ...

class VectorSplitter:
    __data__: Incomplete
    __offset__: int
    def __init__(self, vector) -> None: ...
    def get(self, destination, slc=None): ...
    def truncate(self) -> None: ...

class KptsHelper(lib.StreamObject):
    kconserv: Incomplete
    nkpts: Incomplete
    symm_map: Incomplete
    def __init__(self, cell: Cell, kpts: Union[ndarray, KPoints], init_symm_map: bool = True) -> None: ...
    def build_symm_map(self, kptlist: Optional[ndarray]=None): ...
    def transform_symm(self, eri_kpt: ndarray, kp: Union[int64, int32], kq: Union[int64, int32], kr: Union[int64, int32]) -> ndarray: ...

class KPointSymmetryError(RuntimeError): ...
