from _typeshed import Incomplete
from collections.abc import Generator
from numpy.linalg import inv as inv
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc.lib import kpts_helper as kpts_helper
from pyscf.pbc.lib.kpts_helper import KPT_DIFF_TOL as KPT_DIFF_TOL, is_zero as is_zero, member as member, round_to_fbz as round_to_fbz
from pyscf.pbc.symm import symmetry as symm
from pyscf.pbc.symm.group import PGElement as PGElement, PointGroup as PointGroup, Representation as Representation
from numpy import bool, int64, ndarray
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.gto.cell import Cell
from typing import Iterator, List, Optional, Tuple, Union

libpbc: Incomplete

def is_gamma_point(kpt_or_kpts: ndarray) -> bool: ...
def make_kpts_ibz(kpts: "KPoints", tol: float=...) -> None: ...
def make_ktuples_ibz(kpts: "KPoints", kpts_scaled: None=None, ntuple: int = 2, tol: float=...) -> Tuple[ndarray, ndarray, ndarray, List[ndarray], List[ndarray], ndarray]: ...
def make_k4_ibz(kpts: "KPoints", sym: str = 's1', return_ops: bool = False) -> Union[Tuple[ndarray, ndarray, ndarray, ndarray, List[ndarray], ndarray], Tuple[ndarray, ndarray, ndarray]]: ...
def map_k_points_fast(kpts_scaled: ndarray, ops: ndarray, tol: float=...) -> ndarray: ...
def map_kpts_tuples(kpts_scaled: ndarray, ops: ndarray, ntuple: int = 2, tol: float=...) -> ndarray: ...
def symmetrize_density(kpts: "KPoints", rhoR_k: ndarray, ibz_k_idx: int, mesh: List[int]) -> ndarray: ...
def symmetrize_wavefunction(kpts, psiR_k, mesh): ...
def transform_mo_coeff(kpts: "KPoints", mo_coeff_ibz: Union[ndarray, List[ndarray], List[NPArrayWithTag], Tuple[ndarray, ndarray]]) -> List[Union[NPArrayWithTag, ndarray, List[ndarray]]]: ...
def transform_mo_coeff_k(kpts, mo_coeff_ibz, k): ...
transform_single_mo_coeff = transform_mo_coeff_k

def transform_mo_occ(kpts: "KPoints", mo_occ_ibz: Union[Tuple[List[ndarray], List[ndarray]], List[ndarray], ndarray]) -> List[Union[ndarray, List[ndarray]]]: ...
def transform_dm(kpts: "KPoints", dm_ibz: Union[ndarray, List[ndarray], List[List[ndarray]], NPArrayWithTag]) -> Union[ndarray, NPArrayWithTag]: ...
def dm_at_ref_cell(kpts, dm_ibz): ...
def transform_mo_energy(kpts: "KPoints", mo_energy_ibz: Union[ndarray, List[ndarray]]) -> List[Union[ndarray, List[ndarray]]]: ...
def transform_1e_operator(kpts: "KPoints", fock_ibz: ndarray) -> ndarray: ...
transform_fock = transform_1e_operator

def check_mo_occ_symmetry(kpts: "KPoints", mo_occ: Union[ndarray, List[ndarray]], tol: float = 1e-05) -> List[ndarray]: ...
def get_rotation_mat_for_mos(kpts: "KPoints", mo_coeff: List[ndarray], ovlp: ndarray, k1: ndarray, k2: ndarray, ops_id: Optional[ndarray]=None) -> List[ndarray]: ...
def make_kpts(cell: Cell, kpts: ndarray=..., space_group_symmetry: bool = False, time_reversal_symmetry: bool = False, **kwargs) -> "KPoints": ...

class KPoints(symm.Symmetry, lib.StreamObject):
    verbose: Incomplete
    stdout: Incomplete
    time_reversal: bool
    kpts_ibz: Incomplete
    kpts_scaled_ibz: Incomplete
    weights_ibz: Incomplete
    ibz2bz: Incomplete
    k2opk: Incomplete
    stars: Incomplete
    stars_ops: Incomplete
    stars_ops_bz: Incomplete
    time_reversal_symm_bz: Incomplete
    little_cogroup_ops: Incomplete
    def __init__(self, cell: Optional[Cell]=None, kpts: ndarray=...) -> None: ...
    @property
    def nkpts(self): ...
    @nkpts.setter
    def nkpts(self, n) -> None: ...
    @property
    def nkpts_ibz(self): ...
    @nkpts_ibz.setter
    def nkpts_ibz(self, n) -> None: ...
    def __len__(self) -> int: ...
    def build(self, space_group_symmetry: bool = False, time_reversal_symmetry: bool = False, *args, **kwargs) -> "KPoints": ...
    cell: Incomplete
    kpts: Incomplete
    def reset(self, cell: Optional[Cell]=None) -> "KPoints": ...
    def dump_info(self) -> None: ...
    def make_gdf_kptij_lst_jk(self): ...
    def loop_ktuples(self, ibz2bz: ndarray, ntuple: int) -> Iterator[Union[Tuple[int64, int64, int64], Tuple[int, int64, int64]]]: ...
    def ktuple_to_index(self, kk: ndarray) -> int64: ...
    def index_to_ktuple(self, k: Union[int64, ndarray], ntuple: int) -> Union[ndarray, List[int64], List[Union[int, int64]]]: ...
    @property
    def addition_table(self, tol: float=...) -> ndarray: ...
    @property
    def inverse_table(self, tol: float=...) -> ndarray: ...
    def get_kconserv(self) -> ndarray: ...
    def little_cogroups(self, return_indices: bool = True): ...
    def little_cogroup_rep(self, ki, ir): ...
    make_kpts_ibz = make_kpts_ibz
    make_ktuples_ibz = make_ktuples_ibz
    make_k4_ibz = make_k4_ibz
    symmetrize_density = symmetrize_density
    symmetrize_wavefunction = symmetrize_wavefunction
    transform_mo_coeff = transform_mo_coeff
    transform_single_mo_coeff = transform_single_mo_coeff
    transform_dm = transform_dm
    transform_mo_energy = transform_mo_energy
    transform_mo_occ = transform_mo_occ
    check_mo_occ_symmetry = check_mo_occ_symmetry
    transform_fock = transform_fock
    transform_1e_operator = transform_1e_operator
    dm_at_ref_cell = dm_at_ref_cell
    get_rotation_mat_for_mos = get_rotation_mat_for_mos

class MORotationMatrix:
    kpts: Incomplete
    mo_coeff: Incomplete
    ovlp: Incomplete
    nocc: Incomplete
    nmo: Incomplete
    oo: Incomplete
    vv: Incomplete
    def __init__(self, kpts: KPoints, mo_coeff: ndarray, ovlp: ndarray, nocc: int64, nmo: int64) -> None: ...
    def build(self) -> "MORotationMatrix": ...

class KQuartets:
    kpts: Incomplete
    kqrts_ibz: Incomplete
    weights_ibz: Incomplete
    ibz2bz: Incomplete
    bz2ibz: Incomplete
    stars_ops: Incomplete
    stars_ops_bz: Incomplete
    def __init__(self, kpts: KPoints) -> None: ...
    def build(self) -> "KQuartets": ...
    def cache_stabilizer(self) -> None: ...
    def loop_stabilizer(self, index: int) -> Iterator[Tuple[ndarray, int64]]: ...
