from _typeshed import Incomplete
from collections.abc import Generator
from numpy.linalg import inv as inv
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc.lib import kpts_helper as kpts_helper
from pyscf.pbc.lib.kpts_helper import KPT_DIFF_TOL as KPT_DIFF_TOL, is_zero as is_zero, member as member, round_to_fbz as round_to_fbz
from pyscf.pbc.symm import symmetry as symm
from pyscf.pbc.symm.group import PGElement as PGElement, PointGroup as PointGroup, Representation as Representation

libpbc: Incomplete

def is_gamma_point(kpt_or_kpts): ...
def make_kpts_ibz(kpts, tol=...) -> None: ...
def make_ktuples_ibz(kpts, kpts_scaled=None, ntuple: int = 2, tol=...): ...
def make_k4_ibz(kpts, sym: str = 's1', return_ops: bool = False): ...
def map_k_points_fast(kpts_scaled, ops, tol=...): ...
def map_kpts_tuples(kpts_scaled, ops, ntuple: int = 2, tol=...): ...
def symmetrize_density(kpts, rhoR_k, ibz_k_idx, mesh): ...
def symmetrize_wavefunction(kpts, psiR_k, mesh): ...
def transform_mo_coeff(kpts, mo_coeff_ibz): ...
def transform_mo_coeff_k(kpts, mo_coeff_ibz, k): ...
transform_single_mo_coeff = transform_mo_coeff_k

def transform_mo_occ(kpts, mo_occ_ibz): ...
def transform_dm(kpts, dm_ibz): ...
def dm_at_ref_cell(kpts, dm_ibz): ...
def transform_mo_energy(kpts, mo_energy_ibz): ...
def transform_1e_operator(kpts, fock_ibz): ...
transform_fock = transform_1e_operator

def check_mo_occ_symmetry(kpts, mo_occ, tol: float = 1e-05): ...
def get_rotation_mat_for_mos(kpts, mo_coeff, ovlp, k1, k2, ops_id=None): ...
def make_kpts(cell, kpts=..., space_group_symmetry: bool = False, time_reversal_symmetry: bool = False, **kwargs): ...

class KPoints(symm.Symmetry, lib.StreamObject):
    verbose: Incomplete
    stdout: Incomplete
    time_reversal: bool
    kpts_ibz: Incomplete
    kpts_scaled_ibz: Incomplete
    weights_ibz: Incomplete
    ibz2bz: Incomplete
    k2opk: Incomplete
    stars: Incomplete
    stars_ops: Incomplete
    stars_ops_bz: Incomplete
    time_reversal_symm_bz: Incomplete
    little_cogroup_ops: Incomplete
    def __init__(self, cell=None, kpts=...) -> None: ...
    @property
    def nkpts(self): ...
    @nkpts.setter
    def nkpts(self, n) -> None: ...
    @property
    def nkpts_ibz(self): ...
    @nkpts_ibz.setter
    def nkpts_ibz(self, n) -> None: ...
    def __len__(self) -> int: ...
    def build(self, space_group_symmetry: bool = False, time_reversal_symmetry: bool = False, *args, **kwargs): ...
    cell: Incomplete
    kpts: Incomplete
    def reset(self, cell=None): ...
    def dump_info(self) -> None: ...
    def make_gdf_kptij_lst_jk(self): ...
    def loop_ktuples(self, ibz2bz, ntuple) -> Generator[Incomplete]: ...
    def ktuple_to_index(self, kk): ...
    def index_to_ktuple(self, k, ntuple): ...
    @property
    def addition_table(self, tol=...): ...
    @property
    def inverse_table(self, tol=...): ...
    def get_kconserv(self): ...
    def little_cogroups(self, return_indices: bool = True): ...
    def little_cogroup_rep(self, ki, ir): ...
    make_kpts_ibz = make_kpts_ibz
    make_ktuples_ibz = make_ktuples_ibz
    make_k4_ibz = make_k4_ibz
    symmetrize_density = symmetrize_density
    symmetrize_wavefunction = symmetrize_wavefunction
    transform_mo_coeff = transform_mo_coeff
    transform_single_mo_coeff = transform_single_mo_coeff
    transform_dm = transform_dm
    transform_mo_energy = transform_mo_energy
    transform_mo_occ = transform_mo_occ
    check_mo_occ_symmetry = check_mo_occ_symmetry
    transform_fock = transform_fock
    transform_1e_operator = transform_1e_operator
    dm_at_ref_cell = dm_at_ref_cell
    get_rotation_mat_for_mos = get_rotation_mat_for_mos

class MORotationMatrix:
    kpts: Incomplete
    mo_coeff: Incomplete
    ovlp: Incomplete
    nocc: Incomplete
    nmo: Incomplete
    oo: Incomplete
    vv: Incomplete
    def __init__(self, kpts, mo_coeff, ovlp, nocc, nmo) -> None: ...
    def build(self): ...

class KQuartets:
    kpts: Incomplete
    kqrts_ibz: Incomplete
    weights_ibz: Incomplete
    ibz2bz: Incomplete
    bz2ibz: Incomplete
    stars_ops: Incomplete
    stars_ops_bz: Incomplete
    def __init__(self, kpts) -> None: ...
    def build(self): ...
    def cache_stabilizer(self) -> None: ...
    def loop_stabilizer(self, index) -> Generator[Incomplete, Incomplete]: ...
