import abc
from _typeshed import Incomplete
from numpy.lib.mixins import NDArrayOperatorsMixin
from pyscf import lib as lib

def empty(shape, dtype=..., order: str = 'C', metadata=None): ...
def empty_like(a, *args, **kwargs): ...

class KsymmArray(NDArrayOperatorsMixin, metaclass=abc.ABCMeta):
    metadata: Incomplete
    data: Incomplete
    def __init__(self, subarray_shape, dtype=..., subarray_order: str = 'C', metadata={}, init_with_zeros: bool = False) -> None: ...
    @property
    def shape(self): ...
    @property
    def ndim(self): ...
    @property
    def subarray_ndim(self): ...
    @property
    def subarray_shape(self): ...
    @property
    def subarray_order(self): ...
    @property
    def dtype(self): ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def todense(self): ...
    @staticmethod
    def fromdense(arr, shape, dtype=None, order=None, metadata=None): ...
    @staticmethod
    def fromraw(arr, shape, dtype=None, order=None, metadata=None): ...
    @staticmethod
    def zeros(shape, dtype=..., order: str = 'C', metadata=None): ...

def set_2d(arr, value, kpts, ki) -> None: ...
def set_4d(arr, value, kpts, kqrts, klc) -> None: ...
def transform_2d(arr, kpts, ki, rmat, label, trans): ...
def transform_4d(arr, kpts, kqrts, klc, rmat, label, trans): ...
def index_to_coords(key, shape): ...
def slice_to_coords(k, n): ...

zeros: Incomplete
fromraw: Incomplete
fromdense: Incomplete
