import abc
from _typeshed import Incomplete
from numpy.lib.mixins import NDArrayOperatorsMixin
from pyscf import lib as lib
from dtypes import Complex128DType
from numpy import int32, int64, ndarray
from numpy.dtypes import Complex128DType
from pyscf.pbc.lib.kpts import KPoints, KQuartets, MORotationMatrix
from typing import Dict, List, Optional, Tuple, Union

def empty(shape: Union[Tuple[int64, int64, int64, int64], List[int64], List[int]], dtype: Complex128DType=..., order: str = 'C', metadata: Optional[Dict[str, Union[KPoints, KQuartets, MORotationMatrix, str, bool]]]=None) -> "KsymmArray": ...
def empty_like(a: "KsymmArray", *args, **kwargs) -> "KsymmArray": ...

class KsymmArray(NDArrayOperatorsMixin, metaclass=abc.ABCMeta):
    metadata: Incomplete
    data: Incomplete
    def __init__(self, subarray_shape: Union[Tuple[int64, int64, int64, int64], List[int64], Tuple[int64, int64], List[int]], dtype: Complex128DType=..., subarray_order: str = 'C', metadata: Dict[str, Union[KPoints, KQuartets, MORotationMatrix, str, bool]]={}, init_with_zeros: bool = False) -> None: ...
    @property
    def shape(self) -> Union[Tuple[int, int, int, int64, int64, int64, int64], Tuple[int, int64, int64], Tuple[int, int, int, int, int, int, int]]: ...
    @property
    def ndim(self): ...
    @property
    def subarray_ndim(self) -> int: ...
    @property
    def subarray_shape(self) -> List[Union[int64, int]]: ...
    @property
    def subarray_order(self) -> str: ...
    @property
    def dtype(self) -> Complex128DType: ...
    def __getitem__(self, key: Union[int64, slice, Tuple[int64, int64, int64]]) -> ndarray: ...
    def __setitem__(self, key: Union[Tuple[int32, int64, int64], Tuple[int64, int32, int64], Tuple[int64, int64, int32], int64, Tuple[int64, int64, int64]], value: ndarray) -> None: ...
    def todense(self) -> ndarray: ...
    @staticmethod
    def fromdense(arr, shape, dtype=None, order=None, metadata=None): ...
    @staticmethod
    def fromraw(arr: ndarray, shape: Union[Tuple[int64, int64, int64, int64], Tuple[int64, int64]], dtype: Optional[Complex128DType]=None, order: None=None, metadata: Optional[Dict[str, Union[KPoints, KQuartets, MORotationMatrix, str, bool]]]=None) -> "KsymmArray": ...
    @staticmethod
    def zeros(shape: Tuple[int64, int64], dtype: Complex128DType=..., order: str = 'C', metadata: Optional[Dict[str, Union[KPoints, MORotationMatrix, str, bool]]]=None) -> "KsymmArray": ...

def set_2d(arr: ndarray, value: ndarray, kpts: KPoints, ki: int64) -> None: ...
def set_4d(arr: ndarray, value: ndarray, kpts: KPoints, kqrts: KQuartets, klc: ndarray) -> None: ...
def transform_2d(arr: ndarray, kpts: KPoints, ki: int64, rmat: MORotationMatrix, label: str, trans: str) -> ndarray: ...
def transform_4d(arr: ndarray, kpts: KPoints, kqrts: KQuartets, klc: ndarray, rmat: MORotationMatrix, label: str, trans: str) -> ndarray: ...
def index_to_coords(key: Union[slice, Tuple[int64, int32, int64], Tuple[int64, int64, int32], Tuple[int64, int64, int64], Tuple[int32, int64, int64]], shape: List[int]) -> ndarray: ...
def slice_to_coords(k: slice, n: int) -> ndarray: ...

zeros: Incomplete
fromraw: Incomplete
fromdense: Incomplete
