from _typeshed import Incomplete
from pyscf.lib import logger as logger

method: str
VERBOSE: bool
FOUND_MPI4PY: bool
MPI_RANK: Incomplete
MPI_COMM: Incomplete

def eigs(matvec, size, nroots, x0=None, Adiag=None, guess: bool = False, verbose=...): ...
def davidson(mult_by_A, N, neig, x0=None, Adiag=None, verbose=...): ...
def davidson_guess(mult_by_A, N, neig, Adiag=None): ...
def diagonalize_asymm(H): ...

class Arnoldi:
    matrMultiply: Incomplete
    size: Incomplete
    nEigen: Incomplete
    maxM: Incomplete
    maxOuterLoop: int
    tol: Incomplete
    x0: Incomplete
    iteration: int
    totalIter: int
    converged: bool
    preCon: Incomplete
    def __init__(self, matr_multiply, xStart, inPreCon, nroots: int = 1, tol: float = 1e-10) -> None: ...
    currentSize: Incomplete
    deflated: int
    def solve(self): ...
    subH: Incomplete
    sol: Incomplete
    dgks: Incomplete
    nConv: Incomplete
    eigs: Incomplete
    evecs: Incomplete
    oldeigs: Incomplete
    deigs: Incomplete
    outeigs: Incomplete
    outevecs: Incomplete
    Ax: Incomplete
    res: Incomplete
    vlist: Incomplete
    cv: Incomplete
    cAv: Incomplete
    Avlist: Incomplete
    dres: float
    resnorm: float
    cvEig: float
    ciEig: int
    def allocateVecs(self) -> None: ...
    def guessInitial(self) -> None: ...
    def hMult(self) -> None: ...
    def push_Av(self) -> None: ...
    def constructSubspace(self) -> None: ...
    def solveSubspace(self) -> None: ...
    def constructAllSolV(self) -> None: ...
    def constructSol(self) -> None: ...
    def constructSolV(self) -> None: ...
    def constructSolAv(self) -> None: ...
    def computeResidual(self) -> None: ...
    def updateVecs(self) -> None: ...
    def checkConvergence(self) -> None: ...
    def gramSchmidtCurrentVec(self, northo) -> None: ...
    def checkDeflate(self) -> None: ...
    def constructDeflatedSub(self) -> None: ...

class DavidsonZL:
    maxcycle: int
    crit_e: float
    crit_vec: float
    crit_demo: float
    crit_indp: float
    iprt: int
    ndim: int
    neig: int
    matvec: Incomplete
    v0: Incomplete
    diag: Incomplete
    matrix: Incomplete
    def __init__(self) -> None: ...
    def matvecs(self, vlst): ...
    def genMatrix(self): ...
    def solve_full(self): ...
    def genV0(self): ...
    def solve_iter(self): ...

def svd_cut(mat, thresh): ...
def eigGeneral(Hmat): ...
def realRepresentation(vl, vr, nred): ...
def mgs_ortho(vlst, rlst, crit_indp, iop: int = 0): ...
