from _typeshed import Incomplete
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.lib import logger as logger

IGNORE_H: Incomplete

def orbital_coeff(mol, fout, mo_coeff, spin: str = 'Alpha', symm=None, ene=None, occ=None, ignore_h=...) -> None: ...
def from_mo(mol, filename, mo_coeff, spin: str = 'Alpha', symm=None, ene=None, occ=None, ignore_h=...) -> None: ...
def from_scf(mf, filename, ignore_h=...) -> None: ...
def dump_scf(mf, filename, ignore_h=...) -> None: ...
def from_mcscf(mc, filename, ignore_h=..., cas_natorb: bool = False) -> None: ...
def from_chkfile(filename, chkfile, key: str = 'scf/mo_coeff', ignore_h=...) -> None: ...
def load(moldenfile, verbose: int = 0): ...
parse = load
read = load

def header(mol, fout, ignore_h=...) -> None: ...
def order_ao_index(mol): ...
def remove_high_l(mol, mo_coeff=None): ...
