from _typeshed import Incomplete
from pyscf import __config__ as __config__, gto as gto, lib as lib
from pyscf.lib import logger as logger
from io import TextIOWrapper
from numpy import ndarray
from pyscf.gto.mole import Mole
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.scf.hf_symm import SymAdaptedRHF
from pyscf.scf.uhf import UHF
from pyscf.scf.uhf_symm import SymAdaptedUHF
from typing import Dict, List, Optional, Tuple, Union

IGNORE_H: Incomplete

def orbital_coeff(mol: Mole, fout: TextIOWrapper, mo_coeff: Union[NPArrayWithTag, ndarray], spin: str = 'Alpha', symm: None=None, ene: Optional[ndarray]=None, occ: Optional[ndarray]=None, ignore_h: bool=...) -> None: ...
def from_mo(mol: Mole, filename: str, mo_coeff: NPArrayWithTag, spin: str = 'Alpha', symm: None=None, ene: None=None, occ: None=None, ignore_h: bool=...) -> None: ...
def from_scf(mf, filename, ignore_h=...) -> None: ...
def dump_scf(mf: Union[SymAdaptedUHF, UHF, SymAdaptedRHF], filename: str, ignore_h: bool=...) -> None: ...
def from_mcscf(mc, filename, ignore_h=..., cas_natorb: bool = False) -> None: ...
def from_chkfile(filename, chkfile, key: str = 'scf/mo_coeff', ignore_h=...) -> None: ...
def load(moldenfile: str, verbose: int = 0) -> Union[Tuple[Mole, Tuple[ndarray, ndarray], Tuple[ndarray, ndarray], Tuple[ndarray, ndarray], Tuple[ndarray, ndarray], Tuple[ndarray, ndarray]], Tuple[Mole, ndarray, ndarray, ndarray, List[str], List[str]], Tuple[Mole, None, None, None, None, None]]: ...
parse = load
read = load

def header(mol: Mole, fout: TextIOWrapper, ignore_h: bool=...) -> None: ...
def order_ao_index(mol: Mole) -> List[int]: ...
def remove_high_l(mol: Mole, mo_coeff: Optional[Union[NPArrayWithTag, ndarray]]=None) -> Union[Tuple[Mole, NPArrayWithTag], Tuple[Mole, None], Tuple[Mole, ndarray]]: ...
