from pyscf.lib.parameters import BOHR as BOHR
from numpy import ndarray, str_
from pyscf.dft.uks import UKS
from pyscf.gto.mole import Mole
from typing import Any, Dict, List, Tuple, Union

def load_qcschema_json(file_name: str) -> Dict[str, Any]: ...
def load_qcschema_go_final_json(file_name): ...
def load_qcschema_molecule(qcschema_dict: Dict[str, Any], to_Angstrom: bool = False, xyz: bool = False, mol_select: int = 1, step: int = 0) -> List[Tuple[str_, ndarray]]: ...
def load_qcschema_hessian(qcschema_dict): ...
def load_qcschema_scf_info(qcschema_dict: Dict[str, Any]) -> Dict[str, Union[float, ndarray]]: ...
def recreate_mol_obj(qcschema_dict: Dict[str, Any], to_Angstrom: bool = False) -> Mole: ...
def recreate_scf_obj(qcschema_dict: Dict[str, Any], mol: Mole) -> UKS: ...
