from pyscf.lib.parameters import BOHR as BOHR

def load_qcschema_json(file_name): ...
def load_qcschema_go_final_json(file_name): ...
def load_qcschema_molecule(qcschema_dict, to_Angstrom: bool = False, xyz: bool = False, mol_select: int = 1, step: int = 0): ...
def load_qcschema_hessian(qcschema_dict): ...
def load_qcschema_scf_info(qcschema_dict): ...
def recreate_mol_obj(qcschema_dict, to_Angstrom: bool = False): ...
def recreate_scf_obj(qcschema_dict, mol): ...
