from pyscf import lib as lib
from pyscf.adc import radc as radc, radc_amplitudes as radc_amplitudes, radc_ea as radc_ea, radc_ee as radc_ee, radc_ip as radc_ip, radc_ip_cvs as radc_ip_cvs, uadc as uadc, uadc_amplitudes as uadc_amplitudes, uadc_ea as uadc_ea, uadc_ee as uadc_ee, uadc_ip as uadc_ip, uadc_ip_cvs as uadc_ip_cvs

def ADC(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def UADC(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
def RADC(mf, frozen=None, mo_coeff=None, mo_occ=None): ...
