def get_ovvv_df(myadc, Lov, Lvv, p, chnk_size): ...
def get_ovvv_spin_df(myadc, Lov, Lvv, p, chnk_size): ...
def get_vvvv_df(myadc, Lvv, p, chnk_size): ...
def get_vvvv_antisym_df(myadc, Lvv, p, chnk_size, pack: bool = True): ...
def get_vVvV_df(myadc, Lvv, LVV, p, chnk_size): ...
