from pyscf import lib as lib
from pyscf.lib import logger as logger

def transform_integrals_incore(myadc): ...
def transform_integrals_outcore(myadc): ...
def transform_integrals_df(myadc): ...
def calculate_chunk_size(myadc): ...
def unpack_eri_1(eri, norb): ...
def unpack_eri_2(eri, norb): ...
