from pyscf import lib as lib
from pyscf.adc import dfadc as dfadc, radc_ao2mo as radc_ao2mo
from pyscf.lib import logger as logger

def compute_amplitudes_energy(myadc, eris, verbose=None): ...
def compute_amplitudes(myadc, eris): ...
def compute_energy(myadc, t2, eris): ...
def contract_ladder(myadc, t_amp, vvvv): ...
