from pyscf import scf as scf
from pyscf.adc import dfadc as dfadc, radc_ao2mo as radc_ao2mo, uadc_ao2mo as uadc_ao2mo
from pyscf.lib import logger as logger

def compute_amplitudes_energy(myadc, eris, verbose=None): ...
def compute_amplitudes(myadc, eris): ...
def compute_energy(myadc, t1, t2, eris): ...
def contract_ladder(myadc, t_amp, vvvv_p, prefactor: float = 1.0, pack: bool = False): ...
def contract_ladder_antisym(myadc, t_amp, vvvv_d, pack: bool = True): ...
