from _typeshed import Incomplete
from pyscf import gto as gto, lib as lib, scf as scf
from pyscf.grad import rhf as rhf
from pyscf.lib import logger as logger
from pyscf.scf import cphf as cphf, hf as hf

def hess_elec(hessobj, mo_energy=None, mo_coeff=None, mo_occ=None, mo1=None, mo_e1=None, h1ao=None, atmlst=None, max_memory: int = 4000, verbose=None): ...
def partial_hess_elec(hessobj, mo_energy=None, mo_coeff=None, mo_occ=None, atmlst=None, max_memory: int = 4000, verbose=None): ...
def make_h1(hessobj, mo_coeff, mo_occ, chkfile=None, atmlst=None, verbose=None): ...
def get_hcore(mol): ...
def get_ovlp(mol): ...
def solve_mo1(mf, mo_energy, mo_coeff, mo_occ, h1ao, fx=None, atmlst=None, max_memory: int = 4000, verbose=None, max_cycle: int = 50, level_shift: int = 0): ...
def gen_vind(mf, mo_coeff, mo_occ): ...
def hess_nuc(mol, atmlst=None): ...
def gen_hop(hobj, mo_energy=None, mo_coeff=None, mo_occ=None, verbose=None): ...

class HessianBase(lib.StreamObject):
    max_cycle: int
    level_shift: int
    verbose: Incomplete
    stdout: Incomplete
    mol: Incomplete
    base: Incomplete
    max_memory: Incomplete
    atmlst: Incomplete
    de: Incomplete
    def __init__(self, scf_method) -> None: ...
    def hess_elec(self, *args, **kwargs) -> None: ...
    def make_h1(self, *args, **kwargs) -> None: ...
    def get_hcore(self, mol=None): ...
    def hcore_generator(self, mol=None): ...
    def solve_mo1(self, mo_energy, mo_coeff, mo_occ, h1ao, fx=None, atmlst=None, max_memory: int = 4000, verbose=None): ...
    def hess_nuc(self, mol=None, atmlst=None): ...
    def kernel(self, mo_energy=None, mo_coeff=None, mo_occ=None, atmlst=None): ...
    hess = kernel
    gen_hop = gen_hop
    to_gpu = lib.to_gpu

class Hessian(HessianBase):
    partial_hess_elec = partial_hess_elec
    hess_elec = hess_elec
    make_h1 = make_h1
