from pyscf import lib as lib
from pyscf.data import nist as nist

LINDEP_THRESHOLD: float

def harmonic_analysis(mol, hess, exclude_trans: bool = True, exclude_rot: bool = True, imaginary_freq: bool = True, mass=None): ...
def rotation_const(mass, atom_coords, unit: str = 'GHz'): ...
def thermo(model, freq, temperature: float = 298.15, pressure: int = 101325): ...
def rotational_symmetry_number(mol): ...
def dump_thermo(mol, results): ...
def dump_normal_mode(mol, results): ...
