from pyscf import lib as lib
from pyscf.data import nist as nist
from numpy import float64, ndarray
from pyscf.gto.mole import Mole
from pyscf.scf.hf import RHF
from typing import Dict, Tuple, Union

LINDEP_THRESHOLD: float

def harmonic_analysis(mol: Mole, hess: ndarray, exclude_trans: bool = True, exclude_rot: bool = True, imaginary_freq: bool = True, mass: None=None) -> Dict[str, Union[int, ndarray]]: ...
def rotation_const(mass: ndarray, atom_coords: ndarray, unit: str = 'GHz') -> ndarray: ...
def thermo(model: RHF, freq: ndarray, temperature: float = 298.15, pressure: int = 101325) -> Dict[str, Union[Tuple[float, str], Tuple[int, str], Tuple[float64, str], Tuple[ndarray, str]]]: ...
def rotational_symmetry_number(mol: Mole) -> int: ...
def dump_thermo(mol: Mole, results: Dict[str, Union[Tuple[float, str], Tuple[int, str], Tuple[float64, str], Tuple[ndarray, str]]]): ...
def dump_normal_mode(mol: Mole, results: Dict[str, Union[int, ndarray]]): ...
