from pyscf import lib as lib, scf as scf
from pyscf.grad import uhf as uhf
from pyscf.hessian import rhf as rhf_hess
from pyscf.lib import logger as logger
from pyscf.scf import ucphf as ucphf

def hess_elec(hessobj, mo_energy=None, mo_coeff=None, mo_occ=None, mo1=None, mo_e1=None, h1ao=None, atmlst=None, max_memory: int = 4000, verbose=None): ...
def partial_hess_elec(hessobj, mo_energy=None, mo_coeff=None, mo_occ=None, atmlst=None, max_memory: int = 4000, verbose=None): ...
def make_h1(hessobj, mo_coeff, mo_occ, chkfile=None, atmlst=None, verbose=None): ...
def solve_mo1(mf, mo_energy, mo_coeff, mo_occ, h1ao, fx=None, atmlst=None, max_memory: int = 4000, verbose=None, max_cycle: int = 50, level_shift: int = 0): ...
def gen_vind(mf, mo_coeff, mo_occ): ...
def gen_hop(hobj, mo_energy=None, mo_coeff=None, mo_occ=None, verbose=None): ...

class Hessian(rhf_hess.HessianBase):
    partial_hess_elec = partial_hess_elec
    hess_elec = hess_elec
    make_h1 = make_h1
    gen_hop = gen_hop
    def solve_mo1(self, mo_energy, mo_coeff, mo_occ, h1ao, fx=None, atmlst=None, max_memory: int = 4000, verbose=None): ...
