import abc
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from pyscf import lib as lib
from pyscf.pbc.symm import geom as geom
from pyscf.pbc.symm.tables import SchoenfliesNotation as SchoenfliesNotation

class GroupElement(ABC, metaclass=abc.ABCMeta):
    def __call__(self, other): ...
    @abstractmethod
    def __matmul__(self, other): ...
    def __mul__(self, other): ...
    @abstractmethod
    def __hash__(self): ...
    @abstractmethod
    def inv(self): ...

class PGElement(GroupElement):
    dimension: Incomplete
    def __init__(self, matrix) -> None: ...
    def __matmul__(self, other): ...
    def __hash__(self): ...
    @staticmethod
    def decrypt_hash(h, dimension: int = 3): ...
    def __lt__(self, other): ...
    @property
    def matrix(self): ...
    @matrix.setter
    def matrix(self, a) -> None: ...
    rot = matrix
    def inv(self): ...

class FiniteGroup(ABC, metaclass=abc.ABCMeta):
    elements: Incomplete
    def __init__(self, elements, from_hash: bool = False) -> None: ...
    @staticmethod
    @abstractmethod
    def elements_from_hash(hashes, **kwargs): ...
    def __len__(self) -> int: ...
    def __getitem__(self, i): ...
    def __and__(self, other): ...
    def __or__(self, other): ...
    def issubset(self, other): ...
    @property
    def order(self): ...
    @order.setter
    def order(self, n) -> None: ...
    @property
    def hash_table(self): ...
    @hash_table.setter
    def hash_table(self, table) -> None: ...
    @property
    def inverse_table(self): ...
    @inverse_table.setter
    def inverse_table(self, table) -> None: ...
    @property
    def multiplication_table(self): ...
    @multiplication_table.setter
    def multiplication_table(self, table) -> None: ...
    @property
    def conjugacy_table(self): ...
    @conjugacy_table.setter
    def conjugacy_table(self, table) -> None: ...
    @property
    def conjugacy_mask(self): ...
    def conjugacy_classes(self): ...
    def character_table(self, return_full_table: bool = False, recompute: bool = False): ...
    def project_chi(self, chi, other): ...
    def get_elements_map(self, other): ...
    def get_irrep_chi(self, ir): ...

class PointGroup(FiniteGroup):
    def group_name(self, notation: str = 'international'): ...
    @property
    def group_index(self): ...
    @staticmethod
    def elements_from_hash(hashes, dimension: int = 3): ...

class Representation:
    group: Incomplete
    def __init__(self, group, rep=None, chi=None) -> None: ...
    @property
    def rep(self): ...
    @rep.setter
    def rep(self, value) -> None: ...
    @property
    def chi(self): ...
    @chi.setter
    def chi(self, value) -> None: ...
    def rep_to_chi(self, rep): ...
    def chi_to_rep(self, chi): ...
    def __matmul__(self, other): ...
