from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc.symm import geom as geom
from pyscf.pbc.symm.group import PGElement as PGElement

SYMPREC: Incomplete
XYZ: Incomplete

def transform_rot(op, a, b, allow_non_integer: bool = False): ...
def transform_trans(op, a, b): ...

class SPGElement:
    rot: Incomplete
    trans: Incomplete
    dimension: Incomplete
    def __init__(self, rot=..., trans=..., dimension: int = 3) -> None: ...
    def dot(self, r_or_op): ...
    def dot_rot(self, r): ...
    def inv(self): ...
    def transform(self, a, b, allow_non_integer: bool = False): ...
    @property
    def rot_is_eye(self): ...
    @property
    def rot_is_inversion(self): ...
    @property
    def trans_is_zero(self): ...
    @property
    def is_eye(self): ...
    @property
    def is_inversion(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...
    def __hash__(self): ...
    def a2b(self, cell): ...
    def a2r(self, cell): ...
    def b2a(self, cell): ...
    def b2r(self, cell): ...
    def r2a(self, cell): ...
    def r2b(self, cell): ...

class SpaceGroup(lib.StreamObject):
    cell: Incomplete
    symprec: Incomplete
    verbose: Incomplete
    stdout: Incomplete
    backend: str
    ops: Incomplete
    nop: int
    groupname: Incomplete
    def __init__(self, cell, symprec=...) -> None: ...
    def build(self, dump_info: bool = True): ...
    def dump_info(self, ops=None) -> None: ...
