from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc.symm import geom as geom
from pyscf.pbc.symm.group import PGElement as PGElement
from numpy import bool, ndarray
from pyscf.pbc.df.ft_ao import _RangeSeparatedCell
from pyscf.pbc.gto.cell import Cell
from typing import List, Optional, Union

SYMPREC: Incomplete
XYZ: Incomplete

def transform_rot(op: ndarray, a: ndarray, b: ndarray, allow_non_integer: bool = False) -> ndarray: ...
def transform_trans(op: ndarray, a: ndarray, b: ndarray) -> ndarray: ...

class SPGElement:
    rot: Incomplete
    trans: Incomplete
    dimension: Incomplete
    def __init__(self, rot: ndarray=..., trans: ndarray=..., dimension: int = 3) -> None: ...
    def dot(self, r_or_op): ...
    def dot_rot(self, r: ndarray) -> ndarray: ...
    def inv(self) -> "SPGElement": ...
    def transform(self, a: ndarray, b: ndarray, allow_non_integer: bool = False) -> "SPGElement": ...
    @property
    def rot_is_eye(self) -> bool: ...
    @property
    def rot_is_inversion(self) -> bool: ...
    @property
    def trans_is_zero(self) -> bool: ...
    @property
    def is_eye(self) -> bool: ...
    @property
    def is_inversion(self): ...
    def __eq__(self, other: "SPGElement") -> bool: ...
    def __ne__(self, other): ...
    def __lt__(self, other: "SPGElement") -> bool: ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...
    def __hash__(self) -> int: ...
    def a2b(self, cell: Cell) -> "SPGElement": ...
    def a2r(self, cell: Union[_RangeSeparatedCell, Cell]) -> "SPGElement": ...
    def b2a(self, cell): ...
    def b2r(self, cell): ...
    def r2a(self, cell): ...
    def r2b(self, cell): ...

class SpaceGroup(lib.StreamObject):
    cell: Incomplete
    symprec: Incomplete
    verbose: Incomplete
    stdout: Incomplete
    backend: str
    ops: Incomplete
    nop: int
    groupname: Incomplete
    def __init__(self, cell: Union[_RangeSeparatedCell, Cell], symprec: float=...) -> None: ...
    def build(self, dump_info: bool = True) -> "SpaceGroup": ...
    def dump_info(self, ops: Optional[List[SPGElement]]=None) -> None: ...
