from _typeshed import Incomplete
from numpy.linalg import inv as inv
from pyscf import lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc.symm import space_group as space_group
from pyscf.pbc.symm.space_group import SPGElement, SYMPREC as SYMPREC, XYZ as XYZ
from pyscf.symm import param as param
from pyscf.symm.Dmatrix import Dmatrix as Dmatrix, get_euler_angles as get_euler_angles
from numpy import int32, ndarray
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.pbc.df.ft_ao import _RangeSeparatedCell
from pyscf.pbc.gto.cell import Cell
from pyscf.pbc.lib.kpts import KPoints
from typing import Any, List, Optional, Tuple, Union

def get_Dmat(op: ndarray, l: int) -> ndarray: ...
def get_Dmat_cart(op, l_max): ...
def make_Dmats(cell: Union[Cell, _RangeSeparatedCell], ops: List[ndarray], l_max: None=None) -> Tuple[List[List[ndarray]], int32]: ...
def check_mesh_symmetry(cell: Union[Cell, _RangeSeparatedCell], ops: List[SPGElement], mesh: Optional[ndarray]=None, tol: float=..., return_mesh: bool = False) -> Union[Tuple[List[int], ndarray], Tuple[List[Any], ndarray], List[int]]: ...

class Symmetry:
    cell: Incomplete
    spacegroup: Incomplete
    symmorphic: bool
    ops: Incomplete
    nop: Incomplete
    has_inversion: bool
    Dmats: Incomplete
    l_max: Incomplete
    def __init__(self, cell: Optional[Union[Cell, _RangeSeparatedCell]]) -> None: ...
    def build(self, space_group_symmetry: bool = True, symmorphic: bool = True, check_mesh_symmetry: bool = True, *args, **kwargs) -> Union[Symmetry, KPoints]: ...
    def check_mesh_symmetry(self, cell: Optional[Union[Cell, _RangeSeparatedCell]]=None, ops: Optional[List[SPGElement]]=None, mesh: Optional[ndarray]=None, tol: float=..., return_mesh: bool = False) -> Union[Tuple[List[int], ndarray], Tuple[List[Any], ndarray], List[int]]: ...
    def dump_info(self) -> None: ...
    def reset(self, cell=None): ...

def transform_mo_coeff(cell: Cell, kpt_scaled: ndarray, mo_coeff: Union[ndarray, NPArrayWithTag], op: SPGElement, Dmats: List[ndarray]) -> ndarray: ...
def transform_dm(cell: Cell, kpt_scaled: ndarray, dm: Union[ndarray, NPArrayWithTag], op: SPGElement, Dmats: List[ndarray]) -> ndarray: ...
def transform_1e_operator(cell: Cell, kpt_scaled: ndarray, fock: ndarray, op: SPGElement, Dmats: List[ndarray]) -> ndarray: ...
def make_rot_loc(l_max, key): ...
def is_eye(op) -> None: ...
def is_inversion(op) -> None: ...
