from _typeshed import Incomplete
from numpy.linalg import inv as inv
from pyscf import lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc.symm import space_group as space_group
from pyscf.pbc.symm.space_group import SYMPREC as SYMPREC, XYZ as XYZ
from pyscf.symm import param as param
from pyscf.symm.Dmatrix import Dmatrix as Dmatrix, get_euler_angles as get_euler_angles

def get_Dmat(op, l): ...
def get_Dmat_cart(op, l_max): ...
def make_Dmats(cell, ops, l_max=None): ...
def check_mesh_symmetry(cell, ops, mesh=None, tol=..., return_mesh: bool = False): ...

class Symmetry:
    cell: Incomplete
    spacegroup: Incomplete
    symmorphic: bool
    ops: Incomplete
    nop: Incomplete
    has_inversion: bool
    Dmats: Incomplete
    l_max: Incomplete
    def __init__(self, cell) -> None: ...
    def build(self, space_group_symmetry: bool = True, symmorphic: bool = True, check_mesh_symmetry: bool = True, *args, **kwargs): ...
    def check_mesh_symmetry(self, cell=None, ops=None, mesh=None, tol=..., return_mesh: bool = False): ...
    def dump_info(self) -> None: ...
    def reset(self, cell=None): ...

def transform_mo_coeff(cell, kpt_scaled, mo_coeff, op, Dmats): ...
def transform_dm(cell, kpt_scaled, dm, op, Dmats): ...
def transform_1e_operator(cell, kpt_scaled, fock, op, Dmats): ...
def make_rot_loc(l_max, key): ...
def is_eye(op) -> None: ...
def is_inversion(op) -> None: ...
