from _typeshed import Incomplete

H: Incomplete
He: Incomplete
Li: Incomplete
Be: Incomplete
B: Incomplete
C: Incomplete
N: Incomplete
O: Incomplete
F: Incomplete
Ne: Incomplete
Na: Incomplete
Mg: Incomplete
Al: Incomplete
Si: Incomplete
P: Incomplete
S: Incomplete
Cl: Incomplete
Ar: Incomplete
K: Incomplete
Ca: Incomplete
Sc: Incomplete
Ti: Incomplete
V: Incomplete
Cr: Incomplete
Mn: Incomplete
Fe: Incomplete
Co: Incomplete
Ni: Incomplete
Cu: Incomplete
Zn: Incomplete
Ga: Incomplete
Ge: Incomplete
As: Incomplete
Se: Incomplete
Br: Incomplete
Kr: Incomplete
Rb: Incomplete
Sr: Incomplete
Y: Incomplete
Zr: Incomplete
Nb: Incomplete
Mo: Incomplete
Tc: Incomplete
Ru: Incomplete
Rh: Incomplete
Pd: Incomplete
Ag: Incomplete
Cd: Incomplete
In: Incomplete
Sn: Incomplete
Sb: Incomplete
Te: Incomplete
I: Incomplete
Xe: Incomplete
Cs: Incomplete
Ba: Incomplete
La: Incomplete
Ce: Incomplete
Pr: Incomplete
Nd: Incomplete
Pm: Incomplete
Sm: Incomplete
Eu: Incomplete
Gd: Incomplete
Tb: Incomplete
Dy: Incomplete
Ho: Incomplete
Er: Incomplete
Tm: Incomplete
Yb: Incomplete
Lu: Incomplete
Hf: Incomplete
Ta: Incomplete
W: Incomplete
Re: Incomplete
Os: Incomplete
Ir: Incomplete
Pt: Incomplete
Au: Incomplete
Hg: Incomplete
Tl: Incomplete
Pb: Incomplete
Bi: Incomplete
Po: Incomplete
At: Incomplete
Rn: Incomplete
Fr: Incomplete
Ra: Incomplete
Ac: Incomplete
Th: Incomplete
Pa: Incomplete
U: Incomplete
Np: Incomplete
Pu: Incomplete
Am: Incomplete
Cm: Incomplete
Bk: Incomplete
Cf: Incomplete
Es: Incomplete
Fm: Incomplete
Md: Incomplete
No: Incomplete
Lr: Incomplete
Rf: Incomplete
Db: Incomplete
Sg: Incomplete
Bh: Incomplete
Hs: Incomplete
Mt: Incomplete
Ds: Incomplete
Rg: Incomplete
Cn: Incomplete
Nh: Incomplete
Fl: Incomplete
Mc: Incomplete
Lv: Incomplete
Ts: Incomplete
Og: Incomplete
