from _typeshed import Incomplete

H: Incomplete
He: Incomplete
B: Incomplete
C: Incomplete
N: Incomplete
O: Incomplete
F: Incomplete
Ne: Incomplete
Al: Incomplete
Si: Incomplete
P: Incomplete
S: Incomplete
Cl: Incomplete
Ar: Incomplete
Ga: Incomplete
Ge: Incomplete
As: Incomplete
Se: Incomplete
Br: Incomplete
Kr: Incomplete
In: Incomplete
Sn: Incomplete
Sb: Incomplete
Te: Incomplete
I: Incomplete
Xe: Incomplete
Tl: Incomplete
Pb: Incomplete
Bi: Incomplete
Po: Incomplete
At: Incomplete
Rn: Incomplete
Nh: Incomplete
Fl: Incomplete
Mc: Incomplete
Lv: Incomplete
Ts: Incomplete
Og: Incomplete
