from _typeshed import Incomplete
from pyscf import dmrgscf as dmrgscf, lib as lib
from pyscf.mcscf.addons import StateAverageFCISolver as StateAverageFCISolver, StateAverageMixFCISolver as StateAverageMixFCISolver

DMRGCI: Incomplete

class DMRGCI: ...

def make_one_casdm1s(mc, ci, state: int = 0): ...
def make_one_casdm2(mc, ci, state: int = 0): ...
def dm2_cumulant(dm2, dm1s): ...
def dm2s_cumulant(dm2s, dm1s): ...
def casdm1s_to_dm1s(mc, casdm1s, mo_coeff=None, ncore=None, ncas=None): ...
def make_weighted_casdm1s(mc, ci=None, weights=None): ...
def make_weighted_casdm2(mc, ci=None, weights=None): ...
