from _typeshed import Incomplete
from pyscf import dmrgscf as dmrgscf, lib as lib
from pyscf.mcscf.addons import StateAverageFCISolver as StateAverageFCISolver, StateAverageMixFCISolver as StateAverageMixFCISolver
from numpy import ndarray
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.mcpdft.otfnal import ftransfnal, transfnal
from typing import Optional, Tuple, Union

DMRGCI: Incomplete

class DMRGCI: ...

def make_one_casdm1s(mc, ci, state: int = 0): ...
def make_one_casdm2(mc, ci, state: int = 0): ...
def dm2_cumulant(dm2: ndarray, dm1s: Tuple[ndarray, ndarray]) -> ndarray: ...
def dm2s_cumulant(dm2s, dm1s): ...
def casdm1s_to_dm1s(mc: Union[ftransfnal, transfnal], casdm1s: Tuple[ndarray, ndarray], mo_coeff: Optional[Union[ndarray, NPArrayWithTag]]=None, ncore: Optional[int]=None, ncas: Optional[int]=None) -> NPArrayWithTag: ...
def make_weighted_casdm1s(mc, ci=None, weights=None): ...
def make_weighted_casdm2(mc, ci=None, weights=None): ...
