from _typeshed import Incomplete
from pyscf import lib as lib
from pyscf.dft.libxc import XC_ALIAS as XC_ALIAS, XC_CODES as XC_CODES, XC_KEYS as XC_KEYS, hybrid_coeff as hybrid_coeff, rsh_coeff as rsh_coeff

XC_ALIAS_KEYS: Incomplete
XC_TYPE_HDR: Incomplete
INTCODES_TYPES: Incomplete
INTCODES_HYB: Incomplete
mykey = key
words: Incomplete

class XCSplitError(RuntimeError):
    path: Incomplete
    def __init__(self, xc) -> None: ...
    def extend(self, xc) -> None: ...
    message: Incomplete
    def __call__(self, message): ...

def split_x_c_comma(xc): ...
def is_hybrid_or_rsh(xc_code): ...
def is_hybrid_xc(xc_code): ...
def parse_xc_formula(xc_code): ...
def assemble_xc_formula(facs, terms): ...
