from _typeshed import Incomplete
from pyscf import lib as lib
from pyscf.dft.libxc import XC_ALIAS as XC_ALIAS, XC_CODES as XC_CODES, XC_KEYS as XC_KEYS, hybrid_coeff as hybrid_coeff, rsh_coeff as rsh_coeff
from numpy import float64
from typing import Any, List, Tuple, Union

XC_ALIAS_KEYS: Incomplete
XC_TYPE_HDR: Incomplete
INTCODES_TYPES: Incomplete
INTCODES_HYB: Incomplete
mykey = key
words: Incomplete

class XCSplitError(RuntimeError):
    path: Incomplete
    def __init__(self, xc: str) -> None: ...
    def extend(self, xc: str) -> None: ...
    message: Incomplete
    def __call__(self, message): ...

def split_x_c_comma(xc: str) -> List[str]: ...
def is_hybrid_or_rsh(xc_code: str) -> bool: ...
def is_hybrid_xc(xc_code: str) -> bool: ...
def parse_xc_formula(xc_code: str) -> Union[Tuple[List[int], List[str]], Tuple[List[Any], List[Any]], Tuple[List[float], List[str]]]: ...
def assemble_xc_formula(facs: List[Union[float, float64]], terms: List[str]) -> str: ...
