from _typeshed import Incomplete
from pyscf import __config__ as __config__, mcpdft as mcpdft
from pyscf.fci import direct_spin1 as direct_spin1
from pyscf.lib import logger as logger
from pyscf.mcpdft import chkfile as chkfile

def weighted_average_densities(mc, ci=None, weights=None): ...
def get_lpdft_hconst(mc, E_ot, casdm1s_0, casdm2_0, hyb: float = 1.0, ncas=None, ncore=None, veff1=None, veff2=None, mo_coeff=None): ...
def transformed_h1e_for_cas(mc, E_ot, casdm1s_0, casdm2_0, hyb: float = 1.0, mo_coeff=None, ncas=None, ncore=None): ...
def get_transformed_h2eff_for_cas(mc, ncore=None, ncas=None): ...
def make_lpdft_ham_(mc, mo_coeff=None, ci=None, ot=None): ...
def kernel(mc, mo_coeff=None, ci0=None, ot=None, dump_chk: bool = True, **kwargs): ...

class _LPDFT(mcpdft.MultiStateMCPDFTSolver):
    lpdft_ham: Incomplete
    si_pdft: Incomplete
    veff1: Incomplete
    veff2: Incomplete
    def __init__(self, mc) -> None: ...
    @property
    def e_states(self): ...
    @e_states.setter
    def e_states(self, x) -> None: ...
    make_lpdft_ham_ = make_lpdft_ham_
    get_lpdft_hconst = get_lpdft_hconst
    get_h1lpdft = transformed_h1e_for_cas
    get_h2lpdft = get_transformed_h2eff_for_cas
    get_casdm12_0 = weighted_average_densities
    def get_lpdft_diag(self): ...
    def get_lpdft_ham(self): ...
    mo_coeff: Incomplete
    def kernel(self, mo_coeff=None, ci0=None, ot=None, verbose=None, dump_chk: bool = True): ...
    def get_lpdft_hcore_only(self, casdm1s_0, hyb: float = 1.0, mo_coeff=None, ncore=None, ncas=None): ...
    def get_lpdft_hcore(self, casdm1s_0=None, mo_coeff=None, ncore=None, ncas=None): ...
    def nuc_grad_method(self, state=None): ...
    def dump_chk(self, envs): ...

class _LPDFTMix(_LPDFT):
    def __init__(self, mc) -> None: ...
    def get_lpdft_diag(self): ...
    def get_lpdft_ham(self): ...
    def nuc_grad_method(self, state=None) -> None: ...

def linear_multi_state(mc, weights=(0.5, 0.5), **kwargs): ...
def linear_multi_state_mix(mc, fcisolvers, weights=(0.5, 0.5), **kwargs): ...
