import types
from _typeshed import Incomplete
from pyscf import __config__ as __config__, ao2mo as ao2mo, fci as fci, lib as lib, mcscf as mcscf
from pyscf.dft import gen_grid as gen_grid
from pyscf.lib import logger as logger
from pyscf.mcpdft import chkfile as chkfile, pdft_feff as pdft_feff, pdft_veff as pdft_veff
from pyscf.mcpdft.otfnal import get_transfnal as get_transfnal, transfnal as transfnal
from pyscf.mcscf import mc1step as mc1step
from pyscf.mcscf.addons import StateAverageMCSCFSolver as StateAverageMCSCFSolver, StateAverageMixFCISolver as StateAverageMixFCISolver

def energy_tot(mc, mo_coeff=None, ci=None, ot=None, state: int = 0, verbose=None): ...
kernel = energy_tot

def energy_elec(mc, *args, **kwargs): ...
def energy_mcwfn(mc, mo_coeff=None, ci=None, ot=None, state: int = 0, casdm1s=None, casdm2=None, verbose=None): ...
def energy_dft(mc, mo_coeff=None, ci=None, ot=None, state: int = 0, casdm1s=None, casdm2=None, max_memory=None, hermi: int = 1): ...
def get_energy_decomposition(mc, mo_coeff=None, ci=None, ot=None, otxc=None, grids_level=None, grids_attr=None, split_x_c=None, verbose=None): ...

class _mcscf_env:
    mc: Incomplete
    e_tot: Incomplete
    e_states: Incomplete
    def __init__(self, mc) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...

class _PDFT:
    max_cycle_fp: Incomplete
    conv_tol_ci_fp: Incomplete
    mcscf_kernel: Incomplete
    chkfile: Incomplete
    def __init__(self, scf, ncas, nelecas, my_ot=None, grids_level=None, grids_attr=None, **kwargs) -> None: ...
    def get_rhf_base(self): ...
    @property
    def grids(self): ...
    @grids.setter
    def grids(self, x): ...
    def optimize_mcscf_(self, mo_coeff=None, ci0=None, **kwargs): ...
    mo_coeff: Incomplete
    ci: Incomplete
    otfnal: Incomplete
    verbose: Incomplete
    e_ot: Incomplete
    e_states: Incomplete
    e_tot: Incomplete
    def compute_pdft_energy_(self, mo_coeff=None, ci=None, ot=None, otxc=None, grids_level=None, grids_attr=None, dump_chk: bool = True, verbose=None, **kwargs): ...
    def kernel(self, mo_coeff=None, ci0=None, otxc=None, grids_attr=None, grids_level=None, **kwargs): ...
    def dump_flags(self, verbose=None) -> None: ...
    def get_pdft_veff(self, mo=None, ci=None, state: int = 0, casdm1s=None, casdm2=None, incl_coul: bool = False, paaa_only: bool = False, aaaa_only: bool = False, jk_pc: bool = False, drop_mcwfn: bool = False, incl_energy: bool = False, ot=None): ...
    def get_pdft_feff(self, mo=None, ci=None, state: int = 0, casdm1s=None, casdm2=None, c_dm1s=None, c_cascm2=None, paaa_only: bool = False, aaaa_only: bool = False, jk_pc: bool = False, incl_coul: bool = False, delta: bool = False): ...
    def nuc_grad_method(self): ...
    Gradients = nuc_grad_method
    def dip_moment(self, unit: str = 'Debye', origin: str = 'Coord_Center', state: int = 0): ...
    def get_energy_decomposition(self, mo_coeff=None, ci=None, ot=None, otxc=None, grids_level=None, grids_attr=None, split_x_c=None, verbose=None): ...
    def multi_state_mix(self, fcisolvers=None, weights=(0.5, 0.5), method: str = 'LIN'): ...
    def multi_state(self, weights=(0.5, 0.5), method: str = 'LIN'): ...
    def state_interaction(self, weights=(0.5, 0.5), diabatization: str = 'CMS'): ...
    @property
    def otxc(self): ...
    @otxc.setter
    def otxc(self, x) -> None: ...
    make_one_casdm1s: Incomplete
    make_one_casdm2: Incomplete
    energy_mcwfn = energy_mcwfn
    energy_dft = energy_dft
    def energy_tot(self, mo_coeff=None, ci=None, ot=None, state: int = 0, verbose=None, otxc=None, grids_level=None, grids_attr=None, logger_tag: str = 'MC-PDFT'): ...
    def dump_chk(self, envs): ...
    def update_from_chk(self, chkfile=None, pdft_key: str = 'pdft'): ...
    update = update_from_chk

def get_mcpdft_child_class(mc, ot, **kwargs): ...
