from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib, mcpdft as mcpdft
from pyscf.fci import direct_spin1 as direct_spin1
from pyscf.mcscf import mc1step as mc1step
from pyscf.mcscf.addons import StateAverageMCSCFSolver as StateAverageMCSCFSolver, StateAverageMixFCISolver as StateAverageMixFCISolver
from typing import Callable, Tuple

MAX_CYC_DIABATIZE: Incomplete
CONV_TOL_DIABATIZE: Incomplete
SING_TOL_DIABATIZE: Incomplete
NUDGE_TOL_DIABATIZE: Incomplete

def make_heff_mcscf(mc, mo_coeff=None, ci=None): ...
def si_newton(mc, ci=None, objfn=None, max_cyc=None, conv_tol=None, sing_tol=None, nudge_tol=None): ...

class _MSPDFT(mcpdft.MultiStateMCPDFTSolver):
    max_cyc_diabatize: Incomplete
    conv_tol_diabatize: Incomplete
    sing_tol_diabatize: Incomplete
    nudge_tol_diabatize: Incomplete
    diabatization: Incomplete
    si_mcscf: Incomplete
    si_pdft: Incomplete
    def __init__(self, mc, diabatizer, diabatize, diabatization) -> None: ...
    @property
    def e_states(self): ...
    @e_states.setter
    def e_states(self, x) -> None: ...
    @property
    def si(self): ...
    @si.setter
    def si(self, x) -> None: ...
    def get_heff_offdiag(self): ...
    def get_heff_pdft(self): ...
    def get_ci_adiabats(self, ci=None, uci: str = 'MSPDFT'): ...
    get_ci_basis = get_ci_adiabats
    converged: Incomplete
    heff_mcscf: Incomplete
    hdiag_pdft: Incomplete
    e_tot: Incomplete
    def kernel(self, mo_coeff=None, ci0=None, otxc=None, grids_level=None, grids_attr=None, **kwargs): ...
    def optimize_mcscf_(self, mo_coeff=None, ci0=None, **kwargs): ...
    def diabatize(self, ci=None, ci0=None, **kwargs): ...
    def diabatizer(self, mo_coeff=None, ci=None): ...
    make_heff_mcscf = make_heff_mcscf
    def nuc_grad_method(self): ...
    def nac_method(self): ...
    def dip_moment(self, unit: str = 'Debye', origin: str = 'Coord_Center', state=None): ...
    def trans_moment(self, unit: str = 'Debye', origin: str = 'Coord_Center', state=None): ...

def get_diabfns(obj: str) -> Tuple[Callable, Callable]: ...
def multi_state(mc, weights=(0.5, 0.5), diabatization: str = 'CMS', **kwargs): ...
