from _typeshed import Incomplete
from pyscf import __config__ as __config__, dft as dft, lib as lib
from pyscf.dft import libxc as libxc
from pyscf.dft.gen_grid import Grids as Grids
from pyscf.dft.numint import NumInt, NumInt as NumInt
from pyscf.lib import logger as logger
from pyscf.mcpdft import pdft_eff as pdft_eff, pdft_feff as pdft_feff, pdft_veff as pdft_veff, tfnal_derivs as tfnal_derivs
from pyscf.mcpdft.otpd import get_ontop_pair_density as get_ontop_pair_density
from numpy import float64, ndarray
from pyscf.dft.rks import RKS
from pyscf.dft.rks_symm import SymAdaptedRKS, SymAdaptedROKS
from pyscf.dft.roks import ROKS
from pyscf.gto.mole import Mole
from pyscf.lib.numpy_helper import NPArrayWithTag
from typing import Dict, List, Optional, Tuple, Union

FT_R0: Incomplete
FT_R1: Incomplete
FT_A: Incomplete
FT_B: Incomplete
FT_C: Incomplete
OT_ALIAS: Incomplete
OT_HYB_ALIAS: Incomplete
REG_OT_FUNCTIONALS: Incomplete
OT_PRESET: Incomplete

def register_otfnal(xc_code: str, preset: Dict[str, Union[str, Dict[int, ndarray], Tuple[float, float, int], Tuple[float, float]]]) -> None: ...
def unregister_otfnal(xc_code: str) -> None: ...
def energy_ot(ot: Union[transfnal, ftransfnal], casdm1s: Tuple[ndarray, ndarray], casdm2: ndarray, mo_coeff: Union[ndarray, NPArrayWithTag], ncore: int, max_memory: int = 2000, hermi: int = 1) -> Union[float, float64]: ...

class otfnal:
    mol: Incomplete
    verbose: Incomplete
    stdout: Incomplete
    def __init__(self, mol: Mole) -> None: ...
    Pi_deriv: int
    @property
    def xctype(self) -> str: ...
    @property
    def dens_deriv(self) -> int: ...
    def eval_ot(self, rho, Pi, dderiv: int = 0, **kwargs) -> None: ...
    energy_ot = energy_ot
    get_eff_1body = pdft_eff.get_eff_1body
    get_eff_2body = pdft_eff.get_eff_2body
    get_eff_2body_kl = pdft_eff.get_eff_2body_kl
    get_veff_1body = pdft_veff.get_veff_1body
    get_veff_2body = pdft_veff.get_veff_2body
    get_veff_2body_kl = pdft_veff.get_veff_2body_kl
    get_feff_1body = pdft_feff.get_feff_1body
    get_feff_2body = pdft_feff.get_feff_2body
    def reset(self, mol: Optional[Mole]=None) -> None: ...

class transfnal(otfnal):
    __doc__: Incomplete
    transl_prefix: str
    otxc: Incomplete
    grids: Incomplete
    def __init__(self, ks: Union[SymAdaptedRKS, ROKS, RKS, SymAdaptedROKS], **kwargs) -> None: ...
    def get_ratio(self, Pi: ndarray, rho_avg: ndarray) -> ndarray: ...
    def get_rho_translated(self, Pi: ndarray, rho: ndarray, _fn_deriv: int = 0) -> Union[ndarray, Tuple[ndarray, ndarray, ndarray]]: ...
    def get_zeta(self, R: ndarray, fn_deriv: int = 0, _Rmax: Union[float, int] = 1) -> ndarray: ...
    def split_x_c(self) -> Tuple[transfnal, transfnal]: ...
    def jT_op(self, x: Union[ndarray, List[ndarray]], rho: ndarray, Pi: ndarray) -> ndarray: ...
    def d_jT_op(self, x: List[ndarray], rho: ndarray, Pi: ndarray) -> ndarray: ...
    def eval_ot(self, rho: ndarray, Pi: ndarray, dderiv: int = 1, weights: Optional[ndarray]=None, _unpack_vot: bool = True) -> Union[Tuple[ndarray, Tuple[ndarray, ndarray], None], Tuple[ndarray, ndarray, ndarray], Tuple[ndarray, None, None]]: ...

class ftransfnal(transfnal):
    __doc__: Incomplete
    transl_prefix: str
    R0: Incomplete
    R1: Incomplete
    A: Incomplete
    B: Incomplete
    C: Incomplete
    otxc: Incomplete
    grids: Incomplete
    def __init__(self, ks: Union[SymAdaptedRKS, RKS, SymAdaptedROKS], **kwargs) -> None: ...
    Pi_deriv: Incomplete
    def get_rho_translated(self, Pi: ndarray, rho: ndarray) -> ndarray: ...
    def get_zeta(self, R: ndarray, fn_deriv: int = 1) -> ndarray: ...
    def jT_op(self, x: Union[ndarray, List[ndarray]], rho: ndarray, Pi: ndarray, **kwargs) -> ndarray: ...
    def d_jT_op(self, x: List[ndarray], rho: ndarray, Pi: ndarray, **kwargs) -> ndarray: ...

def get_transfnal(mol: Mole, otxc: str) -> Union[transfnal, ftransfnal]: ...

class colle_salvetti_corr(otfnal):
    otxc: str
    grids: Incomplete
    CS_a: Incomplete
    CS_b: Incomplete
    CS_c: Incomplete
    CS_d: Incomplete
    def __init__(self, mol, **kwargs) -> None: ...
    def get_E_ot(self, rho, Pi, weights): ...

def make_scaled_fnal(xc_code: str, hyb_x: float = 0, hyb_c: float = 0, fnal_x: Optional[float]=None, fnal_c: Optional[float]=None) -> str: ...
def make_hybrid_fnal(xc_code: str, hyb: float, hyb_type: Union[int, str] = 1) -> str: ...

__t_doc__: str
__ft_doc__: str

def t_hybrid_coeff(ni: NumInt, xc_code: str, spin: int = 0) -> List[Union[float, int]]: ...
def t_nlc_coeff(ni, xc_code): ...
def t_rsh_coeff(ni: NumInt, xc_code: str) -> Union[Tuple[int, int, float], Tuple[int, float, float], Tuple[float, float, float]]: ...
def t_eval_xc(ni: NumInt, xc_code: str, rho: Tuple[ndarray, ndarray], spin: int = 0, relativity: int = 0, deriv: int = 1, verbose: Optional[int]=None) -> Union[Tuple[ndarray, List[ndarray], None, None], Tuple[ndarray, List[ndarray], List[ndarray], None], Tuple[ndarray, List[Optional[ndarray]], None, None], Tuple[ndarray, None, None, None]]: ...
def t_xc_type(ni: NumInt, xc_code: str) -> str: ...
def t_rsh_and_hybrid_coeff(ni, xc_code, spin: int = 0): ...
def ft_hybrid_coeff(ni: NumInt, xc_code: str, spin: int = 0) -> List[int]: ...
def ft_nlc_coeff(ni, xc_code): ...
def ft_rsh_coeff(ni: NumInt, xc_code: str) -> Tuple[float, float, float]: ...
def ft_eval_xc(ni: NumInt, xc_code: str, rho: Tuple[ndarray, ndarray], spin: int = 0, relativity: int = 0, deriv: int = 1, verbose: Optional[int]=None) -> Union[Tuple[ndarray, List[ndarray], List[ndarray], None], Tuple[ndarray, List[ndarray], None, None], Tuple[ndarray, None, None, None]]: ...
def ft_xc_type(ni: NumInt, xc_code: str) -> str: ...
def ft_rsh_and_hybrid_coeff(ni, xc_code, spin: int = 0): ...
