from _typeshed import Incomplete
from pyscf import __config__ as __config__, dft as dft, lib as lib
from pyscf.dft import libxc as libxc
from pyscf.dft.gen_grid import Grids as Grids
from pyscf.dft.numint import NumInt as NumInt
from pyscf.lib import logger as logger
from pyscf.mcpdft import pdft_eff as pdft_eff, pdft_feff as pdft_feff, pdft_veff as pdft_veff, tfnal_derivs as tfnal_derivs
from pyscf.mcpdft.otpd import get_ontop_pair_density as get_ontop_pair_density

FT_R0: Incomplete
FT_R1: Incomplete
FT_A: Incomplete
FT_B: Incomplete
FT_C: Incomplete
OT_ALIAS: Incomplete
OT_HYB_ALIAS: Incomplete
REG_OT_FUNCTIONALS: Incomplete
OT_PRESET: Incomplete

def register_otfnal(xc_code, preset) -> None: ...
def unregister_otfnal(xc_code) -> None: ...
def energy_ot(ot, casdm1s, casdm2, mo_coeff, ncore, max_memory: int = 2000, hermi: int = 1): ...

class otfnal:
    mol: Incomplete
    verbose: Incomplete
    stdout: Incomplete
    def __init__(self, mol) -> None: ...
    Pi_deriv: int
    @property
    def xctype(self): ...
    @property
    def dens_deriv(self): ...
    def eval_ot(self, rho, Pi, dderiv: int = 0, **kwargs) -> None: ...
    energy_ot = energy_ot
    get_eff_1body = pdft_eff.get_eff_1body
    get_eff_2body = pdft_eff.get_eff_2body
    get_eff_2body_kl = pdft_eff.get_eff_2body_kl
    get_veff_1body = pdft_veff.get_veff_1body
    get_veff_2body = pdft_veff.get_veff_2body
    get_veff_2body_kl = pdft_veff.get_veff_2body_kl
    get_feff_1body = pdft_feff.get_feff_1body
    get_feff_2body = pdft_feff.get_feff_2body
    def reset(self, mol=None) -> None: ...

class transfnal(otfnal):
    __doc__: Incomplete
    transl_prefix: str
    otxc: Incomplete
    grids: Incomplete
    def __init__(self, ks, **kwargs) -> None: ...
    def get_ratio(self, Pi, rho_avg): ...
    def get_rho_translated(self, Pi, rho, _fn_deriv: int = 0): ...
    def get_zeta(self, R, fn_deriv: int = 0, _Rmax: int = 1): ...
    def split_x_c(self): ...
    def jT_op(self, x, rho, Pi): ...
    def d_jT_op(self, x, rho, Pi): ...
    def eval_ot(self, rho, Pi, dderiv: int = 1, weights=None, _unpack_vot: bool = True): ...

class ftransfnal(transfnal):
    __doc__: Incomplete
    transl_prefix: str
    R0: Incomplete
    R1: Incomplete
    A: Incomplete
    B: Incomplete
    C: Incomplete
    otxc: Incomplete
    grids: Incomplete
    def __init__(self, ks, **kwargs) -> None: ...
    Pi_deriv: Incomplete
    def get_rho_translated(self, Pi, rho): ...
    def get_zeta(self, R, fn_deriv: int = 1): ...
    def jT_op(self, x, rho, Pi, **kwargs): ...
    def d_jT_op(self, x, rho, Pi, **kwargs): ...

def get_transfnal(mol, otxc): ...

class colle_salvetti_corr(otfnal):
    otxc: str
    grids: Incomplete
    CS_a: Incomplete
    CS_b: Incomplete
    CS_c: Incomplete
    CS_d: Incomplete
    def __init__(self, mol, **kwargs) -> None: ...
    def get_E_ot(self, rho, Pi, weights): ...

def make_scaled_fnal(xc_code, hyb_x: int = 0, hyb_c: int = 0, fnal_x=None, fnal_c=None): ...
def make_hybrid_fnal(xc_code, hyb, hyb_type: int = 1): ...

__t_doc__: str
__ft_doc__: str

def t_hybrid_coeff(ni, xc_code, spin: int = 0): ...
def t_nlc_coeff(ni, xc_code): ...
def t_rsh_coeff(ni, xc_code): ...
def t_eval_xc(ni, xc_code, rho, spin: int = 0, relativity: int = 0, deriv: int = 1, verbose=None): ...
def t_xc_type(ni, xc_code): ...
def t_rsh_and_hybrid_coeff(ni, xc_code, spin: int = 0): ...
def ft_hybrid_coeff(ni, xc_code, spin: int = 0): ...
def ft_nlc_coeff(ni, xc_code): ...
def ft_rsh_coeff(ni, xc_code): ...
def ft_eval_xc(ni, xc_code, rho, spin: int = 0, relativity: int = 0, deriv: int = 1, verbose=None): ...
def ft_xc_type(ni, xc_code): ...
def ft_rsh_and_hybrid_coeff(ni, xc_code, spin: int = 0): ...
