from pyscf.lib import logger as logger

def get_ontop_pair_density(ot, rho, ao, cascm2, mo_cas, deriv: int = 0, non0tab=None): ...
def density_orbital_derivative(ot, ncore, ncas, casdm1s, cascm2, rho, mo, deriv: int = 0, non0tab=None): ...
