from pyscf.dft.gen_grid import BLKSIZE as BLKSIZE
from pyscf.lib import current_memory as current_memory, logger as logger, tag_array as tag_array
from pyscf.mcpdft.otpd import get_ontop_pair_density as get_ontop_pair_density
from pyscf.mcpdft.tfnal_derivs import contract_fot as contract_fot
from numpy import ndarray
from pyscf.lib.numpy_helper import NPArrayWithTag
from pyscf.mcpdft.otfnal import ftransfnal, transfnal
from pyscf.mcpdft.pdft_eff import _ERIS
from typing import Tuple, Union

def kernel(ot: Union[ftransfnal, transfnal], dm1s: NPArrayWithTag, cascm2: ndarray, c_dm1s: NPArrayWithTag, c_cascm2: ndarray, mo_coeff: ndarray, ncore: int, ncas: int, max_memory: int = 2000, hermi: int = 1, paaa_only: bool = False, aaaa_only: bool = False, jk_pc: bool = False, delta: bool = False) -> Tuple[ndarray, _ERIS]: ...
def lazy_kernel(ot: Union[ftransfnal, transfnal], dm1s: NPArrayWithTag, cascm2: ndarray, c_dm1s: NPArrayWithTag, c_cascm2: ndarray, mo_cas: ndarray, hermi: int = 1, max_memory: int = 2000, delta: bool = False) -> Tuple[ndarray, ndarray]: ...
def get_feff_1body(otfnal, rho, Pi, crho, cPi, ao, weight, kern=None, non0tab=None, shls_slice=None, ao_loc=None, hermi: int = 0, **kwargs): ...
def get_feff_2body(otfnal, rho, Pi, crho, cPi, ao, weight, aosym: str = 's4', kern=None, fao=None, **kwargs): ...
def get_feff_2body_kl(otfnal, rho, Pi, crho, cPi, ao_k, ao_l, weight, symm: bool = False, kern=None, **kwargs): ...
