from pyscf.dft.gen_grid import BLKSIZE as BLKSIZE
from pyscf.lib import current_memory as current_memory, logger as logger, tag_array as tag_array
from pyscf.mcpdft.otpd import get_ontop_pair_density as get_ontop_pair_density

def kernel(ot, dm1s, cascm2, mo_coeff, ncore, ncas, max_memory: int = 2000, hermi: int = 1, paaa_only: bool = False, aaaa_only: bool = False, jk_pc: bool = False): ...
def lazy_kernel(ot, dm1s, cascm2, mo_cas, max_memory: int = 2000, hermi: int = 1, veff2_mo=None): ...
def get_veff_1body(otfnal, rho, Pi, ao, weight, kern=None, non0tab=None, shls_slice=None, ao_loc=None, hermi: int = 0, **kwargs): ...
def get_veff_2body(otfnal, rho, Pi, ao, weight, aosym: str = 's4', kern=None, vao=None, **kwargs): ...
def get_veff_2body_kl(otfnal, rho, Pi, ao_k, ao_l, weight, symm: bool = False, kern=None, **kwargs): ...
