from pyscf.lib import logger as logger
from numpy import ndarray
from pyscf.mcpdft.otfnal import ftransfnal, transfnal
from typing import Callable, List, Optional, Tuple, Union

def eval_ot(otfnal: Union[transfnal, ftransfnal], rho: ndarray, Pi: ndarray, dderiv: int = 1, weights: Optional[ndarray]=None, _unpack_vot: bool = True) -> Union[Tuple[ndarray, Tuple[ndarray, ndarray], None], Tuple[ndarray, None, None], Tuple[ndarray, ndarray, ndarray]]: ...
def unpack_vot(packed, rho, Pi): ...
def contract_vot(vot, rho, Pi): ...
def contract_fot(otfnal: Union[transfnal, ftransfnal], fot: ndarray, rho0: ndarray, Pi0: ndarray, rho1: ndarray, Pi1: ndarray, unpack: bool = True, vot_packed: Optional[ndarray]=None) -> Tuple[ndarray, ndarray]: ...
