from pyscf.lib import logger as logger

def eval_ot(otfnal, rho, Pi, dderiv: int = 1, weights=None, _unpack_vot: bool = True): ...
def unpack_vot(packed, rho, Pi): ...
def contract_vot(vot, rho, Pi): ...
def contract_fot(otfnal, fot, rho0, Pi0, rho1, Pi1, unpack: bool = True, vot_packed=None): ...
