from pyscf.fci import direct_spin1 as direct_spin1

def fock_h1e_for_cas(mc, sa_casdm1, mo_coeff=None, ncas=None, ncore=None): ...
def make_fock_mcscf(mc, mo_coeff=None, ci=None, weights=None): ...
def diagonalize_safock(mc, mo_coeff=None, ci=None): ...
def safock_energy(mc, **kwargs): ...
def solve_safock(mc, mo_coeff=None, ci=None): ...
