import pyscf.pbc.cc.kccsd_rhf
from _typeshed import Incomplete
from pyscf import lib as lib
from pyscf.lib import logger as logger
from pyscf.lib.linalg_helper import eig as eig
from pyscf.lib.numpy_helper import cartesian_prod as cartesian_prod
from pyscf.lib.parameters import LARGE_DENOM as LARGE_DENOM, LOOSE_ZERO_TOL as LOOSE_ZERO_TOL
from pyscf.pbc.cc.eom_kccsd_ghf import mask_frozen_ea as mask_frozen_ea, mask_frozen_ip as mask_frozen_ip
from pyscf.pbc.lib import kpts_helper as kpts_helper
from pyscf.pbc.lib.linalg_helper import eigs as eigs
from pyscf.pbc.mp.kmp2 import get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc, padded_mo_coeff as padded_mo_coeff, padding_k_idx as padding_k_idx
from pyscf.pbc.mpicc import mpi_kpoint_helper as mpi_kpoint_helper
from pyscf.pbc.mpitools import mpi as mpi, mpi_load_balancer as mpi_load_balancer
from pyscf.pbc.mpitools.mpi_helper import generate_max_task_list as generate_max_task_list, safeAllreduceInPlace as safeAllreduceInPlace, safeBcastInPlace as safeBcastInPlace, safeNormDiff as safeNormDiff
from pyscf.pbc.tools.tril import tril_index as tril_index, unpack_tril as unpack_tril

einsum = lib.einsum
rank: Incomplete
size: Incomplete
comm: Incomplete

def read_amplitudes(t1_shape, t2_shape, t1=None, t2=None, filename: str = 't_amplitudes.hdf5'): ...
def write_amplitudes(t1, t2, filename: str = 't_amplitudes.hdf5') -> None: ...
def read_eom_amplitudes(vec_shape, filename: str = 'reom_amplitudes.hdf5', vec=None): ...
def write_eom_amplitudes(vec, filename: str = 'reom_amplitudes.hdf5') -> None: ...
def restore_from_diis_(mycc, diis_file, inplace: bool = True): ...
def get_normt_diff(cc, t1, t2, t1new, t2new): ...
def update_t1(cc, t1, t2, eris, ints1e): ...
def update_amps(cc, t1, t2, eris, max_memory: int = 2000): ...
def energy(cc, t1, t2, eris): ...
def energy_tril(cc, t1, t2, eris): ...

class RCCSD(pyscf.pbc.cc.kccsd_rhf.RCCSD):
    kconserv: Incomplete
    __imds__: Incomplete
    def __init__(self, mf, frozen=None, mo_coeff=None, mo_occ=None) -> None: ...
    def init_amps(self, eris): ...
    get_normt_diff = get_normt_diff
    def energy(self, t1, t2, eris): ...
    def ao2mo(self, mo_coeff=None): ...
    def update_amps(self, t1, t2, eris, max_memory: int = 2000): ...
    made_ip_imds: bool
    def ipccsd_diag(self): ...
    kshift: Incomplete
    def ipccsd(self, nroots=..., kptlist=None): ...
    restore_from_diis_ = restore_from_diis_
    def run_diis(self, t1, t2, istep, normt, de, adiis): ...
    def ipccsd_matvec(self, vector): ...
    def lipccsd(self, nroots=..., kptlist=None): ...
    def lipccsd_matvec(self, vector): ...
    def vector_size_ip(self): ...
    mask_frozen_ip = mask_frozen_ip
    def vector_to_amplitudes_ip(self, vector): ...
    def amplitudes_to_vector_ip(self, r1, r2): ...
    def ipccsd_star_contract(self, ipccsd_evals, ipccsd_evecs, lipccsd_evecs): ...
    made_ea_imds: bool
    def eaccsd_diag(self): ...
    def eaccsd(self, nroots=..., kptlist=None): ...
    def eaccsd_matvec(self, vector): ...
    def leaccsd(self, nroots=..., kptlist=None): ...
    def leaccsd_matvec(self, vector): ...
    def vector_size_ea(self): ...
    mask_frozen_ea = mask_frozen_ea
    def vector_to_amplitudes_ea(self, vector): ...
    def amplitudes_to_vector_ea(self, r1, r2): ...
    def eaccsd_star_contract(self, eaccsd_evals, eaccsd_evecs, leaccsd_evecs): ...
    def amplitudes_to_vector(self, t1, t2): ...
    def vector_to_amplitudes(self, vec, nmo=None, nocc=None): ...
    @property
    def imds(self): ...

class _ERIS:
    fock: Incomplete
    mo_energy: Incomplete
    dtype: Incomplete
    oooo: Incomplete
    ooov: Incomplete
    ovoo: Incomplete
    oovv: Incomplete
    ovov: Incomplete
    ovvv: Incomplete
    vvvv: Incomplete
    feri1: Incomplete
    ovvo: Incomplete
    voov: Incomplete
    vovv: Incomplete
    ovovL1: Incomplete
    ooovL1: Incomplete
    voovR1: Incomplete
    ooovR1: Incomplete
    vovvR1: Incomplete
    vovvL1: Incomplete
    ovovRev: Incomplete
    ooovRev: Incomplete
    ovvvRev: Incomplete
    def __init__(self, cc, mo_coeff=None, method: str = 'incore') -> None: ...
    def __del__(self) -> None: ...
CCSD = RCCSD

class _IMDS:
    def __init__(self, cc) -> None: ...
    fint1: Incomplete
    Wooov: Incomplete
    Woooo: Incomplete
    WooooS: Incomplete
    W1voov: Incomplete
    W2voov: Incomplete
    Wvoov: Incomplete
    W1ovov: Incomplete
    W2ovov: Incomplete
    Wovov: Incomplete
    Wovoo: Incomplete
    Lvv: Incomplete
    Loo: Incomplete
    Fov: Incomplete
    Woovv: Incomplete
    def make_ip(self, cc) -> None: ...
    def close_ip(self, cc) -> None: ...
    def __del__(self) -> None: ...
    fint2: Incomplete
    Wvovv: Incomplete
    WvoovR1: Incomplete
    Wvvvv: Incomplete
    WovovRev: Incomplete
    WvvvoR1: Incomplete
    def make_ea(self, cc) -> None: ...
