from _typeshed import Incomplete
from pyscf import lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc.mpitools import mpi_load_balancer as mpi_load_balancer
from pyscf.pbc.tools.tril import tril_index as tril_index, unpack_tril as unpack_tril

comm: Incomplete
einsum = lib.einsum
dot: Incomplete

def cc_tau1(cc, t1, t2, eris, feri2=None) -> None: ...
def cc_Foo(cc, t1, t2, eris, feri2=None): ...
def cc_Fvv(cc, t1, t2, eris, feri2=None): ...
def cc_Fov(cc, t1, t2, eris, feri2=None): ...
def Loo(cc, t1, t2, eris, feri2=None): ...
def Lvv(cc, t1, t2, eris, feri2=None): ...
def cc_Woooo(cc, t1, t2, eris, feri2=None) -> None: ...
def cc_Wvvvv(cc, t1, t2, eris, feri2=None) -> None: ...
def cc_Wvoov(cc, t1, t2, eris, feri2=None) -> None: ...
def cc_Wvovo(cc, t1, t2, eris, feri2=None) -> None: ...
def cc_Wovov(cc, t1, t2, eris, feri2=None) -> None: ...
def Wooov(cc, t1, t2, eris, fint=None): ...
def Wvovv(cc, t1, t2, eris, fint=None): ...
def W1ovvo(cc, t1, t2, eris, fint=None): ...
def W2ovvo(cc, t1, t2, eris, fint=None): ...
def Wovvo(cc, t1, t2, eris, fint=None): ...
def W1ovov(cc, t1, t2, eris, fint=None): ...
def W2ovov(cc, t1, t2, eris, fint=None): ...
def Wovov(cc, t1, t2, eris, fint=None): ...
def WovovRev(cc, t1, t2, eris, fint=None): ...
def Woooo(cc, t1, t2, eris, fint=None): ...
def WooooS(cc, t1, t2, eris, fint=None): ...
def Wvvvv(cc, t1, t2, eris, fint=None): ...
def Wvvvo(cc, t1, t2, eris, fint=None): ...
def WvvvoR1(cc, t1, t2, eris, fint=None): ...
def Wovoo(cc, t1, t2, eris, fint=None): ...
def W1voov(cc, t1, t2, eris, fint=None): ...
def W2voov(cc, t1, t2, eris, fint=None): ...
def Wvoov(cc, t1, t2, eris, fint=None): ...
def WvoovR1(cc, t1, t2, eris, fint=None): ...
