from _typeshed import Incomplete
from pyscf.pbc.lib import kpts_helper as kpts_helper

DEBUG: int

class unique_pqr_list:
    operations: Incomplete
    equivalentList: Incomplete
    nUnique: int
    uniqueList: Incomplete
    def __init__(self, cell, kpts) -> None: ...
    def get_uniqueList(self): ...
    def get_irrVec(self, kp, kq, kr): ...
    def get_transformation(self, kp, kq, kr): ...
    def transform_irr2full(self, invec, kp, kq, kr): ...
