import abc
import numpy as np
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from pyscf.lib import chkfile as chkfile, logger as logger

class AC_Method(ABC, metaclass=abc.ABCMeta):
    shape: Incomplete
    def __init__(self, *args, **options) -> None: ...
    @abstractmethod
    def ac_fit(self, data: np.ndarray, omega: np.ndarray, axis: int = -1): ...
    @abstractmethod
    def ac_eval(self, freqs: np.ndarray, axis: int = -1): ...
    @abstractmethod
    def __getitem__(self, multiidx: tuple[int] | slice): ...
    @abstractmethod
    def diagonal(self, axis1: int = 0, axis2: int = 1): ...
    def save(self, chkfilename: str, dataname: str = 'ac'): ...

def load_ac(chkfilename: str, dataname: str = 'ac') -> AC_Method: ...
def pade_thiele_ndarray(freqs, zn, coeff): ...
def thiele_ndarray(fn, zn): ...

class PadeAC(AC_Method):
    step_ratio: Incomplete
    npts: Incomplete
    coeff: Incomplete
    omega: Incomplete
    idx: Incomplete
    def __init__(self, *args, npts: int = 18, step_ratio=..., **options) -> None: ...
    @property
    def omega_fit(self): ...
    shape: Incomplete
    def ac_fit(self, data, omega, axis: int = -1) -> None: ...
    def ac_eval(self, freqs, axis: int = -1): ...
    def __getitem__(self, multi_idx): ...
    def diagonal(self, axis1: int = 0, axis2: int = 1): ...

def AC_pade_thiele_diag(sigma, omega, npts: int = 18, step_ratio=...): ...
def AC_pade_thiele_full(sigma, omega, npts: int = 18, step_ratio=...): ...

class TwoPoleAC(AC_Method):
    coeff: Incomplete
    omega: Incomplete
    orbs: Incomplete
    nocc: Incomplete
    def __init__(self, orbs, nocc, **options) -> None: ...
    shape: Incomplete
    def ac_fit(self, data, omega, axis: int = -1) -> None: ...
    def ac_eval(self, freqs, axis: int = -1): ...
    def __getitem__(self, multi_idx): ...
    def diagonal(self, axis1: int = 0, axis2: int = 1): ...

def two_pole_fit(coeff, omega, sigma): ...
def two_pole(freqs, coeff): ...
