def array_scale(arr, alpha) -> None: ...
def addto_diagonal(arr, x): ...
def get_id_minus_pi(Pi): ...
def get_id_minus_pi_inv(Pi, overwrite_input: bool = False): ...
def get_id_minus_pi_inv_minus_id(Pi, overwrite_input: bool = False): ...
def mkslice(l): ...
