from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc import df as df, dft as dft, scf as scf
from pyscf.pbc.mp.kmp2 import get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc

einsum = lib.einsum

def kernel(gw, mo_energy, mo_coeff, orbs=None, kptlist=None, nw=None, verbose=...): ...
def get_rho_response(gw, omega, mo_energy, Lpq, kL, kidx): ...
def get_sigma_diag(gw, orbs, kptlist, freqs, wts, iw_cutoff=None, max_memory: int = 8000): ...
def get_rho_response_head(gw, omega, mo_energy, qij): ...
def get_rho_response_wing(gw, omega, mo_energy, Lpq, qij): ...
def get_qij(gw, q, mo_coeff, uniform_grids: bool = False): ...
def two_pole_fit(coeff, omega, sigma): ...
def two_pole(freqs, coeff): ...
def AC_twopole_diag(sigma, omega, orbs, nocc): ...
def thiele(fn, zn): ...
def pade_thiele(freqs, zn, coeff): ...
def AC_pade_thiele_diag(sigma, omega): ...

class KRGWAC(lib.StreamObject):
    linearized: Incomplete
    ac: Incomplete
    fc: Incomplete
    mol: Incomplete
    verbose: Incomplete
    stdout: Incomplete
    max_memory: Incomplete
    frozen: Incomplete
    with_df: Incomplete
    kpts: Incomplete
    nkpts: Incomplete
    mo_energy: Incomplete
    mo_coeff: Incomplete
    mo_occ: Incomplete
    sigma: Incomplete
    def __init__(self, mf, frozen=None) -> None: ...
    def dump_flags(self): ...
    @property
    def nocc(self): ...
    @nocc.setter
    def nocc(self, n) -> None: ...
    @property
    def nmo(self): ...
    @nmo.setter
    def nmo(self, n) -> None: ...
    get_nocc = get_nocc
    get_nmo = get_nmo
    get_frozen_mask = get_frozen_mask
    def kernel(self, mo_energy=None, mo_coeff=None, orbs=None, kptlist=None, nw: int = 100): ...
