from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc import df as df, dft as dft, scf as scf
from pyscf.pbc.mp.kmp2 import get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc
from scipy.optimize import least_squares as least_squares
from numpy import complex128, float64, ndarray
from pyscf.pbc.dft.krks import KRKS
from typing import List, Optional, Tuple, Union

einsum = lib.einsum

def kernel(gw: "KRGWCD", mo_energy: ndarray, mo_coeff: ndarray, orbs: Optional[range]=None, kptlist: Optional[List[int]]=None, nw: Optional[int]=None, verbose: int=...) -> Tuple[bool, ndarray, ndarray]: ...
def get_sigma_diag(gw: "KRGWCD", ep: float64, kp: int, p: int, Wmn: ndarray, Del_00: Optional[ndarray], Del_P0: Optional[ndarray], freqs: ndarray, wts: ndarray, qij: Optional[ndarray], q_abs: Optional[ndarray]) -> complex128: ...
def get_rho_response(gw: "KRGWCD", omega: float64, mo_energy: ndarray, Lpq: ndarray, kL: int, kidx: ndarray) -> ndarray: ...
def get_WmnI_diag(gw: "KRGWCD", orbs: range, kptlist: List[int], freqs: ndarray, max_memory: int = 8000) -> Union[Tuple[ndarray, ndarray, ndarray, ndarray, ndarray], Tuple[ndarray, None, None, None, None]]: ...
def get_sigmaI_diag(gw: "KRGWCD", omega: float64, kp: int, p: int, Wmn: ndarray, Del_00: Optional[ndarray], Del_P0: Optional[ndarray], sign: ndarray, freqs: ndarray, wts: ndarray) -> complex128: ...
def get_rho_response_R(gw: "KRGWCD", omega: float64, mo_energy: ndarray, Lpq: ndarray, kL: int, kidx: ndarray) -> ndarray: ...
def get_sigmaR_diag(gw: "KRGWCD", omega: float64, kn: int, orbp: int, ef: float64, freqs: ndarray, qij: Optional[ndarray], q_abs: Optional[ndarray]) -> Union[complex128, complex]: ...
def get_rho_response_head_R(gw: "KRGWCD", omega: float64, mo_energy: ndarray, qij: ndarray) -> complex128: ...
def get_rho_response_wing_R(gw: "KRGWCD", omega: float64, mo_energy: ndarray, Lpq: ndarray, qij: ndarray) -> ndarray: ...
def get_rho_response_head(gw: "KRGWCD", omega: float64, mo_energy: ndarray, qij: ndarray) -> complex128: ...
def get_rho_response_wing(gw: "KRGWCD", omega: float64, mo_energy: ndarray, Lpq: ndarray, qij: ndarray) -> ndarray: ...
def get_qij(gw: "KRGWCD", q: ndarray, mo_coeff: ndarray, uniform_grids: bool = False) -> ndarray: ...

class KRGWCD(lib.StreamObject):
    linearized: Incomplete
    eta: Incomplete
    fc: Incomplete
    mol: Incomplete
    verbose: Incomplete
    stdout: Incomplete
    max_memory: Incomplete
    frozen: Incomplete
    with_df: Incomplete
    kpts: Incomplete
    nkpts: Incomplete
    mo_energy: Incomplete
    mo_coeff: Incomplete
    mo_occ: Incomplete
    sigma: Incomplete
    def __init__(self, mf: KRKS, frozen: None=None) -> None: ...
    def dump_flags(self) -> "KRGWCD": ...
    @property
    def nocc(self): ...
    @nocc.setter
    def nocc(self, n) -> None: ...
    @property
    def nmo(self): ...
    @nmo.setter
    def nmo(self, n) -> None: ...
    get_nocc = get_nocc
    get_nmo = get_nmo
    get_frozen_mask = get_frozen_mask
    def kernel(self, mo_energy: None=None, mo_coeff: None=None, orbs: Optional[range]=None, kptlist: Optional[List[int]]=None, nw: int = 100) -> ndarray: ...
