from _typeshed import Incomplete
from pyscf import __config__ as __config__, lib as lib
from pyscf.lib import logger as logger
from pyscf.pbc import df as df, dft as dft, scf as scf
from pyscf.pbc.cc.kccsd_uhf import get_frozen_mask as get_frozen_mask, get_nmo as get_nmo, get_nocc as get_nocc
from numpy import complex128, float64, ndarray
from pyscf.pbc.scf.kuhf import KUHF
from typing import List, Optional, Tuple

einsum = lib.einsum

def kernel(gw: "KUGWAC", mo_energy: ndarray, mo_coeff: ndarray, orbs: Optional[range]=None, kptlist: Optional[List[int]]=None, nw: Optional[int]=None, verbose: int=...) -> Tuple[bool, ndarray, ndarray]: ...
def get_rho_response(gw: "KUGWAC", omega: float64, mo_energy: ndarray, Lpq: ndarray, kL: int, kidx: ndarray) -> ndarray: ...
def get_sigma_diag(gw: "KUGWAC", orbs: range, kptlist: List[int], freqs: ndarray, wts: ndarray, iw_cutoff: Optional[float]=None, max_memory: int = 8000) -> Tuple[ndarray, ndarray]: ...
def get_rho_response_head(gw: "KUGWAC", omega: float64, mo_energy: ndarray, qij: Tuple[ndarray, ndarray]) -> complex128: ...
def get_rho_response_wing(gw: "KUGWAC", omega: float64, mo_energy: ndarray, Lpq: ndarray, qij: Tuple[ndarray, ndarray]) -> ndarray: ...
def get_qij(gw: "KUGWAC", q: ndarray, mo_coeff: ndarray, uniform_grids: bool = False) -> Tuple[ndarray, ndarray]: ...
def two_pole_fit(coeff, omega, sigma): ...
def two_pole(freqs, coeff): ...
def AC_twopole_diag(sigma, omega, orbs, nocc): ...
def thiele(fn: ndarray, zn: ndarray) -> ndarray: ...
def pade_thiele(freqs: float64, zn: ndarray, coeff: ndarray) -> complex128: ...
def AC_pade_thiele_diag(sigma: ndarray, omega: ndarray) -> Tuple[ndarray, ndarray]: ...

class KUGWAC(lib.StreamObject):
    linearized: Incomplete
    ac: Incomplete
    fc: Incomplete
    mol: Incomplete
    verbose: Incomplete
    stdout: Incomplete
    max_memory: Incomplete
    frozen: Incomplete
    with_df: Incomplete
    kpts: Incomplete
    nkpts: Incomplete
    mo_energy: Incomplete
    mo_coeff: Incomplete
    mo_occ: Incomplete
    sigma: Incomplete
    def __init__(self, mf: KUHF, frozen: None=None) -> None: ...
    def dump_flags(self) -> "KUGWAC": ...
    @property
    def nocc(self): ...
    @nocc.setter
    def nocc(self, n) -> None: ...
    @property
    def nmo(self): ...
    @nmo.setter
    def nmo(self, n) -> None: ...
    get_nocc = get_nocc
    get_nmo = get_nmo
    get_frozen_mask = get_frozen_mask
    def kernel(self, mo_energy: None=None, mo_coeff: None=None, orbs: Optional[range]=None, kptlist: Optional[List[int]]=None, nw: int = 100) -> ndarray: ...
